
#配置文件路径
conf.path=/home/tonlan/bjts/etc/yj.ini

#格式采用：/目录/模块名
logging.path=/mnt/logs/bjts/inner


#session共享
#spring.redis.host=80.16.52.206
#spring.redis.port=7777
#spring.redis.password=Tlsoft@Redis2019

spring.redis.host=80.16.64.236
spring.redis.port=6377
spring.redis.password=ZTsoft$zjsw202207#keY
spring.redis.timeout=2000

#数据库
#金三数据源
jsxt.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
jsxt.jdbc.url =jdbc:oracle:thin:@80.12.73.67:1521:zjswhxcx2
jsxt.jdbc.username=zj_bjts
jsxt.jdbc.password=hxcx#Ei6y1h
jsxt.jdbc.filters=stat,slf4j,wall

#tl_admin用户
tladmin.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
tladmin.jdbc.url =jdbc:oracle:thin:@80.16.50.90:1521:bjts1
tladmin.jdbc.username=tl_admin
tladmin.jdbc.password=Bjts#H362rQ
tladmin.jdbc.filters=stat


tltssh.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
tltssh.jdbc.url =jdbc:oracle:thin:@80.16.50.90:1521:bjts1
tltssh.jdbc.username=tl_tssh
tltssh.jdbc.password=Bjts#s4pMg4
tltssh.jdbc.filters=stat,slf4j

#电子底账
dzdz.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
dzdz.jdbc.url =jdbc:oracle:thin:@80.12.96.41:1521:dzdzcx1
dzdz.jdbc.username=bjts_tl
dzdz.jdbc.password=dzdz#aJm86W
dzdz.jdbc.filters=stat

#数字电票自建
szdp.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
szdp.jdbc.url =jdbc:oracle:thin:@80.12.73.125:1521:dzswjyt1
szdp.jdbc.username=bjts_cx
szdp.jdbc.password=cx_123645
szdp.jdbc.filters=stat