#配置文件路径
#配置文件路径
#conf.path=D:\\tlweb\\bjts\\yj\\etc
#
##格式采用：/目录/模块名
#logging.path=D:\\tlweb\\bjts\\logger

conf.path=/home/tonlan/logs/inner
#格式采用：/目录/模块名
logging.path=/home/tonlan/logs/inner/web/

#spring.redis.host=80.12.136.178
#spring.redis.port=6377
#spring.redis.password=redis@tonlan#202008
#
##数据库
#jsxt.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
#jsxt.jdbc.url =jdbc:oracle:thin:@80.12.73.115:1521:zjswhxcx
#jsxt.jdbc.username=ZJ_WBCX
#jsxt.jdbc.password=cx123
#jsxt.jdbc.filters=stat
#
##tl_admin用户
#tladmin.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
#tladmin.jdbc.url =jdbc:oracle:thin:@80.16.52.208:1521:bjts
#tladmin.jdbc.username=tl_admin
#tladmin.jdbc.password=Bjts#H362rQ
#tladmin.jdbc.filters=stat

spring.redis.host=80.64.64.22
spring.redis.port=6379

#数据库
#金三数据源
jsxt.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
jsxt.jdbc.url =jdbc:oracle:thin:@80.64.64.8:1521:ckts
jsxt.jdbc.username=zj_bjts
jsxt.jdbc.password=ztsoft
jsxt.jdbc.filters=stat,slf4j,wall

#tl_admin用户
tladmin.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
tladmin.jdbc.url =jdbc:oracle:thin:@80.64.64.8:1521:ckts
tladmin.jdbc.username=tl_admin
tladmin.jdbc.password=tlsoft
tladmin.jdbc.filters=stat

#电子抵账数据源
dzdz.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
dzdz.jdbc.url =jdbc:oracle:thin:@80.64.64.8:1521:ckts
dzdz.jdbc.username=bjts_tl
dzdz.jdbc.password=ztsoft
dzdz.jdbc.filters=stat

#数电查询库
szdp.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
szdp.jdbc.url =jdbc:oracle:thin:@80.64.64.8:1521:ckts
szdp.jdbc.username=bjts_cx
szdp.jdbc.password=cx_123645
szdp.jdbc.filters=stat

tltssh.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
tltssh.jdbc.url =jdbc:oracle:thin:@80.64.64.8:1521:ckts
tltssh.jdbc.username=tl_tssh
tltssh.jdbc.password=tlsoft
tltssh.jdbc.filters=stat


#logging.level.com.tl.web.bjts.yj.dao=debug
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
