
#配置文件路径
conf.path=D:\\tlweb\\bjts\\yj\\etc

#格式采用：/目录/模块名
logging.path=D:\\tlweb\\bjts\\logger

spring.redis.host=80.64.64.84
spring.redis.port=7777

#数据库
#金三数据源
jsxt.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
jsxt.jdbc.url =jdbc:oracle:thin:@80.64.64.8:1521:ckts
jsxt.jdbc.username=tssh
jsxt.jdbc.password=tssh
jsxt.jdbc.filters=stat,slf4j,wall

#tl_admin用户
tladmin.jdbc.driverClassName =oracle.jdbc.driver.OracleDriver
tladmin.jdbc.url =jdbc:oracle:thin:@80.64.64.8:1521:ckts
tladmin.jdbc.username=tl_admin
tladmin.jdbc.password=tlsoft
tladmin.jdbc.filters=stat


