DELIMITER $$

DROP PROCEDURE IF EXISTS FUNC_GET_XJ_SWJG$$

CREATE PROCEDURE func_get_xj_swjg(IN P_SJ_SWCODE VARCHAR(4000))
routine_body: BEGIN
    IF SUBSTR(P_SJ_SWCODE, 1, 1) = '2' THEN
        SELECT VIR_SWJGDM AS SWJG_DM
          FROM DM_SWJG_VIRTUAL
         WHERE SWJG_DM = P_SJ_SWCODE
           AND YXBZ = 'Y'
           AND VIR_FLAG = '0';
    ELSE
        SELECT SWJG_DM AS SWJG_DM
          FROM DM_SWJG
         WHERE SWJG_DM_SJ = P_SJ_SWCODE
           AND TSJG_BZ = '1';
    END IF;
END$$

DELIMITER ;
