DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03105_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03105_CSH_NEW
/*************************************************
 * 浙江省出口商品退税率分布情况统计表
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);--当月
  DECLARE LC_THISYEAR      VARCHAR(6);--当年1月
  DECLARE LC_LASTMONTH     VARCHAR(6);--上年同期
  DECLARE LC_LASTYEAR      VARCHAR(6);--上年1月
  
  DECLARE LN_CKE_THIS      DECIMAL(16,4);--本年出口额合计
  DECLARE LN_TSE_THIS      DECIMAL(16,4);--本年退税额合计
  DECLARE LN_CKE_LAST      DECIMAL(16,4);--上年出口额合计
  DECLARE LN_TSE_LAST      DECIMAL(16,4);--上年退税额合计
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;
  
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_THISYEAR =DATE_FORMAT(LD_SYSDATE, '%Y')||'01';
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');
  SET LC_LASTYEAR =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y')||'01';
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03105 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、计算并插入本年明细
  BEGIN
    INSERT INTO TJBB_DT_B03105 (SSNY,BBLC,SWJGDM,CKE_YEAR,TSE_YEAR,CKE_YEAR_LAST,TSE_YEAR_LAST)
      WITH FL_TSLV AS (SELECT XMFL, 
                              SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN USD_AMT ELSE 0 END)/10000 AS USD_AMT, 
                              SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN TS_AMT  ELSE 0 END)/10000 AS TS_AMT, 
                              SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN USD_AMT ELSE 0 END)/10000 AS USD_AMT_LAST, 
                              SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN TS_AMT  ELSE 0 END)/10000 AS TS_AMT_LAST
                         FROM TJBB_FHXX_TSLV
                        WHERE SWCODE=V_SWCODE 
                          AND ((SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH) OR (SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH))
                        GROUP BY XMFL)
    SELECT LC_THISMONTH, A.BBLC, V_SWCODE, 
           ROUND(SUM(C.USD_AMT),0), ROUND(SUM(C.TS_AMT),0), ROUND(SUM(C.USD_AMT_LAST),0), ROUND(SUM(C.TS_AMT_LAST),0)
      FROM DM_TSL_BB03105 A
      LEFT JOIN FL_TSLV C ON C.XMFL = A.TSLV
      GROUP BY A.BBLC;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;
  
  --2、计算并插入合计数
  BEGIN
    SELECT SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN USD_AMT ELSE 0 END)/10000 AS USD_AMT, 
           SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN TS_AMT  ELSE 0 END)/10000 AS TS_AMT, 
           SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN USD_AMT ELSE 0 END)/10000 AS USD_AMT_LAST, 
           SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN TS_AMT  ELSE 0 END)/10000 AS TS_AMT_LAST
      INTO LN_CKE_THIS, LN_TSE_THIS, LN_CKE_LAST, LN_TSE_LAST
      FROM TJBB_FHXX_TSLV
     WHERE SWCODE=V_SWCODE 
       AND ((SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH) OR (SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH));

    INSERT INTO TJBB_DT_B03105 (SSNY,BBLC,SWJGDM,CKE_YEAR,TSE_YEAR, CKE_YEAR_LAST, TSE_YEAR_LAST)
    SELECT LC_THISMONTH, '01', V_SWCODE,
           ROUND(LN_CKE_THIS,0), ROUND(LN_TSE_THIS,0), ROUND(LN_CKE_LAST,0), ROUND(LN_TSE_LAST,0)
;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;
  
  --3、同比计算
  BEGIN
    UPDATE TJBB_DT_B03105
       SET CKE_TB = CASE WHEN IFNULL(CKE_YEAR_LAST, 0)=0 THEN NULL ELSE ROUND(100 * CKE_YEAR / CKE_YEAR_LAST -100,1) END,
           TSE_TB = CASE WHEN IFNULL(TSE_YEAR_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TSE_YEAR / TSE_YEAR_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --4、占比计算
  BEGIN
    UPDATE TJBB_DT_B03105 T
       SET CKE_ZB = CASE WHEN IFNULL(LN_CKE_THIS, 0)=0 THEN NULL ELSE ROUND(100 * CKE_YEAR / LN_CKE_THIS,1) END,
           TSE_ZB = CASE WHEN IFNULL(LN_TSE_THIS, 0)=0 THEN NULL ELSE ROUND(100 * TSE_YEAR / LN_TSE_THIS,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --5、汇总栏初始化
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03105 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03105' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
