DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B05102_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B05102_HZ_NEW
/**************************************************************
 * 跨境电商统计表——无票免税情况表（省、市局汇总）
 **************************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B05102 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、统计
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;
      LEAVE routine_body;

  END;
INSERT INTO TJBB_DT_B05102 (
           SSNY,BBLC,SWJGDM,QJNY,
           KJLS_CKE_HS, KJLS_CKE_HS_HZ, KJLS_CKE_JE, KJLS_CKE_JE_HZ,
           KJLS_TMS_HS, KJLS_TMS_HS_HZ, KJLS_TMS_JE, KJLS_TMS_JE_HZ,
           WPMS_CKE_HS, WPMS_CKE_HS_HZ, WPMS_CKE_JE, WPMS_CKE_JE_HZ)
    SELECT LC_THISMONTH,BBLC,V_SWCODE,QJNY,
           SUM(KJLS_CKE_HS), SUM(KJLS_CKE_HS_HZ), SUM(KJLS_CKE_JE), SUM(KJLS_CKE_JE_HZ),
           SUM(KJLS_TMS_HS), SUM(KJLS_TMS_HS_HZ), SUM(KJLS_TMS_JE), SUM(KJLS_TMS_JE_HZ),
           SUM(WPMS_CKE_HS), SUM(WPMS_CKE_HS_HZ), SUM(WPMS_CKE_JE), SUM(WPMS_CKE_JE_HZ)
      FROM TJBB_DT_B05102
     WHERE SWJGDM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
       AND SSNY=LC_THISMONTH
     GROUP BY BBLC,QJNY;

    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
