DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B02101_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B02101_CSH_NEW
/*************************************************
 * 无纸化管理情况统计表
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;

  DECLARE LC_SWJGMC          VARCHAR(100);
  DECLARE TSFN_ALL           DECIMAL(18,6);
  DECLARE TSFN_WZH_YEAR      DECIMAL(18,6);
  DECLARE TSFN_WZH_MON       DECIMAL(18,6);

  DECLARE LN_BAHS_SC         BIGINT;
  DECLARE LN_BAHS_SC_ADD     BIGINT;
  DECLARE LN_BAHS_WM         BIGINT;
  DECLARE LN_BAHS_WM_ADD     BIGINT;
  DECLARE LN_SBHS_SC_MON     BIGINT;
  DECLARE LN_SBHS_SC_YEAR    BIGINT;
  DECLARE LN_SBHS_WM_MON     BIGINT;
  DECLARE LN_SBHS_WM_YEAR    BIGINT;
  DECLARE LN_QYHS_TMSE       BIGINT;
  DECLARE LN_WZHSB_TMSE_MON  DECIMAL(18,6);
  DECLARE LN_WZHBL_TMSE_MON  DECIMAL(18,6);
  DECLARE LN_WZHSB_TMSE_YEAR DECIMAL(18,6);
  DECLARE LN_WZHBL_TMSE_YEAR DECIMAL(18,6);
  DECLARE LN_SB_TMSE_HJ      DECIMAL(18,6);
  DECLARE LN_BL_TMSE_HJ      DECIMAL(18,6);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';
  
  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =TRUNCATE(LD_SYSDATE, 'YY');
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02101 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、计算列
  BEGIN
    --税务机关名称
    SELECT SWJG_JC
      INTO LC_SWJGMC
      FROM DM_SWJG
     WHERE SWJG_DM=V_SWCODE;
    --返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN S.WZHQY='1' THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN S.WZHQY='1' AND DATE_FORMAT(T.RKRQ, '%Y%m')=LC_THISMONTH THEN T.SJJE ELSE 0 END)/10000,6), 0)
      INTO TSFN_ALL, TSFN_WZH_YEAR, TSFN_WZH_MON
      FROM FG_CKTSFN_HXZG T
      LEFT JOIN GLXT_BB_SHXT_DJXX S ON T.CPCODE=S.CPCODE
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;
    --备案户数统计
    SELECT SUM(CASE WHEN T.WZHQY='1' AND T.JSMODE='1' THEN 1 ELSE 0 END),
           SUM(CASE WHEN T.WZHQY='1' AND T.JSMODE='1' AND T.SQ_DATE>=LD_THISYEAR THEN 1 ELSE 0 END),
           SUM(CASE WHEN T.WZHQY='1' AND T.JSMODE='2' THEN 1 ELSE 0 END),
           SUM(CASE WHEN T.WZHQY='1' AND T.JSMODE='2' AND T.SQ_DATE>=LD_THISYEAR THEN 1 ELSE 0 END)
      INTO LN_BAHS_SC, LN_BAHS_SC_ADD, LN_BAHS_WM, LN_BAHS_WM_ADD
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N';
    --申报户数、退免税额统计
    SELECT COUNT(DISTINCT CASE WHEN S.WZHQY='1' AND S.JSMODE='1' AND T.LCJSRQ>LD_SYSDATE THEN T.DJXH ELSE NULL END), 
           COUNT(DISTINCT CASE WHEN S.WZHQY='1' AND S.JSMODE='1' THEN T.DJXH ELSE NULL END), 
           COUNT(DISTINCT CASE WHEN S.WZHQY='1' AND S.JSMODE='2' AND T.LCJSRQ>LD_SYSDATE THEN T.DJXH ELSE NULL END), 
           COUNT(DISTINCT CASE WHEN S.WZHQY='1' AND S.JSMODE='2' THEN T.DJXH ELSE NULL END), 
           COUNT(DISTINCT T.DJXH),
           ROUND(IFNULL(SUM(CASE WHEN S.WZHQY='1' AND T.LCJSRQ>LD_SYSDATE THEN T.SB_MDTSE ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN S.WZHQY='1' THEN T.SB_MDTSE ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(T.SB_MDTSE), 0)/10000,6)
      INTO LN_SBHS_SC_MON, LN_SBHS_SC_YEAR, LN_SBHS_WM_MON, LN_SBHS_WM_YEAR, LN_QYHS_TMSE, LN_WZHSB_TMSE_MON, LN_WZHSB_TMSE_YEAR, LN_SB_TMSE_HJ
      FROM CKTS_LC_SHXX T
      LEFT JOIN GLXT_BB_SHXT_DJXX S ON T.DJXH=S.DJXH_JS
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.QDSJ<LD_NEXTMONTH
       AND T.LCJSRQ>=LD_THISYEAR;
    --办理退税额
    SELECT ROUND(IFNULL(SUM(CASE WHEN S.WZHQY='1' AND T.XHRQ_TK>LD_SYSDATE THEN T.GKBL_ZZSTSE+T.GKBL_XFSTSE ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN S.WZHQY='1' THEN T.GKBL_ZZSTSE+T.GKBL_XFSTSE ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_WZHBL_TMSE_MON, LN_WZHBL_TMSE_YEAR, LN_BL_TMSE_HJ
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN GLXT_BB_SHXT_DJXX S ON T.DJXH=S.DJXH_JS
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR
       AND T.XHRQ_TK<LD_NEXTMONTH;
    SELECT LN_WZHBL_TMSE_MON + ROUND(IFNULL(SUM(CASE WHEN S.WZHQY='1' AND T.XHRQ_MD>LD_SYSDATE THEN T.GKBL_MDSE ELSE 0 END), 0)/10000,6),
           LN_WZHBL_TMSE_YEAR + ROUND(IFNULL(SUM(CASE WHEN S.WZHQY='1' THEN T.GKBL_MDSE ELSE 0 END), 0)/10000,6),
           LN_BL_TMSE_HJ + ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,6)
      INTO LN_WZHBL_TMSE_MON, LN_WZHBL_TMSE_YEAR, LN_BL_TMSE_HJ
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN GLXT_BB_SHXT_DJXX S ON T.DJXH=S.DJXH_JS
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR
       AND T.XHRQ_MD<LD_NEXTMONTH;

    INSERT INTO TJBB_DT_B02101 (SSNY, BBLC, SWJGDM, SDDWDM, SDSW, SDSJ,
           BAHS_SC, BAHS_SC_ADD, BAHS_WM, BAHS_WM_ADD, BAHS_HJ, BAHS_HJ_ADD,
           SBHS_SC_MON, SBHS_SC_YEAR, SBHS_WM_MON, SBHS_WM_YEAR, SBHS_HJ_MON, SBHS_HJ_YEAR,
           QYHS_TMSE,
           WZHSB_TMSE_MON, WZHSB_TMSE_YEAR, SB_TMSE_HJ,
           WZHBL_TMSE_MON, WZHBL_TMSE_YEAR, BL_TMSE_HJ)
    SELECT LC_THISMONTH, '0001' AS BBLC, V_SWCODE AS SWJGDM, V_SWCODE AS SDDWDM, LC_SWJGMC AS SDSW,
           CASE WHEN V_SWCODE IN ('13300000000','13304830000','13305010000','13306030000') THEN '2015年5月1日'
                WHEN V_SWCODE =  '13304000000' THEN '2015年8月1日（其中，桐乡县从2015年5月1日起试点）'
                WHEN V_SWCODE =  '13305000000' THEN '2015年8月1日（其中，湖州市本级从2015年5月1日起试点）'
                WHEN V_SWCODE =  '13306000000' THEN '2015年8月1日（其中，柯桥区从2015年5月1日起试点）'
                WHEN SUBSTR(V_SWCODE,0,5) <= '13301' THEN '2015年11月1日'
                ELSE '2015年8月1日' END AS SDSJ,
           LN_BAHS_SC, LN_BAHS_SC_ADD, LN_BAHS_WM, LN_BAHS_WM_ADD, LN_BAHS_SC+LN_BAHS_WM, LN_BAHS_SC_ADD+LN_BAHS_WM_ADD,
           LN_SBHS_SC_MON, LN_SBHS_SC_YEAR, LN_SBHS_WM_MON, LN_SBHS_WM_YEAR, LN_SBHS_SC_MON+LN_SBHS_WM_MON, LN_SBHS_SC_YEAR+LN_SBHS_WM_YEAR,
           LN_QYHS_TMSE,
           LN_WZHSB_TMSE_MON, LN_WZHSB_TMSE_YEAR, LN_SB_TMSE_HJ,
           LN_WZHBL_TMSE_MON - TSFN_WZH_MON, LN_WZHBL_TMSE_YEAR - TSFN_WZH_YEAR, LN_BL_TMSE_HJ - TSFN_ALL
;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  --2、更新汇总列
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B02101 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02101' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
