DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03114_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03114_HZ_NEW
/*************************************************
 * 对“一带一路”国家出口退（免）税情况统计表（省、市局汇总）
 * 表结构与浙江省分出口市场统计表一样，算法条件有变化
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);--当月
  DECLARE LC_THISYEAR      VARCHAR(6);--当年首月
  DECLARE LC_LASTMONTH     VARCHAR(6);--上年同期
  DECLARE LN_CKE_HJ        DECIMAL(16,4);--出口额合计
  DECLARE LN_TSE_HJ        DECIMAL(16,4);--退税额合计
  DECLARE LN_CKE_HJ_LAST   DECIMAL(16,4);--出口额合计
  DECLARE LN_TSE_HJ_LAST   DECIMAL(16,4);--退税额合计

  DECLARE V_TEMP           BIGINT DEFAULT 0;
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_THISYEAR =DATE_FORMAT(LD_SYSDATE, '%Y')||'01';
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03114_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    DELETE FROM TJBB_DT_B03114 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、中间表数据计算
  BEGIN
    INSERT INTO TJBB_DT_B03114_MID (SWJGDM,SSNY,DMTYPE,GBDM,CKE_LJ,TSE_LJ,CKPM)
    SELECT V_SWCODE, LC_THISMONTH, B.DMTYPE, B.GBDM, SUM(B.CKE_LJ), SUM(B.TSE_LJ), ROW_NUMBER() OVER (PARTITION BY B.DMTYPE ORDER BY SUM(IFNULL(B.CKE_LJ, 0)) DESC)
      FROM TJBB_DT_B03114_MID B 
     WHERE B.SWJGDM IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))
       AND B.SSNY=LC_THISMONTH
     GROUP BY B.DMTYPE, B.GBDM;
    COMMIT;

    SELECT COUNT(1)
      INTO V_TEMP
      FROM TJBB_DT_B03114_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH AND DMTYPE='GJ';
    IF V_TEMP = 0 THEN
      BEGIN
        DELETE FROM TJBB_DT_B03114_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH;
        COMMIT;

        INSERT INTO TJBB_DT_B03114_MID (SWJGDM,SSNY,DMTYPE,GBDM,CKE_LJ,TSE_LJ,CKPM)
        SELECT V_SWCODE, LC_LASTMONTH, B.DMTYPE, B.GBDM, SUM(B.CKE_LJ), SUM(B.TSE_LJ), ROW_NUMBER() OVER (PARTITION BY B.DMTYPE ORDER BY SUM(IFNULL(B.CKE_LJ, 0)) DESC)
          FROM TJBB_DT_B03114_MID B 
         WHERE B.SWJGDM IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))
           AND B.SSNY=LC_LASTMONTH
         GROUP BY B.DMTYPE, B.GBDM;
        COMMIT;
      END;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --2、计算并插入区域情况及本年前10名明细及上年同期
  BEGIN
    INSERT INTO TJBB_DT_B03114 (SSNY,BBLC,SWJGDM,ITEM,CKE_USD,TMSE,CKE_USD_LAST,TMSE_LAST)
    SELECT LC_THISMONTH, '100', V_SWCODE, '区域情况', NULL, NULL, NULL, NULL

     UNION ALL
    SELECT B.SSNY, CASE WHEN B.CKPM<10 THEN '10' ELSE '1' END || B.CKPM, B.SWJGDM, A.DQ_NAME, B.CKE_LJ, B.TSE_LJ, C.CKE_LJ, C.TSE_LJ
      FROM DM_DQCODE A
     INNER JOIN TJBB_DT_B03114_MID B ON A.DQ_CODE=B.GBDM AND B.SWJGDM=V_SWCODE AND B.SSNY=LC_THISMONTH AND B.DMTYPE='BR'
      LEFT JOIN TJBB_DT_B03114_MID C ON A.DQ_CODE=C.GBDM AND C.SWJGDM=V_SWCODE AND C.SSNY=LC_LASTMONTH AND C.DMTYPE='BR'
     WHERE A.DQ_TYPE='BR'
     UNION ALL
    SELECT LC_THISMONTH, '200', V_SWCODE, '10个主要国别情况', NULL, NULL, NULL, NULL

     UNION ALL
    SELECT B.SSNY, CASE WHEN B.CKPM<10 THEN '20' ELSE '2' END || B.CKPM, B.SWJGDM, A.GB_NAME, B.CKE_LJ, B.TSE_LJ, C.CKE_LJ, C.TSE_LJ
      FROM DM_GBCODE A
     INNER JOIN TJBB_DT_B03114_MID B ON A.GB_CODE=B.GBDM AND B.SWJGDM=V_SWCODE AND B.SSNY=LC_THISMONTH AND B.DMTYPE='GJ'
      LEFT JOIN TJBB_DT_B03114_MID C ON A.GB_CODE=C.GBDM AND C.SWJGDM=V_SWCODE AND C.SSNY=LC_LASTMONTH AND C.DMTYPE='GJ'
     WHERE B.CKPM<=10;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --3、计算并插入合计数
  BEGIN
    SELECT SUM(CKE_LJ), SUM(TSE_LJ)
      INTO LN_CKE_HJ, LN_TSE_HJ
      FROM TJBB_DT_B03114_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH AND DMTYPE='GJ';

    SELECT SUM(CKE_LJ), SUM(TSE_LJ)
      INTO LN_CKE_HJ_LAST, LN_TSE_HJ_LAST
      FROM TJBB_DT_B03114_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH AND DMTYPE='GJ';

    INSERT INTO TJBB_DT_B03114 (SSNY,BBLC,SWJGDM,ITEM,CKE_USD,TMSE,CKE_USD_LAST,TMSE_LAST)
    SELECT LC_THISMONTH, '001', V_SWCODE, '“一带一路”沿线64国', LN_CKE_HJ, LN_TSE_HJ, LN_CKE_HJ_LAST, LN_TSE_HJ_LAST
;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      DO 0;
  END;

  --4、同比计算
  BEGIN
    UPDATE TJBB_DT_B03114
       SET CKE_TB  = CASE WHEN IFNULL(CKE_USD_LAST, 0)=0 THEN NULL ELSE ROUND(100 * CKE_USD / CKE_USD_LAST -100,1) END,
           TMSE_TB = CASE WHEN IFNULL(TMSE_LAST, 0)=0    THEN NULL ELSE ROUND(100 * TMSE    / TMSE_LAST    -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --5、占比计算
  BEGIN
    UPDATE TJBB_DT_B03114 T
       SET CKE_ZB  = CASE WHEN IFNULL(LN_CKE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * CKE_USD / LN_CKE_HJ,1) END,
           TMSE_ZB = CASE WHEN IFNULL(LN_TSE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * TMSE / LN_TSE_HJ,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --6、汇总栏初始化
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03114 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03114' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
