DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B01105_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B01105_CSH_NEW
/*************************************************
 * 出口退税返还情况月报表
 * 返纳数据从金三系统缴款书获取的情形，目前根据税款属性不能区分出清算补税和按规定予以追补、稽查补税
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';
  
  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =TRUNCATE(LD_SYSDATE, 'YY');
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B01105 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、计算列
  BEGIN
    --出口货物退运
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '02', V_SWCODE,
           COUNT(DISTINCT T.DJXH) AS QYHS, 
           IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0) AS JE,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_CUR,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_CUR
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND IFNULL(T.YWHZBUUID, IFNULL(T.YZHYTMSKYY_DM, T.SKSX_DM)) IN ('032','0109');
    COMMIT;

    --稽查补税
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '03', V_SWCODE,
           COUNT(DISTINCT T.DJXH) AS QYHS, 
           IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0) AS JE,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_CUR,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_CUR
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND IFNULL(T.YWHZBUUID, IFNULL(T.YZHYTMSKYY_DM, T.SKSX_DM)) IN (/*'033','0406',*/'0401','0402');
    COMMIT;

    --按规定予以追补
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '04', V_SWCODE,
           COUNT(DISTINCT T.DJXH) AS QYHS, 
           IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0) AS JE,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_CUR,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_CUR
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND IFNULL(T.YWHZBUUID, IFNULL(T.YZHYTMSKYY_DM, T.SKSX_DM)) NOT IN ('032','0109', /*'033','0406',*/'0401','0402');
    COMMIT;

    --清算补税
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '05', V_SWCODE, 0, 0, 0, 0, 0, 0, 0, 0
;
    COMMIT;

    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '01', V_SWCODE,
           SUM(QYHS), SUM(JE), SUM(ZZS_XJ), SUM(ZZS_HIS), SUM(ZZS_CUR), SUM(XFS_XJ), SUM(XFS_HIS), SUM(XFS_CUR)
      FROM TJBB_DT_B01105 
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('02','03','04','05');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  --2、更新汇总列
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B01105 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B01105' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
