DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B01106_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B01106_CSH_NEW
/*************************************************
 * 涉嫌骗取出口退税案源移送稽查部门情况统计月报表
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =MAKEDATE(YEAR(LD_SYSDATE), 1);

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B01106 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、数据筛选
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
INSERT INTO TJBB_DT_B01106 (SSNY, BBLC, SWJGDM,
           AY, SUMARY, ZYAY,
           NSRSBH, NSRMC,
           SPDM, SPMC,
           CKE, CKE_HZ, TMSE_HJ, TMSE_HJ_HZ, TSE, TSE_HZ, MDSE, MDSE_HZ,
           YSDW, YSSJ, YSSWH, YSR,
           JSDW, JSR, JSSJ, BYJA,
           LAZT, LASJ, XHZT, BZ)
    SELECT LC_THISMONTH, ORA_CONCAT('00', ROW_NUMBER() OVER (ORDER BY T.YSJC_DATE)), V_SWCODE,
           T.AJLY_NAME, T.AJLY_SUMMARY, T.AJLY_REASON,
           CASE WHEN T.SHXYNO IS NOT NULL AND T.SHXYNO<>' ' THEN T.SHXYNO ELSE T.NSRDJNO END, T.QYNAME,
           T.SASP_CODE, T.SASP_NAME,
           T.USD_AMT, T.USD_AMT, T.MDTS_AMT, T.MDTS_AMT, T.TS_AMT, T.TS_AMT, T.MD_AMT, T.MD_AMT,
           T.YSJC_SWNAME, T.YSJC_DATE, T.YSJC_NO, T.YSJC_USER,
           T.JCJS_SWNAME, T.JCJS_USER, T.JCJS_DATE, T.JCJS_FLAG,
           T.JCLA_FLAG, T.JCLA_DATE, T.JCJA_FLAG, T.REMARK
      FROM CKTS_OTHER_SXPSAJ T
     WHERE T.SWJGDM=V_SWCODE
       AND (T.JCJA_DATE IS NULL OR T.JCJA_DATE>LD_THISYEAR)
     ORDER BY T.YSJC_DATE;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
