DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03113_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03113_HZ_NEW
/*************************************************
 * 浙江省对美主要出口企业情况表（省、市局汇总）
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);--当月
  DECLARE LC_THISYEAR      VARCHAR(6);--当年首月
  DECLARE LC_LASTMONTH     VARCHAR(6);--上年同期
  DECLARE LC_LASTYEAR      VARCHAR(6);--上年首月
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_THISYEAR =DATE_FORMAT(LD_SYSDATE, '%Y')||'01';
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');
  SET LC_LASTYEAR =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y')||'01';

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03113 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、本年前50名当年数据
  BEGIN
    INSERT INTO TJBB_DT_B03113 
                (SSNY,BBLC,SWJGDM,CPCODE,QYHGDM,QYMC,JSMODE,JSMODEMC,PM,
                USA_CKE_YEAR,CKE_YEAR,USA_TMSE_YEAR,TMSE_YEAR,
                USA_CKE_YEAR_LAST,CKE_YEAR_LAST,USA_TMSE_YEAR_LAST,TMSE_YEAR_LAST,
                USA_CKE_TB,CKE_TB,USA_TMSE_TB,TMSE_TB,
                CKE_YEAR_ZB,CKE_YEAR_ZB_LAST,TMSE_YEAR_ZB,TMSE_YEAR_ZB_LAST)
    SELECT LC_THISMONTH,JSMODE||CASE WHEN PM<10 THEN '0' ELSE '' END||PM,V_SWCODE,CPCODE,QYHGDM,QYMC,JSMODE,JSMODEMC,PM,
           USA_CKE_YEAR,CKE_YEAR,USA_TMSE_YEAR,TMSE_YEAR,
           USA_CKE_YEAR_LAST,CKE_YEAR_LAST,USA_TMSE_YEAR_LAST,TMSE_YEAR_LAST,
           USA_CKE_TB,CKE_TB,USA_TMSE_TB,TMSE_TB,
           CKE_YEAR_ZB,CKE_YEAR_ZB_LAST,TMSE_YEAR_ZB,TMSE_YEAR_ZB_LAST
      FROM (SELECT CPCODE,QYHGDM,QYMC,JSMODE,JSMODEMC,
                   USA_CKE_YEAR,CKE_YEAR,USA_TMSE_YEAR,TMSE_YEAR,
                   USA_CKE_YEAR_LAST,CKE_YEAR_LAST,USA_TMSE_YEAR_LAST,TMSE_YEAR_LAST,
                   USA_CKE_TB,CKE_TB,USA_TMSE_TB,TMSE_TB,
                   CKE_YEAR_ZB,CKE_YEAR_ZB_LAST,TMSE_YEAR_ZB,TMSE_YEAR_ZB_LAST,
                   ROW_NUMBER() OVER (PARTITION BY JSMODE ORDER BY USA_CKE_YEAR DESC) AS PM
              FROM TJBB_DT_B03113 B 
             WHERE B.SWJGDM IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))
               AND B.SSNY=LC_THISMONTH)
     WHERE PM<=50;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --2、汇总栏初始化
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03113 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03113' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
