DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B02113_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B02113_HZ_NEW
/*************************************************
 * 跨境电子商务零售出口退税情况统计表9810（省、市局汇总）
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_NEXTMONTH     DATETIME;
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B02113 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、统计
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;
      LEAVE routine_body;

  END;
INSERT INTO TJBB_DT_B02113 (
           SSNY,BBLC,SWJGDM,
           BAHS, SBHS, SBTSCKE,
           SB_TMSE, SB_TSE, SB_MDSE,
           SH_TMSE, SH_TSE, SH_MDSE,
           BL_TMSE, BL_TSE, BL_MDSE)
    SELECT LC_THISMONTH,BBLC,V_SWCODE,
           SUM(BAHS), SUM(SBHS), SUM(SBTSCKE),
           SUM(SB_TMSE), SUM(SB_TSE), SUM(SB_MDSE),
           SUM(SH_TMSE), SUM(SH_TSE), SUM(SH_MDSE),
           SUM(BL_TMSE), SUM(BL_TSE), SUM(BL_MDSE)
      FROM TJBB_DT_B02113
     WHERE SWJGDM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
       AND SSNY=LC_THISMONTH
     GROUP BY BBLC;
    COMMIT;

    UPDATE TJBB_DT_B02113
       SET ZYSP = (SELECT S1.MLMC
                     FROM DM_SPML S1,
                          (SELECT SPML,SUM(MYLAJ) AS USD_TOTAL
                             FROM (SELECT C.SPML,B.MYLAJ
                                     FROM CKTS_LC_SHXX A
                                    INNER JOIN CKTS_WBSJ_BGD_9X10 B ON B.LCSLID=A.LCSLID AND B.TDCODE='9810' AND B.SBYWB_DM<>'A0305001'
                                    INNER JOIN DM_SPFL C ON C.SPDL=SUBSTR(B.CKSP_DM,1,2)
                                    WHERE A.TSSWJG_DM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
                                      AND A.QDSJ>=CAST('2013-01-01' AS DATE)
                                      AND A.QDSJ<LD_NEXTMONTH) S2
                            GROUP BY SPML
                            ORDER BY USD_TOTAL DESC) S3
                    WHERE S1.SPML=S3.SPML
                      AND 1=1
LIMIT 1)
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('01','04','07');
    COMMIT;

    UPDATE TJBB_DT_B02113
       SET ZYSP = (SELECT S1.MLMC
                     FROM DM_SPML S1,
                          (SELECT SPML,SUM(MYLAJ) AS USD_TOTAL
                             FROM (SELECT C.SPML,B.MYLAJ
                                     FROM CKTS_LC_SHXX A
                                    INNER JOIN CKTS_WBSJ_BGD_9X10 B ON B.LCSLID=A.LCSLID AND B.TDCODE='9810' AND B.SBYWB_DM='A0305001'
                                    INNER JOIN DM_SPFL C ON C.SPDL=SUBSTR(B.CKSP_DM,1,2)
                                    WHERE A.TSSWJG_DM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
                                      AND A.QDSJ>=CAST('2013-01-01' AS DATE)
                                      AND A.QDSJ<LD_NEXTMONTH) S2
                            GROUP BY SPML
                            ORDER BY USD_TOTAL DESC) S3
                    WHERE S1.SPML=S3.SPML
                      AND 1=1
LIMIT 1)
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('02','05','08');
    COMMIT;
  END;

  -- 11、更新汇总列
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B02113 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02113' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
