DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03108_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03108_HZ_NEW
/*************************************************
 * 浙江出口企业分注册类型统计表（省、市局汇总）
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);-- 当月
  DECLARE LC_THISYEAR      VARCHAR(6);-- 当年1月
  DECLARE LC_LASTMONTH     VARCHAR(6);-- 上年同期
  DECLARE LC_LASTYEAR      VARCHAR(6);-- 上年1月

  DECLARE LN_CKE_HJ        DECIMAL(16,4);-- 出口额合计
  DECLARE LN_TSE_HJ        DECIMAL(16,4);-- 退税额合计
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_THISYEAR =ORA_CONCAT(DATE_FORMAT(LD_SYSDATE, '%Y'), '01');
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');
  SET LC_LASTYEAR =ORA_CONCAT(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y'), '01');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_006;
      SET V_MSG = BJTS_SQLERRM_006;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B03108 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、计算并插入本年明细
  BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_005;
      SET V_MSG = BJTS_SQLERRM_005;

  END;
INSERT INTO TJBB_DT_B03108 (SSNY,BBLC,SWJGDM,CKE,TMSE,CKE_LAST,TMSE_LAST)
      WITH FL_DJZCLX AS (SELECT IFNULL(B.DJZCLX_JS, '190') AS DJZCLX_JS, IFNULL(B.JSMODE, '2') AS JSMODE,
                                SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN USD_AMT_ALL ELSE 0 END)/10000 AS USD_AMT,
                                SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN TS_AMT_ALL  ELSE 0 END)/10000 AS TS_AMT,
                                SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN USD_AMT_ALL ELSE 0 END)/10000 AS USD_AMT_LAST,
                                SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN TS_AMT_ALL  ELSE 0 END)/10000 AS TS_AMT_LAST
                           FROM TJBB_FHXX_CPCODE A
                           LEFT JOIN GLXT_BB_SHXT_DJXX B ON A.XMFL=B.CPCODE
                          WHERE ((V_SWCODE='13300000000'  AND (A.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR
                                 (V_SWCODE<>'13300000000' AND (A.SWCODE IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1'))))
                            AND ((SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH) OR (SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH))
                          GROUP BY B.DJZCLX_JS, B.JSMODE)
    SELECT LC_THISMONTH, '01', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     UNION ALL
    SELECT LC_THISMONTH, '02', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.DJZCLX_JS IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '03', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE SUBSTR(T.DJZCLX_JS,1,1) IN ('2','3')
     UNION ALL
    SELECT LC_THISMONTH, '04', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE SUBSTR(T.DJZCLX_JS,1,1) NOT IN ('2','3')
       AND T.DJZCLX_JS NOT IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '05', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE<>'1'
     UNION ALL
    SELECT LC_THISMONTH, '06', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE<>'1'
       AND T.DJZCLX_JS IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '07', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE<>'1'
       AND SUBSTR(T.DJZCLX_JS,1,1) IN ('2','3')
     UNION ALL
    SELECT LC_THISMONTH, '08', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE<>'1'
       AND SUBSTR(T.DJZCLX_JS,1,1) NOT IN ('2','3')
       AND T.DJZCLX_JS NOT IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '09', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE='1'
     UNION ALL
    SELECT LC_THISMONTH, '10', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE='1'
       AND T.DJZCLX_JS IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '11', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE='1'
       AND SUBSTR(T.DJZCLX_JS,1,1) IN ('2','3')
     UNION ALL
    SELECT LC_THISMONTH, '12', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE='1'
       AND SUBSTR(T.DJZCLX_JS,1,1) NOT IN ('2','3')
       AND T.DJZCLX_JS NOT IN ('110','141','143','151','161','162','164','165')
    ;
    COMMIT;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  -- 2、计算并插入合计数
  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      DO 0;

  END;
SELECT CKE, TMSE
      INTO LN_CKE_HJ, LN_TSE_HJ
      FROM TJBB_DT_B03108
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH AND BBLC='01';
  END;

  -- 4、同比计算
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;

  END;
UPDATE TJBB_DT_B03108
       SET CKE_TB  = CASE WHEN IFNULL(CKE_LAST, 0)=0  THEN NULL ELSE ROUND(100 * CKE  / CKE_LAST  -100,1) END,
    TMSE_TB = CASE WHEN IFNULL(TMSE_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TMSE / TMSE_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  -- 5、占比计算
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;

  END;
UPDATE TJBB_DT_B03108 AS T
       SET CKE_ZB  = CASE WHEN IFNULL(LN_CKE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * CKE  / LN_CKE_HJ,1) END,
    TMSE_ZB = CASE WHEN IFNULL(LN_TSE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * TMSE / LN_TSE_HJ,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  -- 6、汇总栏初始化
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03108 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03108' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
