DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B02107_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B02107_CSH_NEW
/*************************************************
 * 外贸综合服务企业基本信息表
 * 202202，针对同时申报出口货物劳务以及服务贸易的企业，调整lctjjc
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02107 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、统计
  BEGIN
    INSERT INTO TJBB_DT_B02107 (SSNY, BBLC, SWJGDM, XH,
           NSRSBH, QYHGDM, NSRMC, JSJDJDM, QYFDDBR, DJRQ, RDRQ_YBNSR, RDRQ_CKTS, NSRZT, ZCLX, JYZLX, QYFR_ZJLX, ZJHM,
           ZCDZ, JYDZ)
    SELECT LC_THISMONTH, SUBSTR(A.SWJGDM, 4, 4)|| SUBSTR('000000'||ROWNUM, LENGTH('000000'||ROWNUM)-5, 6), V_SWCODE, ROWNUM,
           CASE WHEN A.SHXYNO=' ' THEN A.NSRDJNO ELSE A.SHXYNO END, A.QYHGDM, A.NSRMC, A.JSJDJDM, A.FRDB_MC, A.SWDJ_DATE, A.YBNSR_DATE, A.SQ_DATE,
           A.NSRZT_JS, A.DJZCLX_JS, A.QYLX, A.FRDB_ZJLX, A.FRDB_ZJHM, A.ADDRESS_ZC, A.ADDRESS_JY
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG ='N'
       AND A.BAJC_YEAR IN ('70','71','72');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;


  --2、行内计算
  --3、汇总栏初始化
  LEAVE routine_body;
END$$

DELIMITER ;
