DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03103_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03103_HZ_NEW
/*************************************************
 * 浙江省办理出口退（免）税情况统计表（省、市局汇总）
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);--当月
  DECLARE LC_SWJGMC        VARCHAR(40);
  DECLARE LC_SWJGMC_SQ     VARCHAR(40);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03103 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、查询
  --税务机关显示名
  BEGIN
    SELECT DISPSX || CASE WHEN SWJG_DM='13300000000' THEN '合计' ELSE '小计' END, DISPSX || '辖区'
      INTO LC_SWJGMC, LC_SWJGMC_SQ
      FROM DM_SWJG A
     WHERE SWJG_DM=V_SWCODE;
  EXCEPTION
    WHEN OTHERS THEN
      DO 0;
  END;

  --2、插入记录
  BEGIN
    INSERT INTO TJBB_DT_B03103 (SSNY,BBLC,SWJGDM,AREA,
           TMSE_MON,TMSE_MON_LAST,TKE_MON,TKE_MON_LAST,TMSE_YEAR,TMSE_YEAR_LAST,TKE_YEAR,TKE_YEAR_LAST,KTKZY,
           TMSE_MON_HZ,TMSE_MON_LAST_HZ,TKE_MON_HZ,TKE_MON_LAST_HZ,TMSE_YEAR_HZ,TMSE_YEAR_LAST_HZ,TKE_YEAR_HZ,TKE_YEAR_LAST_HZ,KTKZY_HZ)
    SELECT LC_THISMONTH, SUBSTR(V_SWCODE, 4, 4)|| '0001', V_SWCODE, LC_SWJGMC,
           SUM(TMSE_MON),SUM(TMSE_MON_LAST),
           SUM(TKE_MON),SUM(TKE_MON_LAST),
           SUM(TMSE_YEAR),SUM(TMSE_YEAR_LAST),
           SUM(TKE_YEAR),SUM(TKE_YEAR_LAST),SUM(KTKZY),
           SUM(TMSE_MON_HZ),SUM(TMSE_MON_LAST_HZ),
           SUM(TKE_MON_HZ),SUM(TKE_MON_LAST_HZ),
           SUM(TMSE_YEAR_HZ),SUM(TMSE_YEAR_LAST_HZ),
           SUM(TKE_YEAR_HZ),SUM(TKE_YEAR_LAST_HZ),SUM(KTKZY_HZ)
      FROM TJBB_DT_B03103
     WHERE (SWJGDM,BBLC) IN (SELECT SWJG_DM,SUBSTR(SWJG_DM,4,4)||'0001' FROM DM_SWJG S WHERE SWJG_DM_SJ=V_SWCODE AND TSJG_BZ='1')
       AND SSNY=LC_THISMONTH;
    COMMIT;

    IF V_SWCODE <> '13300000000' THEN
      INSERT INTO TJBB_DT_B03103 (SSNY,BBLC,SWJGDM,AREA,
             TMSE_MON,TMSE_MON_LAST,TKE_MON,TKE_MON_LAST,TMSE_YEAR,TMSE_YEAR_LAST,TKE_YEAR,TKE_YEAR_LAST,KTKZY,
             TMSE_MON_HZ,TMSE_MON_LAST_HZ,TKE_MON_HZ,TKE_MON_LAST_HZ,TMSE_YEAR_HZ,TMSE_YEAR_LAST_HZ,TKE_YEAR_HZ,TKE_YEAR_LAST_HZ,KTKZY_HZ)
      SELECT LC_THISMONTH, 
             SUBSTR(V_SWCODE, 4, 4)|| '0002', V_SWCODE, LC_SWJGMC_SQ,
             SUM(TMSE_MON),SUM(TMSE_MON_LAST),
             SUM(TKE_MON),SUM(TKE_MON_LAST),
             SUM(TMSE_YEAR),SUM(TMSE_YEAR_LAST),
             SUM(TKE_YEAR),SUM(TKE_YEAR_LAST),SUM(KTKZY),
             SUM(TMSE_MON_HZ),SUM(TMSE_MON_LAST_HZ),
             SUM(TKE_MON_HZ),SUM(TKE_MON_LAST_HZ),
             SUM(TMSE_YEAR_HZ),SUM(TMSE_YEAR_LAST_HZ),
             SUM(TKE_YEAR_HZ),SUM(TKE_YEAR_LAST_HZ),SUM(KTKZY_HZ)
        FROM TJBB_DT_B03103
       WHERE (SWJGDM,BBLC) IN (SELECT S.SWJG_DM,SUBSTR(S.SWJG_DM,4,4)||'0001' FROM DM_ZBJG T, DM_SWJG S WHERE T.CK_ZBJG=SUBSTR(V_SWCODE,1,7) AND S.ZBJG_DM=T.ZBJG_DM)
         AND SSNY=LC_THISMONTH;
      COMMIT;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --3、同比计算
  BEGIN
    UPDATE TJBB_DT_B03103
       SET TMSE_MON_TB = CASE WHEN IFNULL(TMSE_MON_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TMSE_MON / TMSE_MON_LAST -100,1) END,
           TKE_MON_TB = CASE WHEN IFNULL(TKE_MON_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TKE_MON / TKE_MON_LAST -100,1) END,
           TMSE_YEAR_TB = CASE WHEN IFNULL(TMSE_YEAR_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TMSE_YEAR / TMSE_YEAR_LAST -100,1) END,
           TKE_YEAR_TB = CASE WHEN IFNULL(TKE_YEAR_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TKE_YEAR / TKE_YEAR_LAST -100,1) END,
           TMSE_MON_TB_HZ = CASE WHEN IFNULL(TMSE_MON_LAST_HZ, 0)=0 THEN NULL ELSE ROUND(100 * TMSE_MON_HZ / TMSE_MON_LAST_HZ -100,1) END,
           TKE_MON_TB_HZ = CASE WHEN IFNULL(TKE_MON_LAST_HZ, 0)=0 THEN NULL ELSE ROUND(100 * TKE_MON_HZ / TKE_MON_LAST_HZ -100,1) END,
           TMSE_YEAR_TB_HZ = CASE WHEN IFNULL(TMSE_YEAR_LAST_HZ, 0)=0 THEN NULL ELSE ROUND(100 * TMSE_YEAR_HZ / TMSE_YEAR_LAST_HZ -100,1) END,
           TKE_YEAR_TB_HZ = CASE WHEN IFNULL(TKE_YEAR_LAST_HZ, 0)=0 THEN NULL ELSE ROUND(100 * TKE_YEAR_HZ / TKE_YEAR_LAST_HZ -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  LEAVE routine_body;
END$$

DELIMITER ;
