DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_B02_CSH$$

CREATE PROCEDURE PRO_TJBB_B02_CSH
/*
 * 总局专项报表，区县局初始化
 * 需要指定区县级税务机关和报表所属期
 */
(
  IN LC_SWJGDM VARCHAR(4000),
  IN LC_MONTH VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_ERROR         DECIMAL(38,10);
  DECLARE LC_MSG           VARCHAR(2000);

  -- 按报表顺序依次制表
  BEGIN
  DECLARE BJTS_SQLCODE_009 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_009 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_009 = MYSQL_ERRNO, BJTS_SQLERRM_009 = MESSAGE_TEXT;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02101_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
      COMMIT;

  END;
CALL PRO_TJBB_DT_B02101_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02101_CSH_NEW！', LC_SWJGDM));
    COMMIT;
  END;
  BEGIN
  DECLARE BJTS_SQLCODE_008 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_008 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_008 = MYSQL_ERRNO, BJTS_SQLERRM_008 = MESSAGE_TEXT;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02102_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
      COMMIT;

  END;
CALL PRO_TJBB_DT_B02102_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02102_CSH_NEW！', LC_SWJGDM));
    COMMIT;
  END;
  BEGIN
  DECLARE BJTS_SQLCODE_007 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_007 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_007 = MYSQL_ERRNO, BJTS_SQLERRM_007 = MESSAGE_TEXT;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02103_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
      COMMIT;

  END;
CALL PRO_TJBB_DT_B02103_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02103_CSH_NEW！', LC_SWJGDM));
    COMMIT;
  END;
  BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02104_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
      COMMIT;

  END;
CALL PRO_TJBB_DT_B02104_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02104_CSH_NEW！', LC_SWJGDM));
    COMMIT;
  END;
  BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02105_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
      COMMIT;

  END;
CALL PRO_TJBB_DT_B02105_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02105_CSH_NEW！', LC_SWJGDM));
    COMMIT;
  END;
  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02106_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
      COMMIT;

  END;
CALL PRO_TJBB_DT_B02106_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02106_CSH_NEW！', LC_SWJGDM));
    COMMIT;
  END;
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02107_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
      COMMIT;

  END;
CALL PRO_TJBB_DT_B02107_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02107_CSH_NEW！', LC_SWJGDM));
    COMMIT;
  END;
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02108_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
      COMMIT;

  END;
CALL PRO_TJBB_DT_B02108_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02108_CSH_NEW！', LC_SWJGDM));
    COMMIT;
  END;
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02109_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
      COMMIT;

  END;
CALL PRO_TJBB_DT_B02109_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02109_CSH_NEW！', LC_SWJGDM));
    COMMIT;
  END;

END$$

DELIMITER ;
