DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B01105_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B01105_CSH_NEW
/*************************************************
 * 出口退税返还情况月报表
 * 返纳数据从金三系统缴款书获取的情形，目前根据税款属性不能区分出清算补税和按规定予以追补、稽查补税
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =MAKEDATE(YEAR(LD_SYSDATE), 1);
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B01105 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、计算列
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';
    -- 出口货物退运

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;

  END;
INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM,
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '02', V_SWCODE,
           COUNT(DISTINCT T.DJXH) AS QYHS,
           IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0) AS JE,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_CUR,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_CUR
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND IFNULL(T.YWHZBUUID, IFNULL(T.YZHYTMSKYY_DM, T.SKSX_DM)) IN ('032','0109');
    COMMIT;

    -- 稽查补税
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM,
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '03', V_SWCODE,
           COUNT(DISTINCT T.DJXH) AS QYHS,
           IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0) AS JE,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_CUR,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_CUR
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND IFNULL(T.YWHZBUUID, IFNULL(T.YZHYTMSKYY_DM, T.SKSX_DM)) IN (/*'033','0406',*/'0401','0402');
    COMMIT;

    -- 按规定予以追补
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM,
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '04', V_SWCODE,
           COUNT(DISTINCT T.DJXH) AS QYHS,
           IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0) AS JE,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS ZZS_CUR,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102'                            THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_XJ,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_HIS,
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0) AS XFS_CUR
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND IFNULL(T.YWHZBUUID, IFNULL(T.YZHYTMSKYY_DM, T.SKSX_DM)) NOT IN ('032','0109', /*'033','0406',*/'0401','0402');
    COMMIT;

    -- 清算补税
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM,
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '05', V_SWCODE, 0, 0, 0, 0, 0, 0, 0, 0
;
    COMMIT;

    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM,
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '01', V_SWCODE,
           SUM(QYHS), SUM(JE), SUM(ZZS_XJ), SUM(ZZS_HIS), SUM(ZZS_CUR), SUM(XFS_XJ), SUM(XFS_HIS), SUM(XFS_CUR)
      FROM TJBB_DT_B01105
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('02','03','04','05');
    COMMIT;
  END;

  -- 2、更新汇总列
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B01105 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B01105' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
