DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03110_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03110_HZ_NEW
/*************************************************
 * 浙江省分出口市场统计表
 * 20210205，金额栏保留整数，比率保留小数点后1位
 * 20210630，应省局吴嘉需求，全部国家排名
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);--当月
  DECLARE LC_THISYEAR      VARCHAR(6);--当年1月
  DECLARE LC_LASTMONTH     VARCHAR(6);--上年同期
  DECLARE LC_LASTYEAR      VARCHAR(6);--上年1月
  
  DECLARE LN_CKE_HJ        DECIMAL(16,4);--出口额合计
  DECLARE LN_TSE_HJ        DECIMAL(16,4);--退税额合计
  DECLARE LN_CKE_HJ_LAST   DECIMAL(16,4);--出口额合计
  DECLARE LN_TSE_HJ_LAST   DECIMAL(16,4);--退税额合计
  DECLARE LN_CKE_OTHER     DECIMAL(16,4);--出口额合计
  DECLARE LN_TSE_OTHER     DECIMAL(16,4);--退税额合计
  DECLARE LN_CKE_OTHER_LAST     DECIMAL(16,4);--出口额合计
  DECLARE LN_TSE_OTHER_LAST     DECIMAL(16,4);--退税额合计

  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;
  
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_THISYEAR =DATE_FORMAT(LD_SYSDATE, '%Y')||'01';
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');
  SET LC_LASTYEAR =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y')||'01';

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03110_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    DELETE FROM TJBB_DT_B03110_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH;
    DELETE FROM TJBB_DT_B03110 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、中间表数据计算
  BEGIN
    INSERT INTO TJBB_DT_B03110_MID (SWJGDM,SSNY,DMTYPE,GBDM,CKE_LJ,TSE_LJ,CKPM)
    SELECT V_SWCODE, LC_THISMONTH, 'DQ', DQ_CODE, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
      FROM (SELECT A.DQ_CODE, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM DM_DQCODE A
             INNER JOIN DM_DQGROUP B ON A.DQ_CODE=B.DQ_CODE
              LEFT JOIN TJBB_FHXX_GBCODE C ON B.GB_CODE=C.XMFL AND 
                        ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                         (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))))) AND C.SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH
             WHERE A.DQ_TYPE='DQ'
             GROUP BY A.DQ_CODE)
     UNION ALL
    SELECT V_SWCODE, LC_THISMONTH, 'ZZ', DQ_CODE, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
      FROM (SELECT A.DQ_CODE, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM DM_DQCODE A
             INNER JOIN DM_DQGROUP B ON A.DQ_CODE=B.DQ_CODE
              LEFT JOIN TJBB_FHXX_GBCODE C ON B.GB_CODE=C.XMFL AND 
                        ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                         (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))))) AND C.SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH
             WHERE A.DQ_TYPE='ZZ'
             GROUP BY A.DQ_CODE)
     UNION ALL
    SELECT V_SWCODE, LC_THISMONTH, 'GJ', XMFL, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
      FROM (SELECT XMFL, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM TJBB_FHXX_GBCODE C
             WHERE ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                    (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE))))))
               AND SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH AND XMFL<>'142'
             GROUP BY XMFL)
     UNION ALL
    SELECT V_SWCODE, LC_THISMONTH, 'GJ', XMFL, USD_AMT, TSE_AMT, 999
      FROM (SELECT '142' AS XMFL, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM TJBB_FHXX_GBCODE C
             WHERE ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                    (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE))))))
               AND SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH AND XMFL='142');
    COMMIT;
    
    INSERT INTO TJBB_DT_B03110_MID (SWJGDM,SSNY,DMTYPE,GBDM,CKE_LJ,TSE_LJ,CKPM)
    SELECT V_SWCODE, LC_LASTMONTH, 'DQ', DQ_CODE, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
      FROM (SELECT A.DQ_CODE, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM DM_DQCODE A
             INNER JOIN DM_DQGROUP B ON A.DQ_CODE=B.DQ_CODE
              LEFT JOIN TJBB_FHXX_GBCODE C ON B.GB_CODE=C.XMFL AND 
                        ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                         (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))))) AND C.SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH
             WHERE A.DQ_TYPE='DQ'
             GROUP BY A.DQ_CODE)
     UNION ALL
    SELECT V_SWCODE, LC_LASTMONTH, 'ZZ', DQ_CODE, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
      FROM (SELECT A.DQ_CODE, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM DM_DQCODE A
             INNER JOIN DM_DQGROUP B ON A.DQ_CODE=B.DQ_CODE
              LEFT JOIN TJBB_FHXX_GBCODE C ON B.GB_CODE=C.XMFL AND 
                        ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                         (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))))) AND C.SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH
             WHERE A.DQ_TYPE='ZZ'
             GROUP BY A.DQ_CODE)
     UNION ALL
    SELECT V_SWCODE, LC_LASTMONTH, 'GJ', XMFL, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
      FROM (SELECT XMFL, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM TJBB_FHXX_GBCODE C
             WHERE ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                    (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))))) AND SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH AND XMFL<>'142'
             GROUP BY XMFL)
     UNION ALL
    SELECT V_SWCODE, LC_LASTMONTH, 'GJ', XMFL, USD_AMT, TSE_AMT, 999
      FROM (SELECT '142' AS XMFL, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM TJBB_FHXX_GBCODE C
             WHERE ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                    (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))))) AND SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH AND XMFL='142');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --2、计算并插入本年明细及上年同期
  BEGIN
    INSERT INTO TJBB_DT_B03110 (SSNY,BBLC,SWJGDM,ITEM,CKE_USD,TMSE,CKE_USD_LAST,TMSE_LAST)
    SELECT LC_THISMONTH, '1000', V_SWCODE, '国别地区', NULL, NULL, NULL, NULL

     UNION ALL
    SELECT B.SSNY, CASE WHEN B.CKPM<10 THEN '100' ELSE '10' END || B.CKPM, B.SWJGDM, A.DQ_NAME, B.CKE_LJ, B.TSE_LJ, C.CKE_LJ, C.TSE_LJ
      FROM DM_DQCODE A
     INNER JOIN TJBB_DT_B03110_MID B ON A.DQ_CODE=B.GBDM AND B.SWJGDM=V_SWCODE AND B.SSNY=LC_THISMONTH AND B.DMTYPE='DQ'
      LEFT JOIN TJBB_DT_B03110_MID C ON A.DQ_CODE=C.GBDM AND C.SWJGDM=V_SWCODE AND C.SSNY=LC_LASTMONTH AND C.DMTYPE='DQ'
     WHERE A.DQ_TYPE='DQ'
     UNION ALL
    SELECT LC_THISMONTH, '2000', V_SWCODE, '区域（经济）组织', NULL, NULL, NULL, NULL

     UNION ALL
    SELECT B.SSNY, CASE WHEN B.CKPM<10 THEN '200' ELSE '20' END || B.CKPM, B.SWJGDM, A.DQ_NAME, B.CKE_LJ, B.TSE_LJ, C.CKE_LJ, C.TSE_LJ
      FROM DM_DQCODE A
     INNER JOIN TJBB_DT_B03110_MID B ON A.DQ_CODE=B.GBDM AND B.SWJGDM=V_SWCODE AND B.SSNY=LC_THISMONTH AND B.DMTYPE='ZZ'
      LEFT JOIN TJBB_DT_B03110_MID C ON A.DQ_CODE=C.GBDM AND C.SWJGDM=V_SWCODE AND C.SSNY=LC_LASTMONTH AND C.DMTYPE='ZZ'
     WHERE A.DQ_TYPE='ZZ'
     UNION ALL
    SELECT B.SSNY, CASE WHEN B.CKPM<10 THEN '300' WHEN B.CKPM<100 THEN '30' ELSE '3' END || B.CKPM, B.SWJGDM, A.GB_NAME, B.CKE_LJ, B.TSE_LJ, C.CKE_LJ, C.TSE_LJ
      FROM DM_GBCODE A
     INNER JOIN TJBB_DT_B03110_MID B ON A.GB_CODE=B.GBDM AND B.SWJGDM=V_SWCODE AND B.SSNY=LC_THISMONTH AND B.DMTYPE='GJ'
      LEFT JOIN TJBB_DT_B03110_MID C ON A.GB_CODE=C.GBDM AND C.SWJGDM=V_SWCODE AND C.SSNY=LC_LASTMONTH AND C.DMTYPE='GJ';
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --3、计算并插入合计数及其他数
  BEGIN
    SELECT ROUND(SUM(C.USD_AMT)/10000,0), ROUND(SUM(C.TS_AMT)/10000,0)
      INTO LN_CKE_HJ, LN_TSE_HJ
      FROM TJBB_FHXX_GBCODE C
     WHERE ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
            (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE))))))
        AND C.SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH;

    SELECT ROUND(SUM(C.USD_AMT)/10000,0), ROUND(SUM(C.TS_AMT)/10000,0)
      INTO LN_CKE_HJ_LAST, LN_TSE_HJ_LAST
      FROM TJBB_FHXX_GBCODE C
     WHERE ((V_SWCODE='13300000000'  AND (C.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
            (V_SWCODE<>'13300000000' AND (C.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))))) 
       AND C.SSNY BETWEEN  LC_LASTYEAR AND LC_LASTMONTH;

    SELECT LN_CKE_HJ - SUM(CKE_USD),LN_TSE_HJ - SUM(TMSE),LN_CKE_HJ_LAST - SUM(CKE_USD_LAST),LN_TSE_HJ_LAST - SUM(TMSE_LAST)
      INTO LN_CKE_OTHER, LN_TSE_OTHER, LN_CKE_OTHER_LAST, LN_TSE_OTHER_LAST
      FROM TJBB_DT_B03110
     WHERE SSNY=LC_THISMONTH AND BBLC LIKE '3%' AND SWJGDM=V_SWCODE;
    
    INSERT INTO TJBB_DT_B03110 (SSNY,BBLC,SWJGDM,ITEM,CKE_USD,TMSE,CKE_USD_LAST,TMSE_LAST)
    SELECT LC_THISMONTH, '3000', V_SWCODE, '所有国家合计', LN_CKE_HJ, LN_TSE_HJ, LN_CKE_HJ_LAST, LN_TSE_HJ_LAST
;
    INSERT INTO TJBB_DT_B03110 (SSNY,BBLC,SWJGDM,ITEM,CKE_USD,TMSE,CKE_USD_LAST,TMSE_LAST)
    SELECT LC_THISMONTH, '4000', V_SWCODE, '其他', LN_CKE_OTHER, LN_TSE_OTHER, LN_CKE_OTHER_LAST, LN_TSE_OTHER_LAST
;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      DO 0;
  END;

  --5、同比计算
  BEGIN
    UPDATE TJBB_DT_B03110
       SET CKE_TB  = CASE WHEN IFNULL(CKE_USD_LAST, 0)=0 THEN NULL ELSE ROUND(100 * CKE_USD / CKE_USD_LAST -100,1) END,
           TMSE_TB = CASE WHEN IFNULL(TMSE_LAST, 0)=0    THEN NULL ELSE ROUND(100 * TMSE    / TMSE_LAST    -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --6、占比计算
  BEGIN
    UPDATE TJBB_DT_B03110 T
       SET CKE_ZB  = CASE WHEN IFNULL(LN_CKE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * CKE_USD / LN_CKE_HJ,1) END,
           TMSE_ZB = CASE WHEN IFNULL(LN_TSE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * TMSE / LN_TSE_HJ,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  --7、汇总栏初始化
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03110 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03110' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
