DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03115_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03115_HZ_NEW
/*************************************************
 * 浙江省办理出口退税排名统计表（省、市局汇总）
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);-- 当月
  DECLARE LC_LASTMONTH     VARCHAR(6);-- 上年同期

  DECLARE LN_TMSE_HJ            DECIMAL(16,4);-- 退（免）税额合计
  DECLARE LN_TSE_HJ             DECIMAL(16,4);-- 退税额合计
  DECLARE LN_MDE_HJ             DECIMAL(16,4);-- 免抵额合计
  DECLARE LN_TMSE_HJ_LAST       DECIMAL(16,4);-- 退（免）税额合计
  DECLARE LN_TSE_HJ_LAST        DECIMAL(16,4);-- 退税额合计
  DECLARE LN_MDE_HJ_LAST        DECIMAL(16,4);-- 免抵额合计
  DECLARE LN_TMSE_OTHER         DECIMAL(16,4);-- 退（免）税额合计
  DECLARE LN_TSE_OTHER          DECIMAL(16,4);-- 退税额合计
  DECLARE LN_MDE_OTHER          DECIMAL(16,4);-- 免抵额合计
  DECLARE LN_TMSE_OTHER_LAST    DECIMAL(16,4);-- 退（免）税额合计
  DECLARE LN_TSE_OTHER_LAST     DECIMAL(16,4);-- 退税额合计
  DECLARE LN_MDE_OTHER_LAST     DECIMAL(16,4);-- 免抵额合计

  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_004;
      SET V_MSG = BJTS_SQLERRM_004;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B03115 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、中间表数据计算
  BEGIN
    IF V_SWCODE='13300000000' THEN
      BEGIN
  DECLARE BJTS_CURSOR_DONE_003 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_PM_SWJGDM_003 LONGTEXT;
  DECLARE BJTS_CUR_PM_JSMODE_003 LONGTEXT;
  DECLARE BJTS_CUR_PM_DJXH_003 LONGTEXT;
  DECLARE BJTS_CUR_PM_PM_003 LONGTEXT;
  DECLARE BJTS_CURSOR_003 CURSOR FOR
SELECT SWJGDM, JSMODE, DJXH, ROW_NUMBER() OVER (PARTITION BY JSMODE ORDER BY TMSE DESC) AS PM
                       FROM TJBB_DT_B03115_MID
                      WHERE SSNY=LC_THISMONTH
                        AND JSMODE IS NOT NULL;
  OPEN BJTS_CURSOR_003;
  BJTS_CURSOR_LOOP_003: LOOP
    SET BJTS_CURSOR_DONE_003 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_003 = TRUE;
      FETCH BJTS_CURSOR_003 INTO BJTS_CUR_PM_SWJGDM_003, BJTS_CUR_PM_JSMODE_003, BJTS_CUR_PM_DJXH_003, BJTS_CUR_PM_PM_003;
    END;
    IF BJTS_CURSOR_DONE_003 THEN
      LEAVE BJTS_CURSOR_LOOP_003;
    END IF;
        UPDATE TJBB_DT_B03115_MID AS T
           SET CKPM_3 = BJTS_CUR_PM_PM_003
         WHERE T.SSNY=LC_THISMONTH AND T.JSMODE=BJTS_CUR_PM_JSMODE_003 AND T.SWJGDM=BJTS_CUR_PM_SWJGDM_003 AND T.DJXH=BJTS_CUR_PM_DJXH_003;
        COMMIT;

  END LOOP BJTS_CURSOR_LOOP_003;
  CLOSE BJTS_CURSOR_003;
END;
    ELSE
      BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_PM_SWJGDM_002 LONGTEXT;
  DECLARE BJTS_CUR_PM_JSMODE_002 LONGTEXT;
  DECLARE BJTS_CUR_PM_DJXH_002 LONGTEXT;
  DECLARE BJTS_CUR_PM_PM_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT SWJGDM, JSMODE, DJXH, ROW_NUMBER() OVER (PARTITION BY JSMODE ORDER BY TMSE DESC) AS PM
                       FROM TJBB_DT_B03115_MID
                      WHERE SWJGDM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
                        AND SSNY=LC_THISMONTH
                        AND JSMODE IS NOT NULL;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_CUR_PM_SWJGDM_002, BJTS_CUR_PM_JSMODE_002, BJTS_CUR_PM_DJXH_002, BJTS_CUR_PM_PM_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
        UPDATE TJBB_DT_B03115_MID AS T
           SET CKPM_2 = BJTS_CUR_PM_PM_002
         WHERE T.SSNY=LC_THISMONTH AND T.JSMODE=BJTS_CUR_PM_JSMODE_002 AND T.SWJGDM=BJTS_CUR_PM_SWJGDM_002 AND T.DJXH=BJTS_CUR_PM_DJXH_002;
        COMMIT;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;
    END IF;
  END;

  -- 2、查询并插入外贸（生产）各前10名
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;
      LEAVE routine_body;

  END;
INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,JSMODEMC,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,TMSE_TB,XH)
    SELECT LC_THISMONTH, ORA_CONCAT(JSMODE, SUBSTR(ORA_CONCAT('00', PM),-2)), V_SWCODE,
           DJXH,SHXYNO,QYMC,JSMODE,JSMODEMC,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,TMSE_TB,PM
      FROM (SELECT DJXH, SHXYNO, QYMC, JSMODE, JSMODEMC, SWJG, TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,TMSE_TB,
                   ROW_NUMBER() OVER (PARTITION BY JSMODE ORDER BY TMSE DESC) AS PM
              FROM TJBB_DT_B03115 B
             WHERE B.SWJGDM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
               AND B.SSNY=LC_THISMONTH
               AND B.JSMODE IS NOT NULL)
     WHERE PM<=20;
    COMMIT;
  END;

  -- 3、计算并插入合计数、小计数与其他数
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;
      LEAVE routine_body;

  END;
SELECT SUM(TMSE),SUM(TSE),SUM(MDE),SUM(TMSE_LAST),SUM(TSE_LAST),SUM(MDE_LAST)
      INTO LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ, LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='000';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '000', V_SWCODE,NULL,NULL,'合计',NULL,NULL,LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ,LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST,NULL
;
    COMMIT;

    SELECT SUM(TMSE),SUM(TSE),SUM(MDE),SUM(TMSE_LAST),SUM(TSE_LAST),SUM(MDE_LAST)
      INTO LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ, LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='100';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '100', V_SWCODE,NULL,NULL,'生产小计',NULL,NULL,LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ,LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST,NULL
;
    COMMIT;

    SELECT LN_TMSE_HJ - SUM(A.TMSE), LN_TSE_HJ - SUM(A.TSE), LN_MDE_HJ - SUM(A.MDE),
           LN_TMSE_HJ_LAST - SUM(A.TMSE_LAST), LN_TSE_HJ_LAST - SUM(A.TSE_LAST), LN_MDE_HJ_LAST - SUM(A.MDE_LAST)
      INTO LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM=V_SWCODE AND A.SSNY=LC_THISMONTH AND A.BBLC>'100' AND A.BBLC<'200';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '199', V_SWCODE,NULL,NULL,'生产其他',NULL,NULL,LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST,NULL
;
    COMMIT;

    SELECT SUM(TMSE),SUM(TSE),SUM(MDE),SUM(TMSE_LAST),SUM(TSE_LAST),SUM(MDE_LAST)
      INTO LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ, LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='200';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '200', V_SWCODE,NULL,NULL,'外贸小计',NULL,NULL,LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ,LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST,NULL
;
    COMMIT;

    SELECT LN_TMSE_HJ - SUM(A.TMSE), LN_TSE_HJ - SUM(A.TSE), LN_MDE_HJ - SUM(A.MDE),
           LN_TMSE_HJ_LAST - SUM(A.TMSE_LAST), LN_TSE_HJ_LAST - SUM(A.TSE_LAST), LN_MDE_HJ_LAST - SUM(A.MDE_LAST)
      INTO LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM=V_SWCODE AND A.SSNY=LC_THISMONTH AND A.BBLC>'200';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '299', V_SWCODE,NULL,NULL,'外贸其他',NULL,NULL,LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST,NULL
;
    COMMIT;

    UPDATE TJBB_DT_B03115
       SET TMSE_TB = CASE WHEN IFNULL(TMSE_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TMSE / TMSE_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('000','100','199','200','299');
    COMMIT;
  END;

  -- 4、汇总栏初始化
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03115 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03115' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
