DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B01107_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B01107_CSH_NEW
/****************************************************
 * 全国出口退税专设机构设置及专职人员配备年度统计表
 * 202202，调整口径，按用户表中金三国地税用户筛选，原审核系统或其他用户不统计，其中原国税以133开始，原地税以233开始
 ***************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;

  DECLARE TOTAL_TS_AMT     DECIMAL(18,6);
  DECLARE LC_SWJGMC        VARCHAR(100);
  DECLARE LN_USERS         BIGINT;
  DECLARE LN_TSE_PER_USER  DECIMAL(18,6);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =MAKEDATE(YEAR(LD_SYSDATE), 1);
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B01107 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、计算列
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';
    -- 税务机关名称

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;

  END;
SELECT SWJG_JC
      INTO LC_SWJGMC
      FROM DM_SWJG
     WHERE SWJG_DM=V_SWCODE;
    -- 本税务机关人数
    SELECT COUNT(1)
      INTO LN_USERS
      FROM SYS_USER T
     WHERE T.SWJG_DM=V_SWCODE
       AND T.USRSTATE='3' AND (T.CZRY_DM LIKE '133%' OR T.CZRY_DM LIKE '233%');
    -- 本税务机关办理退税额
    SELECT SUM(IFNULL(T.SEHZ_MDTSE, 0))/10000
      INTO TOTAL_TS_AMT
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH;
    SET LN_TSE_PER_USER = CASE WHEN LN_USERS=0 THEN ROUND(TOTAL_TS_AMT,6) ELSE ROUND(TOTAL_TS_AMT/LN_USERS,6) END;

    INSERT INTO TJBB_DT_B01107(SSNY,BBLC,SWJGDM,SWJGMC,
                JG_HJ,JG_XJ_CITY,JG_XJ_JG,JG_XJ_LV,
                RY_HJ,RY_XJ,RY_XJ_LV,
                PER_SE)
         SELECT LC_THISMONTH, '01', V_SWCODE, LC_SWJGMC,
                1, 1, 1, 100,
                LN_USERS, LN_USERS, 100,
                LN_TSE_PER_USER
;
    COMMIT;
  END;

  -- 2、更新汇总列
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B01107 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B01107' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
