DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_CSH_9X10$$

CREATE PROCEDURE PRO_TJBB_CSH_9X10
/*
 * 省局月报表/出口退税月报表（不计结转），所有税务局重新制表
 * 需要手工调制报表所属期
 */
(
  IN LC_MONTH VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_SWJGDM        VARCHAR(11);
  DECLARE LN_ERROR         DECIMAL(38,10);
  DECLARE LC_MSG           VARCHAR(2000);

  -- 区县局
  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_SWJG_SWJG_DM_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND YXWS=7 AND SWJG_DM LIKE '13301%' ORDER BY SWJG_DM;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_SWJG_SWJG_DM_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    SET LC_SWJGDM = BJTS_LSF_SWJG_SWJG_DM_001;

    CALL PRO_TJBB_DT_B02103_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    CALL PRO_TJBB_DT_B02112_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    CALL PRO_TJBB_DT_B02113_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    CALL PRO_TJBB_DT_B05101_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    COMMIT;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
END$$

DELIMITER ;
