DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03111_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03111_CSH_NEW
/*************************************************
 * 浙江省出口企业函调情况统计表
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LN_I             BIGINT;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03111 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、插入两行空行
  BEGIN
    SET LN_I = 0;
    FOR LN_I IN 1 .. 8 LOOP
      BEGIN
        INSERT INTO TJBB_DT_B03111(SSNY,BBLC,SWJGDM,FP_SL,FP_SL_HZ,HSHFH_SL,HSHFH_SL_HZ,JS_JE,JS_JE_HZ,TS_JE,TS_JE_HZ)
        SELECT LC_THISMONTH, '0'||CAST(LN_I AS CHAR), V_SWCODE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
;
      END;
    END LOOP;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
