DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_B06_CSH$$

CREATE PROCEDURE PRO_TJBB_B06_CSH
/*
 * 市场采购情况统计表，区县局初始化
 * 需要指定区县级税务机关和报表所属期
 */
(
  IN LC_SWJGDM VARCHAR(4000),
  IN LC_MONTH VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_ERROR         DECIMAL(38,10);
  DECLARE LC_MSG           VARCHAR(2000);

  -- 按报表顺序依次制表
    BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B06101_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B06101_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B06101_CSH_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B06102_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B06102_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B06102_CSH_NEW！', LC_SWJGDM));
      COMMIT;
    END;

END$$

DELIMITER ;
