DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B06102_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B06102_CSH_NEW
/**************************************************************
 * 市场采购情况统计表——市场采购贸易方式试点出口情况表
 * 首次不用处理，非首次申报将上月数据迁移到本月报表中
 **************************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LC_PREVMONTH     VARCHAR(6);
  DECLARE V_TEMP           BIGINT DEFAULT 0;


  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_PREVMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -1 MONTH), '%Y%m');
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B06102 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、统计
  BEGIN
    --检查是否第一次使用该报表
    SELECT COUNT(1)
      INTO V_TEMP
      FROM TJBB_DT_B06102
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_PREVMONTH AND ROWNUM=1;
    IF V_TEMP > 0 THEN
      INSERT INTO TJBB_DT_B06102 (SSNY,BBLC,SWJGDM,AREA,PROV,QJNY,CKE_MON,CKE_MON_HZ,CKE_TOTAL,CKE_TOTAL_HZ,SBMS_MON,SBMS_MON_HZ,SBMS_TOTAL,SBMS_TOTAL_HZ)
      SELECT LC_THISMONTH, BBLC,SWJGDM,AREA,PROV,QJNY,CKE_MON,CKE_MON_HZ,CKE_TOTAL,CKE_TOTAL_HZ,SBMS_MON,SBMS_MON_HZ,SBMS_TOTAL,SBMS_TOTAL_HZ
        FROM TJBB_DT_B06102
       WHERE SWJGDM=V_SWCODE AND SSNY=LC_PREVMONTH;
      COMMIT;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
