DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B01109_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B01109_CSH_NEW
/*
 * 202101，返纳数据从金三系统缴款书获取
 * 202102，外贸企业由申报到在途顺序计算改成由在途到申报反向计算，防止报表生成时在途数出负数
 * 202102，受理数统计时扣除返纳，防止报表生成时在途数虚增
 * 202102，符合13号公告规定业务的申报退税只取WMZHFW的数据
 * 202202，针对同时申报出口货物劳务以及服务贸易的企业，调整lctjjc
 * 20260116，根据舟山反馈问题分析，在统计生产企业申报户数、申报出口额、申报免抵退税额口径，提取进料加工数据时加调整数不为0的条件
 */
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;
  DECLARE LC_LASTMONTH     VARCHAR(6);

  DECLARE LN_BAHS          BIGINT;
  DECLARE LN_SBHS          BIGINT;
  DECLARE LN_SB_CKE_HIS    DECIMAL(18,6);
  DECLARE LN_SB_CKE_CUR    DECIMAL(18,6);

  DECLARE LN_SB_ZZS_HIS    DECIMAL(18,6);
  DECLARE LN_SB_ZZS_CUR    DECIMAL(18,6);
  DECLARE LN_SH_ZZS_HIS    DECIMAL(18,6);
  DECLARE LN_SH_ZZS_CUR    DECIMAL(18,6);
  DECLARE LN_SP_ZZS_XJ     DECIMAL(18,6);
  DECLARE LN_SP_ZZS_HIS    DECIMAL(18,6);
  DECLARE LN_SP_ZZS_CUR    DECIMAL(18,6);
  DECLARE LN_YS_ZZS        DECIMAL(18,6);
  DECLARE LN_BL_ZZS_HIS    DECIMAL(18,6);
  DECLARE LN_BL_ZZS_CUR    DECIMAL(18,6);
  DECLARE LN_BL_ZZS_HIS_JZ DECIMAL(18,6);
  DECLARE LN_BL_ZZS_HIS_SP DECIMAL(18,6);
  DECLARE TSFN_ZZS_HIS     DECIMAL(18,6);
  DECLARE TSFN_ZZS_CUR     DECIMAL(18,6);

  DECLARE LN_SB_XFS_HIS    DECIMAL(18,6);
  DECLARE LN_SB_XFS_CUR    DECIMAL(18,6);
  DECLARE LN_SH_XFS_HIS    DECIMAL(18,6);
  DECLARE LN_SH_XFS_CUR    DECIMAL(18,6);
  DECLARE LN_SP_XFS_XJ     DECIMAL(18,6);
  DECLARE LN_SP_XFS_HIS    DECIMAL(18,6);
  DECLARE LN_SP_XFS_CUR    DECIMAL(18,6);
  DECLARE LN_YS_XFS        DECIMAL(18,6);
  DECLARE LN_BL_XFS_HIS    DECIMAL(18,6);
  DECLARE LN_BL_XFS_CUR    DECIMAL(18,6);
  DECLARE LN_BL_XFS_HIS_JZ DECIMAL(18,6);
  DECLARE LN_BL_XFS_HIS_SP DECIMAL(18,6);
  DECLARE TSFN_XFS_HIS     DECIMAL(18,6);
  DECLARE TSFN_XFS_CUR     DECIMAL(18,6);

  DECLARE LC_SQL           VARCHAR(4000);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =MAKEDATE(YEAR(LD_SYSDATE), 1);
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_011 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_011 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_011 = MYSQL_ERRNO, BJTS_SQLERRM_011 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_011;
      SET V_MSG = BJTS_SQLERRM_011;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B01109 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、外贸企业
  BEGIN
  DECLARE BJTS_SQLCODE_010 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_010 TEXT DEFAULT '';
    -- 返纳

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_010 = MYSQL_ERRNO, BJTS_SQLERRM_010 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_010;
      SET V_MSG = BJTS_SQLERRM_010;

  END;
SELECT IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ< LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ< LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0)
      INTO TSFN_ZZS_HIS, TSFN_ZZS_CUR, TSFN_XFS_HIS, TSFN_XFS_CUR
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE S.BAJC_YEAR IN ('00','10')
       AND T.CPCODE=S.CPCODE
       AND T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;

    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='10';

    -- 申报户数、申报出口额
    SELECT COUNT(DISTINCT T.DJXH),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,
                   B.MYLAJ * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                             END AS MYLAJ
              FROM CKTS_LC_SHXX A
              LEFT JOIN CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC IN ('10','40','50')
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR) T;

    -- 申报退税额、审核通过退税额
    SELECT ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 增值税申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 消费税申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6) -- 准予
      INTO LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
      FROM (SELECT A.DJXH,B.SBXH,B.CKRQ_1,B.SZ,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.TSE * CASE WHEN B.SZ='V' THEN (CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                                         WHEN A.ZY_ZZSTSE=0 THEN 1
                                                         WHEN A.SNBL_ZZSTSE=0 THEN 1
                                                         WHEN A.SNBL_ZZSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                                         ELSE LEAST(GREATEST(1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE,0),1)
                                                    END)
                           ELSE (CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                      WHEN A.ZY_XFSTSE=0 THEN 1
                                      WHEN A.SNBL_XFSTSE=0 THEN 1
                                      WHEN A.SNBL_XFSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                      ELSE LEAST(GREATEST(1 - A.SNBL_XFSTSE / A.ZY_XFSTSE,0),1)
                                 END)
                           END AS TSE
              FROM CKTS_LC_SHXX A
             INNER JOIN CKTS_SB_MTS_JHMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC IN ('10','40','50')
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR) T;

    -- 审批退税额、移送国库退税额、国库办理退税额
    SELECT ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE T.SEHZ_ZZSTSE END), 0)/10000,6), -- 增值税审批
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE T.SEHZ_ZZSTSE END * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年审批结转
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE T.SEHZ_XFSTSE END), 0)/10000,6), -- 消费税审批
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE T.SEHZ_XFSTSE END * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6) -- 办理上年审批结转
      INTO LN_SP_ZZS_XJ, LN_SP_ZZS_HIS, LN_YS_ZZS, LN_BL_ZZS_HIS, LN_BL_ZZS_HIS_JZ, LN_BL_ZZS_HIS_SP,
           LN_SP_XFS_XJ, LN_SP_XFS_HIS, LN_YS_XFS, LN_BL_XFS_HIS, LN_BL_XFS_HIS_JZ, LN_BL_XFS_HIS_SP
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN CKTS_LC_YWHZXX S ON S.YWHZBUUID=T.YWHZBUUID AND S.CKTMSHWYSFWLX_DM=T.CKTMSHWYSFWLX_DM
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.LCTJJC='10'
       AND T.XHRQ_TK>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SET LN_SP_ZZS_CUR = LN_SP_ZZS_XJ - LN_SP_ZZS_HIS;
    SET LN_SP_XFS_CUR = LN_SP_XFS_XJ - LN_SP_XFS_HIS;
    SET LN_BL_ZZS_CUR = LN_YS_ZZS - LN_BL_ZZS_HIS;
    SET LN_BL_XFS_CUR = LN_YS_XFS - LN_BL_XFS_HIS;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '05', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE_HIS + LN_SB_CKE_CUR, LN_SB_CKE_HIS, LN_SB_CKE_CUR,
           LN_SB_ZZS_HIS + LN_SB_ZZS_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR,
           LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR,
           LN_SP_ZZS_XJ - TSFN_ZZS_HIS - TSFN_ZZS_CUR,   LN_SP_ZZS_HIS - TSFN_ZZS_HIS, LN_SP_ZZS_CUR - TSFN_ZZS_CUR,
           LN_YS_ZZS                    - TSFN_ZZS_HIS - TSFN_ZZS_CUR, LN_BL_ZZS_HIS - TSFN_ZZS_HIS,
           GREATEST(LN_BL_ZZS_HIS_JZ - TSFN_ZZS_HIS, 0), GREATEST(LN_BL_ZZS_HIS_SP - TSFN_ZZS_HIS, 0),
           LN_BL_ZZS_CUR - TSFN_ZZS_CUR
;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '06', V_SWCODE, 0, 0, 0, 0, 0,
           LN_SB_XFS_HIS + LN_SB_XFS_CUR, LN_SB_XFS_HIS, LN_SB_XFS_CUR,
           LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR,
           LN_SP_XFS_XJ - TSFN_XFS_HIS - TSFN_XFS_CUR,  LN_SP_XFS_HIS - TSFN_XFS_HIS, LN_SP_XFS_CUR - TSFN_XFS_CUR,
           LN_YS_XFS                    - TSFN_XFS_HIS - TSFN_XFS_CUR, LN_BL_XFS_HIS - TSFN_XFS_HIS,
           GREATEST(LN_BL_XFS_HIS_JZ - TSFN_XFS_HIS, 0), GREATEST(LN_BL_XFS_HIS_SP - TSFN_XFS_HIS, 0),
           LN_BL_XFS_CUR - TSFN_XFS_CUR
;
    COMMIT;
  END;

  -- 2、外综服企业
  BEGIN
  DECLARE BJTS_SQLCODE_009 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_009 TEXT DEFAULT '';
    -- 返纳

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_009 = MYSQL_ERRNO, BJTS_SQLERRM_009 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_009;
      SET V_MSG = BJTS_SQLERRM_009;

  END;
SELECT IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ< LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ< LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0)
      INTO TSFN_ZZS_HIS, TSFN_ZZS_CUR, TSFN_XFS_HIS, TSFN_XFS_CUR
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE S.BAJC_YEAR IN ('70','71','72')
       AND T.CPCODE=S.CPCODE
       AND T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;

    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR IN ('70','71','72');

    -- 申报户数、申报出口额
    SELECT COUNT(DISTINCT T.DJXH),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,
                   B.MYLAJ * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                             END AS MYLAJ
              FROM CKTS_LC_SHXX A
              LEFT JOIN CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC IN ('70','71')
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR
             UNION ALL
            SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,
                   B.MYLAJ * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                             END AS MYLAJ
              FROM CKTS_LC_SHXX A
              LEFT JOIN CKTS_SB_WZF_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC = '72'
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR) T;

    -- 申报退税额、审核通过退税额
    SELECT ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 增值税申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 消费税申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6) -- 准予
      INTO LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
      FROM (SELECT A.DJXH,B.SBXH,B.CKRQ_1,B.SZ,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.TSE * CASE WHEN B.SZ='V' THEN (CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                                         WHEN A.ZY_ZZSTSE=0 THEN 1
                                                         WHEN A.SNBL_ZZSTSE=0 THEN 1
                                                         WHEN A.SNBL_ZZSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                                         ELSE LEAST(GREATEST(1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE,0),1)
                                                    END)
                           ELSE (CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                      WHEN A.ZY_XFSTSE=0 THEN 1
                                      WHEN A.SNBL_XFSTSE=0 THEN 1
                                      WHEN A.SNBL_XFSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                      ELSE LEAST(GREATEST(1 - A.SNBL_XFSTSE / A.ZY_XFSTSE,0),1)
                                 END)
                           END AS TSE
              FROM CKTS_LC_SHXX A
             INNER JOIN CKTS_SB_MTS_JHMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC IN ('70','71')
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR
             UNION ALL
            SELECT A.DJXH,B.SBXH,B.CKRQ_1,'V' AS SZ,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.TSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                WHEN A.SNBL_MDTSE=0 THEN 1
                                WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                           END AS TSE
              FROM CKTS_LC_SHXX A
             INNER JOIN CKTS_SB_WZF_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC = '72'
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR) T;

    -- 审批退税额、移送国库退税额、国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE), 0)/10000,6), -- 增值税审批
           ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年审批结转
           ROUND(IFNULL(SUM(T.SEHZ_XFSTSE), 0)/10000,6), -- 消费税审批
           ROUND(IFNULL(SUM(T.SEHZ_XFSTSE * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6) -- 办理上年审批结转
      INTO LN_SP_ZZS_XJ, LN_SP_ZZS_HIS, LN_YS_ZZS, LN_BL_ZZS_HIS, LN_BL_ZZS_HIS_JZ, LN_BL_ZZS_HIS_SP,
           LN_SP_XFS_XJ, LN_SP_XFS_HIS, LN_YS_XFS, LN_BL_XFS_HIS, LN_BL_XFS_HIS_JZ, LN_BL_XFS_HIS_SP
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN CKTS_LC_YWHZXX S ON S.YWHZBUUID=T.YWHZBUUID AND S.CKTMSHWYSFWLX_DM=T.CKTMSHWYSFWLX_DM
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.LCTJJC IN ('70','71','72')
       AND T.XHRQ_TK>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SET LN_SP_ZZS_CUR = LN_SP_ZZS_XJ - LN_SP_ZZS_HIS;
    SET LN_SP_XFS_CUR = LN_SP_XFS_XJ - LN_SP_XFS_HIS;
    SET LN_BL_ZZS_CUR = LN_YS_ZZS - LN_BL_ZZS_HIS;
    SET LN_BL_XFS_CUR = LN_YS_XFS - LN_BL_XFS_HIS;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '08', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE_HIS + LN_SB_CKE_CUR, LN_SB_CKE_HIS, LN_SB_CKE_CUR,
           LN_SB_ZZS_HIS + LN_SB_ZZS_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR,
           LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR,
           LN_SP_ZZS_XJ - TSFN_ZZS_HIS - TSFN_ZZS_CUR,   LN_SP_ZZS_HIS - TSFN_ZZS_HIS, LN_SP_ZZS_CUR - TSFN_ZZS_CUR,
           LN_YS_ZZS                     - TSFN_ZZS_HIS - TSFN_ZZS_CUR, LN_BL_ZZS_HIS - TSFN_ZZS_HIS,
           GREATEST(LN_BL_ZZS_HIS_JZ - TSFN_ZZS_HIS, 0), GREATEST(LN_BL_ZZS_HIS_SP - TSFN_ZZS_HIS, 0),
           LN_BL_ZZS_CUR - TSFN_ZZS_CUR
;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '09', V_SWCODE, 0, 0, 0, 0, 0,
           LN_SB_XFS_HIS + LN_SB_XFS_CUR, LN_SB_XFS_HIS, LN_SB_XFS_CUR,
           LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR,
           LN_SP_XFS_XJ - TSFN_XFS_HIS - TSFN_XFS_CUR,  LN_SP_XFS_HIS - TSFN_XFS_HIS, LN_SP_XFS_CUR - TSFN_XFS_CUR,
           LN_YS_XFS                    - TSFN_XFS_HIS - TSFN_XFS_CUR, LN_BL_XFS_HIS - TSFN_XFS_HIS,
           GREATEST(LN_BL_XFS_HIS_JZ - TSFN_XFS_HIS, 0), GREATEST(LN_BL_XFS_HIS_SP - TSFN_XFS_HIS, 0),
           LN_BL_XFS_CUR - TSFN_XFS_CUR
;
   COMMIT;

    -- 2.1 符合13号公告规定业务
    -- 返纳
    SET TSFN_ZZS_HIS = 0;
    SET TSFN_ZZS_CUR = 0;

    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.BAJC_YEAR IN ('70','71');

    -- 申报户数、申报出口额
    SELECT COUNT(DISTINCT T.DJXH),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,
                   B.MYLAJ * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                             END AS MYLAJ
              FROM CKTS_LC_SHXX A
              LEFT JOIN CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC = '71'
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR) T;

    -- 申报、审核通过
    SELECT ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6) -- 准予
      INTO LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
      FROM (SELECT A.DJXH,B.SBXH,B.CKRQ_1,B.SZ,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.TSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                             END AS TSE
              FROM CKTS_LC_SHXX A
             INNER JOIN CKTS_SB_MTS_JHMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC = '71'
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR) T;

    -- 审批退税额、移送国库退税额、国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE), 0)/10000,6), -- 审批
           ROUND(IFNULL(SUM((T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE) * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE + T.GKBL_XFSTSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM((CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE + T.GKBL_XFSTSE ELSE 0 END) * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE + T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE + T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6) -- 办理上年审批结转
      INTO LN_SP_ZZS_XJ, LN_SP_ZZS_HIS, LN_YS_ZZS, LN_BL_ZZS_HIS, LN_BL_ZZS_HIS_JZ, LN_BL_ZZS_HIS_SP
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN CKTS_LC_YWHZXX S ON S.YWHZBUUID=T.YWHZBUUID AND S.CKTMSHWYSFWLX_DM=T.CKTMSHWYSFWLX_DM
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.LCTJJC = '71'
       AND T.XHRQ_TK>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SET LN_SP_ZZS_CUR = LN_SP_ZZS_XJ - LN_SP_ZZS_HIS;
    SET LN_BL_ZZS_CUR = LN_YS_ZZS - LN_BL_ZZS_HIS;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '10', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE_HIS + LN_SB_CKE_CUR, LN_SB_CKE_HIS, LN_SB_CKE_CUR,
           LN_SB_ZZS_HIS + LN_SB_ZZS_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR,
           LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR,
           LN_SP_ZZS_XJ - TSFN_ZZS_HIS - TSFN_ZZS_CUR,   LN_SP_ZZS_HIS - TSFN_ZZS_HIS, LN_SP_ZZS_CUR - TSFN_ZZS_CUR,
           LN_YS_ZZS                    - TSFN_ZZS_HIS - TSFN_ZZS_CUR, LN_BL_ZZS_HIS - TSFN_ZZS_HIS,
           GREATEST(LN_BL_ZZS_HIS_JZ - TSFN_ZZS_HIS, 0), GREATEST(LN_BL_ZZS_HIS_SP - TSFN_ZZS_HIS, 0),
           LN_BL_ZZS_CUR - TSFN_ZZS_CUR
;
    COMMIT;
  END;

  -- 3、生产企业
  BEGIN
  DECLARE BJTS_SQLCODE_008 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_008 TEXT DEFAULT '';
     -- 返纳

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_008 = MYSQL_ERRNO, BJTS_SQLERRM_008 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_008;
      SET V_MSG = BJTS_SQLERRM_008;

  END;
SELECT IFNULL(ROUND(SUM(CASE WHEN T.SKSSQZ< LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0)
      INTO TSFN_ZZS_HIS, TSFN_ZZS_CUR
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE S.BAJC_YEAR IN ('21','22','23')
       AND T.CPCODE=S.CPCODE
       AND T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;

    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR IN ('21','22','23');

    -- 申报户数、申报出口额
    SELECT COUNT(DISTINCT T.DJXH),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报退税额
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), -- 申报免抵退税额
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.MDE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.MDE ELSE 0 END), 0)/10000,6) -- 准予
      INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR,
           LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR,
           LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.MYLAJ * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                             END AS MYLAJ,
                   B.MDTSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                           ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END)
                             END -- 根据是否复审用申报数或复审数计算退税部分
                           * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_ZZSTSE=0 THEN 1
                                  WHEN A.SNBL_ZZSTSE=0 THEN 1
                                  WHEN A.SNBL_ZZSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE,0),1)
                             END AS TSE,
                   B.MDTSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                           ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_MDSE/A.ZY_MDTSE END)
                             END
                           * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDSE=0 THEN 1
                                  WHEN A.SNBL_MDSE=0 THEN 1
                                  WHEN A.SNBL_MDSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDSE / A.ZY_MDSE,0),1)
                             END AS MDE
              FROM CKTS_LC_SHXX A
              LEFT JOIN CKTS_SB_MDT_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC IN ('21','41','51','61','22','42','52','62','23','43','53','63')
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR
             UNION ALL
             SELECT A.DJXH,B.LCSLID,'00000000' AS SBXH,DATE_ADD(LD_THISYEAR, INTERVAL -1 MONTH) AS CKRQ_1,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30 ELSE 40 END AS SHZT,
                   0 AS MYLAJ,
                   (B.JLJGHXYTZMDTSE + B.JZXQMDTSE - B.SQJZMDTSE)
                   * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                          ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END)
                     END -- 根据是否复审用申报数或复审数计算退税部分
                   * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                          WHEN A.ZY_ZZSTSE=0 THEN 1
                          ELSE LEAST(GREATEST(1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE,0),1)
                     END AS TSE,
                   (B.JLJGHXYTZMDTSE + B.JZXQMDTSE - B.SQJZMDTSE)
                   * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE/A.SB_MDTSE END)
                          ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_MDSE/A.ZY_MDTSE END)
                     END
                   * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                          WHEN A.ZY_MDSE=0 THEN 1
                          ELSE LEAST(GREATEST(1 - A.SNBL_MDSE / A.ZY_MDSE,0),1)
                     END AS MDE
              FROM CKTS_LC_SHXX A
             INNER JOIN CKTS_SB_MDT_SBDSHZ B ON B.LCSLID=A.LCSLID AND (B.JLJGHXYTZMDTSE + B.JZXQMDTSE - B.SQJZMDTSE)<>0
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC IN ('21','41','51','61','22','42','52','62','23','43','53','63')
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR
            ) T;

    -- 审批退税额、移送国库退税额、国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE), 0)/10000,6), -- 增值税审批
           ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6) -- 办理上年审批结转
      INTO LN_SP_ZZS_XJ, LN_SP_ZZS_HIS, LN_YS_ZZS, LN_BL_ZZS_HIS, LN_BL_ZZS_HIS_JZ, LN_BL_ZZS_HIS_SP
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN (SELECT LCSLID_FS,MIN(FSRQ) AS FSRQ,MIN(YWHZRQ) AS YWHZRQ FROM CKTS_LC_YWHZXX WHERE CKTMSHWYSFWLX_DM='1' GROUP BY LCSLID_FS) S ON S.LCSLID_FS=T.LCSLID_FS
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.LCTJJC IN ('21','22','23')
       AND T.XHRQ_TK>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SELECT ROUND(IFNULL(SUM(T.SEHZ_MDSE), 0)/10000,6), -- 免抵审批
           ROUND(IFNULL(SUM(T.SEHZ_MDSE * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END * T.SNCKZB), 0)/10000,6) -- 办理上年审批结转
      INTO LN_SP_XFS_XJ, LN_SP_XFS_HIS, LN_YS_XFS, LN_BL_XFS_HIS, LN_BL_XFS_HIS_JZ, LN_BL_XFS_HIS_SP
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN CKTS_LC_YWHZXX S ON S.YWHZBUUID=T.YWHZBUUID AND S.CKTMSHWYSFWLX_DM=T.CKTMSHWYSFWLX_DM
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.LCTJJC IN ('21','22','23')
       AND T.XHRQ_MD>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SET LN_SP_ZZS_CUR = LN_SP_ZZS_XJ - LN_SP_ZZS_HIS;
    SET LN_SP_XFS_CUR = LN_SP_XFS_XJ - LN_SP_XFS_HIS;
    SET LN_BL_ZZS_CUR = LN_YS_ZZS - LN_BL_ZZS_HIS;
    SET LN_BL_XFS_CUR = LN_YS_XFS - LN_BL_XFS_HIS;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '12', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE_HIS + LN_SB_CKE_CUR, LN_SB_CKE_HIS, LN_SB_CKE_CUR,
           LN_SB_ZZS_HIS + LN_SB_ZZS_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR,
           LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR,
           LN_SP_ZZS_XJ - TSFN_ZZS_HIS - TSFN_ZZS_CUR,   LN_SP_ZZS_HIS - TSFN_ZZS_HIS, LN_SP_ZZS_CUR - TSFN_ZZS_CUR,
           LN_YS_ZZS                    - TSFN_ZZS_HIS - TSFN_ZZS_CUR, LN_BL_ZZS_HIS - TSFN_ZZS_HIS,
           GREATEST(LN_BL_ZZS_HIS_JZ - TSFN_ZZS_HIS, 0), GREATEST(LN_BL_ZZS_HIS_SP - TSFN_ZZS_HIS, 0),
           LN_BL_ZZS_CUR - TSFN_ZZS_CUR
;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '13', V_SWCODE, 0, 0, 0, 0, 0,
           LN_SB_XFS_HIS + LN_SB_XFS_CUR, LN_SB_XFS_HIS, LN_SB_XFS_CUR,
           LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR,
           LN_SP_XFS_XJ,                  LN_SP_XFS_HIS, LN_SP_XFS_CUR,
           LN_YS_XFS, LN_BL_XFS_HIS, LN_BL_XFS_HIS_JZ, LN_BL_XFS_HIS_SP, LN_BL_XFS_CUR
;
    COMMIT;
  END;

  -- 4、服务贸易
  BEGIN
  DECLARE BJTS_SQLCODE_007 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_007 TEXT DEFAULT '';
    -- 返纳

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_007 = MYSQL_ERRNO, BJTS_SQLERRM_007 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_007;
      SET V_MSG = BJTS_SQLERRM_007;

  END;
SELECT IFNULL(ROUND(SUM(CASE WHEN T.SKSSQZ< LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0)
      INTO TSFN_ZZS_HIS, TSFN_ZZS_CUR
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE S.BAJC_YEAR IN ('40','50','60')
       AND T.CPCODE=S.CPCODE
       AND T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;

    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR IN ('40','50','60');

    SELECT COUNT(DISTINCT T.DJXH),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报退税额
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), -- 申报免抵退税额
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.MDE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.MDE ELSE 0 END), 0)/10000,6) -- 准予
      INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR,
           LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR,
           LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.YSFWYYEMY * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                      WHEN A.SNBL_MDTSE=0 THEN 1
                                      WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                      ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                                 END AS MYLAJ,
                   B.MDTSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                           ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END)
                             END -- 根据是否复审用申报数或复审数计算退税部分
                           * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_ZZSTSE=0 THEN 1
                                  WHEN A.SNBL_ZZSTSE=0 THEN 1
                                  WHEN A.SNBL_ZZSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE,0),1)
                             END AS TSE,
                   B.MDTSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                           ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_MDSE/A.ZY_MDTSE END)
                             END
                           * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDSE=0 THEN 1
                                  WHEN A.SNBL_MDSE=0 THEN 1
                                  WHEN A.SNBL_MDSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDSE / A.ZY_MDSE,0),1)
                             END AS MDE
              FROM CKTS_LC_SHXX A
              LEFT JOIN CKTS_SB_MDT_GJYS B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC IN ('61','62','63')
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR
             UNION ALL
            SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.YSFWYYEMY * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                      WHEN A.SNBL_MDTSE=0 THEN 1
                                      WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                      ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                                 END AS MYLAJ,
                   B.MDTSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                           ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END)
                             END -- 根据是否复审用申报数或复审数计算退税部分
                           * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_ZZSTSE=0 THEN 1
                                  WHEN A.SNBL_ZZSTSE=0 THEN 1
                                  WHEN A.SNBL_ZZSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE,0),1)
                             END AS TSE,
                   B.MDTSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                           ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_MDSE/A.ZY_MDTSE END)
                             END
                           * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDSE=0 THEN 1
                                  WHEN A.SNBL_MDSE=0 THEN 1
                                  WHEN A.SNBL_MDSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDSE / A.ZY_MDSE,0),1)
                             END AS MDE
              FROM CKTS_LC_SHXX A
              LEFT JOIN CKTS_SB_MDT_YFSJ B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC IN ('41','42','43','51','52','53')
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR
             UNION ALL
            SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.SKJEMY *   CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                      WHEN A.SNBL_MDTSE=0 THEN 1
                                      WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                      ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                                 END AS MYLAJ,
                   B.ZZSTSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_ZZSTSE=0 THEN 1
                                    WHEN A.SNBL_ZZSTSE=0 THEN 1
                                    WHEN A.SNBL_ZZSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                    ELSE LEAST(GREATEST(1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE,0),1)
                               END AS TSE,
                   0 AS MDE
              FROM CKTS_LC_SHXX A
              LEFT JOIN CKTS_SB_MTS_YSFW B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC IN ('40','50')
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR) T;

    -- 审批退税额、移送国库退税额、国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE), 0)/10000,6), -- 增值税审批
           ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6) -- 办理上年审批结转
      INTO LN_SP_ZZS_XJ, LN_SP_ZZS_HIS, LN_YS_ZZS, LN_BL_ZZS_HIS, LN_BL_ZZS_HIS_JZ, LN_BL_ZZS_HIS_SP
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN CKTS_LC_YWHZXX S ON S.YWHZBUUID=T.YWHZBUUID AND S.CKTMSHWYSFWLX_DM=T.CKTMSHWYSFWLX_DM
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.LCTJJC IN ('40','41','42','43','50','51','52','53','61','62','63')
       AND T.XHRQ_TK>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SELECT ROUND(IFNULL(SUM(T.SEHZ_MDSE), 0)/10000,6), -- 免抵审批
           ROUND(IFNULL(SUM(T.SEHZ_MDSE * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END * T.SNCKZB), 0)/10000,6) -- 办理上年审批结转
      INTO LN_SP_XFS_XJ, LN_SP_XFS_HIS, LN_YS_XFS, LN_BL_XFS_HIS, LN_BL_XFS_HIS_JZ, LN_BL_XFS_HIS_SP
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN CKTS_LC_YWHZXX S ON S.YWHZBUUID=T.YWHZBUUID AND S.CKTMSHWYSFWLX_DM=T.CKTMSHWYSFWLX_DM
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.LCTJJC IN ('40','41','42','43','50','51','52','53','61','62','63')
       AND T.XHRQ_MD>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SET LN_SP_ZZS_CUR = LN_SP_ZZS_XJ - LN_SP_ZZS_HIS;
    SET LN_SP_XFS_CUR = LN_SP_XFS_XJ - LN_SP_XFS_HIS;
    SET LN_BL_ZZS_CUR = LN_YS_ZZS - LN_BL_ZZS_HIS;
    SET LN_BL_XFS_CUR = LN_YS_XFS - LN_BL_XFS_HIS;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '16', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE_HIS + LN_SB_CKE_CUR, LN_SB_CKE_HIS, LN_SB_CKE_CUR,
           LN_SB_ZZS_HIS + LN_SB_ZZS_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR,
           LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR,
           LN_SP_ZZS_XJ - TSFN_ZZS_HIS - TSFN_ZZS_CUR,   LN_SP_ZZS_HIS - TSFN_ZZS_HIS, LN_SP_ZZS_CUR - TSFN_ZZS_CUR,
           LN_YS_ZZS                    - TSFN_ZZS_HIS - TSFN_ZZS_CUR, LN_BL_ZZS_HIS - TSFN_ZZS_HIS,
           GREATEST(LN_BL_ZZS_HIS_JZ - TSFN_ZZS_HIS, 0), GREATEST(LN_BL_ZZS_HIS_SP - TSFN_ZZS_HIS, 0),
           LN_BL_ZZS_CUR - TSFN_ZZS_CUR
;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '17', V_SWCODE, 0, 0, 0, 0, 0,
           LN_SB_XFS_HIS + LN_SB_XFS_CUR, LN_SB_XFS_HIS, LN_SB_XFS_CUR,
           LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR,
           LN_SP_XFS_XJ,                  LN_SP_XFS_HIS, LN_SP_XFS_CUR,
           LN_YS_XFS, LN_BL_XFS_HIS, LN_BL_XFS_HIS_JZ, LN_BL_XFS_HIS_SP, LN_BL_XFS_CUR
;
    COMMIT;
  END;

  -- 5、其他企业
  BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';
    -- 返纳

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_006;
      SET V_MSG = BJTS_SQLERRM_006;

  END;
SELECT IFNULL(ROUND(SUM(CASE WHEN T.SKSSQZ< LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6), 0)
      INTO TSFN_ZZS_HIS, TSFN_ZZS_CUR
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE S.BAJC_YEAR='30'
       AND T.CPCODE=S.CPCODE
       AND T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;

    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.BAJC_YEAR='30';

    -- 申报户数、申报出口额
    SELECT COUNT(DISTINCT T.DJXH), 0, 0
      INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR
      FROM CKTS_LC_SHXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.LCTJJC='30'
       AND T.QDSJ<LD_NEXTMONTH
       AND T.LCJSRQ>=LD_THISYEAR;

    -- 申报退税额、审核通过退税额、暂缓退税额、不予退税额、在途退税额
    SELECT ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 准予
           ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6) -- 准予
      INTO LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
      FROM (SELECT A.DJXH,B.SBXH,B.KPRQ AS CKRQ_1,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.XFSTSE *  CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                    ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                               END AS TSE
              FROM CKTS_LC_SHXX A
             INNER JOIN CKTS_SB_FZC_SBMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC='30'
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR
             UNION ALL
            SELECT A.DJXH,B.SBXH,B.KPRQ AS CKRQ_1,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.TSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                WHEN A.SNBL_MDTSE=0 THEN 1
                                WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                           END AS TSE
              FROM CKTS_LC_SHXX A
             INNER JOIN CKTS_SB_GJ_SBMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC='30'
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR
             UNION ALL
            SELECT A.DJXH,B.SBXH,B.CKRQ_1,
                   CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                        WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                        WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                        ELSE 40 END AS SHZT,
                   B.TSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                WHEN A.SNBL_MDTSE=0 THEN 1
                                WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                           END AS TSE
              FROM CKTS_LC_SHXX A
             INNER JOIN CKTS_SB_YS_SBMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.LCTJJC='30'
               AND A.QDSJ<LD_NEXTMONTH
               AND A.LCJSRQ>=LD_THISYEAR) T;

    -- 审批退税额、移送国库退税额、国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE), 0)/10000,6), -- 审批
           ROUND(IFNULL(SUM((T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE) * T.SNCKZB), 0)/10000,6), -- 审批上年出口
           ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE + T.GKBL_XFSTSE ELSE 0 END), 0)/10000,6), -- 移送国库
           ROUND(IFNULL(SUM((CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE + T.GKBL_XFSTSE ELSE 0 END) * T.SNCKZB), 0)/10000,6), -- 办理上年出口
           ROUND(IFNULL(SUM(CASE WHEN S.FSRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE + T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6), -- 办理上年结转
           ROUND(IFNULL(SUM(CASE WHEN S.YWHZRQ<LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE + T.GKBL_XFSTSE ELSE 0 END * T.SNCKZB), 0)/10000,6) -- 办理上年审批结转
      INTO LN_SP_ZZS_XJ, LN_SP_ZZS_HIS, LN_YS_ZZS, LN_BL_ZZS_HIS, LN_BL_ZZS_HIS_JZ, LN_BL_ZZS_HIS_SP
      FROM CKTS_LC_SEHZXX T
      LEFT JOIN CKTS_LC_YWHZXX S ON S.YWHZBUUID=T.YWHZBUUID AND S.CKTMSHWYSFWLX_DM=T.CKTMSHWYSFWLX_DM
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.LCTJJC='30'
       AND T.XHRQ_TK>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SET LN_SP_ZZS_CUR = LN_SP_ZZS_XJ - LN_SP_ZZS_HIS;
    SET LN_BL_ZZS_CUR = LN_YS_ZZS - LN_BL_ZZS_HIS;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '19', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE_HIS + LN_SB_CKE_CUR, LN_SB_CKE_HIS, LN_SB_CKE_CUR,
           LN_SB_ZZS_HIS + LN_SB_ZZS_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR,
           LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR,
           LN_SP_ZZS_XJ - TSFN_ZZS_HIS - TSFN_ZZS_CUR,   LN_SP_ZZS_HIS - TSFN_ZZS_HIS, LN_SP_ZZS_CUR - TSFN_ZZS_CUR,
           LN_YS_ZZS                    - TSFN_ZZS_HIS - TSFN_ZZS_CUR, LN_BL_ZZS_HIS - TSFN_ZZS_HIS,
           GREATEST(LN_BL_ZZS_HIS_JZ - TSFN_ZZS_HIS, 0), GREATEST(LN_BL_ZZS_HIS_SP - TSFN_ZZS_HIS, 0),
           LN_BL_ZZS_CUR - TSFN_ZZS_CUR
;

    INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '20', V_SWCODE, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
;
    COMMIT;
  END;

  -- 6、计算行
  BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_005;
      SET V_MSG = BJTS_SQLERRM_005;

  END;
BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_BBLC_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_BBCS_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT TRIM(LPAD(CAST(SUBSTR(T.FORMULA,2,INSTR(T.FORMULA,')')-2) AS CHAR), 2, '0')) AS BBLC,
                          ORA_CONCAT(ORA_CONCAT('(', REPLACE(REPLACE(REPLACE(SUBSTR(T.FORMULA,INSTR(T.FORMULA,'=')+1),'(',''''),'+',','),')','''')), ')') AS BBCS
                     FROM TJBB_REPORT_FORMULA T
                    WHERE T.BBDM='B01109'
                      AND T.TYPE=2
                      AND T.FORMULA<>'(14)=(12)*100/(13)'
                    ORDER BY T.YXJ;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_LSF_XX_BBLC_002, BJTS_LSF_XX_BBCS_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
      BEGIN
        SET LC_SQL = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
                          SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
                          SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
                          SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
                          SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
                          TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
                   SELECT ''', LC_THISMONTH), ''', '''), BJTS_LSF_XX_BBLC_002), ''', '''), V_SWCODE), ''', SUM(RDHS), SUM(SBHS),
                          SUM(SB_CKE_XJ),  SUM(SB_CKE_HIS),  SUM(SB_CKE_CUR),
                          SUM(SB_TMSE_XJ), SUM(SB_TMSE_HIS), SUM(SB_TMSE_CUR),
                          SUM(SH_TMSE_XJ), SUM(SH_TMSE_HIS), SUM(SH_TMSE_CUR),
                          SUM(SP_TMSE_XJ), SUM(SP_TMSE_HIS), SUM(SP_TMSE_CUR),
                          SUM(TK_XJ),      SUM(TK_SB_HIS),   SUM(TK_JZ_HIS),   SUM(TK_WBL_HIS),   SUM(TK_SB_CUR)
                     FROM TJBB_DT_B01109
                    WHERE SWJGDM='''), V_SWCODE), '''
                      AND SSNY='''), LC_THISMONTH), '''
                      AND TRIM(CAST(CAST(BBLC AS DECIMAL(65,30)) AS CHAR)) IN '), BJTS_LSF_XX_BBCS_002);

        SET @BJTS_DYNAMIC_SQL_001 = LC_SQL;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
        COMMIT;
      END;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;
  END;

  -- 7、计算14行
  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_004;
      SET V_MSG = BJTS_SQLERRM_004;

  END;
INSERT INTO TJBB_DT_B01109 (SSNY, BBLC, SWJGDM, RDHS, SBHS,
           SB_CKE_XJ,  SB_CKE_HIS,  SB_CKE_CUR,
           SB_TMSE_XJ, SB_TMSE_HIS, SB_TMSE_CUR,
           SH_TMSE_XJ, SH_TMSE_HIS, SH_TMSE_CUR,
           SP_TMSE_XJ, SP_TMSE_HIS, SP_TMSE_CUR,
           TK_XJ,      TK_SB_HIS,   TK_JZ_HIS,   TK_WBL_HIS,   TK_SB_CUR)
    SELECT LC_THISMONTH, '14', V_SWCODE, NULL, NULL, NULL, NULL, NULL,
           CASE WHEN B.SB_TMSE_XJ=0 THEN 9999.99 ELSE 100 * A.SB_TMSE_XJ/B.SB_TMSE_XJ END,
           CASE WHEN B.SB_TMSE_HIS=0 THEN 9999.99 ELSE 100 * A.SB_TMSE_HIS/B.SB_TMSE_HIS END,
           CASE WHEN B.SB_TMSE_CUR=0 THEN 9999.99 ELSE 100 * A.SB_TMSE_CUR/B.SB_TMSE_CUR END,
           CASE WHEN B.SH_TMSE_XJ=0 THEN 9999.99 ELSE 100 * A.SH_TMSE_XJ/B.SH_TMSE_XJ END,
           CASE WHEN B.SH_TMSE_HIS=0 THEN 9999.99 ELSE 100 * A.SH_TMSE_HIS/B.SH_TMSE_HIS END,
           CASE WHEN B.SH_TMSE_CUR=0 THEN 9999.99 ELSE 100 * A.SH_TMSE_CUR/B.SH_TMSE_CUR END,
           CASE WHEN B.SP_TMSE_XJ=0 THEN 9999.99 ELSE 100 * A.SP_TMSE_XJ/B.SP_TMSE_XJ END,
           CASE WHEN B.SP_TMSE_HIS=0 THEN 9999.99 ELSE 100 * A.SP_TMSE_HIS/B.SP_TMSE_HIS END,
           CASE WHEN B.SP_TMSE_CUR=0 THEN 9999.99 ELSE 100 * A.SP_TMSE_CUR/B.SP_TMSE_CUR END,
           CASE WHEN B.TK_XJ=0 THEN 9999.99 ELSE 100 * A.TK_XJ/B.TK_XJ END,
           CASE WHEN B.TK_SB_HIS=0 THEN 9999.99 ELSE 100 * A.TK_SB_HIS/B.TK_SB_HIS END,
           CASE WHEN B.TK_JZ_HIS=0 THEN 9999.99 ELSE 100 * A.TK_JZ_HIS/B.TK_JZ_HIS END,
           CASE WHEN B.TK_WBL_HIS=0 THEN 9999.99 ELSE 100 * A.TK_WBL_HIS/B.TK_WBL_HIS END,
           CASE WHEN B.TK_SB_CUR=0 THEN 9999.99 ELSE 100 * A.TK_SB_CUR/B.TK_SB_CUR END
      FROM TJBB_DT_B01109 A,
           TJBB_DT_B01109 B
     WHERE A.SWJGDM=V_SWCODE
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='12'
       AND B.SWJGDM=V_SWCODE
       AND B.SSNY=LC_THISMONTH
       AND B.BBLC='13';
    COMMIT;
  END;

  -- 8、更新上年同期列
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;

  END;
UPDATE TJBB_DT_B01109 AS T
       SET SB_CKE_LAST = (SELECT IFNULL(SB_CKE_XJ, 0)
FROM TJBB_DT_B01109 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC),
    SB_TMSE_LAST = (SELECT IFNULL(SB_TMSE_XJ, 0)
FROM TJBB_DT_B01109 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC),
    SH_TMSE_LAST = (SELECT IFNULL(SH_TMSE_XJ, 0)
FROM TJBB_DT_B01109 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC),
    SP_TMSE_LAST = (SELECT IFNULL(SP_TMSE_XJ, 0)
FROM TJBB_DT_B01109 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC),
    TK_LAST = (SELECT IFNULL(TK_XJ, 0)
FROM TJBB_DT_B01109 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC)
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 9、更新占比、同比列
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;

  END;
UPDATE TJBB_DT_B01109 AS T
       SET RD_SB_LV     = CASE WHEN T.RDHS=0         THEN 9999.99 ELSE 100 * T.SBHS/T.RDHS                    END,
    SB_CKE_TBLV  = CASE WHEN T.SB_CKE_LAST=0  THEN 9999.99 ELSE 100 * T.SB_CKE_XJ/T.SB_CKE_LAST -100   END,
    SB_TMSE_TBLV = CASE WHEN T.SB_TMSE_LAST=0 THEN 9999.99 ELSE 100 * T.SB_TMSE_XJ/T.SB_TMSE_LAST -100 END,
    SH_TMSE_TBLV = CASE WHEN T.SH_TMSE_LAST=0 THEN 9999.99 ELSE 100 * T.SH_TMSE_XJ/T.SH_TMSE_LAST -100 END,
    SP_TMSE_TBLV = CASE WHEN T.SP_TMSE_LAST=0 THEN 9999.99 ELSE 100 * T.SP_TMSE_XJ/T.SP_TMSE_LAST -100 END,
    TK_TBLV      = CASE WHEN T.TK_LAST=0      THEN 9999.99 ELSE 100 * T.TK_XJ/T.TK_LAST -100           END
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH
       AND T.BBLC<>'14';
    COMMIT;
  END;

  -- 10、更新汇总列
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B01109 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B01109' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_002 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_002 FROM @BJTS_DYNAMIC_SQL_002;
EXECUTE BJTS_DYNAMIC_STMT_002;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_002;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
