DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_B03_HZ$$

CREATE PROCEDURE PRO_TJBB_B03_HZ
/*
 * 省局月报表，地市局、省局初始化
 * 需要指定区县级税务机关和报表所属期
 */
(
  IN LC_SWJGDM VARCHAR(4000),
  IN LC_MONTH VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_ERROR         DECIMAL(38,10);
  DECLARE LC_MSG           VARCHAR(2000);

  -- 按报表顺序依次制表
    BEGIN
  DECLARE BJTS_SQLCODE_018 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_018 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_018 = MYSQL_ERRNO, BJTS_SQLERRM_018 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03101_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03101_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03101_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_017 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_017 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_017 = MYSQL_ERRNO, BJTS_SQLERRM_017 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03102_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03102_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03102_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_016 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_016 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_016 = MYSQL_ERRNO, BJTS_SQLERRM_016 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03103_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03103_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03103_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_015 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_015 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_015 = MYSQL_ERRNO, BJTS_SQLERRM_015 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03104_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03104_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03104_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_014 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_014 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_014 = MYSQL_ERRNO, BJTS_SQLERRM_014 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03105_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03105_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03105_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_013 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_013 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_013 = MYSQL_ERRNO, BJTS_SQLERRM_013 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03106_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03106_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03106_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_012 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_012 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_012 = MYSQL_ERRNO, BJTS_SQLERRM_012 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03107_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03107_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03107_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_011 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_011 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_011 = MYSQL_ERRNO, BJTS_SQLERRM_011 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03108_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03108_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03108_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_010 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_010 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_010 = MYSQL_ERRNO, BJTS_SQLERRM_010 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03109_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03109_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03109_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_009 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_009 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_009 = MYSQL_ERRNO, BJTS_SQLERRM_009 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03110_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03110_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03110_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_008 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_008 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_008 = MYSQL_ERRNO, BJTS_SQLERRM_008 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03111_CSH失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03111_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03111_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_007 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_007 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_007 = MYSQL_ERRNO, BJTS_SQLERRM_007 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03112_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03112_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03112_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03113_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03113_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03113_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03114_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03114_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03114_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03115_HZ失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03115_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03115_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B02112_HZ_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02112_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B02112_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
/*
    BEGIN
      PRO_TJBB_DT_B02113_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02113_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02113_HZ_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
*/
    BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03116_HZ_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03116_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03116_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03117_HZ_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03117_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03117_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;

END$$

DELIMITER ;
