DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B02112_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B02112_CSH_NEW
/*************************************************
 * 跨境电子商务零售出口退税情况统计表9710
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;
  DECLARE LC_SQL           VARCHAR(4000);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LN_BA_HS         BIGINT;
  DECLARE LN_SB_HS         BIGINT;
  DECLARE LN_SB_CKE        DECIMAL(18,6);
  DECLARE LN_SB_TMSE       DECIMAL(18,6);
  DECLARE LN_SB_TSE        DECIMAL(18,6);
  DECLARE LN_SH_TMSE       DECIMAL(18,6);
  DECLARE LN_SH_TSE        DECIMAL(18,6);

  SET V_ERROR =0;
  SET V_MSG = ' ';
  
  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =TRUNCATE(LD_SYSDATE, 'YY');
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02112 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、有9710业务的外贸企业
  BEGIN
    --备案户数
    SELECT COUNT(DISTINCT A.CPCODE)
      INTO LN_BA_HS
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE AND A.ZX_FLAG <>'R' AND A.JSMODE<>'1'
       AND EXISTS (SELECT 1 FROM CKTS_WBSJ_BGD_9X10 S WHERE S.DJXH=A.CPCODE AND S.TDCODE='9710' AND S.SBYWB_DM<>'A0305001');
    --当月申报
    SELECT COUNT(DISTINCT T.DJXH), IFNULL(ROUND(SUM(T.MYLAJ)/10000,6), 0), 
           IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM<>'A0305001'
       AND T.SBRQ>=LD_SYSDATE AND T.SBRQ<LD_NEXTMONTH;
    --当月审核
    SELECT IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM<>'A0305001'
       AND T.FSRQ>=LD_SYSDATE AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --当月备案有效的
    INSERT INTO TJBB_DT_B02112 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '01', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
;
    COMMIT;
    --当年申报
    SELECT COUNT(DISTINCT T.DJXH), IFNULL(ROUND(SUM(T.MYLAJ)/10000,6), 0), 
           IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM<>'A0305001'
       AND T.SBRQ>=LD_THISYEAR AND T.SBRQ<LD_NEXTMONTH;
    --当年审核
    SELECT IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM<>'A0305001'
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --当年备案有效的
    INSERT INTO TJBB_DT_B02112 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '04', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
;
    COMMIT;
    --累计申报
    SELECT COUNT(DISTINCT T.DJXH), IFNULL(ROUND(SUM(T.MYLAJ)/10000,6), 0), 
           IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM<>'A0305001'
       AND T.SBRQ>=DATE'2013-01-01' AND T.SBRQ<LD_NEXTMONTH;
    --累计审核
    SELECT IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM<>'A0305001'
       AND T.FSRQ>=DATE'2013-01-01' AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --财税〔2013〕96号执行以来
    INSERT INTO TJBB_DT_B02112 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '07', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
;
    COMMIT;
  END;

  --2、有9710业务的生产企业
  BEGIN
    --备案户数
    SELECT COUNT(DISTINCT A.CPCODE)
      INTO LN_BA_HS
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE AND A.ZX_FLAG <>'R' AND A.JSMODE='1'
       AND EXISTS (SELECT 1 FROM CKTS_WBSJ_BGD_9X10 S WHERE S.DJXH=A.CPCODE AND S.TDCODE='9710' AND S.SBYWB_DM='A0305001');
    --当月申报
    SELECT COUNT(DISTINCT T.DJXH), IFNULL(ROUND(SUM(T.MYLAJ)/10000,6), 0), 
           IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END))/10000,6), 0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     INNER JOIN CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM='A0305001'
       AND T.SBRQ>=LD_SYSDATE AND T.SBRQ<LD_NEXTMONTH;
    --当月审核
    SELECT IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE * (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END))/10000,6), 0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     INNER JOIN CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM='A0305001'
       AND T.FSRQ>=LD_SYSDATE AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --当月备案有效的
    INSERT INTO TJBB_DT_B02112 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '02', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
;
    COMMIT;
    --当年申报
    SELECT COUNT(DISTINCT T.DJXH), IFNULL(ROUND(SUM(T.MYLAJ)/10000,6), 0), 
           IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END))/10000,6), 0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     INNER JOIN CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM='A0305001'
       AND T.SBRQ>=LD_THISYEAR AND T.SBRQ<LD_NEXTMONTH;
    --当年审核
    SELECT IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE * (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END))/10000,6), 0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     INNER JOIN CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM='A0305001'
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --当年备案有效的
    INSERT INTO TJBB_DT_B02112 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '05', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
;
    COMMIT;
    --累计申报
    SELECT COUNT(DISTINCT T.DJXH), IFNULL(ROUND(SUM(T.MYLAJ)/10000,6), 0), 
           IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END))/10000,6), 0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     INNER JOIN CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM='A0305001'
       AND T.SBRQ>=DATE'2013-01-01' AND T.SBRQ<LD_NEXTMONTH;
    --累计审核
    SELECT IFNULL(ROUND(SUM(T.MDTSE)/10000,6), 0), IFNULL(ROUND(SUM(T.MDTSE * (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END))/10000,6), 0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM CKTS_WBSJ_BGD_9X10 T
     INNER JOIN CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9710'
       AND T.SBYWB_DM='A0305001'
       AND T.FSRQ>=DATE'2013-01-01' AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --财税〔2013〕96号执行以来
    INSERT INTO TJBB_DT_B02112 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '08', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
;
    COMMIT;
  END;

  BEGIN
    UPDATE TJBB_DT_B02112 
       SET ZYSP = (SELECT S1.MLMC
                     FROM DM_SPML S1, 
                          (SELECT SPML,SUM(MYLAJ) AS USD_TOTAL
                             FROM (SELECT C.SPML,B.MYLAJ
                                     FROM CKTS_LC_SHXX A
                                    INNER JOIN CKTS_WBSJ_BGD_9X10 B ON B.LCSLID=A.LCSLID AND B.TDCODE='9710' AND B.SBYWB_DM<>'A0305001'
                                    INNER JOIN DM_SPFL C ON C.SPDL=SUBSTR(B.CKSP_DM,1,2)
                                    WHERE A.TSSWJG_DM=V_SWCODE
                                      AND A.QDSJ>=DATE'2013-01-01'
                                      AND A.QDSJ<LD_NEXTMONTH) S2
                            GROUP BY SPML
                            ORDER BY USD_TOTAL DESC) S3
                    WHERE S1.SPML=S3.SPML
                      AND ROWNUM=1)
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('01','04','07');
    COMMIT;

    UPDATE TJBB_DT_B02112 
       SET ZYSP = (SELECT S1.MLMC
                     FROM DM_SPML S1, 
                          (SELECT SPML,SUM(MYLAJ) AS USD_TOTAL
                             FROM (SELECT C.SPML,B.MYLAJ
                                     FROM CKTS_LC_SHXX A
                                    INNER JOIN CKTS_WBSJ_BGD_9X10 B ON B.LCSLID=A.LCSLID AND B.TDCODE='9710' AND B.SBYWB_DM='A0305001'
                                    INNER JOIN DM_SPFL C ON C.SPDL=SUBSTR(B.CKSP_DM,1,2)
                                    WHERE A.TSSWJG_DM=V_SWCODE
                                      AND A.QDSJ>=DATE'2013-01-01'
                                      AND A.QDSJ<LD_NEXTMONTH) S2
                            GROUP BY SPML
                            ORDER BY USD_TOTAL DESC) S3
                    WHERE S1.SPML=S3.SPML
                      AND ROWNUM=1)
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('02','05','08');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  --10、计算行
  BEGIN
    FOR LSF_XX IN (SELECT TRIM(DATE_FORMAT(SUBSTR(T.FORMULA,2,INSTR(T.FORMULA,')')-2), '00')) AS BBLC,
                          '('||REPLACE(REPLACE(REPLACE(SUBSTR(T.FORMULA,INSTR(T.FORMULA,'=')+1),'(',''''),'+',','),')','''')||')' AS BBCS
                     FROM TJBB_REPORT_FORMULA T 
                    WHERE T.BBDM='B02112' 
                      AND T.TYPE=2
                    ORDER BY T.YXJ) 
    LOOP
      BEGIN
        SET LC_SQL = 'INSERT INTO TJBB_DT_B02112 (SSNY, BBLC, SWJGDM,
                          BAHS,    SBHS,   SBTSCKE,
                          SB_TMSE, SB_TSE, SB_MDSE,
                          SH_TMSE, SH_TSE, SH_MDSE,
                          BL_TMSE, BL_TSE, BL_MDSE)
                   SELECT '''||LC_THISMONTH||''', '''||LSF_XX.BBLC||''', '''||V_SWCODE||''', 
                          SUM(BAHS),    SUM(SBHS),   SUM(SBTSCKE),
                          SUM(SB_TMSE), SUM(SB_TSE), SUM(SB_MDSE),
                          SUM(SH_TMSE), SUM(SH_TSE), SUM(SH_MDSE),
                          SUM(BL_TMSE), SUM(BL_TSE), SUM(BL_MDSE)
                     FROM TJBB_DT_B02112
                    WHERE SWJGDM='''||V_SWCODE||'''
                      AND SSNY='''||LC_THISMONTH||'''
                      AND TRIM(TO_CHAR(TO_NUMBER(BBLC))) IN '||LSF_XX.BBCS;
        
        EXECUTE IMMEDIATE LC_SQL;
        COMMIT;
      END;
    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  --11、更新汇总列
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B02112 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02112' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
