DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B02108_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B02108_CSH_NEW
/*************************************************
 * 外贸综合服务企业退税情况统计表
 * 返纳数据从金三系统缴款书获取的情形
 * 202202，针对同时申报出口货物劳务以及服务贸易的企业，调整lctjjc
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE         DATETIME;
  DECLARE LC_THISMONTH       VARCHAR(6);
  DECLARE LD_THISYEAR        DATETIME;
  DECLARE LD_NEXTMONTH       DATETIME;
  DECLARE LN_BAHS            BIGINT;

  DECLARE FN_YEAR            DECIMAL(18,6);

  DECLARE LN_SB_CKE_MON      DECIMAL(18,6);
  DECLARE LN_SB_CKE_YEAR     DECIMAL(18,6);
  DECLARE LN_SB_CKE13_MON    DECIMAL(18,6);
  DECLARE LN_SB_CKE13_YEAR   DECIMAL(18,6);

  DECLARE LN_SB_TSE_MON      DECIMAL(18,6);
  DECLARE LN_SB_TSE_YEAR     DECIMAL(18,6);
  DECLARE LN_SB_TSE13_MON    DECIMAL(18,6);
  DECLARE LN_SB_TSE13_YEAR   DECIMAL(18,6);
  DECLARE LN_SH_TSE_MON      DECIMAL(18,6);
  DECLARE LN_SH_TSE_YEAR     DECIMAL(18,6);
  DECLARE LN_SH_TSE13_MON    DECIMAL(18,6);
  DECLARE LN_SH_TSE13_YEAR   DECIMAL(18,6);
  DECLARE LN_BYBL_TSE_MON    DECIMAL(18,6);
  DECLARE LN_BYBL_TSE_YEAR   DECIMAL(18,6);
  DECLARE LN_BYBL_TSE13_MON  DECIMAL(18,6);
  DECLARE LN_BYBL_TSE13_YEAR DECIMAL(18,6);

  DECLARE LN_SP_TSE_MON      DECIMAL(18,6);
  DECLARE LN_SP_TSE_YEAR     DECIMAL(18,6);
  DECLARE LN_YS_TKE_YEAR     DECIMAL(18,6);

  DECLARE LC_SQL_UPDATEHZ    VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =MAKEDATE(YEAR(LD_SYSDATE), 1);
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);
  SET LN_BAHS =0;

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B02108 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、统计
  BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_WZFQY_DJXH_JS_002 LONGTEXT;
  DECLARE BJTS_LSF_WZFQY_NSRSBH_002 LONGTEXT;
  DECLARE BJTS_LSF_WZFQY_NSRMC_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT DJXH_JS, IFNULL(SHXYNO, NSRDJNO) AS NSRSBH, NSRMC
                      FROM GLXT_BB_SHXT_DJXX
                     WHERE SWJGDM=V_SWCODE AND ZX_FLAG ='N' AND BAJC_YEAR IN ('70','71','72');
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_LSF_WZFQY_DJXH_JS_002, BJTS_LSF_WZFQY_NSRSBH_002, BJTS_LSF_WZFQY_NSRMC_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
    BEGIN
      SET LN_BAHS =LN_BAHS +1;

      -- 返纳
      SELECT IFNULL(ROUND(SUM(SJJE)/10000,6), 0)
        INTO FN_YEAR
        FROM FG_CKTSFN_HXZG T
       WHERE T.DJXH=BJTS_LSF_WZFQY_DJXH_JS_002
         AND T.RKRQ>=LD_THISYEAR
         AND T.RKRQ<LD_NEXTMONTH
         AND T.YWHZBUUID IS NULL;

      -- 申报退税出口额 (万美元)
      SELECT ROUND(IFNULL(SUM(CASE WHEN T.LCJSRQ>=LD_SYSDATE THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(T.MYLAJ), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.LCTJJC='71' AND T.LCJSRQ>=LD_SYSDATE THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.LCTJJC='71' THEN T.MYLAJ ELSE 0 END), 0)/10000,6)
        INTO LN_SB_CKE_MON, LN_SB_CKE_YEAR, LN_SB_CKE13_MON, LN_SB_CKE13_YEAR
        FROM (SELECT A.LCJSRQ,A.LCTJJC,B.LCSLID,B.SBXH,
                     B.MYLAJ * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                    WHEN A.ZY_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                    ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                               END AS MYLAJ
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
               WHERE A.DJXH=BJTS_LSF_WZFQY_DJXH_JS_002
                 AND A.LCTJJC IN ('70','71')
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR
               UNION ALL
              SELECT A.LCJSRQ,A.LCTJJC,B.LCSLID,B.SBXH,
                     B.MYLAJ * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                    WHEN A.ZY_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                    ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                               END AS MYLAJ
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_WZF_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
               WHERE A.DJXH=BJTS_LSF_WZFQY_DJXH_JS_002
                 AND A.LCTJJC = '72'
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      -- 申报、审核通过、暂缓、不予、在途退税额
      SELECT ROUND(IFNULL(SUM(CASE WHEN T.LCJSRQ>=LD_SYSDATE THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报退税额
             ROUND(IFNULL(SUM(T.TSE), 0)/10000,6), -- 申报退税额
             ROUND(IFNULL(SUM(CASE WHEN T.LCTJJC='71' AND T.LCJSRQ>=LD_SYSDATE THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报退税额
             ROUND(IFNULL(SUM(CASE WHEN T.LCTJJC='71' THEN T.TSE ELSE 0 END), 0)/10000,6), -- 申报退税额
             ROUND(IFNULL(SUM(CASE WHEN T.SHZT=30 AND T.LCJSRQ>=LD_SYSDATE THEN T.TSE ELSE 0 END), 0)/10000,6), -- 审核通过
             ROUND(IFNULL(SUM(CASE WHEN T.SHZT=30 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 审核通过
             ROUND(IFNULL(SUM(CASE WHEN T.SHZT=30 AND T.LCTJJC='71' AND T.LCJSRQ>=LD_SYSDATE THEN T.TSE ELSE 0 END), 0)/10000,6), -- 审核通过
             ROUND(IFNULL(SUM(CASE WHEN T.SHZT=30 AND T.LCTJJC='71' THEN T.TSE ELSE 0 END), 0)/10000,6), -- 审核通过
             ROUND(IFNULL(SUM(CASE WHEN T.SHZT=20 AND T.LCJSRQ>=LD_SYSDATE THEN T.TSE ELSE 0 END), 0)/10000,6), -- 不予
             ROUND(IFNULL(SUM(CASE WHEN T.SHZT=20 THEN T.TSE ELSE 0 END), 0)/10000,6), -- 不予
             ROUND(IFNULL(SUM(CASE WHEN T.SHZT=20 AND T.LCTJJC='71' AND T.LCJSRQ>=LD_SYSDATE THEN T.TSE ELSE 0 END), 0)/10000,6), -- 不予
             ROUND(IFNULL(SUM(CASE WHEN T.SHZT=20 AND T.LCTJJC='71' THEN T.TSE ELSE 0 END), 0)/10000,6) -- 不予
        INTO LN_SB_TSE_MON, LN_SB_TSE_YEAR, LN_SB_TSE13_MON, LN_SB_TSE13_YEAR,
             LN_SH_TSE_MON, LN_SH_TSE_YEAR, LN_SH_TSE13_MON, LN_SH_TSE13_YEAR,
             LN_BYBL_TSE_MON, LN_BYBL_TSE_YEAR, LN_BYBL_TSE13_MON, LN_BYBL_TSE13_YEAR
        FROM (SELECT B.DJXH,B.SBXH,B.CKRQ_1,B.SZ,A.LCJSRQ,A.LCTJJC,
                     CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                          WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                          WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                          WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                          ELSE 40 END AS SHZT,
                     B.TSE * CASE WHEN B.SZ='V' THEN (CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                                           WHEN A.ZY_ZZSTSE=0 THEN 1
                                                           WHEN A.SNBL_ZZSTSE=0 THEN 1
                                                           WHEN A.SNBL_ZZSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                                           ELSE LEAST(GREATEST(1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE,0),1)
                                                      END)
                             ELSE (CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                        WHEN A.ZY_XFSTSE=0 THEN 1
                                        WHEN A.SNBL_XFSTSE=0 THEN 1
                                        WHEN A.SNBL_XFSTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                        ELSE LEAST(GREATEST(1 - A.SNBL_XFSTSE / A.ZY_XFSTSE,0),1)
                                   END)
                             END AS TSE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_MTS_JHMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
               WHERE A.DJXH=BJTS_LSF_WZFQY_DJXH_JS_002
                 AND A.LCTJJC IN ('70','71')
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR
               UNION ALL
              SELECT B.DJXH,B.SBXH,B.CKRQ_1,'V' AS SZ,A.LCJSRQ,A.LCTJJC,
                     CASE WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.ZBBLBZ='Y' THEN 10
                          WHEN TRIM(A.LCSLID_FS) IS NOT NULL AND B.BYTSBZ='Y' THEN 20
                          WHEN TRIM(A.LCSLID_FS) IS NOT NULL THEN 30
                          WHEN TRIM(A.LCSLID_FS) IS NULL AND A.LCSLID_SB<>A.LCSLID THEN 10
                          ELSE 40 END AS SHZT,
                     B.TSE * CASE WHEN TRIM(A.LCSLID_FS) IS NULL THEN 1
                                  WHEN A.ZY_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE=0 THEN 1
                                  WHEN A.SNBL_MDTSE>0 AND (B.ZBBLBZ='Y' OR B.BYTSBZ='Y') THEN 0
                                  ELSE LEAST(GREATEST(1 - A.SNBL_MDTSE / A.ZY_MDTSE,0),1)
                             END AS TSE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_WZF_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
               WHERE A.DJXH=BJTS_LSF_WZFQY_DJXH_JS_002
                 AND A.LCTJJC = '72'
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      -- 审批、移送国库、国库办理
      SELECT ROUND(IFNULL(SUM(CASE WHEN T.SEHZRQ>=LD_SYSDATE THEN T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE ELSE 0 END), 0)/10000,6), -- 审批
             ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE), 0)/10000,6), -- 审批
             ROUND(IFNULL(SUM(CASE WHEN T.XHRQ_TK<LD_NEXTMONTH THEN T.GKBL_ZZSTSE+T.GKBL_XFSTSE ELSE 0 END), 0)/10000,6) -- 移送国库
        INTO LN_SP_TSE_MON, LN_SP_TSE_YEAR, LN_YS_TKE_YEAR
        FROM CKTS_LC_SEHZXX T
       WHERE T.DJXH=BJTS_LSF_WZFQY_DJXH_JS_002
         AND T.LCTJJC IN ('70','71','72')
         AND T.XHRQ_TK>=LD_THISYEAR
         AND T.SEHZRQ<LD_NEXTMONTH;

      INSERT INTO TJBB_DT_B02108 (SSNY, BBLC, SWJGDM, XH, NSRMC, NSRSBH,
             SB_CKE_MON, SB_CKE_YEAR, SB_CKE13_MON, SB_CKE13_YEAR,
             SB_TSE_MON, SB_TSE_YEAR, SB_TSE13_MON, SB_TSE13_YEAR,
             SH_TSE_MON, SH_TSE_YEAR, SH_TSE13_MON, SH_TSE13_YEAR,
             BYBL_TSE_MON, BYBL_TSE_YEAR, BYBL_TSE13_MON, BYBL_TSE13_YEAR,
             SP_TSE_MON, SP_TSE_YEAR, YS_TKE_YEAR, WS_TKE_YEAR, BL_TKE_YEAR, ZT_TKE_YEAR)
      SELECT LC_THISMONTH, ORA_CONCAT(SUBSTR(V_SWCODE, 4, 4), SUBSTR(ORA_CONCAT('000000', LN_BAHS), LENGTH(ORA_CONCAT('000000', LN_BAHS))-5, 6)), V_SWCODE, LN_BAHS, BJTS_LSF_WZFQY_NSRMC_002, BJTS_LSF_WZFQY_NSRSBH_002,
             LN_SB_CKE_MON, LN_SB_CKE_YEAR, LN_SB_CKE13_MON, LN_SB_CKE13_YEAR,
             LN_SB_TSE_MON, LN_SB_TSE_YEAR, LN_SB_TSE13_MON, LN_SB_TSE13_YEAR,
             LN_SH_TSE_MON, LN_SH_TSE_YEAR, LN_SH_TSE13_MON, LN_SH_TSE13_YEAR,
             LN_BYBL_TSE_MON, LN_BYBL_TSE_YEAR, LN_BYBL_TSE13_MON, LN_BYBL_TSE13_YEAR,
             LN_SP_TSE_MON, LN_SP_TSE_YEAR, LN_YS_TKE_YEAR - FN_YEAR, 0, LN_YS_TKE_YEAR - FN_YEAR, 0
;
    END;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;

  -- 2、行内计算
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;
      LEAVE routine_body;

  END;
UPDATE TJBB_DT_B02108
       SET SHZT_TSE_XJ   = SB_TSE_YEAR   - SH_TSE_YEAR   - BYBL_TSE_YEAR,
    SHZT_TSE13_XJ = SB_TSE13_YEAR - SH_TSE13_YEAR - BYBL_TSE13_YEAR
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 3、汇总栏初始化
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;
      LEAVE routine_body;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B02108 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02108' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
