DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03103_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03103_CSH_NEW
/*************************************************
 * 浙江省办理出口退（免）税情况统计表（全部重新统计）
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);--当月

  DECLARE LD_THISMONTH     DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;
  DECLARE LD_THISYEAR      DATETIME;

  DECLARE LD_THISMONTH_PREV     DATETIME;
  DECLARE LD_NEXTMONTH_PREV     DATETIME;
  DECLARE LD_THISYEAR_PREV      DATETIME;

  DECLARE LN_TS_THISMONTH  DECIMAL(18,6);--本月退库数
  DECLARE LN_MD_THISMONTH  DECIMAL(18,6);--本月免抵数
  DECLARE LN_TS_THISYEAR   DECIMAL(18,6);--本年退库数
  DECLARE LN_MD_THISYEAR   DECIMAL(18,6);--本年免抵数
  DECLARE LN_FN            DECIMAL(18,6);--返纳数
  DECLARE LN_TS_LASTMONTH  DECIMAL(18,6);--上年同期月退库数
  DECLARE LN_MD_LASTMONTH  DECIMAL(18,6);--上年同期月免抵数
  DECLARE LN_TS_LASTYEAR   DECIMAL(18,6);--上年同期年退库数
  DECLARE LN_MD_LASTYEAR   DECIMAL(18,6);--上年同期年免抵数
  DECLARE LN_MD_KTKZY      DECIMAL(18,6);--剩余可调库资源
  DECLARE LC_SWJGMC        VARCHAR(40);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_THISMONTH =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_THISMONTH =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_THISMONTH, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);
  SET LD_THISYEAR =TRUNCATE(LD_THISMONTH, 'YY');

  SET LD_THISMONTH_PREV = DATE_ADD(LD_THISMONTH, INTERVAL -12 MONTH);
  SET LD_NEXTMONTH_PREV = DATE_ADD(LD_NEXTMONTH, INTERVAL -12 MONTH);
  SET LD_THISYEAR_PREV = DATE_ADD(LD_THISYEAR, INTERVAL -12 MONTH);

  SET LC_THISMONTH =DATE_FORMAT(LD_THISMONTH, '%Y%m');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03103 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、制表
  BEGIN
    --税务机关显示名
    SELECT DISPSX
      INTO LC_SWJGMC
      FROM DM_SWJG
     WHERE SWJG_DM=V_SWCODE;
    --本月返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,0), 0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISMONTH AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;
    --本月退库数,免抵数
    SELECT IFNULL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0), 0)
      INTO LN_TS_THISMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISMONTH AND T.XHRQ_TK<LD_NEXTMONTH;
    SELECT IFNULL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0), 0) + LN_TS_THISMONTH - LN_FN
      INTO LN_TS_THISMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISMONTH AND T.XHRQ_XFS<LD_NEXTMONTH;
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,0)
      INTO LN_MD_THISMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISMONTH AND T.XHRQ_MD<LD_NEXTMONTH;
    --本年返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,0), 0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;
    --本年退库数,免抵数
    SELECT IFNULL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0), 0)
      INTO LN_TS_THISYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH;
    SELECT IFNULL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0), 0) + LN_TS_THISYEAR - LN_FN
      INTO LN_TS_THISYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISYEAR AND T.XHRQ_XFS<LD_NEXTMONTH;
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,0)
      INTO LN_MD_THISYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH;
    --可调库资源
    SELECT IFNULL(SUM(T.FS_MDSE), 0)
      INTO LN_MD_KTKZY
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ<LD_NEXTMONTH
       AND T.FS_MDSE>0
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SEHZXX S WHERE S.YWHZBUUID=T.YWHZBUUID AND IFNULL(S.SEHZ_MDSE, 0)+IFNULL(S.BYHZ_MDSE, 0)>0);
    SELECT LN_MD_KTKZY + IFNULL(SUM(T.SEHZ_MDSE - (CASE WHEN T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END)), 0)
      INTO LN_MD_KTKZY
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SET LN_MD_KTKZY =ROUND(LN_MD_KTKZY/10000,0);

    --上年同期返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,0), 0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISMONTH_PREV AND T.RKRQ<LD_NEXTMONTH_PREV
       AND T.YWHZBUUID IS NULL;
    --上年同期退库数,免抵数
    SELECT IFNULL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0), 0)
      INTO LN_TS_LASTMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISMONTH_PREV AND T.XHRQ_TK<LD_NEXTMONTH_PREV;
    SELECT IFNULL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0), 0) + LN_TS_LASTMONTH - LN_FN
      INTO LN_TS_LASTMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISMONTH_PREV AND T.XHRQ_XFS<LD_NEXTMONTH_PREV;
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,0)
      INTO LN_MD_LASTMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISMONTH_PREV AND T.XHRQ_MD<LD_NEXTMONTH_PREV;
    --上年同期返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,0), 0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR_PREV AND T.RKRQ<LD_NEXTMONTH_PREV
       AND T.YWHZBUUID IS NULL;
    --上年同期累计退库数,免抵数
    SELECT IFNULL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0), 0)
      INTO LN_TS_LASTYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR_PREV AND T.XHRQ_TK<LD_NEXTMONTH_PREV;
    SELECT IFNULL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0), 0) + LN_TS_LASTYEAR - LN_FN
      INTO LN_TS_LASTYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISYEAR_PREV AND T.XHRQ_XFS<LD_NEXTMONTH_PREV;
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,0)
      INTO LN_MD_LASTYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR_PREV AND T.XHRQ_MD<LD_NEXTMONTH_PREV;

    INSERT INTO TJBB_DT_B03103 (SSNY,BBLC,SWJGDM,AREA,
           TMSE_MON,TMSE_MON_LAST,TKE_MON,TKE_MON_LAST,TMSE_YEAR,TMSE_YEAR_LAST,TKE_YEAR,TKE_YEAR_LAST,KTKZY)
    SELECT LC_THISMONTH, SUBSTR(V_SWCODE, 4, 4)|| '0001', V_SWCODE, LC_SWJGMC,
           LN_TS_THISMONTH, LN_TS_LASTMONTH, LN_MD_THISMONTH, LN_MD_LASTMONTH,
           LN_TS_THISYEAR, LN_TS_LASTYEAR, LN_MD_THISYEAR, LN_MD_LASTYEAR, LN_MD_KTKZY
;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --2、同比计算
  BEGIN
    UPDATE TJBB_DT_B03103
       SET TMSE_MON_TB = CASE WHEN IFNULL(TMSE_MON_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TMSE_MON / TMSE_MON_LAST -100,1) END,
           TKE_MON_TB = CASE WHEN IFNULL(TKE_MON_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TKE_MON / TKE_MON_LAST -100,1) END,
           TMSE_YEAR_TB = CASE WHEN IFNULL(TMSE_YEAR_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TMSE_YEAR / TMSE_YEAR_LAST -100,1) END,
           TKE_YEAR_TB = CASE WHEN IFNULL(TKE_YEAR_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TKE_YEAR / TKE_YEAR_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --4、汇总栏初始化
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03103 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03103' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
