DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B02105_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B02105_CSH_NEW
/*************************************************
 * 特殊政策退（免）税季度统计表
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;

  DECLARE LN_SBHS          BIGINT;
  DECLARE LN_SB_CKE_HIS    DECIMAL(18,6);
  DECLARE LN_SB_CKE_CUR    DECIMAL(18,6);

  DECLARE LN_SB_ZZS_HIS    DECIMAL(18,6);
  DECLARE LN_SB_ZZS_CUR    DECIMAL(18,6);
  DECLARE LN_SH_ZZS_HIS    DECIMAL(18,6);
  DECLARE LN_SH_ZZS_CUR    DECIMAL(18,6);
  DECLARE LN_BY_ZZS_HIS    DECIMAL(18,6);
  DECLARE LN_BY_ZZS_CUR    DECIMAL(18,6);
  DECLARE LN_ZT_ZZS_HIS    DECIMAL(18,6);
  DECLARE LN_ZT_ZZS_CUR    DECIMAL(18,6);

  DECLARE LN_SB_XFS_HIS    DECIMAL(18,6);
  DECLARE LN_SB_XFS_CUR    DECIMAL(18,6);
  DECLARE LN_SH_XFS_HIS    DECIMAL(18,6);
  DECLARE LN_SH_XFS_CUR    DECIMAL(18,6);
  DECLARE LN_BY_XFS_HIS    DECIMAL(18,6);
  DECLARE LN_BY_XFS_CUR    DECIMAL(18,6);
  DECLARE LN_ZT_XFS_HIS    DECIMAL(18,6);
  DECLARE LN_ZT_XFS_CUR    DECIMAL(18,6);
  DECLARE LC_SQL_INSERT    VARCHAR(4000);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';
  
  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =TRUNCATE(LD_SYSDATE, 'YY');
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02105 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  BEGIN
    --1.1 外轮供应、外航供应、远洋运输供应公司
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MTSBZ,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.TSE   * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS TSE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%WL%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '01', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
;
      COMMIT;
    END;
         
    --1.2 出境口岸免税店
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MTSBZ,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.TSE   * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS TSE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%MSD%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '02', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
;
      COMMIT;
    END;

    --1.4 中标机电产品
     BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), --申报免抵退税额
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), --申报
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END), 0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR,
             LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MDTSNY,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END) 
                               END --根据是否复审用申报数或复审数计算退税部分
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_ZZSTSE=0 THEN 1 
                                    WHEN A.SNBL_ZZSTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE 
                               END AS TSE,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_MDSE/A.ZY_MDTSE END) 
                               END
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDSE=0 THEN 1 
                                    WHEN A.SNBL_MDSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDSE / A.ZY_MDSE 
                               END AS MDE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_MDT_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%ZB%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '04', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR

          UNION ALL
         SELECT LC_THISMONTH, '05', V_SWCODE, 0, 
                0, 0, LN_SB_XFS_HIS, LN_SB_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
;
      COMMIT;
    END;

    --1.6 外商投资企业采购国产设备
     BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 0, 0,
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='N' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='N' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.KPRQ AS CKRQ_1,B.BYTSBZ,C.LCSLID_FS,
                     B.TSE   * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS TSE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_GJ_SBMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH IN ('WZYFJG','GCSB')
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               INNER JOIN GLXT_BB_SHXT_DJXX D ON D.DJXH_JS=A.DJXH AND D.QYLX='2'
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '06', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
;
      COMMIT;
    END;

    --1.7 使（领）馆购买国产物品
    BEGIN
      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '07', V_SWCODE, 0, 
                0, 0, 0, 0, 
                0, 0, 0, 0, 0, 0, 
                0, 0, 0, 0, 0
;
      COMMIT;
    END;

    --1.9 对外承包工程
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), --申报免抵退税额
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), --申报
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END), 0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR,
             LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MDTSNY,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END) 
                               END --根据是否复审用申报数或复审数计算退税部分
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_ZZSTSE=0 THEN 1 
                                    WHEN A.SNBL_ZZSTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE 
                               END AS TSE,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_MDSE/A.ZY_MDTSE END) 
                               END
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDSE=0 THEN 1 
                                    WHEN A.SNBL_MDSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDSE / A.ZY_MDSE 
                               END AS MDE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_MDT_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%DWCB%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '09', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR

          UNION ALL
         SELECT LC_THISMONTH, '10', V_SWCODE, 0, 
                0, 0, LN_SB_XFS_HIS, LN_SB_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
;
      COMMIT;
    END;

    --1.12 对外修理修配
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), --申报免抵退税额
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), --申报
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END), 0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR,
             LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MDTSNY,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END) 
                               END --根据是否复审用申报数或复审数计算退税部分
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_ZZSTSE=0 THEN 1 
                                    WHEN A.SNBL_ZZSTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE 
                               END AS TSE,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_MDSE/A.ZY_MDTSE END) 
                               END
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDSE=0 THEN 1 
                                    WHEN A.SNBL_MDSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDSE / A.ZY_MDSE 
                               END AS MDE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_MDT_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%XLXP%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '12', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR

          UNION ALL
         SELECT LC_THISMONTH, '13', V_SWCODE, 0, 
                0, 0, LN_SB_XFS_HIS, LN_SB_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
;
      COMMIT;
    END;

    --1.15 境外投资
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), --申报免抵退税额
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END), 0)/10000,6), --申报
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END), 0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR,
             LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MDTSNY,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END) 
                               END --根据是否复审用申报数或复审数计算退税部分
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_ZZSTSE=0 THEN 1 
                                    WHEN A.SNBL_ZZSTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE 
                               END AS TSE,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_MDSE/A.ZY_MDTSE END) 
                               END
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDSE=0 THEN 1 
                                    WHEN A.SNBL_MDSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDSE / A.ZY_MDSE 
                               END AS MDE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_MDT_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%JWTZ%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '15', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR

          UNION ALL
         SELECT LC_THISMONTH, '16', V_SWCODE, 0, 
                0, 0, LN_SB_XFS_HIS, LN_SB_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
;
      COMMIT;
    END;

    --1.18 其他
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 0, 0,
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6), 
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END), 0)/10000,6),
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='N' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='N' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
             ROUND(IFNULL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.KPRQ AS CKRQ_1,B.BYTSBZ,C.LCSLID_FS,
                     B.TSE   * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS TSE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_GJ_SBMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               INNER JOIN GLXT_BB_SHXT_DJXX D ON D.DJXH_JS=A.DJXH
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR
                 AND ((B.CKTMSYWLXDMJH IN ('SDQ',' NZYFJG')) OR (B.CKTMSYWLXDMJH='GCSB' AND D.QYLX<>'2'))
               UNION ALL
              SELECT B.DJXH,B.LCSLID,B.SBXH,B.KPRQ AS CKRQ_1,B.BYTSBZ,C.LCSLID_FS,
                     B.XFSTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                     WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                     ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                                END AS TSE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_FZC_SBMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               INNER JOIN GLXT_BB_SHXT_DJXX D ON D.DJXH_JS=A.DJXH
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR
               UNION ALL
              SELECT B.DJXH,B.LCSLID,B.SBXH,B.KPRQ AS CKRQ_1,B.BYTSBZ,C.LCSLID_FS,
                     B.TSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                     WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                     ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                                END AS TSE
                FROM CKTS_LC_SHXX A
               INNER JOIN CKTS_SB_YS_SBMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               INNER JOIN GLXT_BB_SHXT_DJXX D ON D.DJXH_JS=A.DJXH
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR
                 ) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '18', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR

          UNION ALL
         SELECT LC_THISMONTH, '19', V_SWCODE, 0, 
                0, 0, 0, 0, 
                0, 0, 0, 0, 0, 0, 
                0, 0, 0, 0, 0
;
      COMMIT;
    END;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  --10、计算行
  SET LC_SQL_INSERT = 
      'INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, ' ||
              'SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, ' ||
              'SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, ' ||
              'SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, ' ||
              'SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, ' ||
              'SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, ' ||
              'SPTK_TKE_HIS,   SPTK_TKE_YEAR, ' ||
              'YSGK_TKE, ' ||
              'GKBL_TKE_HIS,   GKBL_TKE_YEAR) ' ||
      'SELECT :1, :2 AS BBLC, :3 AS SWJGDM, SUM(SBHS), ' ||
              'SUM(SBLJ_TSCKE_HIS), SUM(SBLJ_TSCKE_YEAR), ' ||
              'SUM(SBLJ_TMSE_HIS),  SUM(SBLJ_TMSE_YEAR), ' ||
              'SUM(SHLJ_TMSE_HIS),  SUM(SHLJ_TMSE_YEAR), ' ||
              'SUM(SHBY_TMSE_HIS),  SUM(SHBY_TMSE_YEAR), ' ||
              'SUM(SHZT_TMSE_HIS),  SUM(SHZT_TMSE_YEAR), ' ||
              'SUM(SPTK_TKE_HIS),   SUM(SPTK_TKE_YEAR), ' ||
              'SUM(YSGK_TKE), ' ||
              'SUM(GKBL_TKE_HIS),   SUM(GKBL_TKE_YEAR) ' ||
        'FROM TJBB_DT_B02105 ' ||
       'WHERE SWJGDM=:4 ' ||
         'AND SSNY=:5 ' ||
         'AND TRIM(TO_CHAR(TO_NUMBER(BBLC))) IN ';

  BEGIN
    FOR LSF_XX IN (SELECT TRIM(DATE_FORMAT(SUBSTR(T.FORMULA,2,INSTR(T.FORMULA,')')-2), '00')) AS BBLC,
                          '('||REPLACE(REPLACE(REPLACE(SUBSTR(T.FORMULA,INSTR(T.FORMULA,'=')+1),'(',''''),'+',','),')','''')||')' AS BBCS
                     FROM TJBB_REPORT_FORMULA T
                    WHERE T.BBDM='B02105'
                      AND T.TYPE=2
                    ORDER BY T.YXJ)
    LOOP
      BEGIN
        EXECUTE IMMEDIATE LC_SQL_INSERT || LSF_XX.BBCS
          USING LC_THISMONTH, LSF_XX.BBLC, V_SWCODE, V_SWCODE, LC_THISMONTH;
        COMMIT;
      END;
    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  --10、更新小计列
  BEGIN
    UPDATE TJBB_DT_B02105
       SET SB_TSCKE_XJ  = SBLJ_TSCKE_HIS + SBLJ_TSCKE_YEAR,
           SB_TMSE_XJ   = SBLJ_TMSE_HIS  + SBLJ_TMSE_YEAR,
           SH_TMSE_XJ   = SHLJ_TMSE_HIS  + SHLJ_TMSE_YEAR,
           SHBY_TMSE_XJ = SHBY_TMSE_HIS  + SHBY_TMSE_YEAR,
           SHZT_TMSE_XJ = SHZT_TMSE_HIS  + SHZT_TMSE_YEAR,
           SPTK_TKE_XJ  = SPTK_TKE_HIS   + SPTK_TKE_YEAR,
           GKBL_TKE_XJ  = GKBL_TKE_HIS   + GKBL_TKE_YEAR,
           ZT_TKE       = YSGK_TKE - GKBL_TKE_HIS - GKBL_TKE_YEAR
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --11、更新汇总列
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B02105 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02105' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
