DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03107_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03107_HZ_NEW
/*************************************************
 * 浙江省出口退（免）税分类管理情况统计表（省、市局汇总）
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);--当月
  DECLARE LC_THISYEAR      VARCHAR(6);--当年1月
  DECLARE LC_LASTMONTH     VARCHAR(6);--上年同期
  DECLARE LC_LASTYEAR      VARCHAR(6);--上年1月
  
  DECLARE LN_TSE_HJ        DECIMAL(16,4);--退税额合计
  DECLARE TSE_1_LAST       DECIMAL(16,4);
  DECLARE TSE_2_LAST       DECIMAL(16,4);
  DECLARE TSE_3_LAST       DECIMAL(16,4);
  DECLARE TSE_4_LAST       DECIMAL(16,4);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;
  
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_THISYEAR =DATE_FORMAT(LD_SYSDATE, '%Y')||'01';
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');
  SET LC_LASTYEAR =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y')||'01';

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03107 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、计算并插入本年明细
  BEGIN
    INSERT INTO TJBB_DT_B03107 (SSNY,BBLC,SWJGDM,SBHS_1,SBHS_2,SBHS_3,SBHS_4,TSE_1_LJ,TSE_2_LJ,TSE_3_LJ,TSE_4_LJ)
    WITH THISYEAR AS (SELECT A.XMFL, A.TS_AMT_ALL, IFNULL(B.FLGLCD, 'C') AS FLGLCD_B, IFNULL(C.KZXX, 'C') AS FLGLCD_C, 
                             ROW_NUMBER() OVER (PARTITION BY A.SWCODE,A.XMFL,A.SSNY,A.SBYWBDM ORDER BY C.ST_DATE DESC) AS RN
                        FROM TJBB_FHXX_CPCODE A
                        LEFT JOIN GLXT_BB_SHXT_DJXX B ON A.XMFL=B.CPCODE
                        LEFT JOIN GS_DJ_CKTMSDAB_KZ C ON A.XMFL=C.CPCODE AND C.KZLX='FLGLCD' AND C.FLAG='1' AND A.SSNY||'01' BETWEEN DATE_FORMAT(C.ST_DATE, '%Y%m%d') AND DATE_FORMAT(C.END_DATE, '%Y%m%d')
                       WHERE ((V_SWCODE='13300000000'  AND (A.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                              (V_SWCODE<>'13300000000' AND (A.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE))))))
                         AND A.SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH)
    SELECT LC_THISMONTH, '01', V_SWCODE, 
           COUNT(DISTINCT CASE WHEN FLGLCD_B='A' THEN XMFL ELSE NULL END),
           COUNT(DISTINCT CASE WHEN FLGLCD_B='B' THEN XMFL ELSE NULL END),
           COUNT(DISTINCT CASE WHEN FLGLCD_B='C' THEN XMFL ELSE NULL END),
           COUNT(DISTINCT CASE WHEN FLGLCD_B='D' THEN XMFL ELSE NULL END),
           ROUND(SUM(CASE WHEN FLGLCD_C='A' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='B' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='C' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='D' THEN TS_AMT_ALL ELSE 0 END)/10000,0)
      FROM THISYEAR
     WHERE RN=1;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --2、更新地区名称
  BEGIN
    UPDATE TJBB_DT_B03107 T
       SET AREA=(SELECT S.SWJG_JC FROM DM_SWJG S WHERE S.SWJG_DM=T.SWJGDM)
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      DO 0;
  END;

  --3、更新上年同期
  BEGIN
    WITH LASTYEAR AS (SELECT A.XMFL, A.TS_AMT_ALL, IFNULL(B.FLGLCD, 'C') AS FLGLCD_B, IFNULL(C.KZXX, 'C') AS FLGLCD_C, 
                             ROW_NUMBER() OVER (PARTITION BY A.SWCODE,A.XMFL,A.SSNY,A.SBYWBDM ORDER BY C.ST_DATE DESC) AS RN
                        FROM TJBB_FHXX_CPCODE A
                        LEFT JOIN GLXT_BB_SHXT_DJXX B ON A.XMFL=B.CPCODE
                        LEFT JOIN GS_DJ_CKTMSDAB_KZ C ON A.XMFL=C.CPCODE AND C.KZLX='FLGLCD' AND C.FLAG='1' AND A.SSNY||'01' BETWEEN DATE_FORMAT(C.ST_DATE, '%Y%m%d') AND DATE_FORMAT(C.END_DATE, '%Y%m%d')
                       WHERE ((V_SWCODE='13300000000'  AND (A.SWCODE IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1'))) OR 
                              (V_SWCODE<>'13300000000' AND (A.SWCODE IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE))))))
                         AND A.SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH)
    SELECT ROUND(SUM(CASE WHEN FLGLCD_C='A' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='B' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='C' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='D' THEN TS_AMT_ALL ELSE 0 END)/10000,0)
      INTO TSE_1_LAST,TSE_2_LAST,TSE_3_LAST,TSE_4_LAST
      FROM LASTYEAR
     WHERE RN=1;
    UPDATE TJBB_DT_B03107 T
       SET (TSE_1_LJ_LAST,TSE_2_LJ_LAST,TSE_3_LJ_LAST,TSE_4_LJ_LAST) = (SELECT TSE_1_LAST,TSE_2_LAST,TSE_3_LAST,TSE_4_LAST)
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      DO 0;
  END;

  --4、同比计算
  BEGIN
    UPDATE TJBB_DT_B03107
       SET TSE_1_TB = CASE WHEN IFNULL(TSE_1_LJ_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TSE_1_LJ / TSE_1_LJ_LAST -100,1) END,
           TSE_2_TB = CASE WHEN IFNULL(TSE_2_LJ_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TSE_2_LJ / TSE_2_LJ_LAST -100,1) END,
           TSE_3_TB = CASE WHEN IFNULL(TSE_3_LJ_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TSE_3_LJ / TSE_3_LJ_LAST -100,1) END,
           TSE_4_TB = CASE WHEN IFNULL(TSE_4_LJ_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TSE_4_LJ / TSE_4_LJ_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --5、占比计算
  BEGIN
    SELECT TSE_1_LJ + TSE_2_LJ + TSE_3_LJ + TSE_4_LJ
      INTO LN_TSE_HJ
      FROM TJBB_DT_B03107
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    
    UPDATE TJBB_DT_B03107 T
       SET TSE_1_ZB = CASE WHEN IFNULL(LN_TSE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * TSE_1_LJ / LN_TSE_HJ,1) END,
           TSE_2_ZB = CASE WHEN IFNULL(LN_TSE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * TSE_2_LJ / LN_TSE_HJ,1) END,
           TSE_3_ZB = CASE WHEN IFNULL(LN_TSE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * TSE_3_LJ / LN_TSE_HJ,1) END,
           TSE_4_ZB = CASE WHEN IFNULL(LN_TSE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * TSE_4_LJ / LN_TSE_HJ,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --6、汇总栏初始化
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03107 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03107' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
