DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_CSH_ONESWJG$$

CREATE PROCEDURE PRO_TJBB_CSH_ONESWJG
/*
 * 单一局，所有报表重置
 */
(
  IN LC_SWJGDM VARCHAR(4000),
	IN V_SSNY VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_MONTH         VARCHAR(6);

  IF V_SSNY IS NOT NULL THEN
    SET LC_MONTH =V_SSNY;
  ELSE
    SET LC_MONTH = DATE_FORMAT(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL -1 MONTH), '%Y%m');
  END IF;

  -- 按报表顺序依次制表
  CALL PRO_TJBB_B01_CSH(LC_SWJGDM,LC_MONTH);
  CALL PRO_TJBB_B02_CSH(LC_SWJGDM,LC_MONTH);
  CALL PRO_TJBB_B04_CSH(LC_SWJGDM,LC_MONTH);
  CALL PRO_TJBB_B05_CSH(LC_SWJGDM,LC_MONTH);
  CALL PRO_TJBB_B06_CSH(LC_SWJGDM,LC_MONTH);

  IF SUBSTR(LC_SWJGDM,-6)='000000' THEN
    CALL PRO_TJBB_B03_HZ(LC_SWJGDM,LC_MONTH);
    CALL PRO_TJBB_B07_HZ(LC_SWJGDM,LC_MONTH);
  ELSE
    CALL PRO_TJBB_B03_CSH(LC_SWJGDM,LC_MONTH);
    CALL PRO_TJBB_B07_CSH(LC_SWJGDM,LC_MONTH);
  END IF;

END$$

DELIMITER ;
