DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B01103_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B01103_CSH_NEW
/*************************************************
 * 未申报出口退（免）税情况统计月报表
 * 202202，针对同时申报出口货物劳务以及服务贸易的企业，调整lctjjc
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LC_PREVYEAR      VARCHAR(4);
  DECLARE LN_WSBHS_XJ      BIGINT;
  DECLARE LN_WSBHS_WM      BIGINT;
  DECLARE LN_WSBHS_WZF     BIGINT;
  DECLARE LN_WSBHS_SC      BIGINT;
  DECLARE LN_WSBHS_FWMY    BIGINT;
  DECLARE LN_WSBWM_XJ      DECIMAL(18,6);
  DECLARE LN_WSBWM_PRE     DECIMAL(18,6);
  DECLARE LN_WSBWM_CUR     DECIMAL(18,6);
  DECLARE LN_WSBWZF_XJ     DECIMAL(18,6);
  DECLARE LN_WSBWZF_PRE    DECIMAL(18,6);
  DECLARE LN_WSBWZF_CUR    DECIMAL(18,6);
  DECLARE LN_WSBSC_XJ      DECIMAL(18,6);
  DECLARE LN_WSBSC_PRE     DECIMAL(18,6);
  DECLARE LN_WSBSC_CUR     DECIMAL(18,6);
  DECLARE LN_WSBFW_XJ      DECIMAL(18,6);
  DECLARE LN_WSBFW_PRE     DECIMAL(18,6);
  DECLARE LN_WSBFW_CUR     DECIMAL(18,6);
  DECLARE TOTAL_USD_AMT    DECIMAL(18,6);
  DECLARE TOTAL_TS_AMT     DECIMAL(18,6);
  DECLARE LN_TSE_PER_USD   DECIMAL(18,6);
  DECLARE LC_SWJGMC        VARCHAR(100);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =MAKEDATE(YEAR(LD_SYSDATE), 1);
  SET LC_PREVYEAR =DATE_FORMAT(DATE_ADD(LD_THISYEAR, INTERVAL -1 MONTH), '%Y');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B01103 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、计算列
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';
    -- 税务机关名称

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;

  END;
SELECT SWJG_MC
      INTO LC_SWJGMC
      FROM DM_SWJG
     WHERE SWJG_DM=V_SWCODE;
    -- 户数
    SELECT COUNT(1),
           IFNULL(SUM(CASE WHEN A.BAJC_YEAR<'40' AND A.JSMODE='1' THEN 1 ELSE 0 END), 0),
           IFNULL(SUM(CASE WHEN A.BAJC_YEAR<'40' AND A.JSMODE='2' THEN 1 ELSE 0 END), 0),
           IFNULL(SUM(CASE WHEN A.BAJC_YEAR>='40' AND A.BAJC_YEAR<'70' THEN 1 ELSE 0 END), 0),
           IFNULL(SUM(CASE WHEN A.BAJC_YEAR>='70' THEN 1 ELSE 0 END), 0)
      INTO LN_WSBHS_XJ,LN_WSBHS_SC,LN_WSBHS_WM,LN_WSBHS_FWMY,LN_WSBHS_WZF
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.JSMODE IN ('1','2')
       AND EXISTS (SELECT 1
                     FROM CKTS_WBSJ_BGD_WSB B
                    WHERE B.TSSWJG_DM=A.SWJGDM
                      AND B.DJXH=A.DJXH_JS);
    -- 生产企业
    SELECT IFNULL(ROUND(SUM(B.MYLAJ)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN B.MYLAJ ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN 0 ELSE B.MYLAJ END)/10000,6), 0)
      INTO LN_WSBSC_XJ,LN_WSBSC_PRE,LN_WSBSC_CUR
      FROM GLXT_BB_SHXT_DJXX A
     INNER JOIN CKTS_WBSJ_BGD_WSB B ON B.TSSWJG_DM=A.SWJGDM AND B.DJXH=A.DJXH_JS
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.JSMODE='1'
       AND A.BAJC_YEAR<'40';
    -- 外贸企业
    SELECT IFNULL(ROUND(SUM(B.MYLAJ)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN B.MYLAJ ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN 0 ELSE B.MYLAJ END)/10000,6), 0)
      INTO LN_WSBWM_XJ,LN_WSBWM_PRE,LN_WSBWM_CUR
      FROM GLXT_BB_SHXT_DJXX A
     INNER JOIN CKTS_WBSJ_BGD_WSB B ON B.TSSWJG_DM=A.SWJGDM AND B.DJXH=A.DJXH_JS
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.JSMODE='2'
       AND A.BAJC_YEAR<'40';
    -- 服务贸易企业
    SELECT IFNULL(ROUND(SUM(B.MYLAJ)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN B.MYLAJ ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN 0 ELSE B.MYLAJ END)/10000,6), 0)
      INTO LN_WSBFW_XJ,LN_WSBFW_PRE,LN_WSBFW_CUR
      FROM GLXT_BB_SHXT_DJXX A
     INNER JOIN CKTS_WBSJ_BGD_WSB B ON B.TSSWJG_DM=A.SWJGDM AND B.DJXH=A.DJXH_JS
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.BAJC_YEAR>='40' AND A.BAJC_YEAR<'70';
    -- 外综服企业
    SELECT IFNULL(ROUND(SUM(B.MYLAJ)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN B.MYLAJ ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN 0 ELSE B.MYLAJ END)/10000,6), 0)
      INTO LN_WSBWZF_XJ,LN_WSBWZF_PRE,LN_WSBWZF_CUR
      FROM GLXT_BB_SHXT_DJXX A
     INNER JOIN CKTS_WBSJ_BGD_WSB B ON B.TSSWJG_DM=A.SWJGDM AND B.DJXH=A.DJXH_JS
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.BAJC_YEAR>='70';
    -- 每美元退税额
    SELECT SUM(T.SB_XSEMY), SUM(IFNULL(T.SB_ZZSTSE, 0)+IFNULL(T.SB_XFSTSE, 0))
      INTO TOTAL_USD_AMT, TOTAL_TS_AMT
      FROM CKTS_LC_SHXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SBYWB_DM IN ('A0301001','A0305001','A0310001')
       AND DATE_FORMAT(T.QDSJ, '%Y') = LC_PREVYEAR;
    SET LN_TSE_PER_USD = CASE WHEN TOTAL_USD_AMT=0 THEN 1 ELSE TOTAL_TS_AMT/TOTAL_USD_AMT END;

    INSERT INTO TJBB_DT_B01103(SSNY,BBLC,SWJGDM,SWJGMC,
                HJ_QYHS,QYHS_WM,QYHS_WZF,QYHS_SC,QYHS_FWMY,
                CK_HJ,
                CK_WM_XJ,CK_WM_HIS,CK_WM_CUR,
                CK_WZF_XJ,CK_WZF_HIS,CK_WZF_CUR,
                CK_SC_XJ,CK_SC_HIS,CK_SC_CUR,
                CK_FWMY_XJ,CK_FWMY_HIS,CK_FWMY_CUR,
                TSE_PER_USD,
                CSTSE_HJ,
                CSTSE_WM_XJ,CSTSE_WM_HIS,CSTSE_WM_CUR,
                CSTSE_WZF_XJ,CSTSE_WZF_HIS,CSTSE_WZF_CUR,
                CSTSE_SC_XJ,CSTSE_SC_HIS,CSTSE_SC_CUR,
                CSTSE_FWMY_XJ,CSTSE_FWMY_HIS,CSTSE_FWMY_CUR)
         SELECT LC_THISMONTH, '01', V_SWCODE, LC_SWJGMC,
                LN_WSBHS_XJ,LN_WSBHS_WM,LN_WSBHS_WZF,LN_WSBHS_SC,LN_WSBHS_FWMY,
                LN_WSBWM_XJ + LN_WSBWZF_XJ + LN_WSBSC_XJ + LN_WSBFW_XJ,
                LN_WSBWM_XJ,                   LN_WSBWM_PRE,                   LN_WSBWM_CUR,
                LN_WSBWZF_XJ,                  LN_WSBWZF_PRE,                  LN_WSBWZF_CUR,
                LN_WSBSC_XJ,                   LN_WSBSC_PRE,                   LN_WSBSC_CUR,
                LN_WSBFW_XJ,                   LN_WSBFW_PRE,                   LN_WSBFW_CUR,
                LN_TSE_PER_USD,
                LN_TSE_PER_USD * (LN_WSBWM_XJ + LN_WSBWZF_XJ + LN_WSBSC_XJ + LN_WSBFW_XJ),
                LN_TSE_PER_USD * LN_WSBWM_XJ,  LN_TSE_PER_USD * LN_WSBWM_PRE,  LN_TSE_PER_USD * LN_WSBWM_CUR,
                LN_TSE_PER_USD * LN_WSBWZF_XJ, LN_TSE_PER_USD * LN_WSBWZF_PRE, LN_TSE_PER_USD * LN_WSBWZF_CUR,
                LN_TSE_PER_USD * LN_WSBSC_XJ,  LN_TSE_PER_USD * LN_WSBSC_PRE,  LN_TSE_PER_USD * LN_WSBSC_CUR,
                LN_TSE_PER_USD * LN_WSBFW_XJ,  LN_TSE_PER_USD * LN_WSBFW_PRE,  LN_TSE_PER_USD * LN_WSBFW_CUR
;
    COMMIT;
  END;

  -- 2、更新汇总列
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B01103 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B01103' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
