DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B01104_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B01104_CSH_NEW
/*************************************************
 * 企业不欲申报出口退税情况统计月报表
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LC_PREVYEAR      VARCHAR(4);
  DECLARE TOTAL_USD_AMT    DECIMAL(18,6);
  DECLARE TOTAL_TS_AMT     DECIMAL(18,6);
  DECLARE LN_TSE_PER_USD   DECIMAL(18,6);
  DECLARE LC_SWJGMC        VARCHAR(100);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =MAKEDATE(YEAR(LD_SYSDATE), 1);
  SET LC_PREVYEAR =DATE_FORMAT(DATE_ADD(LD_THISYEAR, INTERVAL -1 MONTH), '%Y');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B01104 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、全部以0填充
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';
    -- 税务机关名称

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;

  END;
SELECT SWJG_MC
      INTO LC_SWJGMC
      FROM DM_SWJG
     WHERE SWJG_DM=V_SWCODE;
    -- 每美元退税额
    SELECT SUM(T.SB_XSEMY), SUM(IFNULL(T.SB_ZZSTSE, 0)+IFNULL(T.SB_XFSTSE, 0))
      INTO TOTAL_USD_AMT, TOTAL_TS_AMT
      FROM CKTS_LC_SHXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SBYWB_DM IN ('A0301001','A0305001','A0310001')
       AND DATE_FORMAT(T.QDSJ, '%Y') = LC_PREVYEAR;
    SET LN_TSE_PER_USD = CASE WHEN TOTAL_USD_AMT=0 THEN 1 ELSE TOTAL_TS_AMT/TOTAL_USD_AMT END;

    INSERT INTO TJBB_DT_B01104(SSNY,BBLC,SWJGDM,SWJGMC,
                QYHS_HJ,QYHS_WM,QYHS_WZF,QYHS_SC,QYHS_FWMY,
                CKE_HJ,
                CK_WM_XJ,CK_WM_HIS,CK_WM_CUR,
                CK_WZF_XJ,CK_WZF_HIS,CK_WZF_CUR,
                CK_SC_XJ,CK_SC_HIS,CK_SC_CUR,
                CK_FWMY_XJ,CK_FWMY_HIS,CK_FWMY_CUR,
                TSE_PER_USD,
                CSTSE_HJ,
                CSTSE_WM_XJ,CSTSE_WM_HIS,CSTSE_WM_CUR,
                CSTSE_WZF_XJ,CSTSE_WZF_HIS,CSTSE_WZF_CUR,
                CSTSE_SC_XJ,CSTSE_SC_HIS,CSTSE_SC_CUR,
                CSTSE_FWMY_XJ,CSTSE_FWMY_HIS,CSTSE_FWMY_CUR)
         SELECT LC_THISMONTH, '01', V_SWCODE,LC_SWJGMC,
                0, 0, 0, 0, 0,
                0,
                0, 0, 0,
                0, 0, 0,
                0, 0, 0,
                0, 0, 0,
                LN_TSE_PER_USD,
                0,
                0, 0, 0,
                0, 0, 0,
                0, 0, 0,
                0, 0, 0
;
    COMMIT;
  END;

  -- 2、更新汇总列
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B01104 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B01104' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
