DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B01103_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B01103_HZ_NEW
/*************************************************
 * 未申报出口退（免）税情况统计月报表
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LC_PREVYEAR      VARCHAR(4);
  DECLARE TOTAL_USD_AMT    DECIMAL(18,6);
  DECLARE TOTAL_TS_AMT     DECIMAL(18,6);
  DECLARE LN_TSE_PER_USD   DECIMAL(18,6);
  DECLARE LC_SWJGMC        VARCHAR(100);

  SET V_ERROR =0;
  SET V_MSG = ' ';
  
  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =TRUNCATE(LD_SYSDATE, 'YY');
  SET LC_PREVYEAR =DATE_FORMAT(DATE_ADD(LD_THISYEAR, INTERVAL -1 MONTH), '%Y');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B01103 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、计算列
  BEGIN
    --税务机关名称
    IF SUBSTR(V_SWCODE,1,1)='2' THEN
      SELECT VIR_NAME
        INTO LC_SWJGMC
        FROM DM_SWJG_VIRTUAL
       WHERE VIR_SWJGDM=V_SWCODE;
    ELSE
      SELECT SWJG_MC
        INTO LC_SWJGMC
        FROM DM_SWJG
       WHERE SWJG_DM=V_SWCODE;
    END IF;

    --每美元退税额
    SELECT SUM(T.SB_XSEMY), SUM(IFNULL(T.SB_ZZSTSE, 0)+IFNULL(T.SB_XFSTSE, 0))
      INTO TOTAL_USD_AMT, TOTAL_TS_AMT
      FROM CKTS_LC_SHXX T
     WHERE ((V_SWCODE='13300000000' AND T.TSSWJG_DM LIKE '133%') OR
            (V_SWCODE!='13300000000' AND T.TSSWJG_DM IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))))
       AND T.SBYWB_DM IN ('A0301001','A0305001','A0310001')
       AND DATE_FORMAT(T.QDSJ, '%Y') = LC_PREVYEAR;
    SET LN_TSE_PER_USD = CASE WHEN TOTAL_USD_AMT=0 THEN 1 ELSE TOTAL_TS_AMT/TOTAL_USD_AMT END;

    --汇总行
    INSERT INTO TJBB_DT_B01103(SSNY,BBLC,SWJGDM,SWJGMC, 
                HJ_QYHS,QYHS_WM,QYHS_WZF,QYHS_SC,QYHS_FWMY,
                CK_HJ,
                CK_WM_XJ,CK_WM_HIS,CK_WM_CUR,
                CK_WZF_XJ,CK_WZF_HIS,CK_WZF_CUR,
                CK_SC_XJ,CK_SC_HIS,CK_SC_CUR,
                CK_FWMY_XJ,CK_FWMY_HIS,CK_FWMY_CUR,
                TSE_PER_USD,
                CSTSE_HJ,
                CSTSE_WM_XJ,CSTSE_WM_HIS,CSTSE_WM_CUR,
                CSTSE_WZF_XJ,CSTSE_WZF_HIS,CSTSE_WZF_CUR,
                CSTSE_SC_XJ,CSTSE_SC_HIS,CSTSE_SC_CUR,
                CSTSE_FWMY_XJ,CSTSE_FWMY_HIS,CSTSE_FWMY_CUR, 
                HJ_QYHS_HZ,QYHS_WM_HZ,QYHS_WZF_HZ,QYHS_SC_HZ,QYHS_FWMY_HZ,
                CK_HJ_HZ,
                CK_WM_XJ_HZ,CK_WM_HIS_HZ,CK_WM_CUR_HZ,
                CK_WZF_XJ_HZ,CK_WZF_HIS_HZ,CK_WZF_CUR_HZ,
                CK_SC_XJ_HZ,CK_SC_HIS_HZ,CK_SC_CUR_HZ,
                CK_FWMY_XJ_HZ,CK_FWMY_HIS_HZ,CK_FWMY_CUR_HZ,
                TSE_PER_USD_HZ,
                CSTSE_HJ_HZ,
                CSTSE_WM_XJ_HZ,CSTSE_WM_HIS_HZ,CSTSE_WM_CUR_HZ,
                CSTSE_WZF_XJ_HZ,CSTSE_WZF_HIS_HZ,CSTSE_WZF_CUR_HZ,
                CSTSE_SC_XJ_HZ,CSTSE_SC_HIS_HZ,CSTSE_SC_CUR_HZ,
                CSTSE_FWMY_XJ_HZ,CSTSE_FWMY_HIS_HZ,CSTSE_FWMY_CUR_HZ)
         SELECT LC_THISMONTH, '01', V_SWCODE, LC_SWJGMC, 
                SUM(HJ_QYHS),SUM(QYHS_WM),SUM(QYHS_WZF),SUM(QYHS_SC),SUM(QYHS_FWMY),
                SUM(CK_HJ),
                SUM(CK_WM_XJ),SUM(CK_WM_HIS),SUM(CK_WM_CUR),
                SUM(CK_WZF_XJ),SUM(CK_WZF_HIS),SUM(CK_WZF_CUR),
                SUM(CK_SC_XJ),SUM(CK_SC_HIS),SUM(CK_SC_CUR),
                SUM(CK_FWMY_XJ),SUM(CK_FWMY_HIS),SUM(CK_FWMY_CUR),
                LN_TSE_PER_USD,
                LN_TSE_PER_USD * SUM(CK_WM_XJ+CK_WZF_XJ+CK_SC_XJ+CK_FWMY_XJ),
                LN_TSE_PER_USD * SUM(CK_WM_XJ),   LN_TSE_PER_USD * SUM(CK_WM_HIS),   LN_TSE_PER_USD * SUM(CK_WM_CUR),
                LN_TSE_PER_USD * SUM(CK_WZF_XJ),  LN_TSE_PER_USD * SUM(CK_WZF_HIS),  LN_TSE_PER_USD * SUM(CK_WZF_CUR),
                LN_TSE_PER_USD * SUM(CK_SC_XJ),   LN_TSE_PER_USD * SUM(CK_SC_HIS),   LN_TSE_PER_USD * SUM(CK_SC_CUR),
                LN_TSE_PER_USD * SUM(CK_FWMY_XJ), LN_TSE_PER_USD * SUM(CK_FWMY_HIS), LN_TSE_PER_USD * SUM(CK_FWMY_CUR), 
                SUM(HJ_QYHS_HZ),SUM(QYHS_WM_HZ),SUM(QYHS_WZF_HZ),SUM(QYHS_SC_HZ),SUM(QYHS_FWMY_HZ),
                SUM(CK_HJ_HZ),
                SUM(CK_WM_XJ_HZ),SUM(CK_WM_HIS_HZ),SUM(CK_WM_CUR_HZ),
                SUM(CK_WZF_XJ_HZ),SUM(CK_WZF_HIS_HZ),SUM(CK_WZF_CUR_HZ),
                SUM(CK_SC_XJ_HZ),SUM(CK_SC_HIS_HZ),SUM(CK_SC_CUR_HZ),
                SUM(CK_FWMY_XJ_HZ),SUM(CK_FWMY_HIS_HZ),SUM(CK_FWMY_CUR_HZ),
                LN_TSE_PER_USD,
                LN_TSE_PER_USD * SUM(CK_WM_XJ+CK_WZF_XJ+CK_SC_XJ+CK_FWMY_XJ_HZ),
                LN_TSE_PER_USD * SUM(CK_WM_XJ_HZ),   LN_TSE_PER_USD * SUM(CK_WM_HIS_HZ),   LN_TSE_PER_USD * SUM(CK_WM_CUR_HZ),
                LN_TSE_PER_USD * SUM(CK_WZF_XJ_HZ),  LN_TSE_PER_USD * SUM(CK_WZF_HIS_HZ),  LN_TSE_PER_USD * SUM(CK_WZF_CUR_HZ),
                LN_TSE_PER_USD * SUM(CK_SC_XJ_HZ),   LN_TSE_PER_USD * SUM(CK_SC_HIS_HZ),   LN_TSE_PER_USD * SUM(CK_SC_CUR_HZ),
                LN_TSE_PER_USD * SUM(CK_FWMY_XJ_HZ), LN_TSE_PER_USD * SUM(CK_FWMY_HIS_HZ), LN_TSE_PER_USD * SUM(CK_FWMY_CUR_HZ)
           FROM TJBB_DT_B01103 T
          WHERE T.SWJGDM IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE)))
            AND T.SSNY=V_SSNY;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
