DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03103_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03103_CSH_NEW
/*************************************************
 * 浙江省办理出口退（免）税情况统计表（全部重新统计）
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);-- 当月

  DECLARE LD_THISMONTH     DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;
  DECLARE LD_THISYEAR      DATETIME;

  DECLARE LD_THISMONTH_PREV     DATETIME;
  DECLARE LD_NEXTMONTH_PREV     DATETIME;
  DECLARE LD_THISYEAR_PREV      DATETIME;

  DECLARE LN_TS_THISMONTH  DECIMAL(18,6);-- 本月退库数
  DECLARE LN_MD_THISMONTH  DECIMAL(18,6);-- 本月免抵数
  DECLARE LN_TS_THISYEAR   DECIMAL(18,6);-- 本年退库数
  DECLARE LN_MD_THISYEAR   DECIMAL(18,6);-- 本年免抵数
  DECLARE LN_FN            DECIMAL(18,6);-- 返纳数
  DECLARE LN_TS_LASTMONTH  DECIMAL(18,6);-- 上年同期月退库数
  DECLARE LN_MD_LASTMONTH  DECIMAL(18,6);-- 上年同期月免抵数
  DECLARE LN_TS_LASTYEAR   DECIMAL(18,6);-- 上年同期年退库数
  DECLARE LN_MD_LASTYEAR   DECIMAL(18,6);-- 上年同期年免抵数
  DECLARE LN_MD_KTKZY      DECIMAL(18,6);-- 剩余可调库资源
  DECLARE LC_SWJGMC        VARCHAR(40);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_THISMONTH =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_THISMONTH =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_THISMONTH, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);
  SET LD_THISYEAR =MAKEDATE(YEAR(LD_THISMONTH), 1);

  SET LD_THISMONTH_PREV = DATE_ADD(LD_THISMONTH, INTERVAL -12 MONTH);
  SET LD_NEXTMONTH_PREV = DATE_ADD(LD_NEXTMONTH, INTERVAL -12 MONTH);
  SET LD_THISYEAR_PREV = DATE_ADD(LD_THISYEAR, INTERVAL -12 MONTH);

  SET LC_THISMONTH =DATE_FORMAT(LD_THISMONTH, '%Y%m');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_004;
      SET V_MSG = BJTS_SQLERRM_004;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B03103 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、制表
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';
    -- 税务机关显示名

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;
      LEAVE routine_body;

  END;
SELECT DISPSX
      INTO LC_SWJGMC
      FROM DM_SWJG
     WHERE SWJG_DM=V_SWCODE;
    -- 本月返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,0), 0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISMONTH AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;
    -- 本月退库数,免抵数
    SELECT IFNULL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0), 0)
      INTO LN_TS_THISMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISMONTH AND T.XHRQ_TK<LD_NEXTMONTH;
    SELECT IFNULL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0), 0) + LN_TS_THISMONTH - LN_FN
      INTO LN_TS_THISMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISMONTH AND T.XHRQ_XFS<LD_NEXTMONTH;
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,0)
      INTO LN_MD_THISMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISMONTH AND T.XHRQ_MD<LD_NEXTMONTH;
    -- 本年返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,0), 0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;
    -- 本年退库数,免抵数
    SELECT IFNULL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0), 0)
      INTO LN_TS_THISYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH;
    SELECT IFNULL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0), 0) + LN_TS_THISYEAR - LN_FN
      INTO LN_TS_THISYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISYEAR AND T.XHRQ_XFS<LD_NEXTMONTH;
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,0)
      INTO LN_MD_THISYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH;
    -- 可调库资源
    SELECT IFNULL(SUM(T.FS_MDSE), 0)
      INTO LN_MD_KTKZY
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ<LD_NEXTMONTH
       AND T.FS_MDSE>0
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SEHZXX S WHERE S.YWHZBUUID=T.YWHZBUUID AND IFNULL(S.SEHZ_MDSE, 0)+IFNULL(S.BYHZ_MDSE, 0)>0);
    SELECT LN_MD_KTKZY + IFNULL(SUM(T.SEHZ_MDSE - (CASE WHEN T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END)), 0)
      INTO LN_MD_KTKZY
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    SET LN_MD_KTKZY =ROUND(LN_MD_KTKZY/10000,0);

    -- 上年同期返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,0), 0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISMONTH_PREV AND T.RKRQ<LD_NEXTMONTH_PREV
       AND T.YWHZBUUID IS NULL;
    -- 上年同期退库数,免抵数
    SELECT IFNULL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0), 0)
      INTO LN_TS_LASTMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISMONTH_PREV AND T.XHRQ_TK<LD_NEXTMONTH_PREV;
    SELECT IFNULL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0), 0) + LN_TS_LASTMONTH - LN_FN
      INTO LN_TS_LASTMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISMONTH_PREV AND T.XHRQ_XFS<LD_NEXTMONTH_PREV;
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,0)
      INTO LN_MD_LASTMONTH
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISMONTH_PREV AND T.XHRQ_MD<LD_NEXTMONTH_PREV;
    -- 上年同期返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,0), 0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR_PREV AND T.RKRQ<LD_NEXTMONTH_PREV
       AND T.YWHZBUUID IS NULL;
    -- 上年同期累计退库数,免抵数
    SELECT IFNULL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0), 0)
      INTO LN_TS_LASTYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR_PREV AND T.XHRQ_TK<LD_NEXTMONTH_PREV;
    SELECT IFNULL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0), 0) + LN_TS_LASTYEAR - LN_FN
      INTO LN_TS_LASTYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISYEAR_PREV AND T.XHRQ_XFS<LD_NEXTMONTH_PREV;
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,0)
      INTO LN_MD_LASTYEAR
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR_PREV AND T.XHRQ_MD<LD_NEXTMONTH_PREV;

    INSERT INTO TJBB_DT_B03103 (SSNY,BBLC,SWJGDM,AREA,
           TMSE_MON,TMSE_MON_LAST,TKE_MON,TKE_MON_LAST,TMSE_YEAR,TMSE_YEAR_LAST,TKE_YEAR,TKE_YEAR_LAST,KTKZY)
    SELECT LC_THISMONTH, ORA_CONCAT(SUBSTR(V_SWCODE, 4, 4), '0001'), V_SWCODE, LC_SWJGMC,
           LN_TS_THISMONTH, LN_TS_LASTMONTH, LN_MD_THISMONTH, LN_MD_LASTMONTH,
           LN_TS_THISYEAR, LN_TS_LASTYEAR, LN_MD_THISYEAR, LN_MD_LASTYEAR, LN_MD_KTKZY
;
    COMMIT;
  END;

  -- 2、同比计算
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;
      LEAVE routine_body;

  END;
UPDATE TJBB_DT_B03103
       SET TMSE_MON_TB = CASE WHEN IFNULL(TMSE_MON_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TMSE_MON / TMSE_MON_LAST -100,1) END,
    TKE_MON_TB = CASE WHEN IFNULL(TKE_MON_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TKE_MON / TKE_MON_LAST -100,1) END,
    TMSE_YEAR_TB = CASE WHEN IFNULL(TMSE_YEAR_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TMSE_YEAR / TMSE_YEAR_LAST -100,1) END,
    TKE_YEAR_TB = CASE WHEN IFNULL(TKE_YEAR_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TKE_YEAR / TKE_YEAR_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  END;

  -- 4、汇总栏初始化
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03103 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03103' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
