DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B07101_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B07101_CSH_NEW
/*
 * 202210，新增
 * 列参考B01109，行参考B01100（将第39行提到11行，原11-38行依次下移一行）
 * 20260116，根据舟山反馈问题分析，在统计生产企业申报户数、申报出口额、申报免抵退税额口径，提取进料加工数据时加调整数不为0的条件
 */
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_THISYEAR      DATETIME;
  DECLARE LD_NEXTMONTH     DATETIME;
  DECLARE LC_LASTMONTH     VARCHAR(6);

  DECLARE LN_BAHS          BIGINT;
  DECLARE LN_SBHS          BIGINT;
  DECLARE LN_SB_CKE        DECIMAL(18,6);

  DECLARE LN_SB_ZZS        DECIMAL(18,6);
  DECLARE LN_SH_ZZS        DECIMAL(18,6);
  DECLARE LN_SP_ZZS        DECIMAL(18,6);
  DECLARE LN_BL_ZZS        DECIMAL(18,6);
  DECLARE TSFN_ZZS         DECIMAL(18,6);

  DECLARE LN_SB_XFS        DECIMAL(18,6);
  DECLARE LN_SH_XFS        DECIMAL(18,6);
  DECLARE LN_SP_XFS        DECIMAL(18,6);
  DECLARE LN_BL_XFS        DECIMAL(18,6);
  DECLARE TSFN_XFS         DECIMAL(18,6);

  DECLARE LC_SQL           VARCHAR(4000);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_THISYEAR =MAKEDATE(YEAR(LD_SYSDATE), 1);
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_011 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_011 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_011 = MYSQL_ERRNO, BJTS_SQLERRM_011 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_011;
      SET V_MSG = BJTS_SQLERRM_011;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B07101 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、外贸企业
  BEGIN
  DECLARE BJTS_SQLCODE_010 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_010 TEXT DEFAULT '';
    -- 备案户数

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_010 = MYSQL_ERRNO, BJTS_SQLERRM_010 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_010;
      SET V_MSG = BJTS_SQLERRM_010;

  END;
SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='10';

    -- 申报户数、申报出口额
    SELECT COUNT(DISTINCT DJXH), ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE
     FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MTS_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('10','40','50')
           ) T;

    -- 申报退税额
    SELECT ROUND(IFNULL(SUM(CASE WHEN SZ='V' THEN TSE ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN SZ='C' THEN TSE ELSE 0 END), 0)/10000,6)
      INTO LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.SZ,C.TSE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MTS_JHMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('10','40','50')
           ) T;

    -- 审核通过退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.FS_XFSTSE), 0)/10000,6)
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '10';

    -- 审批退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.SEHZ_XFSTSE), 0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC='10';

    -- 国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS, LN_BL_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC='10';

    -- 返纳
    SELECT IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' THEN T.SJJE ELSE 0 END)/10000,6), 0)
      INTO TSFN_ZZS, TSFN_XFS
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR IN ('00','10');

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '05', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '06', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS - TSFN_XFS, LN_BL_XFS - TSFN_XFS
;
    COMMIT;
  END;

  -- 2、外综服企业
  BEGIN
  DECLARE BJTS_SQLCODE_009 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_009 TEXT DEFAULT '';
    -- 备案户数

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_009 = MYSQL_ERRNO, BJTS_SQLERRM_009 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_009;
      SET V_MSG = BJTS_SQLERRM_009;

  END;
SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR IN ('70','71','72');

    -- 申报户数、申报出口额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MTS_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('70','71')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_WZF_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '72'
           ) T;

    -- 申报退税额
    SELECT ROUND(IFNULL(SUM(CASE WHEN SZ='V' THEN TSE ELSE 0 END), 0)/10000,6),
           ROUND(IFNULL(SUM(CASE WHEN SZ='C' THEN TSE ELSE 0 END), 0)/10000,6)
      INTO LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.SZ,C.TSE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MTS_JHMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('70','71')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,'V' AS SZ,C.TSE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_WZF_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '72'
           ) T;

    -- 审核通过退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.FS_XFSTSE), 0)/10000,6)
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('70','71','72');

    -- 审批退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.SEHZ_XFSTSE), 0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('70','71','72');

    -- 国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS, LN_BL_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC IN ('70','71','72');

    -- 返纳
    SELECT IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' THEN T.SJJE ELSE 0 END)/10000,6), 0),
           IFNULL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' THEN T.SJJE ELSE 0 END)/10000,6), 0)
      INTO TSFN_ZZS, TSFN_XFS
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR IN ('70','71','72');

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '08', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '09', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS - TSFN_XFS, LN_BL_XFS - TSFN_XFS
;
    COMMIT;

    -- 2.1 符合13号公告规定业务
    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR IN ('70','71');

    -- 申报户数、申报出口额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MTS_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '71'
           ) T;

    -- 申报退税额
    SELECT ROUND(IFNULL(SUM(TSE), 0)/10000,6)
      INTO LN_SB_ZZS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.SZ,C.TSE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MTS_JHMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '71'
           ) T;

    -- 审核通过退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE), 0)/10000,6)
      INTO LN_SH_ZZS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '71';

    -- 审批退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE), 0)/10000,6)
      INTO LN_SP_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '71';

    -- 国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '71';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '10', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS, LN_BL_ZZS
;
    COMMIT;

    -- 2.2 符合35号公告规定业务
    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR IN ('71','72');

    -- 申报户数、申报出口额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_WZF_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '72'
           ) T;

    -- 申报退税额
    SELECT ROUND(IFNULL(SUM(TSE), 0)/10000,6)
      INTO LN_SB_ZZS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,'V' AS SZ,C.TSE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_WZF_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '72'
           ) T;

    -- 审核通过退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE), 0)/10000,6)
      INTO LN_SH_ZZS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '72';

    -- 审批退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE), 0)/10000,6)
      INTO LN_SP_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '72';

    -- 国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '72';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '11', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS, LN_BL_ZZS
;
    COMMIT;

  END;

  -- 3、生产企业
  BEGIN
  DECLARE BJTS_SQLCODE_008 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_008 TEXT DEFAULT '';
    -- 3.1、自营出口的生产企业
    -- 备案户数

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_008 = MYSQL_ERRNO, BJTS_SQLERRM_008 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_008;
      SET V_MSG = BJTS_SQLERRM_008;

  END;
SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='21';

    -- 申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6),
           ROUND(IFNULL(SUM(TSE), 0)/10000,6),
           ROUND(IFNULL(SUM(MDE), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MDT_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('21','41','51','61')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,'00000000' AS SBXH,0 AS MYLAJ,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MDT_SBDSHZ C ON C.LCSLID=B.LCSLID AND C.JLJGHXYTZMDTSE<>0
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('21','41','51','61')
           ) T;

    -- 审核通过免抵退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.FS_MDSE), 0)/10000,6)
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '21';

    -- 审批免抵退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.SEHZ_MDSE), 0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '21';

    -- 国库办理免抵退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '21';
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,6)
      INTO LN_BL_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC = '21';

    -- 返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '21';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '17', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '18', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
;
    COMMIT;

    -- 3.2、委托出口的生产企业
    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='22';

    -- 申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6),
           ROUND(IFNULL(SUM(TSE), 0)/10000,6),
           ROUND(IFNULL(SUM(MDE), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MDT_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('22','42','52','62')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,'00000000' AS SBXH,0 AS MYLAJ,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MDT_SBDSHZ C ON C.LCSLID=B.LCSLID AND C.JLJGHXYTZMDTSE<>0
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('22','42','52','62')
           ) T;

    -- 审核通过免抵退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.FS_MDSE), 0)/10000,6)
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '22';

    -- 审批免抵退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.SEHZ_MDSE), 0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '22';

    -- 国库办理免抵退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '22';
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,6)
      INTO LN_BL_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC = '22';

    -- 返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '22';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '20', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '21', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
;
    COMMIT;

    -- 3.3、外商投资的生产企业
    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='23';

    -- 申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6),
           ROUND(IFNULL(SUM(TSE), 0)/10000,6),
           ROUND(IFNULL(SUM(MDE), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MDT_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('23','43','53','63')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,'00000000' AS SBXH,0 AS MYLAJ,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MDT_SBDSHZ C ON C.LCSLID=B.LCSLID AND C.JLJGHXYTZMDTSE<>0
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('23','43','53','63')
           ) T;

    -- 审核通过免抵退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.FS_MDSE), 0)/10000,6)
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '23';

    -- 审批免抵退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.SEHZ_MDSE), 0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '23';

    -- 国库办理免抵退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '23';
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,6)
      INTO LN_BL_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC = '23';

    -- 返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '23';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '23', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '24', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
;
    COMMIT;
  END;

  -- 4、服务贸易
  BEGIN
  DECLARE BJTS_SQLCODE_007 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_007 TEXT DEFAULT '';
    -- 4.1、国际运输服务
    -- 备案户数

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_007 = MYSQL_ERRNO, BJTS_SQLERRM_007 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_007;
      SET V_MSG = BJTS_SQLERRM_007;

  END;
SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='60';

    -- 申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6),
           ROUND(IFNULL(SUM(TSE), 0)/10000,6),
           ROUND(IFNULL(SUM(MDE), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.YSFWYYEMY AS MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MDT_GJYS C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('61','62','63')
           ) T;

    -- 审核通过免抵退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.FS_MDSE), 0)/10000,6)
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('61','62','63');

    -- 审批免抵退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.SEHZ_MDSE), 0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('61','62','63');

    -- 国库办理免抵退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC IN ('61','62','63');
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,6)
      INTO LN_BL_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC IN ('61','62','63');

    -- 返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '60';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '29', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '30', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
;
    COMMIT;

    -- 4.1、研发设计服务
    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='50';

    -- 申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6),
           ROUND(IFNULL(SUM(TSE), 0)/10000,6),
           ROUND(IFNULL(SUM(MDE), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.YSFWYYEMY AS MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MDT_YFSJ C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('51','52','53')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.SKJEMY AS MYLAJ,C.ZZSTSE AS TSE, 0 AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MTS_YSFW C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '50'
           ) T;

    -- 审核通过免抵退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.FS_MDSE), 0)/10000,6)
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('50','51','52','53');

    -- 审批免抵退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.SEHZ_MDSE), 0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('50','51','52','53');

    -- 国库办理免抵退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC IN ('50','51','52','53');
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,6)
      INTO LN_BL_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC IN ('50','51','52','53');

    -- 返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '50';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '32', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '33', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
;
    COMMIT;

    -- 4.1、其他服务贸易
    -- 备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='40';

    -- 申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(MYLAJ), 0)/10000,6),
           ROUND(IFNULL(SUM(TSE), 0)/10000,6),
           ROUND(IFNULL(SUM(MDE), 0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.YSFWYYEMY AS MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MDT_YFSJ C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('41','42','43')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.SKJEMY AS MYLAJ,C.ZZSTSE AS TSE, 0 AS MDE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_MTS_YSFW C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '40'
           ) T;

    -- 审核通过免抵退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.FS_MDSE), 0)/10000,6)
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('40','41','42','43');

    -- 审批免抵退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE), 0)/10000,6),
           ROUND(IFNULL(SUM(T.SEHZ_MDSE), 0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('40','41','42','43');

    -- 国库办理免抵退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC IN ('40','41','42','43');
    SELECT ROUND(IFNULL(SUM(T.GKBL_MDSE), 0)/10000,6)
      INTO LN_BL_XFS
      FROM CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC IN ('40','41','42','43');

    -- 返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '40';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '35', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '36', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
;
    COMMIT;
  END;

  -- 5、其他企业
  BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';
    -- 备案户数

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_006;
      SET V_MSG = BJTS_SQLERRM_006;

  END;
SELECT COUNT(1)
      INTO LN_BAHS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='30';

    -- 申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH),
           ROUND(IFNULL(SUM(TSE), 0)/10000,6)
      INTO LN_SBHS, LN_SB_ZZS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.XFSTSE AS TSE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_FZC_SBMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '30'
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.TSE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_GJ_SBMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '30'
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.TSE
              FROM CKTS_LC_SBXX A
             INNER JOIN CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN CKTS_SB_YS_SBMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '30'
           ) T;

    -- 审核通过免抵退税额
    SELECT ROUND(IFNULL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE), 0)/10000,6)
      INTO LN_SH_ZZS
      FROM CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '30';

    -- 审批免抵退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE), 0)/10000,6)
      INTO LN_SP_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '30';

    -- 国库办理免抵退税额
    SELECT ROUND(IFNULL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE), 0)/10000,6)
      INTO LN_BL_ZZS
      FROM CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '30';

    -- 返纳
    SELECT IFNULL(ROUND(SUM(T.SJJE)/10000,6), 0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '30';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '38', V_SWCODE, LN_BAHS, LN_SBHS, 0, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '39', V_SWCODE, 0, 0, 0, 0, 0, 0, 0
;
    COMMIT;
  END;

  -- 6、计算行
  BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_005;
      SET V_MSG = BJTS_SQLERRM_005;

  END;
BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_BBLC_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_BBCS_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT TRIM(LPAD(CAST(SUBSTR(T.FORMULA,2,INSTR(T.FORMULA,')')-2) AS CHAR), 2, '0')) AS BBLC,
                          ORA_CONCAT(ORA_CONCAT('(', REPLACE(REPLACE(REPLACE(SUBSTR(T.FORMULA,INSTR(T.FORMULA,'=')+1),'(',''''),'+',','),')','''')), ')') AS BBCS
                     FROM TJBB_REPORT_FORMULA T
                    WHERE T.BBDM='B07101'
                      AND T.TYPE=2
                      AND T.FORMULA<>'(15)=100 *(13)/(14)'
                    ORDER BY T.YXJ;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_LSF_XX_BBLC_002, BJTS_LSF_XX_BBCS_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
      BEGIN
        SET LC_SQL = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
                   SELECT ''', LC_THISMONTH), ''', '''), BJTS_LSF_XX_BBLC_002), ''', '''), V_SWCODE), ''', SUM(RDHS), SUM(SBHS),
                          SUM(SB_CKE_CUR), SUM(SB_TMSE_CUR), SUM(SH_TMSE_CUR), SUM(SP_TMSE_CUR), SUM(TK_CUR)
                     FROM TJBB_DT_B07101
                    WHERE SWJGDM='''), V_SWCODE), '''
                      AND SSNY='''), LC_THISMONTH), '''
                      AND TRIM(CAST(CAST(BBLC AS DECIMAL(65,30)) AS CHAR)) IN '), BJTS_LSF_XX_BBCS_002);

        SET @BJTS_DYNAMIC_SQL_001 = LC_SQL;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
        COMMIT;
      END;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;
  END;

  -- 7、计算15行
  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_004;
      SET V_MSG = BJTS_SQLERRM_004;

  END;
INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '15', V_SWCODE, NULL, NULL, NULL,
           CASE WHEN B.SB_TMSE_CUR=0 THEN 0 ELSE 100 * A.SB_TMSE_CUR/B.SB_TMSE_CUR END,
           CASE WHEN B.SH_TMSE_CUR=0 THEN 0 ELSE 100 * A.SH_TMSE_CUR/B.SH_TMSE_CUR END,
           CASE WHEN B.SP_TMSE_CUR=0 THEN 0 ELSE 100 * A.SP_TMSE_CUR/B.SP_TMSE_CUR END,
           CASE WHEN B.TK_CUR=0 THEN 0 ELSE 100 * A.TK_CUR/B.TK_CUR END
      FROM TJBB_DT_B07101 A,
           TJBB_DT_B07101 B
     WHERE A.SWJGDM=V_SWCODE
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='13'
       AND B.SWJGDM=V_SWCODE
       AND B.SSNY=LC_THISMONTH
       AND B.BBLC='14';
    COMMIT;
  END;

  -- 8、更新上年同期列
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;

  END;
UPDATE TJBB_DT_B07101 AS T
       SET SB_CKE_LAST = (SELECT IFNULL(SB_CKE_CUR, 0)
FROM TJBB_DT_B07101 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC),
    SB_TMSE_LAST = (SELECT IFNULL(SB_TMSE_CUR, 0)
FROM TJBB_DT_B07101 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC),
    SH_TMSE_LAST = (SELECT IFNULL(SH_TMSE_CUR, 0)
FROM TJBB_DT_B07101 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC),
    SP_TMSE_LAST = (SELECT IFNULL(SP_TMSE_CUR, 0)
FROM TJBB_DT_B07101 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC),
    TK_LAST = (SELECT IFNULL(TK_CUR, 0)
FROM TJBB_DT_B07101 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC)
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 9、更新占比、同比列
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;

  END;
UPDATE TJBB_DT_B07101 AS T
       SET RD_SB_LV     = CASE WHEN T.RDHS=0         THEN 0 ELSE 100 * T.SBHS/T.RDHS                    END,
    SB_CKE_TBLV  = CASE WHEN T.SB_CKE_LAST=0  THEN 0 ELSE 100 * T.SB_CKE_CUR/T.SB_CKE_LAST -100   END,
    SB_TMSE_TBLV = CASE WHEN T.SB_TMSE_LAST=0 THEN 0 ELSE 100 * T.SB_TMSE_CUR/T.SB_TMSE_LAST -100 END,
    SH_TMSE_TBLV = CASE WHEN T.SH_TMSE_LAST=0 THEN 0 ELSE 100 * T.SH_TMSE_CUR/T.SH_TMSE_LAST -100 END,
    SP_TMSE_TBLV = CASE WHEN T.SP_TMSE_LAST=0 THEN 0 ELSE 100 * T.SP_TMSE_CUR/T.SP_TMSE_LAST -100 END,
    TK_TBLV      = CASE WHEN T.TK_LAST=0      THEN 0 ELSE 100 * T.TK_CUR/T.TK_LAST -100           END
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH
       AND T.BBLC<>'15';
    COMMIT;
  END;

  -- 10、更新汇总列
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B07101 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B07101' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_002 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_002 FROM @BJTS_DYNAMIC_SQL_002;
EXECUTE BJTS_DYNAMIC_STMT_002;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_002;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
