DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_CSH_B03B07$$

CREATE PROCEDURE PRO_TJBB_CSH_B03B07
/*
 * 省局月报表/出口退税月报表（不计结转），所有税务局重新制表
 * 需要手工调制报表所属期
 */
(
  IN LC_MONTH VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_SWJGDM        VARCHAR(11);

  -- 区县局
  BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_SWJG_SWJG_DM_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND YXWS=7 ORDER BY SWJG_DM;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_LSF_SWJG_SWJG_DM_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
    SET LC_SWJGDM = BJTS_LSF_SWJG_SWJG_DM_002;

    CALL PRO_TJBB_B03_CSH(LC_SWJGDM,LC_MONTH);
    UPDATE TJBB_TASK AS T
       SET STATUS='20'
     WHERE T.BBDLDM='B03' AND T.SWJGDM=LC_SWJGDM AND NY=LC_MONTH AND T.STATUS<>'20';
    COMMIT;

    CALL PRO_TJBB_B07_CSH(LC_SWJGDM,LC_MONTH);
    UPDATE TJBB_TASK AS T
       SET STATUS='20'
     WHERE T.BBDLDM='B07' AND T.SWJGDM=LC_SWJGDM AND NY=LC_MONTH AND T.STATUS<>'20';
    COMMIT;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;

  -- 地市局
  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_SWJG_SWJG_DM_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND YXWS=5 ORDER BY SWJG_DM;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_SWJG_SWJG_DM_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    SET LC_SWJGDM = BJTS_LSF_SWJG_SWJG_DM_001;

    CALL PRO_TJBB_B03_HZ(LC_SWJGDM,LC_MONTH);
    UPDATE TJBB_TASK AS T
       SET STATUS='20'
     WHERE T.BBDLDM='B03' AND T.SWJGDM=LC_SWJGDM AND NY=LC_MONTH AND T.STATUS<>'20';
    COMMIT;

    CALL PRO_TJBB_B07_HZ(LC_SWJGDM,LC_MONTH);
    UPDATE TJBB_TASK AS T
       SET STATUS='20'
     WHERE T.BBDLDM='B07' AND T.SWJGDM=LC_SWJGDM AND NY=LC_MONTH AND T.STATUS<>'20';
    COMMIT;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  -- 省局
  BEGIN
    SET LC_SWJGDM = '13300000000';

    CALL PRO_TJBB_B03_HZ(LC_SWJGDM,LC_MONTH);
    UPDATE TJBB_TASK AS T
       SET STATUS='20'
     WHERE T.BBDLDM='B03' AND T.SWJGDM=LC_SWJGDM AND NY=LC_MONTH AND T.STATUS<>'20';
    COMMIT;

    CALL PRO_TJBB_B07_HZ(LC_SWJGDM,LC_MONTH);
    UPDATE TJBB_TASK AS T
       SET STATUS='20'
     WHERE T.BBDLDM='B07' AND T.SWJGDM=LC_SWJGDM AND NY=LC_MONTH AND T.STATUS<>'20';
    COMMIT;
  END;
END$$

DELIMITER ;
