DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03115_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03115_CSH_NEW
/*************************************************
 * 浙江省办理出口退税排名统计表
 * 20210205，金额栏保留整数，比率保留小数点后1位
 * 20210928，增加中间表用于每月企业办理数排名，前台报表改为仅显示生产、外贸各前20名，通过下钻显示全部排名
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);--当月
  DECLARE LC_THISYEAR      VARCHAR(6);--当年首月
  DECLARE LC_LASTMONTH     VARCHAR(6);--上年同期

  DECLARE LN_TMSE_HJ            DECIMAL(16,4);--退（免）税额合计
  DECLARE LN_TSE_HJ             DECIMAL(16,4);--退税额合计
  DECLARE LN_MDE_HJ             DECIMAL(16,4);--免抵额合计
  DECLARE LN_TMSE_HJ_LAST       DECIMAL(16,4);--退（免）税额合计
  DECLARE LN_TSE_HJ_LAST        DECIMAL(16,4);--退税额合计
  DECLARE LN_MDE_HJ_LAST        DECIMAL(16,4);--免抵额合计
  DECLARE LN_TMSE_OTHER         DECIMAL(16,4);--退（免）税额合计
  DECLARE LN_TSE_OTHER          DECIMAL(16,4);--退税额合计
  DECLARE LN_MDE_OTHER          DECIMAL(16,4);--免抵额合计
  DECLARE LN_TMSE_OTHER_LAST    DECIMAL(16,4);--退（免）税额合计
  DECLARE LN_TSE_OTHER_LAST     DECIMAL(16,4);--退税额合计
  DECLARE LN_MDE_OTHER_LAST     DECIMAL(16,4);--免抵额合计

  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';
  
  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;
  
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_THISYEAR =DATE_FORMAT(LD_SYSDATE, '%Y')||'01';
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03115_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    DELETE FROM TJBB_DT_B03115 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;
  
  --1、中间表数据计算
  BEGIN
    INSERT INTO TJBB_DT_B03115_MID (SWJGDM,SSNY,JSMODE,DJXH,TMSE,TSE,MDE,CKPM_1)
    SELECT V_SWCODE, LC_THISMONTH, A.JSMODE, B.DJXH, ROUND(SUM(B.SEHZ_MDTSE)/10000,4), ROUND(SUM(B.SEHZ_ZZSTSE + B.SEHZ_XFSTSE)/10000,4), ROUND(SUM(B.SEHZ_MDSE)/10000,4), 
           ROW_NUMBER() OVER (PARTITION BY A.JSMODE ORDER BY SUM(B.SEHZ_MDTSE) DESC) AS PM
      FROM GLXT_BB_SHXT_DJXX A, CKTS_LC_SEHZXX B
     WHERE A.SWJGDM=V_SWCODE
       AND A.JSMODE IN ('1','2')
       AND A.DJXH_JS=B.DJXH
       AND DATE_FORMAT(B.SEHZRQ, '%Y%m') BETWEEN LC_THISYEAR AND LC_THISMONTH
     GROUP BY B.DJXH, A.JSMODE;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;
  
  --2、计算并插入本年生产、外贸各20名及上年同期
  BEGIN
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,JSMODEMC,SWJG,TMSE,TSE,MDE,XH,TMSE_LAST,TSE_LAST,MDE_LAST)
    SELECT A.SSNY, A.JSMODE||SUBSTR('00'||A.CKPM_1,-2), V_SWCODE, A.DJXH, IFNULL(B.SHXYNO, B.NSRDJNO), B.NSRMC, A.JSMODE, CASE WHEN A.JSMODE='1' THEN '生产' ELSE '外贸' END,
           A.SWJGDM, A.TMSE, A.TSE, A.MDE, A.CKPM_1, C.TMSE, C.TSE, C.MDE
      FROM TJBB_DT_B03115_MID A
     INNER JOIN GLXT_BB_SHXT_DJXX B ON B.DJXH_JS=A.DJXH
      LEFT JOIN TJBB_DT_B03115_MID C ON C.DJXH=A.DJXH AND C.SSNY=LC_LASTMONTH
     WHERE A.SSNY=LC_THISMONTH
       AND A.JSMODE IN ('1','2')
       AND A.SWJGDM=V_SWCODE
       AND A.CKPM_1<=20;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;
  
  --3、计算并插入合计数、小计数与其他数
  BEGIN
    SELECT SUM(TMSE),SUM(TSE),SUM(MDE)
      INTO LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ
      FROM TJBB_DT_B03115_MID A
     WHERE A.SSNY=LC_THISMONTH
       AND A.JSMODE IN ('1','2')
       AND A.SWJGDM=V_SWCODE;
    SELECT SUM(TMSE),SUM(TSE),SUM(MDE)
      INTO LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST
      FROM TJBB_DT_B03115_MID A
     WHERE A.SSNY=LC_LASTMONTH
       AND A.JSMODE IN ('1','2')
       AND A.SWJGDM=V_SWCODE;
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '000', V_SWCODE,NULL,NULL,'合计',NULL,NULL,LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ,LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST,NULL
;
    COMMIT;
    
    SELECT SUM(TMSE),SUM(TSE),SUM(MDE)
      INTO LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ
      FROM TJBB_DT_B03115_MID A
     WHERE A.SSNY=LC_THISMONTH
       AND A.JSMODE ='1'
       AND A.SWJGDM=V_SWCODE;
    SELECT SUM(TMSE),SUM(TSE),SUM(MDE)
      INTO LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST
      FROM TJBB_DT_B03115_MID A
     WHERE A.SSNY=LC_LASTMONTH
       AND A.JSMODE ='1'
       AND A.SWJGDM=V_SWCODE;
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '100', V_SWCODE,NULL,NULL,'生产小计',NULL,NULL,LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ,LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST,NULL
;
    COMMIT;
    
    SELECT LN_TMSE_HJ - SUM(A.TMSE), LN_TSE_HJ - SUM(A.TSE), LN_MDE_HJ - SUM(A.MDE), 
           LN_TMSE_HJ_LAST - SUM(A.TMSE_LAST), LN_TSE_HJ_LAST - SUM(A.TSE_LAST), LN_MDE_HJ_LAST - SUM(A.MDE_LAST)
      INTO LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM=V_SWCODE AND A.SSNY=LC_THISMONTH AND A.BBLC>'100' AND A.BBLC<'200';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '199', V_SWCODE,NULL,NULL,'生产其他',NULL,NULL,LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST,NULL
;
    COMMIT;
    
    SELECT SUM(TMSE),SUM(TSE),SUM(MDE)
      INTO LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ
      FROM TJBB_DT_B03115_MID A
     WHERE A.SSNY=LC_THISMONTH
       AND A.JSMODE ='2'
       AND A.SWJGDM=V_SWCODE;
    SELECT SUM(TMSE),SUM(TSE),SUM(MDE)
      INTO LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST
      FROM TJBB_DT_B03115_MID A
     WHERE A.SSNY=LC_LASTMONTH
       AND A.JSMODE ='2'
       AND A.SWJGDM=V_SWCODE;
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '200', V_SWCODE,NULL,NULL,'外贸小计',NULL,NULL,LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ,LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST,NULL
;
    COMMIT;
    
    SELECT LN_TMSE_HJ - SUM(A.TMSE), LN_TSE_HJ - SUM(A.TSE), LN_MDE_HJ - SUM(A.MDE), 
           LN_TMSE_HJ_LAST - SUM(A.TMSE_LAST), LN_TSE_HJ_LAST - SUM(A.TSE_LAST), LN_MDE_HJ_LAST - SUM(A.MDE_LAST)
      INTO LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM=V_SWCODE AND A.SSNY=LC_THISMONTH AND A.BBLC>'200';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '299', V_SWCODE,NULL,NULL,'外贸其他',NULL,NULL,LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST,NULL
;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      DO 0;
  END;

  --4、同比计算
  BEGIN
    UPDATE TJBB_DT_B03115
       SET TMSE_TB = CASE WHEN IFNULL(TMSE_LAST, 0)=0 THEN NULL ELSE ROUND(100 * TMSE / TMSE_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --5、汇总栏初始化
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03115 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03115' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
