DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B05101_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B05101_CSH_NEW
/**************************************************************
 * 跨境电商统计表——跨境电商出口情况统计表
 **************************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_INITDATE      DATETIME;
  DECLARE LD_NEXTDATE      DATETIME;
  DECLARE LC_INITMONTH     VARCHAR(6);

  DECLARE LN_CKE_9610_HS      DECIMAL(16,4);
  DECLARE LN_CKE_9610_JE      DECIMAL(16,4);
  DECLARE LN_TMS_9610_HS      DECIMAL(16,4);
  DECLARE LN_TMS_9610_JE      DECIMAL(16,4);
  DECLARE LN_CKE_9710_HS      DECIMAL(16,4);
  DECLARE LN_CKE_9710_JE      DECIMAL(16,4);
  DECLARE LN_TMS_9710_HS      DECIMAL(16,4);
  DECLARE LN_TMS_9710_JE      DECIMAL(16,4);
  DECLARE LN_CKE_9810_HS      DECIMAL(16,4);
  DECLARE LN_CKE_9810_JE      DECIMAL(16,4);
  DECLARE LN_TMS_9810_HS      DECIMAL(16,4);
  DECLARE LN_TMS_9810_JE      DECIMAL(16,4);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =MAKEDATE(YEAR(CURRENT_TIMESTAMP), 1);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B05101 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、统计
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;
      LEAVE routine_body;

  END;
SET LD_INITDATE = STR_TO_DATE('2019-01-01', '%Y-%m-%d');
    BJTS_LOOP_001: LOOP
      IF LD_INITDATE >LD_SYSDATE THEN LEAVE BJTS_LOOP_001; END IF;
      SET LC_INITMONTH =DATE_FORMAT(LD_INITDATE, '%Y%m');
      SET LD_NEXTDATE = DATE_ADD(LD_INITDATE, INTERVAL 1 MONTH);

      SELECT COUNT(DISTINCT T.DJXH), ROUND(IFNULL(SUM(T.RMBLAJ), 0)/10000,4)
        INTO LN_CKE_9610_HS, LN_CKE_9610_JE
        FROM CKTS_WBSJ_HG_BGD T
       WHERE T.TSSWJG_DM_1=V_SWCODE
         AND T.JGFS_DM='9610'
         AND T.CKRQ_1>=LD_INITDATE AND T.CKRQ_1<LD_NEXTDATE;
      SELECT COUNT(DISTINCT T.DJXH), ROUND(IFNULL(SUM(T.RMBLAJ), 0)/10000,4)
        INTO LN_CKE_9710_HS, LN_CKE_9710_JE
        FROM CKTS_WBSJ_HG_BGD T
       WHERE T.TSSWJG_DM_1=V_SWCODE
         AND T.JGFS_DM='9710'
         AND T.CKRQ_1>=LD_INITDATE AND T.CKRQ_1<LD_NEXTDATE;
      SELECT COUNT(DISTINCT T.DJXH), ROUND(IFNULL(SUM(T.RMBLAJ), 0)/10000,4)
        INTO LN_CKE_9810_HS, LN_CKE_9810_JE
        FROM CKTS_WBSJ_HG_BGD T
       WHERE T.TSSWJG_DM_1=V_SWCODE
         AND T.JGFS_DM='9810'
         AND T.CKRQ_1>=LD_INITDATE AND T.CKRQ_1<LD_NEXTDATE;

      SELECT COUNT(DISTINCT A.DJXH), ROUND(IFNULL(SUM(A.MDTSE), 0)/10000,4)
        INTO LN_TMS_9610_HS, LN_TMS_9610_JE
        FROM CKTS_WBSJ_BGD_9X10 A
       WHERE A.TSSWJG_DM=V_SWCODE
         AND A.SBRQ>=LD_INITDATE AND A.SBRQ<LD_NEXTDATE
         AND A.TDCODE='9610';
      SELECT COUNT(DISTINCT A.DJXH), ROUND(IFNULL(SUM(A.MDTSE), 0)/10000,4)
        INTO LN_TMS_9710_HS, LN_TMS_9710_JE
        FROM CKTS_WBSJ_BGD_9X10 A
       WHERE A.TSSWJG_DM=V_SWCODE
         AND A.SBRQ>=LD_INITDATE AND A.SBRQ<LD_NEXTDATE
         AND A.TDCODE='9710';
      SELECT COUNT(DISTINCT A.DJXH), ROUND(IFNULL(SUM(A.MDTSE), 0)/10000,4)
        INTO LN_TMS_9810_HS, LN_TMS_9810_JE
        FROM CKTS_WBSJ_BGD_9X10 A
       WHERE A.TSSWJG_DM=V_SWCODE
         AND A.SBRQ>=LD_INITDATE AND A.SBRQ<LD_NEXTDATE
         AND A.TDCODE='9810';

      INSERT INTO TJBB_DT_B05101 (
             SSNY,BBLC,SWJGDM,QJNY,
             CKE_9610_HS, CKE_9610_HS_HZ, CKE_9610_JE, CKE_9610_JE_HZ, TMS_9610_HS, TMS_9610_HS_HZ, TMS_9610_JE, TMS_9610_JE_HZ,
             CKE_9710_HS, CKE_9710_HS_HZ, CKE_9710_JE, CKE_9710_JE_HZ, TMS_9710_HS, TMS_9710_HS_HZ, TMS_9710_JE, TMS_9710_JE_HZ,
             CKE_9810_HS, CKE_9810_HS_HZ, CKE_9810_JE, CKE_9810_JE_HZ, TMS_9810_HS, TMS_9810_HS_HZ, TMS_9810_JE, TMS_9810_JE_HZ)
      SELECT LC_THISMONTH, LC_INITMONTH,V_SWCODE,LC_INITMONTH,
             LN_CKE_9610_HS, LN_CKE_9610_HS, LN_CKE_9610_JE, LN_CKE_9610_JE, LN_TMS_9610_HS, LN_TMS_9610_HS, LN_TMS_9610_JE, LN_TMS_9610_JE,
             LN_CKE_9710_HS, LN_CKE_9710_HS, LN_CKE_9710_JE, LN_CKE_9710_JE, LN_TMS_9710_HS, LN_TMS_9710_HS, LN_TMS_9710_JE, LN_TMS_9710_JE,
             LN_CKE_9810_HS, LN_CKE_9810_HS, LN_CKE_9810_JE, LN_CKE_9810_JE, LN_TMS_9810_HS, LN_TMS_9810_HS, LN_TMS_9810_JE, LN_TMS_9810_JE
;
      SET LD_INITDATE = LD_NEXTDATE;
    END LOOP BJTS_LOOP_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
