DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03116_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03116_HZ_NEW
/**************************************************************
 * 跨境电子商务零售出口退税情况统计表9810（省、市局汇总）
 * 202504，根据省局关注点全新设计，分出口电子信息、申报（其中预退税）、办理（其中预退税）
 **************************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03116 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、统计
  BEGIN
    INSERT INTO TJBB_DT_B03116 (SSNY,SWJGDM,BBLC,
           CK_HS, CK_MYLAJ, CK_RMBLAJ,
           SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE,
           SB_YTS_HS, SB_YTS_MYXSE, SB_YTS_JSJE, SB_YTS_TMSE,
           BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE,
           BL_YTS_HS, BL_YTS_MYXSE, BL_YTS_JSJE, BL_YTS_TMSE)
    SELECT LC_THISMONTH, V_SWCODE, BBLC, 
           SUM(CK_HS), SUM(CK_MYLAJ), SUM(CK_RMBLAJ),
           SUM(SB_HS), SUM(SB_MYXSE), SUM(SB_JSJE), SUM(SB_TMSE),
           SUM(SB_YTS_HS), SUM(SB_YTS_MYXSE), SUM(SB_YTS_JSJE), SUM(SB_YTS_TMSE),
           SUM(BL_HS), SUM(BL_MYXSE), SUM(BL_JSJE), SUM(BL_TMSE),
           SUM(BL_YTS_HS), SUM(BL_YTS_MYXSE), SUM(BL_YTS_JSJE), SUM(BL_YTS_TMSE)
      FROM TJBB_DT_B03116
     WHERE SWJGDM IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE))) 
       AND SSNY=LC_THISMONTH
     GROUP BY BBLC;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --11、更新汇总列
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03116 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03116' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
