DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03114_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03114_CSH_NEW
/*************************************************
 * 对“一带一路”国家出口退（免）税情况统计表
 * 表结构与浙江省分出口市场统计表一样，算法条件有变化
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);-- 当月
  DECLARE LC_THISYEAR      VARCHAR(6);-- 当年1月
  DECLARE LC_LASTMONTH     VARCHAR(6);-- 上年同期
  DECLARE LC_LASTYEAR      VARCHAR(6);-- 上年1月

  DECLARE LN_CKE_HJ        DECIMAL(16,4);-- 出口额合计
  DECLARE LN_TSE_HJ        DECIMAL(16,4);-- 退税额合计
  DECLARE LN_CKE_HJ_LAST   DECIMAL(16,4);-- 出口额合计
  DECLARE LN_TSE_HJ_LAST   DECIMAL(16,4);-- 退税额合计
  DECLARE LN_CKE_OTHER     DECIMAL(16,4);-- 出口额合计
  DECLARE LN_TSE_OTHER     DECIMAL(16,4);-- 退税额合计
  DECLARE LN_CKE_OTHER_LAST     DECIMAL(16,4);-- 出口额合计
  DECLARE LN_TSE_OTHER_LAST     DECIMAL(16,4);-- 退税额合计

  DECLARE V_TEMP           BIGINT DEFAULT 0;
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_THISYEAR =ORA_CONCAT(DATE_FORMAT(LD_SYSDATE, '%Y'), '01');
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');
  SET LC_LASTYEAR =ORA_CONCAT(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y'), '01');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_007 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_007 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_007 = MYSQL_ERRNO, BJTS_SQLERRM_007 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_007;
      SET V_MSG = BJTS_SQLERRM_007;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B03114_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    DELETE FROM TJBB_DT_B03114 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、中间表数据计算
  BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_006;
      SET V_MSG = BJTS_SQLERRM_006;

  END;
INSERT INTO TJBB_DT_B03114_MID (SWJGDM,SSNY,DMTYPE,GBDM,CKE_LJ,TSE_LJ,CKPM)
    SELECT V_SWCODE, LC_THISMONTH, 'BR', DQ_CODE, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
      FROM (SELECT A.DQ_CODE, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM DM_DQCODE A
             INNER JOIN DM_DQGROUP B ON A.DQ_CODE=B.DQ_CODE
              LEFT JOIN TJBB_FHXX_GBCODE C ON B.GB_CODE=C.XMFL AND C.SWCODE=V_SWCODE AND C.SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH
             WHERE A.DQ_TYPE='BR'
             GROUP BY A.DQ_CODE)
     UNION ALL
    SELECT V_SWCODE, LC_THISMONTH, 'GJ', XMFL, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
      FROM (SELECT C.XMFL, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
              FROM DM_DQCODE A
             INNER JOIN DM_DQGROUP B ON A.DQ_CODE=B.DQ_CODE
             INNER JOIN TJBB_FHXX_GBCODE C ON B.GB_CODE=C.XMFL AND C.SWCODE=V_SWCODE AND C.SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH
             WHERE A.DQ_TYPE='BR'
             GROUP BY C.XMFL);
    COMMIT;

    SELECT COUNT(1)
      INTO V_TEMP
      FROM TJBB_DT_B03114_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH AND DMTYPE='GJ';
    IF V_TEMP = 0 THEN
      BEGIN
        DELETE FROM TJBB_DT_B03114_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH;
        COMMIT;

        INSERT INTO TJBB_DT_B03114_MID (SWJGDM,SSNY,DMTYPE,GBDM,CKE_LJ,TSE_LJ,CKPM)
        SELECT V_SWCODE, LC_LASTMONTH, 'BR', DQ_CODE, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
          FROM (SELECT A.DQ_CODE, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
                  FROM DM_DQCODE A
                 INNER JOIN DM_DQGROUP B ON A.DQ_CODE=B.DQ_CODE
                  LEFT JOIN TJBB_FHXX_GBCODE C ON B.GB_CODE=C.XMFL AND C.SWCODE=V_SWCODE AND C.SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH
                 WHERE A.DQ_TYPE='BR'
                 GROUP BY A.DQ_CODE)
         UNION ALL
        SELECT V_SWCODE, LC_LASTMONTH, 'GJ', XMFL, USD_AMT, TSE_AMT, ROW_NUMBER() OVER (ORDER BY USD_AMT DESC)
          FROM (SELECT C.XMFL, ROUND(SUM(C.USD_AMT)/10000,0) AS USD_AMT, ROUND(SUM(C.TS_AMT)/10000,0) AS TSE_AMT
                  FROM DM_DQCODE A
                 INNER JOIN DM_DQGROUP B ON A.DQ_CODE=B.DQ_CODE
                 INNER JOIN TJBB_FHXX_GBCODE C ON B.GB_CODE=C.XMFL AND C.SWCODE=V_SWCODE AND C.SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH
                 WHERE A.DQ_TYPE='BR'
                 GROUP BY C.XMFL);
        COMMIT;
      END;
    END IF;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  -- 2、计算并插入区域情况及本年前10名明细及上年同期
  BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_005;
      SET V_MSG = BJTS_SQLERRM_005;

  END;
INSERT INTO TJBB_DT_B03114 (SSNY,BBLC,SWJGDM,ITEM,CKE_USD,TMSE,CKE_USD_LAST,TMSE_LAST)
    SELECT LC_THISMONTH, '100', V_SWCODE, '区域情况', NULL, NULL, NULL, NULL

     UNION ALL
    SELECT B.SSNY, ORA_CONCAT(CASE WHEN B.CKPM<10 THEN '10' ELSE '1' END, B.CKPM), B.SWJGDM, A.DQ_NAME, B.CKE_LJ, B.TSE_LJ, C.CKE_LJ, C.TSE_LJ
      FROM DM_DQCODE A
     INNER JOIN TJBB_DT_B03114_MID B ON A.DQ_CODE=B.GBDM AND B.SWJGDM=V_SWCODE AND B.SSNY=LC_THISMONTH AND B.DMTYPE='BR'
      LEFT JOIN TJBB_DT_B03114_MID C ON A.DQ_CODE=C.GBDM AND C.SWJGDM=V_SWCODE AND C.SSNY=LC_LASTMONTH AND C.DMTYPE='BR'
     WHERE A.DQ_TYPE='BR'
     UNION ALL
    SELECT LC_THISMONTH, '200', V_SWCODE, '10个主要国别情况', NULL, NULL, NULL, NULL

     UNION ALL
    SELECT B.SSNY, ORA_CONCAT(CASE WHEN B.CKPM<10 THEN '20' ELSE '2' END, B.CKPM), B.SWJGDM, A.GB_NAME, B.CKE_LJ, B.TSE_LJ, C.CKE_LJ, C.TSE_LJ
      FROM DM_GBCODE A
     INNER JOIN TJBB_DT_B03114_MID B ON A.GB_CODE=B.GBDM AND B.SWJGDM=V_SWCODE AND B.SSNY=LC_THISMONTH AND B.DMTYPE='GJ'
      LEFT JOIN TJBB_DT_B03114_MID C ON A.GB_CODE=C.GBDM AND C.SWJGDM=V_SWCODE AND C.SSNY=LC_LASTMONTH AND C.DMTYPE='GJ'
     WHERE B.CKPM<=10;
    COMMIT;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  -- 3、计算并插入合计数
  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      DO 0;

  END;
SELECT SUM(CKE_LJ), SUM(TSE_LJ)
      INTO LN_CKE_HJ, LN_TSE_HJ
      FROM TJBB_DT_B03114_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH AND DMTYPE='GJ';

    SELECT SUM(CKE_LJ), SUM(TSE_LJ)
      INTO LN_CKE_HJ_LAST, LN_TSE_HJ_LAST
      FROM TJBB_DT_B03114_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH AND DMTYPE='GJ';

    INSERT INTO TJBB_DT_B03114 (SSNY,BBLC,SWJGDM,ITEM,CKE_USD,TMSE,CKE_USD_LAST,TMSE_LAST)
    SELECT LC_THISMONTH, '001', V_SWCODE, '“一带一路”沿线64国', LN_CKE_HJ, LN_TSE_HJ, LN_CKE_HJ_LAST, LN_TSE_HJ_LAST
;
    COMMIT;
  END;

  -- 4、同比计算
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;

  END;
UPDATE TJBB_DT_B03114
       SET CKE_TB  = CASE WHEN IFNULL(CKE_USD_LAST, 0)=0 THEN NULL ELSE ROUND(100 * CKE_USD / CKE_USD_LAST -100,1) END,
    TMSE_TB = CASE WHEN IFNULL(TMSE_LAST, 0)=0    THEN NULL ELSE ROUND(100 * TMSE    / TMSE_LAST    -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  -- 5、占比计算
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;

  END;
UPDATE TJBB_DT_B03114 AS T
       SET CKE_ZB  = CASE WHEN IFNULL(LN_CKE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * CKE_USD / LN_CKE_HJ,1) END,
    TMSE_ZB = CASE WHEN IFNULL(LN_TSE_HJ, 0)=0 THEN NULL ELSE ROUND(100 * TMSE / LN_TSE_HJ,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  -- 6、汇总栏初始化
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03114 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03114' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
