DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B02106_CSH_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B02106_CSH_NEW
/*************************************************
 * 综服企业代办退税情况统计表
 * 202202，针对同时申报出口货物劳务以及服务贸易的企业，调整lctjjc
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);
  DECLARE LD_NEXTMONTH     DATETIME;
  DECLARE LD_STARTMONTH    DATETIME;

  DECLARE LN_WMBAHS        BIGINT;
  DECLARE LN_WMBAHS13      BIGINT;
  DECLARE LN_WMBAHS35      BIGINT;
  DECLARE LN_SCBAHS        BIGINT;
  DECLARE LN_WMSBHS        BIGINT;
  DECLARE LN_SCSBHS        BIGINT;

  DECLARE LN_SB_CKE    DECIMAL(18,6);

  DECLARE LN_SB_ZZS    DECIMAL(18,6);
  DECLARE LN_SH_ZZS    DECIMAL(18,6);
  DECLARE LN_ZH_ZZS    DECIMAL(18,6);
  DECLARE LN_BY_ZZS    DECIMAL(18,6);
  DECLARE LN_ZT_ZZS    DECIMAL(18,6);
  DECLARE LN_SP_ZZS    DECIMAL(18,6);
  DECLARE LN_YS_ZZS    DECIMAL(18,6);

  DECLARE LN_SB_XFS    DECIMAL(18,6);
  DECLARE LN_SH_XFS    DECIMAL(18,6);
  DECLARE LN_ZH_XFS    DECIMAL(18,6);
  DECLARE LN_BY_XFS    DECIMAL(18,6);
  DECLARE LN_ZT_XFS    DECIMAL(18,6);
  DECLARE LN_SP_XFS    DECIMAL(18,6);
  DECLARE LN_YS_XFS    DECIMAL(18,6);

  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);

  SET V_ERROR =0;
  SET V_MSG = ' ';
  
  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME);
  END IF;
  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LD_NEXTMONTH =CAST(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL 1 MONTH), '%Y-%m-01') AS DATETIME);
  SET LD_STARTMONTH =DATE'2017-11-01';
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02106 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、统计
  BEGIN
    --备案代办退税生产企业户数
    SELECT COUNT(DISTINCT A.CPCODE)
      INTO LN_SCBAHS
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       --AND A.ZX_FLAG <>'R'
       AND A.DBTSBA_FLAG='1';
    --申报代办退税生产企业户数
    SELECT COUNT(DISTINCT A.CPCODE)
      INTO LN_SCSBHS
      FROM GLXT_BB_SHXT_DJXX A
     INNER JOIN CKTS_SB_WZF_CKMX B ON B.WTDBTSSCQYNSRSBH=A.NSRDJNO OR B.WTDBTSSCQYNSRSBH=A.SHXYNO
     INNER JOIN CKTS_LC_SHXX C ON C.LCSLID=B.LCSLID AND C.QDSJ<LD_NEXTMONTH
     WHERE A.SWJGDM=V_SWCODE
       --AND A.ZX_FLAG <>'R'
       AND A.DBTSBA_FLAG='1';

    --外综服企业备案户数
    SELECT COUNT(1)
      INTO LN_WMBAHS
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       --AND A.ZX_FLAG <>'R'
       AND A.BAJC_YEAR IN ('71','72');

    --申报户数、申报出口额
    SELECT COUNT(DISTINCT T.DJXH), ROUND(IFNULL(SUM(T.MYLAJ), 0)/10000,6)
      INTO LN_WMSBHS, LN_SB_CKE
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MYLAJ
              FROM GLXT_BB_SHXT_DJXX S
             INNER JOIN CKTS_LC_SHXX A ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
              LEFT JOIN CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE S.SWJGDM=V_SWCODE
               AND S.BAJC_YEAR IN ('71','72')
               AND A.LCTJJC IN ('71','72')
             UNION ALL
            SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MYLAJ
              FROM GLXT_BB_SHXT_DJXX S
             INNER JOIN CKTS_LC_SHXX A  ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
              LEFT JOIN CKTS_SB_WZF_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N'
             WHERE S.SWJGDM=V_SWCODE
               AND S.BAJC_YEAR  IN ('71','72')
               AND A.LCTJJC IN ('71','72')) T;

    --申报退税额、审核通过退税额、暂缓退税额、不予退税额、在途退税额
    SELECT ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' THEN T.TSE ELSE 0 END), 0)/10000,6), --增值税申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='V' AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.ZBBLBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --暂缓
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' THEN T.TSE ELSE 0 END), 0)/10000,6), --消费税申报
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
           ROUND(IFNULL(SUM(CASE WHEN T.SZ='C' AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.ZBBLBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6) --暂缓
      INTO LN_SB_ZZS, LN_ZT_ZZS, LN_SH_ZZS, LN_BY_ZZS, LN_ZH_ZZS, LN_SB_XFS, LN_ZT_XFS, LN_SH_XFS, LN_BY_XFS, LN_ZH_XFS
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MTSBZ,B.BYTSBZ,B.ZBBLBZ,A.LCSLID_FS,B.SZ,B.TSE
              FROM GLXT_BB_SHXT_DJXX S
             INNER JOIN CKTS_LC_SHXX A  ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
             INNER JOIN CKTS_SB_MTS_JHMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N' 
             WHERE S.SWJGDM=V_SWCODE
               AND S.BAJC_YEAR  IN ('71','72')
               AND A.LCTJJC IN ('71','72')
             UNION ALL
            SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MTSBZ,B.BYTSBZ,B.ZBBLBZ,A.LCSLID_FS,'V' AS SZ,B.TSE
              FROM GLXT_BB_SHXT_DJXX S
             INNER JOIN CKTS_LC_SHXX A  ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
             INNER JOIN CKTS_SB_WZF_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N' 
             WHERE S.SWJGDM=V_SWCODE
               AND S.BAJC_YEAR  IN ('71','72')
               AND A.LCTJJC IN ('71','72')) T;

    --审批退税额、移送国库退税额、国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE), 0)/10000,6), --增值税审批
           ROUND(IFNULL(SUM(T.GKBL_ZZSTSE), 0)/10000,6), --移送国库
           ROUND(IFNULL(SUM(T.SEHZ_XFSTSE), 0)/10000,6), --消费税审批
           ROUND(IFNULL(SUM(T.GKBL_XFSTSE), 0)/10000,6) --移送国库
      INTO LN_SP_ZZS, LN_YS_ZZS, LN_SP_XFS, LN_YS_XFS
      FROM GLXT_BB_SHXT_DJXX S
     INNER JOIN CKTS_LC_SHXX A  ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
     INNER JOIN CKTS_LC_SEHZXX T ON TRIM(T.LCSLID_FS)=A.LCSLID_FS AND T.SEHZRQ<LD_NEXTMONTH
     WHERE S.SWJGDM=V_SWCODE
       AND S.BAJC_YEAR IN ('71','72')
       AND A.LCTJJC IN ('71','72');

    INSERT INTO TJBB_DT_B02106 (SSNY, BBLC, SWJGDM,
           BAHS_ZFQY, BAHS_DBTS,
           SBHS_ZFQY, SBHS_DBTS, TSCKE, TSE,
           SHTG_TSE, ZHBL_TSE, BYBL_TSE, SHZT_TSE,
           SPYT_TKE, YSGK_TKE, WSGK_TKE, GKBL_TKE, ZT_TKE)
    SELECT LC_THISMONTH, '01', V_SWCODE,
           LN_WMBAHS, LN_SCBAHS, LN_WMSBHS, LN_SCSBHS, LN_SB_CKE, LN_SB_ZZS + LN_SB_XFS, 
           LN_SH_ZZS + LN_SH_XFS, LN_ZH_ZZS + LN_ZH_XFS, LN_BY_ZZS + LN_BY_XFS, LN_ZT_ZZS + LN_ZT_XFS,
           LN_SP_ZZS + LN_SP_XFS, LN_YS_ZZS + LN_YS_XFS, 0, LN_YS_ZZS + LN_YS_XFS, 0

     UNION ALL
    SELECT LC_THISMONTH, '02', V_SWCODE,
           LN_WMBAHS, LN_SCBAHS, 0, 0, LN_SB_CKE, LN_SB_ZZS,
           LN_SH_ZZS, LN_ZH_ZZS, LN_BY_ZZS, LN_ZT_ZZS,
           LN_SP_ZZS, LN_YS_ZZS, 0, LN_YS_ZZS, 0

     UNION ALL
    SELECT LC_THISMONTH, '03', V_SWCODE,
           LN_WMBAHS, LN_SCBAHS, 0, 0, 0, LN_SB_XFS, 
           LN_SH_XFS, LN_ZH_XFS, LN_BY_XFS, LN_ZT_XFS,
           LN_SP_XFS, LN_YS_XFS, 0, LN_YS_XFS, 0
;

    --符合13号公告规定业务备案户数
    SELECT COUNT(1)
      INTO LN_WMBAHS13
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       --AND A.ZX_FLAG <>'R'
       AND A.BAJC_YEAR = 71;

    --申报户数、申报出口额
    SELECT COUNT(DISTINCT T.DJXH), ROUND(IFNULL(SUM(T.MYLAJ), 0)/10000,6)
      INTO LN_WMSBHS, LN_SB_CKE
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MYLAJ
              FROM GLXT_BB_SHXT_DJXX S
             INNER JOIN CKTS_LC_SHXX A ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
              LEFT JOIN CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N' 
             WHERE S.SWJGDM=V_SWCODE
               AND S.BAJC_YEAR IN ('71','72')
               AND A.LCTJJC='71') T;

    --申报退税额、审核通过退税额、暂缓退税额、不予退税额、在途退税额
    SELECT ROUND(IFNULL(SUM(T.TSE), 0)/10000,6), --申报
           ROUND(IFNULL(SUM(CASE WHEN TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
           ROUND(IFNULL(SUM(CASE WHEN TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
           ROUND(IFNULL(SUM(CASE WHEN TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
           ROUND(IFNULL(SUM(CASE WHEN TRIM(T.LCSLID_FS) IS NOT NULL AND T.ZBBLBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6) --暂缓
      INTO LN_SB_ZZS, LN_ZT_ZZS, LN_SH_ZZS, LN_BY_ZZS, LN_ZH_ZZS
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MTSBZ,B.BYTSBZ,B.ZBBLBZ,A.LCSLID_FS,B.TSE
              FROM GLXT_BB_SHXT_DJXX S
             INNER JOIN CKTS_LC_SHXX A  ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
             INNER JOIN CKTS_SB_MTS_JHMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N' 
             WHERE S.SWJGDM=V_SWCODE
               AND S.BAJC_YEAR IN ('71','72')
               AND A.LCTJJC='71') T;

    --审批退税额、移送国库退税额、国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE), 0)/10000,6), --审批
           ROUND(IFNULL(SUM(T.GKBL_ZZSTSE + T.GKBL_XFSTSE), 0)/10000,6) --移送国库
      INTO LN_SP_ZZS, LN_YS_ZZS
      FROM GLXT_BB_SHXT_DJXX S
     INNER JOIN CKTS_LC_SHXX A  ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
     INNER JOIN CKTS_LC_SEHZXX T ON TRIM(T.LCSLID_FS)=A.LCSLID_FS AND T.SEHZRQ<LD_NEXTMONTH
     WHERE S.SWJGDM=V_SWCODE
       AND S.BAJC_YEAR IN ('71','72')
       AND A.LCTJJC='71';

    INSERT INTO TJBB_DT_B02106 (SSNY, BBLC, SWJGDM,
           BAHS_ZFQY, BAHS_DBTS,
           SBHS_ZFQY, SBHS_DBTS, TSCKE, TSE,
           SHTG_TSE, ZHBL_TSE, BYBL_TSE, SHZT_TSE,
           SPYT_TKE, YSGK_TKE, WSGK_TKE, GKBL_TKE, ZT_TKE)
    SELECT LC_THISMONTH, '04', V_SWCODE,
           LN_WMBAHS13, LN_SCBAHS, 0, 0, LN_SB_CKE, LN_SB_ZZS, 
           LN_SH_ZZS, LN_ZH_ZZS, LN_BY_ZZS, LN_ZT_ZZS,
           LN_SP_ZZS, LN_YS_ZZS, 0, LN_YS_ZZS, 0
;

    --符合35号公告规定业务备案户数
    SELECT COUNT(1)
      INTO LN_WMBAHS35
      FROM GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       --AND A.ZX_FLAG <>'R'
       AND A.BAJC_YEAR IN ('71','72');

    --申报户数、申报出口额
    SELECT COUNT(DISTINCT T.DJXH), ROUND(IFNULL(SUM(T.MYLAJ), 0)/10000,6)
      INTO LN_WMSBHS, LN_SB_CKE
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MYLAJ
              FROM GLXT_BB_SHXT_DJXX S
             INNER JOIN CKTS_LC_SHXX A  ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
              LEFT JOIN CKTS_SB_WZF_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N' 
             WHERE S.SWJGDM=V_SWCODE
               AND S.BAJC_YEAR IN ('71','72')
               AND A.LCTJJC='72') T;

    --申报退税额、审核通过退税额、暂缓退税额、不予退税额、在途退税额
    SELECT ROUND(IFNULL(SUM(T.TSE), 0)/10000,6), --申报
           ROUND(IFNULL(SUM(CASE WHEN TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END), 0)/10000,6), --在途
           ROUND(IFNULL(SUM(CASE WHEN TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --准予
           ROUND(IFNULL(SUM(CASE WHEN TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6), --不予
           ROUND(IFNULL(SUM(CASE WHEN TRIM(T.LCSLID_FS) IS NOT NULL AND T.ZBBLBZ='Y' THEN T.TSE ELSE 0 END), 0)/10000,6) --暂缓
      INTO LN_SB_ZZS, LN_ZT_ZZS, LN_SH_ZZS, LN_BY_ZZS, LN_ZH_ZZS
      FROM (SELECT A.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MTSBZ,B.BYTSBZ,B.ZBBLBZ,A.LCSLID_FS,B.TSE
              FROM GLXT_BB_SHXT_DJXX S
             INNER JOIN CKTS_LC_SHXX A  ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
             INNER JOIN CKTS_SB_WZF_CKMX B ON B.LCSLID=A.LCSLID AND B.BYBLBZ='N' 
             WHERE S.SWJGDM=V_SWCODE
               AND S.BAJC_YEAR  IN ('71','72')
               AND A.LCTJJC='72') T;

    --审批退税额、移送国库退税额、国库办理退税额
    SELECT ROUND(IFNULL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE), 0)/10000,6), --审批
           ROUND(IFNULL(SUM(T.GKBL_ZZSTSE + T.GKBL_XFSTSE), 0)/10000,6) --移送国库
      INTO LN_SP_ZZS, LN_YS_ZZS
      FROM GLXT_BB_SHXT_DJXX S
     INNER JOIN CKTS_LC_SHXX A  ON A.DJXH=S.DJXH_JS AND A.QDSJ>=LD_STARTMONTH AND A.QDSJ<LD_NEXTMONTH
     INNER JOIN CKTS_LC_SEHZXX T ON TRIM(T.LCSLID_FS)=A.LCSLID_FS AND T.SEHZRQ<LD_NEXTMONTH
     WHERE S.SWJGDM=V_SWCODE
       AND S.BAJC_YEAR IN ('71','72')
       AND A.LCTJJC='72';

    INSERT INTO TJBB_DT_B02106 (SSNY, BBLC, SWJGDM,
           BAHS_ZFQY, BAHS_DBTS,
           SBHS_ZFQY, SBHS_DBTS, TSCKE, TSE,
           SHTG_TSE, ZHBL_TSE, BYBL_TSE, SHZT_TSE,
           SPYT_TKE, YSGK_TKE, WSGK_TKE, GKBL_TKE, ZT_TKE)
    SELECT LC_THISMONTH, '05', V_SWCODE,
           LN_WMBAHS35, LN_SCBAHS, LN_WMSBHS, LN_SCSBHS, LN_SB_CKE, LN_SB_ZZS, 
           LN_SH_ZZS, LN_ZH_ZZS, LN_BY_ZZS, LN_ZT_ZZS,
           LN_SP_ZZS, LN_YS_ZZS, 0, LN_YS_ZZS, 0
;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --2、行内计算
  --3、汇总栏初始化
  BEGIN
    SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B02106 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02106' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      SET LC_SQL_UPDATEHZ = LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    SET LC_SQL_UPDATEHZ = SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
