DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B05102_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B05102_HZ_NEW
/**************************************************************
 * 跨境电商统计表——无票免税情况表（省、市局汇总）
 **************************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LD_SYSDATE       DATETIME;
  DECLARE LC_THISMONTH     VARCHAR(6);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(V_SSNY||'01', '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B05102 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  --1、统计
  BEGIN
    INSERT INTO TJBB_DT_B05102 (
           SSNY,BBLC,SWJGDM,QJNY,
           KJLS_CKE_HS, KJLS_CKE_HS_HZ, KJLS_CKE_JE, KJLS_CKE_JE_HZ, 
           KJLS_TMS_HS, KJLS_TMS_HS_HZ, KJLS_TMS_JE, KJLS_TMS_JE_HZ, 
           WPMS_CKE_HS, WPMS_CKE_HS_HZ, WPMS_CKE_JE, WPMS_CKE_JE_HZ)
    SELECT LC_THISMONTH,BBLC,V_SWCODE,QJNY,
           SUM(KJLS_CKE_HS), SUM(KJLS_CKE_HS_HZ), SUM(KJLS_CKE_JE), SUM(KJLS_CKE_JE_HZ),
           SUM(KJLS_TMS_HS), SUM(KJLS_TMS_HS_HZ), SUM(KJLS_TMS_JE), SUM(KJLS_TMS_JE_HZ),
           SUM(WPMS_CKE_HS), SUM(WPMS_CKE_HS_HZ), SUM(WPMS_CKE_JE), SUM(WPMS_CKE_JE_HZ)
      FROM TJBB_DT_B05102
     WHERE SWJGDM IN (SELECT SWJG_DM FROM TABLE(FUNC_GET_XJ_SWJG(V_SWCODE))) 
       AND SSNY=LC_THISMONTH
     GROUP BY BBLC,QJNY;

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ERROR = SQLCODE;
      SET V_MSG = SQLERRM;
      LEAVE routine_body;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
