DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_TJBB_DT_B03113_HZ_NEW$$

CREATE PROCEDURE PRO_TJBB_DT_B03113_HZ_NEW
/*************************************************
 * 浙江省对美主要出口企业情况表（省、市局汇总）
 ************************************************/
(
  IN V_SWCODE VARCHAR(4000),
  IN V_SSNY VARCHAR(4000),
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_THISMONTH     VARCHAR(6);-- 当月
  DECLARE LC_THISYEAR      VARCHAR(6);-- 当年首月
  DECLARE LC_LASTMONTH     VARCHAR(6);-- 上年同期
  DECLARE LC_LASTYEAR      VARCHAR(6);-- 上年首月
  DECLARE LC_SQL_UPDATEHZ  VARCHAR(4000);
  DECLARE LD_SYSDATE       DATETIME;

  SET V_ERROR =0;
  SET V_MSG = ' ';

  IF V_SSNY IS NOT NULL THEN
    SET LD_SYSDATE =STR_TO_DATE(ORA_CONCAT(V_SSNY, '01'), '%Y%m%d');
  ELSE
    SET LD_SYSDATE =CURRENT_TIMESTAMP;
  END IF;

  SET LC_THISMONTH =DATE_FORMAT(LD_SYSDATE, '%Y%m');
  SET LC_THISYEAR =ORA_CONCAT(DATE_FORMAT(LD_SYSDATE, '%Y'), '01');
  SET LC_LASTMONTH =DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y%m');
  SET LC_LASTYEAR =ORA_CONCAT(DATE_FORMAT(DATE_ADD(LD_SYSDATE, INTERVAL -12 MONTH), '%Y'), '01');

  -- 0、清除原有制表数据，准备重新制表
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_003;
      SET V_MSG = BJTS_SQLERRM_003;
      LEAVE routine_body;

  END;
DELETE FROM TJBB_DT_B03113 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  END;

  -- 1、本年前50名当年数据
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_002;
      SET V_MSG = BJTS_SQLERRM_002;

  END;
INSERT INTO TJBB_DT_B03113
                (SSNY,BBLC,SWJGDM,CPCODE,QYHGDM,QYMC,JSMODE,JSMODEMC,PM,
                USA_CKE_YEAR,CKE_YEAR,USA_TMSE_YEAR,TMSE_YEAR,
                USA_CKE_YEAR_LAST,CKE_YEAR_LAST,USA_TMSE_YEAR_LAST,TMSE_YEAR_LAST,
                USA_CKE_TB,CKE_TB,USA_TMSE_TB,TMSE_TB,
                CKE_YEAR_ZB,CKE_YEAR_ZB_LAST,TMSE_YEAR_ZB,TMSE_YEAR_ZB_LAST)
    SELECT LC_THISMONTH,ORA_CONCAT(ORA_CONCAT(JSMODE, CASE WHEN PM<10 THEN '0' ELSE '' END), PM),V_SWCODE,CPCODE,QYHGDM,QYMC,JSMODE,JSMODEMC,PM,
           USA_CKE_YEAR,CKE_YEAR,USA_TMSE_YEAR,TMSE_YEAR,
           USA_CKE_YEAR_LAST,CKE_YEAR_LAST,USA_TMSE_YEAR_LAST,TMSE_YEAR_LAST,
           USA_CKE_TB,CKE_TB,USA_TMSE_TB,TMSE_TB,
           CKE_YEAR_ZB,CKE_YEAR_ZB_LAST,TMSE_YEAR_ZB,TMSE_YEAR_ZB_LAST
      FROM (SELECT CPCODE,QYHGDM,QYMC,JSMODE,JSMODEMC,
                   USA_CKE_YEAR,CKE_YEAR,USA_TMSE_YEAR,TMSE_YEAR,
                   USA_CKE_YEAR_LAST,CKE_YEAR_LAST,USA_TMSE_YEAR_LAST,TMSE_YEAR_LAST,
                   USA_CKE_TB,CKE_TB,USA_TMSE_TB,TMSE_TB,
                   CKE_YEAR_ZB,CKE_YEAR_ZB_LAST,TMSE_YEAR_ZB,TMSE_YEAR_ZB_LAST,
                   ROW_NUMBER() OVER (PARTITION BY JSMODE ORDER BY USA_CKE_YEAR DESC) AS PM
              FROM TJBB_DT_B03113 B
             WHERE B.SWJGDM IN (SELECT VIR_SWJGDM AS SWJG_DM
       FROM DM_SWJG_VIRTUAL
      WHERE SUBSTR(V_SWCODE, 1, 1) = '2'
        AND SWJG_DM = V_SWCODE
        AND YXBZ = 'Y'
        AND VIR_FLAG = '0'
      UNION ALL
     SELECT SWJG_DM AS SWJG_DM
       FROM DM_SWJG
      WHERE (SUBSTR(V_SWCODE, 1, 1) <> '2' OR SUBSTR(V_SWCODE, 1, 1) IS NULL)
        AND SWJG_DM_SJ = V_SWCODE
        AND TSJG_BZ = '1')
               AND B.SSNY=LC_THISMONTH)
     WHERE PM<=50;
    COMMIT;
  END;
  IF V_ERROR <> 0 THEN
    LEAVE routine_body;
  END IF;

  -- 2、汇总栏初始化
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ERROR = BJTS_SQLCODE_001;
      SET V_MSG = BJTS_SQLERRM_001;

  END;
SET LC_SQL_UPDATEHZ = 'UPDATE TJBB_DT_B03113 SET ';

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_FNAME_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03113' AND FTYPE='NUMBER' ORDER BY SHOWORDER;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_FNAME_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(LC_SQL_UPDATEHZ, BJTS_LSF_XX_FNAME_001), '_HZ='), BJTS_LSF_XX_FNAME_001), ', ');

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    SET LC_SQL_UPDATEHZ = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2), ' WHERE SWJGDM='''), V_SWCODE), ''' AND SSNY='''), LC_THISMONTH), '''');

    SET @BJTS_DYNAMIC_SQL_001 = LC_SQL_UPDATEHZ;
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
