DELIMITER $$

DROP PROCEDURE IF EXISTS TMP_PRO_TJBB_CSH_B03117$$

CREATE PROCEDURE TMP_PRO_TJBB_CSH_B03117
/*
 * 省局月报表/出口退税月报表（不计结转），所有税务局重新制表
 * 需要手工调制报表所属期
 */
(
  IN LC_MONTH VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_ERROR         DECIMAL(38,10);
  DECLARE LC_MSG           VARCHAR(2000);
  DECLARE LC_SWJGDM        VARCHAR(11);

  BEGIN
    INSERT INTO TJBB_TASK_SUB (BBID, BBDM, SWJGDM, NY, HZTIME, HZR, BBDLDM)
         SELECT SYS_GUID(), S.BBDM, T.SWJG_DM, LC_MONTH, CURRENT_TIMESTAMP, 'system', S.BBDLDM
           FROM DM_SWJG T, TJBB_REPORT_LIST S
          WHERE T.TSJG_BZ='1' AND T.QYBZ='Y'
            AND S.BBDM='B03117'
          ORDER BY T.SWJG_DM, S.BBDM;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET LC_MSG = SQLERRM;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('新增TJBB_TASK_SUB任务失败！', LC_MSG);
      COMMIT;
  END;
  
  --区县局
  FOR LSF_SWJG IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND QYBZ='Y' AND YXWS=7 ORDER BY SWJG_DM) LOOP
    SET LC_SWJGDM = LSF_SWJG.SWJG_DM;

    BEGIN
      PRO_TJBB_DT_B03117_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03117_CSH_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03117_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
  END LOOP;

  --地市局
  FOR LSF_SWJG IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND QYBZ='Y'AND YXWS=5 ORDER BY SWJG_DM) LOOP
    SET LC_SWJGDM = LSF_SWJG.SWJG_DM;

    BEGIN
      PRO_TJBB_DT_B03117_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03117_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03117_HZ_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
  END LOOP;

  --省局
  BEGIN
    SET LC_SWJGDM = '13300000000';
    
    BEGIN
      PRO_TJBB_DT_B03117_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03117_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03117_HZ_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
  END;

END$$

DELIMITER ;
