DELIMITER $$

DROP PROCEDURE IF EXISTS TMP_PRO_TJBB_UPDATE_TSSWJG$$

CREATE PROCEDURE TMP_PRO_TJBB_UPDATE_TSSWJG
(
  IN V_SWCODE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_ERROR         DECIMAL(38,10);
  DECLARE LC_MSG           VARCHAR(2000);

  DELETE FROM TJBB_FHXX_CMCODE T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_CMCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN JSJE ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN TSE ELSE 0 END)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2);
  COMMIT;

  INSERT INTO TJBB_FHXX_CMCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN RMBLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN MDTSE ELSE 0 END)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2);
  COMMIT;

  INSERT INTO TJBB_FHXX_CMCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN JSJE ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN TSE ELSE 0 END)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2);
  COMMIT;

  DELETE FROM TJBB_FHXX_CPCODE T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_CPCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN JSJE ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN TSE ELSE 0 END)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR);
  COMMIT;

  INSERT INTO TJBB_FHXX_CPCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN RMBLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN MDTSE ELSE 0 END)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR);
  COMMIT;

  INSERT INTO TJBB_FHXX_CPCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN JSJE ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN TSE ELSE 0 END)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR);
  COMMIT;

  DELETE FROM TJBB_FHXX_GBCODE T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_GBCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142');
  COMMIT;

  INSERT INTO TJBB_FHXX_GBCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142'), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142');
  COMMIT;

  INSERT INTO TJBB_FHXX_GBCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142');
  COMMIT;

  DELETE FROM TJBB_FHXX_HGCODE T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_HGCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000');
  COMMIT;

  INSERT INTO TJBB_FHXX_HGCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000'), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000');
  COMMIT;

  INSERT INTO TJBB_FHXX_HGCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000');
  COMMIT;

  DELETE FROM TJBB_FHXX_TDCODE T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_TDCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0');
  COMMIT;

  INSERT INTO TJBB_FHXX_TDCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0'), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0');
  COMMIT;

  INSERT INTO TJBB_FHXX_TDCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0');
  COMMIT;

  DELETE FROM TJBB_FHXX_TSLV T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_TSLV(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, T.TSL, SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206' AND T.TSL IS NOT NULL
        GROUP BY S.BBNY, T.TSSWJG_DM, T.TSL;
  COMMIT;

  INSERT INTO TJBB_FHXX_TSLV(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, T.TSL, SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206' AND T.TSL IS NOT NULL
        GROUP BY S.BBNY, T.TSSWJG_DM, T.TSL;
  COMMIT;

  INSERT INTO TJBB_FHXX_TSLV(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, T.TSL, SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206' AND T.TSL IS NOT NULL
        GROUP BY S.BBNY, T.TSSWJG_DM, T.TSL;
  COMMIT;

  DELETE FROM TJBB_TASK T WHERE T.SWJGDM = V_SWCODE;
  DELETE FROM TJBB_TASK_SUB T WHERE T.SWJGDM = V_SWCODE;
  COMMIT;

  FOR LSF_SSNY IN (SELECT A.BBNY FROM TJBB_CS_ZBRQ A WHERE A.BBNY>='202101' AND A.BBNY<='202206' ORDER BY A.BBNY) LOOP
    --按报表顺序依次制表
    BEGIN
      PRO_TJBB_DT_B01100_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01100_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01100_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B01101_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01101_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01101_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B01102_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01102_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01102_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B01103_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01103_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01103_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B01104_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01104_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01104_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B01105_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01105_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01105_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B01106_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01106_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01106_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B01107_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01107_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01107_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B01108_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01108_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01108_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B01109_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B01109_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B01109_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;

    INSERT INTO TJBB_TASK (BBDLDM, SWJGDM, NY, STATUS, SJSWJG, CJTIME, CJR, ZBTIME, ZBR, TYPE, SWJGMC, SWJGJC)
         SELECT 'B01',V_SWCODE,LSF_SSNY.BBNY,'20',T.SWJG_DM_SJ,CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP,'system','1',T.SWJG_MC,T.SWJG_JC
           FROM DM_SWJG T
          WHERE T.SWJG_DM=V_SWCODE;
    COMMIT;
    INSERT INTO TJBB_TASK_SUB (BBID, BBDM, SWJGDM, NY, HZTIME, HZR, BBDLDM)
         SELECT SYS_GUID(), S.BBDM, V_SWCODE, LSF_SSNY.BBNY, CURRENT_TIMESTAMP, 'system', S.BBDLDM
           FROM TJBB_REPORT_LIST S
          WHERE S.BBDLDM='B01'
          ORDER BY S.BBDM;
    COMMIT;

    BEGIN
      PRO_TJBB_DT_B02101_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02101_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02101_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02102_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02102_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02102_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02103_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02103_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02103_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02104_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02104_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02104_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02105_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02105_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02105_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02106_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02106_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02106_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02107_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02107_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02107_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02108_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02108_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02108_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02109_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02109_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02109_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;

    INSERT INTO TJBB_TASK (BBDLDM, SWJGDM, NY, STATUS, SJSWJG, CJTIME, CJR, ZBTIME, ZBR, TYPE, SWJGMC, SWJGJC)
         SELECT 'B02',V_SWCODE,LSF_SSNY.BBNY,'20',T.SWJG_DM_SJ,CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP,'system','1',T.SWJG_MC,T.SWJG_JC
           FROM DM_SWJG T
          WHERE T.SWJG_DM=V_SWCODE;
    COMMIT;
    INSERT INTO TJBB_TASK_SUB (BBID, BBDM, SWJGDM, NY, HZTIME, HZR, BBDLDM)
         SELECT SYS_GUID(), S.BBDM, V_SWCODE, LSF_SSNY.BBNY, CURRENT_TIMESTAMP, 'system', S.BBDLDM
           FROM TJBB_REPORT_LIST S
          WHERE S.BBDLDM='B02'
          ORDER BY S.BBDM;
    COMMIT;

    BEGIN
      PRO_TJBB_DT_B03101_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03101_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03101_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03102_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03102_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03102_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03103_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03103_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03103_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03104_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03104_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03104_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03105_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03105_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03105_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03106_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03106_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03106_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03107_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03107_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03107_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03108_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03108_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03108_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03109_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03109_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03109_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03110_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03110_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03110_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03111_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03111_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03111_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03112_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03112_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03112_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03113_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03113_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03113_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03114_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03114_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03114_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03115_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03115_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03115_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02112_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02112_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02112_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02113_CSH_NEW(V_SWCODE,LSF_SSNY.BBNY,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02113_CSH_NEW！'||V_SWCODE||'-'||LSF_SSNY.BBNY);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02113_CSH失败：'||V_SWCODE||'-'||LSF_SSNY.BBNY, LC_MSG);
        COMMIT;
    END;

    INSERT INTO TJBB_TASK (BBDLDM, SWJGDM, NY, STATUS, SJSWJG, CJTIME, CJR, ZBTIME, ZBR, TYPE, SWJGMC, SWJGJC)
         SELECT 'B03',V_SWCODE,LSF_SSNY.BBNY,'20',T.SWJG_DM_SJ,CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP,'system','1',T.SWJG_MC,T.SWJG_JC
           FROM DM_SWJG T
          WHERE T.SWJG_DM=V_SWCODE;
    COMMIT;
    INSERT INTO TJBB_TASK_SUB (BBID, BBDM, SWJGDM, NY, HZTIME, HZR, BBDLDM)
         SELECT SYS_GUID(), S.BBDM, V_SWCODE, LSF_SSNY.BBNY, CURRENT_TIMESTAMP, 'system', S.BBDLDM
           FROM TJBB_REPORT_LIST S
          WHERE S.BBDLDM='B03'
          ORDER BY S.BBDM;
    COMMIT;

  END LOOP;
END$$

DELIMITER ;
