DELIMITER $$

DROP PROCEDURE IF EXISTS TMP_PRO_TJBB_CSH_B03116$$

CREATE PROCEDURE TMP_PRO_TJBB_CSH_B03116
/*
 * 省局月报表/出口退税月报表（不计结转），所有税务局重新制表
 * 需要手工调制报表所属期
 */
(
  IN LC_MONTH VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_ERROR         DECIMAL(38,10);
  DECLARE LC_MSG           VARCHAR(2000);
  DECLARE LC_SWJGDM        VARCHAR(11);

  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      SET LC_MSG = BJTS_SQLERRM_004;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('新增TJBB_TASK_SUB任务失败！', LC_MSG);
      COMMIT;

  END;
INSERT INTO TJBB_TASK_SUB (BBID, BBDM, SWJGDM, NY, HZTIME, HZR, BBDLDM)
         SELECT REPLACE(UUID(), '-', ''), S.BBDM, T.SWJG_DM, LC_MONTH, CURRENT_TIMESTAMP, 'system', S.BBDLDM
           FROM DM_SWJG T, TJBB_REPORT_LIST S
          WHERE T.TSJG_BZ='1' AND T.QYBZ='Y'
            AND S.BBDM='B03116'
          ORDER BY T.SWJG_DM, S.BBDM;
    COMMIT;
  END;

  -- 区县局
  BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_SWJG_SWJG_DM_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND QYBZ='Y' AND YXWS=7 ORDER BY SWJG_DM;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_LSF_SWJG_SWJG_DM_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
    SET LC_SWJGDM = BJTS_LSF_SWJG_SWJG_DM_002;

    BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03116_CSH_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03116_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03116_CSH_NEW！', LC_SWJGDM));
      COMMIT;
    END;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;

  -- 地市局
  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_SWJG_SWJG_DM_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND QYBZ='Y'AND YXWS=5 ORDER BY SWJG_DM;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_SWJG_SWJG_DM_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    SET LC_SWJGDM = BJTS_LSF_SWJG_SWJG_DM_001;

    BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03116_HZ_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03116_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03116_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  -- 省局
  BEGIN
    SET LC_SWJGDM = '13300000000';

    BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT('执行PRO_TJBB_DT_B03116_HZ_NEW失败，税务机关：', LC_SWJGDM), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03116_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_TJBB_DT_B03116_HZ_NEW！', LC_SWJGDM));
      COMMIT;
    END;
  END;

END$$

DELIMITER ;
