DELIMITER $$

DROP PROCEDURE IF EXISTS TMP_PRO_TJBB_UPDATE_TSSWJG$$

CREATE PROCEDURE TMP_PRO_TJBB_UPDATE_TSSWJG
(
  IN V_SWCODE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_ERROR         DECIMAL(38,10);
  DECLARE LC_MSG           VARCHAR(2000);

  DELETE FROM TJBB_FHXX_CMCODE AS T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_CMCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN JSJE ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN TSE ELSE 0 END)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2);
  COMMIT;

  INSERT INTO TJBB_FHXX_CMCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN RMBLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN MDTSE ELSE 0 END)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2);
  COMMIT;

  INSERT INTO TJBB_FHXX_CMCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN JSJE ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN TSE ELSE 0 END)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, SUBSTR(T.CKSP_DM,0,2);
  COMMIT;

  DELETE FROM TJBB_FHXX_CPCODE AS T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_CPCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN JSJE ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN TSE ELSE 0 END)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR);
  COMMIT;

  INSERT INTO TJBB_FHXX_CPCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN RMBLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN MDTSE ELSE 0 END)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR);
  COMMIT;

  INSERT INTO TJBB_FHXX_CPCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT_ALL,RMB_AMT_ALL,TS_AMT_ALL,USD_AMT_USA,RMB_AMT_USA,TS_AMT_USA)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE),
              SUM(CASE WHEN GBCODE='502' THEN MYLAJ ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN JSJE ELSE 0 END),
              SUM(CASE WHEN GBCODE='502' THEN TSE ELSE 0 END)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, CAST(T.DJXH AS CHAR);
  COMMIT;

  DELETE FROM TJBB_FHXX_GBCODE AS T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_GBCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142');
  COMMIT;

  INSERT INTO TJBB_FHXX_GBCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142'), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142');
  COMMIT;

  INSERT INTO TJBB_FHXX_GBCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.GBCODE, '142');
  COMMIT;

  DELETE FROM TJBB_FHXX_HGCODE AS T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_HGCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000');
  COMMIT;

  INSERT INTO TJBB_FHXX_HGCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000'), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000');
  COMMIT;

  INSERT INTO TJBB_FHXX_HGCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.HGCODE, '0000');
  COMMIT;

  DELETE FROM TJBB_FHXX_TDCODE AS T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_TDCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0');
  COMMIT;

  INSERT INTO TJBB_FHXX_TDCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0'), SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0');
  COMMIT;

  INSERT INTO TJBB_FHXX_TDCODE(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0'), SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206'
        GROUP BY S.BBNY, T.TSSWJG_DM, IFNULL(T.TDCODE, '0');
  COMMIT;

  DELETE FROM TJBB_FHXX_TSLV AS T WHERE T.SWCODE = V_SWCODE;
  COMMIT;

  INSERT INTO TJBB_FHXX_TSLV(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0301001', S.BBNY, T.TSSWJG_DM, T.TSL, SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_MTS_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206' AND T.TSL IS NOT NULL
        GROUP BY S.BBNY, T.TSSWJG_DM, T.TSL;
  COMMIT;

  INSERT INTO TJBB_FHXX_TSLV(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0305001', S.BBNY, T.TSSWJG_DM, T.TSL, SUM(T.MYLAJ), SUM(T.RMBLAJ), SUM(T.MDTSE)
         FROM CKTS_SB_MDT_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206' AND T.TSL IS NOT NULL
        GROUP BY S.BBNY, T.TSSWJG_DM, T.TSL;
  COMMIT;

  INSERT INTO TJBB_FHXX_TSLV(SBYWBDM,SSNY,SWCODE,XMFL,USD_AMT,RMB_AMT,TS_AMT)
       SELECT 'A0310001', S.BBNY, T.TSSWJG_DM, T.TSL, SUM(T.MYLAJ), SUM(T.JSJE), SUM(T.TSE)
         FROM CKTS_SB_WZF_CKMX T
        INNER JOIN TJBB_CS_ZBRQ S ON T.FSRQ>=S.BBNY_KSRQ AND T.FSRQ<S.BBNY_JZRQ
        WHERE T.TSSWJG_DM = V_SWCODE
          AND S.BBNY>='202101' AND S.BBNY<='202206' AND T.TSL IS NOT NULL
        GROUP BY S.BBNY, T.TSSWJG_DM, T.TSL;
  COMMIT;

  DELETE FROM TJBB_TASK AS T WHERE T.SWJGDM = V_SWCODE;
  DELETE FROM TJBB_TASK_SUB AS T WHERE T.SWJGDM = V_SWCODE;
  COMMIT;

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_SSNY_BBNY_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT A.BBNY FROM TJBB_CS_ZBRQ A WHERE A.BBNY>='202101' AND A.BBNY<='202206' ORDER BY A.BBNY;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_SSNY_BBNY_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    -- 按报表顺序依次制表
    BEGIN
  DECLARE BJTS_SQLCODE_036 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_036 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_036 = MYSQL_ERRNO, BJTS_SQLERRM_036 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01100_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01100_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01100_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_035 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_035 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_035 = MYSQL_ERRNO, BJTS_SQLERRM_035 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01101_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01101_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01101_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_034 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_034 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_034 = MYSQL_ERRNO, BJTS_SQLERRM_034 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01102_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01102_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01102_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_033 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_033 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_033 = MYSQL_ERRNO, BJTS_SQLERRM_033 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01103_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01103_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01103_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_032 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_032 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_032 = MYSQL_ERRNO, BJTS_SQLERRM_032 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01104_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01104_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01104_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_031 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_031 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_031 = MYSQL_ERRNO, BJTS_SQLERRM_031 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01105_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01105_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01105_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_030 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_030 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_030 = MYSQL_ERRNO, BJTS_SQLERRM_030 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01106_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01106_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01106_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_029 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_029 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_029 = MYSQL_ERRNO, BJTS_SQLERRM_029 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01107_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01107_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01107_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_028 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_028 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_028 = MYSQL_ERRNO, BJTS_SQLERRM_028 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01108_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01108_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01108_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_027 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_027 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_027 = MYSQL_ERRNO, BJTS_SQLERRM_027 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B01109_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B01109_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B01109_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;

    INSERT INTO TJBB_TASK (BBDLDM, SWJGDM, NY, STATUS, SJSWJG, CJTIME, CJR, ZBTIME, ZBR, TYPE, SWJGMC, SWJGJC)
         SELECT 'B01',V_SWCODE,BJTS_LSF_SSNY_BBNY_001,'20',T.SWJG_DM_SJ,CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP,'system','1',T.SWJG_MC,T.SWJG_JC
           FROM DM_SWJG T
          WHERE T.SWJG_DM=V_SWCODE;
    COMMIT;
    INSERT INTO TJBB_TASK_SUB (BBID, BBDM, SWJGDM, NY, HZTIME, HZR, BBDLDM)
         SELECT REPLACE(UUID(), '-', ''), S.BBDM, V_SWCODE, BJTS_LSF_SSNY_BBNY_001, CURRENT_TIMESTAMP, 'system', S.BBDLDM
           FROM TJBB_REPORT_LIST S
          WHERE S.BBDLDM='B01'
          ORDER BY S.BBDM;
    COMMIT;

    BEGIN
  DECLARE BJTS_SQLCODE_026 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_026 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_026 = MYSQL_ERRNO, BJTS_SQLERRM_026 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02101_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02101_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02101_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_025 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_025 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_025 = MYSQL_ERRNO, BJTS_SQLERRM_025 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02102_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02102_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02102_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_024 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_024 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_024 = MYSQL_ERRNO, BJTS_SQLERRM_024 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02103_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02103_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02103_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_023 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_023 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_023 = MYSQL_ERRNO, BJTS_SQLERRM_023 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02104_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02104_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02104_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_022 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_022 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_022 = MYSQL_ERRNO, BJTS_SQLERRM_022 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02105_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02105_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02105_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_021 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_021 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_021 = MYSQL_ERRNO, BJTS_SQLERRM_021 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02106_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02106_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02106_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_020 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_020 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_020 = MYSQL_ERRNO, BJTS_SQLERRM_020 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02107_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02107_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02107_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_019 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_019 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_019 = MYSQL_ERRNO, BJTS_SQLERRM_019 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02108_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02108_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02108_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_018 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_018 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_018 = MYSQL_ERRNO, BJTS_SQLERRM_018 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02109_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02109_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02109_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;

    INSERT INTO TJBB_TASK (BBDLDM, SWJGDM, NY, STATUS, SJSWJG, CJTIME, CJR, ZBTIME, ZBR, TYPE, SWJGMC, SWJGJC)
         SELECT 'B02',V_SWCODE,BJTS_LSF_SSNY_BBNY_001,'20',T.SWJG_DM_SJ,CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP,'system','1',T.SWJG_MC,T.SWJG_JC
           FROM DM_SWJG T
          WHERE T.SWJG_DM=V_SWCODE;
    COMMIT;
    INSERT INTO TJBB_TASK_SUB (BBID, BBDM, SWJGDM, NY, HZTIME, HZR, BBDLDM)
         SELECT REPLACE(UUID(), '-', ''), S.BBDM, V_SWCODE, BJTS_LSF_SSNY_BBNY_001, CURRENT_TIMESTAMP, 'system', S.BBDLDM
           FROM TJBB_REPORT_LIST S
          WHERE S.BBDLDM='B02'
          ORDER BY S.BBDM;
    COMMIT;

    BEGIN
  DECLARE BJTS_SQLCODE_017 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_017 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_017 = MYSQL_ERRNO, BJTS_SQLERRM_017 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03101_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03101_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03101_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_016 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_016 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_016 = MYSQL_ERRNO, BJTS_SQLERRM_016 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03102_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03102_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03102_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_015 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_015 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_015 = MYSQL_ERRNO, BJTS_SQLERRM_015 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03103_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03103_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03103_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_014 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_014 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_014 = MYSQL_ERRNO, BJTS_SQLERRM_014 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03104_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03104_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03104_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_013 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_013 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_013 = MYSQL_ERRNO, BJTS_SQLERRM_013 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03105_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03105_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03105_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_012 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_012 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_012 = MYSQL_ERRNO, BJTS_SQLERRM_012 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03106_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03106_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03106_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_011 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_011 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_011 = MYSQL_ERRNO, BJTS_SQLERRM_011 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03107_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03107_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03107_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_010 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_010 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_010 = MYSQL_ERRNO, BJTS_SQLERRM_010 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03108_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03108_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03108_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_009 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_009 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_009 = MYSQL_ERRNO, BJTS_SQLERRM_009 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03109_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03109_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03109_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_008 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_008 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_008 = MYSQL_ERRNO, BJTS_SQLERRM_008 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03110_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03110_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03110_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_007 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_007 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_007 = MYSQL_ERRNO, BJTS_SQLERRM_007 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03111_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03111_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03111_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03112_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03112_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03112_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03113_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03113_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03113_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03114_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03114_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03114_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B03115_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B03115_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B03115_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02112_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02112_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02112_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;
    BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
        INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('执行PRO_TJBB_DT_B02113_CSH失败：', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001), LC_MSG);
        COMMIT;

  END;
CALL PRO_TJBB_DT_B02113_CSH_NEW(V_SWCODE,BJTS_LSF_SSNY_BBNY_001,LN_ERROR,LC_MSG);
      INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('PRO_TJBB_DT_B02113_CSH_NEW！', V_SWCODE), '-'), BJTS_LSF_SSNY_BBNY_001));
      COMMIT;
    END;

    INSERT INTO TJBB_TASK (BBDLDM, SWJGDM, NY, STATUS, SJSWJG, CJTIME, CJR, ZBTIME, ZBR, TYPE, SWJGMC, SWJGJC)
         SELECT 'B03',V_SWCODE,BJTS_LSF_SSNY_BBNY_001,'20',T.SWJG_DM_SJ,CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP,'system','1',T.SWJG_MC,T.SWJG_JC
           FROM DM_SWJG T
          WHERE T.SWJG_DM=V_SWCODE;
    COMMIT;
    INSERT INTO TJBB_TASK_SUB (BBID, BBDM, SWJGDM, NY, HZTIME, HZR, BBDLDM)
         SELECT REPLACE(UUID(), '-', ''), S.BBDM, V_SWCODE, BJTS_LSF_SSNY_BBNY_001, CURRENT_TIMESTAMP, 'system', S.BBDLDM
           FROM TJBB_REPORT_LIST S
          WHERE S.BBDLDM='B03'
          ORDER BY S.BBDM;
    COMMIT;


  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
END$$

DELIMITER ;
