DELIMITER $$

DROP FUNCTION IF EXISTS COMPUTE_BLDATE$$

CREATE FUNCTION COMPUTE_BLDATE
/*
  编制人:毛小东
  编制日期:202109
  功能:计算两个日期之间，减去节假日，返回工作日天数
  参数:SL_DATE 开始日期，SB_DATE 结束日期
  返回：NUMBER 天数
 */
(
  END_DATE DATETIME,
  BEGIN_DATE DATETIME
)
RETURNS DECIMAL(38,10)
NOT DETERMINISTIC
READS SQL DATA
BEGIN
  DECLARE V_END_DATE DATETIME;
  DECLARE V_BEGIN_DATE DATETIME;
  DECLARE V_BETWEENDAYS DECIMAL(38,10);
  DECLARE V_JJRDAYS INTEGER;

  SET V_END_DATE =END_DATE;
  IF V_END_DATE IS NULL THEN 
    SET V_END_DATE =CURRENT_TIMESTAMP;
  END IF;
  
  SET V_BEGIN_DATE =BEGIN_DATE;
  IF V_BEGIN_DATE IS NULL THEN 
    SET V_BEGIN_DATE =CURRENT_TIMESTAMP;
  END IF;
  
  --传递的开始日期只有日期，没有时间，以当天8点30分为开始时间
  IF V_BEGIN_DATE=DATE(V_BEGIN_DATE) THEN
    SET V_BEGIN_DATE =DATE(V_BEGIN_DATE) + 0.3542;
  END IF;
  --传递的开始日期在下午17点30分之后，以次日8点30分为开始时间
  IF V_BEGIN_DATE>=DATE(V_BEGIN_DATE) + 0.7295 THEN
    SET V_BEGIN_DATE =DATE(V_BEGIN_DATE) + 1.3542;
  END IF;
  --剔除开始日期是节假日，以后续第一个工作日8点30分为开始时间
  SELECT COUNT(*) INTO V_JJRDAYS FROM PUB_JJR WHERE JJR_DATE = DATE(V_BEGIN_DATE);
  LOOP
    EXIT WHEN V_JJRDAYS=0;
    SET V_BEGIN_DATE = DATE(V_BEGIN_DATE) + 1.3542;
    SELECT COUNT(*) INTO V_JJRDAYS FROM PUB_JJR WHERE JJR_DATE = DATE(V_BEGIN_DATE);
  END LOOP;
  
  --传递的结束日期只有日期，没有时间，以当天17点30分为结束时间
  IF V_END_DATE=DATE(V_END_DATE) THEN
    SET V_END_DATE =DATE(V_END_DATE) + 0.7295;
  END IF;
  --传递的结束日期在下午17点30分之后，以当天17点30分为结束时间
  IF V_END_DATE>=DATE(V_END_DATE) + 0.7295 THEN
    SET V_END_DATE =DATE(V_END_DATE) + 0.7295;
  END IF;
  --剔除结束日期是节假日，以前一个工作日17点30分为结束时间
  SELECT COUNT(*) INTO V_JJRDAYS FROM PUB_JJR WHERE JJR_DATE = DATE(V_END_DATE);
  LOOP
    EXIT WHEN V_JJRDAYS=0;
    SET V_END_DATE = DATE(V_END_DATE) - 1 + 0.7295;
    SELECT COUNT(*) INTO V_JJRDAYS FROM PUB_JJR WHERE JJR_DATE = DATE(V_END_DATE);
  END LOOP;
  
  --起始、截止日期均非节假日时，计算日期差
  SET V_BETWEENDAYS = V_END_DATE - V_BEGIN_DATE;
  
  --剔除日期间隔中的节假日天数
  SELECT COUNT(*) INTO V_JJRDAYS FROM PUB_JJR WHERE JJR_DATE > V_BEGIN_DATE AND JJR_DATE < V_END_DATE;
  SET V_BETWEENDAYS = V_BETWEENDAYS - V_JJRDAYS;
  
  IF V_BETWEENDAYS < 0 THEN
    RETURN (0);
  ELSE
    RETURN(V_BETWEENDAYS);
  END IF;
END$$

DELIMITER ;
