DELIMITER $$

DROP FUNCTION IF EXISTS F_SEQ_NEXTVAL_ADMIN$$

CREATE FUNCTION F_SEQ_NEXTVAL_ADMIN(P_TABLENAME VARCHAR(4000))
RETURNS BIGINT
NOT DETERMINISTIC
MODIFIES SQL DATA
BEGIN
    RETURN SEQ_NEXTVAL(UPPER(P_TABLENAME));
END$$

DELIMITER ;
