DELIMITER $$

DROP FUNCTION IF EXISTS FUNC_XXBD_CHECK_JLDW$$

CREATE FUNCTION FUNC_XXBD_CHECK_JLDW(V_JLDWMC VARCHAR(4000), V_JLDWDM VARCHAR(4000))
RETURNS DECIMAL(38,10)
NOT DETERMINISTIC
READS SQL DATA
BEGIN
  DECLARE V_NUMBER BIGINT;

/*
  SELECT COUNT(*)
    INTO V_NUMBER
    FROM CKTS_DM_HGJLDW T
   WHERE T.HGJLDW_DM=V_JLDWDM
     AND '.'||T.HGJLDWQC||'.' LIKE '%.'||UPPER(V_JLDWMC)||'.%';
*/
  SELECT COUNT(*)
    INTO V_NUMBER
    FROM CKTS_DM_HGJLDW T
   WHERE T.HGJLDW_DM IN (SELECT S.HGJLDW_DM 
                           FROM CKTS_DM_HGJLDW S 
                          WHERE '.'||S.HGJLDWQC||'.' LIKE '%.'||UPPER(V_JLDWMC)||'.%')
     AND T.HGJLDW_DM IN (SELECT S.HGJLDW_DM 
                           FROM CKTS_DM_HGJLDW S 
                          WHERE '.'||S.HGJLDWQC||'.' LIKE '%.'||(SELECT R.HGJLDWQC FROM CKTS_DM_HGJLDW R WHERE R.HGJLDW_DM=V_JLDWDM)||'.%');

  RETURN V_NUMBER;
END$$

DELIMITER ;
