DELIMITER $$

DROP PROCEDURE IF EXISTS FUNC_XXBD_QUERY_CPCODEKZ$$

CREATE PROCEDURE FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH DECIMAL(38,10), V_IN_KZLX VARCHAR(4000), V_IN_YXQ DATETIME, OUT V_OUT_KZXX VARCHAR(4000), OUT P_RESULT DECIMAL(38,10))
routine_body: BEGIN
  DECLARE LN_R BIGINT DEFAULT 0;
  DECLARE LN_ERROR BIGINT DEFAULT 0;

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET LN_ERROR = BJTS_SQLCODE_001;
      SET V_OUT_KZXX ='C';

  END;
SELECT KZXX
      INTO V_OUT_KZXX
      FROM (SELECT KZXX
              FROM GS_DJ_CKTMSDAB_KZ
             WHERE NSRDZDAH = V_IN_NSRDZDAH
               AND KZLX = V_IN_KZLX
               AND FLAG ='1'
               AND V_IN_YXQ BETWEEN ST_DATE AND END_DATE
             ORDER BY KZXX DESC)
     WHERE 1=1
LIMIT 1;
  END;
  IF LN_ERROR=0 THEN
    SET LN_R =1;
  END IF;
  SET P_RESULT = LN_R; LEAVE routine_body;
END$$

DELIMITER ;
