DELIMITER $$

DROP PROCEDURE IF EXISTS P_DELETE_SB_SBXX$$

CREATE PROCEDURE P_DELETE_SB_SBXX()
routine_body: BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';




  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
    DO ORA_CONCAT('失败:', BJTS_SQLERRM_001);

  END;
BEGIN
  DECLARE BJTS_FETCH_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_RS_NSR_ID_001 LONGTEXT;
  DECLARE BJTS_FETCH_CURSOR_001 CURSOR FOR
select id from sb_sbxx_hz hz where hz.sbzt_dm= '39';
  OPEN BJTS_FETCH_CURSOR_001;
  BJTS_FETCH_LOOP_001: LOOP
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_FETCH_DONE_001 = TRUE;
      FETCH BJTS_FETCH_CURSOR_001 INTO BJTS_RS_NSR_ID_001;
    END;
    IF BJTS_FETCH_DONE_001 THEN
      LEAVE BJTS_FETCH_LOOP_001;
    END IF;


    delete from sb_sbxx_sbsj where id = BJTS_RS_NSR_ID_001;
    delete from sb_sbxx_fksj where id = BJTS_RS_NSR_ID_001;
    commit;

  END LOOP BJTS_FETCH_LOOP_001;
  CLOSE BJTS_FETCH_CURSOR_001;
END;
  COMMIT;
  END$$

DELIMITER ;
