DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MDT_CYSM$$

CREATE PROCEDURE PROC_XXBD_MDT_CYSM
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
  调整日期：20201119，对疑点MDT_BJGX_LACY_CKHW_USD、MDT_BJGX_LACY_CKHW_RMB的校验逻辑进行修正，原来用了报关单离岸价与明细表比较，修正为发票离岸价与明细表比较
  调整日期：20201201，对疑点MDT_BJGX_LACY_CKHW_USD、MDT_BJGX_LACY_CKHW_RMB的校验逻辑进行修正，取消明细表为红字冲减时的比较
  调整日期：20201215，对疑点MDT_BJGX_LACY_CKHW_CKFP的校验逻辑进行修正，取消明细表为红字冲减时的比较
  调整日期：20211123，对疑点MDT_LACY_BGD_USDLAJ的校验逻辑进行修正，仅校验bgd201表，不校验bgd202表，与202表的校验改到PROC_XXBD_MDT_TSSB_BGD中进行
  修改日期：20230207，修改代理证明出口申报离岸价差异表的疑点逻辑和提示
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  --离岸价差异明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_CYSM_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;
  SET LC_YDOBJECT ='离岸差异';

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_CYSM_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_LACY_CKHW_CKPZ','E','出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']未申报免退税出口明细！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_CYSM_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MDT_TSSB_LSB S WHERE S.SBID=T.SBID AND IFNULL(S.DLCKHWZMHM, S.CKBGDH)=IFNULL(T.DLCKHWZMHM, T.CKBGDH));
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_CYSM_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_LACY_CKHW_CKFP','E','出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']出口发票号码与货物出口明细不一致！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_CYSM_LSB T
          INNER JOIN CKTS_SB_MDT_TSSB_LSB S ON S.SBID=T.SBID AND IFNULL(S.DLCKHWZMHM, S.CKBGDH)=IFNULL(T.DLCKHWZMHM, T.CKBGDH) AND INSTR(S.CKTMSYWLXDMJH,'HZCJ')=0
          WHERE T.SBID=V_IN_SBID
            AND T.CKFPH<>S.CKFPH;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_CYSM_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_LACY_CKHW_USD','E','出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']出口发票美元离岸价与货物出口明细不一致！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_CYSM_LSB T
          INNER JOIN CKTS_SB_MDT_TSSB_LSB S ON S.SBID=T.SBID AND IFNULL(S.DLCKHWZMHM, S.CKBGDH)=IFNULL(T.DLCKHWZMHM, T.CKBGDH) AND INSTR(S.CKTMSYWLXDMJH,'HZCJ')=0
          WHERE T.SBID=V_IN_SBID
            AND T.CKFPMYLAJ<>S.MYLAJ;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_CYSM_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_LACY_CKHW_RMB','E','出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']出口发票人民币离岸价与货物出口明细不一致！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_CYSM_LSB T
          INNER JOIN CKTS_SB_MDT_TSSB_LSB S ON S.SBID=T.SBID AND IFNULL(S.DLCKHWZMHM, S.CKBGDH)=IFNULL(T.DLCKHWZMHM, T.CKBGDH) AND INSTR(S.CKTMSYWLXDMJH,'HZCJ')=0
          WHERE T.SBID=V_IN_SBID
            AND T.CKFPRMBLAJ<>S.RMBLAJ;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_CYSM_LSB',NULL,NULL,T.SBXH,NULL,'MDT_LACY_BGD_USDLAJ','E','出口货物报关单号[' || T.CKBGDH || ']美元离岸价[' || T.MYLAJ || ']与电子信息中[' || S.MYLAJ || ']不一致！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_CYSM_LSB T
          INNER JOIN CKTS_WBSJ_HG_BGD201 S ON S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.CKBGDH)=21
            AND T.MYLAJ<>S.MYLAJ;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_CYSM_LSB',NULL,NULL,T.SBXH,NULL,'MDT_LACY_DLZM_USDLAJ','E','代理出口货物证明号[' || T.DLCKHWZMHM || ']美元离岸价[' || T.MYLAJ || ']与电子信息中[' || S.MYLAJ || ']不一致！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_CYSM_LSB T
          INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM S ON S.DJXH=V_IN_DJXH AND S.DLCKHWZMHM=T.DLCKHWZMHM
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.DLCKHWZMHM)=20
            AND T.MYLAJ<>S.MYLAJ;
    COMMIT;
  END;
END$$

DELIMITER ;
