DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_JSB$$

CREATE PROCEDURE PROC_XXBD_JSB
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（出口已使用旧设备退税）
  修改日期：20220615，根据2022年9号公告，合并收汇与不能收汇
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LDT_TODAY       DATETIME;

  DECLARE LC_QYHGDM       VARCHAR(20);
  DECLARE LC_QYLXDM       VARCHAR(20);
  DECLARE LC_TSJSFSDM     VARCHAR(20);
  DECLARE LC_WMZHFWQYBZ   VARCHAR(20);
  DECLARE LC_SFYSFW       VARCHAR(20);
  DECLARE LC_YSFW         VARCHAR(50);
  DECLARE LC_YSFS         VARCHAR(50);
  DECLARE LC_YFSJ         VARCHAR(50);
  DECLARE LC_ZXFLAG       VARCHAR(20);

  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LN_TGSHZL       BIGINT;
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LN_ROWNUM_CKMX  BIGINT;
  DECLARE LN_ROWNUM_CKSH  BIGINT;
  DECLARE LN_ROWNUM_CQSB  BIGINT;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';
  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  IF V_IN_SSSQ>DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m') THEN
    BEGIN
      SET V_OUT_STATUS ='05';
      SET V_OUT_MESSAGE ='申报所属时期超出合理范围！';
      LEAVE routine_body;
    END;
  END IF;

  -- 取各申报明细表数据记录
  BEGIN
  DECLARE BJTS_SQLCODE_009 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_009 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_009 = MYSQL_ERRNO, BJTS_SQLERRM_009 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='06';
      SET V_OUT_MESSAGE ='查询申报记录数据失败！';
      LEAVE routine_body;

  END;
SELECT COUNT(1)
      INTO LN_ROWNUM_CKMX
      FROM CKTS_SB_YS_SBMX_LSB
     WHERE SBID=V_IN_SBID;
    SELECT COUNT(1)
      INTO LN_ROWNUM_CKSH
      FROM CKTS_SB_YS_CKSH_LSB
     WHERE SBID=V_IN_SBID;
    SELECT COUNT(1)
      INTO LN_ROWNUM_CQSB
      FROM CKTS_SB_YS_SBMX_LSB
     WHERE SBID=V_IN_SBID
       AND (((STR_TO_DATE(ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y'), '0420'), '%Y%m%d')<DATE(CURRENT_TIMESTAMP)) AND (CKRQ_1<MAKEDATE(YEAR(CURRENT_TIMESTAMP), 1))) OR (CKRQ_1<DATE_ADD(MAKEDATE(YEAR(CURRENT_TIMESTAMP), 1), INTERVAL -12 MONTH)));
  END;
  IF LN_ROWNUM_CKMX=0 THEN
    BEGIN
      SET V_OUT_STATUS ='07';
      SET V_OUT_MESSAGE ='申报数据为空！';
      LEAVE routine_body;
    END;
  END IF;

  -- 查询企业基本信息
  BEGIN
  DECLARE BJTS_SQLCODE_008 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_008 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_008 = MYSQL_ERRNO, BJTS_SQLERRM_008 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='08';
      SET V_OUT_MESSAGE ='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;

  END;
SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  END;
  IF LC_ZXFLAG='Y' THEN
    BEGIN
      SET V_OUT_STATUS ='09';
      SET V_OUT_MESSAGE ='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;
    END;
  END IF;

  -- 取企业的FLGLCD信息, TGSHZL信息，判断是否需要申报收汇
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD, LN_CPCODEKZ);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      SET V_OUT_STATUS ='10';
      SET V_OUT_MESSAGE ='查询出口企业分类管理类型出错！';
      LEAVE routine_body;
    END;
  END IF;

  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'YBNSRRD',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      SET V_OUT_STATUS ='12';
      SET V_OUT_MESSAGE ='企业当前非增值税一般纳税人，不允许申报出口退（免）税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TQQY',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 THEN
    BEGIN
      SET V_OUT_STATUS ='13';
      SET V_OUT_MESSAGE ='企业当前处于出口退税停权期间，不允许申报出口退（免）税业务！';
      LEAVE routine_body;
    END;
  END IF;

  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXMS',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      SET V_OUT_STATUS ='14';
      SET V_OUT_MESSAGE ='企业当前处于放弃退（免）税权选择免税期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXZS',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      SET V_OUT_STATUS ='15';
      SET V_OUT_MESSAGE ='企业当前处于放弃退（免）税权选择征税期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTMS',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      SET V_OUT_STATUS ='16';
      SET V_OUT_MESSAGE ='企业当前处于放弃退（免）税权期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;

  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TGSHZL',LDT_TODAY,LC_KZXX, LN_TGSHZL);
  IF (LC_FLGLCD='D') AND LN_ROWNUM_CKMX>0 AND LN_ROWNUM_CKSH=0 THEN
    BEGIN
      SET V_OUT_STATUS ='27';
      SET V_OUT_MESSAGE ='出口退（免）税管理类别为四类的企业，申报出口退免税时必须申报收汇情况表！';
      LEAVE routine_body;
    END;
  ELSEIF (LN_TGSHZL>0) AND LN_ROWNUM_CKMX>0 AND LN_ROWNUM_CKSH=0 THEN
    BEGIN
      SET V_OUT_STATUS ='28';
      SET V_OUT_MESSAGE ='被认定为需提供收汇资料的企业，申报出口退免税时必须申报收汇情况表！';
      LEAVE routine_body;
    END;
  ELSEIF (LN_ROWNUM_CQSB>0) AND LN_ROWNUM_CKMX>0 AND LN_ROWNUM_CKSH=0 THEN
    BEGIN
      SET V_OUT_STATUS ='29';
      SET V_OUT_MESSAGE ='超期申报数据，申报出口退免税时必须申报收汇情况表！';
      LEAVE routine_body;
    END;
  END IF;

  BEGIN
  DECLARE BJTS_SQLCODE_007 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_007 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_007 = MYSQL_ERRNO, BJTS_SQLERRM_007 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='51';
      SET V_OUT_MESSAGE =ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('出口已使用旧设备退税明细自检出错：', BJTS_SQLCODE_007), ' - '), BJTS_SQLERRM_007);
      LEAVE routine_body;

  END;
CALL PROC_XXBD_JSB_TSSB(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
  END;

  BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='52';
      SET V_OUT_MESSAGE =ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('出口报关单自检出错：', BJTS_SQLCODE_006), ' - '), BJTS_SQLERRM_006);
      LEAVE routine_body;

  END;
CALL PROC_XXBD_JSB_TSSB_BGD(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
  END;

  BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='53';
      SET V_OUT_MESSAGE =ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口证明自检出错：', BJTS_SQLCODE_005), ' - '), BJTS_SQLERRM_005);
      LEAVE routine_body;

  END;
CALL PROC_XXBD_JSB_TSSB_DLZM(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
  END;

  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='54';
      SET V_OUT_MESSAGE =ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('增值税专用发票自检出错：', BJTS_SQLCODE_004), ' - '), BJTS_SQLERRM_004);
      LEAVE routine_body;

  END;
CALL PROC_XXBD_JSB_TSSB_ZZSFP(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
  END;

  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='55';
      SET V_OUT_MESSAGE =ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('海关进口增值税缴款书自检出错：', BJTS_SQLCODE_003), ' - '), BJTS_SQLERRM_003);
      LEAVE routine_body;

  END;
CALL PROC_XXBD_JSB_TSSB_JKZZS(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
  END;

  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='62';
      SET V_OUT_MESSAGE =ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('出口收汇申报资料自检出错：', BJTS_SQLCODE_002), ' - '), BJTS_SQLERRM_002);
      LEAVE routine_body;

  END;
CALL PROC_XXBD_JSB_CKSH(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
  END;

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='63';
      SET V_OUT_MESSAGE =ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('海关商品代码调整表自检出错：', BJTS_SQLCODE_001), ' - '), BJTS_SQLERRM_001);
      LEAVE routine_body;

  END;
CALL PROC_XXBD_JSB_HGSPTZ(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
  END;

END$$

DELIMITER ;
