DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_TSZM_TYYBSWTS$$

CREATE PROCEDURE PROC_XXBD_TSZM_TYYBSWTS
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（退运已补税未退税证明）
  调整日期：20211025，根据金三H65**疑点，调整部分疑点级别，由错误类疑点改为警告类疑点
  调整日期：20211215，根据临安生产企业已办理退免税后改单导致后续免抵退申报退运冲减无法正常进行的问题，咨询魏浩原业务思路（默认改单或撤单的都是未办理退免税的），增加疑点判断
  调整日期：20230511，1、根据全电票规则调整发票的关联，用JHPZH代替FPDM+FPHM
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LDT_TODAY    DATETIME;

  DECLARE LC_QYHGDM       VARCHAR(20);
  DECLARE LC_QYLXDM       VARCHAR(20);
  DECLARE LC_TSJSFSDM     VARCHAR(20);
  DECLARE LC_WMZHFWQYBZ   VARCHAR(20);
  DECLARE LC_SFYSFW       VARCHAR(20);
  DECLARE LC_YSFW         VARCHAR(50);
  DECLARE LC_YSFS         VARCHAR(50);
  DECLARE LC_YFSJ         VARCHAR(50);
  DECLARE LC_ZXFLAG       VARCHAR(20);

  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LN_ROWNUM_TSSB  BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  IF V_IN_SSSQ>DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m') THEN
    BEGIN
      SET V_OUT_STATUS ='05';
      SET V_OUT_MESSAGE ='申报所属时期超出合理范围！';
      LEAVE routine_body;
    END;
  END IF;

  -- 取各申报明细表数据记录
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='06';
      SET V_OUT_MESSAGE ='查询申报记录数据失败！';
      LEAVE routine_body;

  END;
SELECT COUNT(1)
      INTO LN_ROWNUM_TSSB
      FROM CKTS_ZM_TYYBSWTS_LSB
     WHERE SBID=V_IN_SBID;
  END;
  IF LN_ROWNUM_TSSB=0 THEN
    BEGIN
      SET V_OUT_STATUS ='07';
      SET V_OUT_MESSAGE ='申报数据为空！';
      LEAVE routine_body;
    END;
  END IF;

  -- 查询企业基本信息
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='08';
      SET V_OUT_MESSAGE ='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;

  END;
SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  END;
  IF LC_ZXFLAG='R' THEN
    BEGIN
      SET V_OUT_STATUS ='09';
      SET V_OUT_MESSAGE ='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;
    END;
  END IF;

  -- 取企业的FLGLCD信息, TGSHZL信息，判断是否需要申报收汇
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD, LN_CPCODEKZ);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      SET V_OUT_STATUS ='10';
      SET V_OUT_MESSAGE ='查询出口企业分类管理类型出错！';
      LEAVE routine_body;
    END;
  END IF;

  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'YBNSRRD',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      SET V_OUT_STATUS ='12';
      SET V_OUT_MESSAGE ='企业当前非增值税一般纳税人，不允许申报出口退（免）税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TQQY',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 THEN
    BEGIN
      SET V_OUT_STATUS ='13';
      SET V_OUT_MESSAGE ='企业当前处于出口退税停权期间，不允许申报出口退（免）税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXMS',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      SET V_OUT_STATUS ='14';
      SET V_OUT_MESSAGE ='企业当前处于放弃退（免）税权选择免税期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXZS',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      SET V_OUT_STATUS ='15';
      SET V_OUT_MESSAGE ='企业当前处于放弃退（免）税权选择征税期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTMS',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      SET V_OUT_STATUS ='16';
      SET V_OUT_MESSAGE ='企业当前处于放弃退（免）税权期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;

  SET LC_YDOBJECT ='退运证明';
  BEGIN
    -- 报关单
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_BGD_WDZXX','I',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', T.CKBGDH), ']无电子信息！'),'Y',CURRENT_TIMESTAMP
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.CKBGDH)=21
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_HG_BGD201 S WHERE S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH);
    COMMIT;

    BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKBGDH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKRQ_SH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TMSZTBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TYYBSWTSTYLX_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSSBSL_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TYSL_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_KTYSL_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TYYBSWTSTYLXDM_C_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_DLSBSL_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKHWTYYBSWTSZMBH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_QYGBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_QYGWDDBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_QYGCXCKBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_UUID_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT A.SBXH,
                          A.CKBGDH,
                          DATE(B.CKRQ_1) AS CKRQ_SH,
                          A.TMSZTBZ,
                          A.TYYBSWTSTYLX_DM,
                          B.TSSBSL,
                          A.TYSL,
                          B.CKSL-B.TYSL AS KTYSL,
                          C.TYYBSWTSTYLX_DM AS TYYBSWTSTYLXDM_C,
                          B.DLSBSL,
                          D.CKHWTYYBSWTSZMBH,
                          B.QYGBZ,
                          B.QYGWDDBZ,
                          B.QYGCXCKBZ,
                          E.UUID
                     FROM CKTS_ZM_TYYBSWTS_LSB A
                    INNER JOIN CKTS_WBSJ_HG_BGD201 B ON B.DJXH=V_IN_DJXH AND B.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_WBSJ_HG_ZLKZDCLXX_JGB C ON C.DJXH=V_IN_DJXH AND C.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_WBSJ_ZJ_TYYBSWTSZM D ON D.DJXH=V_IN_DJXH AND D.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_GCB_ZM_TYYBSWTS E ON E.DJXH=V_IN_DJXH AND E.CKBGDH=A.CKBGDH
                    WHERE A.SBID=V_IN_SBID
                      AND LENGTH(A.CKBGDH)=21;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_LSF_XX_SBXH_002, BJTS_LSF_XX_CKBGDH_002, BJTS_LSF_XX_CKRQ_SH_002, BJTS_LSF_XX_TMSZTBZ_002, BJTS_LSF_XX_TYYBSWTSTYLX_DM_002, BJTS_LSF_XX_TSSBSL_002, BJTS_LSF_XX_TYSL_002, BJTS_LSF_XX_KTYSL_002, BJTS_LSF_XX_TYYBSWTSTYLXDM_C_002, BJTS_LSF_XX_DLSBSL_002, BJTS_LSF_XX_CKHWTYYBSWTSZMBH_002, BJTS_LSF_XX_QYGBZ_002, BJTS_LSF_XX_QYGWDDBZ_002, BJTS_LSF_XX_QYGCXCKBZ_002, BJTS_LSF_XX_UUID_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
      BEGIN
        IF (TIMESTAMPDIFF(MONTH, BJTS_LSF_XX_CKRQ_SH_002, LDT_TODAY)>12) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'TSZM_TYBS_BGD_CKRQ_CQSB','I',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', BJTS_LSF_XX_CKBGDH_002), ']退运日期离出口日期['), DATE_FORMAT(BJTS_LSF_XX_CKRQ_SH_002, '%Y-%m-%d')), ']超过12个月！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_TMSZTBZ_002='已办理退（免）税' AND BJTS_LSF_XX_TSSBSL_002=0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'TSZM_TYBS_BGD_TMSZT_YSB','E',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', BJTS_LSF_XX_CKBGDH_002), ']未退税，但退运证明选择“已办理退（免）税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (BJTS_LSF_XX_TMSZTBZ_002='尚未申报退（免）税' AND BJTS_LSF_XX_TSSBSL_002>0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'TSZM_TYBS_BGD_TMSZT_WSB','E',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', BJTS_LSF_XX_CKBGDH_002), ']已退税，但退运证明选择“尚未申报退（免）税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_TYSL_002>BJTS_LSF_XX_KTYSL_002) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'TSZM_TYBS_BGD_TYSL_OVER','I',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', BJTS_LSF_XX_CKBGDH_002), ']申报退运数量['), BJTS_LSF_XX_TYSL_002), ']大于可办理退运数量['), BJTS_LSF_XX_KTYSL_002), ']！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_DLSBSL_002>0 AND BJTS_LSF_XX_CKHWTYYBSWTSZMBH_002 IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'TSZM_TYBS_BGD_DLCK','I',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', BJTS_LSF_XX_CKBGDH_002), ']为代理出口业务，没有委托方开具的出口货物已补税（未退税）证明！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_QYGBZ_002='Y' AND BJTS_LSF_XX_QYGWDDBZ_002='Y' AND BJTS_LSF_XX_QYGCXCKBZ_002='Y') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'TSZM_TYBS_BGD_QYG','I',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', BJTS_LSF_XX_CKBGDH_002), ']为启运港业务，出口货物未运抵离境港不再实际出口且海关撤销出口货物报关单！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_TYYBSWTSTYLXDM_C_002 IN ('1','2','3') OR BJTS_LSF_XX_UUID_002 IS NOT NULL THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'TSZM_TYBS_BGD_TYZM_DUP','E',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', BJTS_LSF_XX_CKBGDH_002), ']存在未处理完毕的退运、改单或撤单标识！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        -- 20211215，根据临安生产企业已办理退免税后改单导致后续免抵退申报退运冲减无法正常进行的问题，咨询魏浩原业务思路（默认改单或撤单的都是未办理退免税的），增加疑点判断
        IF LC_TSJSFSDM='1' AND BJTS_LSF_XX_TYYBSWTSTYLX_DM_002 IN ('2','3') AND BJTS_LSF_XX_TSSBSL_002>0 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'TSZM_TYBS_BGD_TMSZT_TYLX','E',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', BJTS_LSF_XX_CKBGDH_002), ']已退税，请先红字冲减申报以后办理改单或撤单证明！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;
  END;

  BEGIN
    -- 代理证明
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_DLZM_WDZXX','I',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', T.CKBGDH), ']无电子信息！'),'Y',CURRENT_TIMESTAMP
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.CKBGDH)=20
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_ZJ_DLCKHWZM S WHERE S.DJXH=V_IN_DJXH AND S.DLCKHWZMHM=T.CKBGDH);
    COMMIT;

    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_DLCKHWZMHM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKRQ_SH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TMSZTBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TYYBSWTSTYLX_DM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSSBSL_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TYSL_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_KTYSL_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_UUID_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT A.SBXH,
                          A.CKBGDH AS DLCKHWZMHM,
                          DATE(B.CKRQ_1) AS CKRQ_SH,
                          A.TMSZTBZ,
                          A.TYYBSWTSTYLX_DM,
                          B.TSSBSL,
                          A.TYSL,
                          B.CKSL-B.TYSL AS KTYSL,
                          E.UUID
                     FROM CKTS_ZM_TYYBSWTS_LSB A
                    INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM B ON B.DJXH=V_IN_DJXH AND B.DLCKHWZMHM=A.CKBGDH
                     LEFT JOIN CKTS_GCB_ZM_TYYBSWTS E ON E.DJXH=V_IN_DJXH AND E.CKBGDH=A.CKBGDH
                    WHERE A.SBID=V_IN_SBID
                      AND LENGTH(A.CKBGDH)=20;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_SBXH_001, BJTS_LSF_XX_DLCKHWZMHM_001, BJTS_LSF_XX_CKRQ_SH_001, BJTS_LSF_XX_TMSZTBZ_001, BJTS_LSF_XX_TYYBSWTSTYLX_DM_001, BJTS_LSF_XX_TSSBSL_001, BJTS_LSF_XX_TYSL_001, BJTS_LSF_XX_KTYSL_001, BJTS_LSF_XX_UUID_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      BEGIN
        IF (TIMESTAMPDIFF(MONTH, BJTS_LSF_XX_CKRQ_SH_001, LDT_TODAY)>12) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'TSZM_TYBS_DLZM_CKRQ_CQSB','I',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']退运日期离出口日期['), DATE_FORMAT(BJTS_LSF_XX_CKRQ_SH_001, '%Y-%m-%d')), ']超过12个月！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_TMSZTBZ_001='已办理退（免）税' AND BJTS_LSF_XX_TSSBSL_001=0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'TSZM_TYBS_DLZM_TMSZT_YSB','E',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']未退税，但退运证明选择“已办理退（免）税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (BJTS_LSF_XX_TMSZTBZ_001='尚未申报退（免）税' AND BJTS_LSF_XX_TSSBSL_001>0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'TSZM_TYBS_DLZM_TMSZT_WSB','E',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']已退税，但退运证明选择“尚未申报退（免）税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_TYSL_001>BJTS_LSF_XX_KTYSL_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'TSZM_TYBS_DLZM_TYSL_OVER','I',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']申报退运数量['), BJTS_LSF_XX_TYSL_001), ']大于可办理退运数量['), BJTS_LSF_XX_KTYSL_001), ']！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_UUID_001 IS NOT NULL THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'TSZM_TYBS_DLZM_TYZM_DUP','E',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']存在未处理完毕的退运、改单或撤单标识！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        -- 20211215，根据临安生产企业已办理退免税后改单导致后续免抵退申报退运冲减无法正常进行的问题，咨询魏浩原业务思路（默认改单或撤单的都是未办理退免税的），增加疑点判断
        IF LC_TSJSFSDM='1' AND BJTS_LSF_XX_TYYBSWTSTYLX_DM_001 IN ('2','3') AND BJTS_LSF_XX_TSSBSL_001>0 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'TSZM_TYBS_DLZM_TMSZT_TYLX','E',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']已退税，请先红字冲减申报以后办理改单或撤单证明！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
  END;

  BEGIN
    -- 增值税发票
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_JHPZH_WDZXX','E',ORA_CONCAT(ORA_CONCAT('进货凭证号码[', T.JHPZH), ']无电子信息！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND (LENGTH(T.JHPZH)=20 OR LENGTH(T.JHPZH)=18)
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_FP_ZZSZYFPXX S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.JHPZH=T.JHPZH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_SBTMSE_OVER','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('申报的原退（免）税额[', T.YSBMDTSE), ']大于进货凭证的税额['), S.SE), ']！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_ZM_TYYBSWTS_LSB T
          INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX S ON S.DJXH=V_IN_DJXH AND S.JHPZH=T.JHPZH
          WHERE T.SBID=V_IN_SBID
            AND (LENGTH(T.JHPZH)=20 OR LENGTH(T.JHPZH)=18)
            AND T.YSBMDTSE>S.SE+0.01;
    COMMIT;
  END;

  BEGIN
    -- 进口增值税
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_JHPZH_WDZXX','E',ORA_CONCAT(ORA_CONCAT('进货凭证号码[', T.JHPZH), ']无电子信息！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.JHPZH)=22
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_HG_JKJKS S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.HGZYJKSHM=T.JHPZH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_SBTMSE_OVER','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('申报的原退（免）税额[', T.YSBMDTSE), ']大于进货凭证的税额['), S.SKJE), ']！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_ZM_TYYBSWTS_LSB T
          INNER JOIN CKTS_WBSJ_HG_JKJKS S ON S.DJXH=V_IN_DJXH AND S.HGZYJKSHM=T.JHPZH
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.JHPZH)=22
            AND T.YSBMDTSE>S.SKJE;
    COMMIT;
  END;

  BEGIN
    -- 缴款书号码
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_JKSHM_WDZXX','E',ORA_CONCAT(ORA_CONCAT('该缴款书号码[', T.JKSHM), ']不存在！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.JKSHM IS NOT NULL
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_GT3_ZS_JKS S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.DZSPHM=T.JKSHM);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_JKSE_BYZ','I',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('补缴税额[', T.YBJTMSK), ']与实际缴纳税款['), S.SJJE), ']不符！'),'Y',CURRENT_TIMESTAMP
           FROM CKTS_ZM_TYYBSWTS_LSB T
          INNER JOIN CKTS_WBSJ_GT3_ZS_JKS S ON S.DJXH=V_IN_DJXH AND S.DZSPHM=T.JKSHM
          WHERE T.SBID=V_IN_SBID
            AND T.YBJTMSK>S.SJJE+0.01;
    COMMIT;
  END;
END$$

DELIMITER ;
