DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MDT_XTHH$$

CREATE PROCEDURE PROC_XXBD_MDT_XTHH
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LC_ZTXTHHBZ     VARCHAR(20);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  --先退后核明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_XTHH_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;
  SET LC_YDOBJECT ='先退后核';

  BEGIN
    SELECT T.ZTXTHHBZ
      INTO LC_ZTXTHHBZ
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  EXCEPTION
    WHEN OTHERS THEN
      SET LC_ZTXTHHBZ ='N';
  END;
  IF LC_ZTXTHHBZ='Y' THEN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_XTHH_LSB','GS_DJ_CKTMSDAB',NULL,T.SBXH,NULL,'MDT_XTHH_ZGBA','E','企业已被暂停先退税后核销业务！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_XTHH_LSB T
          WHERE T.SBID=V_IN_SBID;
    COMMIT;
  ELSE
    BEGIN
      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                  'CKTS_SB_MDT_XTHH_LSB','CKTS_SB_MDT_XTHHZG_JGB',NULL,T.SBXH,NULL,'MDT_XTHH_HTBA','E','申报先退税后核销合同号[' || T.CKHTH || ']未备案！','N',CURRENT_TIMESTAMP
             FROM CKTS_SB_MDT_XTHH_LSB T
            WHERE T.SBID=V_IN_SBID
              AND NOT EXISTS (SELECT 1 FROM CKTS_JGB_BA_XTHHZG S WHERE S.DJXH=V_IN_DJXH AND S.CKHTH=T.CKHTH);
      COMMIT;
      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                  'CKTS_SB_MDT_XTHH_LSB','CKTS_SB_MDT_XTHHZG_JGB',NULL,T.SBXH,NULL,'MDT_XTHH_HTZF','E','申报先退税后核销合同号[' || T.CKHTH || ']的资格申请已作废！','N',CURRENT_TIMESTAMP
             FROM CKTS_SB_MDT_XTHH_LSB T
            WHERE T.SBID=V_IN_SBID
              AND EXISTS (SELECT 1 FROM CKTS_JGB_BA_XTHHZG S WHERE S.DJXH=V_IN_DJXH AND S.CKHTH=T.CKHTH AND S.ZFBZ_1='Y')
              AND NOT EXISTS (SELECT 1 FROM CKTS_JGB_BA_XTHHZG S WHERE S.DJXH=V_IN_DJXH AND S.CKHTH=T.CKHTH AND S.ZFBZ_1='N');
      COMMIT;

      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                  'CKTS_SB_MDT_XTHH_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_XTHH_CKHW_HTH','E','先退后核附表中合同号[' || T.CKHTH || ']出口货物报关单号[' || T.CKBGDH || ']未申报免退税出口明细！','N',CURRENT_TIMESTAMP
             FROM CKTS_SB_MDT_XTHH_LSB T
            WHERE T.SBID=V_IN_SBID
              AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MDT_TSSB_LSB S WHERE S.SBID=T.SBID AND S.CKHTH=T.CKHTH AND S.CKBGDH=T.CKBGDH);
      COMMIT;
    END;
  END IF;
END$$

DELIMITER ;
