DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MTS_HZCJ$$

CREATE PROCEDURE PROC_XXBD_MTS_HZCJ
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_SQLCODE DECIMAL(38,10) DEFAULT 0;
  DECLARE LC_SQLERRM VARCHAR(8000);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';
END$$

DELIMITER ;
