DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MSZM_LLJGHX$$

CREATE PROCEDURE PROC_XXBD_MSZM_LLJGHX
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（来料加工免税核销）
  调整:20210414，根据金三疑点级别，调整MSZM_LLHX_BGD_WDZXX、MSZM_LLHX_LLJGSZCH_WDZXX、MSZM_LLHX_SL_YKFPHWSL为可挑过疑点
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LDT_TODAY    DATETIME;

  DECLARE LC_QYHGDM       VARCHAR(20);
  DECLARE LC_QYLXDM       VARCHAR(20);
  DECLARE LC_TSJSFSDM     VARCHAR(20);
  DECLARE LC_WMZHFWQYBZ   VARCHAR(20);
  DECLARE LC_SFYSFW       VARCHAR(20);
  DECLARE LC_YSFW         VARCHAR(50);
  DECLARE LC_YSFS         VARCHAR(50);
  DECLARE LC_YFSJ         VARCHAR(50);
  DECLARE LC_ZXFLAG       VARCHAR(20);

  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LN_ROWNUM_TSSB  BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  IF V_IN_SSSQ>DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m') THEN
    BEGIN
      SET V_OUT_STATUS ='05';
      SET V_OUT_MESSAGE ='申报所属时期超出合理范围！';
      LEAVE routine_body;
    END;
  END IF;

  --取各申报明细表数据记录
  BEGIN
    SELECT COUNT(1)
      INTO LN_ROWNUM_TSSB
      FROM CKTS_ZM_LLJGHX_LSB
     WHERE SBID=V_IN_SBID;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_OUT_STATUS ='06';
      SET V_OUT_MESSAGE ='查询申报记录数据失败！';
      LEAVE routine_body;
  END;
  IF LN_ROWNUM_TSSB=0 THEN
    BEGIN
      SET V_OUT_STATUS ='07';
      SET V_OUT_MESSAGE ='申报数据为空！';
      LEAVE routine_body;
    END;
  END IF;

  --查询企业基本信息
  BEGIN
    SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_OUT_STATUS ='08';
      SET V_OUT_MESSAGE ='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;
  END;
  IF LC_ZXFLAG='R' THEN
    BEGIN
      SET V_OUT_STATUS ='09';
      SET V_OUT_MESSAGE ='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;
    END;
  END IF;

  SET LN_CPCODEKZ =FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TQQY',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 THEN
    BEGIN
      SET V_OUT_STATUS ='13';
      SET V_OUT_MESSAGE ='企业当前处于出口退税停权期间，不允许申报出口退（免）税业务！';
      LEAVE routine_body;
    END;
  END IF;
  SET LN_CPCODEKZ =FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQMSQ',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      SET V_OUT_STATUS ='17';
      SET V_OUT_MESSAGE ='企业当前处于放弃免税权期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;

  SET LC_YDOBJECT ='来料核销';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_LLJGHX_LSB',NULL,NULL,T.SBXH,NULL,'MSZM_LLHX_BGD_WDZXX','W','出口货物报关单号[' || T.CKBGDH || ']无电子信息！','Y',CURRENT_TIMESTAMP
           FROM CKTS_ZM_LLJGHX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_HG_BGD201 S WHERE S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_LLJGHX_LSB',NULL,NULL,T.SBXH,NULL,'MSZM_LLHX_LLJGMSZMBH_WDZXX','E','来料加工免税证明号[' || T.LLJGMSZMBH || ']无电子信息！','N',CURRENT_TIMESTAMP
           FROM CKTS_ZM_LLJGHX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_JGB_ZM_LLJG S WHERE S.DJXH=V_IN_DJXH AND S.LLJGMSZMBH=T.LLJGMSZMBH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_LLJGHX_LSB',NULL,NULL,T.SBXH,NULL,'MSZM_LLHX_LLJGSZCH_WDZXX','W','来料登记册号[' || T.LLJGSZCH || ']无电子信息！','Y',CURRENT_TIMESTAMP
           FROM CKTS_ZM_LLJGHX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_JGB_ZM_LLJG S WHERE S.DJXH=V_IN_DJXH AND S.LLJGSZCH=T.LLJGSZCH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           WITH LLJGMSZM AS (SELECT B.LLJGSZCH AS ZM_SZCH, SUM(B.YKFPHWSL) AS ZM_SL
                               FROM CKTS_JGB_ZM_LLJG B
                              WHERE B.DJXH=V_IN_DJXH
                              GROUP BY B.LLJGSZCH),
                LLJGZMHX AS (SELECT A.LLJGSZCH AS HX_SZCH, SUM(A.SL) AS HX_SL, MIN(A.SBXH) AS SBXH
                               FROM CKTS_ZM_LLJGHX_LSB A
                              WHERE A.SBID=V_IN_SBID
                              GROUP BY A.LLJGSZCH)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_ZM_LLJGHX_LSB',NULL,NULL,LLJGZMHX.SBXH,NULL,'MSZM_LLHX_SL_YKFPHWSL','W','来料登记册号[' || LLJGZMHX.HX_SZCH || ']的核销数量[' || LLJGZMHX.HX_SL || ']小于来料加工免税证明发票开具数量[' || LLJGMSZM.ZM_SL || ']！','Y',CURRENT_TIMESTAMP
           FROM LLJGZMHX
          INNER JOIN LLJGMSZM ON LLJGMSZM.ZM_SZCH=LLJGZMHX.HX_SZCH
          WHERE LLJGMSZM.ZM_SL>LLJGZMHX.HX_SL;
    COMMIT;
  END;
END$$

DELIMITER ;
