DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MTS_HGSPTZ$$

CREATE PROCEDURE PROC_XXBD_MTS_HGSPTZ
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  修改日期：20230207，修改代理证明出口申报调整表的疑点逻辑和提示
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  --海关代码调整明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_HGSPTZ_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;
  SET LC_YDOBJECT ='代码调整';

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MTS_HGSPTZ_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,T.SBXH,NULL,'MTS_BJGX_DMTZ_CKMX_CKPZ','E','出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']未申报免退税出口明细！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MTS_HGSPTZ_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_TSSB_LSB S WHERE S.SBID=T.SBID AND IFNULL(S.DLZMH, S.CKBGDH)=IFNULL(T.DLCKHWZMHM, T.CKBGDH));
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MTS_HGSPTZ_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,T.SBXH,NULL,'MTS_BJGX_DMTZ_CKMX_CKRQ','E','出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']的出口日期与免退税出口明细表中不一致！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MTS_HGSPTZ_LSB T
          INNER JOIN CKTS_SB_MTS_TSSB_LSB S ON S.SBID=T.SBID AND IFNULL(S.DLZMH, S.CKBGDH)=IFNULL(T.DLCKHWZMHM, T.CKBGDH)
          WHERE T.SBID=V_IN_SBID
            AND DATE(T.CKRQ_1)<>DATE(S.CKRQ_1);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MTS_HGSPTZ_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,T.SBXH,NULL,'MTS_BJGX_DMTZ_CKMX_SPDM','E','出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']调整前商品代码与免退税出口明细表中不一致！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MTS_HGSPTZ_LSB T
          INNER JOIN CKTS_SB_MTS_TSSB_LSB S ON S.SBID=T.SBID AND IFNULL(S.DLZMH, S.CKBGDH)=IFNULL(T.DLCKHWZMHM, T.CKBGDH)
          WHERE T.SBID=V_IN_SBID
            AND T.CKSP_DM<>S.CKSP_DM;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MTS_HGSPTZ_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,T.SBXH,NULL,'MTS_BJGX_DMTZ_CKMX_TSLV','E','出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']调整后退税率与免退税进货明细表中不一致！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MTS_HGSPTZ_LSB T
          INNER JOIN CKTS_SB_MTS_TSSB_LSB S ON S.SBID=T.SBID AND IFNULL(S.DLZMH, S.CKBGDH)=IFNULL(T.DLCKHWZMHM, T.CKBGDH)
          WHERE T.SBID=V_IN_SBID
            AND T.TZHTSL<>S.TSL;
    COMMIT;
  END;
END$$

DELIMITER ;
