DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MDT_YFSJ$$

CREATE PROCEDURE PROC_XXBD_MDT_YFSJ
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  IN V_IN_YFSJFW VARCHAR(4000), /*出口企业备案研发设计类应税服务类型代码*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LC_MSG          VARCHAR(200) DEFAULT ' ';

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  -- 研发设计明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_YFSJ_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;
  SET LC_YDOBJECT ='应税服务';

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_YFSJFWDM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_YFSJFWJC_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_YFSJFWMC_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT YFSJFWDM, YFSJFWJC, YFSJFWMC FROM CKTS_DM_YFSJFW A WHERE A.YXBZ='Y';
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_YFSJFWDM_001, BJTS_LSF_XX_YFSJFWJC_001, BJTS_LSF_XX_YFSJFWMC_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    BEGIN
      SELECT COUNT(1)
        INTO LN_MXROW
        FROM CKTS_SB_MDT_YFSJ_LSB T
       WHERE T.SBID=V_IN_SBID AND T.CKTMSYWLXDMJH LIKE ORA_CONCAT(ORA_CONCAT('%', BJTS_LSF_XX_YFSJFWJC_001), '%');
      IF LN_MXROW>0 AND INSTR(V_IN_YFSJFW,BJTS_LSF_XX_YFSJFWDM_001)=0 THEN
        SET LC_MSG =ORA_CONCAT(ORA_CONCAT(LC_MSG, BJTS_LSF_XX_YFSJFWMC_001), ',');
      END IF;
    END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
  IF LC_MSG<>' ' OR TRIM(LC_MSG) IS NOT NULL THEN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
     SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
            'CKTS_SB_MDT_YFSJ_LSB',NULL,NULL,NULL,NULL,'MDT_BJGX_YSFW_SPDM','E',ORA_CONCAT(ORA_CONCAT('不允许申报未备案的应税服务[', LC_MSG), ']。'),'N',CURRENT_TIMESTAMP
;
    COMMIT;
  END IF;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_YFSJ_LSB','CKTS_SB_MDT_SYYK_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_YSFW_FWSQ_HTH','E',ORA_CONCAT(ORA_CONCAT('此合同号[', T.HTH), ']在零税率应税服务收讫明细中不存在！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_YFSJ_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_SB_MDT_SYYK_LSB S
                             WHERE S.SBID=V_IN_SBID
                               AND S.HTH=T.HTH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_YFSJ_LSB',NULL,NULL,T.SBXH,NULL,'MDT_YSFW_CKRQ_NSRZG','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业非增值税一般纳税人！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_YFSJ_LSB T
           LEFT JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='YBNSRRD' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND S.KZLX IS NULL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_YFSJ_LSB',NULL,NULL,T.SBXH,NULL,'MDT_YSFW_CKRQ_TQQY','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业处于出口退税停权期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_YFSJ_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TQQY' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_YFSJ_LSB',NULL,NULL,T.SBXH,NULL,'MDT_YSFW_CKRQ_MSQY','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业处于免税期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_YFSJ_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSGMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_YFSJ_LSB',NULL,NULL,T.SBXH,NULL,'MDT_YSFW_CKRQ_FQTS','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']放弃零税率应税服务退税期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_YFSJ_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQLSL' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;
  END;
END$$

DELIMITER ;
