DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MTS_TSSB_DLZM$$

CREATE PROCEDURE PROC_XXBD_MTS_TSSB_DLZM
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  调整日期：20201106，对金额增加null判断
  调整日期：20201111，增加关联号下进货、出口的商品名称、计量单位校验
  调整日期：20210528，修改进出口明细商品名称、计量单位比较的疑点代码
  调整日期：20210603，调整疑点关联业务字段，关联号+申报序号
  调整日期：20210707，MTS_CKMX_DLZM_USDLAJ，对数量部分申报的美元离岸价进行折算，疑点为可挑过
  调整日期：20211208，调整免退税疑点描述字段中申报序号与关联单证号的顺序，使其与客户端疑点展示一致
  调整日期：20220615，MTS_CKMX_DLZM_CKSL分层级，申报数量大于出口数量不可挑过，否则大于剩余数量可挑过
  调整日期：20220701，根据全电票规则调整发票的关联，用JHPZH代替FPDM+FPHM
  调整日期：20230313，增加MTS_CKMX_DLZM_BSQ_BAQD、MTS_CKMX_DLZM_BSQ_BANR疑点判断
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CMCD_LEN     BIGINT;
  DECLARE LC_JHPZHJLDW    VARCHAR(75);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  -- 代理证明号出口明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_TSSB_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.DLZMH IS NOT NULL;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  SET LC_YDOBJECT ='代理证明';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_CKMX_DLZM_WDZXX','E',
                ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', T.DLZMH), ']无电子信息！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MTS_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.DLZMH IS NOT NULL
            AND FUNC_XXBD_CHECK_YWLX(ORA_CONCAT(ORA_CONCAT(',', T.CKTMSYWLXDMJH), ',')) = 0
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_ZJ_DLCKHWZM S WHERE S.DJXH=V_IN_DJXH AND S.DLCKHWZMHM=T.DLZMH);
    COMMIT;
  END;

  BEGIN
    BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_DLZMH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_BYTSBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKRQ_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKRQ_SH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKTMSYWLXDMJH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSP_DM_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSP_DM_SH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSL_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSL_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSSBSL_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TYSL_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_SYSL_SH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_MYLAJ_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_MYLAJ_SH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_MYLAJ_JS_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_JGFS_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_JGFSTSLX_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_YSFS_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_GLH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_DYJLDW_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_DEJLDW_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_SBJLDW_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_GFHHGSPMC_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT A.SBXH,
                          A.DLZMH,
                          B.BYTSBZ,
                          DATE(A.CKRQ_1) AS CKRQ_SB,
                          DATE(B.CKRQ_1) AS CKRQ_SH,
                          IFNULL(A.CKTMSYWLXDMJH, ' ') AS CKTMSYWLXDMJH,
                          A.CKSP_DM AS CKSP_DM_SB,
                          B.CKSP_DM AS CKSP_DM_SH,
                          A.CKSL AS CKSL_SB,
                          B.CKSL,
                          IFNULL(B.TSSBSL, 0) AS TSSBSL,
                          IFNULL(B.TYSL, 0) AS TYSL,
                          B.CKSL-IFNULL(B.TSSBSL, 0)-IFNULL(B.TYSL, 0) AS SYSL_SH,
                          A.MYLAJ AS MYLAJ_SB,
                          B.MYLAJ-IFNULL(B.TSSBMYLAJ, 0)-IFNULL(B.TYMYLAJ, 0) AS MYLAJ_SH,
                          (B.MYLAJ-IFNULL(B.TSSBMYLAJ, 0)-IFNULL(B.TYMYLAJ, 0)) *
                          (CASE WHEN (A.CKSL=0) OR (B.CKSL-IFNULL(B.TSSBSL, 0)-IFNULL(B.TYSL, 0)=0) THEN 0
                                ELSE A.CKSL / (B.CKSL-IFNULL(B.TSSBSL, 0)-IFNULL(B.TYSL, 0)) END) AS MYLAJ_JS,
                          C.JGFS_DM,
                          C.JGFSTSLX_DM,
                          B.YSFS_DM,
                          A.GLH,
                          IFNULL(B.DYJLDW_DM, ' ') AS DYJLDW_DM,
                          IFNULL(B.DEJLDW_DM, ' ') AS DEJLDW_DM,
                          IFNULL(B.SBJLDW_DM, ' ') AS SBJLDW_DM,
                          B.GFHHGSPMC
                     FROM CKTS_SB_MTS_TSSB_LSB A
                    INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM B ON B.DJXH=V_IN_DJXH AND B.DLCKHWZMHM=A.DLZMH
                     LEFT JOIN CKTS_DM_HGJGFS C ON C.JGFS_DM=B.JGFS_DM
                    WHERE A.SBID=V_IN_SBID
                      AND A.DLZMH IS NOT NULL
                      AND FUNC_XXBD_CHECK_YWLX(ORA_CONCAT(ORA_CONCAT(',', A.CKTMSYWLXDMJH), ',')) = 0;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_LSF_XX_SBXH_002, BJTS_LSF_XX_DLZMH_002, BJTS_LSF_XX_BYTSBZ_002, BJTS_LSF_XX_CKRQ_SB_002, BJTS_LSF_XX_CKRQ_SH_002, BJTS_LSF_XX_CKTMSYWLXDMJH_002, BJTS_LSF_XX_CKSP_DM_SB_002, BJTS_LSF_XX_CKSP_DM_SH_002, BJTS_LSF_XX_CKSL_SB_002, BJTS_LSF_XX_CKSL_002, BJTS_LSF_XX_TSSBSL_002, BJTS_LSF_XX_TYSL_002, BJTS_LSF_XX_SYSL_SH_002, BJTS_LSF_XX_MYLAJ_SB_002, BJTS_LSF_XX_MYLAJ_SH_002, BJTS_LSF_XX_MYLAJ_JS_002, BJTS_LSF_XX_JGFS_DM_002, BJTS_LSF_XX_JGFSTSLX_DM_002, BJTS_LSF_XX_YSFS_DM_002, BJTS_LSF_XX_GLH_002, BJTS_LSF_XX_DYJLDW_DM_002, BJTS_LSF_XX_DEJLDW_DM_002, BJTS_LSF_XX_SBJLDW_DM_002, BJTS_LSF_XX_GFHHGSPMC_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
      BEGIN
        SET LC_YDOBJECT ='代理证明';

        IF BJTS_LSF_XX_BYTSBZ_002='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_BYTS','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']已被标注为“不予退税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_CKRQ_SB_002<>BJTS_LSF_XX_CKRQ_SH_002) AND (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'BSQ')=0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_CKRQ','E',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']出口日期['), DATE_FORMAT(BJTS_LSF_XX_CKRQ_SB_002, '%Y-%m-%d')), ']与电子信息中['), DATE_FORMAT(BJTS_LSF_XX_CKRQ_SH_002, '%Y-%m-%d')), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        SET LN_CMCD_LEN = CASE WHEN LENGTH(BJTS_LSF_XX_CKSP_DM_SB_002) > LENGTH(BJTS_LSF_XX_CKSP_DM_SH_002) THEN LENGTH(BJTS_LSF_XX_CKSP_DM_SH_002) ELSE LENGTH(BJTS_LSF_XX_CKSP_DM_SB_002) END;
        IF SUBSTR(BJTS_LSF_XX_CKSP_DM_SB_002,1,LN_CMCD_LEN)<>SUBSTR(BJTS_LSF_XX_CKSP_DM_SH_002,1,LN_CMCD_LEN) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_SPDM','E',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']商品代码['), BJTS_LSF_XX_CKSP_DM_SB_002), ']与电子信息中['), BJTS_LSF_XX_CKSP_DM_SH_002), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_CKSL_SB_002 > BJTS_LSF_XX_CKSL_002 +1) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_CKSL','E',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']申报退税数量['), BJTS_LSF_XX_CKSL_SB_002), ']超过电子信息中出口数量['), BJTS_LSF_XX_CKSL_002), ']！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (BJTS_LSF_XX_CKSL_SB_002 > BJTS_LSF_XX_SYSL_SH_002 + 1) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_CKSL','I',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']申报退税数量['), BJTS_LSF_XX_CKSL_SB_002), ']超过电子信息中剩余数['), BJTS_LSF_XX_SYSL_SH_002), ']（其中出口['), BJTS_LSF_XX_CKSL_002), ']退税申报['), BJTS_LSF_XX_TSSBSL_002), ']退运['), BJTS_LSF_XX_TYSL_002), ']）！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (ABS(BJTS_LSF_XX_MYLAJ_SB_002-BJTS_LSF_XX_MYLAJ_JS_002)>1 AND ABS(BJTS_LSF_XX_MYLAJ_SB_002-BJTS_LSF_XX_MYLAJ_JS_002)>0.05 * BJTS_LSF_XX_MYLAJ_JS_002) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_USDLAJ','I',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']美元离岸价['), BJTS_LSF_XX_MYLAJ_SB_002), ']超过电子信息中合理范围，其中剩余数量['), BJTS_LSF_XX_SYSL_SH_002), ']，剩余美元离岸价['), BJTS_LSF_XX_MYLAJ_SH_002), ']，本次申报数量['), BJTS_LSF_XX_CKSL_SB_002), ']！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (TRIM(BJTS_LSF_XX_JGFS_DM_002) IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_MYXZ_BCZ','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']在电子信息中监管方式不存在！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSE
          IF (TRIM(BJTS_LSF_XX_JGFSTSLX_DM_002)='0') THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_MYXZ_BTS','E',
                        ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']在电子信息中监管方式['), BJTS_LSF_XX_JGFS_DM_002), ']不退税！'),'N',CURRENT_TIMESTAMP
;
            COMMIT;
          END IF;
        END IF;

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'DWCB')>0 AND BJTS_LSF_XX_JGFS_DM_002<>'3422' AND BJTS_LSF_XX_JGFS_DM_002<>'22') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_DWCB_NOT','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']非对外承包业务，“业务类型”不应包含“DWCB”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'DWCB')=0 AND (BJTS_LSF_XX_JGFS_DM_002='3422' OR BJTS_LSF_XX_JGFS_DM_002='22')) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_DWCB_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']为对外承包业务，“业务类型”应包含“DWCB”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'BSQ')>0 THEN
          IF BJTS_LSF_XX_YSFS_DM_002<>'0' THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_BSQ_NOT','E',
                        ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']非经保税区出口业务，“业务类型”不应包含“BSQ”！'),'N',CURRENT_TIMESTAMP
;
            COMMIT;
          ELSE
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_BSQ_BAQD','I',
                        ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']业务类型包含保税区BSQ，请核实是否附送《出境货物备案清单》！'),'Y',CURRENT_TIMESTAMP
;
            COMMIT;
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_BSQ_BANR','I',
                        ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']业务类型包含保税区BSQ，请核实出境货物备案清单的内容是否与报关单相关内容相符,出口日期填报是否准确！'),'Y',CURRENT_TIMESTAMP
;
            COMMIT;
          END IF;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'BSQ')=0 AND BJTS_LSF_XX_YSFS_DM_002='0') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_BSQ_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']为经保税区出口业务，“业务类型”应包含“BSQ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'JWTZ')>0 AND BJTS_LSF_XX_JGFS_DM_002<>'2210') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_JWTZ_NOT','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']非境外投资业务，“业务类型”不应包含“JWTZ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'JWTZ')=0 AND BJTS_LSF_XX_JGFS_DM_002='2210') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_JWTZ_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']为境外投资业务，“业务类型”应包含“JWTZ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'DWYZ')>0 AND BJTS_LSF_XX_JGFS_DM_002<>'3511') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_DWYZ_NOT','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']非对外援助业务，“业务类型”不应包含“DWYZ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'DWYZ')=0 AND BJTS_LSF_XX_JGFS_DM_002='3511') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_DWYZ_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']为对外援助业务，“业务类型”应包含“DWYZ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'XLXP')>0 AND BJTS_LSF_XX_JGFS_DM_002<>'1300') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_XLXP_NOT','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']非修理修配业务，“业务类型”不应包含“XLXP”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'XLXP')=0 AND BJTS_LSF_XX_JGFS_DM_002='1300') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_DLZM_XLXP_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']为修理修配业务，“业务类型”应包含“XLXP”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_YSFS_DM_002='T' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,BJTS_LSF_XX_GLH_002,'MTS_CKMX_CKPZH_YSFS','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLZMH_002), ']为出口到综合试验区（横琴平潭地区）的报关单！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

      -- 2020.11.11 增加关联号下进货、出口的商品名称、计量单位校验
      SET LC_YDOBJECT ='增值税发票';
      BEGIN
        BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_YY_SBXH_001 LONGTEXT;
  DECLARE BJTS_LSF_YY_GLH_001 LONGTEXT;
  DECLARE BJTS_LSF_YY_JHPZH_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT A.SBXH, A.GLH, A.JHPZH FROM CKTS_SB_MTS_TSJH_LSB A WHERE A.SBID=V_IN_SBID AND A.GLH=BJTS_LSF_XX_GLH_002 AND A.CKTMSPZLX_DM='02';
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_YY_SBXH_001, BJTS_LSF_YY_GLH_001, BJTS_LSF_YY_JHPZH_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
          BEGIN
            SELECT COUNT(1)
              INTO LN_MXROW
              FROM CKTS_WBSJ_FP_ZZSFPHWXX B
             WHERE B.DJXH=V_IN_DJXH AND B.JHPZH=BJTS_LSF_YY_JHPZH_001;
            IF LN_MXROW>0 THEN
              BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR NOT FOUND
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                              'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,BJTS_LSF_YY_SBXH_001,BJTS_LSF_YY_GLH_001,'MTS_JHMX_ZZSFP_SPMC_DLZM','I',
                              ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('增值税专用发票[', BJTS_LSF_YY_JHPZH_001), ']商品名称与代理证明商品名称['), BJTS_LSF_XX_GFHHGSPMC_002), ']不一致，请核对确认！'),'Y',CURRENT_TIMESTAMP
;
                  COMMIT;

  END;

  DECLARE EXIT HANDLER FOR 1172
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                              'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,BJTS_LSF_YY_SBXH_001,BJTS_LSF_YY_GLH_001,'MTS_JHMX_ZZSFP_SPMC_JLDW','I',
                              ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('增值税专用发票[', BJTS_LSF_YY_JHPZH_001), ']存在同一商品名称['), BJTS_LSF_XX_GFHHGSPMC_002), ']但计量单位不同的情形，请核对确认！'),'Y',CURRENT_TIMESTAMP
;
                  COMMIT;

  END;

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
                  ITERATE BJTS_CURSOR_LOOP_001;

  END;
SELECT DISTINCT B.JLDWMC
                  INTO LC_JHPZHJLDW
                  FROM CKTS_WBSJ_FP_ZZSFPHWXX B
                 WHERE B.DJXH=V_IN_DJXH AND B.JHPZH=BJTS_LSF_YY_JHPZH_001 AND B.GFHHWHYSLWMC=BJTS_LSF_XX_GFHHGSPMC_002;

                IF FUNC_XXBD_CHECK_JLDW(LC_JHPZHJLDW,BJTS_LSF_XX_DYJLDW_DM_002)=0 AND FUNC_XXBD_CHECK_JLDW(LC_JHPZHJLDW,BJTS_LSF_XX_DEJLDW_DM_002)=0 AND FUNC_XXBD_CHECK_JLDW(LC_JHPZHJLDW,BJTS_LSF_XX_SBJLDW_DM_002)=0 THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                              'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,BJTS_LSF_YY_SBXH_001,BJTS_LSF_YY_GLH_001,'MTS_JHMX_ZZSFP_JLDW_DLZM','I',
                              ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('增值税专用发票[', BJTS_LSF_YY_JHPZH_001), ']的计量单位['), LC_JHPZHJLDW), ']与代理证明计量单位不符，请核对确认！'),'Y',CURRENT_TIMESTAMP
;
                  COMMIT;
                END IF;
              END;
            END IF;
          END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
      END;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;
  END;
END$$

DELIMITER ;
