DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MTS_TSJH_ZZSFP$$

CREATE PROCEDURE PROC_XXBD_MTS_TSJH_ZZSFP
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  调整日期：20201106，对金额增加null判断
  调整日期：20201111，增加关联号下进货、出口的商品名称、计量单位校验，发票代码号码赋值移到主存储过程中
  调整日期：20201119，对疑点MTS_JHMX_ZZSFP_SBJE的描述进行调整，细化企业发票开票数、已申报数据提示
  调整日期：20201230，1、校验发票稽核信息时，剔除代开发票的稽核信息，代开发票开票人税号含DK
  调整日期：20210603，1、调整MTS_YSFW_ZZSFP_SBJE计税金额总量控制误差；2、调整疑点关联业务字段，关联号+申报序号
  调整日期：20211208，1、调整免退税疑点描述字段中申报序号与关联单证号的顺序，使其与客户端疑点展示一致
  调整日期：20220228，1、增加MTS_JHMX_ZZSFP_SBSE疑点，当发票本次申报总退税额大于发票总开票税额（误差+1）时提醒，不可挑过
  调整日期：20220517，1、疑点MTS_JHMX_ZZSFP_SBSE、MTS_JHMX_ZZSFP_SBSE提示信息增加关联业务字段1为申报序号
  调整日期：20220701，1、根据全电票规则调整发票的关联，用JHPZH代替FPDM+FPHM
  调整日期：20230207，1、修改全电发票关联虚开发票时的BUG。
  调整日期：20230315，调整出口企业首次申报日期取数口径，改为按税务机关+企业+业务代码查询首次发放日期
  调整日期：20230515，解决增值税发票外部数据部分数据稽核相符标志为空的问题（赋默认值N）
  调整日期：20230518，解决按税务机关+企业+业务代码查询首次发放日期有结果但日期为空的问题（赋默认值SYSDATE）
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LDT_TODAY       DATETIME;
  DECLARE LDT_SCSBRQ      DATETIME;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';
  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  --增值税专用发票记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_TSJH_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.CKTMSPZLX_DM='02';
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  --查询企业首次申报日期
  BEGIN
    SELECT IFNULL(T.FFRQ, CURRENT_TIMESTAMP)
      INTO LDT_SCSBRQ
      FROM CKTS_TY_YWBLXX_SCFFRQ T
     WHERE T.TSSWJG_DM_1=(SELECT SWJG_DM FROM GS_DJ_CKTMSDAB WHERE NSRDZDAH=V_IN_NSRDZDAH)
       AND T.DJXH=V_IN_DJXH AND T.LCSWSX_DM='LCSXA081039001';
  EXCEPTION
    WHEN OTHERS THEN
      SET LDT_SCSBRQ =LDT_TODAY;
  END;

  SET LC_YDOBJECT ='增值税发票';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_JHMX_ZZSFP_WDZXX','E','增值税专用发票[' || T.JHPZH || ']无电子信息！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MTS_TSJH_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.CKTMSPZLX_DM='02'
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_FP_ZZSZYFPXX S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.JHPZH=T.JHPZH);
    COMMIT;
  END;

  BEGIN
    SET LN_CPCODEKZ =FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
    FOR LSF_XX IN (SELECT A.SBXH,A.GLH,
                          A.JHPZH,
                          IFNULL(A.CKTMSYWLXDMJH, ' ') AS CKTMSYWLXDMJH,
                          IFNULL(B.JHXFZZSZYFPBZ, 'N') AS JHXFZZSZYFPBZ,
                          B.BYTSBZ,
                          A.GHFNSRSBH_1,
                          B.XFNSRSBH,
                          DATE(A.KPRQ) AS KPRQ_SB,
                          DATE(B.KPRQ) AS KPRQ_SH,
                          B.FPYT_DM,
                          IFNULL(B.FPSJBBZ, 'N') AS FPSJBZ,
                          IFNULL(B.NXZCKBZ, 'N') AS NXZCKBZ,
                          C.GHFNSRSBH
                     FROM CKTS_SB_MTS_TSJH_LSB A
                    INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX B ON B.DJXH=V_IN_DJXH AND B.JHPZH=A.JHPZH
                     LEFT JOIN CKTS_WBSJ_ZJ_XKFP C ON C.FP_DM||C.FPHM=A.JHPZH
                    WHERE A.SBID=V_IN_SBID
                      AND A.CKTMSPZLX_DM='02') LOOP
      BEGIN
        IF (LSF_XX.JHXFZZSZYFPBZ='N' AND INSTR(LSF_XX.XFNSRSBH,'DK')=0 AND (INSTR(LSF_XX.CKTMSYWLXDMJH,'RZZL')>0 OR LC_FLGLCD='D' OR (LC_FLGLCD='C' AND TIMESTAMPDIFF(MONTH, LDT_SCSBRQ, LDT_TODAY)<=12))) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_ZZSFP_WDZXX','E','增值税专用发票[' || LSF_XX.JHPZH || ']无稽核相符电子信息！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF LSF_XX.BYTSBZ='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_ZZSFP_BYTS','E','增值税专用发票[' || LSF_XX.JHPZH || ']已被标注为“不予退税”！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF LSF_XX.GHFNSRSBH_1<>LSF_XX.XFNSRSBH THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_ZZSFP_GHFNSR','E','增值税专用发票[' || LSF_XX.JHPZH || ']供货方纳税人[' || LSF_XX.GHFNSRSBH_1 || ']与电子信息中[' || LSF_XX.XFNSRSBH || ']不一致！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF LSF_XX.KPRQ_SB<>LSF_XX.KPRQ_SH THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_ZZSFP_KPRQ','E','增值税专用发票[' || LSF_XX.JHPZH || ']开票日期[' || DATE_FORMAT(LSF_XX.KPRQ_SB, '%Y-%m-%d') || ']与电子信息中[' || DATE_FORMAT(LSF_XX.KPRQ_SH, '%Y-%m-%d') || ']不一致！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF LSF_XX.FPYT_DM='3' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_ZZSFP_DBTS','E','增值税专用发票[' || LSF_XX.JHPZH || ']在电子信息中申报用途代码为“3-代办退税”！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (LSF_XX.FPYT_DM='1' AND LSF_XX.FPSJBZ='Y' AND LSF_XX.NXZCKBZ='N') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_ZZSFP_YDK','E','增值税专用发票[' || LSF_XX.JHPZH || ']在电子信息中已勾选用于抵扣！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF LSF_XX.GHFNSRSBH IS NOT NULL THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_ZZSFP_XKFP','E','增值税专用发票[' || LSF_XX.JHPZH || ']在电子信息中为虚开增值税专用发票！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,T.SBXH,T.JHPZH,'MTS_JHMX_ZZSFP_SBJE','I',
                '增值税专用发票[' || T.JHPZH || ']申报退税的计税金额[' || T.JSJE || ']超过电子信息中剩余数[' || GREATEST(0,S.JE - IFNULL(S.HZCJJE, 0) - IFNULL(S.SBFPJSJE, 0) - IFNULL(S.LSLSBFPJSJE, 0)) ||
                ']（其中开票[' || S.JE || ']红字冲减[' || IFNULL(S.HZCJJE, 0) || ']出口货物劳务已申报[' || IFNULL(S.SBFPJSJE, 0) || ']外购应税服务已申报[' || IFNULL(S.LSLSBFPJSJE, 0) || ']）！','Y',CURRENT_TIMESTAMP
           FROM (SELECT A.JHPZH, SUM(A.JSJE) AS JSJE, MIN(A.SBXH) AS SBXH
                   FROM CKTS_SB_MTS_TSJH_LSB A
                  WHERE A.SBID=V_IN_SBID
                    AND A.CKTMSPZLX_DM='02'
                  GROUP BY A.JHPZH) T
          INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX S ON S.DJXH=V_IN_DJXH AND S.JHPZH=T.JHPZH
          WHERE T.JSJE > S.JE - IFNULL(S.HZCJJE, 0) - IFNULL(S.SBFPJSJE, 0) - IFNULL(S.LSLSBFPJSJE, 0);
    COMMIT;
    
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,T.SBXH,T.JHPZH,'MTS_JHMX_ZZSFP_SBSE','E',
                '增值税专用发票[' || T.JHPZH || ']申报退税额[' || T.TSE || ']超过电子信息中税额[' || IFNULL(S.SE, 0) || ']！','N',CURRENT_TIMESTAMP
           FROM (SELECT A.JHPZH, SUM(A.TSE) AS TSE, MIN(A.SBXH) AS SBXH
                   FROM CKTS_SB_MTS_TSJH_LSB A
                  WHERE A.SBID=V_IN_SBID
                    AND A.CKTMSPZLX_DM='02'
                  GROUP BY A.JHPZH) T
          INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX S ON S.DJXH=V_IN_DJXH AND S.JHPZH=T.JHPZH
          WHERE T.TSE > S.SE + 1;
    COMMIT;
  END;
END$$

DELIMITER ;
