DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_WZF_TSSB_BGD$$

CREATE PROCEDURE PROC_XXBD_WZF_TSSB_BGD
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外综服代办退税）
  调整日期：20201106，1、对金额增加null判断
  调整日期：20201119，1、调整改单报关单监控条件，由bgd202不存在改为bgd201.gdbz_1<>Y
  调整日期：20210113，1、调整改单报关单监控条件，改为bgd202不存在 且 bgd201.gdbz_1<>Y
  调整日期：20230313，增加WZF_DBTS_BGD_BSQ_BAQD、WZF_DBTS_BGD_BSQ_BANR疑点判断
  调整日期：20230814，针对异常扣税凭证做了追回处理后解除异常重新申报退税的总量控制bug，拆分WZF_DBTS_BGD_CKSL疑点、调整WZF_DBTS_BGD_MYLAJ疑点
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LN_CMCD_LEN     BIGINT;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  --报关单出口明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_DB_TSSB_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  SET LC_YDOBJECT ='代办出口';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_BGD_WDZXX','E',
                '出口货物报关单号[' || T.CKBGDH || ']无电子信息！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND FUNC_XXBD_CHECK_YWLX(',' || T.CKTMSYWLXDMJH || ',') = 0
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_HG_BGD201 S WHERE S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH);
    COMMIT;
  END;

  BEGIN
    FOR LSF_XX IN (SELECT A.SBXH,
                          A.CKBGDH,
                          B.BYTSBZ,
                          DATE(A.CKRQ_1) AS CKRQ_SB,
                          DATE(B.CKRQ_1) AS CKRQ_SH,
                          DATE(B.QYRQ_2) AS QYRQ_SH,
                          IFNULL(A.CKTMSYWLXDMJH, ' ') AS CKTMSYWLXDMJH,
                          A.CKSP_DM AS CKSP_DM_SB,
                          B.CKSP_DM AS CKSP_DM_SH,
                          D.TYYBSWTSTYLX_DM,
                          IFNULL(B.GDBZ_1, ' ') AS GDBZ_1,
                          E.CKBGDH AS CKBGDH_GD,
                          C.JGFS_DM,
                          C.JGFSTSLX_DM,
                          B.QYGBZ,
                          B.QYGCXCKBZ,
                          B.QYGWDDBZ,
                          B.QYGZCJGBZ,
                          B.YSFS_DM
                     FROM CKTS_SB_DB_TSSB_LSB A
                    INNER JOIN CKTS_WBSJ_HG_BGD201 B ON B.DJXH=V_IN_DJXH AND B.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_DM_HGJGFS C ON C.JGFS_DM=B.JGFS_DM
                     LEFT JOIN CKTS_JGB_ZM_TYYBSWTS D ON D.DJXH=V_IN_DJXH AND D.CKBGDH=A.CKBGDH AND IFNULL(D.ZFBZ_1, 'N')='N'
                     LEFT JOIN CKTS_WBSJ_HG_BGD202 E ON D.DJXH=V_IN_DJXH AND E.CKBGDH=A.CKBGDH
                    WHERE A.SBID=V_IN_SBID
                      AND FUNC_XXBD_CHECK_YWLX(',' || A.CKTMSYWLXDMJH || ',') = 0) LOOP
      BEGIN
        IF LSF_XX.BYTSBZ='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_BYTS','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']已被标注为“不予退税”！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        SET LN_CMCD_LEN = CASE WHEN LENGTH(LSF_XX.CKSP_DM_SB) > LENGTH(LSF_XX.CKSP_DM_SH) THEN LENGTH(LSF_XX.CKSP_DM_SH) ELSE LENGTH(LSF_XX.CKSP_DM_SB) END;
        IF SUBSTR(LSF_XX.CKSP_DM_SB,1,LN_CMCD_LEN)<>SUBSTR(LSF_XX.CKSP_DM_SH,1,LN_CMCD_LEN) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_SPDM','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']商品代码[' || LSF_XX.CKSP_DM_SB || ']与电子信息中[' || LSF_XX.CKSP_DM_SH || ']不一致！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        --1退运; 2改单; 3撤单
        IF LSF_XX.TYYBSWTSTYLX_DM='3' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_CD','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']曾办理过用途为”撤单“的有效的退运证明！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (LSF_XX.TYYBSWTSTYLX_DM='2' AND LSF_XX.GDBZ_1<>'Y' AND LSF_XX.CKBGDH_GD IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_GD','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']曾办理过用途为“改单”的有效的退运证明，且在“海关出口报关单改单数据”中不存在！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (TRIM(LSF_XX.JGFS_DM) IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_MYXZ_BCZ','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']在电子信息中监管方式不存在！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (TRIM(LSF_XX.JGFSTSLX_DM)='0') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_MYXZ_BTS','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']在电子信息中监管方式[' || LSF_XX.JGFS_DM || ']不退税！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'QYGTS')>0) THEN
          BEGIN
            IF (LSF_XX.CKRQ_SB<>LSF_XX.QYRQ_SH) AND (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')=0) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_CKRQ','E',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']出口日期[' || DATE_FORMAT(LSF_XX.CKRQ_SB, '%Y-%m-%d') || ']与电子信息中[' || DATE_FORMAT(LSF_XX.QYRQ_SH, '%Y-%m-%d') || ']不一致！','N',CURRENT_TIMESTAMP
;
              COMMIT;
            END IF;
            IF LSF_XX.QYGBZ<>'Y' THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_QYGTS_NOT','E',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']非启运港业务，“业务类型”不应包含“QYGTS”！','N',CURRENT_TIMESTAMP
;
              COMMIT;
            ELSE
              BEGIN
                IF LSF_XX.QYGCXCKBZ='Y' THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                              'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_QYGTS_CXCK','E',
                              '出口货物报关单号[' || LSF_XX.CKBGDH || ']为启运港业务，已经撤销出口！','N',CURRENT_TIMESTAMP
;
                  COMMIT;
                END IF;
                SET LN_CPCODEKZ =FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LSF_XX.QYRQ_SH,LC_FLGLCD);
                IF (LC_FLGLCD<>'A' AND LC_FLGLCD<>'B') THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                              'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_QYGTS_FLGLCD','E',
                              '出口货物报关单号[' || LSF_XX.CKBGDH || ']启运日当天该企业分类管理类别非一、二类，“业务类型”不应包含“QYGTS”！','N',CURRENT_TIMESTAMP
;
                  COMMIT;
                END IF;
                IF TIMESTAMPDIFF(MONTH, LSF_XX.QYRQ_SH, TRUNCATE(CURRENT_TIMESTAMP, 0))>2 THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                              'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_QYGTS_CKRQ','E',
                              '出口货物报关单号[' || LSF_XX.CKBGDH || ']超过启运日两月，“业务类型”不应包含“QYGTS”！','N',CURRENT_TIMESTAMP
;
                  COMMIT;
                END IF;
                IF LSF_XX.QYGWDDBZ='Y' THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                              'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_QYGTS_WDD','E',
                              '出口货物报关单号[' || LSF_XX.CKBGDH || ']未实际到达离境港，“业务类型”不应包含“QYGTS”！','N',CURRENT_TIMESTAMP
;
                  COMMIT;
                END IF;
              END;
            END IF;
          END;
        ELSE
          BEGIN
            IF (LSF_XX.CKRQ_SB<>LSF_XX.CKRQ_SH) AND (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')=0) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_CKRQ','E',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']出口日期[' || DATE_FORMAT(LSF_XX.CKRQ_SB, '%Y-%m-%d') || ']与电子信息中[' || DATE_FORMAT(LSF_XX.CKRQ_SH, '%Y-%m-%d') || ']不一致！','N',CURRENT_TIMESTAMP
;
              COMMIT;
            END IF;
            IF (LSF_XX.QYGBZ='Y' AND LSF_XX.QYGZCJGBZ='N') THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_QYGTS_NULL','E',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']为启运港业务，目前尚未收到结关信息，“业务类型”应包含“QYGTS”！','N',CURRENT_TIMESTAMP
;
              COMMIT;
            END IF;
          END;
        END IF;

        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')>0) THEN
          IF (LSF_XX.YSFS_DM<>'0') THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_BSQ_NOT','E',
                        '出口货物报关单号[' || LSF_XX.CKBGDH || ']非经保税区出口业务，“业务类型”不应包含“BSQ”！','N',CURRENT_TIMESTAMP
;
            COMMIT;
           ELSE
            BEGIN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_BSQ_BAQD','I',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']业务类型包含保税区BSQ，请核实是否附送《出境货物备案清单》！','Y',CURRENT_TIMESTAMP
;
              COMMIT;
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_BSQ_BANR','I',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']业务类型包含保税区BSQ，请核实出境货物备案清单的内容是否与报关单相关内容相符,出口日期填报是否准确！','Y',CURRENT_TIMESTAMP
;
              COMMIT;
            END;
           END IF;
        END IF;
        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')=0 AND LSF_XX.YSFS_DM='0') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_BSQ_NULL','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为经保税区出口业务，“业务类型”应包含“BSQ”！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF LSF_XX.YSFS_DM='T' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_BGD_YSFS','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为出口到综合试验区（横琴平潭地区）的报关单！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,NULL,T.CKBGDH,'WZF_DBTS_BGD_CKSL','E',
                '出口货物报关单号[' || T.CKBGDH || ']申报退税数量[' || T.CKSL_SB || ']超过报关单出口数量[' || S.CKSL || ']）！','N',CURRENT_TIMESTAMP
           FROM (SELECT A.CKBGDH, SUM(A.CKSL) AS CKSL_SB
                   FROM CKTS_SB_DB_TSSB_LSB A
                  WHERE A.SBID=V_IN_SBID
                   AND FUNC_XXBD_CHECK_YWLX(',' || A.CKTMSYWLXDMJH || ',') = 0
                  GROUP BY A.CKBGDH) T
          INNER JOIN CKTS_WBSJ_HG_BGD201 S ON S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH
          WHERE T.CKSL_SB > S.CKSL + 1.0;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,NULL,T.CKBGDH,'WZF_DBTS_BGD_CKSL','W',
                '出口货物报关单号[' || T.CKBGDH || ']申报退税数量[' || T.CKSL_SB || ']超过电子信息中剩余数[' || GREATEST(0,S.CKSL - IFNULL(S.TSSBSL, 0) - IFNULL(S.TYSL, 0) - IFNULL(S.DLSBSL, 0)) ||
                ']（其中出口[' || S.CKSL || ']退税申报[' || IFNULL(S.TSSBSL, 0) || ']退运[' || IFNULL(S.TYSL, 0) || ']代理申报[' || IFNULL(S.DLSBSL, 0) || ']）！','Y',CURRENT_TIMESTAMP
           FROM (SELECT A.CKBGDH, SUM(A.CKSL) AS CKSL_SB
                   FROM CKTS_SB_DB_TSSB_LSB A
                  WHERE A.SBID=V_IN_SBID
                   AND FUNC_XXBD_CHECK_YWLX(',' || A.CKTMSYWLXDMJH || ',') = 0
                  GROUP BY A.CKBGDH) T
          INNER JOIN CKTS_WBSJ_HG_BGD201 S ON S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH
          WHERE T.CKSL_SB <= S.CKSL + 1.0
            AND T.CKSL_SB > S.CKSL - IFNULL(S.TSSBSL, 0) - IFNULL(S.TYSL, 0) - IFNULL(S.DLSBSL, 0) + 1.0;
    COMMIT;


    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,NULL,T.CKBGDH,'WZF_DBTS_BGD_MYLAJ','W',
                '出口货物报关单号[' || T.CKBGDH || ']申报美元离岸价[' || T.MYLAJ_SB || ']超过电子信息中剩余数[' || GREATEST(0,S.MYLAJ - IFNULL(S.TSSBMYLAJ, 0) - IFNULL(S.TYMYLAJ, 0) - IFNULL(S.DLSBMYLAJ, 0)) ||
                ']（其中出口[' || S.MYLAJ || ']退税申报[' || IFNULL(S.TSSBMYLAJ, 0) || ']退运[' || IFNULL(S.TYMYLAJ, 0) || ']代理申报[' || IFNULL(S.DLSBMYLAJ, 0) || ']）！','Y',CURRENT_TIMESTAMP
           FROM (SELECT A.CKBGDH, SUM(A.MYLAJ) AS MYLAJ_SB
                   FROM CKTS_SB_DB_TSSB_LSB A
                  WHERE A.SBID=V_IN_SBID
                   AND FUNC_XXBD_CHECK_YWLX(',' || A.CKTMSYWLXDMJH || ',') = 0
                  GROUP BY A.CKBGDH) T
          INNER JOIN CKTS_WBSJ_HG_BGD201 S ON S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH
          WHERE T.MYLAJ_SB > S.MYLAJ - IFNULL(S.TSSBMYLAJ, 0) - IFNULL(S.TYMYLAJ, 0) - IFNULL(S.DLSBMYLAJ, 0) + 1.0;
    COMMIT;
  END;
END$$

DELIMITER ;
