DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MDT_YFSJ_SYYK$$

CREATE PROCEDURE PROC_XXBD_MDT_YFSJ_SYYK
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  --收营业款明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_SYYK_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;
  SET LC_YDOBJECT ='服务收讫';

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_SYYK_LSB','CKTS_SB_MDT_YFSJ_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_FWSQ_YSFW_HTH','E','此合同号[' || T.HTH || ']在零税率应税服务申报明细中不存在！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_SYYK_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_SB_MDT_YFSJ_LSB S
                             WHERE S.SBID=V_IN_SBID
                               AND S.HTH=T.HTH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_SYYK_LSB','CKTS_SB_MDT_YFSJ_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_FWSQ_YSFW_SKRMB','E','此合同号[' || T.HTH || ']当期收款金额（折人民币）合计与应税服务申报明细表应税服务营业额折人民币不一致！！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_YFSJ_LSB T
          INNER JOIN (SELECT S.HTH, SUM(S.SKJERMB) AS SKJERMBHJ
                        FROM CKTS_SB_MDT_SYYK_LSB S
                       WHERE S.SBID=V_IN_SBID
                       GROUP BY S.HTH) SS ON SS.HTH=T.HTH
          WHERE T.SBID=V_IN_SBID
            AND T.BQQRYSFWYYSRRMBJE<>SS.SKJERMBHJ;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_SYYK_LSB','CKTS_SB_MDT_YFSJ_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_FWSQ_YSFW_SKUSD','E','此合同号[' || T.HTH || ']当期收款金额（折美元）合计与应税服务申报明细表应税服务营业额折美元不一致！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_YFSJ_LSB T
          INNER JOIN (SELECT S.HTH, SUM(S.SKJEMY) AS SKJEMYHJ
                        FROM CKTS_SB_MDT_SYYK_LSB S
                       WHERE S.SBID=V_IN_SBID
                       GROUP BY S.HTH) SS ON SS.HTH=T.HTH
          WHERE T.SBID=V_IN_SBID
            AND T.BQSKJEMY<>SS.SKJEMYHJ;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_SYYK_LSB','CKTS_SB_MDT_YFSJ_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_FWSQ_YSFW_DFDWMC','E','此合同号[' || T.HTH || ']与零税率应税服务申报明细中同一合同号的境外单位名称不符！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_SYYK_LSB T
          INNER JOIN CKTS_SB_MDT_YFSJ_LSB S ON S.SBID=V_IN_SBID AND S.HTH=T.HTH
          WHERE T.SBID=V_IN_SBID
            AND T.FKDWMC <> S.JWDWMC;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_SYYK_LSB','CKTS_SB_MDT_YFSJ_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_FWSQ_YSFW_DFDWGJ','E','此合同号[' || T.HTH || ']与零税率应税服务申报明细中同一合同号的境外单位所在国家不符！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_SYYK_LSB T
          INNER JOIN CKTS_SB_MDT_YFSJ_LSB S ON S.SBID=V_IN_SBID AND S.HTH=T.HTH
          WHERE T.SBID=V_IN_SBID
            AND T.GJHDQSZ_DM <> S.GJHDQSZ_DM;
    COMMIT;
  END;
END$$

DELIMITER ;
