DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_GJ_ZZSFP$$

CREATE PROCEDURE PROC_XXBD_GJ_ZZSFP
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（购进自用货物免退税）
  调整日期：20201221，1、根据宁波加工区内退水电气大部分为小规模以及研发中心退国产设备政策第十三条，非增值税一般纳税人允许申报购进自用货物退税，对涉及一般纳税人资格的疑点进行调整
                      2、有关GJZY_BJGX_ZG_SDQ、GJZY_BJGX_ZG_GCSB这两个疑点的判断改成用当前日期，取消开票日期的判断
  调整日期：20201230，1、校验发票稽核信息时，剔除代开发票的稽核信息，代开发票开票人税号含DK
  调整日期：20220701，1、根据全电票规则调整发票的关联，用JHPZH代替FPDM+FPHM
  调整日期：20230207，1、修改全电发票关联虚开发票时的BUG。
  调整日期：20230315，调整出口企业首次申报日期取数口径，改为按税务机关+企业+业务代码查询首次发放日期
  调整日期：20230317，根据钱塘区项灵燕反应有企业发票重复申报进金三重复退税的问题，增加总量控制疑点
  调整日期：20230515，解决增值税发票外部数据部分数据稽核相符标志为空的问题（赋默认值N）
  调整日期：20230518，解决按税务机关+企业+业务代码查询首次发放日期有结果但日期为空的问题（赋默认值SYSDATE）
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LN_CPCODEKZ1    BIGINT;
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LDT_TODAY       DATETIME;
  DECLARE LDT_SCSBRQ      DATETIME;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';
  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  -- 购进自用货物发票记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_GJ_SBMX_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  -- 查询企业首次申报日期
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET LDT_SCSBRQ =LDT_TODAY;

  END;
SELECT IFNULL(T.FFRQ, CURRENT_TIMESTAMP)
      INTO LDT_SCSBRQ
      FROM CKTS_TY_YWBLXX_SCFFRQ T
     WHERE T.TSSWJG_DM_1=(SELECT SWJG_DM FROM GS_DJ_CKTMSDAB WHERE NSRDZDAH=V_IN_NSRDZDAH)
       AND T.DJXH=V_IN_DJXH AND T.LCSWSX_DM='LCSXA081042002';
  END;

  SET LC_YDOBJECT ='购进自用';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_ZZSFP_WDZXX','E',ORA_CONCAT(ORA_CONCAT('进货凭证号码[', T.JHPZH), ']无电子信息！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_GJ_SBMX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.JHPZZL_DM='1'
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_FP_ZZSZYFPXX S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.JHPZH=T.JHPZH);
    COMMIT;
  END;

  BEGIN
    CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD, LN_CPCODEKZ);
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKTMSYWLXDMJH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_JHPZH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_KPRQ_SB_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_KPRQ_SH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_GHFNSRSBH_1_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_XFNSRSBH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_JHXFZZSZYFPBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_BYTSBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_FPYT_DM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_FPSJBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_NXZCKBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_GHFNSRSBH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_JSJE_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_SYJE_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSE_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_SE_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT A.SBXH,
                          IFNULL(A.CKTMSYWLXDMJH, ' ') AS CKTMSYWLXDMJH,
                          A.JHPZH,
                          DATE(A.KPRQ) AS KPRQ_SB,
                          DATE(B.KPRQ) AS KPRQ_SH,
                          A.GHFNSRSBH_1,
                          B.XFNSRSBH,
                          IFNULL(B.JHXFZZSZYFPBZ, 'N') AS JHXFZZSZYFPBZ,
                          B.BYTSBZ,
                          B.FPYT_DM,
                          IFNULL(B.FPSJBBZ, 'N') AS FPSJBZ,
                          IFNULL(B.NXZCKBZ, 'N') AS NXZCKBZ,
                          C.GHFNSRSBH,
                          A.JSJE,
                          B.JE - IFNULL(B.HZCJJE, 0) - IFNULL(B.SBFPJSJE, 0) - IFNULL(B.LSLSBFPJSJE, 0) AS SYJE,
                          A.TSE,
                          B.SE
                     FROM CKTS_SB_GJ_SBMX_LSB A
                    INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX B ON B.DJXH=V_IN_DJXH AND B.JHPZH=A.JHPZH
                     LEFT JOIN CKTS_WBSJ_ZJ_XKFP C ON ORA_CONCAT(C.FP_DM, C.FPHM)=A.JHPZH
                    WHERE A.SBID=V_IN_SBID
                      AND A.JHPZZL_DM='1';
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_SBXH_001, BJTS_LSF_XX_CKTMSYWLXDMJH_001, BJTS_LSF_XX_JHPZH_001, BJTS_LSF_XX_KPRQ_SB_001, BJTS_LSF_XX_KPRQ_SH_001, BJTS_LSF_XX_GHFNSRSBH_1_001, BJTS_LSF_XX_XFNSRSBH_001, BJTS_LSF_XX_JHXFZZSZYFPBZ_001, BJTS_LSF_XX_BYTSBZ_001, BJTS_LSF_XX_FPYT_DM_001, BJTS_LSF_XX_FPSJBZ_001, BJTS_LSF_XX_NXZCKBZ_001, BJTS_LSF_XX_GHFNSRSBH_001, BJTS_LSF_XX_JSJE_001, BJTS_LSF_XX_SYJE_001, BJTS_LSF_XX_TSE_001, BJTS_LSF_XX_SE_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      BEGIN
        -- 20230317，根据钱塘区项灵燕反应有企业发票重复申报进金三重复退税的问题，增加总量控制疑点
        IF (BJTS_LSF_XX_JSJE_001 > BJTS_LSF_XX_SYJE_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'GJZY_JHMX_ZZSFP_SBJE','I',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('进货凭证号码[', BJTS_LSF_XX_JHPZH_001), ']申报退税的计税金额['), BJTS_LSF_XX_JSJE_001), ']超过电子信息中剩余数['), BJTS_LSF_XX_SYJE_001), ']，请检查是否重复申报！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (BJTS_LSF_XX_TSE_001 > BJTS_LSF_XX_SE_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'GJZY_JHMX_ZZSFP_SBSE','E',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('进货凭证号码[', BJTS_LSF_XX_JHPZH_001), ']申报退税额['), BJTS_LSF_XX_TSE_001), ']超过电子信息中税额['), BJTS_LSF_XX_SE_001), ']！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_JHXFZZSZYFPBZ_001='N' AND INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_001,'GCSB')>0 AND INSTR(BJTS_LSF_XX_XFNSRSBH_001,'DK')=0 AND (LC_FLGLCD='D' OR (LC_FLGLCD='C' AND TIMESTAMPDIFF(MONTH, LDT_SCSBRQ, LDT_TODAY)<=12))) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'GJZY_JHMX_ZZSFP_WDZXX','E',ORA_CONCAT(ORA_CONCAT('进货凭证号码[', BJTS_LSF_XX_JHPZH_001), ']无稽核相符电子信息！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_BYTSBZ_001='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'GJZY_JHMX_ZZSFP_BYTS','E',ORA_CONCAT(ORA_CONCAT('进货凭证号码[', BJTS_LSF_XX_JHPZH_001), ']已被标注为“不予退税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_GHFNSRSBH_1_001<>BJTS_LSF_XX_XFNSRSBH_001 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'GJZY_JHMX_ZZSFP_GHFNSR','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('进货凭证号码[', BJTS_LSF_XX_JHPZH_001), ']供货方纳税人['), BJTS_LSF_XX_GHFNSRSBH_1_001), ']与电子信息中['), BJTS_LSF_XX_XFNSRSBH_001), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_KPRQ_SB_001<>BJTS_LSF_XX_KPRQ_SH_001 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_ZZSFP_KPRQ','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('进货凭证号码[', BJTS_LSF_XX_JHPZH_001), ']开票日期['), DATE_FORMAT(BJTS_LSF_XX_KPRQ_SB_001, '%Y-%m-%d')), ']与电子信息中['), DATE_FORMAT(BJTS_LSF_XX_KPRQ_SH_001, '%Y-%m-%d')), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_FPYT_DM_001='3' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_ZZSFP_DBTS','E',ORA_CONCAT(ORA_CONCAT('进货凭证号码[', BJTS_LSF_XX_JHPZH_001), ']在电子信息中申报用途代码为“3-代办退税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (BJTS_LSF_XX_FPYT_DM_001='1' AND BJTS_LSF_XX_FPSJBZ_001='Y' AND BJTS_LSF_XX_NXZCKBZ_001='N') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_ZZSFP_YDK','E',ORA_CONCAT(ORA_CONCAT('进货凭证号码[', BJTS_LSF_XX_JHPZH_001), ']在电子信息中已勾选用于抵扣！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_GHFNSRSBH_001 IS NOT NULL THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_ZZSFP_XKFP','E',ORA_CONCAT(ORA_CONCAT('进货凭证号码[', BJTS_LSF_XX_JHPZH_001), ']在电子信息中为虚开增值税专用发票！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_CKYWLX_GCSB_PTFP','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('申报的增值税普通发票[', T.JHPZH), ']开票日期['), DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']不符合申报条件，请检查确认！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_GJ_SBMX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND INSTR(T.CKTMSYWLXDMJH,'GCSB')>0
            AND T.JHPZZL_DM='2'
            AND FUNC_XXBD_CHECK_GCSBKPRQ(T.KPRQ)=0;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_NSRZG','I',ORA_CONCAT(ORA_CONCAT('开票日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业非增值税一般纳税人，请确认是否符合退税政策！'),'Y',CURRENT_TIMESTAMP
           FROM CKTS_SB_GJ_SBMX_LSB T
           LEFT JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='YBNSRRD' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND INSTR(T.CKTMSYWLXDMJH,'GCSB')>0
            AND S.KZLX IS NULL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_TQQY','E',ORA_CONCAT(ORA_CONCAT('开票日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业处于出口退税停权期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TQQY' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_MSQY','E',ORA_CONCAT(ORA_CONCAT('开票日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业处于免税期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSGMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_FQTS','E',ORA_CONCAT(ORA_CONCAT('开票日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业处于放弃退（免）税权选择免税期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_FQTS','E',ORA_CONCAT(ORA_CONCAT('开票日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业处于放弃退（免）税权选择征税期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXZS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_FQTS','E',ORA_CONCAT(ORA_CONCAT('开票日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业处于放弃退（免）税权期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_BJGX_KZ_SDQ','E',ORA_CONCAT(ORA_CONCAT('出口业务类型为“水电气”，开票日期[', DATE_FORMAT(T.KPRQ, '%Y-%m-%d')), ']企业属于“海关特殊监管区域内的试点企业”！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSQYYBNSRSDQY' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND INSTR(T.CKTMSYWLXDMJH,'SDQ')>0;
    COMMIT;
  END;

  BEGIN
    CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'SDQ',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
    IF LN_CPCODEKZ=0 THEN
      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                  'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,NULL,NULL,'GJZY_BJGX_ZG_SDQ','E','出口业务类型为“水电气”，企业备案出口退（免）税管理类型未勾选“特殊区域内申报水电气退税业务的生产企业”！','N',CURRENT_TIMESTAMP

            WHERE EXISTS (SELECT 1
                            FROM CKTS_SB_GJ_SBMX_LSB T
                           WHERE T.SBID=V_IN_SBID
                             AND INSTR(T.CKTMSYWLXDMJH,'SDQ')>0);
      COMMIT;
    END IF;

    CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'NZYFJG',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
    CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'WZYFJG',LDT_TODAY,LC_KZXX, LN_CPCODEKZ1);
    IF LN_CPCODEKZ=0 AND LN_CPCODEKZ1=0 THEN
      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                  'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,NULL,NULL,'GJZY_BJGX_ZG_GCSB','E','出口业务类型为“国产设备”，企业备案出口退（免）税管理类型未勾选“内资研发机构”或“外资研发中心”！','N',CURRENT_TIMESTAMP

            WHERE EXISTS (SELECT 1
                            FROM CKTS_SB_GJ_SBMX_LSB T
                           WHERE T.SBID=V_IN_SBID
                             AND INSTR(T.CKTMSYWLXDMJH,'GCSB')>0);
      COMMIT;
    END IF;
  END;
END$$

DELIMITER ;
