DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_WZF_TSSB$$

CREATE PROCEDURE PROC_XXBD_WZF_TSSB
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外综服代办退税）
  调整日期：20220323，1、根据总局货劳司关于加强启运港出口退（免）税统计分析功能的业务要求，增加WZF_DBTS_CKYWLX_QYGTS疑点
  修改日期：20220615，根据2022年9号公告，合并收汇与不能收汇
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LDT_TODAY       DATETIME;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';
  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  -- 代办退税明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_DB_TSSB_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  SET LC_YDOBJECT ='代办退税';
  BEGIN
    CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD, LN_CPCODEKZ);
    CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TGSHZL',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
    IF (LC_FLGLCD='D') OR (LN_CPCODEKZ>0) THEN
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                    'CKTS_SB_DB_TSSB_LSB','CKTS_SB_DB_CKHWSH_LSB',NULL,T.SBXH,NULL,'WZF_BJGX_DBTS_SHZL_CKPZ','E',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', T.CKBGDH), ']未申报收汇资料！'),'N',CURRENT_TIMESTAMP
               FROM CKTS_SB_DB_TSSB_LSB T
              WHERE T.SBID=V_IN_SBID
                AND FUNC_XXBD_CHECK_NEEDSH(ORA_CONCAT(ORA_CONCAT(',', T.CKTMSYWLXDMJH), ',')) = 1
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_DB_CKHWSH_LSB S WHERE S.SBID=T.SBID AND S.CKBGDH=T.CKBGDH);
        COMMIT;
      END;
    ELSE
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                    'CKTS_SB_DB_TSSB_LSB','CKTS_SB_DB_CKHWSH_LSB',NULL,T.SBXH,NULL,'WZF_BJGX_DBTS_SHZL_CKPZ','E',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', T.CKBGDH), ']未申报收汇资料！'),'N',CURRENT_TIMESTAMP
               FROM CKTS_SB_DB_TSSB_LSB T
              WHERE T.SBID=V_IN_SBID
                AND (((STR_TO_DATE(ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y'), '0419'), '%Y%m%d')<CURRENT_TIMESTAMP) AND (CKRQ_1<MAKEDATE(YEAR(CURRENT_TIMESTAMP), 1))) OR (CKRQ_1<DATE_ADD(MAKEDATE(YEAR(CURRENT_TIMESTAMP), 1), INTERVAL -12 MONTH)))
                AND FUNC_XXBD_CHECK_NEEDSH(ORA_CONCAT(ORA_CONCAT(',', T.CKTMSYWLXDMJH), ',')) = 1
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_DB_CKHWSH_LSB S WHERE S.SBID=T.SBID AND S.CKBGDH=T.CKBGDH);
        COMMIT;
      END;
    END IF;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_CKRQ_NSRZG','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.CKRQ_1, '%Y-%m-%d')), ']企业非增值税一般纳税人！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
           LEFT JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='YBNSRRD' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND S.KZLX IS NULL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_CKRQ_TQQY','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.CKRQ_1, '%Y-%m-%d')), ']企业处于出口退税停权期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TQQY' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_CKRQ_TQDB','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.CKRQ_1, '%Y-%m-%d')), ']属于综服企业被依职权停权期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TZCSDBTS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_CKRQ_MSQY','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.CKRQ_1, '%Y-%m-%d')), ']企业处于免税期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSGMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_CKRQ_FQTS','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.CKRQ_1, '%Y-%m-%d')), ']企业处于放弃退（免）税权选择免税期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_CKRQ_FQTS','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.CKRQ_1, '%Y-%m-%d')), ']企业处于放弃退（免）税权选择征税期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXZS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_CKRQ_FQTS','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(T.CKRQ_1, '%Y-%m-%d')), ']企业处于放弃退（免）税权期间！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_CKYWLX_QYGTS','E',ORA_CONCAT(ORA_CONCAT('出口货物报关单号[', T.CKBGDH), ']为启运港业务，需确认国内启运方式及海关总署认证企业类型！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND INSTR(T.CKTMSYWLXDMJH,'QYGTS')>0
            AND (T.GNQYFS_DM IS NULL OR T.HGZSRZQYLX_DM IS NULL);
    COMMIT;
  END;
END$$

DELIMITER ;
