DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_WZF_TSSB_ZZSFP$$

CREATE PROCEDURE PROC_XXBD_WZF_TSSB_ZZSFP
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外综服代办退税）
  调整日期：20201106，对金额增加null判断
  调整日期：20201112，CKTS_WBSJ_ZJ_SCWTDBBA表中一般纳税人认定日期不准确，取消出口日期生产企业非一般纳税人校验
  调整日期：20201119，对疑点MTS_JHMX_ZZSFP_SBJE的描述进行调整，细化企业发票开票数、已申报数据提示
  调整日期：20201230，1、校验发票稽核信息时，剔除代开发票的稽核信息，代开发票开票人税号含DK
  修改日期：20210830，WZF_DBTS_WTFSH_YHZH疑点拆分为两个，名称不一致的（有可能全称与简称的区别）可挑过，账号不一致的不可跳过
  调整日期：20220701，1、根据全电票规则调整发票的关联，用JHPZH代替FPDM+FPHM
  调整日期：20220808，1、根据外综服代办退税备案取消的政策，调整原先与外综服代办退税备案结果表比对的口径，
                      改为与外综服企业备案信息、生产企业委托代办退税备案外部数据比对
  调整日期：20220830，1、取消综服企业银行名称的校验，只保留银行账号的校验
  调整日期：20230207，1、修改全电发票关联虚开发票时的BUG。
  调整日期：20230315，调整出口企业首次申报日期取数口径，改为按税务机关+企业+业务代码查询首次发放日期
  调整日期：20230515，解决增值税发票外部数据部分数据稽核相符标志为空的问题（赋默认值N）
  调整日期：20230518，解决按税务机关+企业+业务代码查询首次发放日期有结果但日期为空的问题（赋默认值SYSDATE）
  调整日期：20230814，针对异常扣税凭证做了追回处理后解除异常重新申报退税的总量控制bug，拆分WZF_DBTS_ZZSFP_SBJE疑点
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LDT_TODAY       DATETIME;
  DECLARE LDT_SCSBRQ      DATETIME;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';
  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  -- 代办退税发票记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_DB_TSSB_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  -- 查询企业首次申报日期
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET LDT_SCSBRQ =LDT_TODAY;

  END;
SELECT IFNULL(T.FFRQ, CURRENT_TIMESTAMP)
      INTO LDT_SCSBRQ
      FROM CKTS_TY_YWBLXX_SCFFRQ T
     WHERE T.TSSWJG_DM_1=(SELECT SWJG_DM FROM GS_DJ_CKTMSDAB WHERE NSRDZDAH=V_IN_NSRDZDAH)
       AND T.DJXH=V_IN_DJXH AND T.LCSWSX_DM='LCSXA081040001';
  END;

  SET LC_YDOBJECT ='代办发票';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'WZF_DBTS_ZZSFP_WDZXX','E',ORA_CONCAT(ORA_CONCAT('代办退税发票[', T.DBTSWSPZHM), ']无电子信息！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_DB_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_FP_ZZSZYFPXX S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.JHPZH=T.DBTSWSPZHM);
    COMMIT;
  END;

  BEGIN
    CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD, LN_CPCODEKZ);
    BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_DBTSWSPZHM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKTMSYWLXDMJH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_JHXFZZSZYFPBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_BYTSBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_WTDBTSSCQYNSRSBH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_XFNSRSBH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_KPRQ_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_KPRQ_SH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_FPYT_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_FPSJBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_NXZCKBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_GHFNSRSBH_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT A.SBXH,
                          A.DBTSWSPZHM,
                          IFNULL(A.CKTMSYWLXDMJH, ' ') AS CKTMSYWLXDMJH,
                          IFNULL(B.JHXFZZSZYFPBZ, 'N') AS JHXFZZSZYFPBZ,
                          B.BYTSBZ,
                          A.WTDBTSSCQYNSRSBH,
                          B.XFNSRSBH,
                          DATE(A.KPRQ) AS KPRQ_SB,
                          DATE(B.KPRQ) AS KPRQ_SH,
                          B.FPYT_DM,
                          IFNULL(B.FPSJBBZ, 'N') AS FPSJBZ,
                          IFNULL(B.NXZCKBZ, 'N') AS NXZCKBZ,
                          C.GHFNSRSBH
                     FROM CKTS_SB_DB_TSSB_LSB A
                    INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX B ON B.DJXH=V_IN_DJXH AND B.JHPZH=A.DBTSWSPZHM
                     LEFT JOIN CKTS_WBSJ_ZJ_XKFP C ON ORA_CONCAT(C.FP_DM, C.FPHM)=A.DBTSWSPZHM
                    WHERE A.SBID=V_IN_SBID;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_LSF_XX_SBXH_002, BJTS_LSF_XX_DBTSWSPZHM_002, BJTS_LSF_XX_CKTMSYWLXDMJH_002, BJTS_LSF_XX_JHXFZZSZYFPBZ_002, BJTS_LSF_XX_BYTSBZ_002, BJTS_LSF_XX_WTDBTSSCQYNSRSBH_002, BJTS_LSF_XX_XFNSRSBH_002, BJTS_LSF_XX_KPRQ_SB_002, BJTS_LSF_XX_KPRQ_SH_002, BJTS_LSF_XX_FPYT_DM_002, BJTS_LSF_XX_FPSJBZ_002, BJTS_LSF_XX_NXZCKBZ_002, BJTS_LSF_XX_GHFNSRSBH_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
      BEGIN
        IF (BJTS_LSF_XX_JHXFZZSZYFPBZ_002='N' AND INSTR(BJTS_LSF_XX_XFNSRSBH_002,'DK')=0 AND (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'RZZL')>0 OR LC_FLGLCD='D' OR (LC_FLGLCD='C' AND TIMESTAMPDIFF(MONTH, LDT_SCSBRQ, LDT_TODAY)<=12))) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'WZF_DBTS_ZZSFP_WDZXX','E',ORA_CONCAT(ORA_CONCAT('代办退税发票[', BJTS_LSF_XX_DBTSWSPZHM_002), ']无稽核相符电子信息！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_BYTSBZ_002='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'WZF_DBTS_ZZSFP_BYTS','E',ORA_CONCAT(ORA_CONCAT('代办退税发票[', BJTS_LSF_XX_DBTSWSPZHM_002), ']已被标注为“不予退税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_WTDBTSSCQYNSRSBH_002<>BJTS_LSF_XX_XFNSRSBH_002 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'WZF_DBTS_ZZSFP_GHFNSR','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代办退税发票[', BJTS_LSF_XX_DBTSWSPZHM_002), ']供货方纳税人['), BJTS_LSF_XX_WTDBTSSCQYNSRSBH_002), ']与电子信息中['), BJTS_LSF_XX_XFNSRSBH_002), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_KPRQ_SB_002<>BJTS_LSF_XX_KPRQ_SH_002 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'WZF_DBTS_ZZSFP_KPRQ','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代办退税发票[', BJTS_LSF_XX_DBTSWSPZHM_002), ']开票日期['), DATE_FORMAT(BJTS_LSF_XX_KPRQ_SB_002, '%Y-%m-%d')), ']与电子信息中['), DATE_FORMAT(BJTS_LSF_XX_KPRQ_SH_002, '%Y-%m-%d')), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_FPYT_DM_002<>'3' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'WZF_DBTS_ZZSFP_DBTS','E',ORA_CONCAT(ORA_CONCAT('代办退税发票[', BJTS_LSF_XX_DBTSWSPZHM_002), ']在电子信息中申报用途代码不是“3-代办退税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (BJTS_LSF_XX_FPYT_DM_002='1' AND BJTS_LSF_XX_FPSJBZ_002='Y' AND BJTS_LSF_XX_NXZCKBZ_002='N') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'WZF_DBTS_ZZSFP_YDK','E',ORA_CONCAT(ORA_CONCAT('代办退税发票[', BJTS_LSF_XX_DBTSWSPZHM_002), ']在电子信息中已勾选用于抵扣！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_GHFNSRSBH_002 IS NOT NULL THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'WZF_DBTS_ZZSFP_XKFP','E',ORA_CONCAT(ORA_CONCAT('代办退税发票[', BJTS_LSF_XX_DBTSWSPZHM_002), ']在电子信息中为虚开增值税专用发票！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;
  END;

  BEGIN
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKRQ_1_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_NSRSBH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_BACHBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_BACHRQ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_NSRRDSJQ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_NSRRDSJZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_YBNSRZXGMNSRSJQ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_YBNSRZXGMNSRSJZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TZCKTMSQBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TZCKTMSQQSRQ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TZCKTMSQJZRQ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSGMSBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSGMSQSRQ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSGMSJZRQ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_FQCKTMSQBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_FQCKTMSQQSRQ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_FQCKTMSQJZRQ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSKHYHMC_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSKHYHZH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_YHMC_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_YHZH_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT DISTINCT
                          A.SBXH,
                          A.WTDBTSSCQYNSRSBH,
                          A.CKRQ_1,
                          C.NSRSBH,
                          C.BACHBZ,
                          C.BACHRQ,
                          C.NSRRDSJQ,
                          C.NSRRDSJZ,
                          C.YBNSRZXGMNSRSJQ,
                          C.YBNSRZXGMNSRSJZ,
                          C.TZCKTMSQBZ,
                          C.TZCKTMSQQSRQ,
                          C.TZCKTMSQJZRQ,
                          C.TSGMSBZ,
                          C.TSGMSQSRQ,
                          C.TSGMSJZRQ,
                          C.FQCKTMSQBZ,
                          C.FQCKTMSQQSRQ,
                          C.FQCKTMSQJZRQ,
                          IFNULL(C.TSKHYHMC, '1') AS TSKHYHMC,
                          IFNULL(C.TSKHYHZH, '1') AS TSKHYHZH,
                          B.YHMC,
                          B.YHZH
                     FROM CKTS_SB_DB_TSSB_LSB A
                    INNER JOIN GS_DJ_CKTMSDAB B ON B.NSRDZDAH=V_IN_NSRDZDAH
                     LEFT JOIN CKTS_WBSJ_ZJ_SCWTDBBA C ON C.DJXH=V_IN_DJXH AND (C.NSRSBH=A.WTDBTSSCQYNSRSBH OR C.SHXYDM=A.WTDBTSSCQYNSRSBH)
                    WHERE A.SBID=V_IN_SBID;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_SBXH_001, BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001, BJTS_LSF_XX_CKRQ_1_001, BJTS_LSF_XX_NSRSBH_001, BJTS_LSF_XX_BACHBZ_001, BJTS_LSF_XX_BACHRQ_001, BJTS_LSF_XX_NSRRDSJQ_001, BJTS_LSF_XX_NSRRDSJZ_001, BJTS_LSF_XX_YBNSRZXGMNSRSJQ_001, BJTS_LSF_XX_YBNSRZXGMNSRSJZ_001, BJTS_LSF_XX_TZCKTMSQBZ_001, BJTS_LSF_XX_TZCKTMSQQSRQ_001, BJTS_LSF_XX_TZCKTMSQJZRQ_001, BJTS_LSF_XX_TSGMSBZ_001, BJTS_LSF_XX_TSGMSQSRQ_001, BJTS_LSF_XX_TSGMSJZRQ_001, BJTS_LSF_XX_FQCKTMSQBZ_001, BJTS_LSF_XX_FQCKTMSQQSRQ_001, BJTS_LSF_XX_FQCKTMSQJZRQ_001, BJTS_LSF_XX_TSKHYHMC_001, BJTS_LSF_XX_TSKHYHZH_001, BJTS_LSF_XX_YHMC_001, BJTS_LSF_XX_YHZH_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      BEGIN
        IF (BJTS_LSF_XX_NSRSBH_001 IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_WTFSH_DBBA','E',ORA_CONCAT(ORA_CONCAT('“未收到该委托代办退税生产企业”[', BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001), ']的委托代办退税备案信息！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (BJTS_LSF_XX_BACHBZ_001='Y' AND BJTS_LSF_XX_CKRQ_1_001>BJTS_LSF_XX_BACHRQ_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_WTFSH_TMSBA','E',ORA_CONCAT(ORA_CONCAT('“委托代办退税的生产企业”[', BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001), ']已经办理备案撤回！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (BJTS_LSF_XX_TSKHYHZH_001<>BJTS_LSF_XX_YHZH_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_WTFSH_YHZH','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('“综服企业备案银行账号”[', BJTS_LSF_XX_YHZH_001), ']与委托代办退税备案信息中的账号”['), BJTS_LSF_XX_TSKHYHZH_001), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
/*        ELSIF (LSF_XX.TSKHYHMC<>LSF_XX.YHMC) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_WTFSH_YHZH','E','“综服企业备案银行名称”[' || LSF_XX.YHMC || ']与委托代办退税备案信息中的名称”[' || LSF_XX.TSKHYHMC || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;*/
        END IF;

        IF (BJTS_LSF_XX_TZCKTMSQBZ_001 IN ('Y','1') AND BJTS_LSF_XX_CKRQ_1_001>BJTS_LSF_XX_TZCKTMSQQSRQ_001 AND BJTS_LSF_XX_CKRQ_1_001<BJTS_LSF_XX_TZCKTMSQJZRQ_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_CKRQ_TQQY_SC','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(BJTS_LSF_XX_CKRQ_1_001, '%Y-%m-%d')), ']委托代办退税的生产企业处于出口退税停权期间！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_TSGMSBZ_001 IN ('Y','1') AND BJTS_LSF_XX_CKRQ_1_001>BJTS_LSF_XX_TSGMSQSRQ_001 AND BJTS_LSF_XX_CKRQ_1_001<BJTS_LSF_XX_TSGMSJZRQ_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_CKRQ_MSQY_SC','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(BJTS_LSF_XX_CKRQ_1_001, '%Y-%m-%d')), ']委托代办退税的生产企业处于免税期间！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_FQCKTMSQBZ_001 IN ('Y','1') AND BJTS_LSF_XX_CKRQ_1_001>BJTS_LSF_XX_FQCKTMSQQSRQ_001 AND BJTS_LSF_XX_CKRQ_1_001<BJTS_LSF_XX_FQCKTMSQJZRQ_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_DB_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'WZF_DBTS_CKRQ_FQTS_SC','E',ORA_CONCAT(ORA_CONCAT('出口日期[', DATE_FORMAT(BJTS_LSF_XX_CKRQ_1_001, '%Y-%m-%d')), ']委托代办退税的生产企业处于放弃退（免）税权期间！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,NULL,T.DBTSWSPZHM,'WZF_DBTS_ZZSFP_SBJE','E',
                ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('增值税专用发票[', T.DBTSWSPZHM), ']申报退税的计税金额['), T.JSJE), ']超过电子信息中开票金额['), S.JE), ']）！'),'N',CURRENT_TIMESTAMP
           FROM (SELECT A.DBTSWSPZHM, SUM(A.JSJE) AS JSJE
                   FROM CKTS_SB_DB_TSSB_LSB A
                  WHERE A.SBID=V_IN_SBID
                  GROUP BY A.DBTSWSPZHM) T
          INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX S ON S.DJXH=V_IN_DJXH AND S.JHPZH=T.DBTSWSPZHM
          WHERE T.JSJE > S.JE + 0.1;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_DB_TSSB_LSB',NULL,NULL,NULL,T.DBTSWSPZHM,'WZF_DBTS_ZZSFP_SBJE','W',
                ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('增值税专用发票[', T.DBTSWSPZHM), ']申报退税的计税金额['), T.JSJE), ']超过电子信息中剩余数['), GREATEST(0,S.JE - IFNULL(S.HZCJJE, 0) - IFNULL(S.SBFPJSJE, 0) - IFNULL(S.LSLSBFPJSJE, 0))), ']（其中开票['), S.JE), ']红字冲减['), IFNULL(S.HZCJJE, 0)), ']出口货物劳务已申报['), IFNULL(S.SBFPJSJE, 0)), ']外购应税服务已申报['), IFNULL(S.LSLSBFPJSJE, 0)), ']）！'),'Y',CURRENT_TIMESTAMP
           FROM (SELECT A.DBTSWSPZHM, SUM(A.JSJE) AS JSJE
                   FROM CKTS_SB_DB_TSSB_LSB A
                  WHERE A.SBID=V_IN_SBID
                  GROUP BY A.DBTSWSPZHM) T
          INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX S ON S.DJXH=V_IN_DJXH AND S.JHPZH=T.DBTSWSPZHM
          WHERE T.JSJE <= S.JE + 0.1
            AND T.JSJE > S.JE - IFNULL(S.HZCJJE, 0) - IFNULL(S.SBFPJSJE, 0) - IFNULL(S.LSLSBFPJSJE, 0) + 0.1;
    COMMIT;
  END;
END$$

DELIMITER ;
