DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MTS_TSJH_JKXFS$$

CREATE PROCEDURE PROC_XXBD_MTS_TSJH_JKXFS
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  调整日期：20210603，1、调整疑点关联业务字段，关联号+申报序号
  调整日期：20211019，1、增加MTS_JHMX_JKXFS_GHFNSR疑点判断，海关进口税收凭证填写缴款单位纳税人识别号
  调整日期：20211208，1、调整免退税疑点描述字段中申报序号与关联单证号的顺序，使其与客户端疑点展示一致
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LDT_TODAY       DATETIME;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';
  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  --进口消费税缴款书记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_TSJH_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.CKTMSPZLX_DM='05';
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  SET LC_YDOBJECT ='进口消费税';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_JHMX_JKXFS_WDZXX','E','海关进口消费税缴款书[' || T.JHPZH || ']无电子信息！','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MTS_TSJH_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.CKTMSPZLX_DM='05'
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_HG_JKJKS S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.HGZYJKSHM=T.JHPZH);
    COMMIT;
  END;

  BEGIN
    FOR LSF_XX IN (SELECT A.SBXH,A.GLH,
                          A.JHPZH,
                          A.GHFNSRSBH_1,
                          B.BYTSBZ,
                          B.HGJKJKSCLJG_DM,
                          B.NSRSBH
                     FROM CKTS_SB_MTS_TSJH_LSB A
                    INNER JOIN CKTS_WBSJ_HG_JKJKS B ON B.DJXH=V_IN_DJXH AND B.HGZYJKSHM=A.JHPZH
                    WHERE A.SBID=V_IN_SBID
                      AND A.CKTMSPZLX_DM='05') LOOP
      BEGIN
        IF LSF_XX.BYTSBZ='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_JKXFS_BYTS','E','海关进口消费税缴款书[' || LSF_XX.JHPZH || ']已被标注为“不予退税”！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF LSF_XX.HGJKJKSCLJG_DM IN ('100','500') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_JKXFS_DUP','E','海关进口消费税缴款书[' || LSF_XX.JHPZH || ']在电子信息中重复申请退税！','N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        
        IF LSF_XX.GHFNSRSBH_1<>LSF_XX.NSRSBH THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_JKXFS_GHFNSR','E','海关进口消费税缴款书[' || LSF_XX.JHPZH || ']供货方纳税人[' || LSF_XX.GHFNSRSBH_1 || ']与电子信息中[' || LSF_XX.NSRSBH || ']不一致！','Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;
END$$

DELIMITER ;
