DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_TSZM_WTCKHWZM$$

CREATE PROCEDURE PROC_XXBD_TSZM_WTCKHWZM
/*
  编制人:严国平
  编制日期:202101
  功能:信息比对（委托出口货物证明）
  说明：其中TSZM_WTCK_SPDM_RANK提示性疑点电子税务局已实现，主要为了兼容离线版申报自检；
            TSZM_WTCK_DFDWSH_VALID疑点原来通过java代码实现，修改维护比较麻烦，改为存储过程实现。
  调整日期：20210715，1、调整疑点TSZM_WTCK_DFDWSH_VALID判断逻辑，先判断本地企业再判断全国备案信息
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LDT_TODAY    DATETIME;

  DECLARE LC_QYHGDM       VARCHAR(20);
  DECLARE LC_QYLXDM       VARCHAR(20);
  DECLARE LC_TSJSFSDM     VARCHAR(20);
  DECLARE LC_WMZHFWQYBZ   VARCHAR(20);
  DECLARE LC_SFYSFW       VARCHAR(20);
  DECLARE LC_YSFW         VARCHAR(50);
  DECLARE LC_YSFS         VARCHAR(50);
  DECLARE LC_YFSJ         VARCHAR(50);
  DECLARE LC_ZXFLAG       VARCHAR(20);

  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LN_ROWNUM_TSSB  BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  IF V_IN_SSSQ>DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m') THEN
    BEGIN
      SET V_OUT_STATUS ='05';
      SET V_OUT_MESSAGE ='申报所属时期超出合理范围！';
      LEAVE routine_body;
    END;
  END IF;

  -- 取各申报明细表数据记录
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='06';
      SET V_OUT_MESSAGE ='查询申报记录数据失败！';
      LEAVE routine_body;

  END;
SELECT COUNT(1)
      INTO LN_ROWNUM_TSSB
      FROM CKTS_ZM_WTCK_LSB
     WHERE SBID=V_IN_SBID;
  END;
  IF LN_ROWNUM_TSSB=0 THEN
    BEGIN
      SET V_OUT_STATUS ='07';
      SET V_OUT_MESSAGE ='申报数据为空！';
      LEAVE routine_body;
    END;
  END IF;

  -- 查询企业基本信息
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='08';
      SET V_OUT_MESSAGE ='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;

  END;
SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  END;
  IF LC_ZXFLAG='R' THEN
    BEGIN
      SET V_OUT_STATUS ='09';
      SET V_OUT_MESSAGE ='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;
    END;
  END IF;

  -- 取企业的FLGLCD信息, TGSHZL信息，判断是否需要申报收汇
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD, LN_CPCODEKZ);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      SET V_OUT_STATUS ='10';
      SET V_OUT_MESSAGE ='查询出口企业分类管理类型出错！';
      LEAVE routine_body;
    END;
  END IF;


  SET LC_YDOBJECT ='委托出口';
  BEGIN
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKBGDH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_STFNSRSBH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_STQY_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSP_DM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSP_DM_QSTS_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT DISTINCT A.SBXH,
                          A.CKBGDH,
                          A.STFNSRSBH,
                          IFNULL(E.NSRSBH, B.UUID) AS STQY,
                          A.CKSP_DM,
                          IFNULL(C.CKSP_DM, D.CKSP_DM) AS CKSP_DM_QSTS
                     FROM CKTS_ZM_WTCK_LSB A
                     LEFT JOIN CKTS_WBSJ_ZJ_CKTSBAQGXX B ON B.NSRSBH=A.STFNSRSBH OR B.SHXYDM=A.STFNSRSBH
                     LEFT JOIN CKTS_DM_TSLVWK C ON C.CKSP_DM=A.CKSP_DM AND (CURRENT_TIMESTAMP BETWEEN C.YXQQ AND C.YXQZ) AND C.ZSSL>0 AND C.TSL=0 AND C.CKSPTSSPLX_DM='1'
                     LEFT JOIN CKTS_DM_TSLVWK D ON D.CKSP_DM=SUBSTR(A.CKSP_DM,1,8) AND (CURRENT_TIMESTAMP BETWEEN D.YXQQ AND D.YXQZ) AND D.ZSSL>0 AND D.TSL=0 AND D.CKSPTSSPLX_DM='1'
                     LEFT JOIN GS_DJ_CKTMSDAB E ON E.NSRDJNO=A.STFNSRSBH OR E.SHXYNO=A.STFNSRSBH
                    WHERE A.SBID=V_IN_SBID;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_SBXH_001, BJTS_LSF_XX_CKBGDH_001, BJTS_LSF_XX_STFNSRSBH_001, BJTS_LSF_XX_STQY_001, BJTS_LSF_XX_CKSP_DM_001, BJTS_LSF_XX_CKSP_DM_QSTS_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      BEGIN
        IF (BJTS_LSF_XX_STQY_001 IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_WTCK_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'TSZM_WTCK_DFDWSH_VALID','E',ORA_CONCAT(ORA_CONCAT('未查询到受托企业[', BJTS_LSF_XX_STFNSRSBH_001), ']的出口退（免）税备案信息，请核实受托企业纳税人社会信用码（识别号）是否准确！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_CKSP_DM_QSTS_001 IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_ZM_WTCK_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'TSZM_WTCK_SPDM_RANK','I',ORA_CONCAT(ORA_CONCAT('出口商品代码[', BJTS_LSF_XX_CKSP_DM_001), ']不是取消退税商品，请确认是否需要申请委托出口货物证明！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
  END;
END$$

DELIMITER ;
