DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MDT_TSSB_DLZM$$

CREATE PROCEDURE PROC_XXBD_MDT_TSSB_DLZM
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
  调整日期：20201106，1、对HZCJ不判断剩余数量和美元离岸价，2、对金额增加null判断，3、监管方式1200列入进料加工
  调整日期：20211111，与报关单疑点一致，1、调整MDT_CKHW_BGD_WDZXX监控条件，对红字冲减业务不判断；
                                        2、增加MDT_CKHW_DLZM_USDLAJ_CY、MDT_CKHW_DLZM_HZCJ_BYZ
                                        3、增加MDT_CKHW_DLCK_CKSL、MDT_CKHW_DLZM_USDLAJ
  调整日期：20211213，对疑点MDT_CKHW_DLZM_BYTS的校验逻辑进行修正，仅针对非红字冲减或红字冲减退运的业务进行判断
  调整日期：20211214，对疑点MDT_JLJG_SCH_NOJLJG的校验逻辑进行修正，同时判断企业是否填了加工贸易手册号或计划分配率
  调整日期：20230313，增加MDT_CKHW_DLZM_BSQ_BAQD、MDT_CKHW_DLZM_BSQ_BANR、MDT_CKHW_DLZM_RMBLAJ、MDT_CKHW_DLZM_HZCJ_TY疑点判断
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CMCD_LEN     BIGINT;
  DECLARE LN_ZHJHFPL      DECIMAL(16,6);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';


  -- 代理证明出口货物劳务明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_TSSB_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.DLCKHWZMHM IS NOT NULL;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;
  SET LC_YDOBJECT ='代理证明';

  -- 获取进料加工企业最新调整计划分配律
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET LN_ZHJHFPL =0;

  END;
SELECT ZHJHFPL
      INTO LN_ZHJHFPL
      FROM (SELECT CASE WHEN T.JHFPLV_NEW=0 THEN T.JHFPLV ELSE T.JHFPLV_NEW END AS ZHJHFPL
              FROM GS_JLJG_JHFPL T
             WHERE T.NSRDZDAH=V_IN_NSRDZDAH
             ORDER BY T.UPTIME DESC)
     WHERE 1=1
LIMIT 1;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'MDT_CKHW_DLZM_WDZXX','E',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', T.DLCKHWZMHM), ']无电子信息！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.DLCKHWZMHM IS NOT NULL
            AND FUNC_XXBD_CHECK_YWLX(ORA_CONCAT(ORA_CONCAT(',', T.CKTMSYWLXDMJH), ',')) = 0
            AND INSTR(IFNULL(T.CKTMSYWLXDMJH, ' '),'HZCJ')=0
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_ZJ_DLCKHWZM S WHERE S.DJXH=V_IN_DJXH AND S.DLCKHWZMHM=T.DLCKHWZMHM);
    COMMIT;
  END;

  BEGIN
    BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_DLCKHWZMHM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_BYTSBZ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKRQ_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKRQ_SH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKTMSYWLXDMJH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSP_DM_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSP_DM_SH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_JGFS_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_JGFSTSLX_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_ZZMDGDQSZ_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_YSFS_DM_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSL_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_MYLAJ_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_RMBLAJ_SB_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_MYLAJ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKFPMYLAJ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSSBSL_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSSBMYLAJ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSSBRMBLAJ_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_JLJGSZCH_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_TZHJHFPL_002 LONGTEXT;
  DECLARE BJTS_LSF_XX_SJFPL_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT A.SBXH,
                          A.DLCKHWZMHM,
                          B.BYTSBZ,
                          DATE(A.CKRQ_1) AS CKRQ_SB,
                          DATE(B.CKRQ_1) AS CKRQ_SH,
                          IFNULL(A.CKTMSYWLXDMJH, ' ') AS CKTMSYWLXDMJH,
                          A.CKSP_DM AS CKSP_DM_SB,
                          B.CKSP_DM AS CKSP_DM_SH,
                          C.JGFS_DM,
                          C.JGFSTSLX_DM,
                          B.ZZMDGDQSZ_DM,
                          B.YSFS_DM,
                          A.CKSL AS CKSL_SB,
                          A.MYLAJ AS MYLAJ_SB,
                          A.RMBLAJ AS RMBLAJ_SB,
                          B.MYLAJ,
                          F.CKFPMYLAJ,
                          IFNULL(B.TSSBSL, 0) AS TSSBSL,
                          IFNULL(B.TSSBMYLAJ, 0) AS TSSBMYLAJ,
                          IFNULL(B.TSSBRMBLAJ, 0) AS TSSBRMBLAJ,
                          A.JLJGSZCH,
                          A.TZHJHFPL,
                          G.SJFPL
                     FROM CKTS_SB_MDT_TSSB_LSB A
                    INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM B ON B.DJXH=V_IN_DJXH AND B.DLCKHWZMHM=A.DLCKHWZMHM
                     LEFT JOIN CKTS_DM_HGJGFS C ON C.JGFS_DM=B.JGFS_DM
                     LEFT JOIN CKTS_SB_MDT_CYSM_LSB F ON F.SBID=V_IN_SBID AND F.DLCKHWZMHM=A.DLCKHWZMHM
                     LEFT JOIN (SELECT NSRDZDAH, JGMYSCH, HXQSRQ, HXJZRQ, SJFPL, ROW_NUMBER() OVER (PARTITION BY NSRDZDAH, JGMYSCH, HXQSRQ, HXJZRQ ORDER BY LRRQ DESC) AS RN
                                  FROM GS_JLJG_HXJG) G ON G.NSRDZDAH=V_IN_NSRDZDAH AND G.JGMYSCH=A.JLJGSZCH AND RN=1 AND (SUBSTR(A.JLJGSZCH,1,1)='C' OR (A.CKRQ_1 BETWEEN G.HXQSRQ AND G.HXJZRQ))
                    WHERE A.SBID=V_IN_SBID
                      AND A.DLCKHWZMHM IS NOT NULL
                      AND FUNC_XXBD_CHECK_YWLX(ORA_CONCAT(ORA_CONCAT(',', A.CKTMSYWLXDMJH), ',')) = 0;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_LSF_XX_SBXH_002, BJTS_LSF_XX_DLCKHWZMHM_002, BJTS_LSF_XX_BYTSBZ_002, BJTS_LSF_XX_CKRQ_SB_002, BJTS_LSF_XX_CKRQ_SH_002, BJTS_LSF_XX_CKTMSYWLXDMJH_002, BJTS_LSF_XX_CKSP_DM_SB_002, BJTS_LSF_XX_CKSP_DM_SH_002, BJTS_LSF_XX_JGFS_DM_002, BJTS_LSF_XX_JGFSTSLX_DM_002, BJTS_LSF_XX_ZZMDGDQSZ_DM_002, BJTS_LSF_XX_YSFS_DM_002, BJTS_LSF_XX_CKSL_SB_002, BJTS_LSF_XX_MYLAJ_SB_002, BJTS_LSF_XX_RMBLAJ_SB_002, BJTS_LSF_XX_MYLAJ_002, BJTS_LSF_XX_CKFPMYLAJ_002, BJTS_LSF_XX_TSSBSL_002, BJTS_LSF_XX_TSSBMYLAJ_002, BJTS_LSF_XX_TSSBRMBLAJ_002, BJTS_LSF_XX_JLJGSZCH_002, BJTS_LSF_XX_TZHJHFPL_002, BJTS_LSF_XX_SJFPL_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
      BEGIN
        SET LC_YDOBJECT ='代理证明';

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'HZCJ')>0) THEN
          IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'HZCJ-TY')=0) THEN
            -- 20211111, 增加红字冲减与原申报数的比较
            BEGIN
              IF (BJTS_LSF_XX_CKSL_SB_002 + BJTS_LSF_XX_TSSBSL_002 <>0) THEN
                INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                     SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                            'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_HZCJ_BYZ','E',
                            ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']业务类型选择红字冲减，出口数量与已申报出口数量['), BJTS_LSF_XX_TSSBSL_002), ']不一致！'),'N',CURRENT_TIMESTAMP
;
                COMMIT;
              END IF;
              IF (BJTS_LSF_XX_MYLAJ_SB_002 + BJTS_LSF_XX_TSSBMYLAJ_002 <>0) THEN
                INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                     SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                            'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_HZCJ_BYZ','E',
                            ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']业务类型选择红字冲减，美元离岸价与已申报美元离岸价['), BJTS_LSF_XX_TSSBMYLAJ_002), ']不一致！'),'N',CURRENT_TIMESTAMP
;
                COMMIT;
              END IF;
              IF (BJTS_LSF_XX_RMBLAJ_SB_002 + BJTS_LSF_XX_TSSBRMBLAJ_002 <>0) THEN
                INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                     SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                            'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_HZCJ_BYZ','E',
                            ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']业务类型选择红字冲减，人民币离岸价与已申报人民币离岸价['), BJTS_LSF_XX_TSSBRMBLAJ_002), ']不一致！'),'N',CURRENT_TIMESTAMP
;
                COMMIT;
              END IF;
            END;
          ELSE
            -- 20230314, 增加红字冲减-退运与原退运证明一致性的提示
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_HZCJ_TY','I',
                        ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']业务类型选择红字冲减-退运，请核实退运冲减的人民币离岸价与应冲减的退运证明对应的实际出口销售额是否一致！'),'Y',CURRENT_TIMESTAMP
;
            COMMIT;
          END IF;
        ELSE
          BEGIN
            -- 20211111，与MDT_CKHW_BGD_USDLAJ_CY一致
            IF (ABS(BJTS_LSF_XX_MYLAJ_SB_002-BJTS_LSF_XX_MYLAJ_002)>1) AND (ABS(BJTS_LSF_XX_MYLAJ_SB_002-BJTS_LSF_XX_MYLAJ_002)>0.05 * BJTS_LSF_XX_MYLAJ_002) AND (BJTS_LSF_XX_CKFPMYLAJ_002 IS NULL) THEN
                INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                     SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                            'CKTS_SB_MDT_TSSB_LSB','CKTS_SB_MDT_CYSM_LSB',NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_USDLAJ_CY','E',
                            ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']美元离岸价['), BJTS_LSF_XX_MYLAJ_SB_002), ']超过电子信息中['), BJTS_LSF_XX_MYLAJ_002), ']合理范围，需提供《出口货物离岸价差异原因说明表》！'),'N',CURRENT_TIMESTAMP
;
              COMMIT;
            END IF;
            -- 20211213，对红字冲减、红字冲减退运业务，不判断已经标注“不予退税”
            IF (BJTS_LSF_XX_BYTSBZ_002='Y') THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_BYTS','E',
                          ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']已被标注为“不予退税”！'),'N',CURRENT_TIMESTAMP
;
              COMMIT;
            END IF;
          END;
        END IF;

        IF (BJTS_LSF_XX_CKRQ_SB_002<>BJTS_LSF_XX_CKRQ_SH_002) AND (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'BSQ')=0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_CKRQ','E',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']出口日期['), DATE_FORMAT(BJTS_LSF_XX_CKRQ_SB_002, '%Y-%m-%d')), ']与电子信息中['), DATE_FORMAT(BJTS_LSF_XX_CKRQ_SH_002, '%Y-%m-%d')), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        SET LN_CMCD_LEN = CASE WHEN LENGTH(BJTS_LSF_XX_CKSP_DM_SB_002) > LENGTH(BJTS_LSF_XX_CKSP_DM_SH_002) THEN LENGTH(BJTS_LSF_XX_CKSP_DM_SH_002) ELSE LENGTH(BJTS_LSF_XX_CKSP_DM_SB_002) END;
        IF SUBSTR(BJTS_LSF_XX_CKSP_DM_SB_002,1,LN_CMCD_LEN)<>SUBSTR(BJTS_LSF_XX_CKSP_DM_SH_002,1,LN_CMCD_LEN) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_SPDM','E',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']商品代码['), BJTS_LSF_XX_CKSP_DM_SB_002), ']与电子信息中['), BJTS_LSF_XX_CKSP_DM_SH_002), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (TRIM(BJTS_LSF_XX_JGFS_DM_002) IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_MYXZ_BCZ','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']在电子信息中监管方式不存在！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF (TRIM(BJTS_LSF_XX_JGFSTSLX_DM_002)='0') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_MYXZ_BTS','E',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']在电子信息中监管方式['), BJTS_LSF_XX_JGFS_DM_002), ']不退税！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'DWCB')>0 AND BJTS_LSF_XX_JGFS_DM_002<>'3422' AND BJTS_LSF_XX_JGFS_DM_002<>'22') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_DWCB_NOT','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']非对外承包业务，“业务类型”不应包含“DWCB”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'DWCB')=0 AND (BJTS_LSF_XX_JGFS_DM_002='3422' OR BJTS_LSF_XX_JGFS_DM_002='22')) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_DWCB_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']为对外承包业务，“业务类型”应包含“DWCB”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'BSQ')>0) THEN
          IF (BJTS_LSF_XX_YSFS_DM_002<>'0') THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_BSQ_NOT','E',
                        ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']非经保税区出口业务，“业务类型”不应包含“BSQ”！'),'N',CURRENT_TIMESTAMP
;
            COMMIT;
          ELSE
            BEGIN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_BSQ_BAQD','I',
                          ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']业务类型包含保税区BSQ，请核实是否附送《出境货物备案清单》！'),'Y',CURRENT_TIMESTAMP
;
              COMMIT;
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_BSQ_BANR','I',
                          ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']业务类型包含保税区BSQ，请核实出境货物备案清单的内容是否与报关单相关内容相符,出口日期填报是否准确！'),'Y',CURRENT_TIMESTAMP
;
              COMMIT;
            END;
          END IF;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'BSQ')=0 AND BJTS_LSF_XX_YSFS_DM_002='0') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_BSQ_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']为经保税区出口业务，“业务类型”应包含“BSQ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'JWTZ')>0 AND BJTS_LSF_XX_JGFS_DM_002<>'2210') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_JWTZ_NOT','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']非境外投资业务，“业务类型”不应包含“JWTZ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'JWTZ')=0 AND BJTS_LSF_XX_JGFS_DM_002='2210') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_JWTZ_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']为境外投资业务，“业务类型”应包含“JWTZ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'DWYZ')>0 AND BJTS_LSF_XX_JGFS_DM_002<>'3511') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_DWYZ_NOT','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']非对外援助业务，“业务类型”不应包含“DWYZ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'DWYZ')=0 AND BJTS_LSF_XX_JGFS_DM_002='3511') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_DWYZ_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']为对外援助业务，“业务类型”应包含“DWYZ”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'XLXP')>0 AND BJTS_LSF_XX_JGFS_DM_002<>'1300') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_XLXP_NOT','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']非修理修配业务，“业务类型”不应包含“XLXP”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF (INSTR(BJTS_LSF_XX_CKTMSYWLXDMJH_002,'XLXP')=0 AND BJTS_LSF_XX_JGFS_DM_002='1300') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_XLXP_NULL','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']为修理修配业务，“业务类型”应包含“XLXP”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_YSFS_DM_002='8' AND BJTS_LSF_XX_ZZMDGDQSZ_DM_002='142' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_CKHW_DLZM_BSCKZNX','E',
                      ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']为保税仓库转内销！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        SET LC_YDOBJECT ='进料加工';
        IF BJTS_LSF_XX_JGFS_DM_002 IN ('0615','0715','1200') THEN
          BEGIN
            IF BJTS_LSF_XX_JLJGSZCH_002 IS NULL THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_JLJG_DLZM_NOSCH','E',
                          ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']在电子信息中监管方式为0615/0715，出口明细未申报进料加工手册号！'),'N',CURRENT_TIMESTAMP
;
              COMMIT;
            END IF;

            IF BJTS_LSF_XX_TZHJHFPL_002 IS NULL THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                          'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_JLJG_DLZM_NOFPLV','E',
                          ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']在电子信息中监管方式为0615/0715，出口明细未申报计划分配率！'),'N',CURRENT_TIMESTAMP
;
              COMMIT;
            ELSE
              BEGIN
                IF (BJTS_LSF_XX_SJFPL_002 IS NOT NULL) AND (BJTS_LSF_XX_TZHJHFPL_002<>BJTS_LSF_XX_SJFPL_002) THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                              'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_JLJG_SJFPLV_YHX','E',
                              '该手（账）册号已完成核销，请按照对应的实际分配率修改后后重新申报！','N',CURRENT_TIMESTAMP
;
                  COMMIT;
                END IF;
                IF (BJTS_LSF_XX_SJFPL_002 IS NULL) AND (BJTS_LSF_XX_TZHJHFPL_002<>LN_ZHJHFPL) THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                              'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_JLJG_SJFPLV_WHX','E',
                              '申报的进料加工计划分配率与当前有效的计划分配率不一致，请反馈计划分配率后重新申报！','N',CURRENT_TIMESTAMP
;
                  COMMIT;
                END IF;
              END;
            END IF;
          END;
        ELSE
          -- 20211214，针对企业导入的数据，有可能手册号为空但是存在分配率的，增加分配率的判断
          IF (BJTS_LSF_XX_JLJGSZCH_002 IS NOT NULL) OR (IFNULL(BJTS_LSF_XX_TZHJHFPL_002, 0)<>0) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_002,NULL,'MDT_JLJG_SCH_NOJLJG','I',
                        ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_002), ']申报了手册号（或计划分配率），电子信息中监管方式非0615/0715，请确认！'),'Y',CURRENT_TIMESTAMP
;
            COMMIT;
          END IF;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;
  END;

  BEGIN
    SET LC_YDOBJECT ='代理证明';
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_DLCKHWZMHM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_SBXH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSL_SB_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSL_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSSBSL_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TYSL_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_SYSL_SH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_MYLAJ_SB_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_MYLAJ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSSBMYLAJ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TYMYLAJ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_MYLAJ_SH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_RMBLAJ_SB_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_RMBLAJ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSSBRMBLAJ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TYRMBLAJ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_RMBLAJ_SH_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT A.DLCKHWZMHM,
                          A.SBXH,
                          A.CKSL_SB,
                          B.CKSL,
                          IFNULL(B.TSSBSL, 0) AS TSSBSL,
                          IFNULL(B.TYSL, 0) AS TYSL,
                          B.CKSL-IFNULL(B.TSSBSL, 0)-IFNULL(B.TYSL, 0) AS SYSL_SH,
                          A.MYLAJ_SB,
                          B.MYLAJ,
                          IFNULL(B.TSSBMYLAJ, 0) AS TSSBMYLAJ,
                          IFNULL(B.TYMYLAJ, 0) AS TYMYLAJ,
                          B.MYLAJ-IFNULL(B.TSSBMYLAJ, 0)-IFNULL(B.TYMYLAJ, 0) AS MYLAJ_SH,
                          A.RMBLAJ_SB,
                          B.RMBLAJ,
                          IFNULL(B.TSSBRMBLAJ, 0) AS TSSBRMBLAJ,
                          IFNULL(B.TYRMBLAJ, 0) AS TYRMBLAJ,
                          B.RMBLAJ-IFNULL(B.TSSBRMBLAJ, 0)-IFNULL(B.TYRMBLAJ, 0) AS RMBLAJ_SH
                     FROM (SELECT A.DLCKHWZMHM, MIN(A.SBXH) AS SBXH, SUM(A.CKSL) AS CKSL_SB, SUM(A.MYLAJ) AS MYLAJ_SB, SUM(A.RMBLAJ) AS RMBLAJ_SB
                             FROM CKTS_SB_MDT_TSSB_LSB A
                            WHERE A.SBID=V_IN_SBID
                              AND A.DLCKHWZMHM IS NOT NULL
                              AND FUNC_XXBD_CHECK_YWLX(ORA_CONCAT(ORA_CONCAT(',', A.CKTMSYWLXDMJH), ',')) = 0
                            GROUP BY A.DLCKHWZMHM) A
                    INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM B ON B.DJXH=V_IN_DJXH AND B.DLCKHWZMHM=A.DLCKHWZMHM;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_DLCKHWZMHM_001, BJTS_LSF_XX_SBXH_001, BJTS_LSF_XX_CKSL_SB_001, BJTS_LSF_XX_CKSL_001, BJTS_LSF_XX_TSSBSL_001, BJTS_LSF_XX_TYSL_001, BJTS_LSF_XX_SYSL_SH_001, BJTS_LSF_XX_MYLAJ_SB_001, BJTS_LSF_XX_MYLAJ_001, BJTS_LSF_XX_TSSBMYLAJ_001, BJTS_LSF_XX_TYMYLAJ_001, BJTS_LSF_XX_MYLAJ_SH_001, BJTS_LSF_XX_RMBLAJ_SB_001, BJTS_LSF_XX_RMBLAJ_001, BJTS_LSF_XX_TSSBRMBLAJ_001, BJTS_LSF_XX_TYRMBLAJ_001, BJTS_LSF_XX_RMBLAJ_SH_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      BEGIN
        IF (BJTS_LSF_XX_CKSL_SB_001 > 0) AND (BJTS_LSF_XX_CKSL_SB_001 - BJTS_LSF_XX_SYSL_SH_001 > 0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'MDT_CKHW_DLZM_CKSL','E',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']申报退税数量['), BJTS_LSF_XX_CKSL_SB_001), ']超过电子信息中剩余数量['), BJTS_LSF_XX_SYSL_SH_001), ']（其中出口['), BJTS_LSF_XX_CKSL_001), ']退税申报['), BJTS_LSF_XX_TSSBSL_001), ']退运['), BJTS_LSF_XX_TYSL_001), ']）！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_MYLAJ_SB_001>0) AND (BJTS_LSF_XX_MYLAJ_SB_001 - BJTS_LSF_XX_MYLAJ_SH_001 > 1) AND (BJTS_LSF_XX_MYLAJ_001 > BJTS_LSF_XX_MYLAJ_SH_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'MDT_CKHW_DLZM_USDLAJ','I',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']申报美元离岸价['), BJTS_LSF_XX_MYLAJ_SB_001), ']超过电子信息中剩余美元离岸价['), BJTS_LSF_XX_MYLAJ_SH_001), ']（其中出口['), BJTS_LSF_XX_MYLAJ_001), ']退税申报['), BJTS_LSF_XX_TSSBMYLAJ_001), ']退运['), BJTS_LSF_XX_TYMYLAJ_001), ']）！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_RMBLAJ_SB_001>0) AND (BJTS_LSF_XX_RMBLAJ_SB_001 - BJTS_LSF_XX_RMBLAJ_SH_001 > 1) AND (BJTS_LSF_XX_RMBLAJ_001 > BJTS_LSF_XX_RMBLAJ_SH_001) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MDT_TSSB_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'MDT_CKHW_DLZM_RMBLAJ','I',
                      ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']申报人民币离岸价['), BJTS_LSF_XX_RMBLAJ_SB_001), ']超过电子信息中剩余人民币离岸价['), BJTS_LSF_XX_RMBLAJ_SH_001), ']（其中出口['), BJTS_LSF_XX_RMBLAJ_001), ']退税申报['), BJTS_LSF_XX_TSSBRMBLAJ_001), ']退运['), BJTS_LSF_XX_TYRMBLAJ_001), ']）！'),'Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
  END;
END$$

DELIMITER ;
