DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MTS_CKSH$$

CREATE PROCEDURE PROC_XXBD_MTS_CKSH
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  修改日期：20220615，根据2022年9号公告，四类企业，需提供银行水单企业收汇情况表必须申报本期出口退税，非上述企业改为提示性疑点
  修改日期：20230207，修改代理证明出口申报收汇表的疑点逻辑和提示
  调整日期：20230313，增加MTS_BJGX_SHZL_CKMX_CJBZ、MTS_BJGX_SHZL_CKMX_CJJE的疑点判断
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LDT_TODAY       DATETIME;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';
  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  --收汇明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_CKSH_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  SET LC_YDOBJECT ='出口收汇';
  BEGIN
    SET LN_CPCODEKZ =FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
    SET LN_CPCODEKZ =FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TGSHZL',LDT_TODAY,LC_KZXX);
    IF (LC_FLGLCD='D') OR (LN_CPCODEKZ>0) THEN
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                    'CKTS_SB_MTS_CKSH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,T.SBXH,NULL,'MTS_BJGX_SHZL_CKMX_CKPZ','E',
                    '出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']未申报退税！','N',CURRENT_TIMESTAMP
               FROM CKTS_SB_MTS_CKSH_LSB T
              WHERE T.SBID=V_IN_SBID
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_TSSB_LSB S WHERE S.SBID=T.SBID AND IFNULL(S.DLZMH, S.CKBGDH) = IFNULL(T.DLCKHWZMHM, T.CKBGDH));
        COMMIT;
      END;
    ELSE
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                    'CKTS_SB_MTS_CKSH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,T.SBXH,NULL,'MTS_BJGX_SHZL_CKMX_CKPZ','I',
                    '出口货物报关单号/代理出口货物证明号[' || IFNULL(T.DLCKHWZMHM, T.CKBGDH) || ']本期未申报退税！','Y',CURRENT_TIMESTAMP
               FROM CKTS_SB_MTS_CKSH_LSB T
              WHERE T.SBID=V_IN_SBID
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_TSSB_LSB S WHERE S.SBID=T.SBID AND IFNULL(S.DLZMH, S.CKBGDH) = IFNULL(T.DLCKHWZMHM, T.CKBGDH));
        COMMIT;
      END;
    END IF;
    FOR LSF_XX IN (SELECT A.SBXH,
                          A.CKBGDH AS CKPZH,
                          A.CJHBZM_DM,
                          E.HBZL_DM,
                          A.CKXSERMB,
                          ROUND(B.MYLAJ * C.HL_RMB / 100,2) AS MYLAJZRMB
                     FROM CKTS_SB_MTS_CKSH_LSB A
                    INNER JOIN CKTS_SB_MTS_TSSB_LSB B ON B.SBID=A.SBID AND B.CKBGDH = A.CKBGDH
                    INNER JOIN GS_HBZL_HLV C ON C.CODE='USD' AND C.HL_YM=DATE_FORMAT(B.CKRQ_1, '%Y%m')
                    INNER JOIN CKTS_WBSJ_HG_BGD201 D ON D.DJXH=V_IN_DJXH AND D.CKBGDH=A.CKBGDH
                    INNER JOIN DM_HBZL_HG E ON E.HBZL_HG=D.CJHGHBSZ_DM
                    WHERE A.SBID=V_IN_SBID AND A.DLCKHWZMHM IS NULL) LOOP
      BEGIN
        IF LSF_XX.CJHBZM_DM<>LSF_XX.HBZL_DM THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_CKSH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,LSF_XX.SBXH,NULL,'MTS_BJGX_SHZL_CKMX_CJBZ','I',
                      '出口货物报关单号/代理出口货物证明号[' || LSF_XX.CKPZH || ']的出口退（免）税销售额币种[' || LSF_XX.CJHBZM_DM || ']与电子信息中的币制[' || LSF_XX.HBZL_DM || ']不一致！','Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF LSF_XX.CKXSERMB>1.05*LSF_XX.MYLAJZRMB OR LSF_XX.CKXSERMB<0.95*LSF_XX.MYLAJZRMB THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_CKSH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,LSF_XX.SBXH,NULL,'MTS_BJGX_SHZL_CKMX_CJJE','I',
                      '出口货物报关单号/代理出口货物证明号[' || LSF_XX.CKPZH || ']的出口退（免）税销售额折人民币[' || LSF_XX.CKXSERMB || ']与出口明细表中美元离岸价折算的人民币金额[' || LSF_XX.MYLAJZRMB || ']超过合理区间！','Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;
    END LOOP;    
    FOR LSF_XX IN (SELECT A.SBXH,
                          A.DLCKHWZMHM AS CKPZH,
                          A.CJHBZM_DM,
                          E.HBZL_DM,
                          A.CKXSERMB,
                          ROUND(B.MYLAJ * C.HL_RMB / 100,2) AS MYLAJZRMB
                     FROM CKTS_SB_MTS_CKSH_LSB A
                    INNER JOIN CKTS_SB_MTS_TSSB_LSB B ON B.SBID=A.SBID AND B.DLZMH = A.DLCKHWZMHM
                    INNER JOIN GS_HBZL_HLV C ON C.CODE='USD' AND C.HL_YM=DATE_FORMAT(B.CKRQ_1, '%Y%m')
                    INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM D ON D.DJXH=V_IN_DJXH AND D.DLCKHWZMHM=A.DLCKHWZMHM
                    INNER JOIN DM_HBZL_HG E ON E.HBZL_HG=D.CJHGHBSZ_DM
                    WHERE A.SBID=V_IN_SBID AND A.DLCKHWZMHM IS NOT NULL) LOOP
      BEGIN
        IF LSF_XX.CJHBZM_DM<>LSF_XX.HBZL_DM THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_CKSH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,LSF_XX.SBXH,NULL,'MTS_BJGX_SHZL_CKMX_CJBZ','I',
                      '出口货物报关单号/代理出口货物证明号[' || LSF_XX.CKPZH || ']的出口退（免）税销售额币种[' || LSF_XX.CJHBZM_DM || ']与电子信息中的币制[' || LSF_XX.HBZL_DM || ']不一致！','Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
        IF LSF_XX.CKXSERMB>1.05*LSF_XX.MYLAJZRMB OR LSF_XX.CKXSERMB<0.95*LSF_XX.MYLAJZRMB THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_MTS_CKSH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,LSF_XX.SBXH,NULL,'MTS_BJGX_SHZL_CKMX_CJJE','I',
                      '出口货物报关单号/代理出口货物证明号[' || LSF_XX.CKPZH || ']的出口退（免）税销售额折人民币[' || LSF_XX.CKXSERMB || ']与出口明细表中美元离岸价折算的人民币金额[' || LSF_XX.MYLAJZRMB || ']超过合理区间！','Y',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;
    END LOOP;    
  END;
END$$

DELIMITER ;
