DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_MDT_STZC$$

CREATE PROCEDURE PROC_XXBD_MDT_STZC
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  --视同自产明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_STZCQD_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;
  SET LC_YDOBJECT ='视同自产';

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_MDT_STZCQD_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_STZC_CKHW_SBNO','E','对应出口明细表申报序号在货物出口明细中业务类型非视同自产','N',CURRENT_TIMESTAMP
           FROM CKTS_SB_MDT_STZCQD_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MDT_TSSB_LSB S WHERE S.SBID=T.SBID AND S.SBXH=T.MXSBXH AND INSTR(S.CKTMSYWLXDMJH,'STZC')>0);
    COMMIT;
  END;
END$$

DELIMITER ;
