DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_JSB_TSSB_DLZM$$

CREATE PROCEDURE PROC_XXBD_JSB_TSSB_DLZM
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（出口已使用旧设备退税）
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);
  DECLARE LN_CMCD_LEN     BIGINT;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  -- 代理证明号出口明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_YS_SBMX_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.DLCKHWZMHM IS NOT NULL;
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  SET LC_YDOBJECT ='代理证明';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_YS_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'JSB_CKMX_DLZM_WDZXX','E',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', T.DLCKHWZMHM), ']无电子信息！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_YS_SBMX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.DLCKHWZMHM IS NOT NULL
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_ZJ_DLCKHWZM S WHERE S.DJXH=V_IN_DJXH AND S.DLCKHWZMHM=T.DLCKHWZMHM);
    COMMIT;
  END;

  BEGIN
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_DLCKHWZMHM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_BYTSBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKRQ_SB_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKRQ_SH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSP_DM_SB_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_CKSP_DM_SH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_JGFS_DM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_JGFSTSLX_DM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_YSFS_DM_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT A.SBXH,
                          A.DLCKHWZMHM,
                          B.BYTSBZ,
                          DATE(A.CKRQ_1) AS CKRQ_SB,
                          DATE(B.CKRQ_1) AS CKRQ_SH,
                          A.CKSP_DM AS CKSP_DM_SB,
                          B.CKSP_DM AS CKSP_DM_SH,
                          C.JGFS_DM,
                          C.JGFSTSLX_DM,
                          B.YSFS_DM
                     FROM CKTS_SB_YS_SBMX_LSB A
                    INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM B ON B.DJXH=V_IN_DJXH AND B.DLCKHWZMHM=A.DLCKHWZMHM
                     LEFT JOIN CKTS_DM_HGJGFS C ON C.JGFS_DM=B.JGFS_DM
                    WHERE A.SBID=V_IN_SBID
                      AND A.DLCKHWZMHM IS NOT NULL;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_SBXH_001, BJTS_LSF_XX_DLCKHWZMHM_001, BJTS_LSF_XX_BYTSBZ_001, BJTS_LSF_XX_CKRQ_SB_001, BJTS_LSF_XX_CKRQ_SH_001, BJTS_LSF_XX_CKSP_DM_SB_001, BJTS_LSF_XX_CKSP_DM_SH_001, BJTS_LSF_XX_JGFS_DM_001, BJTS_LSF_XX_JGFSTSLX_DM_001, BJTS_LSF_XX_YSFS_DM_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      BEGIN
        IF BJTS_LSF_XX_BYTSBZ_001='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'JSB_CKMX_DLZM_BYTS','E',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']已被标注为“不予退税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF ((BJTS_LSF_XX_CKRQ_SB_001<>BJTS_LSF_XX_CKRQ_SH_001)) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'JSB_CKMX_DLZM_CKRQ','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']出口日期['), DATE_FORMAT(BJTS_LSF_XX_CKRQ_SB_001, '%Y-%m-%d')), ']与电子信息中['), DATE_FORMAT(BJTS_LSF_XX_CKRQ_SH_001, '%Y-%m-%d')), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        SET LN_CMCD_LEN = CASE WHEN LENGTH(BJTS_LSF_XX_CKSP_DM_SB_001) > LENGTH(BJTS_LSF_XX_CKSP_DM_SH_001) THEN LENGTH(BJTS_LSF_XX_CKSP_DM_SH_001) ELSE LENGTH(BJTS_LSF_XX_CKSP_DM_SB_001) END;
        IF SUBSTR(BJTS_LSF_XX_CKSP_DM_SB_001,1,LN_CMCD_LEN)<>SUBSTR(BJTS_LSF_XX_CKSP_DM_SH_001,1,LN_CMCD_LEN) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'JSB_CKMX_DLZM_SPDM','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']商品代码['), BJTS_LSF_XX_CKSP_DM_SB_001), ']与电子信息中['), BJTS_LSF_XX_CKSP_DM_SH_001), ']不一致！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (TRIM(BJTS_LSF_XX_JGFS_DM_001) IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'JSB_CKMX_DLZM_MYXZ_BCZ','E',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']在电子信息中监管方式不存在！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSE
          IF (TRIM(BJTS_LSF_XX_JGFSTSLX_DM_001)='0') THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_SB_YS_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'JSB_CKMX_DLZM_MYXZ_BTS','E',ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']在电子信息中监管方式['), BJTS_LSF_XX_JGFS_DM_001), ']不退税！'),'N',CURRENT_TIMESTAMP
;
            COMMIT;
          END IF;
        END IF;

        IF BJTS_LSF_XX_YSFS_DM_001='T' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'JSB_CKMX_CKPZH_YSFS','E',ORA_CONCAT(ORA_CONCAT('代理出口货物证明号[', BJTS_LSF_XX_DLCKHWZMHM_001), ']为出口到综合试验区（横琴平潭地区）的报关单！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
  END;
END$$

DELIMITER ;
