DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_XFS_TSSB_JKXFS$$

CREATE PROCEDURE PROC_XXBD_XFS_TSSB_JKXFS
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（出口非自产货物退消费税）
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_MXROW        BIGINT;
  DECLARE LC_YDOBJECT     VARCHAR(20);

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';

  -- 进口消费税缴款书记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_FZC_SBMX_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.CKTMSPZLX_DM='05';
    IF LN_MXROW=0 THEN
      LEAVE routine_body;
    END IF;
  END;

  SET LC_YDOBJECT ='进口消费税';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'XFS_CKMX_XFSJKS_WDZXX','E',ORA_CONCAT(ORA_CONCAT('海关进口消费税缴款书[', T.XFSPZH), ']无电子信息！'),'N',CURRENT_TIMESTAMP
           FROM CKTS_SB_FZC_SBMX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.CKTMSPZLX_DM='05'
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_HG_JKJKS S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.HGZYJKSHM=T.XFSPZH);
    COMMIT;
  END;

  BEGIN
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_XFSPZH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_BYTSBZ_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_HGJKJKSCLJG_DM_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT A.SBXH,
                          A.XFSPZH,
                          B.BYTSBZ,
                          B.HGJKJKSCLJG_DM
                     FROM CKTS_SB_FZC_SBMX_LSB A
                    INNER JOIN CKTS_WBSJ_HG_JKJKS B ON B.DJXH=V_IN_DJXH AND B.HGZYJKSHM=A.XFSPZH
                    WHERE A.SBID=V_IN_SBID
                      AND A.CKTMSPZLX_DM='05';
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_SBXH_001, BJTS_LSF_XX_XFSPZH_001, BJTS_LSF_XX_BYTSBZ_001, BJTS_LSF_XX_HGJKJKSCLJG_DM_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      BEGIN
        IF BJTS_LSF_XX_BYTSBZ_001='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'XFS_CKMX_JKXFS_BYTS','E',ORA_CONCAT(ORA_CONCAT('海关进口消费税缴款书[', BJTS_LSF_XX_XFSPZH_001), ']已被标注为“不予退税”！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF BJTS_LSF_XX_HGJKJKSCLJG_DM_001 IN ('100','500') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'XFS_CKMX_JKXFS_DUP','E',ORA_CONCAT(ORA_CONCAT('海关进口消费税缴款书[', BJTS_LSF_XX_XFSPZH_001), ']在电子信息中重复申请退税！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
  END;
END$$

DELIMITER ;
