DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_ZG_WZFDBTSBA$$

CREATE PROCEDURE PROC_XXBD_ZG_WZFDBTSBA
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（代办退税情况备案）
  修改日期：20210618，企业端提交的代办退税银行、账号未落地CKTS_BA_WMZHFWDBTS_LSB，增加对应字段接收数据并调整比对逻辑
  修改日期：20210830，BA_DBTS_WZF_YHXX_BYZ疑点拆分为两个，名称不一致的（有可能全称与简称的区别）可挑过，账号不一致的不可跳过
 */
(
  IN V_IN_NSRDZDAH DECIMAL(38,10), /*纳税人电子档案号*/
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 其他:执行失败*/
  OUT V_OUT_MESSAGE VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LDT_TODAY       DATETIME;

  DECLARE LC_QYHGDM       VARCHAR(20);
  DECLARE LC_QYLXDM       VARCHAR(20);
  DECLARE LC_TSJSFSDM     VARCHAR(20);
  DECLARE LC_WMZHFWQYBZ   VARCHAR(20);
  DECLARE LC_SFYSFW       VARCHAR(20);
  DECLARE LC_YSFW         VARCHAR(50);
  DECLARE LC_YSFS         VARCHAR(50);
  DECLARE LC_YFSJ         VARCHAR(50);
  DECLARE LC_ZXFLAG       VARCHAR(20);
  DECLARE LC_YHMC         VARCHAR(200);
  DECLARE LC_YHZH         VARCHAR(100);
  DECLARE LC_YDOBJECT     VARCHAR(20);

  DECLARE LN_CPCODEKZ     BIGINT;
  DECLARE LC_KZXX         VARCHAR(20);
  DECLARE LC_FLGLCD       VARCHAR(20);
  DECLARE LN_ROWNUM_CKMX  BIGINT;

  SET V_OUT_STATUS ='00';
  SET V_OUT_MESSAGE =' ';
  SET LDT_TODAY =DATE(CURRENT_TIMESTAMP);

  IF V_IN_SSSQ>DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m') THEN
    BEGIN
      SET V_OUT_STATUS ='05';
      SET V_OUT_MESSAGE ='申报所属时期超出合理范围！';
      LEAVE routine_body;
    END;
  END IF;

  -- 取各申报明细表数据记录
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='06';
      SET V_OUT_MESSAGE ='查询申报记录数据失败！';
      LEAVE routine_body;

  END;
SELECT COUNT(1)
      INTO LN_ROWNUM_CKMX
      FROM CKTS_BA_WMZHFWDBTS_LSB
     WHERE SBID=V_IN_SBID;
  END;
  IF LN_ROWNUM_CKMX=0 THEN
    BEGIN
      SET V_OUT_STATUS ='07';
      SET V_OUT_MESSAGE ='申报数据为空！';
      LEAVE routine_body;
    END;
  END IF;

  -- 查询企业基本信息
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_OUT_STATUS ='08';
      SET V_OUT_MESSAGE ='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;

  END;
SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG, T.YHMC, T.YHZH
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG, LC_YHMC, LC_YHZH
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  END;
  IF LC_ZXFLAG='Y' THEN
    BEGIN
      SET V_OUT_STATUS ='09';
      SET V_OUT_MESSAGE ='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      LEAVE routine_body;
    END;
  END IF;

  -- 取企业的FLGLCD信息, TGSHZL信息，判断是否需要申报收汇
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD, LN_CPCODEKZ);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      SET V_OUT_STATUS ='10';
      SET V_OUT_MESSAGE ='查询出口企业分类管理类型出错！';
      LEAVE routine_body;
    END;
  END IF;

  IF LC_QYLXDM<>'3' OR LC_TSJSFSDM<>'2' THEN
    BEGIN
      SET V_OUT_STATUS ='11';
      SET V_OUT_MESSAGE ='备案信息中企业类型、退免税计算方法与当前申报业务冲突！';
      LEAVE routine_body;
    END;
  END IF;

  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'YBNSRRD',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      SET V_OUT_STATUS ='12';
      SET V_OUT_MESSAGE ='企业当前非增值税一般纳税人，不允许申报出口退（免）税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TQQY',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 THEN
    BEGIN
      SET V_OUT_STATUS ='13';
      SET V_OUT_MESSAGE ='企业当前处于出口退税停权期间，不允许申报出口退（免）税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXMS',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      SET V_OUT_STATUS ='14';
      SET V_OUT_MESSAGE ='企业当前处于放弃退（免）税权选择免税期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXZS',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      SET V_OUT_STATUS ='15';
      SET V_OUT_MESSAGE ='企业当前处于放弃退（免）税权选择征税期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;
  CALL FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTMS',LDT_TODAY,LC_KZXX, LN_CPCODEKZ);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      SET V_OUT_STATUS ='16';
      SET V_OUT_MESSAGE ='企业当前处于放弃退（免）税权期间，不允许申报出口货物劳务免退税业务！';
      LEAVE routine_body;
    END;
  END IF;

  SET LC_YDOBJECT ='代办备案';
  BEGIN
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_XX_SBXH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_DBTSBALCZT_DM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_WTDBTSSCQYNSRMC_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_WTDBTSSCQYHGQYDM_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_WTDBTSSCQYDBTSKHYHMC_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_WTDBTSSCQYDBTSKHYHZH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_WMZHFWHTXYHM_NEW_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_WMZHFWHTXYHM_OLD_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_NSRSBH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_NSRMC_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSKHYHMC_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_TSKHYHZH_001 LONGTEXT;
  DECLARE BJTS_LSF_XX_WMZHFWHTXYHM_SC_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT A.SBXH, A.DBTSBALCZT_DM, A.WTDBTSSCQYNSRMC, A.WTDBTSSCQYHGQYDM, A.WTDBTSSCQYNSRSBH, A.TSKHYHMC AS WTDBTSSCQYDBTSKHYHMC, A.TSKHYHZH AS WTDBTSSCQYDBTSKHYHZH,
                          A.WMZHFWHTXYHM AS WMZHFWHTXYHM_NEW,
                          B.WMZHFWHTXYHM AS WMZHFWHTXYHM_OLD,
                          C.NSRSBH, C.NSRMC, C.TSKHYHMC, C.TSKHYHZH, C.WMZHFWHTXYHM AS WMZHFWHTXYHM_SC
                     FROM CKTS_BA_WMZHFWDBTS_LSB A
                     LEFT JOIN CKTS_JGB_BA_WMZHFWDBTS B ON B.DJXH=V_IN_DJXH AND (B.WTDBTSSCQYNSRSBH=A.WTDBTSSCQYNSRSBH OR B.WTDBTSSCQYSHXYDM=A.WTDBTSSCQYNSRSBH)
                     LEFT JOIN CKTS_WBSJ_ZJ_SCWTDBBA C ON C.DJXH=V_IN_DJXH AND (C.NSRSBH=A.WTDBTSSCQYNSRSBH OR C.SHXYDM=A.WTDBTSSCQYNSRSBH)
                    WHERE A.SBID=V_IN_SBID;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_XX_SBXH_001, BJTS_LSF_XX_DBTSBALCZT_DM_001, BJTS_LSF_XX_WTDBTSSCQYNSRMC_001, BJTS_LSF_XX_WTDBTSSCQYHGQYDM_001, BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001, BJTS_LSF_XX_WTDBTSSCQYDBTSKHYHMC_001, BJTS_LSF_XX_WTDBTSSCQYDBTSKHYHZH_001, BJTS_LSF_XX_WMZHFWHTXYHM_NEW_001, BJTS_LSF_XX_WMZHFWHTXYHM_OLD_001, BJTS_LSF_XX_NSRSBH_001, BJTS_LSF_XX_NSRMC_001, BJTS_LSF_XX_TSKHYHMC_001, BJTS_LSF_XX_TSKHYHZH_001, BJTS_LSF_XX_WMZHFWHTXYHM_SC_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      BEGIN
        IF (BJTS_LSF_XX_DBTSBALCZT_DM_001='1' AND BJTS_LSF_XX_WMZHFWHTXYHM_OLD_001 IS NOT NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'BA_DBTS_WZF_BAXX_DUP','E',ORA_CONCAT(ORA_CONCAT('生产企业[', BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001), ']代办退税的备案信息已存在，请选择变更流程！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        ELSEIF(BJTS_LSF_XX_DBTSBALCZT_DM_001='2' AND BJTS_LSF_XX_WMZHFWHTXYHM_OLD_001 IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'BA_DBTS_WZF_BAXX_NULL','E',ORA_CONCAT(ORA_CONCAT('生产企业[', BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001), ']代办退税的备案信息不存在，请选择备案流程！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;

        IF (BJTS_LSF_XX_NSRSBH_001 IS NOT NULL) THEN
          IF TRIM(BJTS_LSF_XX_WTDBTSSCQYNSRMC_001) <> TRIM(BJTS_LSF_XX_NSRMC_001) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'BA_DBTS_WZF_BAXX_BYZ','E',ORA_CONCAT(ORA_CONCAT('生产企业[', BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001), ']对应的名称与该企业委托代办备案信息不一致！'),'N',CURRENT_TIMESTAMP
;
            COMMIT;
          END IF;

          IF (BJTS_LSF_XX_WTDBTSSCQYDBTSKHYHZH_001<>BJTS_LSF_XX_TSKHYHZH_001) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'BA_DBTS_WZF_YHXX_BYZ','E',ORA_CONCAT(ORA_CONCAT('生产企业[', BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001), ']对应的退税银行账户与该企业委托代办备案信息不一致！'),'N',CURRENT_TIMESTAMP
;
            COMMIT;
          END IF;

          IF (BJTS_LSF_XX_WTDBTSSCQYDBTSKHYHMC_001 <> BJTS_LSF_XX_TSKHYHMC_001) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'BA_DBTS_WZF_YHXX_BYZ','E',ORA_CONCAT(ORA_CONCAT('生产企业[', BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001), ']对应的退税银行名称与该企业委托代办备案信息不一致！'),'Y',CURRENT_TIMESTAMP
;
            COMMIT;
          END IF;

          IF (BJTS_LSF_XX_WMZHFWHTXYHM_NEW_001 <> BJTS_LSF_XX_WMZHFWHTXYHM_SC_001) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                        'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'BA_DBTS_WZF_HTXX_BYZ','E',ORA_CONCAT(ORA_CONCAT('生产企业[', BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001), ']对应的代办退税协议与该企业委托代办备案信息不一致！'),'N',CURRENT_TIMESTAMP
;
            COMMIT;
          END IF;
        ELSE
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_NEXTVAL('SEQ_XXBD_SHQ_YDID'),LC_YDOBJECT,
                      'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,BJTS_LSF_XX_SBXH_001,NULL,'BA_DBTS_WZF_SCQYWBA','E',ORA_CONCAT(ORA_CONCAT('缺少生产企业[', BJTS_LSF_XX_WTDBTSSCQYNSRSBH_001), ']的委托代办备案信息！'),'N',CURRENT_TIMESTAMP
;
          COMMIT;
        END IF;
      END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
  END;
END$$

DELIMITER ;
