DELIMITER $$

DROP PROCEDURE IF EXISTS PROC_XXBD_CHECK_SHQ$$

CREATE PROCEDURE PROC_XXBD_CHECK_SHQ
/*
  编制人:严国平
  编制日期:202009
  功能:检查、创建、取消审核区
 */
(
  IN V_IN_DJXH DECIMAL(38,10), /*登记序号*/
  IN V_IN_SBYWBDM VARCHAR(4000), /*申报业务表代码*/
  IN V_IN_SSSQ VARCHAR(4000), /*申报年月*/
  IN V_IN_SBPC DECIMAL(38,10), /*申报批次*/
  IN V_IN_SBID DECIMAL(38,10), /*申报ID*/
  IN V_IN_YWLX VARCHAR(4000), /*01：创建审核区；02：取消审核区*/
  OUT V_OUT_STATUS VARCHAR(4000), /*00:成功; 01:创建审核区失败；02：取消审核区失败*/
  OUT V_OUT_SBYWBDM VARCHAR(4000),
  OUT V_OUT_SSSQ VARCHAR(4000),
  OUT V_OUT_SBPC DECIMAL(38,10),
  OUT V_OUT_SBID DECIMAL(38,10),
  OUT V_OUT_CRTIME DATETIME
)
routine_body: BEGIN
  DECLARE V_TEMP      BIGINT DEFAULT 0;

  SET V_TEMP = 0;

  IF V_IN_YWLX='01' THEN
    /*创建审核区*/
    BEGIN
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ (DJXH, SBYWB_DM, SSSQ, SBPC, SBID, CRTIME, NOTE)
             VALUES (V_IN_DJXH, V_IN_SBYWBDM, V_IN_SSSQ, V_IN_SBPC, V_IN_SBID, CURRENT_TIMESTAMP, '信息比对');
      EXCEPTION
        WHEN OTHERS THEN
          SET V_TEMP = SQLCODE;
      END;
      IF V_TEMP=0 THEN
         SET V_OUT_STATUS ='00';
         COMMIT;
      ELSE
         SET V_OUT_STATUS ='01';
         ROLLBACK;
      END IF;
      IF V_OUT_STATUS <> '00' THEN
        BEGIN
          BEGIN
            SELECT SBYWB_DM, SSSQ, SBPC, SBID, CRTIME
              INTO V_OUT_SBYWBDM, V_OUT_SSSQ, V_OUT_SBPC, V_OUT_SBID, V_OUT_CRTIME
              FROM CKTS_XXBD_SHQ
             WHERE DJXH = V_IN_DJXH;
          EXCEPTION
            WHEN OTHERS THEN
              DO 0;
          END;
        END;
      END IF;
      LEAVE routine_body;
    END;
  ELSE
    /*取消审核区*/
    BEGIN
      SELECT COUNT(1)
        INTO V_TEMP
        FROM CKTS_XXBD_SHQ
       WHERE DJXH = V_IN_DJXH;

      IF V_TEMP>0 THEN
        BEGIN
          SET V_TEMP =0;
          BEGIN
            DELETE CKTS_XXBD_SHQ WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_XXBD_SHQ_YDXX WHERE DJXH = V_IN_DJXH;

            DELETE CKTS_GCB_ZM_TYYBSWTS WHERE DJXH = V_IN_DJXH;

            DELETE CKTS_JGB_BA_SCQYWTDBTS WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_JGB_BA_WMZHFWDBTS WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_JGB_BA_XTHHZG WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_JGB_ZM_TYYBSWTS WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_JGB_ZM_LLJG WHERE DJXH = V_IN_DJXH;

            DELETE CKTS_WBSJ_FP_YCKSPZXX WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_FP_ZZSZYFPXX WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_FP_ZZSFPHWXX WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_GT3_ZS_JKS WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_HG_BGD201 WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_HG_BGD202 WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_HG_DZSZCBAXX WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_HG_JKJKS WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_ZJ_DLCKHWZM WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_ZJ_JHBFXCJG WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_ZJ_SCWTDBBA WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_ZJ_TYYBSWTSZM WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_ZJ_WTCKHWZM WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_ZJ_XKFP WHERE DJXH = V_IN_DJXH;
            DELETE CKTS_WBSJ_ZJ_ZJZYJKS WHERE DJXH = V_IN_DJXH;

            COMMIT;
          EXCEPTION
            WHEN OTHERS THEN
              SET V_TEMP = SQLCODE;
          END;
        END;
      END IF;

      IF V_TEMP=0 THEN
         SET V_OUT_STATUS ='00';
         COMMIT;
      ELSE
         SET V_OUT_STATUS ='02';
         ROLLBACK;
      END IF;
    END;
  END IF;
END$$

DELIMITER ;
