package com.tl.web.bjts.shzs.dao;

import com.tl.web.bjts.shzs.model.domain.TlDtbsj;

public interface TlDtbsjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DTBSJ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DTBSJ
     *
     * @mbggenerated
     */
    int insert(TlDtbsj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DTBSJ
     *
     * @mbggenerated
     */
    int insertSelective(TlDtbsj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DTBSJ
     *
     * @mbggenerated
     */
    TlDtbsj selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DTBSJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TlDtbsj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DTBSJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TlDtbsj record);
}