package com.tl.web.bjts.shzs.dao;

import com.tl.web.bjts.shzs.model.domain.TlRoleProfile;

public interface TlRoleProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_ROLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_ROLE
     *
     * @mbggenerated
     */
    int insert(TlRoleProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_ROLE
     *
     * @mbggenerated
     */
    int insertSelective(TlRoleProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_ROLE
     *
     * @mbggenerated
     */
    TlRoleProfile selectByPrimaryKey(String roleDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TlRoleProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TlRoleProfile record);
}