package com.tl.web.bjts.shzs.dao;

import com.tl.web.bjts.shzs.model.domain.TlSWJGProfile;
import com.tl.web.bjts.shzs.model.domain.TlSWJGProfileExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface TlSWJGProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_SWJG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String swjgDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_SWJG
     *
     * @mbggenerated
     */
    int insert(TlSWJGProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_SWJG
     *
     * @mbggenerated
     */
    int insertSelective(TlSWJGProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_SWJG
     *
     * @mbggenerated
     */
    List<TlSWJGProfile> selectByExampleWithRowbounds(TlSWJGProfileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_SWJG
     *
     * @mbggenerated
     */
    List<TlSWJGProfile> selectByExample(TlSWJGProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_SWJG
     *
     * @mbggenerated
     */
    TlSWJGProfile selectByPrimaryKey(String swjgDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_SWJG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TlSWJGProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_SWJG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TlSWJGProfile record);
}