-- TDSQL-C MySQL 8.0 shared objects for the BJTS Oracle routine migration.
-- Run this file before installing routines from the three mysql_tl_* folders.
-- The seed values below reflect the checked-in Oracle export snapshots.
-- Refresh them from the final Oracle sequence positions before cutover.

CREATE TABLE IF NOT EXISTS sys_sequence (
    SEQ_NAME VARCHAR(100) NOT NULL,
    SEQ_VALUE BIGINT NOT NULL,
    PRIMARY KEY (SEQ_NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

INSERT INTO sys_sequence (SEQ_NAME, SEQ_VALUE) VALUES
    ('SEQ_DEAL_TKGZ', 11959),
    ('SEQ_FXGL_DATA_ZXZB', 96139),
    ('SEQ_FXGL_SZ_SPFXJH', 489082),
    ('SEQ_GS_TB_NSRDZDAH', 219970),
    ('SEQ_JKGL_DATA_TJ_ZBU_CKGB', 18094660),
    ('SEQ_JKGL_DATA_TJ_ZBU_CKKA', 9491620),
    ('SEQ_JKGL_DATA_TJ_ZBU_CKSP', 17759240),
    ('SEQ_JKGL_DATA_TJ_ZBU_DZGF', 3728720),
    ('SEQ_JKGL_DATA_TJ_ZBU_DZSPJX', 115360),
    ('SEQ_JKGL_DATA_TJ_ZBU_DZSPXX', 32180),
    ('SEQ_JKGL_DATA_TJ_ZBU_DZXF', 4828980),
    ('SEQ_JKGL_DATA_TJ_ZBU_TSGH', 17807380),
    ('SEQ_JKGL_DATA_TJ_ZBU_TSSP', 15818820),
    ('SEQ_JKGL_QSPJ_CKSP', 448980),
    ('SEQ_MSG_PUSH_DATA', 157819),
    ('SEQ_MSG_PUSH_PLAN', 166080),
    ('SEQ_TB_DTBSJ_ID', 23893952),
    ('SEQ_TB_TBPC', 34395504),
    ('SEQ_TJBB_SB_JYXX', 16940),
    ('SEQ_XXBD_SHQ_YDID', 16085620),
    ('SEQ_YJ_DATA_YJXX', 406200)
ON DUPLICATE KEY UPDATE
    SEQ_VALUE = GREATEST(SEQ_VALUE, VALUES(SEQ_VALUE));

DELIMITER $$

DROP FUNCTION IF EXISTS ORA_CONCAT$$

CREATE FUNCTION ORA_CONCAT(P_LEFT LONGTEXT, P_RIGHT LONGTEXT)
RETURNS LONGTEXT
DETERMINISTIC
NO SQL
RETURN NULLIF(CONCAT(IFNULL(P_LEFT, ''), IFNULL(P_RIGHT, '')), '')$$

DROP FUNCTION IF EXISTS ORA_REGEXP_SUBSTR$$

CREATE FUNCTION ORA_REGEXP_SUBSTR(
    P_EXPR LONGTEXT,
    P_PATTERN LONGTEXT,
    P_POSITION INT,
    P_OCCURRENCE INT,
    P_MATCH_TYPE VARCHAR(10),
    P_SUBEXPR INT
)
RETURNS LONGTEXT
DETERMINISTIC
NO SQL
BEGIN
    DECLARE V_FULL_MATCH LONGTEXT;

    SET V_FULL_MATCH = REGEXP_SUBSTR(
        P_EXPR,
        P_PATTERN,
        P_POSITION,
        P_OCCURRENCE,
        P_MATCH_TYPE
    );
    IF V_FULL_MATCH IS NULL OR P_SUBEXPR < 0 OR P_SUBEXPR > 9 THEN
        RETURN NULL;
    END IF;
    IF P_SUBEXPR = 0 THEN
        RETURN V_FULL_MATCH;
    END IF;

    RETURN REGEXP_REPLACE(
        V_FULL_MATCH,
        P_PATTERN,
        CONCAT('$', P_SUBEXPR),
        1,
        1,
        P_MATCH_TYPE
    );
END$$

DROP FUNCTION IF EXISTS ORA_MEDIAN$$

CREATE FUNCTION ORA_MEDIAN(P_VALUES JSON)
RETURNS DECIMAL(65,30)
DETERMINISTIC
CONTAINS SQL
BEGIN
    DECLARE V_RESULT DECIMAL(65,30);

    IF P_VALUES IS NULL OR JSON_LENGTH(P_VALUES) = 0 THEN
        RETURN NULL;
    END IF;

    WITH BJTS_VALUES AS (
        SELECT V_VALUE
          FROM JSON_TABLE(
                   P_VALUES,
                   '$[*]' COLUMNS (
                       V_VALUE DECIMAL(65,30) PATH '$'
                           NULL ON EMPTY NULL ON ERROR
                   )
               ) AS J
         WHERE V_VALUE IS NOT NULL
    ),
    BJTS_RANKED AS (
        SELECT V_VALUE,
               ROW_NUMBER() OVER (ORDER BY V_VALUE) AS V_ROW_NO,
               COUNT(*) OVER () AS V_ROW_COUNT
          FROM BJTS_VALUES
    )
    SELECT AVG(V_VALUE)
      INTO V_RESULT
      FROM BJTS_RANKED
     WHERE V_ROW_NO IN (
         FLOOR((V_ROW_COUNT + 1) / 2),
         FLOOR((V_ROW_COUNT + 2) / 2)
     );

    RETURN V_RESULT;
END$$

DROP FUNCTION IF EXISTS ORA_SPLIT_JSON$$

CREATE FUNCTION ORA_SPLIT_JSON(P_VALUE LONGTEXT, P_DELIMITER VARCHAR(4000))
RETURNS JSON
DETERMINISTIC
NO SQL
BEGIN
    DECLARE V_RESULT JSON;
    DECLARE V_REST LONGTEXT;
    DECLARE V_POSITION INT;
    DECLARE V_TOKEN LONGTEXT;

    SET V_RESULT = JSON_ARRAY();
    SET V_REST = P_VALUE;
    SET P_DELIMITER = COALESCE(NULLIF(P_DELIMITER, ''), ',');

    WHILE V_REST IS NOT NULL AND V_REST <> '' DO
        SET V_POSITION = LOCATE(P_DELIMITER, V_REST);
        IF V_POSITION = 0 THEN
            SET V_TOKEN = V_REST;
            SET V_REST = NULL;
        ELSE
            SET V_TOKEN = LEFT(V_REST, V_POSITION - 1);
            SET V_REST = SUBSTRING(
                V_REST,
                V_POSITION + CHAR_LENGTH(P_DELIMITER)
            );
        END IF;

        IF V_TOKEN IS NOT NULL AND V_TOKEN <> '' THEN
            SET V_RESULT = JSON_ARRAY_APPEND(V_RESULT, '$', V_TOKEN);
        END IF;
    END WHILE;

    RETURN V_RESULT;
END$$

DROP FUNCTION IF EXISTS ORA_DATE_ADD$$

CREATE FUNCTION ORA_DATE_ADD(P_VALUE DATETIME(6), P_DAYS DECIMAL(38,10))
RETURNS DATETIME(6)
DETERMINISTIC
NO SQL
RETURN TIMESTAMPADD(
    MICROSECOND,
    CAST(ROUND(P_DAYS * 86400000000) AS SIGNED),
    P_VALUE
)$$

DROP FUNCTION IF EXISTS ORA_DATE_DIFF$$

CREATE FUNCTION ORA_DATE_DIFF(P_END DATETIME(6), P_START DATETIME(6))
RETURNS DECIMAL(38,10)
DETERMINISTIC
NO SQL
RETURN TIMESTAMPDIFF(MICROSECOND, P_START, P_END) / 86400000000$$

DROP FUNCTION IF EXISTS ORA_NEXT_DAY$$

CREATE FUNCTION ORA_NEXT_DAY(P_VALUE DATETIME(6), P_WEEKDAY VARCHAR(20))
RETURNS DATETIME(6)
DETERMINISTIC
NO SQL
BEGIN
    DECLARE V_TARGET_DAY TINYINT;

    SET V_TARGET_DAY = CASE UPPER(TRIM(P_WEEKDAY))
        WHEN 'SUNDAY' THEN 1 WHEN 'SUN' THEN 1 WHEN '1' THEN 1
        WHEN 'MONDAY' THEN 2 WHEN 'MON' THEN 2 WHEN '2' THEN 2
        WHEN 'TUESDAY' THEN 3 WHEN 'TUE' THEN 3 WHEN '3' THEN 3
        WHEN 'WEDNESDAY' THEN 4 WHEN 'WED' THEN 4 WHEN '4' THEN 4
        WHEN 'THURSDAY' THEN 5 WHEN 'THU' THEN 5 WHEN '5' THEN 5
        WHEN 'FRIDAY' THEN 6 WHEN 'FRI' THEN 6 WHEN '6' THEN 6
        WHEN 'SATURDAY' THEN 7 WHEN 'SAT' THEN 7 WHEN '7' THEN 7
        ELSE NULL
    END;

    IF P_VALUE IS NULL OR V_TARGET_DAY IS NULL THEN
        RETURN NULL;
    END IF;

    RETURN TIMESTAMPADD(
        DAY,
        MOD(V_TARGET_DAY - DAYOFWEEK(P_VALUE) + 6, 7) + 1,
        P_VALUE
    );
END$$

DROP PROCEDURE IF EXISTS ORA_RAISE_APPLICATION_ERROR$$

CREATE PROCEDURE ORA_RAISE_APPLICATION_ERROR(
    IN P_ERROR_NUMBER INT,
    IN P_MESSAGE LONGTEXT
)
BEGIN
    DECLARE V_MESSAGE VARCHAR(128);

    SET V_MESSAGE = LEFT(
        CONCAT('[ORA-', ABS(P_ERROR_NUMBER), '] ', COALESCE(P_MESSAGE, '')),
        128
    );
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = V_MESSAGE;
END$$

DROP FUNCTION IF EXISTS SEQ_NEXTVAL$$

CREATE FUNCTION SEQ_NEXTVAL(P_SEQ_NAME VARCHAR(100))
RETURNS BIGINT
NOT DETERMINISTIC
MODIFIES SQL DATA
BEGIN
    INSERT INTO sys_sequence (SEQ_NAME, SEQ_VALUE)
    VALUES (UPPER(P_SEQ_NAME), LAST_INSERT_ID(1))
    ON DUPLICATE KEY UPDATE
        SEQ_VALUE = LAST_INSERT_ID(SEQ_VALUE + 1);

    RETURN LAST_INSERT_ID();
END$$

DELIMITER ;

-- Creating a data-modifying function can require the TDSQL-C account setting
-- equivalent to MySQL log_bin_trust_function_creators = ON.
