CREATE OR REPLACE FUNCTION FUNC_XXBD_COMPUTE_CHUFA(V_IN_NUMBER1 IN NUMBER, V_IN_NUMBER2 IN NUMBER)
  RETURN NUMBER
/*
 * 编 制 人: 严国平
 * 编制日期: 20201225
 * 功    能: 计算两个数的商
 * 返 回 值：除数为0时，返回被除数，否则返回商
 */
IS
  V_NUMBER NUMBER;
BEGIN
  IF V_IN_NUMBER2=0 THEN
    V_NUMBER := V_IN_NUMBER1;
  ELSE
    V_NUMBER := V_IN_NUMBER1 / V_IN_NUMBER2;
  END IF;

  RETURN V_NUMBER;
END;
/
