CREATE OR REPLACE PROCEDURE PROC_XXBD_TSZM_DLCKHWZM
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（代理出口货物证明）
  调整日期：20201221，1、调整TSZM_DLCK_CKSL_BYZ疑点，提示信息精确化，加出口数量、退税数量、退运数量、代理数量；
                      2、调整TSZM_DLCK_JLDW_BYZ疑点，取消与报关单第一计量单位名称（金三中为NULL）的比较，改用第一计量单位代码对应名称集比较；
                      3、恢复TSZM_DLCK_CKRQ_TQQY疑点，具体出口日期采用报关单电子信息中的出口日期；
                      4、增加TSZM_DLCK_WTFNSH_NULL提示性疑点；
  调整日期：20201222，1、增加TSZM_DLCK_CKRQ_BYZ错误性疑点；
  调整日期：20201225，1、增加TSZM_DLCK_CKDJ_BYZ提示性疑点。
  调整日期：20201228，1、增加TSZM_BJGX_DLCK_WZFZG提示性疑点(电子税务局已实现，兼容离线版申报自检）。TSZM_DLCK_CKRQ_BYZ
  调整日期：20210526，1、调整疑点TSZM_DLCK_CKRQ_BYZ内容的日期格式，限定为YYYY-MM-DD。
  调整日期：20210715，1、调整疑点TSZM_DLCK_WTFNSR_NULL判断逻辑，先判断本地企业再判断全国备案信息
  调整日期：20210923，1、调整疑点TSZM_DLCK_BTSSP_WTZM判断逻辑，增加委托方税号与代理出口证明中社会信用代码的关联
  调整日期：20211011，1、调整疑点TSZM_DLCK_BTSSP_WTZM判断逻辑，针对10位商品代码为取消退税商品且不为基本商品，如果11位扩展码存在退税则不跳疑点，否则照旧。
  调整日期：20211020，1、调整疑点TSZM_DLCK_BTSSP_SPDM判断逻辑，针对委托证明存在8位商品代码的情况，按委托证明、代理证明商品代码长度短的部分进行判断
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LDT_TODAY    DATE;

  LC_QYHGDM       VARCHAR2(20);
  LC_QYLXDM       VARCHAR2(20);
  LC_TSJSFSDM     VARCHAR2(20);
  LC_WMZHFWQYBZ   VARCHAR2(20);
  LC_SFYSFW       VARCHAR2(20);
  LC_YSFW         VARCHAR2(50);
  LC_YSFS         VARCHAR2(50);
  LC_YFSJ         VARCHAR2(50);
  LC_ZXFLAG       VARCHAR2(20);

  LN_CPCODEKZ     NUMBER(10);
  LC_KZXX         VARCHAR2(20);
  LC_FLGLCD       VARCHAR2(20);
  LN_ROWNUM_TSSB  NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);

  LN_DJ1          NUMBER;
  LN_DJ2          NUMBER;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  IF V_IN_SSSQ>TO_CHAR(SYSDATE,'YYYYMM') THEN
    BEGIN
      V_OUT_STATUS :='05';
      V_OUT_MESSAGE:='申报所属时期超出合理范围！';
      RETURN;
    END;
  END IF;

  --取各申报明细表数据记录
  BEGIN
    SELECT COUNT(1)
      INTO LN_ROWNUM_TSSB
      FROM CKTS_ZM_DLCK_LSB
     WHERE SBID=V_IN_SBID;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='06';
      V_OUT_MESSAGE:='查询申报记录数据失败！';
      RETURN;
  END;
  IF LN_ROWNUM_TSSB=0 THEN
    BEGIN
      V_OUT_STATUS :='07';
      V_OUT_MESSAGE:='申报数据为空！';
      RETURN;
    END;
  END IF;

  --查询企业基本信息
  BEGIN
    SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='08';
      V_OUT_MESSAGE:='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
  END;
  IF LC_ZXFLAG='R' THEN
    BEGIN
      V_OUT_STATUS :='09';
      V_OUT_MESSAGE:='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
    END;
  END IF;

  --取企业的FLGLCD信息, TGSHZL信息，判断是否需要申报收汇
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      V_OUT_STATUS :='10';
      V_OUT_MESSAGE:='查询出口企业分类管理类型出错！';
      RETURN;
    END;
  END IF;

  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'YBNSRRD',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      V_OUT_STATUS :='12';
      V_OUT_MESSAGE:='企业当前非增值税一般纳税人，不允许申报出口退（免）税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TQQY',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 THEN
    BEGIN
      V_OUT_STATUS :='13';
      V_OUT_MESSAGE:='企业当前处于出口退税停权期间，不允许申报出口退（免）税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXMS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      V_OUT_STATUS :='14';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权选择免税期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXZS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      V_OUT_STATUS :='15';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权选择征税期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTMS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      V_OUT_STATUS :='16';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;

  LC_YDOBJECT:='代理出口';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_ZM_DLCK_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_DLCK_BGD_WDZXX','E','出口货物报关单号[' || T.CKBGDH || ']无电子信息！','N',SYSDATE
           FROM CKTS_ZM_DLCK_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_HG_BGD201 S WHERE S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH);
    COMMIT;

    FOR LSF_XX IN (SELECT A.SBXH,
                          A.CKBGDH,
                          TRUNC(A.CKRQ_1,'DD') AS CKRQ_SB,
                          TRUNC(B.CKRQ_1,'DD') AS CKRQ_SH,
                          A.CKSP_DM AS CKSP_DM_SB,
                          B.CKSP_DM AS CKSP_DM_SH,
                          A.CKSL AS CKSL_SB,
                          B.CKSL,
                          NVL(B.TSSBSL,0) AS TSSBSL,
                          NVL(B.TYSL,0) AS TYSL,
                          NVL(B.DLSBSL,0) AS DLSBSL,
                          GREATEST(0, B.CKSL-NVL(B.TSSBSL,0)-NVL(B.TYSL,0)-NVL(B.DLSBSL,0)) AS SYSL_SH,
                          A.MYLAJ AS MYLAJ_SB,
                          GREATEST(0, B.MYLAJ-NVL(B.TSSBMYLAJ,0)-NVL(B.DLSBMYLAJ,0)-NVL(B.TYMYLAJ,0)) AS MYLAJ_SH,
                          TRIM(UPPER(A.HGJLDWMC)) AS HGJLDWMC_SB,
                          F.HGJLDWQC AS HGJLDWMC_WK,
                          NVL(C.CKSP_DM,D.CKSP_DM) AS CKSP_DM_QXTS,
                          E.WTCKHWZMBH,
                          E.CKSP_DM AS CKSP_DM_WT,
                          G.UUID AS TQQY,
                          NVL(I.NSRSBH,H.UUID) AS WTQY,
                          A.BZ
                     FROM CKTS_ZM_DLCK_LSB A
                    INNER JOIN CKTS_WBSJ_HG_BGD201 B ON B.DJXH=V_IN_DJXH AND B.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_DM_TSLVWK C ON C.CKSP_DM=A.CKSP_DM AND (B.CKRQ_1 BETWEEN C.YXQQ AND C.YXQZ) AND C.ZSSL>0 AND C.TSL=0 AND C.CKSPTSSPLX_DM='1'
                     LEFT JOIN CKTS_DM_TSLVWK D ON D.CKSP_DM=SUBSTR(A.CKSP_DM,1,8) AND (B.CKRQ_1 BETWEEN D.YXQQ AND D.YXQZ) AND D.ZSSL>0 AND D.TSL=0 AND D.CKSPTSSPLX_DM='1'
                     LEFT JOIN CKTS_WBSJ_ZJ_WTCKHWZM E ON E.DJXH=V_IN_DJXH AND (E.WTFNSRSBH=A.WTFNSRSBH OR E.WTFSHXYDM=A.WTFNSRSBH) AND E.WTCKHWZMBH=A.WTCKHWZMBH
                    INNER JOIN CKTS_DM_HGJLDW F ON F.HGJLDW_DM=B.DYJLDW_DM
                     LEFT JOIN GS_DJ_CKTMSDAB_KZ G ON G.NSRDZDAH=V_IN_NSRDZDAH AND G.KZLX='TQQY' AND G.FLAG='1' AND (B.CKRQ_1 BETWEEN G.ST_DATE AND G.END_DATE)
                     LEFT JOIN CKTS_WBSJ_ZJ_CKTSBAQGXX H ON H.NSRSBH=A.WTFNSRSBH OR H.SHXYDM=A.WTFNSRSBH
                     LEFT JOIN GS_DJ_CKTMSDAB I ON I.NSRDJNO=A.WTFNSRSBH OR I.SHXYNO=A.WTFNSRSBH
                    WHERE A.SBID=V_IN_SBID) LOOP
      BEGIN
        IF (LSF_XX.CKSP_DM_SB<>LSF_XX.CKSP_DM_SH) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_SPDM_BYZ','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']商品代码[' || LSF_XX.CKSP_DM_SB || ']与电子信息中[' || LSF_XX.CKSP_DM_SH || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.CKRQ_SB<>LSF_XX.CKRQ_SH) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_CKRQ_BYZ','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']出口日期[' || TO_CHAR(LSF_XX.CKRQ_SB,'YYYY-MM-DD') || ']与电子信息中[' || TO_CHAR(LSF_XX.CKRQ_SH,'YYYY-MM-DD') || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.CKSL_SB>LSF_XX.SYSL_SH) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_CKSL_BYZ','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']申报数量[' || LSF_XX.CKSL_SB || ']超过电子信息中剩余数[' || LSF_XX.SYSL_SH ||
                      ']（其中出口[' || LSF_XX.CKSL || ']退税申报[' || LSF_XX.TSSBSL || ']退运[' || LSF_XX.TYSL || ']代理申报[' || LSF_XX.DLSBSL || ']）！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.MYLAJ_SB >= LSF_XX.MYLAJ_SH + 1) AND (LSF_XX.MYLAJ_SB >= LSF_XX.MYLAJ_SH * 1.05) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_USDJE_OVER','W','出口货物报关单号[' || LSF_XX.CKBGDH || ']申报美元离岸价[' || LSF_XX.MYLAJ_SB || ']大于电子信息中剩余数[' || LSF_XX.MYLAJ_SH || ']！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.MYLAJ_SB <= LSF_XX.MYLAJ_SH - 1) AND (LSF_XX.MYLAJ_SB <= LSF_XX.MYLAJ_SH * 0.95) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_USDJE_LOW','W','出口货物报关单号[' || LSF_XX.CKBGDH || ']申报美元离岸价[' || LSF_XX.MYLAJ_SB || ']小于电子信息中剩余数[' || LSF_XX.MYLAJ_SH || ']！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        LN_DJ1 := FUNC_XXBD_COMPUTE_CHUFA(LSF_XX.MYLAJ_SB, LSF_XX.CKSL_SB);
        LN_DJ2 := FUNC_XXBD_COMPUTE_CHUFA(LSF_XX.MYLAJ_SH, LSF_XX.SYSL_SH);
        IF (LN_DJ1 > LN_DJ2 * 1.05) OR (LN_DJ1 < LN_DJ2 * 0.95) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_CKDJ_BYZ','W','出口货物报关单号[' || LSF_XX.CKBGDH || ']申报单价与海关信息不匹配！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF INSTR('.'||LSF_XX.HGJLDWMC_WK||'.', '.'||LSF_XX.HGJLDWMC_SB||'.')=0 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_JLDW_BYZ','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']申报计量单位[' || LSF_XX.HGJLDWMC_SB || ']与报关单第一计量单位不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.CKSP_DM_QXTS IS NOT NULL) THEN
          IF (LSF_XX.WTCKHWZMBH IS NULL) THEN
            SELECT COUNT(1)
              INTO LN_ROWNUM_TSSB
              FROM CKTS_DM_TSLVWK T
             WHERE T.CKSP_DM LIKE LSF_XX.CKSP_DM_QXTS || '%'
               AND (LSF_XX.CKRQ_SB BETWEEN T.YXQQ AND T.YXQZ)
               AND (T.ZSSL=0 OR T.TSL>0);
            IF LN_ROWNUM_TSSB=0 THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_BTSSP_WTZM','W','出口货物报关单号[' || LSF_XX.CKBGDH || ']商品代码[' || LSF_XX.CKSP_DM_SB || ']为取消退税商品，未找到对应的委托证明信息！','Y',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
          ELSE
            LN_ROWNUM_TSSB := LEAST(LENGTH(LSF_XX.CKSP_DM_SB),LENGTH(LSF_XX.CKSP_DM_WT));
            IF (SUBSTR(LSF_XX.CKSP_DM_SB,1,LN_ROWNUM_TSSB)<>SUBSTR(LSF_XX.CKSP_DM_WT,1,LN_ROWNUM_TSSB)) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_BTSSP_SPDM','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']商品代码[' || LSF_XX.CKSP_DM_SB || ']与委托出口货物证明的同一报关单的商品代码[' || LSF_XX.CKSP_DM_WT || ']不一致！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
          END IF;
        END IF;

        IF (LSF_XX.TQQY IS NOT NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_CKRQ_TQQY','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']对应出口日期为被停止出口退税权期间，不得办理《代理出口证明》！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.WTQY IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_DLCK_WTFNSR_NULL','W','未查询到委托企业信息，请核实委托企业纳税社会信用码（识别号）是否准确！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LC_WMZHFWQYBZ='Y' AND INSTR(LSF_XX.BZ, 'WMZHFW')=0 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_DLCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_BJGX_DLCK_WZFZG','W','外综服企业申请开具代理出口货物证明，备注栏未录入“WMZHFW”标识”，请确认！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;
END;
/
