CREATE OR REPLACE PROCEDURE PROC_XXBD_XFS_TSSB
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（出口非自产货物退消费税）
  调整日期：20220323，1、根据总局货劳司关于加强启运港出口退（免）税统计分析功能的业务要求，增加XFS_CKMX_CKYWLX_QYGTS疑点
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LC_KZXX         VARCHAR2(20);
  LDT_TODAY       DATE;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  --出口明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_FZC_SBMX_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  LC_YDOBJECT :='退消费税';
  BEGIN
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TGSHZL',LDT_TODAY,LC_KZXX);
    IF (LC_FLGLCD='D') OR (LN_CPCODEKZ>0) THEN
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_FZC_SBMX_LSB','CKTS_SB_FZC_CKSH_LSB',NULL,T.SBXH,NULL,'XFS_BJGX_CKMX_SHZL_CKPZ','E','出口货物报关单号/代理出口货物证明号[' || T.CKBGDH || T.DLCKHWZMHM || ']未申报收汇资料！','N',SYSDATE
               FROM CKTS_SB_FZC_SBMX_LSB T
              WHERE T.SBID=V_IN_SBID
                AND FUNC_XXBD_CHECK_NEEDSH(',' || T.CKTMSYWLXDMJH || ',') = 1
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_FZC_CKSH_LSB S WHERE S.SBID=T.SBID AND S.CKBGDH||S.DLCKHWZMHM=T.CKBGDH||T.DLCKHWZMHM);
        COMMIT;
      END;
    ELSE
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_FZC_SBMX_LSB','CKTS_SB_FZC_CKSH_LSB',NULL,T.SBXH,NULL,'XFS_BJGX_CKMX_SHZL_CKPZ','E','出口货物报关单号/代理出口货物证明号[' || T.CKBGDH || T.DLCKHWZMHM || ']未申报收汇资料！','N',SYSDATE
               FROM CKTS_SB_FZC_SBMX_LSB T
              WHERE T.SBID=V_IN_SBID
                AND (((TO_DATE(TO_CHAR(SYSDATE,'YYYY')||'0419','YYYYMMDD')<SYSDATE) AND (KPRQ<TRUNC(SYSDATE,'YY'))) OR (KPRQ<ADD_MONTHS(TRUNC(SYSDATE,'YY'),-12)))
                AND FUNC_XXBD_CHECK_NEEDSH(',' || T.CKTMSYWLXDMJH || ',') = 1
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_FZC_CKSH_LSB S WHERE S.SBID=T.SBID AND S.CKBGDH||S.DLCKHWZMHM=T.CKBGDH||T.DLCKHWZMHM);
        COMMIT;
      END;
    END IF;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'XFS_CKMX_CKYWLX_QYGTS','E','出口货物报关单号[' || NVL(T.CKBGDH,T.DLCKHWZMHM) || ']为启运港业务，需确认国内启运方式及海关总署认证企业类型！','N',SYSDATE
           FROM CKTS_SB_FZC_SBMX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND INSTR(T.CKTMSYWLXDMJH,'QYGTS')>0
            AND (T.GNQYFS_DM IS NULL OR T.HGZSRZQYLX_DM IS NULL);
    COMMIT;
  END;
END;
/
