CREATE OR REPLACE PROCEDURE PROC_XXBD_JSB_CKSH
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（出口已使用旧设备退税）
  修改日期：20220615，根据2022年9号公告，四类企业，需提供银行水单企业收汇情况表必须申报本期出口退税，非上述企业改为提示性疑点
  修改日期：20230207，修改代理证明出口申报收汇表的疑点逻辑和提示
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LC_KZXX         VARCHAR2(20);
  LDT_TODAY       DATE;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  --收汇明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_YS_CKSH_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  LC_YDOBJECT :='出口收汇';
  BEGIN
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TGSHZL',LDT_TODAY,LC_KZXX);
    IF (LC_FLGLCD='D') OR (LN_CPCODEKZ>0) THEN
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_YS_CKSH_LSB','CKTS_SB_YS_SBMX_LSB',NULL,T.SBXH,NULL,'JSB_BJGX_SHZL_CKMX_CKPZ','E','出口货物报关单号/代理出口货物证明号[' || NVL(T.DLCKHWZMHM,T.CKBGDH) || ']未申报退税！','N',SYSDATE
               FROM CKTS_SB_YS_CKSH_LSB T
              WHERE T.SBID=V_IN_SBID
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_YS_SBMX_LSB S WHERE S.SBID=T.SBID AND NVL(S.DLCKHWZMHM,S.CKBGDH)=NVL(T.DLCKHWZMHM,T.CKBGDH));
        COMMIT;
      END;
    ELSE
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_YS_CKSH_LSB','CKTS_SB_YS_SBMX_LSB',NULL,T.SBXH,NULL,'JSB_BJGX_SHZL_CKMX_CKPZ','I','出口货物报关单号/代理出口货物证明号[' || NVL(T.DLCKHWZMHM,T.CKBGDH) || ']本期未申报退税！','Y',SYSDATE
               FROM CKTS_SB_YS_CKSH_LSB T
              WHERE T.SBID=V_IN_SBID
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_YS_SBMX_LSB S WHERE S.SBID=T.SBID AND NVL(S.DLCKHWZMHM,S.CKBGDH)=NVL(T.DLCKHWZMHM,T.CKBGDH));
        COMMIT;
      END;
    END IF;
  END;
END;
/
