CREATE OR REPLACE PROCEDURE PROC_XXBD_MTS_LSLV
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  调整日期：20211208，1、调整免退税疑点描述字段中申报序号与关联单证号的顺序，使其与客户端疑点展示一致
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_IN_YFSJFW     IN  VARCHAR2, /*出口企业备案研发设计类应税服务类型代码*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LC_MSG          VARCHAR2(200):=' ';
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  --外购服务明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_YSFWCK_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;
  LC_YDOBJECT :='外购服务';

  --初始化增值税发票代码、号码，以备后续使用
  BEGIN
    UPDATE CKTS_SB_MTS_YSFWCK_LSB T
       SET T.FPDM=SUBSTR(T.JHPZH,1,12),
           T.FPHM=SUBSTR(T.JHPZH,13,20)
     WHERE T.SBID=V_IN_SBID AND LENGTH(T.JHPZH)=20;
    COMMIT;
    UPDATE CKTS_SB_MTS_YSFWCK_LSB T
       SET T.FPDM=SUBSTR(T.JHPZH,1,10),
           T.FPHM=SUBSTR(T.JHPZH,11,18)
     WHERE T.SBID=V_IN_SBID AND LENGTH(T.JHPZH)=18;
    COMMIT;
  END;

  FOR LSF_XX IN (SELECT * FROM CKTS_DM_YFSJFW A WHERE A.YXBZ='Y') LOOP
    BEGIN
      SELECT COUNT(1)
        INTO LN_MXROW
        FROM CKTS_SB_MTS_YSFWCK_LSB T
       WHERE T.SBID=V_IN_SBID AND T.CKTMSYWLXDMJH LIKE '%'||LSF_XX.YFSJFWJC||'%';
      IF LN_MXROW>0 AND INSTR(V_IN_YFSJFW,LSF_XX.YFSJFWDM)=0 THEN
        LC_MSG:=LC_MSG||LSF_XX.YFSJFWMC||',';
      END IF;
    END;
  END LOOP;
  IF LC_MSG<>' ' OR TRIM(LC_MSG) IS NOT NULL THEN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
     SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
            'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,NULL,NULL,'MTS_BJGX_YSFW_SPDM','E','不允许申报未备案的应税服务[' || LC_MSG || ']。','N',SYSDATE
       FROM DUAL;
    COMMIT;
  END IF;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,T.SBXH,NULL,'MTS_YSFW_CKRQ_NSRZG','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业非增值税一般纳税人！','N',SYSDATE
           FROM CKTS_SB_MTS_YSFWCK_LSB T
           LEFT JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='YBNSRRD' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND S.KZLX IS NULL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,T.SBXH,NULL,'MTS_YSFW_CKRQ_TQQY','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于出口退税停权期间！','N',SYSDATE
           FROM CKTS_SB_MTS_YSFWCK_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TQQY' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,T.SBXH,NULL,'MTS_YSFW_CKRQ_MSQY','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于免税期间！','N',SYSDATE
           FROM CKTS_SB_MTS_YSFWCK_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSGMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,T.SBXH,NULL,'MTS_YSFW_CKRQ_FQTS','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']放弃零税率应税服务退税期间！','N',SYSDATE
           FROM CKTS_SB_MTS_YSFWCK_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQLSL' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;
  END;
END;
/
