CREATE OR REPLACE PROCEDURE PROC_XXBD_ZG_SCWTDBBA
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（委托代办退税情况备案）
  调整日期：20201217，1、在校验生产企业是否已委托某外综服企业代办时，按生产企业、综服企业分组，按办理时间排序，取最后一条，如果最后一条是撤回备案，默认为可以新增
  调整日期：20210526，1、细化生产企业提供的委托代办退税备案的外综服企业信息与出口退（免）税备案信息不一致的疑点提示
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LDT_TODAY       DATE;

  LC_QYHGDM       VARCHAR2(20);
  LC_QYLXDM       VARCHAR2(20);
  LC_TSJSFSDM     VARCHAR2(20);
  LC_WMZHFWQYBZ   VARCHAR2(20);
  LC_SFYSFW       VARCHAR2(20);
  LC_YSFW         VARCHAR2(50);
  LC_YSFS         VARCHAR2(50);
  LC_YFSJ         VARCHAR2(50);
  LC_ZXFLAG       VARCHAR2(20);

  LC_YDOBJECT     VARCHAR2(20);

  LN_CPCODEKZ     NUMBER(10);
  LC_KZXX         VARCHAR2(20);
  LC_FLGLCD       VARCHAR2(20);
  LN_ROWNUM_CKMX  NUMBER(10);
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  IF V_IN_SSSQ>TO_CHAR(SYSDATE,'YYYYMM') THEN
    BEGIN
      V_OUT_STATUS :='05';
      V_OUT_MESSAGE:='申报所属时期超出合理范围！';
      RETURN;
    END;
  END IF;

  --取各申报明细表数据记录
  BEGIN
    SELECT COUNT(1)
      INTO LN_ROWNUM_CKMX
      FROM CKTS_BA_SCQYWTDBTS_LSB
     WHERE SBID=V_IN_SBID;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='06';
      V_OUT_MESSAGE:='查询申报记录数据失败！';
      RETURN;
  END;
  IF LN_ROWNUM_CKMX=0 THEN
    BEGIN
      V_OUT_STATUS :='07';
      V_OUT_MESSAGE:='申报数据为空！';
      RETURN;
    END;
  END IF;

  --查询企业基本信息
  BEGIN
    SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='08';
      V_OUT_MESSAGE:='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
  END;
  IF LC_ZXFLAG='Y' THEN
    BEGIN
      V_OUT_STATUS :='09';
      V_OUT_MESSAGE:='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
    END;
  END IF;

  --取企业的FLGLCD信息, TGSHZL信息，判断是否需要申报收汇
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      V_OUT_STATUS :='10';
      V_OUT_MESSAGE:='查询出口企业分类管理类型出错！';
      RETURN;
    END;
  END IF;

  IF ((LC_QYLXDM<>'1' AND LC_QYLXDM<>'2') OR LC_TSJSFSDM<>'1') THEN
    BEGIN
      V_OUT_STATUS :='11';
      V_OUT_MESSAGE:='备案信息中企业类型、退免税计算方法与当前申报业务冲突！';
      RETURN;
    END;
  END IF;

  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'YBNSRRD',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      V_OUT_STATUS :='12';
      V_OUT_MESSAGE:='企业当前非增值税一般纳税人，不允许申报出口退（免）税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TQQY',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 THEN
    BEGIN
      V_OUT_STATUS :='13';
      V_OUT_MESSAGE:='企业当前处于出口退税停权期间，不允许申报出口退（免）税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXMS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      V_OUT_STATUS :='14';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权选择免税期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXZS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      V_OUT_STATUS :='15';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权选择征税期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTMS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      V_OUT_STATUS :='16';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;

  LC_YDOBJECT:='委托代办';
  BEGIN
    FOR LSF_XX IN (SELECT A.SBXH, A.DBTSBALCZT_DM, A.WMZHFWQYNSRMC, A.WMZHFWQYHGQYDM, A.WMZHFWQYNSRSBH, A.TSKHYHMC, A.TSKHYHZH, A.FDDBRXM,
                          B.DBTSBALCZT_DM AS YDBTSBALCZTDM,
                          C.NSRSBH, C.NSRMC, C.QYHGDM, C.YHMC, C.YHZH,
                          D.NSRSBH AS NSRSBH_QG, D.NSRMC AS NSRMC_QG, D.HGQY_DM
                     FROM CKTS_BA_SCQYWTDBTS_LSB A
                     LEFT JOIN (SELECT WMZHFWQYNSRSBH,DBTSBALCZT_DM,ROW_NUMBER() OVER (PARTITION BY WMZHFWQYNSRSBH ORDER BY LRRQ DESC) AS RN
                                  FROM CKTS_JGB_BA_SCQYWTDBTS WHERE DJXH=V_IN_DJXH) B ON B.WMZHFWQYNSRSBH=A.WMZHFWQYNSRSBH AND B.RN=1
                     LEFT JOIN GS_DJ_CKTMSDAB C ON C.NSRDJNO=A.WMZHFWQYNSRSBH OR C.SHXYNO=A.WMZHFWQYNSRSBH
                     LEFT JOIN CKTS_WBSJ_ZJ_CKTSBAQGXX D ON D.NSRSBH=A.WMZHFWQYNSRSBH OR D.SHXYDM=A.WMZHFWQYNSRSBH
                    WHERE A.SBID=V_IN_SBID) LOOP
      BEGIN
        IF (LSF_XX.FDDBRXM IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_FRDB_NULL','E','法人代表不允许为空，请反馈企业备案信息以后重新申报！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.DBTSBALCZT_DM='3') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_BALC_ERR','E','备案流程与申报业务不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSE
          IF (LSF_XX.DBTSBALCZT_DM='1' AND LSF_XX.YDBTSBALCZTDM IS NOT NULL AND LSF_XX.YDBTSBALCZTDM<>'3') THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_WTBAXX_DUP','E','生产企业已办理该外综服企业[' || LSF_XX.WMZHFWQYNSRSBH || ']的委托代办退税备案，请选择变更流程！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          ELSIF(LSF_XX.DBTSBALCZT_DM='2' AND (LSF_XX.YDBTSBALCZTDM IS NULL OR LSF_XX.YDBTSBALCZTDM='3')) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_WTBAXX_NULL','E','生产企业未办理该外综服企业[' || LSF_XX.WMZHFWQYNSRSBH || ']的委托代办退税备案，请选择备案流程！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;

          IF (LSF_XX.NSRSBH IS NOT NULL) THEN
            --外综服企业为本地出口企业
            IF TRIM(LSF_XX.WMZHFWQYNSRMC) <> TRIM(LSF_XX.NSRMC) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_ZFQYXX_BYZ','E','生产企业提供的委托代办退税的外综服企业名称[' || LSF_XX.WMZHFWQYNSRMC || ']与该外综服企业出口退（免）税备案信息不一致！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
            IF TRIM(LSF_XX.WMZHFWQYHGQYDM) <> TRIM(LSF_XX.QYHGDM) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_ZFQYXX_BYZ','E','生产企业提供的委托代办退税的外综服企业海关代码[' || LSF_XX.WMZHFWQYHGQYDM || ']与该外综服企业出口退（免）税备案信息不一致！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
            IF (TRIM(LSF_XX.TSKHYHMC) <> TRIM(LSF_XX.YHMC)) OR (TRIM(LSF_XX.TSKHYHZH) <> TRIM(LSF_XX.YHZH)) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_ZFQYXX_BYZ','E','生产企业提供的代办退税银行账号[' || LSF_XX.TSKHYHMC || LSF_XX.TSKHYHZH || ']与该外综服企业出口退（免）税备案信息不一致！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
          ELSIF (LSF_XX.NSRSBH_QG IS NOT NULL) THEN
            --外综服企业为外地出口企业
            IF TRIM(LSF_XX.WMZHFWQYNSRMC) <> TRIM(LSF_XX.NSRMC_QG) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_ZFQYXX_BYZ','E','生产企业提供的委托代办退税的外综服企业名称[' || LSF_XX.WMZHFWQYNSRMC || ']与该外综服企业出口退（免）税备案信息不一致！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
            IF TRIM(LSF_XX.WMZHFWQYHGQYDM) <> TRIM(LSF_XX.HGQY_DM) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_ZFQYXX_BYZ','E','生产企业提供的委托代办退税的外综服企业海关代码[' || LSF_XX.WMZHFWQYHGQYDM || ']与该外综服企业出口退（免）税备案信息不一致！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
          ELSE
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_BA_SCQYWTDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_SC_ZFQYXX_NULL','W','未查到该综服企业[' || LSF_XX.WMZHFWQYNSRSBH || ']的出口退（免）税备案信息，请确认是否输入正确！','Y',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;
        END IF;
      END;
    END LOOP;
  END;
END;
/
