CREATE OR REPLACE PROCEDURE PROC_XXBD_MTS_TSSB
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  调整日期：20210603，1、调整疑点关联业务字段，关联号+申报序号
  调整日期：20211208，1、调整免退税疑点描述字段中申报序号与关联单证号的顺序，使其与客户端疑点展示一致
  调整日期：20220323，1、根据总局货劳司关于加强启运港出口退（免）税统计分析功能的业务要求，增加MTS_CKMX_CKYWLX_QYGTS疑点
  修改日期：20220615，根据2022年9号公告，合并收汇与不能收汇
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LC_KZXX         VARCHAR2(20);
  LDT_TODAY       DATE;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  --出口明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_TSSB_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  LC_YDOBJECT :='出口明细';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB','CKTS_SB_MTS_TSJH_LSB',NULL,T.SBXH,T.GLH,'MTS_BJGX_CKMX_JHMX_GLH','E','出口明细中的关联号[' || T.GLH || ']在进货明细中不存在！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_TSJH_LSB S WHERE S.SBID=T.SBID AND S.GLH=T.GLH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB','CKTS_SB_MTS_TSJH_LSB',NULL,T.SBXH,T.GLH,'MTS_BJGX_CKMX_JHMX_SPDM','E','出口明细中的关联号[' || T.GLH || ']商品代码[' || T.CKSP_DM || ']在进货明细中不存在！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_TSJH_LSB S WHERE S.SBID=T.SBID AND S.GLH=T.GLH AND S.CKSP_DM=T.CKSP_DM);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB','CKTS_SB_MTS_TSJH_LSB',NULL,T.SBXH,T.GLH,'MTS_BJGX_CKMX_JHMX_JLDW','E','出口明细中的关联号[' || T.GLH || ']计量单位[' || T.HGJLDWMC || ']在进货明细中不存在！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_TSJH_LSB S WHERE S.SBID=T.SBID AND S.GLH=T.GLH AND S.HGJLDWMC=T.HGJLDWMC);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           WITH CK AS (SELECT T.SBID,T.GLH,T.CKSP_DM,SUM(T.CKSL) AS CKSL FROM CKTS_SB_MTS_TSSB_LSB T WHERE T.SBID=V_IN_SBID GROUP BY T.SBID,T.GLH,T.CKSP_DM),
                JH AS (SELECT S.SBID,S.GLH,S.CKSP_DM,SUM(S.SL) AS JHSL FROM CKTS_SB_MTS_TSJH_LSB S WHERE S.SBID=V_IN_SBID AND S.SZ='V' GROUP BY S.SBID,S.GLH,S.CKSP_DM)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB','CKTS_SB_MTS_TSJH_LSB',NULL,NULL,CK.GLH,'MTS_BJGX_CKMX_JHMX_CKSL','E','出口明细中的关联号[' || CK.GLH || ']商品代码[' || CK.CKSP_DM || ']出口数量[' || CK.CKSL || ']大于进货数量[' || NVL(JH.JHSL,0.00) || ']！','N',SYSDATE
           FROM CK
           LEFT JOIN JH ON JH.SBID=CK.SBID AND JH.GLH=CK.GLH AND JH.CKSP_DM=CK.CKSP_DM
          WHERE CK.SBID=V_IN_SBID AND CK.CKSL>NVL(JH.JHSL,0);
    COMMIT;

    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TGSHZL',LDT_TODAY,LC_KZXX);
    IF (LC_FLGLCD='D') OR (LN_CPCODEKZ>0) THEN
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_MTS_TSSB_LSB','CKTS_SB_MTS_CKSH_LSB',NULL,T.SBXH,T.GLH,'MTS_BJGX_CKMX_SHZL_CKPZ','E','出口货物报关单号/代理出口货物证明号[' || T.CKBGDH || T.DLZMH || ']未申报收汇资料！','N',SYSDATE
               FROM CKTS_SB_MTS_TSSB_LSB T
              WHERE T.SBID=V_IN_SBID
                AND FUNC_XXBD_CHECK_NEEDSH(',' || T.CKTMSYWLXDMJH || ',') = 1
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_CKSH_LSB S WHERE S.SBID=T.SBID AND S.CKBGDH||S.DLCKHWZMHM = T.CKBGDH||T.DLZMH);
        COMMIT;
      END;
    ELSE
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_MTS_TSSB_LSB','CKTS_SB_MTS_CKSH_LSB',NULL,T.SBXH,T.GLH,'MTS_BJGX_CKMX_SHZL_CKPZ','E','出口货物报关单号/代理出口货物证明号[' || T.CKBGDH || T.DLZMH || ']未申报收汇资料！','N',SYSDATE
               FROM CKTS_SB_MTS_TSSB_LSB T
              WHERE T.SBID=V_IN_SBID
                AND (((TO_DATE(TO_CHAR(SYSDATE,'YYYY')||'0419','YYYYMMDD')<SYSDATE) AND (CKRQ_1<TRUNC(SYSDATE,'YY'))) OR (CKRQ_1<ADD_MONTHS(TRUNC(SYSDATE,'YY'),-12)))
                AND FUNC_XXBD_CHECK_NEEDSH(',' || T.CKTMSYWLXDMJH || ',') = 1
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_CKSH_LSB S WHERE S.SBID=T.SBID AND S.CKBGDH||S.DLCKHWZMHM = T.CKBGDH||T.DLZMH);
        COMMIT;
      END;
    END IF;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_CKMX_CKRQ_NSRZG','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业非增值税一般纳税人！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
           LEFT JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='YBNSRRD' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND S.KZLX IS NULL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_CKMX_CKRQ_TQQY','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于出口退税停权期间！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TQQY' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_CKMX_CKRQ_MSQY','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于免税期间！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSGMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_CKMX_CKRQ_FQTS','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于放弃退（免）税权选择免税期间！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_CKMX_CKRQ_FQTS','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于放弃退（免）税权选择征税期间！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXZS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_CKMX_CKRQ_FQTS','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于放弃退（免）税权期间！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,T.SBXH,NULL,'MTS_CKMX_CKYWLX_QYGTS','E','出口货物报关单号[' || NVL(T.CKBGDH,T.DLZMH) || ']为启运港业务，需确认国内启运方式及海关总署认证企业类型！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND INSTR(T.CKTMSYWLXDMJH,'QYGTS')>0
            AND (T.GNQYFS_DM IS NULL OR T.HGZSRZQYLX_DM IS NULL);
    COMMIT;
  END;
END;
/
