CREATE OR REPLACE PROCEDURE PROC_XXBD_JSB_TSSB
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（出口已使用旧设备退税）
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LC_KZXX         VARCHAR2(20);
  LDT_TODAY       DATE;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  --出口明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_YS_SBMX_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  LC_YDOBJECT :='已用设备';
  BEGIN
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TGSHZL',LDT_TODAY,LC_KZXX);
    IF (LC_FLGLCD='D') OR (LN_CPCODEKZ>0) THEN
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_YS_SBMX_LSB','CKTS_SB_YS_CKSH_LSB',NULL,T.SBXH,NULL,'JSB_BJGX_CKMX_SHZL_CKPZ','E','出口货物报关单号[' || T.CKBGDH || T.DLCKHWZMHM || ']未申报收汇资料！','N',SYSDATE
               FROM CKTS_SB_YS_SBMX_LSB T
              WHERE T.SBID=V_IN_SBID
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_YS_CKSH_LSB S WHERE S.SBID=T.SBID AND S.CKBGDH||S.DLCKHWZMHM=T.CKBGDH||T.DLCKHWZMHM);
        COMMIT;
      END;
    ELSE
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_YS_SBMX_LSB','CKTS_SB_YS_CKSH_LSB',NULL,T.SBXH,NULL,'JSB_BJGX_CKMX_SHZL_CKPZ','E','出口货物报关单号[' || T.CKBGDH || T.DLCKHWZMHM || ']未申报收汇资料！','N',SYSDATE
               FROM CKTS_SB_YS_SBMX_LSB T
              WHERE T.SBID=V_IN_SBID
                AND (((TO_DATE(TO_CHAR(SYSDATE,'YYYY')||'0419','YYYYMMDD')<SYSDATE) AND (CKRQ_1<TRUNC(SYSDATE,'YY'))) OR (CKRQ_1<ADD_MONTHS(TRUNC(SYSDATE,'YY'),-12)))
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_YS_CKSH_LSB S WHERE S.SBID=T.SBID AND S.CKBGDH||S.DLCKHWZMHM=T.CKBGDH||T.DLCKHWZMHM);
        COMMIT;
      END;
    END IF;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_YS_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'JSB_CKMX_CKRQ_NSRZG','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业非增值税一般纳税人！','N',SYSDATE
           FROM CKTS_SB_YS_SBMX_LSB T
           LEFT JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='YBNSRRD' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND S.KZLX IS NULL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_YS_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'JSB_CKMX_CKRQ_TQQY','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于出口退税停权期间！','N',SYSDATE
           FROM CKTS_SB_YS_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TQQY' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_YS_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'JSB_CKMX_CKRQ_MSQY','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于免税期间！','N',SYSDATE
           FROM CKTS_SB_YS_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSGMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_YS_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'JSB_CKMX_CKRQ_FQTS','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于放弃退（免）税权选择免税期间！','N',SYSDATE
           FROM CKTS_SB_YS_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_YS_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'JSB_CKMX_CKRQ_FQTS','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于放弃退（免）税权选择征税期间！','N',SYSDATE
           FROM CKTS_SB_YS_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXZS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_YS_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'JSB_CKMX_CKRQ_FQTS','E','出口日期[' || TO_CHAR(T.CKRQ_1,'YYYY-MM-DD') || ']企业处于放弃退（免）税权期间！','N',SYSDATE
           FROM CKTS_SB_YS_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTMS' AND S.FLAG='1' AND T.CKRQ_1 BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;
  END;
END;
/
