CREATE OR REPLACE PROCEDURE PROC_XXBD_MDT_XTHH
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LC_ZTXTHHBZ     VARCHAR2(20);
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  --先退后核明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_XTHH_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;
  LC_YDOBJECT :='先退后核';

  BEGIN
    SELECT T.ZTXTHHBZ
      INTO LC_ZTXTHHBZ
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  EXCEPTION
    WHEN OTHERS THEN
      LC_ZTXTHHBZ:='N';
  END;
  IF LC_ZTXTHHBZ='Y' THEN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_XTHH_LSB','GS_DJ_CKTMSDAB',NULL,T.SBXH,NULL,'MDT_XTHH_ZGBA','E','企业已被暂停先退税后核销业务！','N',SYSDATE
           FROM CKTS_SB_MDT_XTHH_LSB T
          WHERE T.SBID=V_IN_SBID;
    COMMIT;
  ELSE
    BEGIN
      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                  'CKTS_SB_MDT_XTHH_LSB','CKTS_SB_MDT_XTHHZG_JGB',NULL,T.SBXH,NULL,'MDT_XTHH_HTBA','E','申报先退税后核销合同号[' || T.CKHTH || ']未备案！','N',SYSDATE
             FROM CKTS_SB_MDT_XTHH_LSB T
            WHERE T.SBID=V_IN_SBID
              AND NOT EXISTS (SELECT 1 FROM CKTS_JGB_BA_XTHHZG S WHERE S.DJXH=V_IN_DJXH AND S.CKHTH=T.CKHTH);
      COMMIT;
      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                  'CKTS_SB_MDT_XTHH_LSB','CKTS_SB_MDT_XTHHZG_JGB',NULL,T.SBXH,NULL,'MDT_XTHH_HTZF','E','申报先退税后核销合同号[' || T.CKHTH || ']的资格申请已作废！','N',SYSDATE
             FROM CKTS_SB_MDT_XTHH_LSB T
            WHERE T.SBID=V_IN_SBID
              AND EXISTS (SELECT 1 FROM CKTS_JGB_BA_XTHHZG S WHERE S.DJXH=V_IN_DJXH AND S.CKHTH=T.CKHTH AND S.ZFBZ_1='Y')
              AND NOT EXISTS (SELECT 1 FROM CKTS_JGB_BA_XTHHZG S WHERE S.DJXH=V_IN_DJXH AND S.CKHTH=T.CKHTH AND S.ZFBZ_1='N');
      COMMIT;

      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                  'CKTS_SB_MDT_XTHH_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_XTHH_CKHW_HTH','E','先退后核附表中合同号[' || T.CKHTH || ']出口货物报关单号[' || T.CKBGDH || ']未申报免退税出口明细！','N',SYSDATE
             FROM CKTS_SB_MDT_XTHH_LSB T
            WHERE T.SBID=V_IN_SBID
              AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MDT_TSSB_LSB S WHERE S.SBID=T.SBID AND S.CKHTH=T.CKHTH AND S.CKBGDH=T.CKBGDH);
      COMMIT;
    END;
  END IF;
END;
/
