CREATE OR REPLACE PROCEDURE PROC_XXBD_JSB_TSSB_DLZM
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（出口已使用旧设备退税）
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CMCD_LEN     NUMBER(10);
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  --代理证明号出口明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_YS_SBMX_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.DLCKHWZMHM IS NOT NULL;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  LC_YDOBJECT :='代理证明';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_YS_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'JSB_CKMX_DLZM_WDZXX','E','代理出口货物证明号[' || T.DLCKHWZMHM || ']无电子信息！','N',SYSDATE
           FROM CKTS_SB_YS_SBMX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.DLCKHWZMHM IS NOT NULL
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_ZJ_DLCKHWZM S WHERE S.DJXH=V_IN_DJXH AND S.DLCKHWZMHM=T.DLCKHWZMHM);
    COMMIT;
  END;

  BEGIN
    FOR LSF_XX IN (SELECT A.SBXH,
                          A.DLCKHWZMHM,
                          B.BYTSBZ,
                          TRUNC(A.CKRQ_1,'DD') AS CKRQ_SB,
                          TRUNC(B.CKRQ_1,'DD') AS CKRQ_SH,
                          A.CKSP_DM AS CKSP_DM_SB,
                          B.CKSP_DM AS CKSP_DM_SH,
                          C.JGFS_DM,
                          C.JGFSTSLX_DM,
                          B.YSFS_DM
                     FROM CKTS_SB_YS_SBMX_LSB A
                    INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM B ON B.DJXH=V_IN_DJXH AND B.DLCKHWZMHM=A.DLCKHWZMHM
                     LEFT JOIN CKTS_DM_HGJGFS C ON C.JGFS_DM=B.JGFS_DM
                    WHERE A.SBID=V_IN_SBID
                      AND A.DLCKHWZMHM IS NOT NULL) LOOP
      BEGIN
        IF LSF_XX.BYTSBZ='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'JSB_CKMX_DLZM_BYTS','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']已被标注为“不予退税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF ((LSF_XX.CKRQ_SB<>LSF_XX.CKRQ_SH)) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'JSB_CKMX_DLZM_CKRQ','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']出口日期[' || TO_CHAR(LSF_XX.CKRQ_SB,'YYYY-MM-DD') || ']与电子信息中[' || TO_CHAR(LSF_XX.CKRQ_SH,'YYYY-MM-DD') || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        LN_CMCD_LEN := CASE WHEN LENGTH(LSF_XX.CKSP_DM_SB) > LENGTH(LSF_XX.CKSP_DM_SH) THEN LENGTH(LSF_XX.CKSP_DM_SH) ELSE LENGTH(LSF_XX.CKSP_DM_SB) END;
        IF SUBSTR(LSF_XX.CKSP_DM_SB,1,LN_CMCD_LEN)<>SUBSTR(LSF_XX.CKSP_DM_SH,1,LN_CMCD_LEN) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'JSB_CKMX_DLZM_SPDM','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']商品代码[' || LSF_XX.CKSP_DM_SB || ']与电子信息中[' || LSF_XX.CKSP_DM_SH || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (TRIM(LSF_XX.JGFS_DM) IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'JSB_CKMX_DLZM_MYXZ_BCZ','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']在电子信息中监管方式不存在！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSE
          IF (TRIM(LSF_XX.JGFSTSLX_DM)='0') THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_SB_YS_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'JSB_CKMX_DLZM_MYXZ_BTS','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']在电子信息中监管方式[' || LSF_XX.JGFS_DM || ']不退税！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;
        END IF;

        IF LSF_XX.YSFS_DM='T' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_YS_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'JSB_CKMX_CKPZH_YSFS','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']为出口到综合试验区（横琴平潭地区）的报关单！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;
END;
/
