CREATE OR REPLACE PROCEDURE PROC_XXBD_TSZM_TYYBSWTS
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（退运已补税未退税证明）
  调整日期：20211025，根据金三H65**疑点，调整部分疑点级别，由错误类疑点改为警告类疑点
  调整日期：20211215，根据临安生产企业已办理退免税后改单导致后续免抵退申报退运冲减无法正常进行的问题，咨询魏浩原业务思路（默认改单或撤单的都是未办理退免税的），增加疑点判断
  调整日期：20230511，1、根据全电票规则调整发票的关联，用JHPZH代替FPDM+FPHM
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LDT_TODAY    DATE;

  LC_QYHGDM       VARCHAR2(20);
  LC_QYLXDM       VARCHAR2(20);
  LC_TSJSFSDM     VARCHAR2(20);
  LC_WMZHFWQYBZ   VARCHAR2(20);
  LC_SFYSFW       VARCHAR2(20);
  LC_YSFW         VARCHAR2(50);
  LC_YSFS         VARCHAR2(50);
  LC_YFSJ         VARCHAR2(50);
  LC_ZXFLAG       VARCHAR2(20);

  LN_CPCODEKZ     NUMBER(10);
  LC_KZXX         VARCHAR2(20);
  LC_FLGLCD       VARCHAR2(20);
  LN_ROWNUM_TSSB  NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  IF V_IN_SSSQ>TO_CHAR(SYSDATE,'YYYYMM') THEN
    BEGIN
      V_OUT_STATUS :='05';
      V_OUT_MESSAGE:='申报所属时期超出合理范围！';
      RETURN;
    END;
  END IF;

  --取各申报明细表数据记录
  BEGIN
    SELECT COUNT(1)
      INTO LN_ROWNUM_TSSB
      FROM CKTS_ZM_TYYBSWTS_LSB
     WHERE SBID=V_IN_SBID;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='06';
      V_OUT_MESSAGE:='查询申报记录数据失败！';
      RETURN;
  END;
  IF LN_ROWNUM_TSSB=0 THEN
    BEGIN
      V_OUT_STATUS :='07';
      V_OUT_MESSAGE:='申报数据为空！';
      RETURN;
    END;
  END IF;

  --查询企业基本信息
  BEGIN
    SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='08';
      V_OUT_MESSAGE:='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
  END;
  IF LC_ZXFLAG='R' THEN
    BEGIN
      V_OUT_STATUS :='09';
      V_OUT_MESSAGE:='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
    END;
  END IF;

  --取企业的FLGLCD信息, TGSHZL信息，判断是否需要申报收汇
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      V_OUT_STATUS :='10';
      V_OUT_MESSAGE:='查询出口企业分类管理类型出错！';
      RETURN;
    END;
  END IF;

  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'YBNSRRD',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      V_OUT_STATUS :='12';
      V_OUT_MESSAGE:='企业当前非增值税一般纳税人，不允许申报出口退（免）税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TQQY',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 THEN
    BEGIN
      V_OUT_STATUS :='13';
      V_OUT_MESSAGE:='企业当前处于出口退税停权期间，不允许申报出口退（免）税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXMS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      V_OUT_STATUS :='14';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权选择免税期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXZS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      V_OUT_STATUS :='15';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权选择征税期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTMS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_TSSB>0 THEN
    BEGIN
      V_OUT_STATUS :='16';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;

  LC_YDOBJECT:='退运证明';
  BEGIN
    --报关单
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_BGD_WDZXX','I','出口货物报关单号[' || T.CKBGDH || ']无电子信息！','Y',SYSDATE
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.CKBGDH)=21
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_HG_BGD201 S WHERE S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH);
    COMMIT;

    FOR LSF_XX IN (SELECT A.SBXH,
                          A.CKBGDH,
                          TRUNC(B.CKRQ_1,'DD') AS CKRQ_SH,
                          A.TMSZTBZ,
                          A.TYYBSWTSTYLX_DM,
                          B.TSSBSL,
                          A.TYSL,
                          B.CKSL-B.TYSL AS KTYSL,
                          C.TYYBSWTSTYLX_DM AS TYYBSWTSTYLXDM_C,
                          B.DLSBSL,
                          D.CKHWTYYBSWTSZMBH,
                          B.QYGBZ,
                          B.QYGWDDBZ,
                          B.QYGCXCKBZ,
                          E.UUID
                     FROM CKTS_ZM_TYYBSWTS_LSB A
                    INNER JOIN CKTS_WBSJ_HG_BGD201 B ON B.DJXH=V_IN_DJXH AND B.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_WBSJ_HG_ZLKZDCLXX_JGB C ON C.DJXH=V_IN_DJXH AND C.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_WBSJ_ZJ_TYYBSWTSZM D ON D.DJXH=V_IN_DJXH AND D.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_GCB_ZM_TYYBSWTS E ON E.DJXH=V_IN_DJXH AND E.CKBGDH=A.CKBGDH
                    WHERE A.SBID=V_IN_SBID
                      AND LENGTH(A.CKBGDH)=21) LOOP
      BEGIN
        IF (MONTHS_BETWEEN(LDT_TODAY,LSF_XX.CKRQ_SH)>12) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_BGD_CKRQ_CQSB','I','出口货物报关单号[' || LSF_XX.CKBGDH || ']退运日期离出口日期[' || TO_CHAR(LSF_XX.CKRQ_SH,'YYYY-MM-DD') || ']超过12个月！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.TMSZTBZ='已办理退（免）税' AND LSF_XX.TSSBSL=0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_BGD_TMSZT_YSB','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']未退税，但退运证明选择“已办理退（免）税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF (LSF_XX.TMSZTBZ='尚未申报退（免）税' AND LSF_XX.TSSBSL>0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_BGD_TMSZT_WSB','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']已退税，但退运证明选择“尚未申报退（免）税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.TYSL>LSF_XX.KTYSL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_BGD_TYSL_OVER','I','出口货物报关单号[' || LSF_XX.CKBGDH || ']申报退运数量[' || LSF_XX.TYSL || ']大于可办理退运数量[' || LSF_XX.KTYSL || ']！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.DLSBSL>0 AND LSF_XX.CKHWTYYBSWTSZMBH IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_BGD_DLCK','I','出口货物报关单号[' || LSF_XX.CKBGDH || ']为代理出口业务，没有委托方开具的出口货物已补税（未退税）证明！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.QYGBZ='Y' AND LSF_XX.QYGWDDBZ='Y' AND LSF_XX.QYGCXCKBZ='Y') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_BGD_QYG','I','出口货物报关单号[' || LSF_XX.CKBGDH || ']为启运港业务，出口货物未运抵离境港不再实际出口且海关撤销出口货物报关单！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.TYYBSWTSTYLXDM_C IN ('1','2','3') OR LSF_XX.UUID IS NOT NULL THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_BGD_TYZM_DUP','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']存在未处理完毕的退运、改单或撤单标识！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        --20211215，根据临安生产企业已办理退免税后改单导致后续免抵退申报退运冲减无法正常进行的问题，咨询魏浩原业务思路（默认改单或撤单的都是未办理退免税的），增加疑点判断
        IF LC_TSJSFSDM='1' AND LSF_XX.TYYBSWTSTYLX_DM IN ('2','3') AND LSF_XX.TSSBSL>0 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_BGD_TMSZT_TYLX','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']已退税，请先红字冲减申报以后办理改单或撤单证明！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;

  BEGIN
    --代理证明
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_DLZM_WDZXX','I','代理出口货物证明号[' || T.CKBGDH || ']无电子信息！','Y',SYSDATE
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.CKBGDH)=20
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_ZJ_DLCKHWZM S WHERE S.DJXH=V_IN_DJXH AND S.DLCKHWZMHM=T.CKBGDH);
    COMMIT;

    FOR LSF_XX IN (SELECT A.SBXH,
                          A.CKBGDH AS DLCKHWZMHM,
                          TRUNC(B.CKRQ_1,'DD') AS CKRQ_SH,
                          A.TMSZTBZ,
                          A.TYYBSWTSTYLX_DM,
                          B.TSSBSL,
                          A.TYSL,
                          B.CKSL-B.TYSL AS KTYSL,
                          E.UUID
                     FROM CKTS_ZM_TYYBSWTS_LSB A
                    INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM B ON B.DJXH=V_IN_DJXH AND B.DLCKHWZMHM=A.CKBGDH
                     LEFT JOIN CKTS_GCB_ZM_TYYBSWTS E ON E.DJXH=V_IN_DJXH AND E.CKBGDH=A.CKBGDH
                    WHERE A.SBID=V_IN_SBID
                      AND LENGTH(A.CKBGDH)=20) LOOP
      BEGIN
        IF (MONTHS_BETWEEN(LDT_TODAY,LSF_XX.CKRQ_SH)>12) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_DLZM_CKRQ_CQSB','I','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']退运日期离出口日期[' || TO_CHAR(LSF_XX.CKRQ_SH,'YYYY-MM-DD') || ']超过12个月！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.TMSZTBZ='已办理退（免）税' AND LSF_XX.TSSBSL=0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_DLZM_TMSZT_YSB','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']未退税，但退运证明选择“已办理退（免）税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF (LSF_XX.TMSZTBZ='尚未申报退（免）税' AND LSF_XX.TSSBSL>0) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_DLZM_TMSZT_WSB','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']已退税，但退运证明选择“尚未申报退（免）税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.TYSL>LSF_XX.KTYSL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_DLZM_TYSL_OVER','I','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']申报退运数量[' || LSF_XX.TYSL || ']大于可办理退运数量[' || LSF_XX.KTYSL || ']！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.UUID IS NOT NULL THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_DLZM_TYZM_DUP','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']存在未处理完毕的退运、改单或撤单标识！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        --20211215，根据临安生产企业已办理退免税后改单导致后续免抵退申报退运冲减无法正常进行的问题，咨询魏浩原业务思路（默认改单或撤单的都是未办理退免税的），增加疑点判断
        IF LC_TSJSFSDM='1' AND LSF_XX.TYYBSWTSTYLX_DM IN ('2','3') AND LSF_XX.TSSBSL>0 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_TYBS_DLZM_TMSZT_TYLX','E','代理出口货物证明号[' || LSF_XX.DLCKHWZMHM || ']已退税，请先红字冲减申报以后办理改单或撤单证明！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;

  BEGIN
    --增值税发票
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_JHPZH_WDZXX','E','进货凭证号码[' || T.JHPZH || ']无电子信息！','N',SYSDATE
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND (LENGTH(T.JHPZH)=20 OR LENGTH(T.JHPZH)=18)
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_FP_ZZSZYFPXX S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.JHPZH=T.JHPZH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_SBTMSE_OVER','E','申报的原退（免）税额[' || T.YSBMDTSE || ']大于进货凭证的税额[' || S.SE || ']！','N',SYSDATE
           FROM CKTS_ZM_TYYBSWTS_LSB T
          INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX S ON S.DJXH=V_IN_DJXH AND S.JHPZH=T.JHPZH
          WHERE T.SBID=V_IN_SBID
            AND (LENGTH(T.JHPZH)=20 OR LENGTH(T.JHPZH)=18)
            AND T.YSBMDTSE>S.SE+0.01;
    COMMIT;
  END;

  BEGIN
    --进口增值税
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_JHPZH_WDZXX','E','进货凭证号码[' || T.JHPZH || ']无电子信息！','N',SYSDATE
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.JHPZH)=22
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_HG_JKJKS S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.HGZYJKSHM=T.JHPZH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_SBTMSE_OVER','E','申报的原退（免）税额[' || T.YSBMDTSE || ']大于进货凭证的税额[' || S.SKJE || ']！','N',SYSDATE
           FROM CKTS_ZM_TYYBSWTS_LSB T
          INNER JOIN CKTS_WBSJ_HG_JKJKS S ON S.DJXH=V_IN_DJXH AND S.HGZYJKSHM=T.JHPZH
          WHERE T.SBID=V_IN_SBID
            AND LENGTH(T.JHPZH)=22
            AND T.YSBMDTSE>S.SKJE;
    COMMIT;
  END;

  BEGIN
    --缴款书号码
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_JKSHM_WDZXX','E','该缴款书号码[' || T.JKSHM || ']不存在！','N',SYSDATE
           FROM CKTS_ZM_TYYBSWTS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.JKSHM IS NOT NULL
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_GT3_ZS_JKS S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.DZSPHM=T.JKSHM);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_ZM_TYYBSWTS_LSB',NULL,NULL,T.SBXH,NULL,'TSZM_TYBS_JKSE_BYZ','I','补缴税额[' || T.YBJTMSK || ']与实际缴纳税款[' || S.SJJE || ']不符！','Y',SYSDATE
           FROM CKTS_ZM_TYYBSWTS_LSB T
          INNER JOIN CKTS_WBSJ_GT3_ZS_JKS S ON S.DJXH=V_IN_DJXH AND S.DZSPHM=T.JKSHM
          WHERE T.SBID=V_IN_SBID
            AND T.YBJTMSK>S.SJJE+0.01;
    COMMIT;
  END;
END;
/
