CREATE OR REPLACE PROCEDURE PROC_XXBD_MTS_TSSB_BGD
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  调整日期：20201106，对金额增加null判断
  调整日期：20201111，增加关联号下进货、出口的商品名称、计量单位校验
  调整日期：20201119，调整改单报关单监控条件，由bgd202不存在改为bgd201.gdbz_1<>Y
  调整日期：20210113，调整改单报关单监控条件，改为bgd202不存在 且 bgd201.gdbz_1<>Y
  调整日期：20210528，修改进出口明细商品名称、计量单位比较的疑点代码
  调整日期：20210603，调整疑点关联业务字段，关联号+申报序号
  调整日期：20210707，MTS_CKMX_BGD_USDLAJ，对数量部分申报的美元离岸价进行折算，疑点为可挑过
  调整日期：20211208，调整免退税疑点描述字段中申报序号与关联单证号的顺序，使其与客户端疑点展示一致
  调整日期：20220615，MTS_CKMX_DLZM_CKSL分层级，申报数量大于出口数量不可挑过，否则大于剩余数量可挑过
  调整日期：20220701，根据全电票规则调整发票的关联，用JHPZH代替FPDM+FPHM
  调整日期：20230313，增加MTS_CKMX_BGD_BSQ_BAQD、MTS_CKMX_BGD_BSQ_BANR疑点判断
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LC_KZXX         VARCHAR2(20);
  LN_CMCD_LEN     NUMBER(10);
  LC_JHPZHJLDW    VARCHAR2(75);
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  --报关单出口明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_TSSB_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.CKBGDH IS NOT NULL;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  LC_YDOBJECT :='出口报关单';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_CKMX_BGD_WDZXX','E',
                '出口货物报关单号[' || T.CKBGDH || ']无电子信息！','N',SYSDATE
           FROM CKTS_SB_MTS_TSSB_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.CKBGDH IS NOT NULL
            AND FUNC_XXBD_CHECK_YWLX(',' || T.CKTMSYWLXDMJH || ',') = 0
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_HG_BGD201 S WHERE S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH);
    COMMIT;
  END;

  BEGIN
    FOR LSF_XX IN (SELECT A.SBXH,
                          A.CKBGDH,
                          B.BYTSBZ,
                          TRUNC(A.CKRQ_1,'DD') AS CKRQ_SB,
                          TRUNC(B.CKRQ_1,'DD') AS CKRQ_SH,
                          TRUNC(B.QYRQ_2,'DD') AS QYRQ_SH,
                          NVL(A.CKTMSYWLXDMJH,' ') AS CKTMSYWLXDMJH,
                          A.CKSP_DM AS CKSP_DM_SB,
                          B.CKSP_DM AS CKSP_DM_SH,
                          A.CKSL AS CKSL_SB,
                          B.CKSL,
                          NVL(B.TSSBSL,0) AS TSSBSL,
                          NVL(B.DLSBSL,0) AS DLSBSL,
                          NVL(B.TYSL,0) AS TYSL,
                          B.CKSL-NVL(B.TSSBSL,0)-NVL(B.DLSBSL,0)-NVL(B.TYSL,0) AS SYSL_SH,
                          A.MYLAJ AS MYLAJ_SB,
                          B.MYLAJ-NVL(B.TSSBMYLAJ,0)-NVL(B.DLSBMYLAJ,0)-NVL(B.TYMYLAJ,0) AS MYLAJ_SH,
                          (B.MYLAJ-NVL(B.TSSBMYLAJ,0)-NVL(B.DLSBMYLAJ,0)-NVL(B.TYMYLAJ,0)) * 
                          (CASE WHEN (A.CKSL=0) OR (B.CKSL-NVL(B.TSSBSL,0)-NVL(B.DLSBSL,0)-NVL(B.TYSL,0)=0) THEN 0
                                ELSE A.CKSL / (B.CKSL-NVL(B.TSSBSL,0)-NVL(B.DLSBSL,0)-NVL(B.TYSL,0)) END) AS MYLAJ_JS,
                          D.TYYBSWTSTYLX_DM,
                          NVL(B.GDBZ_1,' ') AS GDBZ_1,
                          E.CKBGDH AS CKBGDH_GD,
                          C.JGFS_DM,
                          C.JGFSTSLX_DM,
                          B.ZZMDGDQSZ_DM,
                          B.QYGBZ,
                          B.QYGCXCKBZ,
                          B.QYGWDDBZ,
                          B.QYGZCJGBZ,
                          B.YSFS_DM,
                          A.GLH,
                          NVL(B.DYJLDW_DM,' ') AS DYJLDW_DM,
                          NVL(B.DEJLDW_DM,' ') AS DEJLDW_DM,
                          NVL(B.SBJLDW_DM,' ') AS SBJLDW_DM,
                          B.GFHHGSPMC
                     FROM CKTS_SB_MTS_TSSB_LSB A
                    INNER JOIN CKTS_WBSJ_HG_BGD201 B ON B.DJXH=V_IN_DJXH AND B.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_DM_HGJGFS C ON C.JGFS_DM=B.JGFS_DM
                     LEFT JOIN CKTS_JGB_ZM_TYYBSWTS D ON D.DJXH=V_IN_DJXH AND D.CKBGDH=B.CKBGDH AND NVL(D.ZFBZ_1,'N')='N'
                     LEFT JOIN CKTS_WBSJ_HG_BGD202 E ON E.DJXH=V_IN_DJXH AND E.CKBGDH=B.CKBGDH
                    WHERE A.SBID=V_IN_SBID
                      AND A.CKBGDH IS NOT NULL
                      AND FUNC_XXBD_CHECK_YWLX(',' || A.CKTMSYWLXDMJH || ',') = 0) LOOP
      BEGIN
        LC_YDOBJECT :='出口报关单';

        IF LSF_XX.BYTSBZ='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_BYTS','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']已被标注为“不予退税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        LN_CMCD_LEN := CASE WHEN LENGTH(LSF_XX.CKSP_DM_SB) > LENGTH(LSF_XX.CKSP_DM_SH) THEN LENGTH(LSF_XX.CKSP_DM_SH) ELSE LENGTH(LSF_XX.CKSP_DM_SB) END;
        IF SUBSTR(LSF_XX.CKSP_DM_SB,1,LN_CMCD_LEN)<>SUBSTR(LSF_XX.CKSP_DM_SH,1,LN_CMCD_LEN) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_SPDM','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']商品代码[' || LSF_XX.CKSP_DM_SB || ']与电子信息中[' || LSF_XX.CKSP_DM_SH || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.CKSL_SB > LSF_XX.CKSL + 1) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_CKSL','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']申报退税数量[' || LSF_XX.CKSL_SB || ']超过电子信息中出口数量[' || LSF_XX.CKSL || ']！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF (LSF_XX.CKSL_SB > LSF_XX.SYSL_SH + 1) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_CKSL','I',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']申报退税数量[' || LSF_XX.CKSL_SB || ']超过电子信息中剩余数[' || LSF_XX.SYSL_SH ||
                      ']（其中出口[' || LSF_XX.CKSL || ']退税申报[' || LSF_XX.TSSBSL || ']退运[' || LSF_XX.TYSL || ']代理申报[' || LSF_XX.DLSBSL || ']）！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF (ABS(LSF_XX.MYLAJ_SB-LSF_XX.MYLAJ_JS)>1 AND ABS(LSF_XX.MYLAJ_SB-LSF_XX.MYLAJ_JS)>0.05 * LSF_XX.MYLAJ_JS) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_USDLAJ','I',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']美元离岸价[' || LSF_XX.MYLAJ_SB || ']超过电子信息中合理范围，其中剩余数量[' || LSF_XX.SYSL_SH ||
                      ']，剩余美元离岸价[' || LSF_XX.MYLAJ_SH || ']，本次申报数量[' || LSF_XX.CKSL_SB || ']！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        --1退运; 2改单; 3撤单
        IF LSF_XX.TYYBSWTSTYLX_DM='3' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_CD','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']曾办理过用途为”撤单“的有效的退运证明！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF (LSF_XX.TYYBSWTSTYLX_DM='2' AND LSF_XX.GDBZ_1<>'Y' AND LSF_XX.CKBGDH_GD IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_GD','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']曾办理过用途为“改单”的有效的退运证明，且在“海关出口报关单改单数据”中不存在！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (TRIM(LSF_XX.JGFS_DM) IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_MYXZ_BCZ','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']在电子信息中监管方式不存在！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSE
          IF (TRIM(LSF_XX.JGFSTSLX_DM)='0') THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_MYXZ_BTS','E',
                        '出口货物报关单号[' || LSF_XX.CKBGDH || ']在电子信息中监管方式[' || LSF_XX.JGFS_DM || ']不退税！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;
        END IF;

        IF LSF_XX.ZZMDGDQSZ_DM<>'142' AND INSTR(LSF_XX.CKTMSYWLXDMJH,'LMYCL')>0 THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_LMYCL_ZZMDG','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']贸易国别非中国，“业务类型”不应包含“LMYCL”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'QYGTS')>0) THEN
          BEGIN
            IF (LSF_XX.CKRQ_SB<>LSF_XX.QYRQ_SH) AND (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')=0) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_CKRQ','E',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']出口日期[' || TO_CHAR(LSF_XX.CKRQ_SB,'YYYY-MM-DD') || ']与电子信息中[' || TO_CHAR(LSF_XX.QYRQ_SH,'YYYY-MM-DD') || ']不一致！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
            IF LSF_XX.QYGBZ<>'Y' THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_QYGTS_NOT','E',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']非启运港业务，“业务类型”不应包含“QYGTS”！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            ELSE
              BEGIN
                IF LSF_XX.QYGCXCKBZ='Y' THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                              'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_QYGTS_CXCK','E',
                              '出口货物报关单号[' || LSF_XX.CKBGDH || ']为启运港业务，已经撤销出口！','N',SYSDATE
                         FROM DUAL;
                  COMMIT;
                END IF;
                LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LSF_XX.QYRQ_SH,LC_FLGLCD);
                IF (LC_FLGLCD<>'A' AND LC_FLGLCD<>'B') THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                              'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_QYGTS_FLGLCD','E',
                              '出口货物报关单号[' || LSF_XX.CKBGDH || ']启运日当天该企业分类管理类别非一、二类，“业务类型”不应包含“QYGTS”！','N',SYSDATE
                         FROM DUAL;
                  COMMIT;
                END IF;
                IF MONTHS_BETWEEN(TRUNC(SYSDATE),LSF_XX.QYRQ_SH)>2 THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                              'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_QYGTS_CKRQ','E',
                              '出口货物报关单号[' || LSF_XX.CKBGDH || ']超过启运日两月，“业务类型”不应包含“QYGTS”！','N',SYSDATE
                         FROM DUAL;
                  COMMIT;
                END IF;
                IF LSF_XX.QYGWDDBZ='Y' THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                              'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_QYGTS_WDD','E',
                              '出口货物报关单号[' || LSF_XX.CKBGDH || ']未实际到达离境港，“业务类型”不应包含“QYGTS”！','N',SYSDATE
                         FROM DUAL;
                  COMMIT;
                END IF;
              END;
            END IF;
          END;
        ELSE
          BEGIN
            IF (LSF_XX.CKRQ_SB<>LSF_XX.CKRQ_SH) AND (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')=0) THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_CKRQ','E',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']出口日期[' || TO_CHAR(LSF_XX.CKRQ_SB,'YYYY-MM-DD') || ']与电子信息中[' || TO_CHAR(LSF_XX.CKRQ_SH,'YYYY-MM-DD') || ']不一致！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
            IF (LSF_XX.QYGBZ='Y' AND LSF_XX.QYGZCJGBZ='N') THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_QYGTS_NULL','E',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']为启运港业务，目前尚未收到结关信息，“业务类型”应包含“QYGTS”！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
          END;
        END IF;

        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'DWCB')>0 AND LSF_XX.JGFS_DM<>'3422' AND LSF_XX.JGFS_DM<>'22') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_DWCB_NOT','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']非对外承包业务，“业务类型”不应包含“DWCB”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'DWCB')=0 AND (LSF_XX.JGFS_DM='3422' OR LSF_XX.JGFS_DM='22')) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_DWCB_NULL','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为对外承包业务，“业务类型”应包含“DWCB”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')>0 THEN
          IF LSF_XX.YSFS_DM<>'0' THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_BSQ_NOT','E',
                        '出口货物报关单号[' || LSF_XX.CKBGDH || ']非经保税区出口业务，“业务类型”不应包含“BSQ”！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          ELSE
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_BSQ_BAQD','I',
                        '出口货物报关单号[' || LSF_XX.CKBGDH || ']业务类型包含保税区BSQ，请核实是否附送《出境货物备案清单》！','Y',SYSDATE
                   FROM DUAL;
            COMMIT;
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_BSQ_BANR','I',
                        '出口货物报关单号[' || LSF_XX.CKBGDH || ']业务类型包含保税区BSQ，请核实出境货物备案清单的内容是否与报关单相关内容相符,出口日期填报是否准确！','Y',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;
        END IF;
        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')=0 AND LSF_XX.YSFS_DM='0') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_BSQ_NULL','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为经保税区出口业务，“业务类型”应包含“BSQ”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF INSTR(LSF_XX.CKTMSYWLXDMJH,'RZZL')>0 THEN
          BEGIN
            LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'RZZL',LSF_XX.CKRQ_SH,LC_KZXX);
            IF LN_CPCODEKZ=0 THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_RZZL_ZG','E',
                          '企业备案扩展信息中未做融资租赁备案，“业务类型”不应包含“RZZL”！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
            IF LSF_XX.JGFS_DM<>'1523' THEN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_RZZL_NOT','E',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']非融资租赁业务，“业务类型”不应包含“RZZL”！','N',SYSDATE
                     FROM DUAL;
              COMMIT;
            END IF;
          END;
        ELSE
          IF LSF_XX.JGFS_DM='1523' THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_RZZL_NOT','E',
                        '出口货物报关单号[' || LSF_XX.CKBGDH || ']为融资租赁业务，“业务类型”应包含“RZZL”！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;
        END IF;

        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'JWTZ')>0 AND LSF_XX.JGFS_DM<>'2210') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_JWTZ_NOT','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']非境外投资业务，“业务类型”不应包含“JWTZ”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'JWTZ')=0 AND LSF_XX.JGFS_DM='2210') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_JWTZ_NULL','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为境外投资业务，“业务类型”应包含“JWTZ”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'DWYZ')>0 AND LSF_XX.JGFS_DM<>'3511') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_DWYZ_NOT','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']非对外援助业务，“业务类型”不应包含“DWYZ”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'DWYZ')=0 AND LSF_XX.JGFS_DM='3511') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_DWYZ_NULL','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为对外援助业务，“业务类型”应包含“DWYZ”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'XLXP')>0 AND LSF_XX.JGFS_DM<>'1300') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_XLXP_NOT','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']非修理修配业务，“业务类型”不应包含“XLXP”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'XLXP')=0 AND LSF_XX.JGFS_DM='1300') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_BGD_XLXP_NULL','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为修理修配业务，“业务类型”应包含“XLXP”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.YSFS_DM='T' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSSB_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_CKMX_CKPZH_YSFS','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为出口到综合试验区（横琴平潭地区）的报关单！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;

      --2020.11.11 增加关联号下进货、出口的商品名称、计量单位校验
      LC_YDOBJECT :='增值税发票';
      BEGIN
        FOR LSF_YY IN (SELECT A.SBXH, A.GLH, A.JHPZH FROM CKTS_SB_MTS_TSJH_LSB A WHERE A.SBID=V_IN_SBID AND A.GLH=LSF_XX.GLH AND A.CKTMSPZLX_DM='02') LOOP
          BEGIN
            SELECT COUNT(1)
              INTO LN_MXROW
              FROM CKTS_WBSJ_FP_ZZSFPHWXX B
             WHERE B.DJXH=V_IN_DJXH AND B.JHPZH=LSF_YY.JHPZH;
            IF LN_MXROW>0 THEN
              BEGIN
                SELECT DISTINCT B.JLDWMC
                  INTO LC_JHPZHJLDW
                  FROM CKTS_WBSJ_FP_ZZSFPHWXX B
                 WHERE B.DJXH=V_IN_DJXH AND B.JHPZH=LSF_YY.JHPZH AND B.GFHHWHYSLWMC=LSF_XX.GFHHGSPMC;

                IF FUNC_XXBD_CHECK_JLDW(LC_JHPZHJLDW,LSF_XX.DYJLDW_DM)=0 AND FUNC_XXBD_CHECK_JLDW(LC_JHPZHJLDW,LSF_XX.DEJLDW_DM)=0 AND FUNC_XXBD_CHECK_JLDW(LC_JHPZHJLDW,LSF_XX.SBJLDW_DM)=0 THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                              'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_YY.SBXH,LSF_YY.GLH,'MTS_JHMX_ZZSFP_JLDW_BGD','I',
                              '增值税专用发票[' || LSF_YY.JHPZH || ']的计量单位[' || LC_JHPZHJLDW || ']与出口报关单计量单位不符，请核对确认！','Y',SYSDATE
                         FROM DUAL;
                  COMMIT;
                END IF;
              EXCEPTION
                WHEN NO_DATA_FOUND THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                              'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_YY.SBXH,LSF_YY.GLH,'MTS_JHMX_ZZSFP_SPMC_BGD','I',
                              '增值税专用发票[' || LSF_YY.JHPZH || ']商品名称与出口报关单商品名称[' || LSF_XX.GFHHGSPMC || ']不一致，请核对确认！','Y',SYSDATE
                         FROM DUAL;
                  COMMIT;
                WHEN TOO_MANY_ROWS THEN
                  INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                       SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                              'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_YY.SBXH,LSF_YY.GLH,'MTS_JHMX_ZZSFP_SPMC_JLDW','I',
                              '增值税专用发票[' || LSF_YY.JHPZH || ']存在同一商品名称[' || LSF_XX.GFHHGSPMC || ']但计量单位不同的情形，请核对确认！','Y',SYSDATE
                         FROM DUAL;
                  COMMIT;
                WHEN OTHERS THEN
                  CONTINUE;
              END;
            END IF;
          END;
        END LOOP;
      END;
    END LOOP;
  END;
END;
/
