CREATE OR REPLACE PROCEDURE PROC_XXBD_MDT_CKSH
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
  修改日期：20220615，根据2022年9号公告，四类企业，需提供银行水单企业收汇情况表必须申报本期出口退税，非上述企业改为提示性疑点
  修改日期：20230207，修改代理证明出口申报收汇表的疑点逻辑和提示
  调整日期：20230313，增加MDT_BJGX_SHZL_CKHW_CJBZ、MDT_BJGX_SHZL_CKHW_CJJE的疑点判断
  调整日期：20230526，币种不一致、折人民币不一致疑点改成错误类，不可挑过。
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LC_KZXX         VARCHAR2(20);
  LDT_TODAY       DATE;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  --收汇明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_CKSH_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  LC_YDOBJECT :='出口收汇';
  BEGIN
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TGSHZL',LDT_TODAY,LC_KZXX);
    IF (LC_FLGLCD='D') OR (LN_CPCODEKZ>0) THEN
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_MDT_CKSH_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_SHZL_CKHW_CKPZ','E',
                    '出口货物报关单号/代理出口货物证明号[' || NVL(T.DLCKHWZMHM,T.CKBGDH) || ']未申报退税！','N',SYSDATE
               FROM CKTS_SB_MDT_CKSH_LSB T
              WHERE T.SBID=V_IN_SBID
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MDT_TSSB_LSB S WHERE S.SBID=T.SBID AND NVL(S.DLCKHWZMHM,S.CKBGDH)=NVL(T.DLCKHWZMHM,T.CKBGDH));
        COMMIT;
      END;
    ELSE
      BEGIN
        INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
             SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                    'CKTS_SB_MDT_CKSH_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_SHZL_CKHW_CKPZ','I',
                    '出口货物报关单号/代理出口货物证明号[' || NVL(T.DLCKHWZMHM,T.CKBGDH) || ']本期未申报退税！','Y',SYSDATE
               FROM CKTS_SB_MDT_CKSH_LSB T
              WHERE T.SBID=V_IN_SBID
                AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MDT_TSSB_LSB S WHERE S.SBID=T.SBID AND NVL(S.DLCKHWZMHM,S.CKBGDH)=NVL(T.DLCKHWZMHM,T.CKBGDH));
        COMMIT;
      END;
    END IF;
    FOR LSF_XX IN (SELECT A.SBXH,
                          A.CKBGDH AS CKPZH,
                          A.CJHBZM_DM,
                          E.HBZL_DM,
                          A.CKXSERMB,
                          B.RMBLAJ
                     FROM CKTS_SB_MDT_CKSH_LSB A
                    INNER JOIN CKTS_SB_MDT_TSSB_LSB B ON B.SBID=A.SBID AND B.CKBGDH = A.CKBGDH AND B.RMBLAJ>0
                    INNER JOIN CKTS_WBSJ_HG_BGD201 D ON D.DJXH=V_IN_DJXH AND D.CKBGDH=A.CKBGDH
                    INNER JOIN DM_HBZL_HG E ON E.HBZL_HG=D.CJHGHBSZ_DM
                    WHERE A.SBID=V_IN_SBID AND A.DLCKHWZMHM IS NULL) LOOP
      BEGIN
        IF LSF_XX.CJHBZM_DM<>LSF_XX.HBZL_DM THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MDT_CKSH_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,LSF_XX.SBXH,NULL,'MDT_BJGX_SHZL_CKHW_CJBZ','E',
                      '出口货物报关单号/代理出口货物证明号[' || LSF_XX.CKPZH || ']的出口退（免）税销售额币种[' || LSF_XX.CJHBZM_DM || ']与电子信息中的币制[' || LSF_XX.HBZL_DM || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
        IF LSF_XX.CKXSERMB<>LSF_XX.RMBLAJ THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MDT_CKSH_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,LSF_XX.SBXH,NULL,'MDT_BJGX_SHZL_CKHW_CJJE','E',
                      '出口货物报关单号/代理出口货物证明号[' || LSF_XX.CKPZH || ']的出口退（免）税销售额折人民币[' || LSF_XX.CKXSERMB || ']与免抵退税明细表中出口销售额人民币[' || LSF_XX.RMBLAJ || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;    
    FOR LSF_XX IN (SELECT A.SBXH,
                          A.DLCKHWZMHM AS CKPZH,
                          A.CJHBZM_DM,
                          E.HBZL_DM,
                          A.CKXSERMB,
                          B.RMBLAJ
                     FROM CKTS_SB_MDT_CKSH_LSB A
                    INNER JOIN CKTS_SB_MDT_TSSB_LSB B ON B.SBID=A.SBID AND B.DLCKHWZMHM=A.DLCKHWZMHM AND B.RMBLAJ>0
                    INNER JOIN CKTS_WBSJ_ZJ_DLCKHWZM D ON D.DJXH=V_IN_DJXH AND D.DLCKHWZMHM=A.DLCKHWZMHM
                    INNER JOIN DM_HBZL_HG E ON E.HBZL_HG=D.CJHGHBSZ_DM
                    WHERE A.SBID=V_IN_SBID AND A.DLCKHWZMHM IS NOT NULL) LOOP
      BEGIN
        IF LSF_XX.CJHBZM_DM<>LSF_XX.HBZL_DM THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MDT_CKSH_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,LSF_XX.SBXH,NULL,'MDT_BJGX_SHZL_CKHW_CJBZ','E',
                      '出口货物报关单号/代理出口货物证明号[' || LSF_XX.CKPZH || ']的出口退（免）税销售额币种[' || LSF_XX.CJHBZM_DM || ']与电子信息中的币制[' || LSF_XX.HBZL_DM || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
        IF LSF_XX.CKXSERMB<>LSF_XX.RMBLAJ THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MDT_CKSH_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,LSF_XX.SBXH,NULL,'MDT_BJGX_SHZL_CKHW_CJJE','E',
                      '出口货物报关单号/代理出口货物证明号[' || LSF_XX.CKPZH || ']的出口退（免）税销售额折人民币[' || LSF_XX.CKXSERMB || ']与免抵退税明细表中出口销售额人民币[' || LSF_XX.RMBLAJ || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;    
  END;
END;
/
