CREATE OR REPLACE PROCEDURE PROC_XXBD_MTS_TSJH_JKXFS
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  调整日期：20210603，1、调整疑点关联业务字段，关联号+申报序号
  调整日期：20211019，1、增加MTS_JHMX_JKXFS_GHFNSR疑点判断，海关进口税收凭证填写缴款单位纳税人识别号
  调整日期：20211208，1、调整免退税疑点描述字段中申报序号与关联单证号的顺序，使其与客户端疑点展示一致
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LC_KZXX         VARCHAR2(20);
  LDT_TODAY       DATE;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  --进口消费税缴款书记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_TSJH_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.CKTMSPZLX_DM='05';
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  LC_YDOBJECT :='进口消费税';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,T.SBXH,T.GLH,'MTS_JHMX_JKXFS_WDZXX','E','海关进口消费税缴款书[' || T.JHPZH || ']无电子信息！','N',SYSDATE
           FROM CKTS_SB_MTS_TSJH_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.CKTMSPZLX_DM='05'
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_HG_JKJKS S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.HGZYJKSHM=T.JHPZH);
    COMMIT;
  END;

  BEGIN
    FOR LSF_XX IN (SELECT A.SBXH,A.GLH,
                          A.JHPZH,
                          A.GHFNSRSBH_1,
                          B.BYTSBZ,
                          B.HGJKJKSCLJG_DM,
                          B.NSRSBH
                     FROM CKTS_SB_MTS_TSJH_LSB A
                    INNER JOIN CKTS_WBSJ_HG_JKJKS B ON B.DJXH=V_IN_DJXH AND B.HGZYJKSHM=A.JHPZH
                    WHERE A.SBID=V_IN_SBID
                      AND A.CKTMSPZLX_DM='05') LOOP
      BEGIN
        IF LSF_XX.BYTSBZ='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_JKXFS_BYTS','E','海关进口消费税缴款书[' || LSF_XX.JHPZH || ']已被标注为“不予退税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.HGJKJKSCLJG_DM IN ('100','500') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_JKXFS_DUP','E','海关进口消费税缴款书[' || LSF_XX.JHPZH || ']在电子信息中重复申请退税！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
        
        IF LSF_XX.GHFNSRSBH_1<>LSF_XX.NSRSBH THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_TSJH_LSB',NULL,NULL,LSF_XX.SBXH,LSF_XX.GLH,'MTS_JHMX_JKXFS_GHFNSR','E','海关进口消费税缴款书[' || LSF_XX.JHPZH || ']供货方纳税人[' || LSF_XX.GHFNSRSBH_1 || ']与电子信息中[' || LSF_XX.NSRSBH || ']不一致！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;
END;
/
