CREATE OR REPLACE PROCEDURE PROC_XXBD_GJ_ZZSFP
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（购进自用货物免退税）
  调整日期：20201221，1、根据宁波加工区内退水电气大部分为小规模以及研发中心退国产设备政策第十三条，非增值税一般纳税人允许申报购进自用货物退税，对涉及一般纳税人资格的疑点进行调整
                      2、有关GJZY_BJGX_ZG_SDQ、GJZY_BJGX_ZG_GCSB这两个疑点的判断改成用当前日期，取消开票日期的判断
  调整日期：20201230，1、校验发票稽核信息时，剔除代开发票的稽核信息，代开发票开票人税号含DK
  调整日期：20220701，1、根据全电票规则调整发票的关联，用JHPZH代替FPDM+FPHM
  调整日期：20230207，1、修改全电发票关联虚开发票时的BUG。
  调整日期：20230315，调整出口企业首次申报日期取数口径，改为按税务机关+企业+业务代码查询首次发放日期
  调整日期：20230317，根据钱塘区项灵燕反应有企业发票重复申报进金三重复退税的问题，增加总量控制疑点
  调整日期：20230515，解决增值税发票外部数据部分数据稽核相符标志为空的问题（赋默认值N）
  调整日期：20230518，解决按税务机关+企业+业务代码查询首次发放日期有结果但日期为空的问题（赋默认值SYSDATE）
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LN_CPCODEKZ1    NUMBER(10);
  LC_KZXX         VARCHAR2(20);
  LC_FLGLCD       VARCHAR2(20);
  LDT_TODAY       DATE;
  LDT_SCSBRQ      DATE;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  --购进自用货物发票记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_GJ_SBMX_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  --查询企业首次申报日期
  BEGIN
    SELECT NVL(T.FFRQ,SYSDATE)
      INTO LDT_SCSBRQ
      FROM CKTS_TY_YWBLXX_SCFFRQ T
     WHERE T.TSSWJG_DM_1=(SELECT SWJG_DM FROM GS_DJ_CKTMSDAB WHERE NSRDZDAH=V_IN_NSRDZDAH)
       AND T.DJXH=V_IN_DJXH AND T.LCSWSX_DM='LCSXA081042002';
  EXCEPTION
    WHEN OTHERS THEN
      LDT_SCSBRQ:=LDT_TODAY;
  END;

  LC_YDOBJECT :='购进自用';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_ZZSFP_WDZXX','E','进货凭证号码[' || T.JHPZH || ']无电子信息！','N',SYSDATE
           FROM CKTS_SB_GJ_SBMX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.JHPZZL_DM='1'
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_FP_ZZSZYFPXX S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.JHPZH=T.JHPZH);
    COMMIT;
  END;

  BEGIN
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
    FOR LSF_XX IN (SELECT A.SBXH,
                          NVL(A.CKTMSYWLXDMJH,' ') AS CKTMSYWLXDMJH,
                          A.JHPZH,
                          TRUNC(A.KPRQ,'DD') AS KPRQ_SB,
                          TRUNC(B.KPRQ,'DD') AS KPRQ_SH,
                          A.GHFNSRSBH_1,
                          B.XFNSRSBH,
                          NVL(B.JHXFZZSZYFPBZ,'N') AS JHXFZZSZYFPBZ,
                          B.BYTSBZ,
                          B.FPYT_DM,
                          NVL(B.FPSJBBZ,'N') AS FPSJBZ,
                          NVL(B.NXZCKBZ,'N') AS NXZCKBZ,
                          C.GHFNSRSBH,
                          A.JSJE,
                          B.JE - NVL(B.HZCJJE,0) - NVL(B.SBFPJSJE,0) - NVL(B.LSLSBFPJSJE,0) AS SYJE,
                          A.TSE,
                          B.SE
                     FROM CKTS_SB_GJ_SBMX_LSB A
                    INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX B ON B.DJXH=V_IN_DJXH AND B.JHPZH=A.JHPZH
                     LEFT JOIN CKTS_WBSJ_ZJ_XKFP C ON C.FP_DM||C.FPHM=A.JHPZH
                    WHERE A.SBID=V_IN_SBID
                      AND A.JHPZZL_DM='1') LOOP
      BEGIN
        --20230317，根据钱塘区项灵燕反应有企业发票重复申报进金三重复退税的问题，增加总量控制疑点
        IF (LSF_XX.JSJE > LSF_XX.SYJE) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'GJZY_JHMX_ZZSFP_SBJE','I',
                      '进货凭证号码[' || LSF_XX.JHPZH || ']申报退税的计税金额[' || LSF_XX.JSJE || ']超过电子信息中剩余数[' || LSF_XX.SYJE ||']，请检查是否重复申报！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF (LSF_XX.TSE > LSF_XX.SE) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'GJZY_JHMX_ZZSFP_SBSE','E',
                      '进货凭证号码[' || LSF_XX.JHPZH || ']申报退税额[' || LSF_XX.TSE || ']超过电子信息中税额[' || LSF_XX.SE ||']！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
        
        IF (LSF_XX.JHXFZZSZYFPBZ='N' AND INSTR(LSF_XX.CKTMSYWLXDMJH,'GCSB')>0 AND INSTR(LSF_XX.XFNSRSBH,'DK')=0 AND (LC_FLGLCD='D' OR (LC_FLGLCD='C' AND MONTHS_BETWEEN(LDT_TODAY,LDT_SCSBRQ)<=12))) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'GJZY_JHMX_ZZSFP_WDZXX','E','进货凭证号码[' || LSF_XX.JHPZH || ']无稽核相符电子信息！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.BYTSBZ='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'GJZY_JHMX_ZZSFP_BYTS','E','进货凭证号码[' || LSF_XX.JHPZH || ']已被标注为“不予退税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.GHFNSRSBH_1<>LSF_XX.XFNSRSBH THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'GJZY_JHMX_ZZSFP_GHFNSR','E','进货凭证号码[' || LSF_XX.JHPZH || ']供货方纳税人[' || LSF_XX.GHFNSRSBH_1 || ']与电子信息中[' || LSF_XX.XFNSRSBH || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.KPRQ_SB<>LSF_XX.KPRQ_SH THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_ZZSFP_KPRQ','E','进货凭证号码[' || LSF_XX.JHPZH || ']开票日期[' || TO_CHAR(LSF_XX.KPRQ_SB,'YYYY-MM-DD') || ']与电子信息中[' || TO_CHAR(LSF_XX.KPRQ_SH,'YYYY-MM-DD') || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.FPYT_DM='3' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_ZZSFP_DBTS','E','进货凭证号码[' || LSF_XX.JHPZH || ']在电子信息中申报用途代码为“3-代办退税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
        IF (LSF_XX.FPYT_DM='1' AND LSF_XX.FPSJBZ='Y' AND LSF_XX.NXZCKBZ='N') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_ZZSFP_YDK','E','进货凭证号码[' || LSF_XX.JHPZH || ']在电子信息中已勾选用于抵扣！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.GHFNSRSBH IS NOT NULL THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'WZF_DBTS_ZZSFP_XKFP','E','进货凭证号码[' || LSF_XX.JHPZH || ']在电子信息中为虚开增值税专用发票！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_CKYWLX_GCSB_PTFP','E','申报的增值税普通发票[' || T.JHPZH ||']开票日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']不符合申报条件，请检查确认！','N',SYSDATE
           FROM CKTS_SB_GJ_SBMX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND INSTR(T.CKTMSYWLXDMJH,'GCSB')>0
            AND T.JHPZZL_DM='2'
            AND FUNC_XXBD_CHECK_GCSBKPRQ(T.KPRQ)=0;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_NSRZG','I','开票日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业非增值税一般纳税人，请确认是否符合退税政策！','Y',SYSDATE
           FROM CKTS_SB_GJ_SBMX_LSB T
           LEFT JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='YBNSRRD' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND INSTR(T.CKTMSYWLXDMJH,'GCSB')>0
            AND S.KZLX IS NULL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_TQQY','E','开票日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于出口退税停权期间！','N',SYSDATE
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TQQY' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_MSQY','E','开票日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于免税期间！','N',SYSDATE
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSGMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_FQTS','E','开票日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于放弃退（免）税权选择免税期间！','N',SYSDATE
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_FQTS','E','开票日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于放弃退（免）税权选择征税期间！','N',SYSDATE
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXZS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_JHMX_KPRQ_FQTS','E','开票日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于放弃退（免）税权期间！','N',SYSDATE
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'GJZY_BJGX_KZ_SDQ','E','出口业务类型为“水电气”，开票日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业属于“海关特殊监管区域内的试点企业”！','N',SYSDATE
           FROM CKTS_SB_GJ_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSQYYBNSRSDQY' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND INSTR(T.CKTMSYWLXDMJH,'SDQ')>0;
    COMMIT;
  END;

  BEGIN
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'SDQ',LDT_TODAY,LC_KZXX);
    IF LN_CPCODEKZ=0 THEN
      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                  'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,NULL,NULL,'GJZY_BJGX_ZG_SDQ','E','出口业务类型为“水电气”，企业备案出口退（免）税管理类型未勾选“特殊区域内申报水电气退税业务的生产企业”！','N',SYSDATE
             FROM DUAL
            WHERE EXISTS (SELECT 1
                            FROM CKTS_SB_GJ_SBMX_LSB T
                           WHERE T.SBID=V_IN_SBID
                             AND INSTR(T.CKTMSYWLXDMJH,'SDQ')>0);
      COMMIT;
    END IF;

    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'NZYFJG',LDT_TODAY,LC_KZXX);
    LN_CPCODEKZ1:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'WZYFJG',LDT_TODAY,LC_KZXX);
    IF LN_CPCODEKZ=0 AND LN_CPCODEKZ1=0 THEN
      INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                  'CKTS_SB_GJ_SBMX_LSB',NULL,NULL,NULL,NULL,'GJZY_BJGX_ZG_GCSB','E','出口业务类型为“国产设备”，企业备案出口退（免）税管理类型未勾选“内资研发机构”或“外资研发中心”！','N',SYSDATE
             FROM DUAL
            WHERE EXISTS (SELECT 1
                            FROM CKTS_SB_GJ_SBMX_LSB T
                           WHERE T.SBID=V_IN_SBID
                             AND INSTR(T.CKTMSYWLXDMJH,'GCSB')>0);
      COMMIT;
    END IF;
  END;
END;
/
