CREATE OR REPLACE PROCEDURE PROC_XXBD_CHECK_SBB
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对统一入口
  修改日期：20220524，根据2022年9号公告，增加备案变更、备案撤回的直接返回（实际比对在java中进行）
  修改日期：20220615，根据2022年9号公告，取消非需收汇企业视同收汇申报、外综服企业代办退税备案
  修改日期：20220909，增加退税贷企业变更银行账号的控制需求
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  BEGIN
    IF V_IN_SBYWBDM ='A0301001' THEN
      PROC_XXBD_MTS(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0302001' THEN
      PROC_XXBD_XFS(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0303001' THEN
      PROC_XXBD_JSB(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0304001' THEN
      PROC_XXBD_GJ(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0305001' THEN
      PROC_XXBD_MDT(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0310001' THEN
      PROC_XXBD_WZF(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0404001' THEN -- 非需收汇企业视同收汇申报，根据2022年9号公告取消
      RETURN;

    ELSIF V_IN_SBYWBDM ='A0201001' THEN
      PROC_XXBD_TSZM_DLCKHWZM(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0201002' THEN -- 代理进口证明，金三所有疑点要求都暂时取消了
      RETURN;
    ELSIF V_IN_SBYWBDM ='A0201003' THEN -- 委托出口证明，原来通过java实现，为后续运维方便改存储过程
      PROC_XXBD_TSZM_WTCKHWZM(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0201004' THEN
      PROC_XXBD_TSZM_CKHWZNXZM(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0201005' THEN
      PROC_XXBD_TSZM_TYYBSWTS(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0203001' THEN
      PROC_XXBD_MSZM_LLJGHX(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0203002' THEN
      PROC_XXBD_MSZM_LLJG(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0202001' THEN -- 补办有关证明，仅需要服务端完成证明种类和证明编号的有效性校验
      RETURN;
    ELSIF V_IN_SBYWBDM ='Z0202002' THEN -- 作废有关证明，仅需要服务端完成证明种类和证明编号的有效性校验
      RETURN;

    ELSIF V_IN_SBYWBDM ='A0102001' THEN --备案变更，仅需要服务端完成有效性校验
      PROC_XXBD_ZG_CKTMSBABG(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0103001' THEN --备案撤回，仅需要服务端完成有效性校验
      RETURN;
    ELSIF V_IN_SBYWBDM ='A0109001' THEN -- 委托代办退税情况备案申请
      PROC_XXBD_ZG_SCWTDBBA(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0109002' THEN -- 委托代办退税情况备案撤回
      PROC_XXBD_ZG_SCWTDBCH(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSIF V_IN_SBYWBDM ='A0110001' THEN -- 代办退税情况备案申请，根据2022年9号公告取消
      RETURN;
    ELSIF V_IN_SBYWBDM ='A0410001' THEN -- 进货凭证信息回退申请
      PROC_XXBD_JHPZHT(V_IN_NSRDZDAH,V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,V_OUT_STATUS,V_OUT_MESSAGE);
    ELSE
      V_OUT_STATUS :='03';
      V_OUT_MESSAGE:='本业务暂未开通申报自检服务！';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='04';
      V_OUT_MESSAGE:= SQLCODE||' : '||SQLERRM;
  END;

END;
/
