CREATE OR REPLACE PROCEDURE PROC_XXBD_XFS_TSSB_BGD
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（出口非自产货物退消费税）
  调整日期：20201119，1、调整改单报关单监控条件，由bgd202不存在改为bgd201.gdbz_1<>Y
  调整日期：20210113，1、调整改单报关单监控条件，改为bgd202不存在 且 bgd201.gdbz_1<>Y
  调整日期：20220720，1、增加疑点XFS_CKMX_BGD_CKRQ，报关单出口日期与电子信息不一致；
                      2、调整出口日期无退税资格疑点的口径，直接用企业申报的出口日期
  调整日期：20230313，增加XFS_CKMX_BGD_BSQ_BAQD、XFS_CKMX_BGD_BSQ_BANR疑点判断
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CMCD_LEN     NUMBER(10);
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  --报关单出口明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_FZC_SBMX_LSB T
     WHERE T.SBID=V_IN_SBID
       AND T.CKBGDH IS NOT NULL;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  LC_YDOBJECT :='出口报关单';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'XFS_CKMX_BGD_WDZXX','E',
                '出口货物报关单号[' || T.CKBGDH || ']无电子信息！','N',SYSDATE
           FROM CKTS_SB_FZC_SBMX_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.CKBGDH IS NOT NULL
            AND NOT EXISTS (SELECT 1 FROM CKTS_WBSJ_HG_BGD201 S WHERE S.DJXH=V_IN_DJXH AND S.CKBGDH=T.CKBGDH);
    COMMIT;
  END;

  BEGIN
    FOR LSF_XX IN (SELECT A.SBXH,
                          A.CKBGDH,
                          B.BYTSBZ,
                          A.CKSP_DM AS CKSP_DM_SB,
                          B.CKSP_DM AS CKSP_DM_SH,
                          TRUNC(A.KPRQ,'DD') AS CKRQ_SB,
                          TRUNC(B.CKRQ_1,'DD') AS CKRQ_SH,
                          TRUNC(B.QYRQ_2,'DD') AS QYRQ_SH,
                          D.TYYBSWTSTYLX_DM,
                          NVL(B.GDBZ_1,' ') AS GDBZ_1,
                          E.CKBGDH AS CKBGDH_GD,
                          C.JGFS_DM,
                          C.JGFSTSLX_DM,
                          B.YSFS_DM,
                          NVL(A.CKTMSYWLXDMJH,' ') AS CKTMSYWLXDMJH
                     FROM CKTS_SB_FZC_SBMX_LSB A
                    INNER JOIN CKTS_WBSJ_HG_BGD201 B ON B.DJXH=V_IN_DJXH AND B.CKBGDH=A.CKBGDH
                     LEFT JOIN CKTS_DM_HGJGFS C ON C.JGFS_DM=B.JGFS_DM
                     LEFT JOIN CKTS_JGB_ZM_TYYBSWTS D ON D.DJXH=V_IN_DJXH AND D.CKBGDH=A.CKBGDH AND NVL(D.ZFBZ_1,'N')='N'
                     LEFT JOIN CKTS_WBSJ_HG_BGD202 E ON D.DJXH=V_IN_DJXH AND E.CKBGDH=A.CKBGDH
                    WHERE A.SBID=V_IN_SBID
                      AND A.CKBGDH IS NOT NULL) LOOP
      BEGIN
        IF LSF_XX.BYTSBZ='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_BYTS','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']已被标注为“不予退税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        LN_CMCD_LEN := CASE WHEN LENGTH(LSF_XX.CKSP_DM_SB) > LENGTH(LSF_XX.CKSP_DM_SH) THEN LENGTH(LSF_XX.CKSP_DM_SH) ELSE LENGTH(LSF_XX.CKSP_DM_SB) END;
        IF SUBSTR(LSF_XX.CKSP_DM_SB,1,LN_CMCD_LEN)<>SUBSTR(LSF_XX.CKSP_DM_SH,1,LN_CMCD_LEN) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_SPDM','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']商品代码[' || LSF_XX.CKSP_DM_SB || ']与电子信息中[' || LSF_XX.CKSP_DM_SH || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'QYGTS')>0) THEN
          IF (LSF_XX.CKRQ_SB<>LSF_XX.QYRQ_SH) AND (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')=0) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_CKRQ','E',
                        '出口货物报关单号[' || LSF_XX.CKBGDH || ']出口日期[' || TO_CHAR(LSF_XX.CKRQ_SB,'YYYY-MM-DD') || ']与电子信息中[' || TO_CHAR(LSF_XX.QYRQ_SH,'YYYY-MM-DD') || ']不一致！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;
        ELSE
          IF (LSF_XX.CKRQ_SB<>LSF_XX.CKRQ_SH) AND (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')=0) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_CKRQ','E',
                        '出口货物报关单号[' || LSF_XX.CKBGDH || ']出口日期[' || TO_CHAR(LSF_XX.CKRQ_SB,'YYYY-MM-DD') || ']与电子信息中[' || TO_CHAR(LSF_XX.CKRQ_SH,'YYYY-MM-DD') || ']不一致！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;
        END IF;

        --1退运; 2改单; 3撤单
        IF LSF_XX.TYYBSWTSTYLX_DM='3' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_CD','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']曾办理过用途为”撤单“的有效的退运证明！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF (LSF_XX.TYYBSWTSTYLX_DM='2' AND LSF_XX.GDBZ_1<>'Y' AND LSF_XX.CKBGDH_GD IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_GD','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']曾办理过用途为“改单”的有效的退运证明，且在“海关出口报关单改单数据”中不存在！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (TRIM(LSF_XX.JGFS_DM) IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_MYXZ_BCZ','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']在电子信息中监管方式不存在！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF (TRIM(LSF_XX.JGFSTSLX_DM)='0') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_MYXZ_BTS','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']在电子信息中监管方式[' || LSF_XX.JGFS_DM || ']不退税！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.YSFS_DM='T' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_CKPZH_YSFS','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为出口到综合试验区（横琴平潭地区）的报关单！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')>0) THEN
          IF (LSF_XX.YSFS_DM<>'0') THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_BSQ_NOT','E','出口货物报关单号[' || LSF_XX.CKBGDH || ']非经保税区出口业务，“业务类型”不应包含“BSQ”！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          ELSE
            BEGIN
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_BSQ_BAQD','I',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']业务类型包含保税区BSQ，请核实是否附送《出境货物备案清单》！','Y',SYSDATE
                     FROM DUAL;
              COMMIT;
              INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                   SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                          'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_BSQ_BANR','I',
                          '出口货物报关单号[' || LSF_XX.CKBGDH || ']业务类型包含保税区BSQ，请核实出境货物备案清单的内容是否与报关单相关内容相符,出口日期填报是否准确！','Y',SYSDATE
                     FROM DUAL;
              COMMIT;
            END;
          END IF;
        END IF;
        IF (INSTR(LSF_XX.CKTMSYWLXDMJH,'BSQ')=0 AND LSF_XX.YSFS_DM='0') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'XFS_CKMX_BGD_BSQ_NULL','E',
                      '出口货物报关单号[' || LSF_XX.CKBGDH || ']为经保税区出口业务，“业务类型”应包含“BSQ”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'XFS_CKMX_CKRQ_NSRZG','E',
                '出口货物报关单号[' || T.CKBGDH || ']对应的出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业非增值税一般纳税人！','N',SYSDATE
           FROM CKTS_SB_FZC_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='YBNSRRD' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND S.KZLX IS NULL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'XFS_CKMX_CKRQ_TQQY','E',
                '出口货物报关单号[' || T.CKBGDH || ']对应的出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于出口退税停权期间！','N',SYSDATE
           FROM CKTS_SB_FZC_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TQQY' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'XFS_CKMX_CKRQ_MSQY','E',
                '出口货物报关单号[' || T.CKBGDH || ']对应的出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于免税期间！','N',SYSDATE
           FROM CKTS_SB_FZC_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSGMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'XFS_CKMX_CKRQ_FQTS','E',
                '出口货物报关单号[' || T.CKBGDH || ']对应的出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于放弃退（免）税权选择免税期间！','N',SYSDATE
           FROM CKTS_SB_FZC_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'XFS_CKMX_CKRQ_FQTS','E',
                '出口货物报关单号[' || T.CKBGDH || ']对应的出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于放弃退（免）税权选择征税期间！','N',SYSDATE
           FROM CKTS_SB_FZC_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTSSXZS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_FZC_SBMX_LSB',NULL,NULL,T.SBXH,NULL,'XFS_CKMX_CKRQ_FQTS','E',
                '出口货物报关单号[' || T.CKBGDH || ']对应的出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于放弃退（免）税权期间！','N',SYSDATE
           FROM CKTS_SB_FZC_SBMX_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQTMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;
  END;
END;
/
