CREATE OR REPLACE PROCEDURE PROC_XXBD_ZG_WZFDBTSBA
/*
  编制人:严国平
  编制日期:202010
  功能:信息比对（代办退税情况备案）
  修改日期：20210618，企业端提交的代办退税银行、账号未落地CKTS_BA_WMZHFWDBTS_LSB，增加对应字段接收数据并调整比对逻辑
  修改日期：20210830，BA_DBTS_WZF_YHXX_BYZ疑点拆分为两个，名称不一致的（有可能全称与简称的区别）可挑过，账号不一致的不可跳过
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LDT_TODAY       DATE;

  LC_QYHGDM       VARCHAR2(20);
  LC_QYLXDM       VARCHAR2(20);
  LC_TSJSFSDM     VARCHAR2(20);
  LC_WMZHFWQYBZ   VARCHAR2(20);
  LC_SFYSFW       VARCHAR2(20);
  LC_YSFW         VARCHAR2(50);
  LC_YSFS         VARCHAR2(50);
  LC_YFSJ         VARCHAR2(50);
  LC_ZXFLAG       VARCHAR2(20);
  LC_YHMC         VARCHAR2(200);
  LC_YHZH         VARCHAR2(100);
  LC_YDOBJECT     VARCHAR2(20);

  LN_CPCODEKZ     NUMBER(10);
  LC_KZXX         VARCHAR2(20);
  LC_FLGLCD       VARCHAR2(20);
  LN_ROWNUM_CKMX  NUMBER(10);
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  IF V_IN_SSSQ>TO_CHAR(SYSDATE,'YYYYMM') THEN
    BEGIN
      V_OUT_STATUS :='05';
      V_OUT_MESSAGE:='申报所属时期超出合理范围！';
      RETURN;
    END;
  END IF;

  --取各申报明细表数据记录
  BEGIN
    SELECT COUNT(1)
      INTO LN_ROWNUM_CKMX
      FROM CKTS_BA_WMZHFWDBTS_LSB
     WHERE SBID=V_IN_SBID;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='06';
      V_OUT_MESSAGE:='查询申报记录数据失败！';
      RETURN;
  END;
  IF LN_ROWNUM_CKMX=0 THEN
    BEGIN
      V_OUT_STATUS :='07';
      V_OUT_MESSAGE:='申报数据为空！';
      RETURN;
    END;
  END IF;

  --查询企业基本信息
  BEGIN
    SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG, T.YHMC, T.YHZH
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG, LC_YHMC, LC_YHZH
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='08';
      V_OUT_MESSAGE:='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
  END;
  IF LC_ZXFLAG='Y' THEN
    BEGIN
      V_OUT_STATUS :='09';
      V_OUT_MESSAGE:='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
    END;
  END IF;

  --取企业的FLGLCD信息, TGSHZL信息，判断是否需要申报收汇
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      V_OUT_STATUS :='10';
      V_OUT_MESSAGE:='查询出口企业分类管理类型出错！';
      RETURN;
    END;
  END IF;

  IF LC_QYLXDM<>'3' OR LC_TSJSFSDM<>'2' THEN
    BEGIN
      V_OUT_STATUS :='11';
      V_OUT_MESSAGE:='备案信息中企业类型、退免税计算方法与当前申报业务冲突！';
      RETURN;
    END;
  END IF;

  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'YBNSRRD',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      V_OUT_STATUS :='12';
      V_OUT_MESSAGE:='企业当前非增值税一般纳税人，不允许申报出口退（免）税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'TQQY',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 THEN
    BEGIN
      V_OUT_STATUS :='13';
      V_OUT_MESSAGE:='企业当前处于出口退税停权期间，不允许申报出口退（免）税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXMS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      V_OUT_STATUS :='14';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权选择免税期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTSSXZS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      V_OUT_STATUS :='15';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权选择征税期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FQTMS',LDT_TODAY,LC_KZXX);
  IF LN_CPCODEKZ=1 AND LN_ROWNUM_CKMX>0 THEN
    BEGIN
      V_OUT_STATUS :='16';
      V_OUT_MESSAGE:='企业当前处于放弃退（免）税权期间，不允许申报出口货物劳务免退税业务！';
      RETURN;
    END;
  END IF;

  LC_YDOBJECT:='代办备案';
  BEGIN
    FOR LSF_XX IN (SELECT A.SBXH, A.DBTSBALCZT_DM, A.WTDBTSSCQYNSRMC, A.WTDBTSSCQYHGQYDM, A.WTDBTSSCQYNSRSBH, A.TSKHYHMC AS WTDBTSSCQYDBTSKHYHMC, A.TSKHYHZH AS WTDBTSSCQYDBTSKHYHZH,
                          A.WMZHFWHTXYHM AS WMZHFWHTXYHM_NEW,
                          B.WMZHFWHTXYHM AS WMZHFWHTXYHM_OLD,
                          C.NSRSBH, C.NSRMC, C.TSKHYHMC, C.TSKHYHZH, C.WMZHFWHTXYHM AS WMZHFWHTXYHM_SC
                     FROM CKTS_BA_WMZHFWDBTS_LSB A
                     LEFT JOIN CKTS_JGB_BA_WMZHFWDBTS B ON B.DJXH=V_IN_DJXH AND (B.WTDBTSSCQYNSRSBH=A.WTDBTSSCQYNSRSBH OR B.WTDBTSSCQYSHXYDM=A.WTDBTSSCQYNSRSBH)
                     LEFT JOIN CKTS_WBSJ_ZJ_SCWTDBBA C ON C.DJXH=V_IN_DJXH AND (C.NSRSBH=A.WTDBTSSCQYNSRSBH OR C.SHXYDM=A.WTDBTSSCQYNSRSBH)
                    WHERE A.SBID=V_IN_SBID) LOOP
      BEGIN
        IF (LSF_XX.DBTSBALCZT_DM='1' AND LSF_XX.WMZHFWHTXYHM_OLD IS NOT NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_WZF_BAXX_DUP','E','生产企业[' || LSF_XX.WTDBTSSCQYNSRSBH || ']代办退税的备案信息已存在，请选择变更流程！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF(LSF_XX.DBTSBALCZT_DM='2' AND LSF_XX.WMZHFWHTXYHM_OLD IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_WZF_BAXX_NULL','E','生产企业[' || LSF_XX.WTDBTSSCQYNSRSBH || ']代办退税的备案信息不存在，请选择备案流程！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.NSRSBH IS NOT NULL) THEN
          IF TRIM(LSF_XX.WTDBTSSCQYNSRMC) <> TRIM(LSF_XX.NSRMC) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_WZF_BAXX_BYZ','E','生产企业[' || LSF_XX.WTDBTSSCQYNSRSBH || ']对应的名称与该企业委托代办备案信息不一致！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;

          IF (LSF_XX.WTDBTSSCQYDBTSKHYHZH<>LSF_XX.TSKHYHZH) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_WZF_YHXX_BYZ','E','生产企业[' || LSF_XX.WTDBTSSCQYNSRSBH || ']对应的退税银行账户与该企业委托代办备案信息不一致！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;

          IF (LSF_XX.WTDBTSSCQYDBTSKHYHMC <> LSF_XX.TSKHYHMC) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_WZF_YHXX_BYZ','E','生产企业[' || LSF_XX.WTDBTSSCQYNSRSBH || ']对应的退税银行名称与该企业委托代办备案信息不一致！','Y',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;

          IF (LSF_XX.WMZHFWHTXYHM_NEW <> LSF_XX.WMZHFWHTXYHM_SC) THEN
            INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
                 SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                        'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_WZF_HTXX_BYZ','E','生产企业[' || LSF_XX.WTDBTSSCQYNSRSBH || ']对应的代办退税协议与该企业委托代办备案信息不一致！','N',SYSDATE
                   FROM DUAL;
            COMMIT;
          END IF;
        ELSE
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_BA_WMZHFWDBTS_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'BA_DBTS_WZF_SCQYWBA','E','缺少生产企业[' || LSF_XX.WTDBTSSCQYNSRSBH || ']的委托代办备案信息！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;
END;
/
