CREATE OR REPLACE PROCEDURE PROC_XXBD_MDT_GJYS
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_IN_GJYSFW     IN  VARCHAR2, /*出口企业备案国际运输类应税服务类型代码*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LC_MSG          VARCHAR2(200):=' ';
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  --国际运输明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_GJYS_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;
  LC_YDOBJECT :='国际运输';

  FOR LSF_XX IN (SELECT * FROM CKTS_DM_GJYSFW A WHERE A.YXBZ='Y') LOOP
    BEGIN
      SELECT COUNT(1)
        INTO LN_MXROW
        FROM CKTS_SB_MDT_GJYS_LSB T
       WHERE T.SBID=V_IN_SBID AND T.YSFW_DM LIKE LSF_XX.GJYSFWJC||'%';
      IF LN_MXROW>0 AND INSTR(V_IN_GJYSFW,LSF_XX.GJYSFWDM)=0 THEN
        LC_MSG:=LC_MSG||LSF_XX.GJYSFWMC||',';
      END IF;
    END;
  END LOOP;
  IF LC_MSG<>' ' OR TRIM(LC_MSG) IS NOT NULL THEN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
     SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
            'CKTS_SB_MDT_GJYS_LSB',NULL,NULL,NULL,NULL,'MDT_BJGX_GJYS_SPDM','E','不允许申报未备案的国际运输服务[' || LC_MSG || ']。','N',SYSDATE
       FROM DUAL;
    COMMIT;
  END IF;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_GJYS_LSB','CKTS_SB_MDT_TLHY_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_GJYS_TLHY_SPDM','E','应提供国际联运运输收入的《清算资金通知清单》！','N',SYSDATE
           FROM CKTS_SB_MDT_GJYS_LSB T
          WHERE T.SBID=V_IN_SBID
            AND T.YSFW_DM IN ('9901300011','9901300012','9901300013')
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_SB_MDT_TLHY_LSB S
                             WHERE S.SBID=V_IN_SBID);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_GJYS_LSB',NULL,NULL,T.SBXH,NULL,'MDT_GJYS_CKRQ_NSRZG','E','出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业非增值税一般纳税人！','N',SYSDATE
           FROM CKTS_SB_MDT_GJYS_LSB T
           LEFT JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='YBNSRRD' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID
            AND S.KZLX IS NULL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_GJYS_LSB',NULL,NULL,T.SBXH,NULL,'MDT_GJYS_CKRQ_TQQY','E','出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于出口退税停权期间！','N',SYSDATE
           FROM CKTS_SB_MDT_GJYS_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TQQY' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_GJYS_LSB',NULL,NULL,T.SBXH,NULL,'MDT_GJYS_CKRQ_MSQY','E','出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']企业处于免税期间！','N',SYSDATE
           FROM CKTS_SB_MDT_GJYS_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='TSGMS' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_GJYS_LSB',NULL,NULL,T.SBXH,NULL,'MDT_GJYS_CKRQ_FQTS','E','出口日期[' || TO_CHAR(T.KPRQ,'YYYY-MM-DD') || ']放弃零税率应税服务退税期间！','N',SYSDATE
           FROM CKTS_SB_MDT_GJYS_LSB T
          INNER JOIN GS_DJ_CKTMSDAB_KZ S ON S.NSRDZDAH=V_IN_NSRDZDAH AND S.KZLX='FQLSL' AND S.FLAG='1' AND T.KPRQ BETWEEN S.ST_DATE AND S.END_DATE
          WHERE T.SBID=V_IN_SBID;
    COMMIT;
  END;
END;
/
