CREATE OR REPLACE PROCEDURE PROC_XXBD_TSZM_WTCKHWZM
/*
  编制人:严国平
  编制日期:202101
  功能:信息比对（委托出口货物证明）
  说明：其中TSZM_WTCK_SPDM_RANK提示性疑点电子税务局已实现，主要为了兼容离线版申报自检；
            TSZM_WTCK_DFDWSH_VALID疑点原来通过java代码实现，修改维护比较麻烦，改为存储过程实现。
  调整日期：20210715，1、调整疑点TSZM_WTCK_DFDWSH_VALID判断逻辑，先判断本地企业再判断全国备案信息
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LDT_TODAY    DATE;

  LC_QYHGDM       VARCHAR2(20);
  LC_QYLXDM       VARCHAR2(20);
  LC_TSJSFSDM     VARCHAR2(20);
  LC_WMZHFWQYBZ   VARCHAR2(20);
  LC_SFYSFW       VARCHAR2(20);
  LC_YSFW         VARCHAR2(50);
  LC_YSFS         VARCHAR2(50);
  LC_YFSJ         VARCHAR2(50);
  LC_ZXFLAG       VARCHAR2(20);

  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LN_ROWNUM_TSSB  NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  IF V_IN_SSSQ>TO_CHAR(SYSDATE,'YYYYMM') THEN
    BEGIN
      V_OUT_STATUS :='05';
      V_OUT_MESSAGE:='申报所属时期超出合理范围！';
      RETURN;
    END;
  END IF;

  --取各申报明细表数据记录
  BEGIN
    SELECT COUNT(1)
      INTO LN_ROWNUM_TSSB
      FROM CKTS_ZM_WTCK_LSB
     WHERE SBID=V_IN_SBID;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='06';
      V_OUT_MESSAGE:='查询申报记录数据失败！';
      RETURN;
  END;
  IF LN_ROWNUM_TSSB=0 THEN
    BEGIN
      V_OUT_STATUS :='07';
      V_OUT_MESSAGE:='申报数据为空！';
      RETURN;
    END;
  END IF;

  --查询企业基本信息
  BEGIN
    SELECT T.QYHGDM, T.QYLX_DM, T.TSJSFS_DM, T.WMZHFWQYBZ, T.SFYSFW, T.YSFW, T.YSFS, T.YFSJ, T.ZX_FLAG
      INTO LC_QYHGDM, LC_QYLXDM, LC_TSJSFSDM, LC_WMZHFWQYBZ, LC_SFYSFW, LC_YSFW, LC_YSFS, LC_YFSJ, LC_ZXFLAG
      FROM GS_DJ_CKTMSDAB T
     WHERE T.NSRDZDAH=V_IN_NSRDZDAH;
  EXCEPTION
    WHEN OTHERS THEN
      V_OUT_STATUS :='08';
      V_OUT_MESSAGE:='企业当前未进行出口退（免）税备案，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
  END;
  IF LC_ZXFLAG='R' THEN
    BEGIN
      V_OUT_STATUS :='09';
      V_OUT_MESSAGE:='企业当前已出口退（免）税备案撤回，不允许申报除出口退（免）税备案以外的其他业务！';
      RETURN;
    END;
  END IF;

  --取企业的FLGLCD信息, TGSHZL信息，判断是否需要申报收汇
  LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
  IF LN_CPCODEKZ=0 THEN
    BEGIN
      V_OUT_STATUS :='10';
      V_OUT_MESSAGE:='查询出口企业分类管理类型出错！';
      RETURN;
    END;
  END IF;


  LC_YDOBJECT:='委托出口';
  BEGIN
    FOR LSF_XX IN (SELECT DISTINCT A.SBXH,
                          A.CKBGDH,
                          A.STFNSRSBH,
                          NVL(E.NSRSBH,B.UUID) AS STQY,
                          A.CKSP_DM,
                          NVL(C.CKSP_DM,D.CKSP_DM) AS CKSP_DM_QSTS
                     FROM CKTS_ZM_WTCK_LSB A
                     LEFT JOIN CKTS_WBSJ_ZJ_CKTSBAQGXX B ON B.NSRSBH=A.STFNSRSBH OR B.SHXYDM=A.STFNSRSBH
                     LEFT JOIN CKTS_DM_TSLVWK C ON C.CKSP_DM=A.CKSP_DM AND (SYSDATE BETWEEN C.YXQQ AND C.YXQZ) AND C.ZSSL>0 AND C.TSL=0 AND C.CKSPTSSPLX_DM='1'
                     LEFT JOIN CKTS_DM_TSLVWK D ON D.CKSP_DM=SUBSTR(A.CKSP_DM,1,8) AND (SYSDATE BETWEEN D.YXQQ AND D.YXQZ) AND D.ZSSL>0 AND D.TSL=0 AND D.CKSPTSSPLX_DM='1'
                     LEFT JOIN GS_DJ_CKTMSDAB E ON E.NSRDJNO=A.STFNSRSBH OR E.SHXYNO=A.STFNSRSBH
                    WHERE A.SBID=V_IN_SBID) LOOP
      BEGIN
        IF (LSF_XX.STQY IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_WTCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_WTCK_DFDWSH_VALID','E','未查询到受托企业[' || LSF_XX.STFNSRSBH || ']的出口退（免）税备案信息，请核实受托企业纳税人社会信用码（识别号）是否准确！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF (LSF_XX.CKSP_DM_QSTS IS NULL) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_ZM_WTCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'TSZM_WTCK_SPDM_RANK','I','出口商品代码[' || LSF_XX.CKSP_DM || ']不是取消退税商品，请确认是否需要申请委托出口货物证明！','Y',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;
END;
/
