CREATE OR REPLACE PROCEDURE PROC_XXBD_MDT_HGSPTZ
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（生产企业免抵退税）
  修改日期：20230207，修改代理证明出口申报调整表的疑点逻辑和提示
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  --海关代码调整明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MDT_HGSPTZ_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;
  LC_YDOBJECT :='代码调整';

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_HGSPTZ_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_DMTZ_CKHW_CKPZ','E','出口货物报关单号/代理出口货物证明号[' || NVL(T.DLCKHWZMHM,T.CKBGDH) || ']未申报免退税出口明细！','N',SYSDATE
           FROM CKTS_SB_MDT_HGSPTZ_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MDT_TSSB_LSB S WHERE S.SBID=T.SBID AND NVL(S.DLCKHWZMHM,S.CKBGDH)=NVL(T.DLCKHWZMHM,T.CKBGDH));
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_HGSPTZ_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_DMTZ_CKHW_CKRQ','E','出口货物报关单号/代理出口货物证明号[' || NVL(T.DLCKHWZMHM,T.CKBGDH) || ']的出口日期与免退税出口明细表中不一致！','N',SYSDATE
           FROM CKTS_SB_MDT_HGSPTZ_LSB T
          INNER JOIN CKTS_SB_MDT_TSSB_LSB S ON S.SBID=T.SBID AND NVL(S.DLCKHWZMHM,S.CKBGDH)=NVL(T.DLCKHWZMHM,T.CKBGDH)
          WHERE T.SBID=V_IN_SBID
            AND TRUNC(T.CKRQ_1,'DD')<>TRUNC(S.CKRQ_1,'DD');
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_HGSPTZ_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_DMTZ_CKHW_SPDM','E','出口货物报关单号/代理出口货物证明号[' || NVL(T.DLCKHWZMHM,T.CKBGDH) || ']调整前商品代码与免退税出口明细表中不一致！','N',SYSDATE
           FROM CKTS_SB_MDT_HGSPTZ_LSB T
          INNER JOIN CKTS_SB_MDT_TSSB_LSB S ON S.SBID=T.SBID AND NVL(S.DLCKHWZMHM,S.CKBGDH)=NVL(T.DLCKHWZMHM,T.CKBGDH)
          WHERE T.SBID=V_IN_SBID
            AND T.CKSP_DM<>S.CKSP_DM;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_HGSPTZ_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_DMTZ_CKHW_ZSLV','E','出口货物报关单号/代理出口货物证明号[' || NVL(T.DLCKHWZMHM,T.CKBGDH) || ']调整后商品代码在对应出口日期的退税率文库中的征税率与货物出口明细表中不一致！','N',SYSDATE
           FROM CKTS_SB_MDT_HGSPTZ_LSB T
          INNER JOIN CKTS_SB_MDT_TSSB_LSB S ON S.SBID=T.SBID AND NVL(S.DLCKHWZMHM,S.CKBGDH)=NVL(T.DLCKHWZMHM,T.CKBGDH)
           LEFT JOIN CKTS_DM_TSLVWK C ON C.CKSP_DM=T.TZHCKSP_DM AND S.CKRQ_1 BETWEEN C.YXQQ AND C.YXQZ
           LEFT JOIN CKTS_DM_TSLVTZ D ON D.CKSP_DM=T.TZHCKSP_DM AND S.CKRQ_1 BETWEEN D.KSSJ AND D.JSSJ
          WHERE T.SBID=V_IN_SBID
            AND NVL(NVL(D.ZSSL,C.ZSSL),0)<>S.ZSSL;
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MDT_HGSPTZ_LSB','CKTS_SB_MDT_TSSB_LSB',NULL,T.SBXH,NULL,'MDT_BJGX_DMTZ_CKHW_TSLV','E','出口货物报关单号/代理出口货物证明号[' || NVL(T.DLCKHWZMHM,T.CKBGDH) || ']调整后退税率与免退税进货明细表中不一致！','N',SYSDATE
           FROM CKTS_SB_MDT_HGSPTZ_LSB T
          INNER JOIN CKTS_SB_MDT_TSSB_LSB S ON S.SBID=T.SBID AND NVL(S.DLCKHWZMHM,S.CKBGDH)=NVL(T.DLCKHWZMHM,T.CKBGDH)
          WHERE T.SBID=V_IN_SBID
            AND T.TZHTSL<>S.TSL;
    COMMIT;
  END;
END;
/
