CREATE OR REPLACE PROCEDURE PROC_XXBD_MTS_TSJH
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  调整日期：20210603，1、调整疑点关联业务字段，关联号+申报序号
  调整日期：20211208，1、调整免退税疑点描述字段中申报序号与关联单证号的顺序，使其与客户端疑点展示一致
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LC_KZXX         VARCHAR2(20);
  LDT_TODAY       DATE;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';

  --进货明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_TSJH_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;
  LC_YDOBJECT :='进货明细';

  --初始化进货明细出口业务类型、出口日期，以备后续使用
  BEGIN
    UPDATE CKTS_SB_MTS_TSJH_LSB T
       SET (T.CKTMSYWLXDMJH,T.CKRQ_1)=(SELECT S.CKTMSYWLXDMJH,S.CKRQ_1
                                         FROM CKTS_SB_MTS_TSSB_LSB S
                                        WHERE S.SBID=T.SBID
                                          AND S.GLH=T.GLH
                                          AND ROWNUM=1)
     WHERE T.SBID=V_IN_SBID;
    COMMIT;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSJH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,T.SBXH,T.GLH,'MTS_BJGX_JHMX_CKMX_GLH','E','进货明细中的关联号[' || T.GLH || ']在出口明细中不存在！','N',SYSDATE
           FROM CKTS_SB_MTS_TSJH_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_TSSB_LSB S WHERE S.SBID=T.SBID AND S.GLH=T.GLH);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSJH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,T.SBXH,T.GLH,'MTS_BJGX_JHMX_CKMX_SPDM','E','进货明细中的关联号[' || T.GLH || ']商品代码[' || T.CKSP_DM || ']在出口明细中不存在！','N',SYSDATE
           FROM CKTS_SB_MTS_TSJH_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_TSSB_LSB S WHERE S.SBID=T.SBID AND S.GLH=T.GLH AND S.CKSP_DM=T.CKSP_DM);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSJH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,T.SBXH,T.GLH,'MTS_BJGX_JHMX_CKMX_JLDW','E','进货明细中的关联号[' || T.GLH || ']计量单位[' || T.HGJLDWMC || ']在出口明细中不存在！','N',SYSDATE
           FROM CKTS_SB_MTS_TSJH_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_TSSB_LSB S WHERE S.SBID=T.SBID AND S.GLH=T.GLH AND S.HGJLDWMC=T.HGJLDWMC);
    COMMIT;

    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
           WITH CK AS (SELECT T.SBID,T.GLH,T.CKSP_DM,SUM(T.CKSL) AS CKSL FROM CKTS_SB_MTS_TSSB_LSB T WHERE T.SBID=V_IN_SBID GROUP BY T.SBID,T.GLH,T.CKSP_DM),
                JH AS (SELECT S.SBID,S.GLH,S.CKSP_DM,SUM(S.SL) AS JHSL FROM CKTS_SB_MTS_TSJH_LSB S WHERE S.SBID=V_IN_SBID AND S.SZ='V' GROUP BY S.SBID,S.GLH,S.CKSP_DM)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_TSJH_LSB','CKTS_SB_MTS_TSSB_LSB',NULL,NULL,JH.GLH,'MTS_BJGX_JHMX_CKMX_CKSL','E','进货明细中的关联号[' || JH.GLH || ']商品代码[' || JH.CKSP_DM || ']进货数量[' || JH.JHSL || ']大于出口数量[' || NVL(CK.CKSL,0.00) || ']！','N',SYSDATE
           FROM JH
           LEFT JOIN CK ON JH.SBID=CK.SBID AND JH.GLH=CK.GLH AND JH.CKSP_DM=CK.CKSP_DM
          WHERE CK.SBID=V_IN_SBID AND JH.JHSL>NVL(CK.CKSL,0);
    COMMIT;
  END;

END;
/
