CREATE OR REPLACE PROCEDURE PROC_XXBD_MTS_LSLV_ZZSFP
/*
  编制人:严国平
  编制日期:202009
  功能:信息比对（外贸企业免退税）
  调整日期：20201125，增加疑点MTS_JHMX_ZZSFP_SBJE的描述进行调整，细化企业发票开票数、已申报数据提示
  调整日期：20201230，1、校验发票稽核信息时，剔除代开发票的稽核信息，代开发票开票人税号含DK
  调整日期：20210603，1、调整MTS_YSFW_ZZSFP_SBJE计税金额总量控制误差
  调整日期：20211208，1、调整免退税疑点描述字段中申报序号与关联单证号的顺序，使其与客户端疑点展示一致
  调整日期：20220228，1、增加MTS_YSFW_ZZSFP_SBSE疑点，当发票本次申报总退税额大于发票总开票税额（误差+1）时提醒，不可挑过
  调整日期：20220701，1、根据全电票规则调整发票的关联，用JHPZH代替FPDM+FPHM
  调整日期：20230207，1、修改全电发票关联虚开发票时的BUG。
  调整日期：20230315，调整出口企业首次申报日期取数口径，改为按税务机关+企业+业务代码查询首次发放日期
  调整日期：20230515，解决增值税发票外部数据部分数据稽核相符标志为空的问题（赋默认值N）
  调整日期：20230518，解决按税务机关+企业+业务代码查询首次发放日期有结果但日期为空的问题（赋默认值SYSDATE）
 */
(
  V_IN_NSRDZDAH   IN  NUMBER, /*纳税人电子档案号*/
  V_IN_DJXH       IN  NUMBER, /*登记序号*/
  V_IN_SBYWBDM    IN  VARCHAR2, /*申报业务表代码*/
  V_IN_SSSQ       IN  VARCHAR2, /*申报年月*/
  V_IN_SBPC       IN  NUMBER, /*申报批次*/
  V_IN_SBID       IN  NUMBER, /*申报ID*/
  V_OUT_STATUS    OUT VARCHAR2, /*00:成功; 其他:执行失败*/
  V_OUT_MESSAGE   OUT VARCHAR2
)
AS
  LN_MXROW        NUMBER(10);
  LC_YDOBJECT     VARCHAR2(20);
  LN_CPCODEKZ     NUMBER(10);
  LC_FLGLCD       VARCHAR2(20);
  LC_KZXX         VARCHAR2(20);
  LDT_TODAY       DATE;
  LDT_SCSBRQ      DATE;
BEGIN
  V_OUT_STATUS :='00';
  V_OUT_MESSAGE:=' ';
  LDT_TODAY:=TRUNC(SYSDATE,'DD');

  --外购服务明细表记录为空，不需要比对
  BEGIN
    SELECT COUNT(1)
      INTO LN_MXROW
      FROM CKTS_SB_MTS_YSFWCK_LSB T
     WHERE T.SBID=V_IN_SBID;
    IF LN_MXROW=0 THEN
      RETURN;
    END IF;
  END;

  --查询企业首次申报日期
  BEGIN
    SELECT NVL(T.FFRQ,SYSDATE)
      INTO LDT_SCSBRQ
      FROM CKTS_TY_YWBLXX_SCFFRQ T
     WHERE T.TSSWJG_DM_1=(SELECT SWJG_DM FROM GS_DJ_CKTMSDAB WHERE NSRDZDAH=V_IN_NSRDZDAH)
       AND T.DJXH=V_IN_DJXH AND T.LCSWSX_DM='LCSXA081039001';
  EXCEPTION
    WHEN OTHERS THEN
      LDT_SCSBRQ:=LDT_TODAY;
  END;

  LC_YDOBJECT :='服务进货';
  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,T.SBXH,NULL,'MTS_YSFW_JHPZH_WDZXX','E','进货凭证号[' || T.JHPZH || ']无电子信息！','N',SYSDATE
           FROM CKTS_SB_MTS_YSFWCK_LSB T
          WHERE T.SBID=V_IN_SBID
            AND NOT EXISTS (SELECT 1
                              FROM CKTS_WBSJ_FP_ZZSZYFPXX S
                             WHERE S.DJXH=V_IN_DJXH
                               AND S.JHPZH=T.JHPZH);
    COMMIT;
  END;

  BEGIN
    LN_CPCODEKZ:=FUNC_XXBD_QUERY_CPCODEKZ(V_IN_NSRDZDAH,'FLGLCD',LDT_TODAY,LC_FLGLCD);
    FOR LSF_XX IN (SELECT A.SBXH,
                          A.JHPZH,
                          NVL(A.CKTMSYWLXDMJH,' ') AS CKTMSYWLXDMJH,
                          NVL(B.JHXFZZSZYFPBZ,'N') AS JHXFZZSZYFPBZ,
                          B.BYTSBZ,
                          A.GHFNSRSBH_1,
                          B.XFNSRSBH,
                          TRUNC(A.KPRQ,'DD') AS KPRQ_SB,
                          TRUNC(B.KPRQ,'DD') AS KPRQ_SH,
                          B.FPYT_DM,
                          NVL(B.FPSJBBZ,'N') AS FPSJBZ,
                          NVL(B.NXZCKBZ,'N') AS NXZCKBZ,
                          C.GHFNSRSBH
                     FROM CKTS_SB_MTS_YSFWCK_LSB A
                    INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX B ON B.DJXH=V_IN_DJXH AND B.JHPZH=A.JHPZH
                     LEFT JOIN CKTS_WBSJ_ZJ_XKFP C ON C.FP_DM||C.FPHM=A.JHPZH
                    WHERE A.SBID=V_IN_SBID) LOOP
      BEGIN
        IF (LSF_XX.JHXFZZSZYFPBZ='N' AND INSTR(LSF_XX.XFNSRSBH,'DK')=0 AND (INSTR(LSF_XX.CKTMSYWLXDMJH,'RZZL')>0 OR LC_FLGLCD='D' OR (LC_FLGLCD='C' AND MONTHS_BETWEEN(LDT_TODAY,LDT_SCSBRQ)<=12))) THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'MTS_YSFW_JHPZH_WDZXX','E','进货凭证号[' || LSF_XX.JHPZH || ']无稽核相符电子信息！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.BYTSBZ='Y' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'MTS_YSFW_JHPZH_BYTS','E','进货凭证号[' || LSF_XX.JHPZH || ']已被标注为“不予退税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.GHFNSRSBH_1<>LSF_XX.XFNSRSBH THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'MTS_YSFW_JHPZH_GHFNSR','E','进货凭证号[' || LSF_XX.JHPZH || ']供货方纳税人[' || LSF_XX.GHFNSRSBH_1 || ']与电子信息中[' || LSF_XX.XFNSRSBH || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.KPRQ_SB<>LSF_XX.KPRQ_SH THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'MTS_YSFW_JHPZH_KPRQ','E','进货凭证号[' || LSF_XX.JHPZH || ']开票日期[' || TO_CHAR(LSF_XX.KPRQ_SB,'YYYY-MM-DD') || ']与电子信息中[' || TO_CHAR(LSF_XX.KPRQ_SH,'YYYY-MM-DD') || ']不一致！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.FPYT_DM='3' THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'MTS_YSFW_JHPZH_DBTS','E','进货凭证号[' || LSF_XX.JHPZH || ']在电子信息中申报用途代码为“3-代办退税”！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        ELSIF (LSF_XX.FPYT_DM='1' AND LSF_XX.FPSJBZ='Y' AND LSF_XX.NXZCKBZ='N') THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'MTS_YSFW_JHPZH_YDK','E','进货凭证号[' || LSF_XX.JHPZH || ']在电子信息中已勾选用于抵扣！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;

        IF LSF_XX.GHFNSRSBH IS NOT NULL THEN
          INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
               SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                      'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,LSF_XX.SBXH,NULL,'MTS_YSFW_JHPZH_XKFP','E','进货凭证号[' || LSF_XX.JHPZH || ']在电子信息中为虚开进货凭证号！','N',SYSDATE
                 FROM DUAL;
          COMMIT;
        END IF;
      END;
    END LOOP;
  END;

  BEGIN
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,NULL,T.JHPZH,'MTS_YSFW_ZZSFP_SBJE','E',
                '增值税专用发票[' || T.JHPZH || ']申报退税的计税金额[' || T.JSJE || ']超过电子信息中剩余数[' || GREATEST(0,S.JE - NVL(S.HZCJJE,0) - NVL(S.SBFPJSJE,0) - NVL(S.LSLSBFPJSJE,0)) ||
                ']（其中开票[' || S.JE || ']红字冲减[' || NVL(S.HZCJJE,0) || ']出口货物劳务已申报[' || NVL(S.SBFPJSJE,0) || ']外购应税服务已申报[' || NVL(S.LSLSBFPJSJE,0) || ']）！','Y',SYSDATE
           FROM (SELECT A.JHPZH, SUM(A.JSJE) AS JSJE
                   FROM CKTS_SB_MTS_YSFWCK_LSB A
                  WHERE A.SBID=V_IN_SBID
                  GROUP BY A.JHPZH) T
          INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX S ON S.DJXH=V_IN_DJXH AND S.JHPZH=T.JHPZH
          WHERE T.JSJE > S.JE - NVL(S.HZCJJE,0) - NVL(S.SBFPJSJE,0) - NVL(S.LSLSBFPJSJE,0);
    COMMIT;
    
    INSERT INTO CKTS_XXBD_SHQ_YDXX(DJXH,SBYWB_DM,SSSQ,SBPC,SBID,ERR_LY,XH,ERR_OBJ,GLYWB1,GLYWB2,GLYWB3,GLYWZ1,GLYWZ2,YDCODE,ERR_LEV,ERR_MSG,PASS_FLAG,CRTIME)
         SELECT V_IN_DJXH,V_IN_SBYWBDM,V_IN_SSSQ,V_IN_SBPC,V_IN_SBID,'1',SEQ_XXBD_SHQ_YDID.NEXTVAL,LC_YDOBJECT,
                'CKTS_SB_MTS_YSFWCK_LSB',NULL,NULL,NULL,T.JHPZH,'MTS_YSFW_ZZSFP_SBSE','E',
                '增值税专用发票[' || T.JHPZH || ']申报退税额[' || T.TSE || ']超过电子信息中税额[' || NVL(S.SE,0) || ']！','N',SYSDATE
           FROM (SELECT A.JHPZH, SUM(A.ZZSTSE) AS TSE
                   FROM CKTS_SB_MTS_YSFWCK_LSB A
                  WHERE A.SBID=V_IN_SBID
                  GROUP BY A.JHPZH) T
          INNER JOIN CKTS_WBSJ_FP_ZZSZYFPXX S ON S.DJXH=V_IN_DJXH AND S.JHPZH=T.JHPZH
          WHERE T.TSE > S.SE + 1;
    COMMIT;
  END;
END;
/
