package com.tl.web.bjts.shzs.model.domain;

import java.math.BigDecimal;
import java.util.Date;

public class DocFileinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.FILENAME
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.FMCODE
     *
     * @mbggenerated
     */
    private String fmcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.FILESIZE
     *
     * @mbggenerated
     */
    private Long filesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.ROOTPATH
     *
     * @mbggenerated
     */
    private String rootpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.FILEPATH
     *
     * @mbggenerated
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.BUSITYPE
     *
     * @mbggenerated
     */
    private String busitype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.BUSIKEY
     *
     * @mbggenerated
     */
    private Long busikey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.NSRDZDAH
     *
     * @mbggenerated
     */
    private BigDecimal nsrdzdah;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.FILETYPE
     *
     * @mbggenerated
     */
    private String filetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.ISSIGN
     *
     * @mbggenerated
     */
    private String issign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.CRID
     *
     * @mbggenerated
     */
    private Long crid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.CRTIME
     *
     * @mbggenerated
     */
    private Date crtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.UPID
     *
     * @mbggenerated
     */
    private Long upid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILEINFO.UPTIME
     *
     * @mbggenerated
     */
    private Date uptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.ID
     *
     * @return the value of DOC_FILEINFO.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.ID
     *
     * @param id the value for DOC_FILEINFO.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.FILENAME
     *
     * @return the value of DOC_FILEINFO.FILENAME
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.FILENAME
     *
     * @param filename the value for DOC_FILEINFO.FILENAME
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.FMCODE
     *
     * @return the value of DOC_FILEINFO.FMCODE
     *
     * @mbggenerated
     */
    public String getFmcode() {
        return fmcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.FMCODE
     *
     * @param fmcode the value for DOC_FILEINFO.FMCODE
     *
     * @mbggenerated
     */
    public void setFmcode(String fmcode) {
        this.fmcode = fmcode == null ? null : fmcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.TITLE
     *
     * @return the value of DOC_FILEINFO.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.TITLE
     *
     * @param title the value for DOC_FILEINFO.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.FILESIZE
     *
     * @return the value of DOC_FILEINFO.FILESIZE
     *
     * @mbggenerated
     */
    public Long getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.FILESIZE
     *
     * @param filesize the value for DOC_FILEINFO.FILESIZE
     *
     * @mbggenerated
     */
    public void setFilesize(Long filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.ROOTPATH
     *
     * @return the value of DOC_FILEINFO.ROOTPATH
     *
     * @mbggenerated
     */
    public String getRootpath() {
        return rootpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.ROOTPATH
     *
     * @param rootpath the value for DOC_FILEINFO.ROOTPATH
     *
     * @mbggenerated
     */
    public void setRootpath(String rootpath) {
        this.rootpath = rootpath == null ? null : rootpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.FILEPATH
     *
     * @return the value of DOC_FILEINFO.FILEPATH
     *
     * @mbggenerated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.FILEPATH
     *
     * @param filepath the value for DOC_FILEINFO.FILEPATH
     *
     * @mbggenerated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.BUSITYPE
     *
     * @return the value of DOC_FILEINFO.BUSITYPE
     *
     * @mbggenerated
     */
    public String getBusitype() {
        return busitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.BUSITYPE
     *
     * @param busitype the value for DOC_FILEINFO.BUSITYPE
     *
     * @mbggenerated
     */
    public void setBusitype(String busitype) {
        this.busitype = busitype == null ? null : busitype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.BUSIKEY
     *
     * @return the value of DOC_FILEINFO.BUSIKEY
     *
     * @mbggenerated
     */
    public Long getBusikey() {
        return busikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.BUSIKEY
     *
     * @param busikey the value for DOC_FILEINFO.BUSIKEY
     *
     * @mbggenerated
     */
    public void setBusikey(Long busikey) {
        this.busikey = busikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.NSRDZDAH
     *
     * @return the value of DOC_FILEINFO.NSRDZDAH
     *
     * @mbggenerated
     */
    public BigDecimal getNsrdzdah() {
        return nsrdzdah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.NSRDZDAH
     *
     * @param nsrdzdah the value for DOC_FILEINFO.NSRDZDAH
     *
     * @mbggenerated
     */
    public void setNsrdzdah(BigDecimal nsrdzdah) {
        this.nsrdzdah = nsrdzdah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.FILETYPE
     *
     * @return the value of DOC_FILEINFO.FILETYPE
     *
     * @mbggenerated
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.FILETYPE
     *
     * @param filetype the value for DOC_FILEINFO.FILETYPE
     *
     * @mbggenerated
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype == null ? null : filetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.NOTE
     *
     * @return the value of DOC_FILEINFO.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.NOTE
     *
     * @param note the value for DOC_FILEINFO.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.ISSIGN
     *
     * @return the value of DOC_FILEINFO.ISSIGN
     *
     * @mbggenerated
     */
    public String getIssign() {
        return issign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.ISSIGN
     *
     * @param issign the value for DOC_FILEINFO.ISSIGN
     *
     * @mbggenerated
     */
    public void setIssign(String issign) {
        this.issign = issign == null ? null : issign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.CRID
     *
     * @return the value of DOC_FILEINFO.CRID
     *
     * @mbggenerated
     */
    public Long getCrid() {
        return crid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.CRID
     *
     * @param crid the value for DOC_FILEINFO.CRID
     *
     * @mbggenerated
     */
    public void setCrid(Long crid) {
        this.crid = crid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.CRTIME
     *
     * @return the value of DOC_FILEINFO.CRTIME
     *
     * @mbggenerated
     */
    public Date getCrtime() {
        return crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.CRTIME
     *
     * @param crtime the value for DOC_FILEINFO.CRTIME
     *
     * @mbggenerated
     */
    public void setCrtime(Date crtime) {
        this.crtime = crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.UPID
     *
     * @return the value of DOC_FILEINFO.UPID
     *
     * @mbggenerated
     */
    public Long getUpid() {
        return upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.UPID
     *
     * @param upid the value for DOC_FILEINFO.UPID
     *
     * @mbggenerated
     */
    public void setUpid(Long upid) {
        this.upid = upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILEINFO.UPTIME
     *
     * @return the value of DOC_FILEINFO.UPTIME
     *
     * @mbggenerated
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILEINFO.UPTIME
     *
     * @param uptime the value for DOC_FILEINFO.UPTIME
     *
     * @mbggenerated
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }
}