package com.tl.web.bjts.shzs.model.domain;

import java.io.Serializable;
import java.util.Date;

public class TlDtbsj implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_DTBSJ.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_DTBSJ.TBLX_DM
     *
     * @mbggenerated
     */
    private String tblxDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_DTBSJ.MAINID
     *
     * @mbggenerated
     */
    private Long mainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_DTBSJ.CJSJ
     *
     * @mbggenerated
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_DTBSJ.TQBZ
     *
     * @mbggenerated
     */
    private String tqbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_DTBSJ.TQSJ
     *
     * @mbggenerated
     */
    private Date tqsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_DTBSJ.TBCS
     *
     * @mbggenerated
     */
    private Integer tbcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_DTBSJ.SBYY
     *
     * @mbggenerated
     */
    private String sbyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_DTBSJ.YXJ
     *
     * @mbggenerated
     */
    private Integer yxj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_DTBSJ
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_DTBSJ.ID
     *
     * @return the value of TB_DTBSJ.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_DTBSJ.ID
     *
     * @param id the value for TB_DTBSJ.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_DTBSJ.TBLX_DM
     *
     * @return the value of TB_DTBSJ.TBLX_DM
     *
     * @mbggenerated
     */
    public String getTblxDm() {
        return tblxDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_DTBSJ.TBLX_DM
     *
     * @param tblxDm the value for TB_DTBSJ.TBLX_DM
     *
     * @mbggenerated
     */
    public void setTblxDm(String tblxDm) {
        this.tblxDm = tblxDm == null ? null : tblxDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_DTBSJ.MAINID
     *
     * @return the value of TB_DTBSJ.MAINID
     *
     * @mbggenerated
     */
    public Long getMainid() {
        return mainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_DTBSJ.MAINID
     *
     * @param mainid the value for TB_DTBSJ.MAINID
     *
     * @mbggenerated
     */
    public void setMainid(Long mainid) {
        this.mainid = mainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_DTBSJ.CJSJ
     *
     * @return the value of TB_DTBSJ.CJSJ
     *
     * @mbggenerated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_DTBSJ.CJSJ
     *
     * @param cjsj the value for TB_DTBSJ.CJSJ
     *
     * @mbggenerated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_DTBSJ.TQBZ
     *
     * @return the value of TB_DTBSJ.TQBZ
     *
     * @mbggenerated
     */
    public String getTqbz() {
        return tqbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_DTBSJ.TQBZ
     *
     * @param tqbz the value for TB_DTBSJ.TQBZ
     *
     * @mbggenerated
     */
    public void setTqbz(String tqbz) {
        this.tqbz = tqbz == null ? null : tqbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_DTBSJ.TQSJ
     *
     * @return the value of TB_DTBSJ.TQSJ
     *
     * @mbggenerated
     */
    public Date getTqsj() {
        return tqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_DTBSJ.TQSJ
     *
     * @param tqsj the value for TB_DTBSJ.TQSJ
     *
     * @mbggenerated
     */
    public void setTqsj(Date tqsj) {
        this.tqsj = tqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_DTBSJ.TBCS
     *
     * @return the value of TB_DTBSJ.TBCS
     *
     * @mbggenerated
     */
    public Integer getTbcs() {
        return tbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_DTBSJ.TBCS
     *
     * @param tbcs the value for TB_DTBSJ.TBCS
     *
     * @mbggenerated
     */
    public void setTbcs(Integer tbcs) {
        this.tbcs = tbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_DTBSJ.SBYY
     *
     * @return the value of TB_DTBSJ.SBYY
     *
     * @mbggenerated
     */
    public String getSbyy() {
        return sbyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_DTBSJ.SBYY
     *
     * @param sbyy the value for TB_DTBSJ.SBYY
     *
     * @mbggenerated
     */
    public void setSbyy(String sbyy) {
        this.sbyy = sbyy == null ? null : sbyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_DTBSJ.YXJ
     *
     * @return the value of TB_DTBSJ.YXJ
     *
     * @mbggenerated
     */
    public Integer getYxj() {
        return yxj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_DTBSJ.YXJ
     *
     * @param yxj the value for TB_DTBSJ.YXJ
     *
     * @mbggenerated
     */
    public void setYxj(Integer yxj) {
        this.yxj = yxj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DTBSJ
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tblxDm=").append(tblxDm);
        sb.append(", mainid=").append(mainid);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", tqbz=").append(tqbz);
        sb.append(", tqsj=").append(tqsj);
        sb.append(", tbcs=").append(tbcs);
        sb.append(", sbyy=").append(sbyy);
        sb.append(", yxj=").append(yxj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}