package com.tl.web.bjts.shzs.model.domain;

import java.io.Serializable;
import java.util.Date;

public class TlGcYwlcInfoHisProfile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.LCSLID
     *
     * @mbggenerated
     */
    private String lcslid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.LC_ID
     *
     * @mbggenerated
     */
    private String lcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.LCT_ID
     *
     * @mbggenerated
     */
    private String lctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.FIRING
     *
     * @mbggenerated
     */
    private Date firing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.LCT_HDID
     *
     * @mbggenerated
     */
    private String lctHdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.NODE_ID
     *
     * @mbggenerated
     */
    private String nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.LCT_HDID_NAME
     *
     * @mbggenerated
     */
    private String lctHdidName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.YW_PK
     *
     * @mbggenerated
     */
    private String ywPk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.YW_PK_NAME
     *
     * @mbggenerated
     */
    private String ywPkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.YW_INFO
     *
     * @mbggenerated
     */
    private String ywInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.TS_USER
     *
     * @mbggenerated
     */
    private String tsUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.TS_NAME
     *
     * @mbggenerated
     */
    private String tsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.TS_DATE
     *
     * @mbggenerated
     */
    private Date tsDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.JS_USER
     *
     * @mbggenerated
     */
    private String jsUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.JS_NAME
     *
     * @mbggenerated
     */
    private String jsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.JS_POST
     *
     * @mbggenerated
     */
    private String jsPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.JS_POST_NAME
     *
     * @mbggenerated
     */
    private String jsPostName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.OP_USER
     *
     * @mbggenerated
     */
    private String opUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.OP_NAME
     *
     * @mbggenerated
     */
    private String opName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.OP_DATE
     *
     * @mbggenerated
     */
    private Date opDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.HT_USER
     *
     * @mbggenerated
     */
    private String htUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.HT_NAME
     *
     * @mbggenerated
     */
    private String htName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.HT_DATE
     *
     * @mbggenerated
     */
    private Date htDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.HT_REASON
     *
     * @mbggenerated
     */
    private String htReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.ZF_FLAG
     *
     * @mbggenerated
     */
    private String zfFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.ZF_USER
     *
     * @mbggenerated
     */
    private String zfUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.ZF_NAME
     *
     * @mbggenerated
     */
    private String zfName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.ZF_REASON
     *
     * @mbggenerated
     */
    private String zfReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.ZF_DATE
     *
     * @mbggenerated
     */
    private Date zfDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.ZH_FLAG
     *
     * @mbggenerated
     */
    private String zhFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.PL_FLAG
     *
     * @mbggenerated
     */
    private String plFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.FINISH_DATE
     *
     * @mbggenerated
     */
    private Date finishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.RSV_FLAG
     *
     * @mbggenerated
     */
    private String rsvFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.USER_GROUP
     *
     * @mbggenerated
     */
    private String userGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.TX_LEV
     *
     * @mbggenerated
     */
    private String txLev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.TX_INFO
     *
     * @mbggenerated
     */
    private String txInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.TX_USER
     *
     * @mbggenerated
     */
    private String txUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.TX_DATE
     *
     * @mbggenerated
     */
    private Date txDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.SWCODE
     *
     * @mbggenerated
     */
    private String swcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.LC_NAME
     *
     * @mbggenerated
     */
    private String lcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.BL_LIMIT
     *
     * @mbggenerated
     */
    private String blLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.HT_FLAG
     *
     * @mbggenerated
     */
    private String htFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.LOG_UUID
     *
     * @mbggenerated
     */
    private String logUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.IS_WZH
     *
     * @mbggenerated
     */
    private String isWzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.FLGLCD
     *
     * @mbggenerated
     */
    private String flglcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.QYDM
     *
     * @mbggenerated
     */
    private String qydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.NSRDJ_NO
     *
     * @mbggenerated
     */
    private String nsrdjNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.SHXY_NO
     *
     * @mbggenerated
     */
    private String shxyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.SLTZ_DATE
     *
     * @mbggenerated
     */
    private Date sltzDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.SBLY
     *
     * @mbggenerated
     */
    private String sbly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.S_LCT_ID
     *
     * @mbggenerated
     */
    private String sLctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.DP_FLAG
     *
     * @mbggenerated
     */
    private String dpFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSSH.GC_YWLC_INFO_HIS.EWM
     *
     * @mbggenerated
     */
    private String ewm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TSSH.GC_YWLC_INFO_HIS
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.LCSLID
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.LCSLID
     *
     * @mbggenerated
     */
    public String getLcslid() {
        return lcslid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.LCSLID
     *
     * @param lcslid the value for TSSH.GC_YWLC_INFO_HIS.LCSLID
     *
     * @mbggenerated
     */
    public void setLcslid(String lcslid) {
        this.lcslid = lcslid == null ? null : lcslid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.LC_ID
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.LC_ID
     *
     * @mbggenerated
     */
    public String getLcId() {
        return lcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.LC_ID
     *
     * @param lcId the value for TSSH.GC_YWLC_INFO_HIS.LC_ID
     *
     * @mbggenerated
     */
    public void setLcId(String lcId) {
        this.lcId = lcId == null ? null : lcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.LCT_ID
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.LCT_ID
     *
     * @mbggenerated
     */
    public String getLctId() {
        return lctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.LCT_ID
     *
     * @param lctId the value for TSSH.GC_YWLC_INFO_HIS.LCT_ID
     *
     * @mbggenerated
     */
    public void setLctId(String lctId) {
        this.lctId = lctId == null ? null : lctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.STATE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.STATE
     *
     * @param state the value for TSSH.GC_YWLC_INFO_HIS.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.FIRING
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.FIRING
     *
     * @mbggenerated
     */
    public Date getFiring() {
        return firing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.FIRING
     *
     * @param firing the value for TSSH.GC_YWLC_INFO_HIS.FIRING
     *
     * @mbggenerated
     */
    public void setFiring(Date firing) {
        this.firing = firing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.LCT_HDID
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.LCT_HDID
     *
     * @mbggenerated
     */
    public String getLctHdid() {
        return lctHdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.LCT_HDID
     *
     * @param lctHdid the value for TSSH.GC_YWLC_INFO_HIS.LCT_HDID
     *
     * @mbggenerated
     */
    public void setLctHdid(String lctHdid) {
        this.lctHdid = lctHdid == null ? null : lctHdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.NODE_ID
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.NODE_ID
     *
     * @mbggenerated
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.NODE_ID
     *
     * @param nodeId the value for TSSH.GC_YWLC_INFO_HIS.NODE_ID
     *
     * @mbggenerated
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.LCT_HDID_NAME
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.LCT_HDID_NAME
     *
     * @mbggenerated
     */
    public String getLctHdidName() {
        return lctHdidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.LCT_HDID_NAME
     *
     * @param lctHdidName the value for TSSH.GC_YWLC_INFO_HIS.LCT_HDID_NAME
     *
     * @mbggenerated
     */
    public void setLctHdidName(String lctHdidName) {
        this.lctHdidName = lctHdidName == null ? null : lctHdidName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.YW_PK
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.YW_PK
     *
     * @mbggenerated
     */
    public String getYwPk() {
        return ywPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.YW_PK
     *
     * @param ywPk the value for TSSH.GC_YWLC_INFO_HIS.YW_PK
     *
     * @mbggenerated
     */
    public void setYwPk(String ywPk) {
        this.ywPk = ywPk == null ? null : ywPk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.YW_PK_NAME
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.YW_PK_NAME
     *
     * @mbggenerated
     */
    public String getYwPkName() {
        return ywPkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.YW_PK_NAME
     *
     * @param ywPkName the value for TSSH.GC_YWLC_INFO_HIS.YW_PK_NAME
     *
     * @mbggenerated
     */
    public void setYwPkName(String ywPkName) {
        this.ywPkName = ywPkName == null ? null : ywPkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.YW_INFO
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.YW_INFO
     *
     * @mbggenerated
     */
    public String getYwInfo() {
        return ywInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.YW_INFO
     *
     * @param ywInfo the value for TSSH.GC_YWLC_INFO_HIS.YW_INFO
     *
     * @mbggenerated
     */
    public void setYwInfo(String ywInfo) {
        this.ywInfo = ywInfo == null ? null : ywInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.TS_USER
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.TS_USER
     *
     * @mbggenerated
     */
    public String getTsUser() {
        return tsUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.TS_USER
     *
     * @param tsUser the value for TSSH.GC_YWLC_INFO_HIS.TS_USER
     *
     * @mbggenerated
     */
    public void setTsUser(String tsUser) {
        this.tsUser = tsUser == null ? null : tsUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.TS_NAME
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.TS_NAME
     *
     * @mbggenerated
     */
    public String getTsName() {
        return tsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.TS_NAME
     *
     * @param tsName the value for TSSH.GC_YWLC_INFO_HIS.TS_NAME
     *
     * @mbggenerated
     */
    public void setTsName(String tsName) {
        this.tsName = tsName == null ? null : tsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.TS_DATE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.TS_DATE
     *
     * @mbggenerated
     */
    public Date getTsDate() {
        return tsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.TS_DATE
     *
     * @param tsDate the value for TSSH.GC_YWLC_INFO_HIS.TS_DATE
     *
     * @mbggenerated
     */
    public void setTsDate(Date tsDate) {
        this.tsDate = tsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.JS_USER
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.JS_USER
     *
     * @mbggenerated
     */
    public String getJsUser() {
        return jsUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.JS_USER
     *
     * @param jsUser the value for TSSH.GC_YWLC_INFO_HIS.JS_USER
     *
     * @mbggenerated
     */
    public void setJsUser(String jsUser) {
        this.jsUser = jsUser == null ? null : jsUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.JS_NAME
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.JS_NAME
     *
     * @mbggenerated
     */
    public String getJsName() {
        return jsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.JS_NAME
     *
     * @param jsName the value for TSSH.GC_YWLC_INFO_HIS.JS_NAME
     *
     * @mbggenerated
     */
    public void setJsName(String jsName) {
        this.jsName = jsName == null ? null : jsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.JS_POST
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.JS_POST
     *
     * @mbggenerated
     */
    public String getJsPost() {
        return jsPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.JS_POST
     *
     * @param jsPost the value for TSSH.GC_YWLC_INFO_HIS.JS_POST
     *
     * @mbggenerated
     */
    public void setJsPost(String jsPost) {
        this.jsPost = jsPost == null ? null : jsPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.JS_POST_NAME
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.JS_POST_NAME
     *
     * @mbggenerated
     */
    public String getJsPostName() {
        return jsPostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.JS_POST_NAME
     *
     * @param jsPostName the value for TSSH.GC_YWLC_INFO_HIS.JS_POST_NAME
     *
     * @mbggenerated
     */
    public void setJsPostName(String jsPostName) {
        this.jsPostName = jsPostName == null ? null : jsPostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.OP_USER
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.OP_USER
     *
     * @mbggenerated
     */
    public String getOpUser() {
        return opUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.OP_USER
     *
     * @param opUser the value for TSSH.GC_YWLC_INFO_HIS.OP_USER
     *
     * @mbggenerated
     */
    public void setOpUser(String opUser) {
        this.opUser = opUser == null ? null : opUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.OP_NAME
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.OP_NAME
     *
     * @mbggenerated
     */
    public String getOpName() {
        return opName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.OP_NAME
     *
     * @param opName the value for TSSH.GC_YWLC_INFO_HIS.OP_NAME
     *
     * @mbggenerated
     */
    public void setOpName(String opName) {
        this.opName = opName == null ? null : opName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.OP_DATE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.OP_DATE
     *
     * @mbggenerated
     */
    public Date getOpDate() {
        return opDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.OP_DATE
     *
     * @param opDate the value for TSSH.GC_YWLC_INFO_HIS.OP_DATE
     *
     * @mbggenerated
     */
    public void setOpDate(Date opDate) {
        this.opDate = opDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_USER
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.HT_USER
     *
     * @mbggenerated
     */
    public String getHtUser() {
        return htUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_USER
     *
     * @param htUser the value for TSSH.GC_YWLC_INFO_HIS.HT_USER
     *
     * @mbggenerated
     */
    public void setHtUser(String htUser) {
        this.htUser = htUser == null ? null : htUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_NAME
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.HT_NAME
     *
     * @mbggenerated
     */
    public String getHtName() {
        return htName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_NAME
     *
     * @param htName the value for TSSH.GC_YWLC_INFO_HIS.HT_NAME
     *
     * @mbggenerated
     */
    public void setHtName(String htName) {
        this.htName = htName == null ? null : htName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_DATE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.HT_DATE
     *
     * @mbggenerated
     */
    public Date getHtDate() {
        return htDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_DATE
     *
     * @param htDate the value for TSSH.GC_YWLC_INFO_HIS.HT_DATE
     *
     * @mbggenerated
     */
    public void setHtDate(Date htDate) {
        this.htDate = htDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_REASON
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.HT_REASON
     *
     * @mbggenerated
     */
    public String getHtReason() {
        return htReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_REASON
     *
     * @param htReason the value for TSSH.GC_YWLC_INFO_HIS.HT_REASON
     *
     * @mbggenerated
     */
    public void setHtReason(String htReason) {
        this.htReason = htReason == null ? null : htReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_FLAG
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.ZF_FLAG
     *
     * @mbggenerated
     */
    public String getZfFlag() {
        return zfFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_FLAG
     *
     * @param zfFlag the value for TSSH.GC_YWLC_INFO_HIS.ZF_FLAG
     *
     * @mbggenerated
     */
    public void setZfFlag(String zfFlag) {
        this.zfFlag = zfFlag == null ? null : zfFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_USER
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.ZF_USER
     *
     * @mbggenerated
     */
    public String getZfUser() {
        return zfUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_USER
     *
     * @param zfUser the value for TSSH.GC_YWLC_INFO_HIS.ZF_USER
     *
     * @mbggenerated
     */
    public void setZfUser(String zfUser) {
        this.zfUser = zfUser == null ? null : zfUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_NAME
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.ZF_NAME
     *
     * @mbggenerated
     */
    public String getZfName() {
        return zfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_NAME
     *
     * @param zfName the value for TSSH.GC_YWLC_INFO_HIS.ZF_NAME
     *
     * @mbggenerated
     */
    public void setZfName(String zfName) {
        this.zfName = zfName == null ? null : zfName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_REASON
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.ZF_REASON
     *
     * @mbggenerated
     */
    public String getZfReason() {
        return zfReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_REASON
     *
     * @param zfReason the value for TSSH.GC_YWLC_INFO_HIS.ZF_REASON
     *
     * @mbggenerated
     */
    public void setZfReason(String zfReason) {
        this.zfReason = zfReason == null ? null : zfReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_DATE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.ZF_DATE
     *
     * @mbggenerated
     */
    public Date getZfDate() {
        return zfDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.ZF_DATE
     *
     * @param zfDate the value for TSSH.GC_YWLC_INFO_HIS.ZF_DATE
     *
     * @mbggenerated
     */
    public void setZfDate(Date zfDate) {
        this.zfDate = zfDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.ZH_FLAG
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.ZH_FLAG
     *
     * @mbggenerated
     */
    public String getZhFlag() {
        return zhFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.ZH_FLAG
     *
     * @param zhFlag the value for TSSH.GC_YWLC_INFO_HIS.ZH_FLAG
     *
     * @mbggenerated
     */
    public void setZhFlag(String zhFlag) {
        this.zhFlag = zhFlag == null ? null : zhFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.PL_FLAG
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.PL_FLAG
     *
     * @mbggenerated
     */
    public String getPlFlag() {
        return plFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.PL_FLAG
     *
     * @param plFlag the value for TSSH.GC_YWLC_INFO_HIS.PL_FLAG
     *
     * @mbggenerated
     */
    public void setPlFlag(String plFlag) {
        this.plFlag = plFlag == null ? null : plFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.FINISH_DATE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.FINISH_DATE
     *
     * @mbggenerated
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.FINISH_DATE
     *
     * @param finishDate the value for TSSH.GC_YWLC_INFO_HIS.FINISH_DATE
     *
     * @mbggenerated
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.NOTE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.NOTE
     *
     * @param note the value for TSSH.GC_YWLC_INFO_HIS.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.RSV_FLAG
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.RSV_FLAG
     *
     * @mbggenerated
     */
    public String getRsvFlag() {
        return rsvFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.RSV_FLAG
     *
     * @param rsvFlag the value for TSSH.GC_YWLC_INFO_HIS.RSV_FLAG
     *
     * @mbggenerated
     */
    public void setRsvFlag(String rsvFlag) {
        this.rsvFlag = rsvFlag == null ? null : rsvFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.USER_GROUP
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.USER_GROUP
     *
     * @mbggenerated
     */
    public String getUserGroup() {
        return userGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.USER_GROUP
     *
     * @param userGroup the value for TSSH.GC_YWLC_INFO_HIS.USER_GROUP
     *
     * @mbggenerated
     */
    public void setUserGroup(String userGroup) {
        this.userGroup = userGroup == null ? null : userGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.TX_LEV
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.TX_LEV
     *
     * @mbggenerated
     */
    public String getTxLev() {
        return txLev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.TX_LEV
     *
     * @param txLev the value for TSSH.GC_YWLC_INFO_HIS.TX_LEV
     *
     * @mbggenerated
     */
    public void setTxLev(String txLev) {
        this.txLev = txLev == null ? null : txLev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.TX_INFO
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.TX_INFO
     *
     * @mbggenerated
     */
    public String getTxInfo() {
        return txInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.TX_INFO
     *
     * @param txInfo the value for TSSH.GC_YWLC_INFO_HIS.TX_INFO
     *
     * @mbggenerated
     */
    public void setTxInfo(String txInfo) {
        this.txInfo = txInfo == null ? null : txInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.TX_USER
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.TX_USER
     *
     * @mbggenerated
     */
    public String getTxUser() {
        return txUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.TX_USER
     *
     * @param txUser the value for TSSH.GC_YWLC_INFO_HIS.TX_USER
     *
     * @mbggenerated
     */
    public void setTxUser(String txUser) {
        this.txUser = txUser == null ? null : txUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.TX_DATE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.TX_DATE
     *
     * @mbggenerated
     */
    public Date getTxDate() {
        return txDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.TX_DATE
     *
     * @param txDate the value for TSSH.GC_YWLC_INFO_HIS.TX_DATE
     *
     * @mbggenerated
     */
    public void setTxDate(Date txDate) {
        this.txDate = txDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.SWCODE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.SWCODE
     *
     * @mbggenerated
     */
    public String getSwcode() {
        return swcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.SWCODE
     *
     * @param swcode the value for TSSH.GC_YWLC_INFO_HIS.SWCODE
     *
     * @mbggenerated
     */
    public void setSwcode(String swcode) {
        this.swcode = swcode == null ? null : swcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.LC_NAME
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.LC_NAME
     *
     * @mbggenerated
     */
    public String getLcName() {
        return lcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.LC_NAME
     *
     * @param lcName the value for TSSH.GC_YWLC_INFO_HIS.LC_NAME
     *
     * @mbggenerated
     */
    public void setLcName(String lcName) {
        this.lcName = lcName == null ? null : lcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.BL_LIMIT
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.BL_LIMIT
     *
     * @mbggenerated
     */
    public String getBlLimit() {
        return blLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.BL_LIMIT
     *
     * @param blLimit the value for TSSH.GC_YWLC_INFO_HIS.BL_LIMIT
     *
     * @mbggenerated
     */
    public void setBlLimit(String blLimit) {
        this.blLimit = blLimit == null ? null : blLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_FLAG
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.HT_FLAG
     *
     * @mbggenerated
     */
    public String getHtFlag() {
        return htFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.HT_FLAG
     *
     * @param htFlag the value for TSSH.GC_YWLC_INFO_HIS.HT_FLAG
     *
     * @mbggenerated
     */
    public void setHtFlag(String htFlag) {
        this.htFlag = htFlag == null ? null : htFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.LOG_UUID
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.LOG_UUID
     *
     * @mbggenerated
     */
    public String getLogUuid() {
        return logUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.LOG_UUID
     *
     * @param logUuid the value for TSSH.GC_YWLC_INFO_HIS.LOG_UUID
     *
     * @mbggenerated
     */
    public void setLogUuid(String logUuid) {
        this.logUuid = logUuid == null ? null : logUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.IS_WZH
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.IS_WZH
     *
     * @mbggenerated
     */
    public String getIsWzh() {
        return isWzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.IS_WZH
     *
     * @param isWzh the value for TSSH.GC_YWLC_INFO_HIS.IS_WZH
     *
     * @mbggenerated
     */
    public void setIsWzh(String isWzh) {
        this.isWzh = isWzh == null ? null : isWzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.FLGLCD
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.FLGLCD
     *
     * @mbggenerated
     */
    public String getFlglcd() {
        return flglcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.FLGLCD
     *
     * @param flglcd the value for TSSH.GC_YWLC_INFO_HIS.FLGLCD
     *
     * @mbggenerated
     */
    public void setFlglcd(String flglcd) {
        this.flglcd = flglcd == null ? null : flglcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.QYDM
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.QYDM
     *
     * @mbggenerated
     */
    public String getQydm() {
        return qydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.QYDM
     *
     * @param qydm the value for TSSH.GC_YWLC_INFO_HIS.QYDM
     *
     * @mbggenerated
     */
    public void setQydm(String qydm) {
        this.qydm = qydm == null ? null : qydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.NSRDJ_NO
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.NSRDJ_NO
     *
     * @mbggenerated
     */
    public String getNsrdjNo() {
        return nsrdjNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.NSRDJ_NO
     *
     * @param nsrdjNo the value for TSSH.GC_YWLC_INFO_HIS.NSRDJ_NO
     *
     * @mbggenerated
     */
    public void setNsrdjNo(String nsrdjNo) {
        this.nsrdjNo = nsrdjNo == null ? null : nsrdjNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.SHXY_NO
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.SHXY_NO
     *
     * @mbggenerated
     */
    public String getShxyNo() {
        return shxyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.SHXY_NO
     *
     * @param shxyNo the value for TSSH.GC_YWLC_INFO_HIS.SHXY_NO
     *
     * @mbggenerated
     */
    public void setShxyNo(String shxyNo) {
        this.shxyNo = shxyNo == null ? null : shxyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.SLTZ_DATE
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.SLTZ_DATE
     *
     * @mbggenerated
     */
    public Date getSltzDate() {
        return sltzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.SLTZ_DATE
     *
     * @param sltzDate the value for TSSH.GC_YWLC_INFO_HIS.SLTZ_DATE
     *
     * @mbggenerated
     */
    public void setSltzDate(Date sltzDate) {
        this.sltzDate = sltzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.SBLY
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.SBLY
     *
     * @mbggenerated
     */
    public String getSbly() {
        return sbly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.SBLY
     *
     * @param sbly the value for TSSH.GC_YWLC_INFO_HIS.SBLY
     *
     * @mbggenerated
     */
    public void setSbly(String sbly) {
        this.sbly = sbly == null ? null : sbly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.S_LCT_ID
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.S_LCT_ID
     *
     * @mbggenerated
     */
    public String getsLctId() {
        return sLctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.S_LCT_ID
     *
     * @param sLctId the value for TSSH.GC_YWLC_INFO_HIS.S_LCT_ID
     *
     * @mbggenerated
     */
    public void setsLctId(String sLctId) {
        this.sLctId = sLctId == null ? null : sLctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.DP_FLAG
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.DP_FLAG
     *
     * @mbggenerated
     */
    public String getDpFlag() {
        return dpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.DP_FLAG
     *
     * @param dpFlag the value for TSSH.GC_YWLC_INFO_HIS.DP_FLAG
     *
     * @mbggenerated
     */
    public void setDpFlag(String dpFlag) {
        this.dpFlag = dpFlag == null ? null : dpFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSSH.GC_YWLC_INFO_HIS.EWM
     *
     * @return the value of TSSH.GC_YWLC_INFO_HIS.EWM
     *
     * @mbggenerated
     */
    public String getEwm() {
        return ewm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSSH.GC_YWLC_INFO_HIS.EWM
     *
     * @param ewm the value for TSSH.GC_YWLC_INFO_HIS.EWM
     *
     * @mbggenerated
     */
    public void setEwm(String ewm) {
        this.ewm = ewm == null ? null : ewm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSSH.GC_YWLC_INFO_HIS
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lcslid=").append(lcslid);
        sb.append(", lcId=").append(lcId);
        sb.append(", lctId=").append(lctId);
        sb.append(", state=").append(state);
        sb.append(", firing=").append(firing);
        sb.append(", lctHdid=").append(lctHdid);
        sb.append(", nodeId=").append(nodeId);
        sb.append(", lctHdidName=").append(lctHdidName);
        sb.append(", ywPk=").append(ywPk);
        sb.append(", ywPkName=").append(ywPkName);
        sb.append(", ywInfo=").append(ywInfo);
        sb.append(", tsUser=").append(tsUser);
        sb.append(", tsName=").append(tsName);
        sb.append(", tsDate=").append(tsDate);
        sb.append(", jsUser=").append(jsUser);
        sb.append(", jsName=").append(jsName);
        sb.append(", jsPost=").append(jsPost);
        sb.append(", jsPostName=").append(jsPostName);
        sb.append(", opUser=").append(opUser);
        sb.append(", opName=").append(opName);
        sb.append(", opDate=").append(opDate);
        sb.append(", htUser=").append(htUser);
        sb.append(", htName=").append(htName);
        sb.append(", htDate=").append(htDate);
        sb.append(", htReason=").append(htReason);
        sb.append(", zfFlag=").append(zfFlag);
        sb.append(", zfUser=").append(zfUser);
        sb.append(", zfName=").append(zfName);
        sb.append(", zfReason=").append(zfReason);
        sb.append(", zfDate=").append(zfDate);
        sb.append(", zhFlag=").append(zhFlag);
        sb.append(", plFlag=").append(plFlag);
        sb.append(", finishDate=").append(finishDate);
        sb.append(", note=").append(note);
        sb.append(", rsvFlag=").append(rsvFlag);
        sb.append(", userGroup=").append(userGroup);
        sb.append(", txLev=").append(txLev);
        sb.append(", txInfo=").append(txInfo);
        sb.append(", txUser=").append(txUser);
        sb.append(", txDate=").append(txDate);
        sb.append(", swcode=").append(swcode);
        sb.append(", lcName=").append(lcName);
        sb.append(", blLimit=").append(blLimit);
        sb.append(", htFlag=").append(htFlag);
        sb.append(", logUuid=").append(logUuid);
        sb.append(", isWzh=").append(isWzh);
        sb.append(", flglcd=").append(flglcd);
        sb.append(", qydm=").append(qydm);
        sb.append(", nsrdjNo=").append(nsrdjNo);
        sb.append(", shxyNo=").append(shxyNo);
        sb.append(", sltzDate=").append(sltzDate);
        sb.append(", sbly=").append(sbly);
        sb.append(", sLctId=").append(sLctId);
        sb.append(", dpFlag=").append(dpFlag);
        sb.append(", ewm=").append(ewm);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}