package com.tl.web.bjts.shzs.model.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TlRoleServiceProfileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public TlRoleServiceProfileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRoleDmIsNull() {
            addCriterion("ROLE_DM is null");
            return (Criteria) this;
        }

        public Criteria andRoleDmIsNotNull() {
            addCriterion("ROLE_DM is not null");
            return (Criteria) this;
        }

        public Criteria andRoleDmEqualTo(String value) {
            addCriterion("ROLE_DM =", value, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmNotEqualTo(String value) {
            addCriterion("ROLE_DM <>", value, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmGreaterThan(String value) {
            addCriterion("ROLE_DM >", value, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_DM >=", value, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmLessThan(String value) {
            addCriterion("ROLE_DM <", value, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmLessThanOrEqualTo(String value) {
            addCriterion("ROLE_DM <=", value, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmLike(String value) {
            addCriterion("ROLE_DM like", value, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmNotLike(String value) {
            addCriterion("ROLE_DM not like", value, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmIn(List<String> values) {
            addCriterion("ROLE_DM in", values, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmNotIn(List<String> values) {
            addCriterion("ROLE_DM not in", values, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmBetween(String value1, String value2) {
            addCriterion("ROLE_DM between", value1, value2, "roleDm");
            return (Criteria) this;
        }

        public Criteria andRoleDmNotBetween(String value1, String value2) {
            addCriterion("ROLE_DM not between", value1, value2, "roleDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmIsNull() {
            addCriterion("SERVICE_DM is null");
            return (Criteria) this;
        }

        public Criteria andServiceDmIsNotNull() {
            addCriterion("SERVICE_DM is not null");
            return (Criteria) this;
        }

        public Criteria andServiceDmEqualTo(String value) {
            addCriterion("SERVICE_DM =", value, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmNotEqualTo(String value) {
            addCriterion("SERVICE_DM <>", value, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmGreaterThan(String value) {
            addCriterion("SERVICE_DM >", value, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmGreaterThanOrEqualTo(String value) {
            addCriterion("SERVICE_DM >=", value, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmLessThan(String value) {
            addCriterion("SERVICE_DM <", value, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmLessThanOrEqualTo(String value) {
            addCriterion("SERVICE_DM <=", value, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmLike(String value) {
            addCriterion("SERVICE_DM like", value, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmNotLike(String value) {
            addCriterion("SERVICE_DM not like", value, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmIn(List<String> values) {
            addCriterion("SERVICE_DM in", values, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmNotIn(List<String> values) {
            addCriterion("SERVICE_DM not in", values, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmBetween(String value1, String value2) {
            addCriterion("SERVICE_DM between", value1, value2, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andServiceDmNotBetween(String value1, String value2) {
            addCriterion("SERVICE_DM not between", value1, value2, "serviceDm");
            return (Criteria) this;
        }

        public Criteria andCrtimeIsNull() {
            addCriterion("CRTIME is null");
            return (Criteria) this;
        }

        public Criteria andCrtimeIsNotNull() {
            addCriterion("CRTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCrtimeEqualTo(Date value) {
            addCriterion("CRTIME =", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeNotEqualTo(Date value) {
            addCriterion("CRTIME <>", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeGreaterThan(Date value) {
            addCriterion("CRTIME >", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CRTIME >=", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeLessThan(Date value) {
            addCriterion("CRTIME <", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeLessThanOrEqualTo(Date value) {
            addCriterion("CRTIME <=", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeIn(List<Date> values) {
            addCriterion("CRTIME in", values, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeNotIn(List<Date> values) {
            addCriterion("CRTIME not in", values, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeBetween(Date value1, Date value2) {
            addCriterion("CRTIME between", value1, value2, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeNotBetween(Date value1, Date value2) {
            addCriterion("CRTIME not between", value1, value2, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrnameIsNull() {
            addCriterion("CRNAME is null");
            return (Criteria) this;
        }

        public Criteria andCrnameIsNotNull() {
            addCriterion("CRNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCrnameEqualTo(String value) {
            addCriterion("CRNAME =", value, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameNotEqualTo(String value) {
            addCriterion("CRNAME <>", value, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameGreaterThan(String value) {
            addCriterion("CRNAME >", value, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameGreaterThanOrEqualTo(String value) {
            addCriterion("CRNAME >=", value, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameLessThan(String value) {
            addCriterion("CRNAME <", value, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameLessThanOrEqualTo(String value) {
            addCriterion("CRNAME <=", value, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameLike(String value) {
            addCriterion("CRNAME like", value, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameNotLike(String value) {
            addCriterion("CRNAME not like", value, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameIn(List<String> values) {
            addCriterion("CRNAME in", values, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameNotIn(List<String> values) {
            addCriterion("CRNAME not in", values, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameBetween(String value1, String value2) {
            addCriterion("CRNAME between", value1, value2, "crname");
            return (Criteria) this;
        }

        public Criteria andCrnameNotBetween(String value1, String value2) {
            addCriterion("CRNAME not between", value1, value2, "crname");
            return (Criteria) this;
        }

        public Criteria andUptimeIsNull() {
            addCriterion("UPTIME is null");
            return (Criteria) this;
        }

        public Criteria andUptimeIsNotNull() {
            addCriterion("UPTIME is not null");
            return (Criteria) this;
        }

        public Criteria andUptimeEqualTo(Date value) {
            addCriterion("UPTIME =", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeNotEqualTo(Date value) {
            addCriterion("UPTIME <>", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeGreaterThan(Date value) {
            addCriterion("UPTIME >", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPTIME >=", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeLessThan(Date value) {
            addCriterion("UPTIME <", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeLessThanOrEqualTo(Date value) {
            addCriterion("UPTIME <=", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeIn(List<Date> values) {
            addCriterion("UPTIME in", values, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeNotIn(List<Date> values) {
            addCriterion("UPTIME not in", values, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeBetween(Date value1, Date value2) {
            addCriterion("UPTIME between", value1, value2, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeNotBetween(Date value1, Date value2) {
            addCriterion("UPTIME not between", value1, value2, "uptime");
            return (Criteria) this;
        }

        public Criteria andUpnameIsNull() {
            addCriterion("UPNAME is null");
            return (Criteria) this;
        }

        public Criteria andUpnameIsNotNull() {
            addCriterion("UPNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUpnameEqualTo(String value) {
            addCriterion("UPNAME =", value, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameNotEqualTo(String value) {
            addCriterion("UPNAME <>", value, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameGreaterThan(String value) {
            addCriterion("UPNAME >", value, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameGreaterThanOrEqualTo(String value) {
            addCriterion("UPNAME >=", value, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameLessThan(String value) {
            addCriterion("UPNAME <", value, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameLessThanOrEqualTo(String value) {
            addCriterion("UPNAME <=", value, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameLike(String value) {
            addCriterion("UPNAME like", value, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameNotLike(String value) {
            addCriterion("UPNAME not like", value, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameIn(List<String> values) {
            addCriterion("UPNAME in", values, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameNotIn(List<String> values) {
            addCriterion("UPNAME not in", values, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameBetween(String value1, String value2) {
            addCriterion("UPNAME between", value1, value2, "upname");
            return (Criteria) this;
        }

        public Criteria andUpnameNotBetween(String value1, String value2) {
            addCriterion("UPNAME not between", value1, value2, "upname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_CFG_ROLE_SERVICE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}