package com.tl.web.bjts.shzs.model.domain;

import java.io.Serializable;
import java.util.Date;

public class TlRoleProfile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_ROLE.ROLE_DM
     *
     * @mbggenerated
     */
    private String roleDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_ROLE.ROLE_MC
     *
     * @mbggenerated
     */
    private String roleMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_ROLE.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_ROLE.CRTIME
     *
     * @mbggenerated
     */
    private Date crtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_ROLE.CRNAME
     *
     * @mbggenerated
     */
    private String crname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_ROLE.UPTIME
     *
     * @mbggenerated
     */
    private Date uptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_ROLE.UPNAME
     *
     * @mbggenerated
     */
    private String upname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_ROLE.QYBZ
     *
     * @mbggenerated
     */
    private String qybz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DM_ROLE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_ROLE.ROLE_DM
     *
     * @return the value of DM_ROLE.ROLE_DM
     *
     * @mbggenerated
     */
    public String getRoleDm() {
        return roleDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_ROLE.ROLE_DM
     *
     * @param roleDm the value for DM_ROLE.ROLE_DM
     *
     * @mbggenerated
     */
    public void setRoleDm(String roleDm) {
        this.roleDm = roleDm == null ? null : roleDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_ROLE.ROLE_MC
     *
     * @return the value of DM_ROLE.ROLE_MC
     *
     * @mbggenerated
     */
    public String getRoleMc() {
        return roleMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_ROLE.ROLE_MC
     *
     * @param roleMc the value for DM_ROLE.ROLE_MC
     *
     * @mbggenerated
     */
    public void setRoleMc(String roleMc) {
        this.roleMc = roleMc == null ? null : roleMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_ROLE.DESCRIPTION
     *
     * @return the value of DM_ROLE.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_ROLE.DESCRIPTION
     *
     * @param description the value for DM_ROLE.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_ROLE.CRTIME
     *
     * @return the value of DM_ROLE.CRTIME
     *
     * @mbggenerated
     */
    public Date getCrtime() {
        return crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_ROLE.CRTIME
     *
     * @param crtime the value for DM_ROLE.CRTIME
     *
     * @mbggenerated
     */
    public void setCrtime(Date crtime) {
        this.crtime = crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_ROLE.CRNAME
     *
     * @return the value of DM_ROLE.CRNAME
     *
     * @mbggenerated
     */
    public String getCrname() {
        return crname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_ROLE.CRNAME
     *
     * @param crname the value for DM_ROLE.CRNAME
     *
     * @mbggenerated
     */
    public void setCrname(String crname) {
        this.crname = crname == null ? null : crname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_ROLE.UPTIME
     *
     * @return the value of DM_ROLE.UPTIME
     *
     * @mbggenerated
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_ROLE.UPTIME
     *
     * @param uptime the value for DM_ROLE.UPTIME
     *
     * @mbggenerated
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_ROLE.UPNAME
     *
     * @return the value of DM_ROLE.UPNAME
     *
     * @mbggenerated
     */
    public String getUpname() {
        return upname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_ROLE.UPNAME
     *
     * @param upname the value for DM_ROLE.UPNAME
     *
     * @mbggenerated
     */
    public void setUpname(String upname) {
        this.upname = upname == null ? null : upname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_ROLE.QYBZ
     *
     * @return the value of DM_ROLE.QYBZ
     *
     * @mbggenerated
     */
    public String getQybz() {
        return qybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_ROLE.QYBZ
     *
     * @param qybz the value for DM_ROLE.QYBZ
     *
     * @mbggenerated
     */
    public void setQybz(String qybz) {
        this.qybz = qybz == null ? null : qybz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_ROLE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleDm=").append(roleDm);
        sb.append(", roleMc=").append(roleMc);
        sb.append(", description=").append(description);
        sb.append(", crtime=").append(crtime);
        sb.append(", crname=").append(crname);
        sb.append(", uptime=").append(uptime);
        sb.append(", upname=").append(upname);
        sb.append(", qybz=").append(qybz);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}