package com.tl.web.bjts.shzs.model.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TlRwTxbExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public TlRwTxbExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahIsNull() {
            addCriterion("NSRDZDAH is null");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahIsNotNull() {
            addCriterion("NSRDZDAH is not null");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH =", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahNotEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH <>", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahGreaterThan(BigDecimal value) {
            addCriterion("NSRDZDAH >", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH >=", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahLessThan(BigDecimal value) {
            addCriterion("NSRDZDAH <", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH <=", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahIn(List<BigDecimal> values) {
            addCriterion("NSRDZDAH in", values, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahNotIn(List<BigDecimal> values) {
            addCriterion("NSRDZDAH not in", values, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NSRDZDAH between", value1, value2, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NSRDZDAH not between", value1, value2, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andRwlxDmIsNull() {
            addCriterion("RWLX_DM is null");
            return (Criteria) this;
        }

        public Criteria andRwlxDmIsNotNull() {
            addCriterion("RWLX_DM is not null");
            return (Criteria) this;
        }

        public Criteria andRwlxDmEqualTo(String value) {
            addCriterion("RWLX_DM =", value, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmNotEqualTo(String value) {
            addCriterion("RWLX_DM <>", value, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmGreaterThan(String value) {
            addCriterion("RWLX_DM >", value, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmGreaterThanOrEqualTo(String value) {
            addCriterion("RWLX_DM >=", value, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmLessThan(String value) {
            addCriterion("RWLX_DM <", value, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmLessThanOrEqualTo(String value) {
            addCriterion("RWLX_DM <=", value, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmLike(String value) {
            addCriterion("RWLX_DM like", value, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmNotLike(String value) {
            addCriterion("RWLX_DM not like", value, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmIn(List<String> values) {
            addCriterion("RWLX_DM in", values, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmNotIn(List<String> values) {
            addCriterion("RWLX_DM not in", values, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmBetween(String value1, String value2) {
            addCriterion("RWLX_DM between", value1, value2, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwlxDmNotBetween(String value1, String value2) {
            addCriterion("RWLX_DM not between", value1, value2, "rwlxDm");
            return (Criteria) this;
        }

        public Criteria andRwbtIsNull() {
            addCriterion("RWBT is null");
            return (Criteria) this;
        }

        public Criteria andRwbtIsNotNull() {
            addCriterion("RWBT is not null");
            return (Criteria) this;
        }

        public Criteria andRwbtEqualTo(String value) {
            addCriterion("RWBT =", value, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtNotEqualTo(String value) {
            addCriterion("RWBT <>", value, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtGreaterThan(String value) {
            addCriterion("RWBT >", value, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtGreaterThanOrEqualTo(String value) {
            addCriterion("RWBT >=", value, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtLessThan(String value) {
            addCriterion("RWBT <", value, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtLessThanOrEqualTo(String value) {
            addCriterion("RWBT <=", value, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtLike(String value) {
            addCriterion("RWBT like", value, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtNotLike(String value) {
            addCriterion("RWBT not like", value, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtIn(List<String> values) {
            addCriterion("RWBT in", values, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtNotIn(List<String> values) {
            addCriterion("RWBT not in", values, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtBetween(String value1, String value2) {
            addCriterion("RWBT between", value1, value2, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwbtNotBetween(String value1, String value2) {
            addCriterion("RWBT not between", value1, value2, "rwbt");
            return (Criteria) this;
        }

        public Criteria andRwnrIsNull() {
            addCriterion("RWNR is null");
            return (Criteria) this;
        }

        public Criteria andRwnrIsNotNull() {
            addCriterion("RWNR is not null");
            return (Criteria) this;
        }

        public Criteria andRwnrEqualTo(String value) {
            addCriterion("RWNR =", value, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrNotEqualTo(String value) {
            addCriterion("RWNR <>", value, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrGreaterThan(String value) {
            addCriterion("RWNR >", value, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrGreaterThanOrEqualTo(String value) {
            addCriterion("RWNR >=", value, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrLessThan(String value) {
            addCriterion("RWNR <", value, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrLessThanOrEqualTo(String value) {
            addCriterion("RWNR <=", value, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrLike(String value) {
            addCriterion("RWNR like", value, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrNotLike(String value) {
            addCriterion("RWNR not like", value, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrIn(List<String> values) {
            addCriterion("RWNR in", values, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrNotIn(List<String> values) {
            addCriterion("RWNR not in", values, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrBetween(String value1, String value2) {
            addCriterion("RWNR between", value1, value2, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwnrNotBetween(String value1, String value2) {
            addCriterion("RWNR not between", value1, value2, "rwnr");
            return (Criteria) this;
        }

        public Criteria andRwlyIsNull() {
            addCriterion("RWLY is null");
            return (Criteria) this;
        }

        public Criteria andRwlyIsNotNull() {
            addCriterion("RWLY is not null");
            return (Criteria) this;
        }

        public Criteria andRwlyEqualTo(String value) {
            addCriterion("RWLY =", value, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyNotEqualTo(String value) {
            addCriterion("RWLY <>", value, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyGreaterThan(String value) {
            addCriterion("RWLY >", value, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyGreaterThanOrEqualTo(String value) {
            addCriterion("RWLY >=", value, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyLessThan(String value) {
            addCriterion("RWLY <", value, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyLessThanOrEqualTo(String value) {
            addCriterion("RWLY <=", value, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyLike(String value) {
            addCriterion("RWLY like", value, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyNotLike(String value) {
            addCriterion("RWLY not like", value, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyIn(List<String> values) {
            addCriterion("RWLY in", values, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyNotIn(List<String> values) {
            addCriterion("RWLY not in", values, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyBetween(String value1, String value2) {
            addCriterion("RWLY between", value1, value2, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwlyNotBetween(String value1, String value2) {
            addCriterion("RWLY not between", value1, value2, "rwly");
            return (Criteria) this;
        }

        public Criteria andRwztDmIsNull() {
            addCriterion("RWZT_DM is null");
            return (Criteria) this;
        }

        public Criteria andRwztDmIsNotNull() {
            addCriterion("RWZT_DM is not null");
            return (Criteria) this;
        }

        public Criteria andRwztDmEqualTo(String value) {
            addCriterion("RWZT_DM =", value, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmNotEqualTo(String value) {
            addCriterion("RWZT_DM <>", value, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmGreaterThan(String value) {
            addCriterion("RWZT_DM >", value, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmGreaterThanOrEqualTo(String value) {
            addCriterion("RWZT_DM >=", value, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmLessThan(String value) {
            addCriterion("RWZT_DM <", value, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmLessThanOrEqualTo(String value) {
            addCriterion("RWZT_DM <=", value, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmLike(String value) {
            addCriterion("RWZT_DM like", value, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmNotLike(String value) {
            addCriterion("RWZT_DM not like", value, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmIn(List<String> values) {
            addCriterion("RWZT_DM in", values, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmNotIn(List<String> values) {
            addCriterion("RWZT_DM not in", values, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmBetween(String value1, String value2) {
            addCriterion("RWZT_DM between", value1, value2, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andRwztDmNotBetween(String value1, String value2) {
            addCriterion("RWZT_DM not between", value1, value2, "rwztDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmIsNull() {
            addCriterion("YWLX_DM is null");
            return (Criteria) this;
        }

        public Criteria andYwlxDmIsNotNull() {
            addCriterion("YWLX_DM is not null");
            return (Criteria) this;
        }

        public Criteria andYwlxDmEqualTo(String value) {
            addCriterion("YWLX_DM =", value, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmNotEqualTo(String value) {
            addCriterion("YWLX_DM <>", value, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmGreaterThan(String value) {
            addCriterion("YWLX_DM >", value, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmGreaterThanOrEqualTo(String value) {
            addCriterion("YWLX_DM >=", value, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmLessThan(String value) {
            addCriterion("YWLX_DM <", value, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmLessThanOrEqualTo(String value) {
            addCriterion("YWLX_DM <=", value, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmLike(String value) {
            addCriterion("YWLX_DM like", value, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmNotLike(String value) {
            addCriterion("YWLX_DM not like", value, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmIn(List<String> values) {
            addCriterion("YWLX_DM in", values, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmNotIn(List<String> values) {
            addCriterion("YWLX_DM not in", values, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmBetween(String value1, String value2) {
            addCriterion("YWLX_DM between", value1, value2, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwlxDmNotBetween(String value1, String value2) {
            addCriterion("YWLX_DM not between", value1, value2, "ywlxDm");
            return (Criteria) this;
        }

        public Criteria andYwqxIsNull() {
            addCriterion("YWQX is null");
            return (Criteria) this;
        }

        public Criteria andYwqxIsNotNull() {
            addCriterion("YWQX is not null");
            return (Criteria) this;
        }

        public Criteria andYwqxEqualTo(String value) {
            addCriterion("YWQX =", value, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxNotEqualTo(String value) {
            addCriterion("YWQX <>", value, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxGreaterThan(String value) {
            addCriterion("YWQX >", value, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxGreaterThanOrEqualTo(String value) {
            addCriterion("YWQX >=", value, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxLessThan(String value) {
            addCriterion("YWQX <", value, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxLessThanOrEqualTo(String value) {
            addCriterion("YWQX <=", value, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxLike(String value) {
            addCriterion("YWQX like", value, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxNotLike(String value) {
            addCriterion("YWQX not like", value, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxIn(List<String> values) {
            addCriterion("YWQX in", values, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxNotIn(List<String> values) {
            addCriterion("YWQX not in", values, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxBetween(String value1, String value2) {
            addCriterion("YWQX between", value1, value2, "ywqx");
            return (Criteria) this;
        }

        public Criteria andYwqxNotBetween(String value1, String value2) {
            addCriterion("YWQX not between", value1, value2, "ywqx");
            return (Criteria) this;
        }

        public Criteria andSwryDmIsNull() {
            addCriterion("SWRY_DM is null");
            return (Criteria) this;
        }

        public Criteria andSwryDmIsNotNull() {
            addCriterion("SWRY_DM is not null");
            return (Criteria) this;
        }

        public Criteria andSwryDmEqualTo(String value) {
            addCriterion("SWRY_DM =", value, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmNotEqualTo(String value) {
            addCriterion("SWRY_DM <>", value, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmGreaterThan(String value) {
            addCriterion("SWRY_DM >", value, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmGreaterThanOrEqualTo(String value) {
            addCriterion("SWRY_DM >=", value, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmLessThan(String value) {
            addCriterion("SWRY_DM <", value, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmLessThanOrEqualTo(String value) {
            addCriterion("SWRY_DM <=", value, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmLike(String value) {
            addCriterion("SWRY_DM like", value, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmNotLike(String value) {
            addCriterion("SWRY_DM not like", value, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmIn(List<String> values) {
            addCriterion("SWRY_DM in", values, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmNotIn(List<String> values) {
            addCriterion("SWRY_DM not in", values, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmBetween(String value1, String value2) {
            addCriterion("SWRY_DM between", value1, value2, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryDmNotBetween(String value1, String value2) {
            addCriterion("SWRY_DM not between", value1, value2, "swryDm");
            return (Criteria) this;
        }

        public Criteria andSwryMcIsNull() {
            addCriterion("SWRY_MC is null");
            return (Criteria) this;
        }

        public Criteria andSwryMcIsNotNull() {
            addCriterion("SWRY_MC is not null");
            return (Criteria) this;
        }

        public Criteria andSwryMcEqualTo(String value) {
            addCriterion("SWRY_MC =", value, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcNotEqualTo(String value) {
            addCriterion("SWRY_MC <>", value, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcGreaterThan(String value) {
            addCriterion("SWRY_MC >", value, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcGreaterThanOrEqualTo(String value) {
            addCriterion("SWRY_MC >=", value, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcLessThan(String value) {
            addCriterion("SWRY_MC <", value, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcLessThanOrEqualTo(String value) {
            addCriterion("SWRY_MC <=", value, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcLike(String value) {
            addCriterion("SWRY_MC like", value, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcNotLike(String value) {
            addCriterion("SWRY_MC not like", value, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcIn(List<String> values) {
            addCriterion("SWRY_MC in", values, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcNotIn(List<String> values) {
            addCriterion("SWRY_MC not in", values, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcBetween(String value1, String value2) {
            addCriterion("SWRY_MC between", value1, value2, "swryMc");
            return (Criteria) this;
        }

        public Criteria andSwryMcNotBetween(String value1, String value2) {
            addCriterion("SWRY_MC not between", value1, value2, "swryMc");
            return (Criteria) this;
        }

        public Criteria andLxdhIsNull() {
            addCriterion("LXDH is null");
            return (Criteria) this;
        }

        public Criteria andLxdhIsNotNull() {
            addCriterion("LXDH is not null");
            return (Criteria) this;
        }

        public Criteria andLxdhEqualTo(String value) {
            addCriterion("LXDH =", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotEqualTo(String value) {
            addCriterion("LXDH <>", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhGreaterThan(String value) {
            addCriterion("LXDH >", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhGreaterThanOrEqualTo(String value) {
            addCriterion("LXDH >=", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhLessThan(String value) {
            addCriterion("LXDH <", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhLessThanOrEqualTo(String value) {
            addCriterion("LXDH <=", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhLike(String value) {
            addCriterion("LXDH like", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotLike(String value) {
            addCriterion("LXDH not like", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhIn(List<String> values) {
            addCriterion("LXDH in", values, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotIn(List<String> values) {
            addCriterion("LXDH not in", values, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhBetween(String value1, String value2) {
            addCriterion("LXDH between", value1, value2, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotBetween(String value1, String value2) {
            addCriterion("LXDH not between", value1, value2, "lxdh");
            return (Criteria) this;
        }

        public Criteria andCjrqIsNull() {
            addCriterion("CJRQ is null");
            return (Criteria) this;
        }

        public Criteria andCjrqIsNotNull() {
            addCriterion("CJRQ is not null");
            return (Criteria) this;
        }

        public Criteria andCjrqEqualTo(Date value) {
            addCriterion("CJRQ =", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqNotEqualTo(Date value) {
            addCriterion("CJRQ <>", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqGreaterThan(Date value) {
            addCriterion("CJRQ >", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqGreaterThanOrEqualTo(Date value) {
            addCriterion("CJRQ >=", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqLessThan(Date value) {
            addCriterion("CJRQ <", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqLessThanOrEqualTo(Date value) {
            addCriterion("CJRQ <=", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqIn(List<Date> values) {
            addCriterion("CJRQ in", values, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqNotIn(List<Date> values) {
            addCriterion("CJRQ not in", values, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqBetween(Date value1, Date value2) {
            addCriterion("CJRQ between", value1, value2, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqNotBetween(Date value1, Date value2) {
            addCriterion("CJRQ not between", value1, value2, "cjrq");
            return (Criteria) this;
        }

        public Criteria andJzrqIsNull() {
            addCriterion("JZRQ is null");
            return (Criteria) this;
        }

        public Criteria andJzrqIsNotNull() {
            addCriterion("JZRQ is not null");
            return (Criteria) this;
        }

        public Criteria andJzrqEqualTo(Date value) {
            addCriterionForJDBCDate("JZRQ =", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("JZRQ <>", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqGreaterThan(Date value) {
            addCriterionForJDBCDate("JZRQ >", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("JZRQ >=", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqLessThan(Date value) {
            addCriterionForJDBCDate("JZRQ <", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("JZRQ <=", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqIn(List<Date> values) {
            addCriterionForJDBCDate("JZRQ in", values, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqNotIn(List<Date> values) {
            addCriterionForJDBCDate("JZRQ not in", values, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("JZRQ between", value1, value2, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("JZRQ not between", value1, value2, "jzrq");
            return (Criteria) this;
        }

        public Criteria andSwjgDmIsNull() {
            addCriterion("SWJG_DM is null");
            return (Criteria) this;
        }

        public Criteria andSwjgDmIsNotNull() {
            addCriterion("SWJG_DM is not null");
            return (Criteria) this;
        }

        public Criteria andSwjgDmEqualTo(String value) {
            addCriterion("SWJG_DM =", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmNotEqualTo(String value) {
            addCriterion("SWJG_DM <>", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmGreaterThan(String value) {
            addCriterion("SWJG_DM >", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmGreaterThanOrEqualTo(String value) {
            addCriterion("SWJG_DM >=", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmLessThan(String value) {
            addCriterion("SWJG_DM <", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmLessThanOrEqualTo(String value) {
            addCriterion("SWJG_DM <=", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmLike(String value) {
            addCriterion("SWJG_DM like", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmNotLike(String value) {
            addCriterion("SWJG_DM not like", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmIn(List<String> values) {
            addCriterion("SWJG_DM in", values, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmNotIn(List<String> values) {
            addCriterion("SWJG_DM not in", values, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmBetween(String value1, String value2) {
            addCriterion("SWJG_DM between", value1, value2, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmNotBetween(String value1, String value2) {
            addCriterion("SWJG_DM not between", value1, value2, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgMcIsNull() {
            addCriterion("SWJG_MC is null");
            return (Criteria) this;
        }

        public Criteria andSwjgMcIsNotNull() {
            addCriterion("SWJG_MC is not null");
            return (Criteria) this;
        }

        public Criteria andSwjgMcEqualTo(String value) {
            addCriterion("SWJG_MC =", value, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcNotEqualTo(String value) {
            addCriterion("SWJG_MC <>", value, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcGreaterThan(String value) {
            addCriterion("SWJG_MC >", value, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcGreaterThanOrEqualTo(String value) {
            addCriterion("SWJG_MC >=", value, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcLessThan(String value) {
            addCriterion("SWJG_MC <", value, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcLessThanOrEqualTo(String value) {
            addCriterion("SWJG_MC <=", value, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcLike(String value) {
            addCriterion("SWJG_MC like", value, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcNotLike(String value) {
            addCriterion("SWJG_MC not like", value, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcIn(List<String> values) {
            addCriterion("SWJG_MC in", values, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcNotIn(List<String> values) {
            addCriterion("SWJG_MC not in", values, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcBetween(String value1, String value2) {
            addCriterion("SWJG_MC between", value1, value2, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andSwjgMcNotBetween(String value1, String value2) {
            addCriterion("SWJG_MC not between", value1, value2, "swjgMc");
            return (Criteria) this;
        }

        public Criteria andYwgjzIsNull() {
            addCriterion("YWGJZ is null");
            return (Criteria) this;
        }

        public Criteria andYwgjzIsNotNull() {
            addCriterion("YWGJZ is not null");
            return (Criteria) this;
        }

        public Criteria andYwgjzEqualTo(Long value) {
            addCriterion("YWGJZ =", value, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andYwgjzNotEqualTo(Long value) {
            addCriterion("YWGJZ <>", value, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andYwgjzGreaterThan(Long value) {
            addCriterion("YWGJZ >", value, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andYwgjzGreaterThanOrEqualTo(Long value) {
            addCriterion("YWGJZ >=", value, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andYwgjzLessThan(Long value) {
            addCriterion("YWGJZ <", value, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andYwgjzLessThanOrEqualTo(Long value) {
            addCriterion("YWGJZ <=", value, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andYwgjzIn(List<Long> values) {
            addCriterion("YWGJZ in", values, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andYwgjzNotIn(List<Long> values) {
            addCriterion("YWGJZ not in", values, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andYwgjzBetween(Long value1, Long value2) {
            addCriterion("YWGJZ between", value1, value2, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andYwgjzNotBetween(Long value1, Long value2) {
            addCriterion("YWGJZ not between", value1, value2, "ywgjz");
            return (Criteria) this;
        }

        public Criteria andWcrqIsNull() {
            addCriterion("WCRQ is null");
            return (Criteria) this;
        }

        public Criteria andWcrqIsNotNull() {
            addCriterion("WCRQ is not null");
            return (Criteria) this;
        }

        public Criteria andWcrqEqualTo(Date value) {
            addCriterion("WCRQ =", value, "wcrq");
            return (Criteria) this;
        }

        public Criteria andWcrqNotEqualTo(Date value) {
            addCriterion("WCRQ <>", value, "wcrq");
            return (Criteria) this;
        }

        public Criteria andWcrqGreaterThan(Date value) {
            addCriterion("WCRQ >", value, "wcrq");
            return (Criteria) this;
        }

        public Criteria andWcrqGreaterThanOrEqualTo(Date value) {
            addCriterion("WCRQ >=", value, "wcrq");
            return (Criteria) this;
        }

        public Criteria andWcrqLessThan(Date value) {
            addCriterion("WCRQ <", value, "wcrq");
            return (Criteria) this;
        }

        public Criteria andWcrqLessThanOrEqualTo(Date value) {
            addCriterion("WCRQ <=", value, "wcrq");
            return (Criteria) this;
        }

        public Criteria andWcrqIn(List<Date> values) {
            addCriterion("WCRQ in", values, "wcrq");
            return (Criteria) this;
        }

        public Criteria andWcrqNotIn(List<Date> values) {
            addCriterion("WCRQ not in", values, "wcrq");
            return (Criteria) this;
        }

        public Criteria andWcrqBetween(Date value1, Date value2) {
            addCriterion("WCRQ between", value1, value2, "wcrq");
            return (Criteria) this;
        }

        public Criteria andWcrqNotBetween(Date value1, Date value2) {
            addCriterion("WCRQ not between", value1, value2, "wcrq");
            return (Criteria) this;
        }

        public Criteria andThyyIsNull() {
            addCriterion("THYY is null");
            return (Criteria) this;
        }

        public Criteria andThyyIsNotNull() {
            addCriterion("THYY is not null");
            return (Criteria) this;
        }

        public Criteria andThyyEqualTo(String value) {
            addCriterion("THYY =", value, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyNotEqualTo(String value) {
            addCriterion("THYY <>", value, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyGreaterThan(String value) {
            addCriterion("THYY >", value, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyGreaterThanOrEqualTo(String value) {
            addCriterion("THYY >=", value, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyLessThan(String value) {
            addCriterion("THYY <", value, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyLessThanOrEqualTo(String value) {
            addCriterion("THYY <=", value, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyLike(String value) {
            addCriterion("THYY like", value, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyNotLike(String value) {
            addCriterion("THYY not like", value, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyIn(List<String> values) {
            addCriterion("THYY in", values, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyNotIn(List<String> values) {
            addCriterion("THYY not in", values, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyBetween(String value1, String value2) {
            addCriterion("THYY between", value1, value2, "thyy");
            return (Criteria) this;
        }

        public Criteria andThyyNotBetween(String value1, String value2) {
            addCriterion("THYY not between", value1, value2, "thyy");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andClcsIsNull() {
            addCriterion("CLCS is null");
            return (Criteria) this;
        }

        public Criteria andClcsIsNotNull() {
            addCriterion("CLCS is not null");
            return (Criteria) this;
        }

        public Criteria andClcsEqualTo(Integer value) {
            addCriterion("CLCS =", value, "clcs");
            return (Criteria) this;
        }

        public Criteria andClcsNotEqualTo(Integer value) {
            addCriterion("CLCS <>", value, "clcs");
            return (Criteria) this;
        }

        public Criteria andClcsGreaterThan(Integer value) {
            addCriterion("CLCS >", value, "clcs");
            return (Criteria) this;
        }

        public Criteria andClcsGreaterThanOrEqualTo(Integer value) {
            addCriterion("CLCS >=", value, "clcs");
            return (Criteria) this;
        }

        public Criteria andClcsLessThan(Integer value) {
            addCriterion("CLCS <", value, "clcs");
            return (Criteria) this;
        }

        public Criteria andClcsLessThanOrEqualTo(Integer value) {
            addCriterion("CLCS <=", value, "clcs");
            return (Criteria) this;
        }

        public Criteria andClcsIn(List<Integer> values) {
            addCriterion("CLCS in", values, "clcs");
            return (Criteria) this;
        }

        public Criteria andClcsNotIn(List<Integer> values) {
            addCriterion("CLCS not in", values, "clcs");
            return (Criteria) this;
        }

        public Criteria andClcsBetween(Integer value1, Integer value2) {
            addCriterion("CLCS between", value1, value2, "clcs");
            return (Criteria) this;
        }

        public Criteria andClcsNotBetween(Integer value1, Integer value2) {
            addCriterion("CLCS not between", value1, value2, "clcs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RW_RWTXB
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RW_RWTXB
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}