package com.tl.web.bjts.shzs.model.domain;

import java.util.ArrayList;
import java.util.List;

public class TlSbxxProfileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public TlSbxxProfileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNsrsbhIsNull() {
            addCriterion("NSRSBH is null");
            return (Criteria) this;
        }

        public Criteria andNsrsbhIsNotNull() {
            addCriterion("NSRSBH is not null");
            return (Criteria) this;
        }

        public Criteria andNsrsbhEqualTo(String value) {
            addCriterion("NSRSBH =", value, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhNotEqualTo(String value) {
            addCriterion("NSRSBH <>", value, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhGreaterThan(String value) {
            addCriterion("NSRSBH >", value, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhGreaterThanOrEqualTo(String value) {
            addCriterion("NSRSBH >=", value, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhLessThan(String value) {
            addCriterion("NSRSBH <", value, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhLessThanOrEqualTo(String value) {
            addCriterion("NSRSBH <=", value, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhLike(String value) {
            addCriterion("NSRSBH like", value, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhNotLike(String value) {
            addCriterion("NSRSBH not like", value, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhIn(List<String> values) {
            addCriterion("NSRSBH in", values, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhNotIn(List<String> values) {
            addCriterion("NSRSBH not in", values, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhBetween(String value1, String value2) {
            addCriterion("NSRSBH between", value1, value2, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andNsrsbhNotBetween(String value1, String value2) {
            addCriterion("NSRSBH not between", value1, value2, "nsrsbh");
            return (Criteria) this;
        }

        public Criteria andQyhgdmIsNull() {
            addCriterion("QYHGDM is null");
            return (Criteria) this;
        }

        public Criteria andQyhgdmIsNotNull() {
            addCriterion("QYHGDM is not null");
            return (Criteria) this;
        }

        public Criteria andQyhgdmEqualTo(String value) {
            addCriterion("QYHGDM =", value, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmNotEqualTo(String value) {
            addCriterion("QYHGDM <>", value, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmGreaterThan(String value) {
            addCriterion("QYHGDM >", value, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmGreaterThanOrEqualTo(String value) {
            addCriterion("QYHGDM >=", value, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmLessThan(String value) {
            addCriterion("QYHGDM <", value, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmLessThanOrEqualTo(String value) {
            addCriterion("QYHGDM <=", value, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmLike(String value) {
            addCriterion("QYHGDM like", value, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmNotLike(String value) {
            addCriterion("QYHGDM not like", value, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmIn(List<String> values) {
            addCriterion("QYHGDM in", values, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmNotIn(List<String> values) {
            addCriterion("QYHGDM not in", values, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmBetween(String value1, String value2) {
            addCriterion("QYHGDM between", value1, value2, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andQyhgdmNotBetween(String value1, String value2) {
            addCriterion("QYHGDM not between", value1, value2, "qyhgdm");
            return (Criteria) this;
        }

        public Criteria andNsrmcIsNull() {
            addCriterion("NSRMC is null");
            return (Criteria) this;
        }

        public Criteria andNsrmcIsNotNull() {
            addCriterion("NSRMC is not null");
            return (Criteria) this;
        }

        public Criteria andNsrmcEqualTo(String value) {
            addCriterion("NSRMC =", value, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcNotEqualTo(String value) {
            addCriterion("NSRMC <>", value, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcGreaterThan(String value) {
            addCriterion("NSRMC >", value, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcGreaterThanOrEqualTo(String value) {
            addCriterion("NSRMC >=", value, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcLessThan(String value) {
            addCriterion("NSRMC <", value, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcLessThanOrEqualTo(String value) {
            addCriterion("NSRMC <=", value, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcLike(String value) {
            addCriterion("NSRMC like", value, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcNotLike(String value) {
            addCriterion("NSRMC not like", value, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcIn(List<String> values) {
            addCriterion("NSRMC in", values, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcNotIn(List<String> values) {
            addCriterion("NSRMC not in", values, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcBetween(String value1, String value2) {
            addCriterion("NSRMC between", value1, value2, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andNsrmcNotBetween(String value1, String value2) {
            addCriterion("NSRMC not between", value1, value2, "nsrmc");
            return (Criteria) this;
        }

        public Criteria andSwjgDmIsNull() {
            addCriterion("SWJG_DM is null");
            return (Criteria) this;
        }

        public Criteria andSwjgDmIsNotNull() {
            addCriterion("SWJG_DM is not null");
            return (Criteria) this;
        }

        public Criteria andSwjgDmEqualTo(String value) {
            addCriterion("SWJG_DM =", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmNotEqualTo(String value) {
            addCriterion("SWJG_DM <>", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmGreaterThan(String value) {
            addCriterion("SWJG_DM >", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmGreaterThanOrEqualTo(String value) {
            addCriterion("SWJG_DM >=", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmLessThan(String value) {
            addCriterion("SWJG_DM <", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmLessThanOrEqualTo(String value) {
            addCriterion("SWJG_DM <=", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmLike(String value) {
            addCriterion("SWJG_DM like", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmNotLike(String value) {
            addCriterion("SWJG_DM not like", value, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmIn(List<String> values) {
            addCriterion("SWJG_DM in", values, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmNotIn(List<String> values) {
            addCriterion("SWJG_DM not in", values, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmBetween(String value1, String value2) {
            addCriterion("SWJG_DM between", value1, value2, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andSwjgDmNotBetween(String value1, String value2) {
            addCriterion("SWJG_DM not between", value1, value2, "swjgDm");
            return (Criteria) this;
        }

        public Criteria andFlglcdIsNull() {
            addCriterion("FLGLCD is null");
            return (Criteria) this;
        }

        public Criteria andFlglcdIsNotNull() {
            addCriterion("FLGLCD is not null");
            return (Criteria) this;
        }

        public Criteria andFlglcdEqualTo(String value) {
            addCriterion("FLGLCD =", value, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdNotEqualTo(String value) {
            addCriterion("FLGLCD <>", value, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdGreaterThan(String value) {
            addCriterion("FLGLCD >", value, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdGreaterThanOrEqualTo(String value) {
            addCriterion("FLGLCD >=", value, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdLessThan(String value) {
            addCriterion("FLGLCD <", value, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdLessThanOrEqualTo(String value) {
            addCriterion("FLGLCD <=", value, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdLike(String value) {
            addCriterion("FLGLCD like", value, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdNotLike(String value) {
            addCriterion("FLGLCD not like", value, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdIn(List<String> values) {
            addCriterion("FLGLCD in", values, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdNotIn(List<String> values) {
            addCriterion("FLGLCD not in", values, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdBetween(String value1, String value2) {
            addCriterion("FLGLCD between", value1, value2, "flglcd");
            return (Criteria) this;
        }

        public Criteria andFlglcdNotBetween(String value1, String value2) {
            addCriterion("FLGLCD not between", value1, value2, "flglcd");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmIsNull() {
            addCriterion("TSJSFS_DM is null");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmIsNotNull() {
            addCriterion("TSJSFS_DM is not null");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmEqualTo(String value) {
            addCriterion("TSJSFS_DM =", value, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmNotEqualTo(String value) {
            addCriterion("TSJSFS_DM <>", value, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmGreaterThan(String value) {
            addCriterion("TSJSFS_DM >", value, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmGreaterThanOrEqualTo(String value) {
            addCriterion("TSJSFS_DM >=", value, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmLessThan(String value) {
            addCriterion("TSJSFS_DM <", value, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmLessThanOrEqualTo(String value) {
            addCriterion("TSJSFS_DM <=", value, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmLike(String value) {
            addCriterion("TSJSFS_DM like", value, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmNotLike(String value) {
            addCriterion("TSJSFS_DM not like", value, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmIn(List<String> values) {
            addCriterion("TSJSFS_DM in", values, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmNotIn(List<String> values) {
            addCriterion("TSJSFS_DM not in", values, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmBetween(String value1, String value2) {
            addCriterion("TSJSFS_DM between", value1, value2, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andTsjsfsDmNotBetween(String value1, String value2) {
            addCriterion("TSJSFS_DM not between", value1, value2, "tsjsfsDm");
            return (Criteria) this;
        }

        public Criteria andSbidIsNull() {
            addCriterion("SBID is null");
            return (Criteria) this;
        }

        public Criteria andSbidIsNotNull() {
            addCriterion("SBID is not null");
            return (Criteria) this;
        }

        public Criteria andSbidEqualTo(Long value) {
            addCriterion("SBID =", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidNotEqualTo(Long value) {
            addCriterion("SBID <>", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidGreaterThan(Long value) {
            addCriterion("SBID >", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidGreaterThanOrEqualTo(Long value) {
            addCriterion("SBID >=", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidLessThan(Long value) {
            addCriterion("SBID <", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidLessThanOrEqualTo(Long value) {
            addCriterion("SBID <=", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidIn(List<Long> values) {
            addCriterion("SBID in", values, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidNotIn(List<Long> values) {
            addCriterion("SBID not in", values, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidBetween(Long value1, Long value2) {
            addCriterion("SBID between", value1, value2, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidNotBetween(Long value1, Long value2) {
            addCriterion("SBID not between", value1, value2, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbywbDmIsNull() {
            addCriterion("SBYWB_DM is null");
            return (Criteria) this;
        }

        public Criteria andSbywbDmIsNotNull() {
            addCriterion("SBYWB_DM is not null");
            return (Criteria) this;
        }

        public Criteria andSbywbDmEqualTo(String value) {
            addCriterion("SBYWB_DM =", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmNotEqualTo(String value) {
            addCriterion("SBYWB_DM <>", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmGreaterThan(String value) {
            addCriterion("SBYWB_DM >", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmGreaterThanOrEqualTo(String value) {
            addCriterion("SBYWB_DM >=", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmLessThan(String value) {
            addCriterion("SBYWB_DM <", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmLessThanOrEqualTo(String value) {
            addCriterion("SBYWB_DM <=", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmLike(String value) {
            addCriterion("SBYWB_DM like", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmNotLike(String value) {
            addCriterion("SBYWB_DM not like", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmIn(List<String> values) {
            addCriterion("SBYWB_DM in", values, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmNotIn(List<String> values) {
            addCriterion("SBYWB_DM not in", values, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmBetween(String value1, String value2) {
            addCriterion("SBYWB_DM between", value1, value2, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmNotBetween(String value1, String value2) {
            addCriterion("SBYWB_DM not between", value1, value2, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSssqIsNull() {
            addCriterion("SSSQ is null");
            return (Criteria) this;
        }

        public Criteria andSssqIsNotNull() {
            addCriterion("SSSQ is not null");
            return (Criteria) this;
        }

        public Criteria andSssqEqualTo(String value) {
            addCriterion("SSSQ =", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqNotEqualTo(String value) {
            addCriterion("SSSQ <>", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqGreaterThan(String value) {
            addCriterion("SSSQ >", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqGreaterThanOrEqualTo(String value) {
            addCriterion("SSSQ >=", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqLessThan(String value) {
            addCriterion("SSSQ <", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqLessThanOrEqualTo(String value) {
            addCriterion("SSSQ <=", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqLike(String value) {
            addCriterion("SSSQ like", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqNotLike(String value) {
            addCriterion("SSSQ not like", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqIn(List<String> values) {
            addCriterion("SSSQ in", values, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqNotIn(List<String> values) {
            addCriterion("SSSQ not in", values, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqBetween(String value1, String value2) {
            addCriterion("SSSQ between", value1, value2, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqNotBetween(String value1, String value2) {
            addCriterion("SSSQ not between", value1, value2, "sssq");
            return (Criteria) this;
        }

        public Criteria andSbpcIsNull() {
            addCriterion("SBPC is null");
            return (Criteria) this;
        }

        public Criteria andSbpcIsNotNull() {
            addCriterion("SBPC is not null");
            return (Criteria) this;
        }

        public Criteria andSbpcEqualTo(Integer value) {
            addCriterion("SBPC =", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcNotEqualTo(Integer value) {
            addCriterion("SBPC <>", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcGreaterThan(Integer value) {
            addCriterion("SBPC >", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcGreaterThanOrEqualTo(Integer value) {
            addCriterion("SBPC >=", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcLessThan(Integer value) {
            addCriterion("SBPC <", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcLessThanOrEqualTo(Integer value) {
            addCriterion("SBPC <=", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcIn(List<Integer> values) {
            addCriterion("SBPC in", values, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcNotIn(List<Integer> values) {
            addCriterion("SBPC not in", values, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcBetween(Integer value1, Integer value2) {
            addCriterion("SBPC between", value1, value2, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcNotBetween(Integer value1, Integer value2) {
            addCriterion("SBPC not between", value1, value2, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbztDmIsNull() {
            addCriterion("SBZT_DM is null");
            return (Criteria) this;
        }

        public Criteria andSbztDmIsNotNull() {
            addCriterion("SBZT_DM is not null");
            return (Criteria) this;
        }

        public Criteria andSbztDmEqualTo(String value) {
            addCriterion("SBZT_DM =", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmNotEqualTo(String value) {
            addCriterion("SBZT_DM <>", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmGreaterThan(String value) {
            addCriterion("SBZT_DM >", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmGreaterThanOrEqualTo(String value) {
            addCriterion("SBZT_DM >=", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmLessThan(String value) {
            addCriterion("SBZT_DM <", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmLessThanOrEqualTo(String value) {
            addCriterion("SBZT_DM <=", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmLike(String value) {
            addCriterion("SBZT_DM like", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmNotLike(String value) {
            addCriterion("SBZT_DM not like", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmIn(List<String> values) {
            addCriterion("SBZT_DM in", values, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmNotIn(List<String> values) {
            addCriterion("SBZT_DM not in", values, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmBetween(String value1, String value2) {
            addCriterion("SBZT_DM between", value1, value2, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmNotBetween(String value1, String value2) {
            addCriterion("SBZT_DM not between", value1, value2, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbrqIsNull() {
            addCriterion("SBRQ is null");
            return (Criteria) this;
        }

        public Criteria andSbrqIsNotNull() {
            addCriterion("SBRQ is not null");
            return (Criteria) this;
        }

        public Criteria andSbrqEqualTo(String value) {
            addCriterion("SBRQ =", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqNotEqualTo(String value) {
            addCriterion("SBRQ <>", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqGreaterThan(String value) {
            addCriterion("SBRQ >", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqGreaterThanOrEqualTo(String value) {
            addCriterion("SBRQ >=", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqLessThan(String value) {
            addCriterion("SBRQ <", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqLessThanOrEqualTo(String value) {
            addCriterion("SBRQ <=", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqIn(List<String> values) {
            addCriterion("SBRQ in", values, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqNotIn(List<String> values) {
            addCriterion("SBRQ not in", values, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqBetween(String value1, String value2) {
            addCriterion("SBRQ between", value1, value2, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqNotBetween(String value1, String value2) {
            addCriterion("SBRQ not between", value1, value2, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbzlDmIsNull() {
            addCriterion("SBZL_DM is null");
            return (Criteria) this;
        }

        public Criteria andSbzlDmIsNotNull() {
            addCriterion("SBZL_DM is not null");
            return (Criteria) this;
        }

        public Criteria andSbzlDmEqualTo(String value) {
            addCriterion("SBZL_DM =", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmNotEqualTo(String value) {
            addCriterion("SBZL_DM <>", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmGreaterThan(String value) {
            addCriterion("SBZL_DM >", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmGreaterThanOrEqualTo(String value) {
            addCriterion("SBZL_DM >=", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmLessThan(String value) {
            addCriterion("SBZL_DM <", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmLessThanOrEqualTo(String value) {
            addCriterion("SBZL_DM <=", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmLike(String value) {
            addCriterion("SBZL_DM like", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmNotLike(String value) {
            addCriterion("SBZL_DM not like", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmIn(List<String> values) {
            addCriterion("SBZL_DM in", values, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmNotIn(List<String> values) {
            addCriterion("SBZL_DM not in", values, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmBetween(String value1, String value2) {
            addCriterion("SBZL_DM between", value1, value2, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmNotBetween(String value1, String value2) {
            addCriterion("SBZL_DM not between", value1, value2, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andZzsbbIsNull() {
            addCriterion("ZZSBB is null");
            return (Criteria) this;
        }

        public Criteria andZzsbbIsNotNull() {
            addCriterion("ZZSBB is not null");
            return (Criteria) this;
        }

        public Criteria andZzsbbEqualTo(String value) {
            addCriterion("ZZSBB =", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbNotEqualTo(String value) {
            addCriterion("ZZSBB <>", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbGreaterThan(String value) {
            addCriterion("ZZSBB >", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbGreaterThanOrEqualTo(String value) {
            addCriterion("ZZSBB >=", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbLessThan(String value) {
            addCriterion("ZZSBB <", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbLessThanOrEqualTo(String value) {
            addCriterion("ZZSBB <=", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbLike(String value) {
            addCriterion("ZZSBB like", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbNotLike(String value) {
            addCriterion("ZZSBB not like", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbIn(List<String> values) {
            addCriterion("ZZSBB in", values, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbNotIn(List<String> values) {
            addCriterion("ZZSBB not in", values, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbBetween(String value1, String value2) {
            addCriterion("ZZSBB between", value1, value2, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbNotBetween(String value1, String value2) {
            addCriterion("ZZSBB not between", value1, value2, "zzsbb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_SBXX_SBDR_FILEMODE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}