package com.tl.web.bjts.shzs.model.domain;

import java.io.Serializable;
import java.util.Date;

public class TlServiceProfile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_SERVICE.SERVICE_DM
     *
     * @mbggenerated
     */
    private String serviceDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_SERVICE.SERVICE_MC
     *
     * @mbggenerated
     */
    private String serviceMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_SERVICE.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_SERVICE.MENU_SET
     *
     * @mbggenerated
     */
    private String menuSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_SERVICE.CRTIME
     *
     * @mbggenerated
     */
    private Date crtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_SERVICE.CRNAME
     *
     * @mbggenerated
     */
    private String crname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_SERVICE.UPTIME
     *
     * @mbggenerated
     */
    private Date uptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_SERVICE.UPNAME
     *
     * @mbggenerated
     */
    private String upname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_SERVICE.QYBZ
     *
     * @mbggenerated
     */
    private String qybz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DM_SERVICE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_SERVICE.SERVICE_DM
     *
     * @return the value of DM_SERVICE.SERVICE_DM
     *
     * @mbggenerated
     */
    public String getServiceDm() {
        return serviceDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_SERVICE.SERVICE_DM
     *
     * @param serviceDm the value for DM_SERVICE.SERVICE_DM
     *
     * @mbggenerated
     */
    public void setServiceDm(String serviceDm) {
        this.serviceDm = serviceDm == null ? null : serviceDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_SERVICE.SERVICE_MC
     *
     * @return the value of DM_SERVICE.SERVICE_MC
     *
     * @mbggenerated
     */
    public String getServiceMc() {
        return serviceMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_SERVICE.SERVICE_MC
     *
     * @param serviceMc the value for DM_SERVICE.SERVICE_MC
     *
     * @mbggenerated
     */
    public void setServiceMc(String serviceMc) {
        this.serviceMc = serviceMc == null ? null : serviceMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_SERVICE.DESCRIPTION
     *
     * @return the value of DM_SERVICE.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_SERVICE.DESCRIPTION
     *
     * @param description the value for DM_SERVICE.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_SERVICE.MENU_SET
     *
     * @return the value of DM_SERVICE.MENU_SET
     *
     * @mbggenerated
     */
    public String getMenuSet() {
        return menuSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_SERVICE.MENU_SET
     *
     * @param menuSet the value for DM_SERVICE.MENU_SET
     *
     * @mbggenerated
     */
    public void setMenuSet(String menuSet) {
        this.menuSet = menuSet == null ? null : menuSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_SERVICE.CRTIME
     *
     * @return the value of DM_SERVICE.CRTIME
     *
     * @mbggenerated
     */
    public Date getCrtime() {
        return crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_SERVICE.CRTIME
     *
     * @param crtime the value for DM_SERVICE.CRTIME
     *
     * @mbggenerated
     */
    public void setCrtime(Date crtime) {
        this.crtime = crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_SERVICE.CRNAME
     *
     * @return the value of DM_SERVICE.CRNAME
     *
     * @mbggenerated
     */
    public String getCrname() {
        return crname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_SERVICE.CRNAME
     *
     * @param crname the value for DM_SERVICE.CRNAME
     *
     * @mbggenerated
     */
    public void setCrname(String crname) {
        this.crname = crname == null ? null : crname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_SERVICE.UPTIME
     *
     * @return the value of DM_SERVICE.UPTIME
     *
     * @mbggenerated
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_SERVICE.UPTIME
     *
     * @param uptime the value for DM_SERVICE.UPTIME
     *
     * @mbggenerated
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_SERVICE.UPNAME
     *
     * @return the value of DM_SERVICE.UPNAME
     *
     * @mbggenerated
     */
    public String getUpname() {
        return upname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_SERVICE.UPNAME
     *
     * @param upname the value for DM_SERVICE.UPNAME
     *
     * @mbggenerated
     */
    public void setUpname(String upname) {
        this.upname = upname == null ? null : upname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_SERVICE.QYBZ
     *
     * @return the value of DM_SERVICE.QYBZ
     *
     * @mbggenerated
     */
    public String getQybz() {
        return qybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_SERVICE.QYBZ
     *
     * @param qybz the value for DM_SERVICE.QYBZ
     *
     * @mbggenerated
     */
    public void setQybz(String qybz) {
        this.qybz = qybz == null ? null : qybz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_SERVICE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serviceDm=").append(serviceDm);
        sb.append(", serviceMc=").append(serviceMc);
        sb.append(", description=").append(description);
        sb.append(", menuSet=").append(menuSet);
        sb.append(", crtime=").append(crtime);
        sb.append(", crname=").append(crname);
        sb.append(", uptime=").append(uptime);
        sb.append(", upname=").append(upname);
        sb.append(", qybz=").append(qybz);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}