package com.tl.web.bjts.shzs.model.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TlShSbxxHzProfileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public TlShSbxxHzProfileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahIsNull() {
            addCriterion("NSRDZDAH is null");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahIsNotNull() {
            addCriterion("NSRDZDAH is not null");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH =", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahNotEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH <>", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahGreaterThan(BigDecimal value) {
            addCriterion("NSRDZDAH >", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH >=", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahLessThan(BigDecimal value) {
            addCriterion("NSRDZDAH <", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH <=", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahIn(List<BigDecimal> values) {
            addCriterion("NSRDZDAH in", values, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahNotIn(List<BigDecimal> values) {
            addCriterion("NSRDZDAH not in", values, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NSRDZDAH between", value1, value2, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NSRDZDAH not between", value1, value2, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andSbywbDmIsNull() {
            addCriterion("SBYWB_DM is null");
            return (Criteria) this;
        }

        public Criteria andSbywbDmIsNotNull() {
            addCriterion("SBYWB_DM is not null");
            return (Criteria) this;
        }

        public Criteria andSbywbDmEqualTo(String value) {
            addCriterion("SBYWB_DM =", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmNotEqualTo(String value) {
            addCriterion("SBYWB_DM <>", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmGreaterThan(String value) {
            addCriterion("SBYWB_DM >", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmGreaterThanOrEqualTo(String value) {
            addCriterion("SBYWB_DM >=", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmLessThan(String value) {
            addCriterion("SBYWB_DM <", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmLessThanOrEqualTo(String value) {
            addCriterion("SBYWB_DM <=", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmLike(String value) {
            addCriterion("SBYWB_DM like", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmNotLike(String value) {
            addCriterion("SBYWB_DM not like", value, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmIn(List<String> values) {
            addCriterion("SBYWB_DM in", values, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmNotIn(List<String> values) {
            addCriterion("SBYWB_DM not in", values, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmBetween(String value1, String value2) {
            addCriterion("SBYWB_DM between", value1, value2, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSbywbDmNotBetween(String value1, String value2) {
            addCriterion("SBYWB_DM not between", value1, value2, "sbywbDm");
            return (Criteria) this;
        }

        public Criteria andSssqIsNull() {
            addCriterion("SSSQ is null");
            return (Criteria) this;
        }

        public Criteria andSssqIsNotNull() {
            addCriterion("SSSQ is not null");
            return (Criteria) this;
        }

        public Criteria andSssqEqualTo(String value) {
            addCriterion("SSSQ =", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqNotEqualTo(String value) {
            addCriterion("SSSQ <>", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqGreaterThan(String value) {
            addCriterion("SSSQ >", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqGreaterThanOrEqualTo(String value) {
            addCriterion("SSSQ >=", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqLessThan(String value) {
            addCriterion("SSSQ <", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqLessThanOrEqualTo(String value) {
            addCriterion("SSSQ <=", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqLike(String value) {
            addCriterion("SSSQ like", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqNotLike(String value) {
            addCriterion("SSSQ not like", value, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqIn(List<String> values) {
            addCriterion("SSSQ in", values, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqNotIn(List<String> values) {
            addCriterion("SSSQ not in", values, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqBetween(String value1, String value2) {
            addCriterion("SSSQ between", value1, value2, "sssq");
            return (Criteria) this;
        }

        public Criteria andSssqNotBetween(String value1, String value2) {
            addCriterion("SSSQ not between", value1, value2, "sssq");
            return (Criteria) this;
        }

        public Criteria andSbpcIsNull() {
            addCriterion("SBPC is null");
            return (Criteria) this;
        }

        public Criteria andSbpcIsNotNull() {
            addCriterion("SBPC is not null");
            return (Criteria) this;
        }

        public Criteria andSbpcEqualTo(Integer value) {
            addCriterion("SBPC =", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcNotEqualTo(Integer value) {
            addCriterion("SBPC <>", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcGreaterThan(Integer value) {
            addCriterion("SBPC >", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcGreaterThanOrEqualTo(Integer value) {
            addCriterion("SBPC >=", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcLessThan(Integer value) {
            addCriterion("SBPC <", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcLessThanOrEqualTo(Integer value) {
            addCriterion("SBPC <=", value, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcIn(List<Integer> values) {
            addCriterion("SBPC in", values, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcNotIn(List<Integer> values) {
            addCriterion("SBPC not in", values, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcBetween(Integer value1, Integer value2) {
            addCriterion("SBPC between", value1, value2, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbpcNotBetween(Integer value1, Integer value2) {
            addCriterion("SBPC not between", value1, value2, "sbpc");
            return (Criteria) this;
        }

        public Criteria andSbrqIsNull() {
            addCriterion("SBRQ is null");
            return (Criteria) this;
        }

        public Criteria andSbrqIsNotNull() {
            addCriterion("SBRQ is not null");
            return (Criteria) this;
        }

        public Criteria andSbrqEqualTo(Date value) {
            addCriterion("SBRQ =", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqNotEqualTo(Date value) {
            addCriterion("SBRQ <>", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqGreaterThan(Date value) {
            addCriterion("SBRQ >", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqGreaterThanOrEqualTo(Date value) {
            addCriterion("SBRQ >=", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqLessThan(Date value) {
            addCriterion("SBRQ <", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqLessThanOrEqualTo(Date value) {
            addCriterion("SBRQ <=", value, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqIn(List<Date> values) {
            addCriterion("SBRQ in", values, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqNotIn(List<Date> values) {
            addCriterion("SBRQ not in", values, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqBetween(Date value1, Date value2) {
            addCriterion("SBRQ between", value1, value2, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbrqNotBetween(Date value1, Date value2) {
            addCriterion("SBRQ not between", value1, value2, "sbrq");
            return (Criteria) this;
        }

        public Criteria andSbztDmIsNull() {
            addCriterion("SBZT_DM is null");
            return (Criteria) this;
        }

        public Criteria andSbztDmIsNotNull() {
            addCriterion("SBZT_DM is not null");
            return (Criteria) this;
        }

        public Criteria andSbztDmEqualTo(String value) {
            addCriterion("SBZT_DM =", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmNotEqualTo(String value) {
            addCriterion("SBZT_DM <>", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmGreaterThan(String value) {
            addCriterion("SBZT_DM >", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmGreaterThanOrEqualTo(String value) {
            addCriterion("SBZT_DM >=", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmLessThan(String value) {
            addCriterion("SBZT_DM <", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmLessThanOrEqualTo(String value) {
            addCriterion("SBZT_DM <=", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmLike(String value) {
            addCriterion("SBZT_DM like", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmNotLike(String value) {
            addCriterion("SBZT_DM not like", value, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmIn(List<String> values) {
            addCriterion("SBZT_DM in", values, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmNotIn(List<String> values) {
            addCriterion("SBZT_DM not in", values, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmBetween(String value1, String value2) {
            addCriterion("SBZT_DM between", value1, value2, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andSbztDmNotBetween(String value1, String value2) {
            addCriterion("SBZT_DM not between", value1, value2, "sbztDm");
            return (Criteria) this;
        }

        public Criteria andLzhjIsNull() {
            addCriterion("LZHJ is null");
            return (Criteria) this;
        }

        public Criteria andLzhjIsNotNull() {
            addCriterion("LZHJ is not null");
            return (Criteria) this;
        }

        public Criteria andLzhjEqualTo(String value) {
            addCriterion("LZHJ =", value, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjNotEqualTo(String value) {
            addCriterion("LZHJ <>", value, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjGreaterThan(String value) {
            addCriterion("LZHJ >", value, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjGreaterThanOrEqualTo(String value) {
            addCriterion("LZHJ >=", value, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjLessThan(String value) {
            addCriterion("LZHJ <", value, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjLessThanOrEqualTo(String value) {
            addCriterion("LZHJ <=", value, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjLike(String value) {
            addCriterion("LZHJ like", value, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjNotLike(String value) {
            addCriterion("LZHJ not like", value, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjIn(List<String> values) {
            addCriterion("LZHJ in", values, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjNotIn(List<String> values) {
            addCriterion("LZHJ not in", values, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjBetween(String value1, String value2) {
            addCriterion("LZHJ between", value1, value2, "lzhj");
            return (Criteria) this;
        }

        public Criteria andLzhjNotBetween(String value1, String value2) {
            addCriterion("LZHJ not between", value1, value2, "lzhj");
            return (Criteria) this;
        }

        public Criteria andFkrqIsNull() {
            addCriterion("FKRQ is null");
            return (Criteria) this;
        }

        public Criteria andFkrqIsNotNull() {
            addCriterion("FKRQ is not null");
            return (Criteria) this;
        }

        public Criteria andFkrqEqualTo(Date value) {
            addCriterion("FKRQ =", value, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkrqNotEqualTo(Date value) {
            addCriterion("FKRQ <>", value, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkrqGreaterThan(Date value) {
            addCriterion("FKRQ >", value, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkrqGreaterThanOrEqualTo(Date value) {
            addCriterion("FKRQ >=", value, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkrqLessThan(Date value) {
            addCriterion("FKRQ <", value, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkrqLessThanOrEqualTo(Date value) {
            addCriterion("FKRQ <=", value, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkrqIn(List<Date> values) {
            addCriterion("FKRQ in", values, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkrqNotIn(List<Date> values) {
            addCriterion("FKRQ not in", values, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkrqBetween(Date value1, Date value2) {
            addCriterion("FKRQ between", value1, value2, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkrqNotBetween(Date value1, Date value2) {
            addCriterion("FKRQ not between", value1, value2, "fkrq");
            return (Criteria) this;
        }

        public Criteria andFkxxIsNull() {
            addCriterion("FKXX is null");
            return (Criteria) this;
        }

        public Criteria andFkxxIsNotNull() {
            addCriterion("FKXX is not null");
            return (Criteria) this;
        }

        public Criteria andFkxxEqualTo(String value) {
            addCriterion("FKXX =", value, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxNotEqualTo(String value) {
            addCriterion("FKXX <>", value, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxGreaterThan(String value) {
            addCriterion("FKXX >", value, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxGreaterThanOrEqualTo(String value) {
            addCriterion("FKXX >=", value, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxLessThan(String value) {
            addCriterion("FKXX <", value, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxLessThanOrEqualTo(String value) {
            addCriterion("FKXX <=", value, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxLike(String value) {
            addCriterion("FKXX like", value, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxNotLike(String value) {
            addCriterion("FKXX not like", value, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxIn(List<String> values) {
            addCriterion("FKXX in", values, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxNotIn(List<String> values) {
            addCriterion("FKXX not in", values, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxBetween(String value1, String value2) {
            addCriterion("FKXX between", value1, value2, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFkxxNotBetween(String value1, String value2) {
            addCriterion("FKXX not between", value1, value2, "fkxx");
            return (Criteria) this;
        }

        public Criteria andFjslIsNull() {
            addCriterion("FJSL is null");
            return (Criteria) this;
        }

        public Criteria andFjslIsNotNull() {
            addCriterion("FJSL is not null");
            return (Criteria) this;
        }

        public Criteria andFjslEqualTo(Integer value) {
            addCriterion("FJSL =", value, "fjsl");
            return (Criteria) this;
        }

        public Criteria andFjslNotEqualTo(Integer value) {
            addCriterion("FJSL <>", value, "fjsl");
            return (Criteria) this;
        }

        public Criteria andFjslGreaterThan(Integer value) {
            addCriterion("FJSL >", value, "fjsl");
            return (Criteria) this;
        }

        public Criteria andFjslGreaterThanOrEqualTo(Integer value) {
            addCriterion("FJSL >=", value, "fjsl");
            return (Criteria) this;
        }

        public Criteria andFjslLessThan(Integer value) {
            addCriterion("FJSL <", value, "fjsl");
            return (Criteria) this;
        }

        public Criteria andFjslLessThanOrEqualTo(Integer value) {
            addCriterion("FJSL <=", value, "fjsl");
            return (Criteria) this;
        }

        public Criteria andFjslIn(List<Integer> values) {
            addCriterion("FJSL in", values, "fjsl");
            return (Criteria) this;
        }

        public Criteria andFjslNotIn(List<Integer> values) {
            addCriterion("FJSL not in", values, "fjsl");
            return (Criteria) this;
        }

        public Criteria andFjslBetween(Integer value1, Integer value2) {
            addCriterion("FJSL between", value1, value2, "fjsl");
            return (Criteria) this;
        }

        public Criteria andFjslNotBetween(Integer value1, Integer value2) {
            addCriterion("FJSL not between", value1, value2, "fjsl");
            return (Criteria) this;
        }

        public Criteria andQybjIsNull() {
            addCriterion("QYBJ is null");
            return (Criteria) this;
        }

        public Criteria andQybjIsNotNull() {
            addCriterion("QYBJ is not null");
            return (Criteria) this;
        }

        public Criteria andQybjEqualTo(String value) {
            addCriterion("QYBJ =", value, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjNotEqualTo(String value) {
            addCriterion("QYBJ <>", value, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjGreaterThan(String value) {
            addCriterion("QYBJ >", value, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjGreaterThanOrEqualTo(String value) {
            addCriterion("QYBJ >=", value, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjLessThan(String value) {
            addCriterion("QYBJ <", value, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjLessThanOrEqualTo(String value) {
            addCriterion("QYBJ <=", value, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjLike(String value) {
            addCriterion("QYBJ like", value, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjNotLike(String value) {
            addCriterion("QYBJ not like", value, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjIn(List<String> values) {
            addCriterion("QYBJ in", values, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjNotIn(List<String> values) {
            addCriterion("QYBJ not in", values, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjBetween(String value1, String value2) {
            addCriterion("QYBJ between", value1, value2, "qybj");
            return (Criteria) this;
        }

        public Criteria andQybjNotBetween(String value1, String value2) {
            addCriterion("QYBJ not between", value1, value2, "qybj");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andCjrqIsNull() {
            addCriterion("CJRQ is null");
            return (Criteria) this;
        }

        public Criteria andCjrqIsNotNull() {
            addCriterion("CJRQ is not null");
            return (Criteria) this;
        }

        public Criteria andCjrqEqualTo(Date value) {
            addCriterion("CJRQ =", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqNotEqualTo(Date value) {
            addCriterion("CJRQ <>", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqGreaterThan(Date value) {
            addCriterion("CJRQ >", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqGreaterThanOrEqualTo(Date value) {
            addCriterion("CJRQ >=", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqLessThan(Date value) {
            addCriterion("CJRQ <", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqLessThanOrEqualTo(Date value) {
            addCriterion("CJRQ <=", value, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqIn(List<Date> values) {
            addCriterion("CJRQ in", values, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqNotIn(List<Date> values) {
            addCriterion("CJRQ not in", values, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqBetween(Date value1, Date value2) {
            addCriterion("CJRQ between", value1, value2, "cjrq");
            return (Criteria) this;
        }

        public Criteria andCjrqNotBetween(Date value1, Date value2) {
            addCriterion("CJRQ not between", value1, value2, "cjrq");
            return (Criteria) this;
        }

        public Criteria andXgrqIsNull() {
            addCriterion("XGRQ is null");
            return (Criteria) this;
        }

        public Criteria andXgrqIsNotNull() {
            addCriterion("XGRQ is not null");
            return (Criteria) this;
        }

        public Criteria andXgrqEqualTo(Date value) {
            addCriterion("XGRQ =", value, "xgrq");
            return (Criteria) this;
        }

        public Criteria andXgrqNotEqualTo(Date value) {
            addCriterion("XGRQ <>", value, "xgrq");
            return (Criteria) this;
        }

        public Criteria andXgrqGreaterThan(Date value) {
            addCriterion("XGRQ >", value, "xgrq");
            return (Criteria) this;
        }

        public Criteria andXgrqGreaterThanOrEqualTo(Date value) {
            addCriterion("XGRQ >=", value, "xgrq");
            return (Criteria) this;
        }

        public Criteria andXgrqLessThan(Date value) {
            addCriterion("XGRQ <", value, "xgrq");
            return (Criteria) this;
        }

        public Criteria andXgrqLessThanOrEqualTo(Date value) {
            addCriterion("XGRQ <=", value, "xgrq");
            return (Criteria) this;
        }

        public Criteria andXgrqIn(List<Date> values) {
            addCriterion("XGRQ in", values, "xgrq");
            return (Criteria) this;
        }

        public Criteria andXgrqNotIn(List<Date> values) {
            addCriterion("XGRQ not in", values, "xgrq");
            return (Criteria) this;
        }

        public Criteria andXgrqBetween(Date value1, Date value2) {
            addCriterion("XGRQ between", value1, value2, "xgrq");
            return (Criteria) this;
        }

        public Criteria andXgrqNotBetween(Date value1, Date value2) {
            addCriterion("XGRQ not between", value1, value2, "xgrq");
            return (Criteria) this;
        }

        public Criteria andTqbzIsNull() {
            addCriterion("TQBZ is null");
            return (Criteria) this;
        }

        public Criteria andTqbzIsNotNull() {
            addCriterion("TQBZ is not null");
            return (Criteria) this;
        }

        public Criteria andTqbzEqualTo(String value) {
            addCriterion("TQBZ =", value, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzNotEqualTo(String value) {
            addCriterion("TQBZ <>", value, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzGreaterThan(String value) {
            addCriterion("TQBZ >", value, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzGreaterThanOrEqualTo(String value) {
            addCriterion("TQBZ >=", value, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzLessThan(String value) {
            addCriterion("TQBZ <", value, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzLessThanOrEqualTo(String value) {
            addCriterion("TQBZ <=", value, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzLike(String value) {
            addCriterion("TQBZ like", value, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzNotLike(String value) {
            addCriterion("TQBZ not like", value, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzIn(List<String> values) {
            addCriterion("TQBZ in", values, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzNotIn(List<String> values) {
            addCriterion("TQBZ not in", values, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzBetween(String value1, String value2) {
            addCriterion("TQBZ between", value1, value2, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqbzNotBetween(String value1, String value2) {
            addCriterion("TQBZ not between", value1, value2, "tqbz");
            return (Criteria) this;
        }

        public Criteria andTqsjIsNull() {
            addCriterion("TQSJ is null");
            return (Criteria) this;
        }

        public Criteria andTqsjIsNotNull() {
            addCriterion("TQSJ is not null");
            return (Criteria) this;
        }

        public Criteria andTqsjEqualTo(Date value) {
            addCriterion("TQSJ =", value, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqsjNotEqualTo(Date value) {
            addCriterion("TQSJ <>", value, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqsjGreaterThan(Date value) {
            addCriterion("TQSJ >", value, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqsjGreaterThanOrEqualTo(Date value) {
            addCriterion("TQSJ >=", value, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqsjLessThan(Date value) {
            addCriterion("TQSJ <", value, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqsjLessThanOrEqualTo(Date value) {
            addCriterion("TQSJ <=", value, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqsjIn(List<Date> values) {
            addCriterion("TQSJ in", values, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqsjNotIn(List<Date> values) {
            addCriterion("TQSJ not in", values, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqsjBetween(Date value1, Date value2) {
            addCriterion("TQSJ between", value1, value2, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqsjNotBetween(Date value1, Date value2) {
            addCriterion("TQSJ not between", value1, value2, "tqsj");
            return (Criteria) this;
        }

        public Criteria andTqcsIsNull() {
            addCriterion("TQCS is null");
            return (Criteria) this;
        }

        public Criteria andTqcsIsNotNull() {
            addCriterion("TQCS is not null");
            return (Criteria) this;
        }

        public Criteria andTqcsEqualTo(Integer value) {
            addCriterion("TQCS =", value, "tqcs");
            return (Criteria) this;
        }

        public Criteria andTqcsNotEqualTo(Integer value) {
            addCriterion("TQCS <>", value, "tqcs");
            return (Criteria) this;
        }

        public Criteria andTqcsGreaterThan(Integer value) {
            addCriterion("TQCS >", value, "tqcs");
            return (Criteria) this;
        }

        public Criteria andTqcsGreaterThanOrEqualTo(Integer value) {
            addCriterion("TQCS >=", value, "tqcs");
            return (Criteria) this;
        }

        public Criteria andTqcsLessThan(Integer value) {
            addCriterion("TQCS <", value, "tqcs");
            return (Criteria) this;
        }

        public Criteria andTqcsLessThanOrEqualTo(Integer value) {
            addCriterion("TQCS <=", value, "tqcs");
            return (Criteria) this;
        }

        public Criteria andTqcsIn(List<Integer> values) {
            addCriterion("TQCS in", values, "tqcs");
            return (Criteria) this;
        }

        public Criteria andTqcsNotIn(List<Integer> values) {
            addCriterion("TQCS not in", values, "tqcs");
            return (Criteria) this;
        }

        public Criteria andTqcsBetween(Integer value1, Integer value2) {
            addCriterion("TQCS between", value1, value2, "tqcs");
            return (Criteria) this;
        }

        public Criteria andTqcsNotBetween(Integer value1, Integer value2) {
            addCriterion("TQCS not between", value1, value2, "tqcs");
            return (Criteria) this;
        }

        public Criteria andSbyyIsNull() {
            addCriterion("SBYY is null");
            return (Criteria) this;
        }

        public Criteria andSbyyIsNotNull() {
            addCriterion("SBYY is not null");
            return (Criteria) this;
        }

        public Criteria andSbyyEqualTo(String value) {
            addCriterion("SBYY =", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyNotEqualTo(String value) {
            addCriterion("SBYY <>", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyGreaterThan(String value) {
            addCriterion("SBYY >", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyGreaterThanOrEqualTo(String value) {
            addCriterion("SBYY >=", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyLessThan(String value) {
            addCriterion("SBYY <", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyLessThanOrEqualTo(String value) {
            addCriterion("SBYY <=", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyLike(String value) {
            addCriterion("SBYY like", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyNotLike(String value) {
            addCriterion("SBYY not like", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyIn(List<String> values) {
            addCriterion("SBYY in", values, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyNotIn(List<String> values) {
            addCriterion("SBYY not in", values, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyBetween(String value1, String value2) {
            addCriterion("SBYY between", value1, value2, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyNotBetween(String value1, String value2) {
            addCriterion("SBYY not between", value1, value2, "sbyy");
            return (Criteria) this;
        }

        public Criteria andYxjIsNull() {
            addCriterion("YXJ is null");
            return (Criteria) this;
        }

        public Criteria andYxjIsNotNull() {
            addCriterion("YXJ is not null");
            return (Criteria) this;
        }

        public Criteria andYxjEqualTo(Integer value) {
            addCriterion("YXJ =", value, "yxj");
            return (Criteria) this;
        }

        public Criteria andYxjNotEqualTo(Integer value) {
            addCriterion("YXJ <>", value, "yxj");
            return (Criteria) this;
        }

        public Criteria andYxjGreaterThan(Integer value) {
            addCriterion("YXJ >", value, "yxj");
            return (Criteria) this;
        }

        public Criteria andYxjGreaterThanOrEqualTo(Integer value) {
            addCriterion("YXJ >=", value, "yxj");
            return (Criteria) this;
        }

        public Criteria andYxjLessThan(Integer value) {
            addCriterion("YXJ <", value, "yxj");
            return (Criteria) this;
        }

        public Criteria andYxjLessThanOrEqualTo(Integer value) {
            addCriterion("YXJ <=", value, "yxj");
            return (Criteria) this;
        }

        public Criteria andYxjIn(List<Integer> values) {
            addCriterion("YXJ in", values, "yxj");
            return (Criteria) this;
        }

        public Criteria andYxjNotIn(List<Integer> values) {
            addCriterion("YXJ not in", values, "yxj");
            return (Criteria) this;
        }

        public Criteria andYxjBetween(Integer value1, Integer value2) {
            addCriterion("YXJ between", value1, value2, "yxj");
            return (Criteria) this;
        }

        public Criteria andYxjNotBetween(Integer value1, Integer value2) {
            addCriterion("YXJ not between", value1, value2, "yxj");
            return (Criteria) this;
        }

        public Criteria andSbsjIsNull() {
            addCriterion("SBSJ is null");
            return (Criteria) this;
        }

        public Criteria andSbsjIsNotNull() {
            addCriterion("SBSJ is not null");
            return (Criteria) this;
        }

        public Criteria andSbsjEqualTo(Date value) {
            addCriterion("SBSJ =", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjNotEqualTo(Date value) {
            addCriterion("SBSJ <>", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjGreaterThan(Date value) {
            addCriterion("SBSJ >", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjGreaterThanOrEqualTo(Date value) {
            addCriterion("SBSJ >=", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjLessThan(Date value) {
            addCriterion("SBSJ <", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjLessThanOrEqualTo(Date value) {
            addCriterion("SBSJ <=", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjIn(List<Date> values) {
            addCriterion("SBSJ in", values, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjNotIn(List<Date> values) {
            addCriterion("SBSJ not in", values, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjBetween(Date value1, Date value2) {
            addCriterion("SBSJ between", value1, value2, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjNotBetween(Date value1, Date value2) {
            addCriterion("SBSJ not between", value1, value2, "sbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjIsNull() {
            addCriterion("TBSJ is null");
            return (Criteria) this;
        }

        public Criteria andTbsjIsNotNull() {
            addCriterion("TBSJ is not null");
            return (Criteria) this;
        }

        public Criteria andTbsjEqualTo(Date value) {
            addCriterion("TBSJ =", value, "tbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjNotEqualTo(Date value) {
            addCriterion("TBSJ <>", value, "tbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjGreaterThan(Date value) {
            addCriterion("TBSJ >", value, "tbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjGreaterThanOrEqualTo(Date value) {
            addCriterion("TBSJ >=", value, "tbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjLessThan(Date value) {
            addCriterion("TBSJ <", value, "tbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjLessThanOrEqualTo(Date value) {
            addCriterion("TBSJ <=", value, "tbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjIn(List<Date> values) {
            addCriterion("TBSJ in", values, "tbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjNotIn(List<Date> values) {
            addCriterion("TBSJ not in", values, "tbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjBetween(Date value1, Date value2) {
            addCriterion("TBSJ between", value1, value2, "tbsj");
            return (Criteria) this;
        }

        public Criteria andTbsjNotBetween(Date value1, Date value2) {
            addCriterion("TBSJ not between", value1, value2, "tbsj");
            return (Criteria) this;
        }

        public Criteria andLcslidIsNull() {
            addCriterion("LCSLID is null");
            return (Criteria) this;
        }

        public Criteria andLcslidIsNotNull() {
            addCriterion("LCSLID is not null");
            return (Criteria) this;
        }

        public Criteria andLcslidEqualTo(String value) {
            addCriterion("LCSLID =", value, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidNotEqualTo(String value) {
            addCriterion("LCSLID <>", value, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidGreaterThan(String value) {
            addCriterion("LCSLID >", value, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidGreaterThanOrEqualTo(String value) {
            addCriterion("LCSLID >=", value, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidLessThan(String value) {
            addCriterion("LCSLID <", value, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidLessThanOrEqualTo(String value) {
            addCriterion("LCSLID <=", value, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidLike(String value) {
            addCriterion("LCSLID like", value, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidNotLike(String value) {
            addCriterion("LCSLID not like", value, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidIn(List<String> values) {
            addCriterion("LCSLID in", values, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidNotIn(List<String> values) {
            addCriterion("LCSLID not in", values, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidBetween(String value1, String value2) {
            addCriterion("LCSLID between", value1, value2, "lcslid");
            return (Criteria) this;
        }

        public Criteria andLcslidNotBetween(String value1, String value2) {
            addCriterion("LCSLID not between", value1, value2, "lcslid");
            return (Criteria) this;
        }

        public Criteria andTbcsIsNull() {
            addCriterion("TBCS is null");
            return (Criteria) this;
        }

        public Criteria andTbcsIsNotNull() {
            addCriterion("TBCS is not null");
            return (Criteria) this;
        }

        public Criteria andTbcsEqualTo(Integer value) {
            addCriterion("TBCS =", value, "tbcs");
            return (Criteria) this;
        }

        public Criteria andTbcsNotEqualTo(Integer value) {
            addCriterion("TBCS <>", value, "tbcs");
            return (Criteria) this;
        }

        public Criteria andTbcsGreaterThan(Integer value) {
            addCriterion("TBCS >", value, "tbcs");
            return (Criteria) this;
        }

        public Criteria andTbcsGreaterThanOrEqualTo(Integer value) {
            addCriterion("TBCS >=", value, "tbcs");
            return (Criteria) this;
        }

        public Criteria andTbcsLessThan(Integer value) {
            addCriterion("TBCS <", value, "tbcs");
            return (Criteria) this;
        }

        public Criteria andTbcsLessThanOrEqualTo(Integer value) {
            addCriterion("TBCS <=", value, "tbcs");
            return (Criteria) this;
        }

        public Criteria andTbcsIn(List<Integer> values) {
            addCriterion("TBCS in", values, "tbcs");
            return (Criteria) this;
        }

        public Criteria andTbcsNotIn(List<Integer> values) {
            addCriterion("TBCS not in", values, "tbcs");
            return (Criteria) this;
        }

        public Criteria andTbcsBetween(Integer value1, Integer value2) {
            addCriterion("TBCS between", value1, value2, "tbcs");
            return (Criteria) this;
        }

        public Criteria andTbcsNotBetween(Integer value1, Integer value2) {
            addCriterion("TBCS not between", value1, value2, "tbcs");
            return (Criteria) this;
        }

        public Criteria andSbzlDmIsNull() {
            addCriterion("SBZL_DM is null");
            return (Criteria) this;
        }

        public Criteria andSbzlDmIsNotNull() {
            addCriterion("SBZL_DM is not null");
            return (Criteria) this;
        }

        public Criteria andSbzlDmEqualTo(String value) {
            addCriterion("SBZL_DM =", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmNotEqualTo(String value) {
            addCriterion("SBZL_DM <>", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmGreaterThan(String value) {
            addCriterion("SBZL_DM >", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmGreaterThanOrEqualTo(String value) {
            addCriterion("SBZL_DM >=", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmLessThan(String value) {
            addCriterion("SBZL_DM <", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmLessThanOrEqualTo(String value) {
            addCriterion("SBZL_DM <=", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmLike(String value) {
            addCriterion("SBZL_DM like", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmNotLike(String value) {
            addCriterion("SBZL_DM not like", value, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmIn(List<String> values) {
            addCriterion("SBZL_DM in", values, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmNotIn(List<String> values) {
            addCriterion("SBZL_DM not in", values, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmBetween(String value1, String value2) {
            addCriterion("SBZL_DM between", value1, value2, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbzlDmNotBetween(String value1, String value2) {
            addCriterion("SBZL_DM not between", value1, value2, "sbzlDm");
            return (Criteria) this;
        }

        public Criteria andSbtypeIsNull() {
            addCriterion("SBTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSbtypeIsNotNull() {
            addCriterion("SBTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSbtypeEqualTo(String value) {
            addCriterion("SBTYPE =", value, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeNotEqualTo(String value) {
            addCriterion("SBTYPE <>", value, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeGreaterThan(String value) {
            addCriterion("SBTYPE >", value, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeGreaterThanOrEqualTo(String value) {
            addCriterion("SBTYPE >=", value, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeLessThan(String value) {
            addCriterion("SBTYPE <", value, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeLessThanOrEqualTo(String value) {
            addCriterion("SBTYPE <=", value, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeLike(String value) {
            addCriterion("SBTYPE like", value, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeNotLike(String value) {
            addCriterion("SBTYPE not like", value, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeIn(List<String> values) {
            addCriterion("SBTYPE in", values, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeNotIn(List<String> values) {
            addCriterion("SBTYPE not in", values, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeBetween(String value1, String value2) {
            addCriterion("SBTYPE between", value1, value2, "sbtype");
            return (Criteria) this;
        }

        public Criteria andSbtypeNotBetween(String value1, String value2) {
            addCriterion("SBTYPE not between", value1, value2, "sbtype");
            return (Criteria) this;
        }

        public Criteria andYsbzIsNull() {
            addCriterion("YSBZ is null");
            return (Criteria) this;
        }

        public Criteria andYsbzIsNotNull() {
            addCriterion("YSBZ is not null");
            return (Criteria) this;
        }

        public Criteria andYsbzEqualTo(String value) {
            addCriterion("YSBZ =", value, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzNotEqualTo(String value) {
            addCriterion("YSBZ <>", value, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzGreaterThan(String value) {
            addCriterion("YSBZ >", value, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzGreaterThanOrEqualTo(String value) {
            addCriterion("YSBZ >=", value, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzLessThan(String value) {
            addCriterion("YSBZ <", value, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzLessThanOrEqualTo(String value) {
            addCriterion("YSBZ <=", value, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzLike(String value) {
            addCriterion("YSBZ like", value, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzNotLike(String value) {
            addCriterion("YSBZ not like", value, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzIn(List<String> values) {
            addCriterion("YSBZ in", values, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzNotIn(List<String> values) {
            addCriterion("YSBZ not in", values, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzBetween(String value1, String value2) {
            addCriterion("YSBZ between", value1, value2, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYsbzNotBetween(String value1, String value2) {
            addCriterion("YSBZ not between", value1, value2, "ysbz");
            return (Criteria) this;
        }

        public Criteria andYstqsjIsNull() {
            addCriterion("YSTQSJ is null");
            return (Criteria) this;
        }

        public Criteria andYstqsjIsNotNull() {
            addCriterion("YSTQSJ is not null");
            return (Criteria) this;
        }

        public Criteria andYstqsjEqualTo(Date value) {
            addCriterion("YSTQSJ =", value, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYstqsjNotEqualTo(Date value) {
            addCriterion("YSTQSJ <>", value, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYstqsjGreaterThan(Date value) {
            addCriterion("YSTQSJ >", value, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYstqsjGreaterThanOrEqualTo(Date value) {
            addCriterion("YSTQSJ >=", value, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYstqsjLessThan(Date value) {
            addCriterion("YSTQSJ <", value, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYstqsjLessThanOrEqualTo(Date value) {
            addCriterion("YSTQSJ <=", value, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYstqsjIn(List<Date> values) {
            addCriterion("YSTQSJ in", values, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYstqsjNotIn(List<Date> values) {
            addCriterion("YSTQSJ not in", values, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYstqsjBetween(Date value1, Date value2) {
            addCriterion("YSTQSJ between", value1, value2, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYstqsjNotBetween(Date value1, Date value2) {
            addCriterion("YSTQSJ not between", value1, value2, "ystqsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjIsNull() {
            addCriterion("YSWCSJ is null");
            return (Criteria) this;
        }

        public Criteria andYswcsjIsNotNull() {
            addCriterion("YSWCSJ is not null");
            return (Criteria) this;
        }

        public Criteria andYswcsjEqualTo(Date value) {
            addCriterion("YSWCSJ =", value, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjNotEqualTo(Date value) {
            addCriterion("YSWCSJ <>", value, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjGreaterThan(Date value) {
            addCriterion("YSWCSJ >", value, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjGreaterThanOrEqualTo(Date value) {
            addCriterion("YSWCSJ >=", value, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjLessThan(Date value) {
            addCriterion("YSWCSJ <", value, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjLessThanOrEqualTo(Date value) {
            addCriterion("YSWCSJ <=", value, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjIn(List<Date> values) {
            addCriterion("YSWCSJ in", values, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjNotIn(List<Date> values) {
            addCriterion("YSWCSJ not in", values, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjBetween(Date value1, Date value2) {
            addCriterion("YSWCSJ between", value1, value2, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYswcsjNotBetween(Date value1, Date value2) {
            addCriterion("YSWCSJ not between", value1, value2, "yswcsj");
            return (Criteria) this;
        }

        public Criteria andYstqcsIsNull() {
            addCriterion("YSTQCS is null");
            return (Criteria) this;
        }

        public Criteria andYstqcsIsNotNull() {
            addCriterion("YSTQCS is not null");
            return (Criteria) this;
        }

        public Criteria andYstqcsEqualTo(Integer value) {
            addCriterion("YSTQCS =", value, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andYstqcsNotEqualTo(Integer value) {
            addCriterion("YSTQCS <>", value, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andYstqcsGreaterThan(Integer value) {
            addCriterion("YSTQCS >", value, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andYstqcsGreaterThanOrEqualTo(Integer value) {
            addCriterion("YSTQCS >=", value, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andYstqcsLessThan(Integer value) {
            addCriterion("YSTQCS <", value, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andYstqcsLessThanOrEqualTo(Integer value) {
            addCriterion("YSTQCS <=", value, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andYstqcsIn(List<Integer> values) {
            addCriterion("YSTQCS in", values, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andYstqcsNotIn(List<Integer> values) {
            addCriterion("YSTQCS not in", values, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andYstqcsBetween(Integer value1, Integer value2) {
            addCriterion("YSTQCS between", value1, value2, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andYstqcsNotBetween(Integer value1, Integer value2) {
            addCriterion("YSTQCS not between", value1, value2, "ystqcs");
            return (Criteria) this;
        }

        public Criteria andBwzyIsNull() {
            addCriterion("BWZY is null");
            return (Criteria) this;
        }

        public Criteria andBwzyIsNotNull() {
            addCriterion("BWZY is not null");
            return (Criteria) this;
        }

        public Criteria andBwzyEqualTo(String value) {
            addCriterion("BWZY =", value, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyNotEqualTo(String value) {
            addCriterion("BWZY <>", value, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyGreaterThan(String value) {
            addCriterion("BWZY >", value, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyGreaterThanOrEqualTo(String value) {
            addCriterion("BWZY >=", value, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyLessThan(String value) {
            addCriterion("BWZY <", value, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyLessThanOrEqualTo(String value) {
            addCriterion("BWZY <=", value, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyLike(String value) {
            addCriterion("BWZY like", value, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyNotLike(String value) {
            addCriterion("BWZY not like", value, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyIn(List<String> values) {
            addCriterion("BWZY in", values, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyNotIn(List<String> values) {
            addCriterion("BWZY not in", values, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyBetween(String value1, String value2) {
            addCriterion("BWZY between", value1, value2, "bwzy");
            return (Criteria) this;
        }

        public Criteria andBwzyNotBetween(String value1, String value2) {
            addCriterion("BWZY not between", value1, value2, "bwzy");
            return (Criteria) this;
        }

        public Criteria andYsjgIsNull() {
            addCriterion("YSJG is null");
            return (Criteria) this;
        }

        public Criteria andYsjgIsNotNull() {
            addCriterion("YSJG is not null");
            return (Criteria) this;
        }

        public Criteria andYsjgEqualTo(String value) {
            addCriterion("YSJG =", value, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgNotEqualTo(String value) {
            addCriterion("YSJG <>", value, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgGreaterThan(String value) {
            addCriterion("YSJG >", value, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgGreaterThanOrEqualTo(String value) {
            addCriterion("YSJG >=", value, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgLessThan(String value) {
            addCriterion("YSJG <", value, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgLessThanOrEqualTo(String value) {
            addCriterion("YSJG <=", value, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgLike(String value) {
            addCriterion("YSJG like", value, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgNotLike(String value) {
            addCriterion("YSJG not like", value, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgIn(List<String> values) {
            addCriterion("YSJG in", values, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgNotIn(List<String> values) {
            addCriterion("YSJG not in", values, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgBetween(String value1, String value2) {
            addCriterion("YSJG between", value1, value2, "ysjg");
            return (Criteria) this;
        }

        public Criteria andYsjgNotBetween(String value1, String value2) {
            addCriterion("YSJG not between", value1, value2, "ysjg");
            return (Criteria) this;
        }

        public Criteria andSbrIsNull() {
            addCriterion("SBR is null");
            return (Criteria) this;
        }

        public Criteria andSbrIsNotNull() {
            addCriterion("SBR is not null");
            return (Criteria) this;
        }

        public Criteria andSbrEqualTo(String value) {
            addCriterion("SBR =", value, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrNotEqualTo(String value) {
            addCriterion("SBR <>", value, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrGreaterThan(String value) {
            addCriterion("SBR >", value, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrGreaterThanOrEqualTo(String value) {
            addCriterion("SBR >=", value, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrLessThan(String value) {
            addCriterion("SBR <", value, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrLessThanOrEqualTo(String value) {
            addCriterion("SBR <=", value, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrLike(String value) {
            addCriterion("SBR like", value, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrNotLike(String value) {
            addCriterion("SBR not like", value, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrIn(List<String> values) {
            addCriterion("SBR in", values, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrNotIn(List<String> values) {
            addCriterion("SBR not in", values, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrBetween(String value1, String value2) {
            addCriterion("SBR between", value1, value2, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbrNotBetween(String value1, String value2) {
            addCriterion("SBR not between", value1, value2, "sbr");
            return (Criteria) this;
        }

        public Criteria andSbfsIsNull() {
            addCriterion("SBFS is null");
            return (Criteria) this;
        }

        public Criteria andSbfsIsNotNull() {
            addCriterion("SBFS is not null");
            return (Criteria) this;
        }

        public Criteria andSbfsEqualTo(String value) {
            addCriterion("SBFS =", value, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsNotEqualTo(String value) {
            addCriterion("SBFS <>", value, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsGreaterThan(String value) {
            addCriterion("SBFS >", value, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsGreaterThanOrEqualTo(String value) {
            addCriterion("SBFS >=", value, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsLessThan(String value) {
            addCriterion("SBFS <", value, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsLessThanOrEqualTo(String value) {
            addCriterion("SBFS <=", value, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsLike(String value) {
            addCriterion("SBFS like", value, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsNotLike(String value) {
            addCriterion("SBFS not like", value, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsIn(List<String> values) {
            addCriterion("SBFS in", values, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsNotIn(List<String> values) {
            addCriterion("SBFS not in", values, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsBetween(String value1, String value2) {
            addCriterion("SBFS between", value1, value2, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbfsNotBetween(String value1, String value2) {
            addCriterion("SBFS not between", value1, value2, "sbfs");
            return (Criteria) this;
        }

        public Criteria andSbcsIsNull() {
            addCriterion("SBCS is null");
            return (Criteria) this;
        }

        public Criteria andSbcsIsNotNull() {
            addCriterion("SBCS is not null");
            return (Criteria) this;
        }

        public Criteria andSbcsEqualTo(Integer value) {
            addCriterion("SBCS =", value, "sbcs");
            return (Criteria) this;
        }

        public Criteria andSbcsNotEqualTo(Integer value) {
            addCriterion("SBCS <>", value, "sbcs");
            return (Criteria) this;
        }

        public Criteria andSbcsGreaterThan(Integer value) {
            addCriterion("SBCS >", value, "sbcs");
            return (Criteria) this;
        }

        public Criteria andSbcsGreaterThanOrEqualTo(Integer value) {
            addCriterion("SBCS >=", value, "sbcs");
            return (Criteria) this;
        }

        public Criteria andSbcsLessThan(Integer value) {
            addCriterion("SBCS <", value, "sbcs");
            return (Criteria) this;
        }

        public Criteria andSbcsLessThanOrEqualTo(Integer value) {
            addCriterion("SBCS <=", value, "sbcs");
            return (Criteria) this;
        }

        public Criteria andSbcsIn(List<Integer> values) {
            addCriterion("SBCS in", values, "sbcs");
            return (Criteria) this;
        }

        public Criteria andSbcsNotIn(List<Integer> values) {
            addCriterion("SBCS not in", values, "sbcs");
            return (Criteria) this;
        }

        public Criteria andSbcsBetween(Integer value1, Integer value2) {
            addCriterion("SBCS between", value1, value2, "sbcs");
            return (Criteria) this;
        }

        public Criteria andSbcsNotBetween(Integer value1, Integer value2) {
            addCriterion("SBCS not between", value1, value2, "sbcs");
            return (Criteria) this;
        }

        public Criteria andZzsbbIsNull() {
            addCriterion("ZZSBB is null");
            return (Criteria) this;
        }

        public Criteria andZzsbbIsNotNull() {
            addCriterion("ZZSBB is not null");
            return (Criteria) this;
        }

        public Criteria andZzsbbEqualTo(String value) {
            addCriterion("ZZSBB =", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbNotEqualTo(String value) {
            addCriterion("ZZSBB <>", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbGreaterThan(String value) {
            addCriterion("ZZSBB >", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbGreaterThanOrEqualTo(String value) {
            addCriterion("ZZSBB >=", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbLessThan(String value) {
            addCriterion("ZZSBB <", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbLessThanOrEqualTo(String value) {
            addCriterion("ZZSBB <=", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbLike(String value) {
            addCriterion("ZZSBB like", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbNotLike(String value) {
            addCriterion("ZZSBB not like", value, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbIn(List<String> values) {
            addCriterion("ZZSBB in", values, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbNotIn(List<String> values) {
            addCriterion("ZZSBB not in", values, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbBetween(String value1, String value2) {
            addCriterion("ZZSBB between", value1, value2, "zzsbb");
            return (Criteria) this;
        }

        public Criteria andZzsbbNotBetween(String value1, String value2) {
            addCriterion("ZZSBB not between", value1, value2, "zzsbb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}