package com.tl.web.bjts.shzs.model.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TlShYjxxProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.TBPC
     *
     * @mbggenerated
     */
    private Long tbpc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.SBID
     *
     * @mbggenerated
     */
    private Long sbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.NSRDZDAH
     *
     * @mbggenerated
     */
    private BigDecimal nsrdzdah;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.CJ_DATE
     *
     * @mbggenerated
     */
    private Date cjDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.YJ_TYPE
     *
     * @mbggenerated
     */
    private String yjType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.YJ_OBJECT
     *
     * @mbggenerated
     */
    private String yjObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.YJ_COUNT
     *
     * @mbggenerated
     */
    private Long yjCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.YJ_AMT
     *
     * @mbggenerated
     */
    private BigDecimal yjAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.YJ_TAX
     *
     * @mbggenerated
     */
    private BigDecimal yjTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.YJ_RECORD
     *
     * @mbggenerated
     */
    private String yjRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.YJ_MSG
     *
     * @mbggenerated
     */
    private String yjMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.CL_DATE
     *
     * @mbggenerated
     */
    private Date clDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.CL_USER
     *
     * @mbggenerated
     */
    private String clUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.CL_MSG
     *
     * @mbggenerated
     */
    private String clMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SH_YJXX.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.ID
     *
     * @return the value of SH_YJXX.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.ID
     *
     * @param id the value for SH_YJXX.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.TBPC
     *
     * @return the value of SH_YJXX.TBPC
     *
     * @mbggenerated
     */
    public Long getTbpc() {
        return tbpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.TBPC
     *
     * @param tbpc the value for SH_YJXX.TBPC
     *
     * @mbggenerated
     */
    public void setTbpc(Long tbpc) {
        this.tbpc = tbpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.SBID
     *
     * @return the value of SH_YJXX.SBID
     *
     * @mbggenerated
     */
    public Long getSbid() {
        return sbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.SBID
     *
     * @param sbid the value for SH_YJXX.SBID
     *
     * @mbggenerated
     */
    public void setSbid(Long sbid) {
        this.sbid = sbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.NSRDZDAH
     *
     * @return the value of SH_YJXX.NSRDZDAH
     *
     * @mbggenerated
     */
    public BigDecimal getNsrdzdah() {
        return nsrdzdah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.NSRDZDAH
     *
     * @param nsrdzdah the value for SH_YJXX.NSRDZDAH
     *
     * @mbggenerated
     */
    public void setNsrdzdah(BigDecimal nsrdzdah) {
        this.nsrdzdah = nsrdzdah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.CJ_DATE
     *
     * @return the value of SH_YJXX.CJ_DATE
     *
     * @mbggenerated
     */
    public Date getCjDate() {
        return cjDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.CJ_DATE
     *
     * @param cjDate the value for SH_YJXX.CJ_DATE
     *
     * @mbggenerated
     */
    public void setCjDate(Date cjDate) {
        this.cjDate = cjDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.YJ_TYPE
     *
     * @return the value of SH_YJXX.YJ_TYPE
     *
     * @mbggenerated
     */
    public String getYjType() {
        return yjType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.YJ_TYPE
     *
     * @param yjType the value for SH_YJXX.YJ_TYPE
     *
     * @mbggenerated
     */
    public void setYjType(String yjType) {
        this.yjType = yjType == null ? null : yjType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.YJ_OBJECT
     *
     * @return the value of SH_YJXX.YJ_OBJECT
     *
     * @mbggenerated
     */
    public String getYjObject() {
        return yjObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.YJ_OBJECT
     *
     * @param yjObject the value for SH_YJXX.YJ_OBJECT
     *
     * @mbggenerated
     */
    public void setYjObject(String yjObject) {
        this.yjObject = yjObject == null ? null : yjObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.YJ_COUNT
     *
     * @return the value of SH_YJXX.YJ_COUNT
     *
     * @mbggenerated
     */
    public Long getYjCount() {
        return yjCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.YJ_COUNT
     *
     * @param yjCount the value for SH_YJXX.YJ_COUNT
     *
     * @mbggenerated
     */
    public void setYjCount(Long yjCount) {
        this.yjCount = yjCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.YJ_AMT
     *
     * @return the value of SH_YJXX.YJ_AMT
     *
     * @mbggenerated
     */
    public BigDecimal getYjAmt() {
        return yjAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.YJ_AMT
     *
     * @param yjAmt the value for SH_YJXX.YJ_AMT
     *
     * @mbggenerated
     */
    public void setYjAmt(BigDecimal yjAmt) {
        this.yjAmt = yjAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.YJ_TAX
     *
     * @return the value of SH_YJXX.YJ_TAX
     *
     * @mbggenerated
     */
    public BigDecimal getYjTax() {
        return yjTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.YJ_TAX
     *
     * @param yjTax the value for SH_YJXX.YJ_TAX
     *
     * @mbggenerated
     */
    public void setYjTax(BigDecimal yjTax) {
        this.yjTax = yjTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.YJ_RECORD
     *
     * @return the value of SH_YJXX.YJ_RECORD
     *
     * @mbggenerated
     */
    public String getYjRecord() {
        return yjRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.YJ_RECORD
     *
     * @param yjRecord the value for SH_YJXX.YJ_RECORD
     *
     * @mbggenerated
     */
    public void setYjRecord(String yjRecord) {
        this.yjRecord = yjRecord == null ? null : yjRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.YJ_MSG
     *
     * @return the value of SH_YJXX.YJ_MSG
     *
     * @mbggenerated
     */
    public String getYjMsg() {
        return yjMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.YJ_MSG
     *
     * @param yjMsg the value for SH_YJXX.YJ_MSG
     *
     * @mbggenerated
     */
    public void setYjMsg(String yjMsg) {
        this.yjMsg = yjMsg == null ? null : yjMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.CL_DATE
     *
     * @return the value of SH_YJXX.CL_DATE
     *
     * @mbggenerated
     */
    public Date getClDate() {
        return clDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.CL_DATE
     *
     * @param clDate the value for SH_YJXX.CL_DATE
     *
     * @mbggenerated
     */
    public void setClDate(Date clDate) {
        this.clDate = clDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.CL_USER
     *
     * @return the value of SH_YJXX.CL_USER
     *
     * @mbggenerated
     */
    public String getClUser() {
        return clUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.CL_USER
     *
     * @param clUser the value for SH_YJXX.CL_USER
     *
     * @mbggenerated
     */
    public void setClUser(String clUser) {
        this.clUser = clUser == null ? null : clUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.CL_MSG
     *
     * @return the value of SH_YJXX.CL_MSG
     *
     * @mbggenerated
     */
    public String getClMsg() {
        return clMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.CL_MSG
     *
     * @param clMsg the value for SH_YJXX.CL_MSG
     *
     * @mbggenerated
     */
    public void setClMsg(String clMsg) {
        this.clMsg = clMsg == null ? null : clMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SH_YJXX.BZ
     *
     * @return the value of SH_YJXX.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SH_YJXX.BZ
     *
     * @param bz the value for SH_YJXX.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}