package com.tl.web.bjts.shzs.model.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TlShSbxxHzProfile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.UUID
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.NSRDZDAH
     *
     * @mbggenerated
     */
    private BigDecimal nsrdzdah;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBYWB_DM
     *
     * @mbggenerated
     */
    private String sbywbDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SSSQ
     *
     * @mbggenerated
     */
    private String sssq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBPC
     *
     * @mbggenerated
     */
    private Integer sbpc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBRQ
     *
     * @mbggenerated
     */
    private Date sbrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBZT_DM
     *
     * @mbggenerated
     */
    private String sbztDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.LZHJ
     *
     * @mbggenerated
     */
    private String lzhj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.FKRQ
     *
     * @mbggenerated
     */
    private Date fkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.FKXX
     *
     * @mbggenerated
     */
    private String fkxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.FJSL
     *
     * @mbggenerated
     */
    private Integer fjsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.QYBJ
     *
     * @mbggenerated
     */
    private String qybj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.CJRQ
     *
     * @mbggenerated
     */
    private Date cjrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.XGRQ
     *
     * @mbggenerated
     */
    private Date xgrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.TQBZ
     *
     * @mbggenerated
     */
    private String tqbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.TQSJ
     *
     * @mbggenerated
     */
    private Date tqsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.TQCS
     *
     * @mbggenerated
     */
    private Integer tqcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBYY
     *
     * @mbggenerated
     */
    private String sbyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.YXJ
     *
     * @mbggenerated
     */
    private Integer yxj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBSJ
     *
     * @mbggenerated
     */
    private Date sbsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.TBSJ
     *
     * @mbggenerated
     */
    private Date tbsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.LCSLID
     *
     * @mbggenerated
     */
    private String lcslid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.TBCS
     *
     * @mbggenerated
     */
    private Integer tbcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBZL_DM
     *
     * @mbggenerated
     */
    private String sbzlDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBTYPE
     *
     * @mbggenerated
     */
    private String sbtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.YSBZ
     *
     * @mbggenerated
     */
    private String ysbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.YSTQSJ
     *
     * @mbggenerated
     */
    private Date ystqsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.YSWCSJ
     *
     * @mbggenerated
     */
    private Date yswcsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.YSTQCS
     *
     * @mbggenerated
     */
    private Integer ystqcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.BWZY
     *
     * @mbggenerated
     */
    private String bwzy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.YSJG
     *
     * @mbggenerated
     */
    private String ysjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBR
     *
     * @mbggenerated
     */
    private String sbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBFS
     *
     * @mbggenerated
     */
    private String sbfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.SBCS
     *
     * @mbggenerated
     */
    private Integer sbcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SB_SBXX_HZ.ZZSBB
     *
     * @mbggenerated
     */
    private String zzsbb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.ID
     *
     * @return the value of SB_SBXX_HZ.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.ID
     *
     * @param id the value for SB_SBXX_HZ.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.UUID
     *
     * @return the value of SB_SBXX_HZ.UUID
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.UUID
     *
     * @param uuid the value for SB_SBXX_HZ.UUID
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.NSRDZDAH
     *
     * @return the value of SB_SBXX_HZ.NSRDZDAH
     *
     * @mbggenerated
     */
    public BigDecimal getNsrdzdah() {
        return nsrdzdah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.NSRDZDAH
     *
     * @param nsrdzdah the value for SB_SBXX_HZ.NSRDZDAH
     *
     * @mbggenerated
     */
    public void setNsrdzdah(BigDecimal nsrdzdah) {
        this.nsrdzdah = nsrdzdah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBYWB_DM
     *
     * @return the value of SB_SBXX_HZ.SBYWB_DM
     *
     * @mbggenerated
     */
    public String getSbywbDm() {
        return sbywbDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBYWB_DM
     *
     * @param sbywbDm the value for SB_SBXX_HZ.SBYWB_DM
     *
     * @mbggenerated
     */
    public void setSbywbDm(String sbywbDm) {
        this.sbywbDm = sbywbDm == null ? null : sbywbDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SSSQ
     *
     * @return the value of SB_SBXX_HZ.SSSQ
     *
     * @mbggenerated
     */
    public String getSssq() {
        return sssq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SSSQ
     *
     * @param sssq the value for SB_SBXX_HZ.SSSQ
     *
     * @mbggenerated
     */
    public void setSssq(String sssq) {
        this.sssq = sssq == null ? null : sssq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBPC
     *
     * @return the value of SB_SBXX_HZ.SBPC
     *
     * @mbggenerated
     */
    public Integer getSbpc() {
        return sbpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBPC
     *
     * @param sbpc the value for SB_SBXX_HZ.SBPC
     *
     * @mbggenerated
     */
    public void setSbpc(Integer sbpc) {
        this.sbpc = sbpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBRQ
     *
     * @return the value of SB_SBXX_HZ.SBRQ
     *
     * @mbggenerated
     */
    public Date getSbrq() {
        return sbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBRQ
     *
     * @param sbrq the value for SB_SBXX_HZ.SBRQ
     *
     * @mbggenerated
     */
    public void setSbrq(Date sbrq) {
        this.sbrq = sbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBZT_DM
     *
     * @return the value of SB_SBXX_HZ.SBZT_DM
     *
     * @mbggenerated
     */
    public String getSbztDm() {
        return sbztDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBZT_DM
     *
     * @param sbztDm the value for SB_SBXX_HZ.SBZT_DM
     *
     * @mbggenerated
     */
    public void setSbztDm(String sbztDm) {
        this.sbztDm = sbztDm == null ? null : sbztDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.LZHJ
     *
     * @return the value of SB_SBXX_HZ.LZHJ
     *
     * @mbggenerated
     */
    public String getLzhj() {
        return lzhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.LZHJ
     *
     * @param lzhj the value for SB_SBXX_HZ.LZHJ
     *
     * @mbggenerated
     */
    public void setLzhj(String lzhj) {
        this.lzhj = lzhj == null ? null : lzhj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.FKRQ
     *
     * @return the value of SB_SBXX_HZ.FKRQ
     *
     * @mbggenerated
     */
    public Date getFkrq() {
        return fkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.FKRQ
     *
     * @param fkrq the value for SB_SBXX_HZ.FKRQ
     *
     * @mbggenerated
     */
    public void setFkrq(Date fkrq) {
        this.fkrq = fkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.FKXX
     *
     * @return the value of SB_SBXX_HZ.FKXX
     *
     * @mbggenerated
     */
    public String getFkxx() {
        return fkxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.FKXX
     *
     * @param fkxx the value for SB_SBXX_HZ.FKXX
     *
     * @mbggenerated
     */
    public void setFkxx(String fkxx) {
        this.fkxx = fkxx == null ? null : fkxx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.FJSL
     *
     * @return the value of SB_SBXX_HZ.FJSL
     *
     * @mbggenerated
     */
    public Integer getFjsl() {
        return fjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.FJSL
     *
     * @param fjsl the value for SB_SBXX_HZ.FJSL
     *
     * @mbggenerated
     */
    public void setFjsl(Integer fjsl) {
        this.fjsl = fjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.QYBJ
     *
     * @return the value of SB_SBXX_HZ.QYBJ
     *
     * @mbggenerated
     */
    public String getQybj() {
        return qybj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.QYBJ
     *
     * @param qybj the value for SB_SBXX_HZ.QYBJ
     *
     * @mbggenerated
     */
    public void setQybj(String qybj) {
        this.qybj = qybj == null ? null : qybj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.BZ
     *
     * @return the value of SB_SBXX_HZ.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.BZ
     *
     * @param bz the value for SB_SBXX_HZ.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.CJRQ
     *
     * @return the value of SB_SBXX_HZ.CJRQ
     *
     * @mbggenerated
     */
    public Date getCjrq() {
        return cjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.CJRQ
     *
     * @param cjrq the value for SB_SBXX_HZ.CJRQ
     *
     * @mbggenerated
     */
    public void setCjrq(Date cjrq) {
        this.cjrq = cjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.XGRQ
     *
     * @return the value of SB_SBXX_HZ.XGRQ
     *
     * @mbggenerated
     */
    public Date getXgrq() {
        return xgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.XGRQ
     *
     * @param xgrq the value for SB_SBXX_HZ.XGRQ
     *
     * @mbggenerated
     */
    public void setXgrq(Date xgrq) {
        this.xgrq = xgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.TQBZ
     *
     * @return the value of SB_SBXX_HZ.TQBZ
     *
     * @mbggenerated
     */
    public String getTqbz() {
        return tqbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.TQBZ
     *
     * @param tqbz the value for SB_SBXX_HZ.TQBZ
     *
     * @mbggenerated
     */
    public void setTqbz(String tqbz) {
        this.tqbz = tqbz == null ? null : tqbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.TQSJ
     *
     * @return the value of SB_SBXX_HZ.TQSJ
     *
     * @mbggenerated
     */
    public Date getTqsj() {
        return tqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.TQSJ
     *
     * @param tqsj the value for SB_SBXX_HZ.TQSJ
     *
     * @mbggenerated
     */
    public void setTqsj(Date tqsj) {
        this.tqsj = tqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.TQCS
     *
     * @return the value of SB_SBXX_HZ.TQCS
     *
     * @mbggenerated
     */
    public Integer getTqcs() {
        return tqcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.TQCS
     *
     * @param tqcs the value for SB_SBXX_HZ.TQCS
     *
     * @mbggenerated
     */
    public void setTqcs(Integer tqcs) {
        this.tqcs = tqcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBYY
     *
     * @return the value of SB_SBXX_HZ.SBYY
     *
     * @mbggenerated
     */
    public String getSbyy() {
        return sbyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBYY
     *
     * @param sbyy the value for SB_SBXX_HZ.SBYY
     *
     * @mbggenerated
     */
    public void setSbyy(String sbyy) {
        this.sbyy = sbyy == null ? null : sbyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.YXJ
     *
     * @return the value of SB_SBXX_HZ.YXJ
     *
     * @mbggenerated
     */
    public Integer getYxj() {
        return yxj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.YXJ
     *
     * @param yxj the value for SB_SBXX_HZ.YXJ
     *
     * @mbggenerated
     */
    public void setYxj(Integer yxj) {
        this.yxj = yxj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBSJ
     *
     * @return the value of SB_SBXX_HZ.SBSJ
     *
     * @mbggenerated
     */
    public Date getSbsj() {
        return sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBSJ
     *
     * @param sbsj the value for SB_SBXX_HZ.SBSJ
     *
     * @mbggenerated
     */
    public void setSbsj(Date sbsj) {
        this.sbsj = sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.TBSJ
     *
     * @return the value of SB_SBXX_HZ.TBSJ
     *
     * @mbggenerated
     */
    public Date getTbsj() {
        return tbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.TBSJ
     *
     * @param tbsj the value for SB_SBXX_HZ.TBSJ
     *
     * @mbggenerated
     */
    public void setTbsj(Date tbsj) {
        this.tbsj = tbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.LCSLID
     *
     * @return the value of SB_SBXX_HZ.LCSLID
     *
     * @mbggenerated
     */
    public String getLcslid() {
        return lcslid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.LCSLID
     *
     * @param lcslid the value for SB_SBXX_HZ.LCSLID
     *
     * @mbggenerated
     */
    public void setLcslid(String lcslid) {
        this.lcslid = lcslid == null ? null : lcslid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.TBCS
     *
     * @return the value of SB_SBXX_HZ.TBCS
     *
     * @mbggenerated
     */
    public Integer getTbcs() {
        return tbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.TBCS
     *
     * @param tbcs the value for SB_SBXX_HZ.TBCS
     *
     * @mbggenerated
     */
    public void setTbcs(Integer tbcs) {
        this.tbcs = tbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBZL_DM
     *
     * @return the value of SB_SBXX_HZ.SBZL_DM
     *
     * @mbggenerated
     */
    public String getSbzlDm() {
        return sbzlDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBZL_DM
     *
     * @param sbzlDm the value for SB_SBXX_HZ.SBZL_DM
     *
     * @mbggenerated
     */
    public void setSbzlDm(String sbzlDm) {
        this.sbzlDm = sbzlDm == null ? null : sbzlDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBTYPE
     *
     * @return the value of SB_SBXX_HZ.SBTYPE
     *
     * @mbggenerated
     */
    public String getSbtype() {
        return sbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBTYPE
     *
     * @param sbtype the value for SB_SBXX_HZ.SBTYPE
     *
     * @mbggenerated
     */
    public void setSbtype(String sbtype) {
        this.sbtype = sbtype == null ? null : sbtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.YSBZ
     *
     * @return the value of SB_SBXX_HZ.YSBZ
     *
     * @mbggenerated
     */
    public String getYsbz() {
        return ysbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.YSBZ
     *
     * @param ysbz the value for SB_SBXX_HZ.YSBZ
     *
     * @mbggenerated
     */
    public void setYsbz(String ysbz) {
        this.ysbz = ysbz == null ? null : ysbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.YSTQSJ
     *
     * @return the value of SB_SBXX_HZ.YSTQSJ
     *
     * @mbggenerated
     */
    public Date getYstqsj() {
        return ystqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.YSTQSJ
     *
     * @param ystqsj the value for SB_SBXX_HZ.YSTQSJ
     *
     * @mbggenerated
     */
    public void setYstqsj(Date ystqsj) {
        this.ystqsj = ystqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.YSWCSJ
     *
     * @return the value of SB_SBXX_HZ.YSWCSJ
     *
     * @mbggenerated
     */
    public Date getYswcsj() {
        return yswcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.YSWCSJ
     *
     * @param yswcsj the value for SB_SBXX_HZ.YSWCSJ
     *
     * @mbggenerated
     */
    public void setYswcsj(Date yswcsj) {
        this.yswcsj = yswcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.YSTQCS
     *
     * @return the value of SB_SBXX_HZ.YSTQCS
     *
     * @mbggenerated
     */
    public Integer getYstqcs() {
        return ystqcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.YSTQCS
     *
     * @param ystqcs the value for SB_SBXX_HZ.YSTQCS
     *
     * @mbggenerated
     */
    public void setYstqcs(Integer ystqcs) {
        this.ystqcs = ystqcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.BWZY
     *
     * @return the value of SB_SBXX_HZ.BWZY
     *
     * @mbggenerated
     */
    public String getBwzy() {
        return bwzy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.BWZY
     *
     * @param bwzy the value for SB_SBXX_HZ.BWZY
     *
     * @mbggenerated
     */
    public void setBwzy(String bwzy) {
        this.bwzy = bwzy == null ? null : bwzy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.YSJG
     *
     * @return the value of SB_SBXX_HZ.YSJG
     *
     * @mbggenerated
     */
    public String getYsjg() {
        return ysjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.YSJG
     *
     * @param ysjg the value for SB_SBXX_HZ.YSJG
     *
     * @mbggenerated
     */
    public void setYsjg(String ysjg) {
        this.ysjg = ysjg == null ? null : ysjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBR
     *
     * @return the value of SB_SBXX_HZ.SBR
     *
     * @mbggenerated
     */
    public String getSbr() {
        return sbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBR
     *
     * @param sbr the value for SB_SBXX_HZ.SBR
     *
     * @mbggenerated
     */
    public void setSbr(String sbr) {
        this.sbr = sbr == null ? null : sbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBFS
     *
     * @return the value of SB_SBXX_HZ.SBFS
     *
     * @mbggenerated
     */
    public String getSbfs() {
        return sbfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBFS
     *
     * @param sbfs the value for SB_SBXX_HZ.SBFS
     *
     * @mbggenerated
     */
    public void setSbfs(String sbfs) {
        this.sbfs = sbfs == null ? null : sbfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.SBCS
     *
     * @return the value of SB_SBXX_HZ.SBCS
     *
     * @mbggenerated
     */
    public Integer getSbcs() {
        return sbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.SBCS
     *
     * @param sbcs the value for SB_SBXX_HZ.SBCS
     *
     * @mbggenerated
     */
    public void setSbcs(Integer sbcs) {
        this.sbcs = sbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SB_SBXX_HZ.ZZSBB
     *
     * @return the value of SB_SBXX_HZ.ZZSBB
     *
     * @mbggenerated
     */
    public String getZzsbb() {
        return zzsbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SB_SBXX_HZ.ZZSBB
     *
     * @param zzsbb the value for SB_SBXX_HZ.ZZSBB
     *
     * @mbggenerated
     */
    public void setZzsbb(String zzsbb) {
        this.zzsbb = zzsbb == null ? null : zzsbb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SB_SBXX_HZ
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uuid=").append(uuid);
        sb.append(", nsrdzdah=").append(nsrdzdah);
        sb.append(", sbywbDm=").append(sbywbDm);
        sb.append(", sssq=").append(sssq);
        sb.append(", sbpc=").append(sbpc);
        sb.append(", sbrq=").append(sbrq);
        sb.append(", sbztDm=").append(sbztDm);
        sb.append(", lzhj=").append(lzhj);
        sb.append(", fkrq=").append(fkrq);
        sb.append(", fkxx=").append(fkxx);
        sb.append(", fjsl=").append(fjsl);
        sb.append(", qybj=").append(qybj);
        sb.append(", bz=").append(bz);
        sb.append(", cjrq=").append(cjrq);
        sb.append(", xgrq=").append(xgrq);
        sb.append(", tqbz=").append(tqbz);
        sb.append(", tqsj=").append(tqsj);
        sb.append(", tqcs=").append(tqcs);
        sb.append(", sbyy=").append(sbyy);
        sb.append(", yxj=").append(yxj);
        sb.append(", sbsj=").append(sbsj);
        sb.append(", tbsj=").append(tbsj);
        sb.append(", lcslid=").append(lcslid);
        sb.append(", tbcs=").append(tbcs);
        sb.append(", sbzlDm=").append(sbzlDm);
        sb.append(", sbtype=").append(sbtype);
        sb.append(", ysbz=").append(ysbz);
        sb.append(", ystqsj=").append(ystqsj);
        sb.append(", yswcsj=").append(yswcsj);
        sb.append(", ystqcs=").append(ystqcs);
        sb.append(", bwzy=").append(bwzy);
        sb.append(", ysjg=").append(ysjg);
        sb.append(", sbr=").append(sbr);
        sb.append(", sbfs=").append(sbfs);
        sb.append(", sbcs=").append(sbcs);
        sb.append(", zzsbb=").append(zzsbb);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}