package com.tl.web.bjts.shzs.model.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TlShYjxxProfileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public TlShYjxxProfileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTbpcIsNull() {
            addCriterion("TBPC is null");
            return (Criteria) this;
        }

        public Criteria andTbpcIsNotNull() {
            addCriterion("TBPC is not null");
            return (Criteria) this;
        }

        public Criteria andTbpcEqualTo(Long value) {
            addCriterion("TBPC =", value, "tbpc");
            return (Criteria) this;
        }

        public Criteria andTbpcNotEqualTo(Long value) {
            addCriterion("TBPC <>", value, "tbpc");
            return (Criteria) this;
        }

        public Criteria andTbpcGreaterThan(Long value) {
            addCriterion("TBPC >", value, "tbpc");
            return (Criteria) this;
        }

        public Criteria andTbpcGreaterThanOrEqualTo(Long value) {
            addCriterion("TBPC >=", value, "tbpc");
            return (Criteria) this;
        }

        public Criteria andTbpcLessThan(Long value) {
            addCriterion("TBPC <", value, "tbpc");
            return (Criteria) this;
        }

        public Criteria andTbpcLessThanOrEqualTo(Long value) {
            addCriterion("TBPC <=", value, "tbpc");
            return (Criteria) this;
        }

        public Criteria andTbpcIn(List<Long> values) {
            addCriterion("TBPC in", values, "tbpc");
            return (Criteria) this;
        }

        public Criteria andTbpcNotIn(List<Long> values) {
            addCriterion("TBPC not in", values, "tbpc");
            return (Criteria) this;
        }

        public Criteria andTbpcBetween(Long value1, Long value2) {
            addCriterion("TBPC between", value1, value2, "tbpc");
            return (Criteria) this;
        }

        public Criteria andTbpcNotBetween(Long value1, Long value2) {
            addCriterion("TBPC not between", value1, value2, "tbpc");
            return (Criteria) this;
        }

        public Criteria andSbidIsNull() {
            addCriterion("SBID is null");
            return (Criteria) this;
        }

        public Criteria andSbidIsNotNull() {
            addCriterion("SBID is not null");
            return (Criteria) this;
        }

        public Criteria andSbidEqualTo(Long value) {
            addCriterion("SBID =", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidNotEqualTo(Long value) {
            addCriterion("SBID <>", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidGreaterThan(Long value) {
            addCriterion("SBID >", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidGreaterThanOrEqualTo(Long value) {
            addCriterion("SBID >=", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidLessThan(Long value) {
            addCriterion("SBID <", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidLessThanOrEqualTo(Long value) {
            addCriterion("SBID <=", value, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidIn(List<Long> values) {
            addCriterion("SBID in", values, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidNotIn(List<Long> values) {
            addCriterion("SBID not in", values, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidBetween(Long value1, Long value2) {
            addCriterion("SBID between", value1, value2, "sbid");
            return (Criteria) this;
        }

        public Criteria andSbidNotBetween(Long value1, Long value2) {
            addCriterion("SBID not between", value1, value2, "sbid");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahIsNull() {
            addCriterion("NSRDZDAH is null");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahIsNotNull() {
            addCriterion("NSRDZDAH is not null");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH =", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahNotEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH <>", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahGreaterThan(BigDecimal value) {
            addCriterion("NSRDZDAH >", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH >=", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahLessThan(BigDecimal value) {
            addCriterion("NSRDZDAH <", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NSRDZDAH <=", value, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahIn(List<BigDecimal> values) {
            addCriterion("NSRDZDAH in", values, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahNotIn(List<BigDecimal> values) {
            addCriterion("NSRDZDAH not in", values, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NSRDZDAH between", value1, value2, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andNsrdzdahNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NSRDZDAH not between", value1, value2, "nsrdzdah");
            return (Criteria) this;
        }

        public Criteria andCjDateIsNull() {
            addCriterion("CJ_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCjDateIsNotNull() {
            addCriterion("CJ_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCjDateEqualTo(Date value) {
            addCriterionForJDBCDate("CJ_DATE =", value, "cjDate");
            return (Criteria) this;
        }

        public Criteria andCjDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CJ_DATE <>", value, "cjDate");
            return (Criteria) this;
        }

        public Criteria andCjDateGreaterThan(Date value) {
            addCriterionForJDBCDate("CJ_DATE >", value, "cjDate");
            return (Criteria) this;
        }

        public Criteria andCjDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CJ_DATE >=", value, "cjDate");
            return (Criteria) this;
        }

        public Criteria andCjDateLessThan(Date value) {
            addCriterionForJDBCDate("CJ_DATE <", value, "cjDate");
            return (Criteria) this;
        }

        public Criteria andCjDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CJ_DATE <=", value, "cjDate");
            return (Criteria) this;
        }

        public Criteria andCjDateIn(List<Date> values) {
            addCriterionForJDBCDate("CJ_DATE in", values, "cjDate");
            return (Criteria) this;
        }

        public Criteria andCjDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("CJ_DATE not in", values, "cjDate");
            return (Criteria) this;
        }

        public Criteria andCjDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CJ_DATE between", value1, value2, "cjDate");
            return (Criteria) this;
        }

        public Criteria andCjDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CJ_DATE not between", value1, value2, "cjDate");
            return (Criteria) this;
        }

        public Criteria andYjTypeIsNull() {
            addCriterion("YJ_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andYjTypeIsNotNull() {
            addCriterion("YJ_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andYjTypeEqualTo(String value) {
            addCriterion("YJ_TYPE =", value, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeNotEqualTo(String value) {
            addCriterion("YJ_TYPE <>", value, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeGreaterThan(String value) {
            addCriterion("YJ_TYPE >", value, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeGreaterThanOrEqualTo(String value) {
            addCriterion("YJ_TYPE >=", value, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeLessThan(String value) {
            addCriterion("YJ_TYPE <", value, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeLessThanOrEqualTo(String value) {
            addCriterion("YJ_TYPE <=", value, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeLike(String value) {
            addCriterion("YJ_TYPE like", value, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeNotLike(String value) {
            addCriterion("YJ_TYPE not like", value, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeIn(List<String> values) {
            addCriterion("YJ_TYPE in", values, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeNotIn(List<String> values) {
            addCriterion("YJ_TYPE not in", values, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeBetween(String value1, String value2) {
            addCriterion("YJ_TYPE between", value1, value2, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjTypeNotBetween(String value1, String value2) {
            addCriterion("YJ_TYPE not between", value1, value2, "yjType");
            return (Criteria) this;
        }

        public Criteria andYjObjectIsNull() {
            addCriterion("YJ_OBJECT is null");
            return (Criteria) this;
        }

        public Criteria andYjObjectIsNotNull() {
            addCriterion("YJ_OBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andYjObjectEqualTo(String value) {
            addCriterion("YJ_OBJECT =", value, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectNotEqualTo(String value) {
            addCriterion("YJ_OBJECT <>", value, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectGreaterThan(String value) {
            addCriterion("YJ_OBJECT >", value, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectGreaterThanOrEqualTo(String value) {
            addCriterion("YJ_OBJECT >=", value, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectLessThan(String value) {
            addCriterion("YJ_OBJECT <", value, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectLessThanOrEqualTo(String value) {
            addCriterion("YJ_OBJECT <=", value, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectLike(String value) {
            addCriterion("YJ_OBJECT like", value, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectNotLike(String value) {
            addCriterion("YJ_OBJECT not like", value, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectIn(List<String> values) {
            addCriterion("YJ_OBJECT in", values, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectNotIn(List<String> values) {
            addCriterion("YJ_OBJECT not in", values, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectBetween(String value1, String value2) {
            addCriterion("YJ_OBJECT between", value1, value2, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjObjectNotBetween(String value1, String value2) {
            addCriterion("YJ_OBJECT not between", value1, value2, "yjObject");
            return (Criteria) this;
        }

        public Criteria andYjCountIsNull() {
            addCriterion("YJ_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andYjCountIsNotNull() {
            addCriterion("YJ_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andYjCountEqualTo(Long value) {
            addCriterion("YJ_COUNT =", value, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjCountNotEqualTo(Long value) {
            addCriterion("YJ_COUNT <>", value, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjCountGreaterThan(Long value) {
            addCriterion("YJ_COUNT >", value, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjCountGreaterThanOrEqualTo(Long value) {
            addCriterion("YJ_COUNT >=", value, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjCountLessThan(Long value) {
            addCriterion("YJ_COUNT <", value, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjCountLessThanOrEqualTo(Long value) {
            addCriterion("YJ_COUNT <=", value, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjCountIn(List<Long> values) {
            addCriterion("YJ_COUNT in", values, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjCountNotIn(List<Long> values) {
            addCriterion("YJ_COUNT not in", values, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjCountBetween(Long value1, Long value2) {
            addCriterion("YJ_COUNT between", value1, value2, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjCountNotBetween(Long value1, Long value2) {
            addCriterion("YJ_COUNT not between", value1, value2, "yjCount");
            return (Criteria) this;
        }

        public Criteria andYjAmtIsNull() {
            addCriterion("YJ_AMT is null");
            return (Criteria) this;
        }

        public Criteria andYjAmtIsNotNull() {
            addCriterion("YJ_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andYjAmtEqualTo(BigDecimal value) {
            addCriterion("YJ_AMT =", value, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjAmtNotEqualTo(BigDecimal value) {
            addCriterion("YJ_AMT <>", value, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjAmtGreaterThan(BigDecimal value) {
            addCriterion("YJ_AMT >", value, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YJ_AMT >=", value, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjAmtLessThan(BigDecimal value) {
            addCriterion("YJ_AMT <", value, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YJ_AMT <=", value, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjAmtIn(List<BigDecimal> values) {
            addCriterion("YJ_AMT in", values, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjAmtNotIn(List<BigDecimal> values) {
            addCriterion("YJ_AMT not in", values, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YJ_AMT between", value1, value2, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YJ_AMT not between", value1, value2, "yjAmt");
            return (Criteria) this;
        }

        public Criteria andYjTaxIsNull() {
            addCriterion("YJ_TAX is null");
            return (Criteria) this;
        }

        public Criteria andYjTaxIsNotNull() {
            addCriterion("YJ_TAX is not null");
            return (Criteria) this;
        }

        public Criteria andYjTaxEqualTo(BigDecimal value) {
            addCriterion("YJ_TAX =", value, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjTaxNotEqualTo(BigDecimal value) {
            addCriterion("YJ_TAX <>", value, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjTaxGreaterThan(BigDecimal value) {
            addCriterion("YJ_TAX >", value, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjTaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YJ_TAX >=", value, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjTaxLessThan(BigDecimal value) {
            addCriterion("YJ_TAX <", value, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjTaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YJ_TAX <=", value, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjTaxIn(List<BigDecimal> values) {
            addCriterion("YJ_TAX in", values, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjTaxNotIn(List<BigDecimal> values) {
            addCriterion("YJ_TAX not in", values, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjTaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YJ_TAX between", value1, value2, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjTaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YJ_TAX not between", value1, value2, "yjTax");
            return (Criteria) this;
        }

        public Criteria andYjRecordIsNull() {
            addCriterion("YJ_RECORD is null");
            return (Criteria) this;
        }

        public Criteria andYjRecordIsNotNull() {
            addCriterion("YJ_RECORD is not null");
            return (Criteria) this;
        }

        public Criteria andYjRecordEqualTo(String value) {
            addCriterion("YJ_RECORD =", value, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordNotEqualTo(String value) {
            addCriterion("YJ_RECORD <>", value, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordGreaterThan(String value) {
            addCriterion("YJ_RECORD >", value, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordGreaterThanOrEqualTo(String value) {
            addCriterion("YJ_RECORD >=", value, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordLessThan(String value) {
            addCriterion("YJ_RECORD <", value, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordLessThanOrEqualTo(String value) {
            addCriterion("YJ_RECORD <=", value, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordLike(String value) {
            addCriterion("YJ_RECORD like", value, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordNotLike(String value) {
            addCriterion("YJ_RECORD not like", value, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordIn(List<String> values) {
            addCriterion("YJ_RECORD in", values, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordNotIn(List<String> values) {
            addCriterion("YJ_RECORD not in", values, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordBetween(String value1, String value2) {
            addCriterion("YJ_RECORD between", value1, value2, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjRecordNotBetween(String value1, String value2) {
            addCriterion("YJ_RECORD not between", value1, value2, "yjRecord");
            return (Criteria) this;
        }

        public Criteria andYjMsgIsNull() {
            addCriterion("YJ_MSG is null");
            return (Criteria) this;
        }

        public Criteria andYjMsgIsNotNull() {
            addCriterion("YJ_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andYjMsgEqualTo(String value) {
            addCriterion("YJ_MSG =", value, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgNotEqualTo(String value) {
            addCriterion("YJ_MSG <>", value, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgGreaterThan(String value) {
            addCriterion("YJ_MSG >", value, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgGreaterThanOrEqualTo(String value) {
            addCriterion("YJ_MSG >=", value, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgLessThan(String value) {
            addCriterion("YJ_MSG <", value, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgLessThanOrEqualTo(String value) {
            addCriterion("YJ_MSG <=", value, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgLike(String value) {
            addCriterion("YJ_MSG like", value, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgNotLike(String value) {
            addCriterion("YJ_MSG not like", value, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgIn(List<String> values) {
            addCriterion("YJ_MSG in", values, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgNotIn(List<String> values) {
            addCriterion("YJ_MSG not in", values, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgBetween(String value1, String value2) {
            addCriterion("YJ_MSG between", value1, value2, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andYjMsgNotBetween(String value1, String value2) {
            addCriterion("YJ_MSG not between", value1, value2, "yjMsg");
            return (Criteria) this;
        }

        public Criteria andClDateIsNull() {
            addCriterion("CL_DATE is null");
            return (Criteria) this;
        }

        public Criteria andClDateIsNotNull() {
            addCriterion("CL_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andClDateEqualTo(Date value) {
            addCriterionForJDBCDate("CL_DATE =", value, "clDate");
            return (Criteria) this;
        }

        public Criteria andClDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CL_DATE <>", value, "clDate");
            return (Criteria) this;
        }

        public Criteria andClDateGreaterThan(Date value) {
            addCriterionForJDBCDate("CL_DATE >", value, "clDate");
            return (Criteria) this;
        }

        public Criteria andClDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CL_DATE >=", value, "clDate");
            return (Criteria) this;
        }

        public Criteria andClDateLessThan(Date value) {
            addCriterionForJDBCDate("CL_DATE <", value, "clDate");
            return (Criteria) this;
        }

        public Criteria andClDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CL_DATE <=", value, "clDate");
            return (Criteria) this;
        }

        public Criteria andClDateIn(List<Date> values) {
            addCriterionForJDBCDate("CL_DATE in", values, "clDate");
            return (Criteria) this;
        }

        public Criteria andClDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("CL_DATE not in", values, "clDate");
            return (Criteria) this;
        }

        public Criteria andClDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CL_DATE between", value1, value2, "clDate");
            return (Criteria) this;
        }

        public Criteria andClDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CL_DATE not between", value1, value2, "clDate");
            return (Criteria) this;
        }

        public Criteria andClUserIsNull() {
            addCriterion("CL_USER is null");
            return (Criteria) this;
        }

        public Criteria andClUserIsNotNull() {
            addCriterion("CL_USER is not null");
            return (Criteria) this;
        }

        public Criteria andClUserEqualTo(String value) {
            addCriterion("CL_USER =", value, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserNotEqualTo(String value) {
            addCriterion("CL_USER <>", value, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserGreaterThan(String value) {
            addCriterion("CL_USER >", value, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserGreaterThanOrEqualTo(String value) {
            addCriterion("CL_USER >=", value, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserLessThan(String value) {
            addCriterion("CL_USER <", value, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserLessThanOrEqualTo(String value) {
            addCriterion("CL_USER <=", value, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserLike(String value) {
            addCriterion("CL_USER like", value, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserNotLike(String value) {
            addCriterion("CL_USER not like", value, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserIn(List<String> values) {
            addCriterion("CL_USER in", values, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserNotIn(List<String> values) {
            addCriterion("CL_USER not in", values, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserBetween(String value1, String value2) {
            addCriterion("CL_USER between", value1, value2, "clUser");
            return (Criteria) this;
        }

        public Criteria andClUserNotBetween(String value1, String value2) {
            addCriterion("CL_USER not between", value1, value2, "clUser");
            return (Criteria) this;
        }

        public Criteria andClMsgIsNull() {
            addCriterion("CL_MSG is null");
            return (Criteria) this;
        }

        public Criteria andClMsgIsNotNull() {
            addCriterion("CL_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andClMsgEqualTo(String value) {
            addCriterion("CL_MSG =", value, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgNotEqualTo(String value) {
            addCriterion("CL_MSG <>", value, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgGreaterThan(String value) {
            addCriterion("CL_MSG >", value, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgGreaterThanOrEqualTo(String value) {
            addCriterion("CL_MSG >=", value, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgLessThan(String value) {
            addCriterion("CL_MSG <", value, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgLessThanOrEqualTo(String value) {
            addCriterion("CL_MSG <=", value, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgLike(String value) {
            addCriterion("CL_MSG like", value, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgNotLike(String value) {
            addCriterion("CL_MSG not like", value, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgIn(List<String> values) {
            addCriterion("CL_MSG in", values, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgNotIn(List<String> values) {
            addCriterion("CL_MSG not in", values, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgBetween(String value1, String value2) {
            addCriterion("CL_MSG between", value1, value2, "clMsg");
            return (Criteria) this;
        }

        public Criteria andClMsgNotBetween(String value1, String value2) {
            addCriterion("CL_MSG not between", value1, value2, "clMsg");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SH_YJXX
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SH_YJXX
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}