package com.tl.web.bjts.shzs.model.domain;

import java.io.Serializable;
import java.util.Date;

public class TlUserProfile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.CZRY_DM
     *
     * @mbggenerated
     */
    private String czryDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.CZRY_MC
     *
     * @mbggenerated
     */
    private String czryMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.SWJG_DM
     *
     * @mbggenerated
     */
    private String swjgDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.CZRY_DM_ZG
     *
     * @mbggenerated
     */
    private String czryDmZg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.YHLX
     *
     * @mbggenerated
     */
    private String yhlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.USRSTATE
     *
     * @mbggenerated
     */
    private String usrstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.CRTIME
     *
     * @mbggenerated
     */
    private Date crtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.CRNAME
     *
     * @mbggenerated
     */
    private String crname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.UPTIME
     *
     * @mbggenerated
     */
    private Date uptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.UPNAME
     *
     * @mbggenerated
     */
    private String upname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.QYBZ
     *
     * @mbggenerated
     */
    private String qybz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DM_CZRY.LXDH
     *
     * @mbggenerated
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DM_CZRY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.CZRY_DM
     *
     * @return the value of DM_CZRY.CZRY_DM
     *
     * @mbggenerated
     */
    public String getCzryDm() {
        return czryDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.CZRY_DM
     *
     * @param czryDm the value for DM_CZRY.CZRY_DM
     *
     * @mbggenerated
     */
    public void setCzryDm(String czryDm) {
        this.czryDm = czryDm == null ? null : czryDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.CZRY_MC
     *
     * @return the value of DM_CZRY.CZRY_MC
     *
     * @mbggenerated
     */
    public String getCzryMc() {
        return czryMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.CZRY_MC
     *
     * @param czryMc the value for DM_CZRY.CZRY_MC
     *
     * @mbggenerated
     */
    public void setCzryMc(String czryMc) {
        this.czryMc = czryMc == null ? null : czryMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.PASSWORD
     *
     * @return the value of DM_CZRY.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.PASSWORD
     *
     * @param password the value for DM_CZRY.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.SWJG_DM
     *
     * @return the value of DM_CZRY.SWJG_DM
     *
     * @mbggenerated
     */
    public String getSwjgDm() {
        return swjgDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.SWJG_DM
     *
     * @param swjgDm the value for DM_CZRY.SWJG_DM
     *
     * @mbggenerated
     */
    public void setSwjgDm(String swjgDm) {
        this.swjgDm = swjgDm == null ? null : swjgDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.CZRY_DM_ZG
     *
     * @return the value of DM_CZRY.CZRY_DM_ZG
     *
     * @mbggenerated
     */
    public String getCzryDmZg() {
        return czryDmZg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.CZRY_DM_ZG
     *
     * @param czryDmZg the value for DM_CZRY.CZRY_DM_ZG
     *
     * @mbggenerated
     */
    public void setCzryDmZg(String czryDmZg) {
        this.czryDmZg = czryDmZg == null ? null : czryDmZg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.YHLX
     *
     * @return the value of DM_CZRY.YHLX
     *
     * @mbggenerated
     */
    public String getYhlx() {
        return yhlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.YHLX
     *
     * @param yhlx the value for DM_CZRY.YHLX
     *
     * @mbggenerated
     */
    public void setYhlx(String yhlx) {
        this.yhlx = yhlx == null ? null : yhlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.USRSTATE
     *
     * @return the value of DM_CZRY.USRSTATE
     *
     * @mbggenerated
     */
    public String getUsrstate() {
        return usrstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.USRSTATE
     *
     * @param usrstate the value for DM_CZRY.USRSTATE
     *
     * @mbggenerated
     */
    public void setUsrstate(String usrstate) {
        this.usrstate = usrstate == null ? null : usrstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.DESCRIPTION
     *
     * @return the value of DM_CZRY.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.DESCRIPTION
     *
     * @param description the value for DM_CZRY.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.CRTIME
     *
     * @return the value of DM_CZRY.CRTIME
     *
     * @mbggenerated
     */
    public Date getCrtime() {
        return crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.CRTIME
     *
     * @param crtime the value for DM_CZRY.CRTIME
     *
     * @mbggenerated
     */
    public void setCrtime(Date crtime) {
        this.crtime = crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.CRNAME
     *
     * @return the value of DM_CZRY.CRNAME
     *
     * @mbggenerated
     */
    public String getCrname() {
        return crname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.CRNAME
     *
     * @param crname the value for DM_CZRY.CRNAME
     *
     * @mbggenerated
     */
    public void setCrname(String crname) {
        this.crname = crname == null ? null : crname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.UPTIME
     *
     * @return the value of DM_CZRY.UPTIME
     *
     * @mbggenerated
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.UPTIME
     *
     * @param uptime the value for DM_CZRY.UPTIME
     *
     * @mbggenerated
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.UPNAME
     *
     * @return the value of DM_CZRY.UPNAME
     *
     * @mbggenerated
     */
    public String getUpname() {
        return upname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.UPNAME
     *
     * @param upname the value for DM_CZRY.UPNAME
     *
     * @mbggenerated
     */
    public void setUpname(String upname) {
        this.upname = upname == null ? null : upname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.QYBZ
     *
     * @return the value of DM_CZRY.QYBZ
     *
     * @mbggenerated
     */
    public String getQybz() {
        return qybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.QYBZ
     *
     * @param qybz the value for DM_CZRY.QYBZ
     *
     * @mbggenerated
     */
    public void setQybz(String qybz) {
        this.qybz = qybz == null ? null : qybz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DM_CZRY.LXDH
     *
     * @return the value of DM_CZRY.LXDH
     *
     * @mbggenerated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DM_CZRY.LXDH
     *
     * @param lxdh the value for DM_CZRY.LXDH
     *
     * @mbggenerated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DM_CZRY
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", czryDm=").append(czryDm);
        sb.append(", czryMc=").append(czryMc);
        sb.append(", password=").append(password);
        sb.append(", swjgDm=").append(swjgDm);
        sb.append(", czryDmZg=").append(czryDmZg);
        sb.append(", yhlx=").append(yhlx);
        sb.append(", usrstate=").append(usrstate);
        sb.append(", description=").append(description);
        sb.append(", crtime=").append(crtime);
        sb.append(", crname=").append(crname);
        sb.append(", uptime=").append(uptime);
        sb.append(", upname=").append(upname);
        sb.append(", qybz=").append(qybz);
        sb.append(", lxdh=").append(lxdh);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}