CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B01105_CSH_NEW
/*************************************************
 * 出口退税返还情况月报表
 * 返纳数据从金三系统缴款书获取的情形，目前根据税款属性不能区分出清算补税和按规定予以追补、稽查补税
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
  LD_NEXTMONTH     DATE;
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_SYSDATE,1),'MM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B01105 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、计算列
  BEGIN
    --出口货物退运
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '02', V_SWCODE,
           COUNT(DISTINCT T.DJXH) AS QYHS, 
           NVL(ROUND(SUM(T.SJJE)/10000,6),0) AS JE,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101'                            THEN T.SJJE ELSE 0 END)/10000,6),0) AS ZZS_XJ,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6),0) AS ZZS_HIS,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6),0) AS ZZS_CUR,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102'                            THEN T.SJJE ELSE 0 END)/10000,6),0) AS XFS_XJ,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6),0) AS XFS_HIS,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6),0) AS XFS_CUR
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND NVL(T.YWHZBUUID,NVL(T.YZHYTMSKYY_DM,T.SKSX_DM)) IN ('032','0109');
    COMMIT;

    --稽查补税
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '03', V_SWCODE,
           COUNT(DISTINCT T.DJXH) AS QYHS, 
           NVL(ROUND(SUM(T.SJJE)/10000,6),0) AS JE,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101'                            THEN T.SJJE ELSE 0 END)/10000,6),0) AS ZZS_XJ,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6),0) AS ZZS_HIS,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6),0) AS ZZS_CUR,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102'                            THEN T.SJJE ELSE 0 END)/10000,6),0) AS XFS_XJ,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6),0) AS XFS_HIS,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6),0) AS XFS_CUR
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND NVL(T.YWHZBUUID,NVL(T.YZHYTMSKYY_DM,T.SKSX_DM)) IN (/*'033','0406',*/'0401','0402');
    COMMIT;

    --按规定予以追补
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '04', V_SWCODE,
           COUNT(DISTINCT T.DJXH) AS QYHS, 
           NVL(ROUND(SUM(T.SJJE)/10000,6),0) AS JE,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101'                            THEN T.SJJE ELSE 0 END)/10000,6),0) AS ZZS_XJ,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6),0) AS ZZS_HIS,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6),0) AS ZZS_CUR,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102'                            THEN T.SJJE ELSE 0 END)/10000,6),0) AS XFS_XJ,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ<LD_THISYEAR  THEN T.SJJE ELSE 0 END)/10000,6),0) AS XFS_HIS,
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' AND T.SKSSQZ>=LD_THISYEAR THEN T.SJJE ELSE 0 END)/10000,6),0) AS XFS_CUR
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR
       AND T.RKRQ<LD_NEXTMONTH
       AND NVL(T.YWHZBUUID,NVL(T.YZHYTMSKYY_DM,T.SKSX_DM)) NOT IN ('032','0109', /*'033','0406',*/'0401','0402');
    COMMIT;

    --清算补税
    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '05', V_SWCODE, 0, 0, 0, 0, 0, 0, 0, 0
      FROM DUAL;
    COMMIT;

    INSERT INTO TJBB_DT_B01105 (SSNY, BBLC, SWJGDM, 
           QYHS, JE, ZZS_XJ, ZZS_HIS, ZZS_CUR, XFS_XJ, XFS_HIS, XFS_CUR)
    SELECT LC_THISMONTH, '01', V_SWCODE,
           SUM(QYHS), SUM(JE), SUM(ZZS_XJ), SUM(ZZS_HIS), SUM(ZZS_CUR), SUM(XFS_XJ), SUM(XFS_HIS), SUM(XFS_CUR)
      FROM TJBB_DT_B01105 
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('02','03','04','05');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --2、更新汇总列
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B01105 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B01105' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
