CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B07101_CSH_NEW
/*
 * 202210，新增
 * 列参考B01109，行参考B01100（将第39行提到11行，原11-38行依次下移一行）
 * 20260116，根据舟山反馈问题分析，在统计生产企业申报户数、申报出口额、申报免抵退税额口径，提取进料加工数据时加调整数不为0的条件
 */
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
  LD_NEXTMONTH     DATE;
  LC_LASTMONTH     VARCHAR2(6);

  LN_BAHS          NUMBER(10);
  LN_SBHS          NUMBER(10);
  LN_SB_CKE        NUMBER(18,6);

  LN_SB_ZZS        NUMBER(18,6);
  LN_SH_ZZS        NUMBER(18,6);
  LN_SP_ZZS        NUMBER(18,6);
  LN_BL_ZZS        NUMBER(18,6);
  TSFN_ZZS         NUMBER(18,6);

  LN_SB_XFS        NUMBER(18,6);
  LN_SH_XFS        NUMBER(18,6);
  LN_SP_XFS        NUMBER(18,6);
  LN_BL_XFS        NUMBER(18,6);
  TSFN_XFS         NUMBER(18,6);

  LC_SQL           VARCHAR2(4000);
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_SYSDATE,1),'MM');
  LC_LASTMONTH :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYYMM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B07101 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、外贸企业
  BEGIN
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='10';

    --申报户数、申报出口额
    SELECT COUNT(DISTINCT DJXH), ROUND(NVL(SUM(MYLAJ),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE
     FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MTS_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('10','40','50')
           ) T;

    --申报退税额
    SELECT ROUND(NVL(SUM(CASE WHEN SZ='V' THEN TSE ELSE 0 END),0)/10000,6), 
           ROUND(NVL(SUM(CASE WHEN SZ='C' THEN TSE ELSE 0 END),0)/10000,6) 
      INTO LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.SZ,C.TSE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MTS_JHMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('10','40','50')
           ) T;

    --审核通过退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.FS_XFSTSE),0)/10000,6) 
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '10';

    --审批退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.SEHZ_XFSTSE),0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC='10';

    --国库办理退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS, LN_BL_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC='10';

    --返纳
    SELECT NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' THEN T.SJJE ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' THEN T.SJJE ELSE 0 END)/10000,6),0)
      INTO TSFN_ZZS, TSFN_XFS
      FROM FG_CKTSFN_HXZG T, TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR IN ('00','10');

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '05', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
      FROM DUAL;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '06', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS - TSFN_XFS, LN_BL_XFS - TSFN_XFS
      FROM DUAL;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --2、外综服企业
  BEGIN
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR IN ('70','71','72');

    --申报户数、申报出口额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(MYLAJ),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MTS_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('70','71')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_WZF_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '72'
           ) T;

    --申报退税额
    SELECT ROUND(NVL(SUM(CASE WHEN SZ='V' THEN TSE ELSE 0 END),0)/10000,6), 
           ROUND(NVL(SUM(CASE WHEN SZ='C' THEN TSE ELSE 0 END),0)/10000,6) 
      INTO LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.SZ,C.TSE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MTS_JHMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('70','71')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,'V' AS SZ,C.TSE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_WZF_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '72'
           ) T;

    --审核通过退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.FS_XFSTSE),0)/10000,6) 
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('70','71','72');

    --审批退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.SEHZ_XFSTSE),0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('70','71','72');

    --国库办理退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS, LN_BL_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC IN ('70','71','72');

    --返纳
    SELECT NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10101' THEN T.SJJE ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN T.ZSXM_DM='10102' THEN T.SJJE ELSE 0 END)/10000,6),0)
      INTO TSFN_ZZS, TSFN_XFS
      FROM FG_CKTSFN_HXZG T, TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR IN ('70','71','72');

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '08', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
      FROM DUAL;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '09', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS - TSFN_XFS, LN_BL_XFS - TSFN_XFS
      FROM DUAL;
    COMMIT;

    --2.1 符合13号公告规定业务
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR IN ('70','71');

    --申报户数、申报出口额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(MYLAJ),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MTS_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '71'
           ) T;

    --申报退税额
    SELECT ROUND(NVL(SUM(TSE),0)/10000,6)
      INTO LN_SB_ZZS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.SZ,C.TSE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MTS_JHMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '71'
           ) T;

    --审核通过退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE),0)/10000,6) 
      INTO LN_SH_ZZS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '71';

    --审批退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE),0)/10000,6)
      INTO LN_SP_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '71';

    --国库办理退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '71';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '10', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS, LN_BL_ZZS
      FROM DUAL;
    COMMIT;

    --2.2 符合35号公告规定业务
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR IN ('71','72');

    --申报户数、申报出口额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(MYLAJ),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_WZF_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '72'
           ) T;

    --申报退税额
    SELECT ROUND(NVL(SUM(TSE),0)/10000,6)
      INTO LN_SB_ZZS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,'V' AS SZ,C.TSE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_WZF_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '72'
           ) T;

    --审核通过退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE),0)/10000,6) 
      INTO LN_SH_ZZS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '72';

    --审批退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE+T.SEHZ_XFSTSE),0)/10000,6)
      INTO LN_SP_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '72';

    --国库办理退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '72';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '11', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS, LN_BL_ZZS
      FROM DUAL;
    COMMIT;

  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --3、生产企业
  BEGIN
    --3.1、自营出口的生产企业
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='21';

    --申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(MYLAJ),0)/10000,6),
           ROUND(NVL(SUM(TSE),0)/10000,6),
           ROUND(NVL(SUM(MDE),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MDT_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('21','41','51','61')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,'00000000' AS SBXH,0 AS MYLAJ,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MDT_SBDSHZ C ON C.LCSLID=B.LCSLID AND C.JLJGHXYTZMDTSE<>0
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('21','41','51','61')
           ) T;

    --审核通过免抵退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.FS_MDSE),0)/10000,6) 
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '21';

    --审批免抵退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.SEHZ_MDSE),0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '21';

    --国库办理免抵退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '21';
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,6)
      INTO LN_BL_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC = '21';

    --返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,6),0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '21';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '17', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
      FROM DUAL;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '18', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
      FROM DUAL;
    COMMIT;

    --3.2、委托出口的生产企业
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='22';

    --申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(MYLAJ),0)/10000,6),
           ROUND(NVL(SUM(TSE),0)/10000,6),
           ROUND(NVL(SUM(MDE),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MDT_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('22','42','52','62')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,'00000000' AS SBXH,0 AS MYLAJ,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MDT_SBDSHZ C ON C.LCSLID=B.LCSLID AND C.JLJGHXYTZMDTSE<>0
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('22','42','52','62')
           ) T;

    --审核通过免抵退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.FS_MDSE),0)/10000,6) 
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '22';

    --审批免抵退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.SEHZ_MDSE),0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '22';

    --国库办理免抵退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '22';
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,6)
      INTO LN_BL_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC = '22';

    --返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,6),0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '22';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '20', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
      FROM DUAL;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '21', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
      FROM DUAL;
    COMMIT;

    --3.3、外商投资的生产企业
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='23';

    --申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(MYLAJ),0)/10000,6),
           ROUND(NVL(SUM(TSE),0)/10000,6),
           ROUND(NVL(SUM(MDE),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MDT_CKMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('23','43','53','63')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,'00000000' AS SBXH,0 AS MYLAJ,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.JLJGHXYTZMDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MDT_SBDSHZ C ON C.LCSLID=B.LCSLID AND C.JLJGHXYTZMDTSE<>0
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('23','43','53','63')
           ) T;

    --审核通过免抵退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.FS_MDSE),0)/10000,6) 
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '23';

    --审批免抵退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.SEHZ_MDSE),0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '23';

    --国库办理免抵退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '23';
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,6)
      INTO LN_BL_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC = '23';

    --返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,6),0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '23';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '23', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
      FROM DUAL;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '24', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
      FROM DUAL;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --4、服务贸易
  BEGIN
    --4.1、国际运输服务
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='60';

    --申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(MYLAJ),0)/10000,6),
           ROUND(NVL(SUM(TSE),0)/10000,6),
           ROUND(NVL(SUM(MDE),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.YSFWYYEMY AS MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MDT_GJYS C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('61','62','63')
           ) T;

    --审核通过免抵退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.FS_MDSE),0)/10000,6) 
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('61','62','63');

    --审批免抵退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.SEHZ_MDSE),0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('61','62','63');

    --国库办理免抵退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC IN ('61','62','63');
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,6)
      INTO LN_BL_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC IN ('61','62','63');

    --返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,6),0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '60';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '29', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
      FROM DUAL;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '30', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
      FROM DUAL;
    COMMIT;

    --4.1、研发设计服务
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='50';

    --申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(MYLAJ),0)/10000,6),
           ROUND(NVL(SUM(TSE),0)/10000,6),
           ROUND(NVL(SUM(MDE),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.YSFWYYEMY AS MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MDT_YFSJ C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('51','52','53')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.SKJEMY AS MYLAJ,C.ZZSTSE AS TSE, 0 AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MTS_YSFW C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '50'
           ) T;

    --审核通过免抵退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.FS_MDSE),0)/10000,6) 
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('50','51','52','53');

    --审批免抵退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.SEHZ_MDSE),0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('50','51','52','53');

    --国库办理免抵退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC IN ('50','51','52','53');
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,6)
      INTO LN_BL_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC IN ('50','51','52','53');

    --返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,6),0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '50';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '32', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
      FROM DUAL;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '33', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
      FROM DUAL;
    COMMIT;

    --4.1、其他服务贸易
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='40';

    --申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(MYLAJ),0)/10000,6),
           ROUND(NVL(SUM(TSE),0)/10000,6),
           ROUND(NVL(SUM(MDE),0)/10000,6)
      INTO LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SB_XFS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.YSFWYYEMY AS MYLAJ,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END) AS TSE,
                   C.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_MDSE  /A.SB_MDTSE END) AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MDT_YFSJ C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC IN ('41','42','43')
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.SKJEMY AS MYLAJ,C.ZZSTSE AS TSE, 0 AS MDE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_MTS_YSFW C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '40'
           ) T;

    --审核通过免抵退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.FS_MDSE),0)/10000,6) 
      INTO LN_SH_ZZS, LN_SH_XFS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('40','41','42','43');

    --审批免抵退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE),0)/10000,6), 
           ROUND(NVL(SUM(T.SEHZ_MDSE),0)/10000,6)
      INTO LN_SP_ZZS, LN_SP_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC IN ('40','41','42','43');

    --国库办理免抵退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC IN ('40','41','42','43');
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,6)
      INTO LN_BL_XFS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH
       AND T.LCTJJC IN ('40','41','42','43');

    --返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,6),0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '40';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '35', V_SWCODE, LN_BAHS, LN_SBHS, LN_SB_CKE, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
      FROM DUAL;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '36', V_SWCODE, 0, 0, 0, LN_SB_XFS, LN_SH_XFS, LN_SP_XFS, LN_BL_XFS
      FROM DUAL;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --5、其他企业
  BEGIN
    --备案户数
    SELECT COUNT(1)
      INTO LN_BAHS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N'
       AND T.BAJC_YEAR='30';

    --申报户数、申报出口额、申报免抵退税额
    SELECT COUNT(DISTINCT DJXH), 
           ROUND(NVL(SUM(TSE),0)/10000,6)
      INTO LN_SBHS, LN_SB_ZZS
      FROM (SELECT A.DJXH,C.LCSLID,C.SBXH,C.XFSTSE AS TSE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_FZC_SBMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '30'
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.TSE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_GJ_SBMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '30'
             UNION ALL
            SELECT A.DJXH,C.LCSLID,C.SBXH,C.TSE
              FROM TL_TSSH.CKTS_LC_SBXX A
             INNER JOIN TL_TSSH.CKTS_LC_SHXX B ON B.LCSLID_SB=A.LCSLID_SB
             INNER JOIN TL_TSSH.CKTS_SB_YS_SBMX C ON C.LCSLID=B.LCSLID AND C.BYBLBZ='N'
             WHERE A.TSSWJG_DM=V_SWCODE
               AND A.QDSJ>=LD_THISYEAR AND A.QDSJ<LD_NEXTMONTH
               AND B.LCTJJC = '30'
           ) T;

    --审核通过免抵退税额
    SELECT ROUND(NVL(SUM(T.FS_ZZSTSE+T.FS_XFSTSE),0)/10000,6)
      INTO LN_SH_ZZS
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.LCTJJC = '30';

    --审批免抵退税额
    SELECT ROUND(NVL(SUM(T.SEHZ_ZZSTSE + T.SEHZ_XFSTSE),0)/10000,6)
      INTO LN_SP_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SEHZRQ>=LD_THISYEAR AND T.SEHZRQ<LD_NEXTMONTH
       AND T.LCTJJC = '30';

    --国库办理免抵退税额
    SELECT ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_BL_ZZS
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH
       AND T.LCTJJC = '30';

    --返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,6),0)
      INTO TSFN_ZZS
      FROM FG_CKTSFN_HXZG T, TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL
       AND T.CPCODE=S.CPCODE
       AND S.BAJC_YEAR = '30';

    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '38', V_SWCODE, LN_BAHS, LN_SBHS, 0, LN_SB_ZZS, LN_SH_ZZS, LN_SP_ZZS - TSFN_ZZS, LN_BL_ZZS - TSFN_ZZS
      FROM DUAL;
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '39', V_SWCODE, 0, 0, 0, 0, 0, 0, 0
      FROM DUAL;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --6、计算行
  BEGIN
    FOR LSF_XX IN (SELECT TRIM(TO_CHAR(SUBSTR(T.FORMULA,2,INSTR(T.FORMULA,')')-2),'00')) AS BBLC,
                          '('||REPLACE(REPLACE(REPLACE(SUBSTR(T.FORMULA,INSTR(T.FORMULA,'=')+1),'(',''''),'+',','),')','''')||')' AS BBCS
                     FROM TJBB_REPORT_FORMULA T
                    WHERE T.BBDM='B07101'
                      AND T.TYPE=2
                      AND T.FORMULA<>'(15)=100 *(13)/(14)'
                    ORDER BY T.YXJ)
    LOOP
      BEGIN
        LC_SQL := 'INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
                   SELECT '''||LC_THISMONTH||''', '''||LSF_XX.BBLC||''', '''||V_SWCODE||''', SUM(RDHS), SUM(SBHS),
                          SUM(SB_CKE_CUR), SUM(SB_TMSE_CUR), SUM(SH_TMSE_CUR), SUM(SP_TMSE_CUR), SUM(TK_CUR)
                     FROM TJBB_DT_B07101
                    WHERE SWJGDM='''||V_SWCODE||'''
                      AND SSNY='''||LC_THISMONTH||'''
                      AND TRIM(TO_CHAR(TO_NUMBER(BBLC))) IN '||LSF_XX.BBCS;

        EXECUTE IMMEDIATE LC_SQL;
        COMMIT;
      END;
    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --7、计算15行
  BEGIN
    INSERT INTO TJBB_DT_B07101 (SSNY, BBLC, SWJGDM, RDHS, SBHS, SB_CKE_CUR, SB_TMSE_CUR, SH_TMSE_CUR, SP_TMSE_CUR, TK_CUR)
    SELECT LC_THISMONTH, '15', V_SWCODE, NULL, NULL, NULL, 
           CASE WHEN B.SB_TMSE_CUR=0 THEN 0 ELSE 100 * A.SB_TMSE_CUR/B.SB_TMSE_CUR END,
           CASE WHEN B.SH_TMSE_CUR=0 THEN 0 ELSE 100 * A.SH_TMSE_CUR/B.SH_TMSE_CUR END,
           CASE WHEN B.SP_TMSE_CUR=0 THEN 0 ELSE 100 * A.SP_TMSE_CUR/B.SP_TMSE_CUR END,
           CASE WHEN B.TK_CUR=0 THEN 0 ELSE 100 * A.TK_CUR/B.TK_CUR END
      FROM TJBB_DT_B07101 A,
           TJBB_DT_B07101 B
     WHERE A.SWJGDM=V_SWCODE
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='13'
       AND B.SWJGDM=V_SWCODE
       AND B.SSNY=LC_THISMONTH
       AND B.BBLC='14';
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --8、更新上年同期列
  BEGIN
    UPDATE TJBB_DT_B07101 T
       SET (SB_CKE_LAST, SB_TMSE_LAST, SH_TMSE_LAST, SP_TMSE_LAST, TK_LAST)=
           (SELECT NVL(SB_CKE_CUR,0), NVL(SB_TMSE_CUR,0), NVL(SH_TMSE_CUR,0), NVL(SP_TMSE_CUR,0), NVL(TK_CUR,0)
              FROM TJBB_DT_B07101 B
             WHERE B.SWJGDM=V_SWCODE
               AND B.SSNY=LC_LASTMONTH
               AND B.BBLC=T.BBLC)
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --9、更新占比、同比列
  BEGIN
    UPDATE TJBB_DT_B07101 T
       SET RD_SB_LV     = CASE WHEN T.RDHS=0         THEN 0 ELSE 100 * T.SBHS/T.RDHS                    END,
           SB_CKE_TBLV  = CASE WHEN T.SB_CKE_LAST=0  THEN 0 ELSE 100 * T.SB_CKE_CUR/T.SB_CKE_LAST -100   END,
           SB_TMSE_TBLV = CASE WHEN T.SB_TMSE_LAST=0 THEN 0 ELSE 100 * T.SB_TMSE_CUR/T.SB_TMSE_LAST -100 END,
           SH_TMSE_TBLV = CASE WHEN T.SH_TMSE_LAST=0 THEN 0 ELSE 100 * T.SH_TMSE_CUR/T.SH_TMSE_LAST -100 END,
           SP_TMSE_TBLV = CASE WHEN T.SP_TMSE_LAST=0 THEN 0 ELSE 100 * T.SP_TMSE_CUR/T.SP_TMSE_LAST -100 END,
           TK_TBLV      = CASE WHEN T.TK_LAST=0      THEN 0 ELSE 100 * T.TK_CUR/T.TK_LAST -100           END
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH
       AND T.BBLC<>'15';
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --10、更新汇总列
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B07101 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B07101' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
