CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B06101_CSH_NEW
/**************************************************************
 * 市场采购情况统计表——经营主体备案情况表
 * 首次不用处理，非首次申报将上月数据迁移到本月报表中
 **************************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LC_PREVMONTH     VARCHAR2(6);
  V_TEMP           NUMBER(5) := 0;

BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;

  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LC_PREVMONTH :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-1),'YYYYMM');
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B06101 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、统计
  BEGIN
    --检查是否第一次使用该报表
    SELECT COUNT(1)
      INTO V_TEMP
      FROM TJBB_DT_B06101
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_PREVMONTH AND ROWNUM=1;
    IF V_TEMP > 0 THEN
      INSERT INTO TJBB_DT_B06101 (SSNY,BBLC,SWJGDM,AREA,PROV,SDSJ,JYH_BAS,JYH_BAS_HZ,JYZ_BAS,JYZ_BAS_HZ)
      SELECT LC_THISMONTH, BBLC,SWJGDM,AREA,PROV,SDSJ,JYH_BAS,JYH_BAS,JYZ_BAS,JYZ_BAS
        FROM TJBB_DT_B06101
       WHERE SWJGDM=V_SWCODE AND SSNY=LC_PREVMONTH;
      COMMIT;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  RETURN;
END;
/
