CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03108_CSH_NEW
/*************************************************
 * 浙江出口企业分注册类型统计表
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LC_THISMONTH     VARCHAR2(6);--当月
  LC_THISYEAR      VARCHAR2(6);--当年1月
  LC_LASTMONTH     VARCHAR2(6);--上年同期
  LC_LASTYEAR      VARCHAR2(6);--上年1月
  
  LN_CKE_HJ        NUMBER(16,4);--出口额合计
  LN_TSE_HJ        NUMBER(16,4);--退税额合计
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LD_SYSDATE       DATE;
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;

  LC_THISMONTH   :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LC_THISYEAR    :=TO_CHAR(LD_SYSDATE,'YYYY')||'01';
  LC_LASTMONTH   :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYYMM');
  LC_LASTYEAR    :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYY')||'01';

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03108 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、计算并插入本年明细
  BEGIN
    INSERT INTO TJBB_DT_B03108 (SSNY,BBLC,SWJGDM,CKE,TMSE,CKE_LAST,TMSE_LAST)
      WITH FL_DJZCLX AS (SELECT NVL(B.DJZCLX_JS,'190') AS DJZCLX_JS, NVL(B.JSMODE,'2') AS JSMODE,  
                                SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN USD_AMT_ALL ELSE 0 END)/10000 AS USD_AMT, 
                                SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN TS_AMT_ALL  ELSE 0 END)/10000 AS TS_AMT, 
                                SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN USD_AMT_ALL ELSE 0 END)/10000 AS USD_AMT_LAST, 
                                SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN TS_AMT_ALL  ELSE 0 END)/10000 AS TS_AMT_LAST
                           FROM TL_TSSH.TJBB_FHXX_CPCODE A
                           LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX B ON A.XMFL=B.CPCODE
                          WHERE SWCODE=V_SWCODE 
                            AND ((SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH) OR (SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH))
                          GROUP BY B.DJZCLX_JS, B.JSMODE)
    SELECT LC_THISMONTH, '01', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     UNION ALL
    SELECT LC_THISMONTH, '02', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.DJZCLX_JS IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '03', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE SUBSTR(T.DJZCLX_JS,1,1) IN ('2','3')
     UNION ALL
    SELECT LC_THISMONTH, '04', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE SUBSTR(T.DJZCLX_JS,1,1) NOT IN ('2','3')
       AND T.DJZCLX_JS NOT IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '05', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE<>'1'
     UNION ALL
    SELECT LC_THISMONTH, '06', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE<>'1' 
       AND T.DJZCLX_JS IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '07', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE<>'1' 
       AND SUBSTR(T.DJZCLX_JS,1,1) IN ('2','3')
     UNION ALL
    SELECT LC_THISMONTH, '08', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE<>'1' 
       AND SUBSTR(T.DJZCLX_JS,1,1) NOT IN ('2','3')
       AND T.DJZCLX_JS NOT IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '09', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE='1'
     UNION ALL
    SELECT LC_THISMONTH, '10', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE='1' 
       AND T.DJZCLX_JS IN ('110','141','143','151','161','162','164','165')
     UNION ALL
    SELECT LC_THISMONTH, '11', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE='1' 
       AND SUBSTR(T.DJZCLX_JS,1,1) IN ('2','3')
     UNION ALL
    SELECT LC_THISMONTH, '12', V_SWCODE, ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_DJZCLX T
     WHERE T.JSMODE='1' 
       AND SUBSTR(T.DJZCLX_JS,1,1) NOT IN ('2','3')
       AND T.DJZCLX_JS NOT IN ('110','141','143','151','161','162','164','165')
    ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --2、计算并插入合计数
  BEGIN
    SELECT CKE, TMSE
      INTO LN_CKE_HJ, LN_TSE_HJ
      FROM TJBB_DT_B03108
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH AND BBLC='01';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  --4、同比计算
  BEGIN
    UPDATE TJBB_DT_B03108
       SET CKE_TB  = CASE WHEN NVL(CKE_LAST,0)=0  THEN NULL ELSE ROUND(100 * CKE  / CKE_LAST  -100,1) END,
           TMSE_TB = CASE WHEN NVL(TMSE_LAST,0)=0 THEN NULL ELSE ROUND(100 * TMSE / TMSE_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --5、占比计算
  BEGIN
    UPDATE TJBB_DT_B03108 T
       SET CKE_ZB  = CASE WHEN NVL(LN_CKE_HJ,0)=0 THEN NULL ELSE ROUND(100 * CKE  / LN_CKE_HJ,1) END,
           TMSE_ZB = CASE WHEN NVL(LN_TSE_HJ,0)=0 THEN NULL ELSE ROUND(100 * TMSE / LN_TSE_HJ,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --6、汇总栏初始化
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03108 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03108' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
