CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B02107_CSH_NEW
/*************************************************
 * 外贸综合服务企业基本信息表
 * 202202，针对同时申报出口货物劳务以及服务贸易的企业，调整lctjjc
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LC_THISMONTH     VARCHAR2(6);
  LD_SYSDATE       DATE;
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;

  LC_THISMONTH   :=TO_CHAR(LD_SYSDATE,'YYYYMM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02107 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、统计
  BEGIN
    INSERT INTO TJBB_DT_B02107 (SSNY, BBLC, SWJGDM, XH,
           NSRSBH, QYHGDM, NSRMC, JSJDJDM, QYFDDBR, DJRQ, RDRQ_YBNSR, RDRQ_CKTS, NSRZT, ZCLX, JYZLX, QYFR_ZJLX, ZJHM,
           ZCDZ, JYDZ)
    SELECT LC_THISMONTH, SUBSTR(A.SWJGDM, 4, 4)|| SUBSTR('000000'||ROWNUM, LENGTH('000000'||ROWNUM)-5, 6), V_SWCODE, ROWNUM,
           CASE WHEN A.SHXYNO=' ' THEN A.NSRDJNO ELSE A.SHXYNO END, A.QYHGDM, A.NSRMC, A.JSJDJDM, A.FRDB_MC, A.SWDJ_DATE, A.YBNSR_DATE, A.SQ_DATE,
           A.NSRZT_JS, A.DJZCLX_JS, A.QYLX, A.FRDB_ZJLX, A.FRDB_ZJHM, A.ADDRESS_ZC, A.ADDRESS_JY
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG ='N'
       AND A.BAJC_YEAR IN ('70','71','72');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;


  --2、行内计算
  --3、汇总栏初始化
  RETURN;
END;
/
