CREATE OR REPLACE PROCEDURE PRO_TJBB_CSH_9X10
/*
 * 省局月报表/出口退税月报表（不计结转），所有税务局重新制表
 * 需要手工调制报表所属期
 */
(
  LC_MONTH    IN  VARCHAR2
)
AS
  LC_SWJGDM        VARCHAR2(11);
  LN_ERROR         NUMBER;
  LC_MSG           VARCHAR2(2000);
BEGIN
  --区县局
  FOR LSF_SWJG IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND YXWS=7 AND SWJG_DM LIKE '13301%' ORDER BY SWJG_DM) LOOP
    LC_SWJGDM := LSF_SWJG.SWJG_DM;

    PRO_TJBB_DT_B02103_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    PRO_TJBB_DT_B02112_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    PRO_TJBB_DT_B02113_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    PRO_TJBB_DT_B05101_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    COMMIT;
  END LOOP;
END;
/
