CREATE OR REPLACE PROCEDURE PRO_TJBB_B03_HZ
/*
 * 省局月报表，地市局、省局初始化
 * 需要指定区县级税务机关和报表所属期
 */
(
  LC_SWJGDM   IN  VARCHAR2,
  LC_MONTH    IN  VARCHAR2
)
AS
  LN_ERROR         NUMBER;
  LC_MSG           VARCHAR2(2000);
BEGIN
  --按报表顺序依次制表
    BEGIN
      PRO_TJBB_DT_B03101_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03101_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03101_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03102_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03102_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03102_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03103_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03103_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03103_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03104_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03104_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03104_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03105_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03105_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03105_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03106_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03106_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03106_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03107_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03107_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03107_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03108_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03108_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03108_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03109_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03109_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03109_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03110_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03110_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03110_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03111_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03111_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03111_CSH失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03112_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03112_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03112_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03113_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03113_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03113_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03114_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03114_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03114_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03115_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03115_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03115_HZ失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B02112_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02112_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02112_HZ_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
/*
    BEGIN
      PRO_TJBB_DT_B02113_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02113_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02113_HZ_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
*/
    BEGIN
      PRO_TJBB_DT_B03116_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03116_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03116_HZ_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
    BEGIN
      PRO_TJBB_DT_B03117_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03117_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03117_HZ_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;

END;
/
