CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B05101_CSH_NEW
/**************************************************************
 * 跨境电商统计表——跨境电商出口情况统计表
 **************************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_INITDATE      DATE;
  LD_NEXTDATE      DATE;
  LC_INITMONTH     VARCHAR2(6);

  LN_CKE_9610_HS      NUMBER(16,4);
  LN_CKE_9610_JE      NUMBER(16,4);
  LN_TMS_9610_HS      NUMBER(16,4);
  LN_TMS_9610_JE      NUMBER(16,4);
  LN_CKE_9710_HS      NUMBER(16,4);
  LN_CKE_9710_JE      NUMBER(16,4);
  LN_TMS_9710_HS      NUMBER(16,4);
  LN_TMS_9710_JE      NUMBER(16,4);
  LN_CKE_9810_HS      NUMBER(16,4);
  LN_CKE_9810_JE      NUMBER(16,4);
  LN_TMS_9810_HS      NUMBER(16,4);
  LN_TMS_9810_JE      NUMBER(16,4);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'YY');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B05101 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、统计
  BEGIN
    LD_INITDATE:= TO_DATE('2019-01-01','YYYY-MM-DD');
    LOOP
      EXIT WHEN LD_INITDATE >LD_SYSDATE;
      LC_INITMONTH :=TO_CHAR(LD_INITDATE,'YYYYMM');
      LD_NEXTDATE := ADD_MONTHS(LD_INITDATE,1);
      
      SELECT COUNT(DISTINCT T.DJXH), ROUND(NVL(SUM(T.RMBLAJ),0)/10000,4)
        INTO LN_CKE_9610_HS, LN_CKE_9610_JE
        FROM TL_TSSH.CKTS_WBSJ_HG_BGD T
       WHERE T.TSSWJG_DM_1=V_SWCODE
         AND T.JGFS_DM='9610'
         AND T.CKRQ_1>=LD_INITDATE AND T.CKRQ_1<LD_NEXTDATE;
      SELECT COUNT(DISTINCT T.DJXH), ROUND(NVL(SUM(T.RMBLAJ),0)/10000,4)
        INTO LN_CKE_9710_HS, LN_CKE_9710_JE
        FROM TL_TSSH.CKTS_WBSJ_HG_BGD T
       WHERE T.TSSWJG_DM_1=V_SWCODE
         AND T.JGFS_DM='9710'
         AND T.CKRQ_1>=LD_INITDATE AND T.CKRQ_1<LD_NEXTDATE;
      SELECT COUNT(DISTINCT T.DJXH), ROUND(NVL(SUM(T.RMBLAJ),0)/10000,4)
        INTO LN_CKE_9810_HS, LN_CKE_9810_JE
        FROM TL_TSSH.CKTS_WBSJ_HG_BGD T
       WHERE T.TSSWJG_DM_1=V_SWCODE
         AND T.JGFS_DM='9810'
         AND T.CKRQ_1>=LD_INITDATE AND T.CKRQ_1<LD_NEXTDATE;
          
      SELECT COUNT(DISTINCT A.DJXH), ROUND(NVL(SUM(A.MDTSE),0)/10000,4)
        INTO LN_TMS_9610_HS, LN_TMS_9610_JE
        FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 A
       WHERE A.TSSWJG_DM=V_SWCODE
         AND A.SBRQ>=LD_INITDATE AND A.SBRQ<LD_NEXTDATE
         AND A.TDCODE='9610';
      SELECT COUNT(DISTINCT A.DJXH), ROUND(NVL(SUM(A.MDTSE),0)/10000,4)
        INTO LN_TMS_9710_HS, LN_TMS_9710_JE
        FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 A
       WHERE A.TSSWJG_DM=V_SWCODE
         AND A.SBRQ>=LD_INITDATE AND A.SBRQ<LD_NEXTDATE
         AND A.TDCODE='9710';
      SELECT COUNT(DISTINCT A.DJXH), ROUND(NVL(SUM(A.MDTSE),0)/10000,4)
        INTO LN_TMS_9810_HS, LN_TMS_9810_JE
        FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 A
       WHERE A.TSSWJG_DM=V_SWCODE
         AND A.SBRQ>=LD_INITDATE AND A.SBRQ<LD_NEXTDATE
         AND A.TDCODE='9810';

      INSERT INTO TJBB_DT_B05101 (
             SSNY,BBLC,SWJGDM,QJNY,
             CKE_9610_HS, CKE_9610_HS_HZ, CKE_9610_JE, CKE_9610_JE_HZ, TMS_9610_HS, TMS_9610_HS_HZ, TMS_9610_JE, TMS_9610_JE_HZ,
             CKE_9710_HS, CKE_9710_HS_HZ, CKE_9710_JE, CKE_9710_JE_HZ, TMS_9710_HS, TMS_9710_HS_HZ, TMS_9710_JE, TMS_9710_JE_HZ,
             CKE_9810_HS, CKE_9810_HS_HZ, CKE_9810_JE, CKE_9810_JE_HZ, TMS_9810_HS, TMS_9810_HS_HZ, TMS_9810_JE, TMS_9810_JE_HZ)
      SELECT LC_THISMONTH, LC_INITMONTH,V_SWCODE,LC_INITMONTH,
             LN_CKE_9610_HS, LN_CKE_9610_HS, LN_CKE_9610_JE, LN_CKE_9610_JE, LN_TMS_9610_HS, LN_TMS_9610_HS, LN_TMS_9610_JE, LN_TMS_9610_JE,
             LN_CKE_9710_HS, LN_CKE_9710_HS, LN_CKE_9710_JE, LN_CKE_9710_JE, LN_TMS_9710_HS, LN_TMS_9710_HS, LN_TMS_9710_JE, LN_TMS_9710_JE,
             LN_CKE_9810_HS, LN_CKE_9810_HS, LN_CKE_9810_JE, LN_CKE_9810_JE, LN_TMS_9810_HS, LN_TMS_9810_HS, LN_TMS_9810_JE, LN_TMS_9810_JE
            FROM DUAL;
      LD_INITDATE := LD_NEXTDATE;
    END LOOP;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  RETURN;
END;
/
