CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B01106_CSH_NEW
/*************************************************
 * 涉嫌骗取出口退税案源移送稽查部门情况统计月报表
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B01106 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、数据筛选
  BEGIN
    INSERT INTO TJBB_DT_B01106 (SSNY, BBLC, SWJGDM,
           AY, SUMARY, ZYAY,
           NSRSBH, NSRMC,
           SPDM, SPMC,
           CKE, CKE_HZ, TMSE_HJ, TMSE_HJ_HZ, TSE, TSE_HZ, MDSE, MDSE_HZ,
           YSDW, YSSJ, YSSWH, YSR,
           JSDW, JSR, JSSJ, BYJA,
           LAZT, LASJ, XHZT, BZ)
    SELECT LC_THISMONTH, '00'||ROW_NUMBER() OVER (ORDER BY T.YSJC_DATE), V_SWCODE,
           T.AJLY_NAME, T.AJLY_SUMMARY, T.AJLY_REASON,
           CASE WHEN T.SHXYNO IS NOT NULL AND T.SHXYNO<>' ' THEN T.SHXYNO ELSE T.NSRDJNO END, T.QYNAME,
           T.SASP_CODE, T.SASP_NAME,
           T.USD_AMT, T.USD_AMT, T.MDTS_AMT, T.MDTS_AMT, T.TS_AMT, T.TS_AMT, T.MD_AMT, T.MD_AMT,
           T.YSJC_SWNAME, T.YSJC_DATE, T.YSJC_NO, T.YSJC_USER,
           T.JCJS_SWNAME, T.JCJS_USER, T.JCJS_DATE, T.JCJS_FLAG,
           T.JCLA_FLAG, T.JCLA_DATE, T.JCJA_FLAG, T.REMARK
      FROM TL_TSSH.CKTS_OTHER_SXPSAJ T
     WHERE T.SWJGDM=V_SWCODE 
       AND (T.JCJA_DATE IS NULL OR T.JCJA_DATE>LD_THISYEAR)
     ORDER BY T.YSJC_DATE;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
