CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B02103_CSH_NEW
/*************************************************
 * 跨境电子商务零售出口退税情况统计表9610
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
  LD_NEXTMONTH     DATE;
  LC_SQL           VARCHAR2(4000);
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LN_BA_HS         NUMBER(10);
  LN_SB_HS         NUMBER(10);
  LN_SB_CKE        NUMBER(18,6);
  LN_SB_TMSE       NUMBER(18,6);
  LN_SB_TSE        NUMBER(18,6);
  LN_SH_TMSE       NUMBER(18,6);
  LN_SH_TSE        NUMBER(18,6);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_SYSDATE,1),'MM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02103 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、有9610业务的外贸企业
  BEGIN
    --备案户数
    SELECT COUNT(DISTINCT A.CPCODE)
      INTO LN_BA_HS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE AND A.ZX_FLAG <>'R' AND A.JSMODE<>'1'
       AND EXISTS (SELECT 1 FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 S WHERE S.DJXH=A.CPCODE AND S.TDCODE='9610' AND S.SBYWB_DM<>'A0305001');
    --当月申报
    SELECT COUNT(DISTINCT T.DJXH), NVL(ROUND(SUM(T.MYLAJ)/10000,6),0), 
           NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE)/10000,6),0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM<>'A0305001'
       AND T.SBRQ>=LD_SYSDATE AND T.SBRQ<LD_NEXTMONTH;
    --当月审核
    SELECT NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE)/10000,6),0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM<>'A0305001'
       AND T.FSRQ>=LD_SYSDATE AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --当月备案有效的
    INSERT INTO TJBB_DT_B02103 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '01', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
           FROM DUAL;
    COMMIT;
    --当年申报
    SELECT COUNT(DISTINCT T.DJXH), NVL(ROUND(SUM(T.MYLAJ)/10000,6),0), 
           NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE)/10000,6),0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM<>'A0305001'
       AND T.SBRQ>=LD_THISYEAR AND T.SBRQ<LD_NEXTMONTH;
    --当年审核
    SELECT NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE)/10000,6),0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM<>'A0305001'
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --当年备案有效的
    INSERT INTO TJBB_DT_B02103 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '04', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
           FROM DUAL;
    COMMIT;
    --累计申报
    SELECT COUNT(DISTINCT T.DJXH), NVL(ROUND(SUM(T.MYLAJ)/10000,6),0), 
           NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE)/10000,6),0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM<>'A0305001'
       AND T.SBRQ>=DATE'2013-01-01' AND T.SBRQ<LD_NEXTMONTH;
    --累计审核
    SELECT NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE)/10000,6),0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM<>'A0305001'
       AND T.FSRQ>=DATE'2013-01-01' AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --财税〔2013〕96号执行以来
    INSERT INTO TJBB_DT_B02103 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '07', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
           FROM DUAL;
    COMMIT;
  END;

  --2、有9610业务的生产企业
  BEGIN
    --备案户数
    SELECT COUNT(DISTINCT A.CPCODE)
      INTO LN_BA_HS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE AND A.ZX_FLAG <>'R' AND A.JSMODE='1'
       AND EXISTS (SELECT 1 FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 S WHERE S.DJXH=A.CPCODE AND S.TDCODE='9610' AND S.SBYWB_DM='A0305001');
    --当月申报
    SELECT COUNT(DISTINCT T.DJXH), NVL(ROUND(SUM(T.MYLAJ)/10000,6),0), 
           NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END))/10000,6),0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     INNER JOIN TL_TSSH.CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM='A0305001'
       AND T.SBRQ>=LD_SYSDATE AND T.SBRQ<LD_NEXTMONTH;
    --当月审核
    SELECT NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE * (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END))/10000,6),0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     INNER JOIN TL_TSSH.CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM='A0305001'
       AND T.FSRQ>=LD_SYSDATE AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --当月备案有效的
    INSERT INTO TJBB_DT_B02103 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '02', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
           FROM DUAL;
    COMMIT;
    --当年申报
    SELECT COUNT(DISTINCT T.DJXH), NVL(ROUND(SUM(T.MYLAJ)/10000,6),0), 
           NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END))/10000,6),0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     INNER JOIN TL_TSSH.CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM='A0305001'
       AND T.SBRQ>=LD_THISYEAR AND T.SBRQ<LD_NEXTMONTH;
    --当年审核
    SELECT NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE * (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END))/10000,6),0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     INNER JOIN TL_TSSH.CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM='A0305001'
       AND T.FSRQ>=LD_THISYEAR AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --当年备案有效的
    INSERT INTO TJBB_DT_B02103 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '05', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
           FROM DUAL;
    COMMIT;
    --累计申报
    SELECT COUNT(DISTINCT T.DJXH), NVL(ROUND(SUM(T.MYLAJ)/10000,6),0), 
           NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE * (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END))/10000,6),0)
      INTO LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     INNER JOIN TL_TSSH.CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM='A0305001'
       AND T.SBRQ>=DATE'2013-01-01' AND T.SBRQ<LD_NEXTMONTH;
    --累计审核
    SELECT NVL(ROUND(SUM(T.MDTSE)/10000,6),0), NVL(ROUND(SUM(T.MDTSE * (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END))/10000,6),0)
      INTO LN_SH_TMSE, LN_SH_TSE
      FROM TL_TSSH.CKTS_WBSJ_BGD_9X10 T
     INNER JOIN TL_TSSH.CKTS_LC_SHXX A ON A.LCSLID=T.LCSLID
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.TDCODE='9610'
       AND T.SBYWB_DM='A0305001'
       AND T.FSRQ>=DATE'2013-01-01' AND T.FSRQ<LD_NEXTMONTH
       AND T.ZYTSBZ='Y';
    --财税〔2013〕96号执行以来
    INSERT INTO TJBB_DT_B02103 (SSNY,BBLC,SWJGDM,BAHS,SBHS,SBTSCKE,SB_TMSE,SB_TSE,SB_MDSE,
                SH_TMSE,SH_TSE,SH_MDSE,BL_TMSE,BL_TSE,BL_MDSE)
         SELECT LC_THISMONTH, '08', V_SWCODE, LN_BA_HS, LN_SB_HS, LN_SB_CKE, LN_SB_TMSE, LN_SB_TSE, LN_SB_TMSE - LN_SB_TSE,
                LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE, LN_SH_TMSE, LN_SH_TSE, LN_SH_TMSE - LN_SH_TSE
           FROM DUAL;
    COMMIT;
  END;

  BEGIN
    UPDATE TJBB_DT_B02103 
       SET ZYSP = (SELECT S1.MLMC
                     FROM DM_SPML S1, 
                          (SELECT SPML,SUM(MYLAJ) AS USD_TOTAL
                             FROM (SELECT C.SPML,B.MYLAJ
                                     FROM TL_TSSH.CKTS_LC_SHXX A
                                    INNER JOIN TL_TSSH.CKTS_WBSJ_BGD_9X10 B ON B.LCSLID=A.LCSLID AND B.TDCODE='9610' AND B.SBYWB_DM<>'A0305001'
                                    INNER JOIN TL_ADMIN.DM_SPFL C ON C.SPDL=SUBSTR(B.CKSP_DM,1,2)
                                    WHERE A.TSSWJG_DM=V_SWCODE
                                      AND A.QDSJ>=DATE'2013-01-01'
                                      AND A.QDSJ<LD_NEXTMONTH) S2
                            GROUP BY SPML
                            ORDER BY USD_TOTAL DESC) S3
                    WHERE S1.SPML=S3.SPML
                      AND ROWNUM=1)
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('01','04','07');
    COMMIT;

    UPDATE TJBB_DT_B02103 
       SET ZYSP = (SELECT S1.MLMC
                     FROM DM_SPML S1, 
                          (SELECT SPML,SUM(MYLAJ) AS USD_TOTAL
                             FROM (SELECT C.SPML,B.MYLAJ
                                     FROM TL_TSSH.CKTS_LC_SHXX A
                                    INNER JOIN TL_TSSH.CKTS_WBSJ_BGD_9X10 B ON B.LCSLID=A.LCSLID AND B.TDCODE='9610' AND B.SBYWB_DM='A0305001'
                                    INNER JOIN TL_ADMIN.DM_SPFL C ON C.SPDL=SUBSTR(B.CKSP_DM,1,2)
                                    WHERE A.TSSWJG_DM=V_SWCODE
                                      AND A.QDSJ>=DATE'2013-01-01'
                                      AND A.QDSJ<LD_NEXTMONTH) S2
                            GROUP BY SPML
                            ORDER BY USD_TOTAL DESC) S3
                    WHERE S1.SPML=S3.SPML
                      AND ROWNUM=1)
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('02','05','08');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --10、计算行
  BEGIN
    FOR LSF_XX IN (SELECT TRIM(TO_CHAR(SUBSTR(T.FORMULA,2,INSTR(T.FORMULA,')')-2),'00')) AS BBLC,
                          '('||REPLACE(REPLACE(REPLACE(SUBSTR(T.FORMULA,INSTR(T.FORMULA,'=')+1),'(',''''),'+',','),')','''')||')' AS BBCS
                     FROM TJBB_REPORT_FORMULA T 
                    WHERE T.BBDM='B02103' 
                      AND T.TYPE=2
                    ORDER BY T.YXJ) 
    LOOP
      BEGIN
        LC_SQL := 'INSERT INTO TJBB_DT_B02103 (SSNY, BBLC, SWJGDM,
                          BAHS,    SBHS,   SBTSCKE,
                          SB_TMSE, SB_TSE, SB_MDSE,
                          SH_TMSE, SH_TSE, SH_MDSE,
                          BL_TMSE, BL_TSE, BL_MDSE)
                   SELECT '''||LC_THISMONTH||''', '''||LSF_XX.BBLC||''', '''||V_SWCODE||''', 
                          SUM(BAHS),    SUM(SBHS),   SUM(SBTSCKE),
                          SUM(SB_TMSE), SUM(SB_TSE), SUM(SB_MDSE),
                          SUM(SH_TMSE), SUM(SH_TSE), SUM(SH_MDSE),
                          SUM(BL_TMSE), SUM(BL_TSE), SUM(BL_MDSE)
                     FROM TJBB_DT_B02103
                    WHERE SWJGDM='''||V_SWCODE||'''
                      AND SSNY='''||LC_THISMONTH||'''
                      AND TRIM(TO_CHAR(TO_NUMBER(BBLC))) IN '||LSF_XX.BBCS;
        
        EXECUTE IMMEDIATE LC_SQL;
        COMMIT;
      END;
    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --11、更新汇总列
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B02103 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02103' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
