CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03102_CSH_NEW
/*************************************************
 * 浙江省办理出口退税累计趋势图（全部重新统计）
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY    IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
  LD_NEXTMONTH     DATE;
  LD_LASTYEAR      DATE;

  LC_THISYEAR      VARCHAR2(4);--当年
  LC_LASTYEAR      VARCHAR2(4);--上年
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_SYSDATE,1),'MM');
  LD_LASTYEAR  :=TRUNC(ADD_MONTHS(LD_SYSDATE,-12),'YY');

  LC_THISYEAR    :=TO_CHAR(LD_SYSDATE,'YYYY');
  LC_LASTYEAR    :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYY');
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03102 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;
  
  --1、制表
  BEGIN
    --1.1 本年数
    --1.1.1 生产企业
    INSERT INTO TJBB_DT_B03102 (SSNY,BBLC,SWJGDM,
           JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,
           JAN_HZ,FEB_HZ,MAR_HZ,APR_HZ,MAY_HZ,JUN_HZ,JUL_HZ,AUG_HZ,SEP_HZ,OCT_HZ,NOV_HZ,DEC_HZ)
    WITH TSFN AS (SELECT TO_CHAR(T.RKRQ,'YYYYMM') AS FNMONTH, NVL(ROUND(SUM(T.SJJE)/10000,0),0) AS FNSE
                    FROM FG_CKTSFN_HXZG T
                    LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX R ON R.DJXH_JS=T.DJXH
                   WHERE T.SKSSSWJG_DM=V_SWCODE
                     AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
                     AND T.YWHZBUUID IS NULL
                     AND R.JSMODE='1'
                   GROUP BY TO_CHAR(T.RKRQ,'YYYYMM')),
         TSTK AS (SELECT TO_CHAR(S.XHRQ_TK,'YYYYMM') AS TKMONTH, NVL(ROUND(SUM(S.GKBL_ZZSTSE+S.GKBL_XFSTSE)/10000,0),0) AS TKSE
                    FROM TL_TSSH.CKTS_LC_SEHZXX S
                    LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX R ON R.DJXH_JS=S.DJXH
                   WHERE S.CKTMSJHSSSWJGDM=V_SWCODE
                     AND S.XHRQ_TK>=LD_THISYEAR AND S.XHRQ_TK<LD_NEXTMONTH
                     AND R.JSMODE='1'
                   GROUP BY TO_CHAR(S.XHRQ_TK,'YYYYMM'))
    SELECT LC_THISMONTH,'01',V_SWCODE,
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'01' AND LC_THISYEAR||'01'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'02' AND LC_THISYEAR||'02'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'03' AND LC_THISYEAR||'03'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'04' AND LC_THISYEAR||'04'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'05' AND LC_THISYEAR||'05'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'06' AND LC_THISYEAR||'06'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'07' AND LC_THISYEAR||'07'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'08' AND LC_THISYEAR||'08'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'09' AND LC_THISYEAR||'09'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'10' AND LC_THISYEAR||'10'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'11' AND LC_THISYEAR||'11'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'12' AND LC_THISYEAR||'12'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'01' AND LC_THISYEAR||'01'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'02' AND LC_THISYEAR||'02'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'03' AND LC_THISYEAR||'03'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'04' AND LC_THISYEAR||'04'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'05' AND LC_THISYEAR||'05'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'06' AND LC_THISYEAR||'06'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'07' AND LC_THISYEAR||'07'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'08' AND LC_THISYEAR||'08'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'09' AND LC_THISYEAR||'09'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'10' AND LC_THISYEAR||'10'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'11' AND LC_THISYEAR||'11'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'12' AND LC_THISYEAR||'12'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END)
      FROM TSTK
      LEFT JOIN TSFN ON TSFN.FNMONTH = TSTK.TKMONTH;
    COMMIT;

    --1.1.2 外贸企业
    INSERT INTO TJBB_DT_B03102 (SSNY,BBLC,SWJGDM,
           JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,
           JAN_HZ,FEB_HZ,MAR_HZ,APR_HZ,MAY_HZ,JUN_HZ,JUL_HZ,AUG_HZ,SEP_HZ,OCT_HZ,NOV_HZ,DEC_HZ)
    WITH TSFN AS (SELECT TO_CHAR(T.RKRQ,'YYYYMM') AS FNMONTH, NVL(ROUND(SUM(T.SJJE)/10000,0),0) AS FNSE
                    FROM FG_CKTSFN_HXZG T
                    LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX R ON R.DJXH_JS=T.DJXH
                   WHERE T.SKSSSWJG_DM=V_SWCODE
                     AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
                     AND T.YWHZBUUID IS NULL
                     AND (R.JSMODE IS NULL OR R.JSMODE<>'1')
                   GROUP BY TO_CHAR(T.RKRQ,'YYYYMM')),
         TSTK AS (SELECT TO_CHAR(S.XHRQ_TK,'YYYYMM') AS TKMONTH, NVL(ROUND(SUM(S.GKBL_ZZSTSE+S.GKBL_XFSTSE)/10000,0),0) AS TKSE
                    FROM TL_TSSH.CKTS_LC_SEHZXX S
                    LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX R ON R.DJXH_JS=S.DJXH
                   WHERE S.CKTMSJHSSSWJGDM=V_SWCODE
                     AND S.XHRQ_TK>=LD_THISYEAR AND S.XHRQ_TK<LD_NEXTMONTH
                     AND (R.JSMODE IS NULL OR R.JSMODE<>'1')
                   GROUP BY TO_CHAR(S.XHRQ_TK,'YYYYMM'))
    SELECT LC_THISMONTH,'02',V_SWCODE,
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'01' AND LC_THISYEAR||'01'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'02' AND LC_THISYEAR||'02'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'03' AND LC_THISYEAR||'03'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'04' AND LC_THISYEAR||'04'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'05' AND LC_THISYEAR||'05'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'06' AND LC_THISYEAR||'06'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'07' AND LC_THISYEAR||'07'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'08' AND LC_THISYEAR||'08'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'09' AND LC_THISYEAR||'09'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'10' AND LC_THISYEAR||'10'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'11' AND LC_THISYEAR||'11'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'12' AND LC_THISYEAR||'12'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'01' AND LC_THISYEAR||'01'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'02' AND LC_THISYEAR||'02'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'03' AND LC_THISYEAR||'03'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'04' AND LC_THISYEAR||'04'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'05' AND LC_THISYEAR||'05'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'06' AND LC_THISYEAR||'06'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'07' AND LC_THISYEAR||'07'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'08' AND LC_THISYEAR||'08'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'09' AND LC_THISYEAR||'09'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'10' AND LC_THISYEAR||'10'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'11' AND LC_THISYEAR||'11'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_THISYEAR||'12' AND LC_THISYEAR||'12'<=V_SSNY THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END)
      FROM TSTK
      LEFT JOIN TSFN ON TSFN.FNMONTH = TSTK.TKMONTH;
    COMMIT;
    
    --1.2 上年数
    --1.2.1 生产企业
    INSERT INTO TJBB_DT_B03102 (SSNY,BBLC,SWJGDM,
           JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,
           JAN_HZ,FEB_HZ,MAR_HZ,APR_HZ,MAY_HZ,JUN_HZ,JUL_HZ,AUG_HZ,SEP_HZ,OCT_HZ,NOV_HZ,DEC_HZ)
    WITH TSFN AS (SELECT TO_CHAR(T.RKRQ,'YYYYMM') AS FNMONTH, NVL(ROUND(SUM(T.SJJE)/10000,0),0) AS FNSE
                    FROM FG_CKTSFN_HXZG T
                    LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX R ON R.DJXH_JS=T.DJXH
                   WHERE T.SKSSSWJG_DM=V_SWCODE
                     AND T.RKRQ>=LD_LASTYEAR AND T.RKRQ<LD_THISYEAR
                     AND T.YWHZBUUID IS NULL
                     AND R.JSMODE='1'
                   GROUP BY TO_CHAR(T.RKRQ,'YYYYMM')),
         TSTK AS (SELECT TO_CHAR(S.XHRQ_TK,'YYYYMM') AS TKMONTH, NVL(ROUND(SUM(S.GKBL_ZZSTSE+S.GKBL_XFSTSE)/10000,0),0) AS TKSE
                    FROM TL_TSSH.CKTS_LC_SEHZXX S
                    LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX R ON R.DJXH_JS=S.DJXH
                   WHERE S.CKTMSJHSSSWJGDM=V_SWCODE
                     AND S.XHRQ_TK>=LD_LASTYEAR AND S.XHRQ_TK<LD_THISYEAR
                     AND R.JSMODE='1'
                   GROUP BY TO_CHAR(S.XHRQ_TK,'YYYYMM'))
    SELECT LC_THISMONTH,'04',V_SWCODE,
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'01' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'02' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'03' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'04' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'05' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'06' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'07' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'08' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'09' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'10' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'11' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'12' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'01' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'02' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'03' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'04' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'05' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'06' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'07' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'08' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'09' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'10' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'11' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'12' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END)
      FROM TSTK
      LEFT JOIN TSFN ON TSFN.FNMONTH = TSTK.TKMONTH;
    COMMIT;

    --1.2.2 外贸企业
    INSERT INTO TJBB_DT_B03102 (SSNY,BBLC,SWJGDM,
           JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,
           JAN_HZ,FEB_HZ,MAR_HZ,APR_HZ,MAY_HZ,JUN_HZ,JUL_HZ,AUG_HZ,SEP_HZ,OCT_HZ,NOV_HZ,DEC_HZ)
    WITH TSFN AS (SELECT TO_CHAR(T.RKRQ,'YYYYMM') AS FNMONTH, NVL(ROUND(SUM(T.SJJE)/10000,0),0) AS FNSE
                    FROM FG_CKTSFN_HXZG T
                    LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX R ON R.DJXH_JS=T.DJXH
                   WHERE T.SKSSSWJG_DM=V_SWCODE
                     AND T.RKRQ>=LD_LASTYEAR AND T.RKRQ<LD_THISYEAR
                     AND T.YWHZBUUID IS NULL
                     AND (R.JSMODE IS NULL OR R.JSMODE<>'1')
                   GROUP BY TO_CHAR(T.RKRQ,'YYYYMM')),
         TSTK AS (SELECT TO_CHAR(S.XHRQ_TK,'YYYYMM') AS TKMONTH, NVL(ROUND(SUM(S.GKBL_ZZSTSE+S.GKBL_XFSTSE)/10000,0),0) AS TKSE
                    FROM TL_TSSH.CKTS_LC_SEHZXX S
                    LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX R ON R.DJXH_JS=S.DJXH
                   WHERE S.CKTMSJHSSSWJGDM=V_SWCODE
                     AND S.XHRQ_TK>=LD_LASTYEAR AND S.XHRQ_TK<LD_THISYEAR
                     AND (R.JSMODE IS NULL OR R.JSMODE<>'1')
                   GROUP BY TO_CHAR(S.XHRQ_TK,'YYYYMM'))
    SELECT LC_THISMONTH,'05',V_SWCODE,
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'01' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'02' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'03' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'04' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'05' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'06' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'07' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'08' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'09' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'10' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'11' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'12' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'01' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'02' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'03' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'04' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'05' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'06' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'07' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'08' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'09' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'10' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'11' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END),
           SUM(CASE WHEN TSTK.TKMONTH<=LC_LASTYEAR||'12' THEN NVL(TSTK.TKSE,0) - NVL(TSFN.FNSE,0) ELSE 0 END)
      FROM TSTK
      LEFT JOIN TSFN ON TSFN.FNMONTH = TSTK.TKMONTH;
    COMMIT;
    
    --合计统计
    INSERT INTO TJBB_DT_B03102 (SSNY,BBLC,SWJGDM,
           JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,
           JAN_HZ,FEB_HZ,MAR_HZ,APR_HZ,MAY_HZ,JUN_HZ,JUL_HZ,AUG_HZ,SEP_HZ,OCT_HZ,NOV_HZ,DEC_HZ)
    SELECT LC_THISMONTH, '03', V_SWCODE, 
           SUM(JAN),SUM(FEB),SUM(MAR),SUM(APR),SUM(MAY),SUM(JUN),SUM(JUL),SUM(AUG),SUM(SEP),SUM(OCT),SUM(NOV),SUM(DEC),
           SUM(JAN_HZ),SUM(FEB_HZ),SUM(MAR_HZ),SUM(APR_HZ),SUM(MAY_HZ),SUM(JUN_HZ),SUM(JUL_HZ),SUM(AUG_HZ),SUM(SEP_HZ),SUM(OCT_HZ),SUM(NOV_HZ),SUM(DEC_HZ)
      FROM TJBB_DT_B03102
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('01','02');
    COMMIT;

    --合计统计
    INSERT INTO TJBB_DT_B03102 (SSNY,BBLC,SWJGDM,
           JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,
           JAN_HZ,FEB_HZ,MAR_HZ,APR_HZ,MAY_HZ,JUN_HZ,JUL_HZ,AUG_HZ,SEP_HZ,OCT_HZ,NOV_HZ,DEC_HZ)
    SELECT LC_THISMONTH, '06', V_SWCODE, 
           SUM(JAN),SUM(FEB),SUM(MAR),SUM(APR),SUM(MAY),SUM(JUN),SUM(JUL),SUM(AUG),SUM(SEP),SUM(OCT),SUM(NOV),SUM(DEC),
           SUM(JAN_HZ),SUM(FEB_HZ),SUM(MAR_HZ),SUM(APR_HZ),SUM(MAY_HZ),SUM(JUN_HZ),SUM(JUL_HZ),SUM(AUG_HZ),SUM(SEP_HZ),SUM(OCT_HZ),SUM(NOV_HZ),SUM(DEC_HZ)
      FROM TJBB_DT_B03102
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('04','05');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;
  
  --2、同比
  BEGIN
    --生产
    INSERT INTO TJBB_DT_B03102 (SSNY,BBLC,SWJGDM,
           JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,
           JAN_HZ,FEB_HZ,MAR_HZ,APR_HZ,MAY_HZ,JUN_HZ,JUL_HZ,AUG_HZ,SEP_HZ,OCT_HZ,NOV_HZ,DEC_HZ)
    SELECT LC_THISMONTH, '07', V_SWCODE, 
           CASE WHEN NVL(B.JAN,0)=0 THEN NULL ELSE ROUND(100 * A.JAN/B.JAN -100,1) END,
           CASE WHEN NVL(B.FEB,0)=0 THEN NULL ELSE ROUND(100 * A.FEB/B.FEB -100,1) END,
           CASE WHEN NVL(B.MAR,0)=0 THEN NULL ELSE ROUND(100 * A.MAR/B.MAR -100,1) END,
           CASE WHEN NVL(B.APR,0)=0 THEN NULL ELSE ROUND(100 * A.APR/B.APR -100,1) END,
           CASE WHEN NVL(B.MAY,0)=0 THEN NULL ELSE ROUND(100 * A.MAY/B.MAY -100,1) END,
           CASE WHEN NVL(B.JUN,0)=0 THEN NULL ELSE ROUND(100 * A.JUN/B.JUN -100,1) END,
           CASE WHEN NVL(B.JUL,0)=0 THEN NULL ELSE ROUND(100 * A.JUL/B.JUL -100,1) END,
           CASE WHEN NVL(B.AUG,0)=0 THEN NULL ELSE ROUND(100 * A.AUG/B.AUG -100,1) END,
           CASE WHEN NVL(B.SEP,0)=0 THEN NULL ELSE ROUND(100 * A.SEP/B.SEP -100,1) END,
           CASE WHEN NVL(B.OCT,0)=0 THEN NULL ELSE ROUND(100 * A.OCT/B.OCT -100,1) END,
           CASE WHEN NVL(B.NOV,0)=0 THEN NULL ELSE ROUND(100 * A.NOV/B.NOV -100,1) END,
           CASE WHEN NVL(B.DEC,0)=0 THEN NULL ELSE ROUND(100 * A.DEC/B.DEC -100,1) END,
           CASE WHEN NVL(B.JAN_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.JAN_HZ/B.JAN_HZ -100,1) END,
           CASE WHEN NVL(B.FEB_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.FEB_HZ/B.FEB_HZ -100,1) END,
           CASE WHEN NVL(B.MAR_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.MAR_HZ/B.MAR_HZ -100,1) END,
           CASE WHEN NVL(B.APR_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.APR_HZ/B.APR_HZ -100,1) END,
           CASE WHEN NVL(B.MAY_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.MAY_HZ/B.MAY_HZ -100,1) END,
           CASE WHEN NVL(B.JUN_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.JUN_HZ/B.JUN_HZ -100,1) END,
           CASE WHEN NVL(B.JUL_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.JUL_HZ/B.JUL_HZ -100,1) END,
           CASE WHEN NVL(B.AUG_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.AUG_HZ/B.AUG_HZ -100,1) END,
           CASE WHEN NVL(B.SEP_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.SEP_HZ/B.SEP_HZ -100,1) END,
           CASE WHEN NVL(B.OCT_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.OCT_HZ/B.OCT_HZ -100,1) END,
           CASE WHEN NVL(B.NOV_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.NOV_HZ/B.NOV_HZ -100,1) END,
           CASE WHEN NVL(B.DEC_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.DEC_HZ/B.DEC_HZ -100,1) END
      FROM TJBB_DT_B03102 A,
           TJBB_DT_B03102 B
     WHERE A.SWJGDM=V_SWCODE
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='01'
       AND B.SWJGDM=V_SWCODE
       AND B.SSNY=LC_THISMONTH
       AND B.BBLC='04';
    COMMIT;
    
    --外贸
    INSERT INTO TJBB_DT_B03102 (SSNY,BBLC,SWJGDM,
           JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,
           JAN_HZ,FEB_HZ,MAR_HZ,APR_HZ,MAY_HZ,JUN_HZ,JUL_HZ,AUG_HZ,SEP_HZ,OCT_HZ,NOV_HZ,DEC_HZ)
    SELECT LC_THISMONTH, '08', V_SWCODE, 
           CASE WHEN NVL(B.JAN,0)=0 THEN NULL ELSE ROUND(100 * A.JAN/B.JAN -100,1) END,
           CASE WHEN NVL(B.FEB,0)=0 THEN NULL ELSE ROUND(100 * A.FEB/B.FEB -100,1) END,
           CASE WHEN NVL(B.MAR,0)=0 THEN NULL ELSE ROUND(100 * A.MAR/B.MAR -100,1) END,
           CASE WHEN NVL(B.APR,0)=0 THEN NULL ELSE ROUND(100 * A.APR/B.APR -100,1) END,
           CASE WHEN NVL(B.MAY,0)=0 THEN NULL ELSE ROUND(100 * A.MAY/B.MAY -100,1) END,
           CASE WHEN NVL(B.JUN,0)=0 THEN NULL ELSE ROUND(100 * A.JUN/B.JUN -100,1) END,
           CASE WHEN NVL(B.JUL,0)=0 THEN NULL ELSE ROUND(100 * A.JUL/B.JUL -100,1) END,
           CASE WHEN NVL(B.AUG,0)=0 THEN NULL ELSE ROUND(100 * A.AUG/B.AUG -100,1) END,
           CASE WHEN NVL(B.SEP,0)=0 THEN NULL ELSE ROUND(100 * A.SEP/B.SEP -100,1) END,
           CASE WHEN NVL(B.OCT,0)=0 THEN NULL ELSE ROUND(100 * A.OCT/B.OCT -100,1) END,
           CASE WHEN NVL(B.NOV,0)=0 THEN NULL ELSE ROUND(100 * A.NOV/B.NOV -100,1) END,
           CASE WHEN NVL(B.DEC,0)=0 THEN NULL ELSE ROUND(100 * A.DEC/B.DEC -100,1) END,
           CASE WHEN NVL(B.JAN_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.JAN_HZ/B.JAN_HZ -100,1) END,
           CASE WHEN NVL(B.FEB_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.FEB_HZ/B.FEB_HZ -100,1) END,
           CASE WHEN NVL(B.MAR_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.MAR_HZ/B.MAR_HZ -100,1) END,
           CASE WHEN NVL(B.APR_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.APR_HZ/B.APR_HZ -100,1) END,
           CASE WHEN NVL(B.MAY_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.MAY_HZ/B.MAY_HZ -100,1) END,
           CASE WHEN NVL(B.JUN_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.JUN_HZ/B.JUN_HZ -100,1) END,
           CASE WHEN NVL(B.JUL_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.JUL_HZ/B.JUL_HZ -100,1) END,
           CASE WHEN NVL(B.AUG_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.AUG_HZ/B.AUG_HZ -100,1) END,
           CASE WHEN NVL(B.SEP_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.SEP_HZ/B.SEP_HZ -100,1) END,
           CASE WHEN NVL(B.OCT_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.OCT_HZ/B.OCT_HZ -100,1) END,
           CASE WHEN NVL(B.NOV_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.NOV_HZ/B.NOV_HZ -100,1) END,
           CASE WHEN NVL(B.DEC_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.DEC_HZ/B.DEC_HZ -100,1) END
      FROM TJBB_DT_B03102 A,
           TJBB_DT_B03102 B
     WHERE A.SWJGDM=V_SWCODE
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='02'
       AND B.SWJGDM=V_SWCODE
       AND B.SSNY=LC_THISMONTH
       AND B.BBLC='05';
    COMMIT;
    
    --3、合计统计
    INSERT INTO TJBB_DT_B03102 (SSNY,BBLC,SWJGDM,
           JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,
           JAN_HZ,FEB_HZ,MAR_HZ,APR_HZ,MAY_HZ,JUN_HZ,JUL_HZ,AUG_HZ,SEP_HZ,OCT_HZ,NOV_HZ,DEC_HZ)
    SELECT LC_THISMONTH, '09', V_SWCODE,
           CASE WHEN NVL(B.JAN,0)=0 THEN NULL ELSE ROUND(100 * A.JAN/B.JAN -100,1) END,
           CASE WHEN NVL(B.FEB,0)=0 THEN NULL ELSE ROUND(100 * A.FEB/B.FEB -100,1) END,
           CASE WHEN NVL(B.MAR,0)=0 THEN NULL ELSE ROUND(100 * A.MAR/B.MAR -100,1) END,
           CASE WHEN NVL(B.APR,0)=0 THEN NULL ELSE ROUND(100 * A.APR/B.APR -100,1) END,
           CASE WHEN NVL(B.MAY,0)=0 THEN NULL ELSE ROUND(100 * A.MAY/B.MAY -100,1) END,
           CASE WHEN NVL(B.JUN,0)=0 THEN NULL ELSE ROUND(100 * A.JUN/B.JUN -100,1) END,
           CASE WHEN NVL(B.JUL,0)=0 THEN NULL ELSE ROUND(100 * A.JUL/B.JUL -100,1) END,
           CASE WHEN NVL(B.AUG,0)=0 THEN NULL ELSE ROUND(100 * A.AUG/B.AUG -100,1) END,
           CASE WHEN NVL(B.SEP,0)=0 THEN NULL ELSE ROUND(100 * A.SEP/B.SEP -100,1) END,
           CASE WHEN NVL(B.OCT,0)=0 THEN NULL ELSE ROUND(100 * A.OCT/B.OCT -100,1) END,
           CASE WHEN NVL(B.NOV,0)=0 THEN NULL ELSE ROUND(100 * A.NOV/B.NOV -100,1) END,
           CASE WHEN NVL(B.DEC,0)=0 THEN NULL ELSE ROUND(100 * A.DEC/B.DEC -100,1) END,
           CASE WHEN NVL(B.JAN_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.JAN_HZ/B.JAN_HZ -100,1) END,
           CASE WHEN NVL(B.FEB_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.FEB_HZ/B.FEB_HZ -100,1) END,
           CASE WHEN NVL(B.MAR_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.MAR_HZ/B.MAR_HZ -100,1) END,
           CASE WHEN NVL(B.APR_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.APR_HZ/B.APR_HZ -100,1) END,
           CASE WHEN NVL(B.MAY_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.MAY_HZ/B.MAY_HZ -100,1) END,
           CASE WHEN NVL(B.JUN_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.JUN_HZ/B.JUN_HZ -100,1) END,
           CASE WHEN NVL(B.JUL_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.JUL_HZ/B.JUL_HZ -100,1) END,
           CASE WHEN NVL(B.AUG_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.AUG_HZ/B.AUG_HZ -100,1) END,
           CASE WHEN NVL(B.SEP_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.SEP_HZ/B.SEP_HZ -100,1) END,
           CASE WHEN NVL(B.OCT_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.OCT_HZ/B.OCT_HZ -100,1) END,
           CASE WHEN NVL(B.NOV_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.NOV_HZ/B.NOV_HZ -100,1) END,
           CASE WHEN NVL(B.DEC_HZ,0)=0 THEN NULL ELSE ROUND(100 * A.DEC_HZ/B.DEC_HZ -100,1) END
      FROM TJBB_DT_B03102 A,
           TJBB_DT_B03102 B
     WHERE A.SWJGDM=V_SWCODE
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='03'
       AND B.SWJGDM=V_SWCODE
       AND B.SSNY=LC_THISMONTH
       AND B.BBLC='06';
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
