CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03114_HZ_NEW
/*************************************************
 * 对“一带一路”国家出口退（免）税情况统计表（省、市局汇总）
 * 表结构与浙江省分出口市场统计表一样，算法条件有变化
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LC_THISMONTH     VARCHAR2(6);--当月
  LC_THISYEAR      VARCHAR2(6);--当年首月
  LC_LASTMONTH     VARCHAR2(6);--上年同期
  LN_CKE_HJ        NUMBER(16,4);--出口额合计
  LN_TSE_HJ        NUMBER(16,4);--退税额合计
  LN_CKE_HJ_LAST   NUMBER(16,4);--出口额合计
  LN_TSE_HJ_LAST   NUMBER(16,4);--退税额合计

  V_TEMP           NUMBER(10, 0) := 0;
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LD_SYSDATE       DATE;
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;

  LC_THISMONTH   :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LC_THISYEAR    :=TO_CHAR(LD_SYSDATE,'YYYY')||'01';
  LC_LASTMONTH   :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYYMM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03114_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    DELETE FROM TJBB_DT_B03114 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、中间表数据计算
  BEGIN
    INSERT INTO TJBB_DT_B03114_MID (SWJGDM,SSNY,DMTYPE,GBDM,CKE_LJ,TSE_LJ,CKPM)
    SELECT V_SWCODE, LC_THISMONTH, B.DMTYPE, B.GBDM, SUM(B.CKE_LJ), SUM(B.TSE_LJ), ROW_NUMBER() OVER (PARTITION BY B.DMTYPE ORDER BY SUM(NVL(B.CKE_LJ,0)) DESC)
      FROM TJBB_DT_B03114_MID B 
     WHERE B.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))
       AND B.SSNY=LC_THISMONTH
     GROUP BY B.DMTYPE, B.GBDM;
    COMMIT;

    SELECT COUNT(1)
      INTO V_TEMP
      FROM TJBB_DT_B03114_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH AND DMTYPE='GJ';
    IF V_TEMP = 0 THEN
      BEGIN
        DELETE FROM TJBB_DT_B03114_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH;
        COMMIT;

        INSERT INTO TJBB_DT_B03114_MID (SWJGDM,SSNY,DMTYPE,GBDM,CKE_LJ,TSE_LJ,CKPM)
        SELECT V_SWCODE, LC_LASTMONTH, B.DMTYPE, B.GBDM, SUM(B.CKE_LJ), SUM(B.TSE_LJ), ROW_NUMBER() OVER (PARTITION BY B.DMTYPE ORDER BY SUM(NVL(B.CKE_LJ,0)) DESC)
          FROM TJBB_DT_B03114_MID B 
         WHERE B.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))
           AND B.SSNY=LC_LASTMONTH
         GROUP BY B.DMTYPE, B.GBDM;
        COMMIT;
      END;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --2、计算并插入区域情况及本年前10名明细及上年同期
  BEGIN
    INSERT INTO TJBB_DT_B03114 (SSNY,BBLC,SWJGDM,ITEM,CKE_USD,TMSE,CKE_USD_LAST,TMSE_LAST)
    SELECT LC_THISMONTH, '100', V_SWCODE, '区域情况', NULL, NULL, NULL, NULL
      FROM DUAL
     UNION ALL
    SELECT B.SSNY, CASE WHEN B.CKPM<10 THEN '10' ELSE '1' END || B.CKPM, B.SWJGDM, A.DQ_NAME, B.CKE_LJ, B.TSE_LJ, C.CKE_LJ, C.TSE_LJ
      FROM DM_DQCODE A
     INNER JOIN TJBB_DT_B03114_MID B ON A.DQ_CODE=B.GBDM AND B.SWJGDM=V_SWCODE AND B.SSNY=LC_THISMONTH AND B.DMTYPE='BR'
      LEFT JOIN TJBB_DT_B03114_MID C ON A.DQ_CODE=C.GBDM AND C.SWJGDM=V_SWCODE AND C.SSNY=LC_LASTMONTH AND C.DMTYPE='BR'
     WHERE A.DQ_TYPE='BR'
     UNION ALL
    SELECT LC_THISMONTH, '200', V_SWCODE, '10个主要国别情况', NULL, NULL, NULL, NULL
      FROM DUAL
     UNION ALL
    SELECT B.SSNY, CASE WHEN B.CKPM<10 THEN '20' ELSE '2' END || B.CKPM, B.SWJGDM, A.GB_NAME, B.CKE_LJ, B.TSE_LJ, C.CKE_LJ, C.TSE_LJ
      FROM DM_GBCODE A
     INNER JOIN TJBB_DT_B03114_MID B ON A.GB_CODE=B.GBDM AND B.SWJGDM=V_SWCODE AND B.SSNY=LC_THISMONTH AND B.DMTYPE='GJ'
      LEFT JOIN TJBB_DT_B03114_MID C ON A.GB_CODE=C.GBDM AND C.SWJGDM=V_SWCODE AND C.SSNY=LC_LASTMONTH AND C.DMTYPE='GJ'
     WHERE B.CKPM<=10;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --3、计算并插入合计数
  BEGIN
    SELECT SUM(CKE_LJ), SUM(TSE_LJ)
      INTO LN_CKE_HJ, LN_TSE_HJ
      FROM TJBB_DT_B03114_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH AND DMTYPE='GJ';

    SELECT SUM(CKE_LJ), SUM(TSE_LJ)
      INTO LN_CKE_HJ_LAST, LN_TSE_HJ_LAST
      FROM TJBB_DT_B03114_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH AND DMTYPE='GJ';

    INSERT INTO TJBB_DT_B03114 (SSNY,BBLC,SWJGDM,ITEM,CKE_USD,TMSE,CKE_USD_LAST,TMSE_LAST)
    SELECT LC_THISMONTH, '001', V_SWCODE, '“一带一路”沿线64国', LN_CKE_HJ, LN_TSE_HJ, LN_CKE_HJ_LAST, LN_TSE_HJ_LAST
      FROM DUAL;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  --4、同比计算
  BEGIN
    UPDATE TJBB_DT_B03114
       SET CKE_TB  = CASE WHEN NVL(CKE_USD_LAST,0)=0 THEN NULL ELSE ROUND(100 * CKE_USD / CKE_USD_LAST -100,1) END,
           TMSE_TB = CASE WHEN NVL(TMSE_LAST,0)=0    THEN NULL ELSE ROUND(100 * TMSE    / TMSE_LAST    -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --5、占比计算
  BEGIN
    UPDATE TJBB_DT_B03114 T
       SET CKE_ZB  = CASE WHEN NVL(LN_CKE_HJ,0)=0 THEN NULL ELSE ROUND(100 * CKE_USD / LN_CKE_HJ,1) END,
           TMSE_ZB = CASE WHEN NVL(LN_TSE_HJ,0)=0 THEN NULL ELSE ROUND(100 * TMSE / LN_TSE_HJ,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --6、汇总栏初始化
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03114 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03114' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
