CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03103_CSH_NEW
/*************************************************
 * 浙江省办理出口退（免）税情况统计表（全部重新统计）
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LC_THISMONTH     VARCHAR2(6);--当月

  LD_THISMONTH     DATE;
  LD_NEXTMONTH     DATE;
  LD_THISYEAR      DATE;

  LD_THISMONTH_PREV     DATE;
  LD_NEXTMONTH_PREV     DATE;
  LD_THISYEAR_PREV      DATE;

  LN_TS_THISMONTH  NUMBER(18,6);--本月退库数
  LN_MD_THISMONTH  NUMBER(18,6);--本月免抵数
  LN_TS_THISYEAR   NUMBER(18,6);--本年退库数
  LN_MD_THISYEAR   NUMBER(18,6);--本年免抵数
  LN_FN            NUMBER(18,6);--返纳数
  LN_TS_LASTMONTH  NUMBER(18,6);--上年同期月退库数
  LN_MD_LASTMONTH  NUMBER(18,6);--上年同期月免抵数
  LN_TS_LASTYEAR   NUMBER(18,6);--上年同期年退库数
  LN_MD_LASTYEAR   NUMBER(18,6);--上年同期年免抵数
  LN_MD_KTKZY      NUMBER(18,6);--剩余可调库资源
  LC_SWJGMC        VARCHAR2(40);
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_THISMONTH:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_THISMONTH:=TRUNC(SYSDATE,'MM');
  END IF;
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_THISMONTH,1),'MM');
  LD_THISYEAR  :=TRUNC(LD_THISMONTH,'YY');

  LD_THISMONTH_PREV := ADD_MONTHS(LD_THISMONTH,-12);
  LD_NEXTMONTH_PREV := ADD_MONTHS(LD_NEXTMONTH,-12);
  LD_THISYEAR_PREV  := ADD_MONTHS(LD_THISYEAR,-12);

  LC_THISMONTH :=TO_CHAR(LD_THISMONTH,'YYYYMM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03103 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、制表
  BEGIN
    --税务机关显示名
    SELECT DISPSX
      INTO LC_SWJGMC
      FROM DM_SWJG
     WHERE SWJG_DM=V_SWCODE;
    --本月返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,0),0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISMONTH AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;
    --本月退库数,免抵数
    SELECT NVL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0),0)
      INTO LN_TS_THISMONTH
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISMONTH AND T.XHRQ_TK<LD_NEXTMONTH;
    SELECT NVL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0),0) + LN_TS_THISMONTH - LN_FN
      INTO LN_TS_THISMONTH
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISMONTH AND T.XHRQ_XFS<LD_NEXTMONTH;
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,0)
      INTO LN_MD_THISMONTH
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISMONTH AND T.XHRQ_MD<LD_NEXTMONTH;
    --本年返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,0),0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;
    --本年退库数,免抵数
    SELECT NVL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0),0)
      INTO LN_TS_THISYEAR
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR AND T.XHRQ_TK<LD_NEXTMONTH;
    SELECT NVL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0),0) + LN_TS_THISYEAR - LN_FN
      INTO LN_TS_THISYEAR
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISYEAR AND T.XHRQ_XFS<LD_NEXTMONTH;
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,0)
      INTO LN_MD_THISYEAR
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR AND T.XHRQ_MD<LD_NEXTMONTH;
    --可调库资源
    SELECT NVL(SUM(T.FS_MDSE),0)
      INTO LN_MD_KTKZY
      FROM TL_TSSH.CKTS_LC_YWHZXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.FSRQ<LD_NEXTMONTH
       AND T.FS_MDSE>0
       AND NOT EXISTS (SELECT 1 FROM TL_TSSH.CKTS_LC_SEHZXX S WHERE S.YWHZBUUID=T.YWHZBUUID AND NVL(S.SEHZ_MDSE,0)+NVL(S.BYHZ_MDSE,0)>0);
    SELECT LN_MD_KTKZY + NVL(SUM(T.SEHZ_MDSE - (CASE WHEN T.XHRQ_MD<LD_NEXTMONTH THEN T.GKBL_MDSE ELSE 0 END)),0)
      INTO LN_MD_KTKZY
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR
       AND T.SEHZRQ<LD_NEXTMONTH;
    LN_MD_KTKZY:=ROUND(LN_MD_KTKZY/10000,0);

    --上年同期返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,0),0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISMONTH_PREV AND T.RKRQ<LD_NEXTMONTH_PREV
       AND T.YWHZBUUID IS NULL;
    --上年同期退库数,免抵数
    SELECT NVL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0),0)
      INTO LN_TS_LASTMONTH
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISMONTH_PREV AND T.XHRQ_TK<LD_NEXTMONTH_PREV;
    SELECT NVL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0),0) + LN_TS_LASTMONTH - LN_FN
      INTO LN_TS_LASTMONTH
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISMONTH_PREV AND T.XHRQ_XFS<LD_NEXTMONTH_PREV;
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,0)
      INTO LN_MD_LASTMONTH
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISMONTH_PREV AND T.XHRQ_MD<LD_NEXTMONTH_PREV;
    --上年同期返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,0),0)
      INTO LN_FN
      FROM FG_CKTSFN_HXZG T
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR_PREV AND T.RKRQ<LD_NEXTMONTH_PREV
       AND T.YWHZBUUID IS NULL;
    --上年同期累计退库数,免抵数
    SELECT NVL(ROUND(SUM(T.GKBL_ZZSTSE)/10000,0),0)
      INTO LN_TS_LASTYEAR
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR_PREV AND T.XHRQ_TK<LD_NEXTMONTH_PREV;
    SELECT NVL(ROUND(SUM(T.GKBL_XFSTSE)/10000,0),0) + LN_TS_LASTYEAR - LN_FN
      INTO LN_TS_LASTYEAR
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_XFS>=LD_THISYEAR_PREV AND T.XHRQ_XFS<LD_NEXTMONTH_PREV;
    SELECT ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,0)
      INTO LN_MD_LASTYEAR
      FROM TL_TSSH.CKTS_LC_SEHZXX T
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR_PREV AND T.XHRQ_MD<LD_NEXTMONTH_PREV;

    INSERT INTO TJBB_DT_B03103 (SSNY,BBLC,SWJGDM,AREA,
           TMSE_MON,TMSE_MON_LAST,TKE_MON,TKE_MON_LAST,TMSE_YEAR,TMSE_YEAR_LAST,TKE_YEAR,TKE_YEAR_LAST,KTKZY)
    SELECT LC_THISMONTH, SUBSTR(V_SWCODE, 4, 4)|| '0001', V_SWCODE, LC_SWJGMC,
           LN_TS_THISMONTH, LN_TS_LASTMONTH, LN_MD_THISMONTH, LN_MD_LASTMONTH,
           LN_TS_THISYEAR, LN_TS_LASTYEAR, LN_MD_THISYEAR, LN_MD_LASTYEAR, LN_MD_KTKZY
      FROM DUAL;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --2、同比计算
  BEGIN
    UPDATE TJBB_DT_B03103
       SET TMSE_MON_TB = CASE WHEN NVL(TMSE_MON_LAST,0)=0 THEN NULL ELSE ROUND(100 * TMSE_MON / TMSE_MON_LAST -100,1) END,
           TKE_MON_TB = CASE WHEN NVL(TKE_MON_LAST,0)=0 THEN NULL ELSE ROUND(100 * TKE_MON / TKE_MON_LAST -100,1) END,
           TMSE_YEAR_TB = CASE WHEN NVL(TMSE_YEAR_LAST,0)=0 THEN NULL ELSE ROUND(100 * TMSE_YEAR / TMSE_YEAR_LAST -100,1) END,
           TKE_YEAR_TB = CASE WHEN NVL(TKE_YEAR_LAST,0)=0 THEN NULL ELSE ROUND(100 * TKE_YEAR / TKE_YEAR_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --4、汇总栏初始化
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03103 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03103' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
