CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B02101_CSH_NEW
/*************************************************
 * 无纸化管理情况统计表
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
  LD_NEXTMONTH     DATE;

  LC_SWJGMC          VARCHAR2(100);
  TSFN_ALL           NUMBER(18,6);
  TSFN_WZH_YEAR      NUMBER(18,6);
  TSFN_WZH_MON       NUMBER(18,6);

  LN_BAHS_SC         NUMBER(10);
  LN_BAHS_SC_ADD     NUMBER(10);
  LN_BAHS_WM         NUMBER(10);
  LN_BAHS_WM_ADD     NUMBER(10);
  LN_SBHS_SC_MON     NUMBER(10);
  LN_SBHS_SC_YEAR    NUMBER(10);
  LN_SBHS_WM_MON     NUMBER(10);
  LN_SBHS_WM_YEAR    NUMBER(10);
  LN_QYHS_TMSE       NUMBER(10);
  LN_WZHSB_TMSE_MON  NUMBER(18,6);
  LN_WZHBL_TMSE_MON  NUMBER(18,6);
  LN_WZHSB_TMSE_YEAR NUMBER(18,6);
  LN_WZHBL_TMSE_YEAR NUMBER(18,6);
  LN_SB_TMSE_HJ      NUMBER(18,6);
  LN_BL_TMSE_HJ      NUMBER(18,6);
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_SYSDATE,1),'MM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02101 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、计算列
  BEGIN
    --税务机关名称
    SELECT SWJG_JC
      INTO LC_SWJGMC
      FROM DM_SWJG
     WHERE SWJG_DM=V_SWCODE;
    --返纳
    SELECT NVL(ROUND(SUM(T.SJJE)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN S.WZHQY='1' THEN T.SJJE ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN S.WZHQY='1' AND TO_CHAR(T.RKRQ,'YYYYMM')=LC_THISMONTH THEN T.SJJE ELSE 0 END)/10000,6),0)
      INTO TSFN_ALL, TSFN_WZH_YEAR, TSFN_WZH_MON
      FROM FG_CKTSFN_HXZG T
      LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX S ON T.CPCODE=S.CPCODE
     WHERE T.SKSSSWJG_DM=V_SWCODE
       AND T.RKRQ>=LD_THISYEAR AND T.RKRQ<LD_NEXTMONTH
       AND T.YWHZBUUID IS NULL;
    --备案户数统计
    SELECT SUM(CASE WHEN T.WZHQY='1' AND T.JSMODE='1' THEN 1 ELSE 0 END),
           SUM(CASE WHEN T.WZHQY='1' AND T.JSMODE='1' AND T.SQ_DATE>=LD_THISYEAR THEN 1 ELSE 0 END),
           SUM(CASE WHEN T.WZHQY='1' AND T.JSMODE='2' THEN 1 ELSE 0 END),
           SUM(CASE WHEN T.WZHQY='1' AND T.JSMODE='2' AND T.SQ_DATE>=LD_THISYEAR THEN 1 ELSE 0 END)
      INTO LN_BAHS_SC, LN_BAHS_SC_ADD, LN_BAHS_WM, LN_BAHS_WM_ADD
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.SWJGDM=V_SWCODE
       AND T.ZX_FLAG='N';
    --申报户数、退免税额统计
    SELECT COUNT(DISTINCT CASE WHEN S.WZHQY='1' AND S.JSMODE='1' AND T.LCJSRQ>LD_SYSDATE THEN T.DJXH ELSE NULL END), 
           COUNT(DISTINCT CASE WHEN S.WZHQY='1' AND S.JSMODE='1' THEN T.DJXH ELSE NULL END), 
           COUNT(DISTINCT CASE WHEN S.WZHQY='1' AND S.JSMODE='2' AND T.LCJSRQ>LD_SYSDATE THEN T.DJXH ELSE NULL END), 
           COUNT(DISTINCT CASE WHEN S.WZHQY='1' AND S.JSMODE='2' THEN T.DJXH ELSE NULL END), 
           COUNT(DISTINCT T.DJXH),
           ROUND(NVL(SUM(CASE WHEN S.WZHQY='1' AND T.LCJSRQ>LD_SYSDATE THEN T.SB_MDTSE ELSE 0 END),0)/10000,6),
           ROUND(NVL(SUM(CASE WHEN S.WZHQY='1' THEN T.SB_MDTSE ELSE 0 END),0)/10000,6),
           ROUND(NVL(SUM(T.SB_MDTSE),0)/10000,6)
      INTO LN_SBHS_SC_MON, LN_SBHS_SC_YEAR, LN_SBHS_WM_MON, LN_SBHS_WM_YEAR, LN_QYHS_TMSE, LN_WZHSB_TMSE_MON, LN_WZHSB_TMSE_YEAR, LN_SB_TMSE_HJ
      FROM TL_TSSH.CKTS_LC_SHXX T
      LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX S ON T.DJXH=S.DJXH_JS
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.QDSJ<LD_NEXTMONTH
       AND T.LCJSRQ>=LD_THISYEAR;
    --办理退税额
    SELECT ROUND(NVL(SUM(CASE WHEN S.WZHQY='1' AND T.XHRQ_TK>LD_SYSDATE THEN T.GKBL_ZZSTSE+T.GKBL_XFSTSE ELSE 0 END),0)/10000,6),
           ROUND(NVL(SUM(CASE WHEN S.WZHQY='1' THEN T.GKBL_ZZSTSE+T.GKBL_XFSTSE ELSE 0 END),0)/10000,6),
           ROUND(NVL(SUM(T.GKBL_ZZSTSE+T.GKBL_XFSTSE),0)/10000,6)
      INTO LN_WZHBL_TMSE_MON, LN_WZHBL_TMSE_YEAR, LN_BL_TMSE_HJ
      FROM TL_TSSH.CKTS_LC_SEHZXX T
      LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX S ON T.DJXH=S.DJXH_JS
     WHERE T.CKTMSJHSSSWJGDM=V_SWCODE
       AND T.XHRQ_TK>=LD_THISYEAR
       AND T.XHRQ_TK<LD_NEXTMONTH;
    SELECT LN_WZHBL_TMSE_MON + ROUND(NVL(SUM(CASE WHEN S.WZHQY='1' AND T.XHRQ_MD>LD_SYSDATE THEN T.GKBL_MDSE ELSE 0 END),0)/10000,6),
           LN_WZHBL_TMSE_YEAR + ROUND(NVL(SUM(CASE WHEN S.WZHQY='1' THEN T.GKBL_MDSE ELSE 0 END),0)/10000,6),
           LN_BL_TMSE_HJ + ROUND(NVL(SUM(T.GKBL_MDSE),0)/10000,6)
      INTO LN_WZHBL_TMSE_MON, LN_WZHBL_TMSE_YEAR, LN_BL_TMSE_HJ
      FROM TL_TSSH.CKTS_LC_SEHZXX T
      LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX S ON T.DJXH=S.DJXH_JS
     WHERE T.MDTKSSSWJGDM=V_SWCODE
       AND T.XHRQ_MD>=LD_THISYEAR
       AND T.XHRQ_MD<LD_NEXTMONTH;

    INSERT INTO TJBB_DT_B02101 (SSNY, BBLC, SWJGDM, SDDWDM, SDSW, SDSJ,
           BAHS_SC, BAHS_SC_ADD, BAHS_WM, BAHS_WM_ADD, BAHS_HJ, BAHS_HJ_ADD,
           SBHS_SC_MON, SBHS_SC_YEAR, SBHS_WM_MON, SBHS_WM_YEAR, SBHS_HJ_MON, SBHS_HJ_YEAR,
           QYHS_TMSE,
           WZHSB_TMSE_MON, WZHSB_TMSE_YEAR, SB_TMSE_HJ,
           WZHBL_TMSE_MON, WZHBL_TMSE_YEAR, BL_TMSE_HJ)
    SELECT LC_THISMONTH, '0001' AS BBLC, V_SWCODE AS SWJGDM, V_SWCODE AS SDDWDM, LC_SWJGMC AS SDSW,
           CASE WHEN V_SWCODE IN ('13300000000','13304830000','13305010000','13306030000') THEN '2015年5月1日'
                WHEN V_SWCODE =  '13304000000' THEN '2015年8月1日（其中，桐乡县从2015年5月1日起试点）'
                WHEN V_SWCODE =  '13305000000' THEN '2015年8月1日（其中，湖州市本级从2015年5月1日起试点）'
                WHEN V_SWCODE =  '13306000000' THEN '2015年8月1日（其中，柯桥区从2015年5月1日起试点）'
                WHEN SUBSTR(V_SWCODE,0,5) <= '13301' THEN '2015年11月1日'
                ELSE '2015年8月1日' END AS SDSJ,
           LN_BAHS_SC, LN_BAHS_SC_ADD, LN_BAHS_WM, LN_BAHS_WM_ADD, LN_BAHS_SC+LN_BAHS_WM, LN_BAHS_SC_ADD+LN_BAHS_WM_ADD,
           LN_SBHS_SC_MON, LN_SBHS_SC_YEAR, LN_SBHS_WM_MON, LN_SBHS_WM_YEAR, LN_SBHS_SC_MON+LN_SBHS_WM_MON, LN_SBHS_SC_YEAR+LN_SBHS_WM_YEAR,
           LN_QYHS_TMSE,
           LN_WZHSB_TMSE_MON, LN_WZHSB_TMSE_YEAR, LN_SB_TMSE_HJ,
           LN_WZHBL_TMSE_MON - TSFN_WZH_MON, LN_WZHBL_TMSE_YEAR - TSFN_WZH_YEAR, LN_BL_TMSE_HJ - TSFN_ALL
      FROM DUAL;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --2、更新汇总列
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B02101 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02101' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
