CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03117_CSH_NEW
/*************************************************
 * 启运港政策出口退税情况表
 * 202504，根据省局关注点全新设计，分出口电子信息（其中剔除市场采购）、申报、办理
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
  LD_NEXTMONTH     DATE;
  LC_SQL           VARCHAR2(4000);
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LN_CK_HS         NUMBER(10);
  LN_CK_MY         NUMBER(18,6);
  LN_CK_RMB        NUMBER(18,6);
  LN_CK_HS_F1039   NUMBER(10);
  LN_CK_MY_F1039   NUMBER(18,6);
  LN_CK_RMB_F1039  NUMBER(18,6);
  LN_SB_HS         NUMBER(10);
  LN_SB_MY         NUMBER(18,6);
  LN_SB_JSJE       NUMBER(18,6);
  LN_SB_TMSE       NUMBER(18,6);
  LN_BL_HS         NUMBER(10);
  LN_BL_MY         NUMBER(18,6);
  LN_BL_JSJE       NUMBER(18,6);
  LN_BL_TMSE       NUMBER(18,6);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_SYSDATE,1),'MM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03117 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、当月总数
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0),
           COUNT(DISTINCT CASE WHEN BGD.JGFS_DM='1039' THEN NULL ELSE BGD.DJXH END),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.MYLAJ END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.RMBLAJ END)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB, LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.QYGBZ = 'Y'
       AND BGD.CKRQ_1>=LD_SYSDATE AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND MDT.SBRQ>=LD_SYSDATE AND MDT.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND MTS.SBRQ>=LD_SYSDATE AND MTS.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND WZF.SBRQ>=LD_SYSDATE AND WZF.SBRQ<LD_NEXTMONTH) T;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND MDT.FSRQ>=LD_SYSDATE AND MDT.FSRQ<LD_NEXTMONTH
               AND NVL(MDT.BYBLBZ,'N')='N' AND NVL(MDT.BYTSBZ,'N')='N' AND MDT.SJLY='2'
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND MTS.FSRQ>=LD_SYSDATE AND MTS.FSRQ<LD_NEXTMONTH
               AND NVL(MTS.BYBLBZ,'N')='N' AND NVL(MTS.BYTSBZ,'N')='N' AND MTS.SJLY='2'
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND WZF.FSRQ>=LD_SYSDATE AND WZF.FSRQ<LD_NEXTMONTH
               AND NVL(WZF.BYBLBZ,'N')='N' AND NVL(WZF.BYTSBZ,'N')='N' AND WZF.SJLY='2') T;
    
    INSERT INTO TJBB_DT_B03117 (SSNY, BBLC, SWJGDM,
                CK_HS, CK_MYLAJ, CK_RMBLAJ,
                CK_F1039_HS, CK_F1039_MYLAJ, CK_F1039_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE)
         SELECT LC_THISMONTH, '01', V_SWCODE,
                LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
           FROM DUAL;
    COMMIT;
  END;
  
  --2、当月陆路启运港
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0),
           COUNT(DISTINCT CASE WHEN BGD.JGFS_DM='1039' THEN NULL ELSE BGD.DJXH END),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.MYLAJ END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.RMBLAJ END)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB, LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.QYGBZ = 'Y'
       AND REGEXP_LIKE(BGD.CKBGDH,'^2920|^2921') --金华义乌港
       AND BGD.CKRQ_1>=LD_SYSDATE AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MDT.CKBGDH,'^2920|^2921') --金华义乌港
               AND MDT.SBRQ>=LD_SYSDATE AND MDT.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MTS.CKBGDH,'^2920|^2921') --金华义乌港
               AND MTS.SBRQ>=LD_SYSDATE AND MTS.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(WZF.CKBGDH,'^2920|^2921') --金华义乌港
               AND WZF.SBRQ>=LD_SYSDATE AND WZF.SBRQ<LD_NEXTMONTH) T;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MDT.CKBGDH,'^2920|^2921') --金华义乌港
               AND MDT.FSRQ>=LD_SYSDATE AND MDT.FSRQ<LD_NEXTMONTH
               AND NVL(MDT.BYBLBZ,'N')='N' AND NVL(MDT.BYTSBZ,'N')='N' AND MDT.SJLY='2'
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MTS.CKBGDH,'^2920|^2921') --金华义乌港
               AND MTS.FSRQ>=LD_SYSDATE AND MTS.FSRQ<LD_NEXTMONTH
               AND NVL(MTS.BYBLBZ,'N')='N' AND NVL(MTS.BYTSBZ,'N')='N' AND MTS.SJLY='2'
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(WZF.CKBGDH,'^2920|^2921') --金华义乌港
               AND WZF.FSRQ>=LD_SYSDATE AND WZF.FSRQ<LD_NEXTMONTH
               AND NVL(WZF.BYBLBZ,'N')='N' AND NVL(WZF.BYTSBZ,'N')='N' AND WZF.SJLY='2') T;
    
    INSERT INTO TJBB_DT_B03117 (SSNY, BBLC, SWJGDM,
                CK_HS, CK_MYLAJ, CK_RMBLAJ,
                CK_F1039_HS, CK_F1039_MYLAJ, CK_F1039_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE)
         SELECT LC_THISMONTH, '02', V_SWCODE,
                LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
           FROM DUAL;
    COMMIT;
  END;
  
  --3、当月海运启运港
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0),
           COUNT(DISTINCT CASE WHEN BGD.JGFS_DM='1039' THEN NULL ELSE BGD.DJXH END),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.MYLAJ END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.RMBLAJ END)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB, LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.QYGBZ = 'Y'
       AND REGEXP_LIKE(BGD.HGGQKA_DM,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
       AND BGD.CKRQ_1>=LD_SYSDATE AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MDT.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND MDT.SBRQ>=LD_SYSDATE AND MDT.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MTS.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND MTS.SBRQ>=LD_SYSDATE AND MTS.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(WZF.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND WZF.SBRQ>=LD_SYSDATE AND WZF.SBRQ<LD_NEXTMONTH) T;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MDT.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND MDT.FSRQ>=LD_SYSDATE AND MDT.FSRQ<LD_NEXTMONTH
               AND NVL(MDT.BYBLBZ,'N')='N' AND NVL(MDT.BYTSBZ,'N')='N' AND MDT.SJLY='2'
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MTS.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND MTS.FSRQ>=LD_SYSDATE AND MTS.FSRQ<LD_NEXTMONTH
               AND NVL(MTS.BYBLBZ,'N')='N' AND NVL(MTS.BYTSBZ,'N')='N' AND MTS.SJLY='2'
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(WZF.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND WZF.FSRQ>=LD_SYSDATE AND WZF.FSRQ<LD_NEXTMONTH
               AND NVL(WZF.BYBLBZ,'N')='N' AND NVL(WZF.BYTSBZ,'N')='N' AND WZF.SJLY='2') T;
    
    INSERT INTO TJBB_DT_B03117 (SSNY, BBLC, SWJGDM,
                CK_HS, CK_MYLAJ, CK_RMBLAJ,
                CK_F1039_HS, CK_F1039_MYLAJ, CK_F1039_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE)
         SELECT LC_THISMONTH, '03', V_SWCODE,
                LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
           FROM DUAL;
    COMMIT;
  END;

  --4、陆路海运小计

  --5、当年总数
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0),
           COUNT(DISTINCT CASE WHEN BGD.JGFS_DM='1039' THEN NULL ELSE BGD.DJXH END),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.MYLAJ END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.RMBLAJ END)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB, LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.QYGBZ = 'Y'
       AND BGD.CKRQ_1>=LD_THISYEAR AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND MDT.SBRQ>=LD_THISYEAR AND MDT.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND MTS.SBRQ>=LD_THISYEAR AND MTS.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND WZF.SBRQ>=LD_THISYEAR AND WZF.SBRQ<LD_NEXTMONTH) T;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND MDT.FSRQ>=LD_THISYEAR AND MDT.FSRQ<LD_NEXTMONTH
               AND NVL(MDT.BYBLBZ,'N')='N' AND NVL(MDT.BYTSBZ,'N')='N' AND MDT.SJLY='2'
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND MTS.FSRQ>=LD_THISYEAR AND MTS.FSRQ<LD_NEXTMONTH
               AND NVL(MTS.BYBLBZ,'N')='N' AND NVL(MTS.BYTSBZ,'N')='N' AND MTS.SJLY='2'
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND WZF.FSRQ>=LD_THISYEAR AND WZF.FSRQ<LD_NEXTMONTH
               AND NVL(WZF.BYBLBZ,'N')='N' AND NVL(WZF.BYTSBZ,'N')='N' AND WZF.SJLY='2') T;
    
    INSERT INTO TJBB_DT_B03117 (SSNY, BBLC, SWJGDM,
                CK_HS, CK_MYLAJ, CK_RMBLAJ,
                CK_F1039_HS, CK_F1039_MYLAJ, CK_F1039_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE)
         SELECT LC_THISMONTH, '05', V_SWCODE,
                LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
           FROM DUAL;
    COMMIT;
  END;
  
  --6、当年陆路启运港
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0),
           COUNT(DISTINCT CASE WHEN BGD.JGFS_DM='1039' THEN NULL ELSE BGD.DJXH END),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.MYLAJ END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.RMBLAJ END)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB, LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.QYGBZ = 'Y'
       AND REGEXP_LIKE(BGD.CKBGDH,'^2920|^2921') --金华义乌港
       AND BGD.CKRQ_1>=LD_THISYEAR AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MDT.CKBGDH,'^2920|^2921') --金华义乌港
               AND MDT.SBRQ>=LD_THISYEAR AND MDT.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MTS.CKBGDH,'^2920|^2921') --金华义乌港
               AND MTS.SBRQ>=LD_THISYEAR AND MTS.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(WZF.CKBGDH,'^2920|^2921') --金华义乌港
               AND WZF.SBRQ>=LD_THISYEAR AND WZF.SBRQ<LD_NEXTMONTH) T;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MDT.CKBGDH,'^2920|^2921') --金华义乌港
               AND MDT.FSRQ>=LD_THISYEAR AND MDT.FSRQ<LD_NEXTMONTH
               AND NVL(MDT.BYBLBZ,'N')='N' AND NVL(MDT.BYTSBZ,'N')='N' AND MDT.SJLY='2'
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MTS.CKBGDH,'^2920|^2921') --金华义乌港
               AND MTS.FSRQ>=LD_THISYEAR AND MTS.FSRQ<LD_NEXTMONTH
               AND NVL(MTS.BYBLBZ,'N')='N' AND NVL(MTS.BYTSBZ,'N')='N' AND MTS.SJLY='2'
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(WZF.CKBGDH,'^2920|^2921') --金华义乌港
               AND WZF.FSRQ>=LD_THISYEAR AND WZF.FSRQ<LD_NEXTMONTH
               AND NVL(WZF.BYBLBZ,'N')='N' AND NVL(WZF.BYTSBZ,'N')='N' AND WZF.SJLY='2') T;
    
    INSERT INTO TJBB_DT_B03117 (SSNY, BBLC, SWJGDM,
                CK_HS, CK_MYLAJ, CK_RMBLAJ,
                CK_F1039_HS, CK_F1039_MYLAJ, CK_F1039_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE)
         SELECT LC_THISMONTH, '06', V_SWCODE,
                LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
           FROM DUAL;
    COMMIT;
  END;
  
  --7、当年海运启运港
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0),
           COUNT(DISTINCT CASE WHEN BGD.JGFS_DM='1039' THEN NULL ELSE BGD.DJXH END),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.MYLAJ END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN BGD.JGFS_DM='1039' THEN 0 ELSE BGD.RMBLAJ END)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB, LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.QYGBZ = 'Y'
       AND REGEXP_LIKE(BGD.HGGQKA_DM,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
       AND BGD.CKRQ_1>=LD_THISYEAR AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MDT.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND MDT.SBRQ>=LD_THISYEAR AND MDT.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MTS.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND MTS.SBRQ>=LD_THISYEAR AND MTS.SBRQ<LD_NEXTMONTH
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(WZF.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND WZF.SBRQ>=LD_THISYEAR AND WZF.SBRQ<LD_NEXTMONTH) T;
    
    SELECT COUNT(DISTINCT DJXH), NVL(ROUND(SUM(MYLAJ)/10000,6),0), NVL(ROUND(SUM(JSJE)/10000,6),0), NVL(ROUND(SUM(TMSE)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
      FROM (SELECT MDT.DJXH, MDT.MYLAJ, MDT.RMBLAJ AS JSJE, MDT.MDTSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
             WHERE MDT.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MDT.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND MDT.FSRQ>=LD_THISYEAR AND MDT.FSRQ<LD_NEXTMONTH
               AND NVL(MDT.BYBLBZ,'N')='N' AND NVL(MDT.BYTSBZ,'N')='N' AND MDT.SJLY='2'
             UNION ALL
            SELECT MTS.DJXH, MTS.MYLAJ, MTS.JSJE, MTS.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
             WHERE MTS.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(MTS.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND MTS.FSRQ>=LD_THISYEAR AND MTS.FSRQ<LD_NEXTMONTH
               AND NVL(MTS.BYBLBZ,'N')='N' AND NVL(MTS.BYTSBZ,'N')='N' AND MTS.SJLY='2'
             UNION ALL
            SELECT WZF.DJXH, WZF.MYLAJ, WZF.JSJE, WZF.TSE AS TMSE
              FROM TL_TSSH.CKTS_SB_WZF_CKMX WZF
             WHERE WZF.TSSWJG_DM=V_SWCODE
               AND REGEXP_LIKE(WZF.CKTMSYWLXDMJH ,'^QYGTS')
               AND REGEXP_LIKE(WZF.HGCODE,'^2904|^2941|^2942|^2943|^31') --宁波舟山港
               AND WZF.FSRQ>=LD_THISYEAR AND WZF.FSRQ<LD_NEXTMONTH
               AND NVL(WZF.BYBLBZ,'N')='N' AND NVL(WZF.BYTSBZ,'N')='N' AND WZF.SJLY='2') T;
    
    INSERT INTO TJBB_DT_B03117 (SSNY, BBLC, SWJGDM,
                CK_HS, CK_MYLAJ, CK_RMBLAJ,
                CK_F1039_HS, CK_F1039_MYLAJ, CK_F1039_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE)
         SELECT LC_THISMONTH, '07', V_SWCODE,
                LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_CK_HS_F1039, LN_CK_MY_F1039, LN_CK_RMB_F1039,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE
           FROM DUAL;
    COMMIT;
  END;

  --8、陆路海运小计
  
  --10、小计行计算
  BEGIN
    FOR LSF_XX IN (SELECT TRIM(TO_CHAR(SUBSTR(T.FORMULA,2,INSTR(T.FORMULA,')')-2),'00')) AS BBLC,
                          '('||REPLACE(REPLACE(REPLACE(SUBSTR(T.FORMULA,INSTR(T.FORMULA,'=')+1),'(',''''),'+',','),')','''')||')' AS BBCS
                     FROM TJBB_REPORT_FORMULA T 
                    WHERE T.BBDM='B03117' 
                      AND T.TYPE=2
                    ORDER BY T.YXJ) 
    LOOP
      BEGIN
        LC_SQL := 'INSERT INTO TJBB_DT_B03117 (SSNY, BBLC, SWJGDM,
                          CK_HS, CK_MYLAJ, CK_RMBLAJ,
                          CK_F1039_HS, CK_F1039_MYLAJ, CK_F1039_RMBLAJ,
                          SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE,
                          BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE)
                   SELECT '''||LC_THISMONTH||''', '''||LSF_XX.BBLC||''', '''||V_SWCODE||''', 
                          SUM(CK_HS),       SUM(CK_MYLAJ),       SUM(CK_RMBLAJ),
                          SUM(CK_F1039_HS), SUM(CK_F1039_MYLAJ), SUM(CK_F1039_RMBLAJ),
                          SUM(SB_HS),       SUM(SB_MYXSE),       SUM(SB_JSJE),         SUM(SB_TMSE),
                          SUM(BL_HS),       SUM(BL_MYXSE),       SUM(BL_JSJE),         SUM(BL_TMSE)
                     FROM TJBB_DT_B03117
                    WHERE SWJGDM='''||V_SWCODE||'''
                      AND SSNY='''||LC_THISMONTH||'''
                      AND TRIM(TO_CHAR(TO_NUMBER(BBLC))) IN '||LSF_XX.BBCS;
        
        EXECUTE IMMEDIATE LC_SQL;
        COMMIT;
      END;
    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --11、更新汇总列
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03117 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03117' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
