CREATE OR REPLACE PROCEDURE PRO_TJBB_CHECK_DTBB
/****************************************************
 * 报表上报前的表间逻辑关系检查
 ***************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY    IN  VARCHAR2,
  V_BBDLDM  IN  VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LC_PREVMONTH     VARCHAR2(6);

  LN_AMT_TARGET    NUMBER(16,4);
  LN_AMT_REFER     NUMBER(16,4);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;
  LC_THISMONTH   :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LC_PREVMONTH   :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-1),'YYYYMM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_SB_JYXX WHERE SWJGDM=V_SWCODE AND BBDLDM=V_BBDLDM;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  IF V_BBDLDM='B01' THEN
    BEGIN
      SELECT T.ZH_TMSE_XJ
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT T.HJ_TSE
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01101 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,暂缓办理退（免）税额小计应与附表《暂缓退（免）税统计月报表》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT T.BY_TMSE_XJ
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT T.HJ_TSE
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01102 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,不予办理退（免）税额小计应与附表《不予办理退（免）税统计月报表》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;

      SELECT T.RDHS
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT T.RDHS
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01108 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>0 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,备案户数应与《出口退（免）税情况分析月报表（本月情况）》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      SELECT T.RDHS
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01109 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>0 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,备案户数应与《出口退（免）税情况分析月报表（累计情况）》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT T.SBHS
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT T.SBHS
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01109 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>0 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,申报户数应与《出口退（免）税情况分析月报表（累计情况）》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT T.SB_CKE_XJ
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT T.SB_CKE_XJ
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01109 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,申报退税出口额应与《出口退（免）税情况分析月报表（累计情况）》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT T.SB_TMSE_XJ
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT T.SB_TMSE_XJ
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01109 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,申报退（免）税额应与《出口退（免）税情况分析月报表（累计情况）》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT T.SH_TMSE_XJ
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT T.SH_TMSE_XJ
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01109 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,审核通过应退（免）税额应与《出口退（免）税情况分析月报表（累计情况）》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT T.SP_TK_XJ
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT T.SP_TMSE_XJ
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01109 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,审批应退（免）税额应与《出口退（免）税情况分析月报表（累计情况）》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT T.BL_TK_XJ
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT T.TK_XJ
        INTO LN_AMT_REFER
        FROM TJBB_DT_B01109 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,国库已办理退（调）库额应与《出口退（免）税情况分析月报表（累计情况）》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;

      BEGIN
        SELECT NVL(T.BL_TK_XJ,0)
          INTO LN_AMT_REFER
          FROM TJBB_DT_B01100 T
         WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_PREVMONTH AND T.BBLC='01';
      EXCEPTION
        WHEN OTHERS THEN
          LN_AMT_REFER:=0;
      END;
      IF SUBSTR(LC_THISMONTH,5,2)<>'01' AND LN_AMT_TARGET<LN_AMT_REFER THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','2','2','出口退（免）税情况分析月报表（主表）,国库已办理退（调）库额小计，本月累计数不应小于上月累计数（年初除外）'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT COUNT(1)
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T 
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01'
         AND ABS(T.SB_TMSE_XJ-T.SH_TMSE_XJ-T.ZH_TMSE_XJ-T.BY_TMSE_XJ-T.ZT_TMSE_XJ)>2;
      IF LN_AMT_TARGET=1 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','2','2','出口退（免）税情况分析月报表（主表）,申报受理退（免）税额小计应于审核情况的退（免）税额小计之和一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT T.ZT_TMSE_XJ, T.ZT_TK
        INTO LN_AMT_TARGET, LN_AMT_REFER
        FROM TJBB_DT_B01100 T 
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF LN_AMT_TARGET<-2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','2','2','出口退（免）税情况分析月报表（主表）,审核在途数小计小于0，请确认'
               FROM DUAL;
        COMMIT;
      END IF;
      IF LN_AMT_REFER<-2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','2','2','出口退（免）税情况分析月报表（主表）,退（调）库在途数小计小于0，请确认'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT T.JE
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01105 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      IF LN_AMT_TARGET>10000 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01105','2','2','出口退税返还情况月报表，返还金额大于1亿，请确认'
               FROM DUAL;
        COMMIT;
      END IF;
    END;
  END IF;
    
  IF V_BBDLDM IN ('B01','B02') THEN
    BEGIN
      SELECT NVL(T.BL_TK_XJ,0)
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='01';
      SELECT NVL(T.BL_TMSE_HJ,0)
        INTO LN_AMT_REFER
        FROM TJBB_DT_B02101 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='0001';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,国库已办理退（调）库额应与《无纸化统计表》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT NVL(T.RDHS,0)
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='07';
      SELECT COUNT(1)
        INTO LN_AMT_REFER
        FROM TJBB_DT_B02107 T
       WHERE (T.SWJGDM=V_SWCODE OR T.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))) AND T.SSNY=LC_THISMONTH;
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>0 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,外综服企业备案户数应与《外贸综合服务企业基本信息表》外综服企业户数一致'
               FROM DUAL;
        COMMIT;
      END IF;

      SELECT NVL(T.SBHS,0)
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='07';
      SELECT COUNT(1)
        INTO LN_AMT_REFER
        FROM TJBB_DT_B02108 T
       WHERE (T.SWJGDM=V_SWCODE OR T.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))) AND T.SSNY=LC_THISMONTH
         AND T.SB_CKE_YEAR<>0;
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>0 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,外综服企业申报户数应与《外贸综合服务企业退税情况统计表》外综服企业本年有申报户数一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT NVL(T.BL_TK_XJ,0)
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='07';
      SELECT NVL(SUM(T.BL_TKE_YEAR),0)
        INTO LN_AMT_REFER
        FROM TJBB_DT_B02108 T
       WHERE (T.SWJGDM=V_SWCODE OR T.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))) AND T.SSNY=LC_THISMONTH;
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,外综服企业国库已办理退（调）库额应与《外贸综合服务企业退税情况统计表》外综服企业国库已办理退（调）库额一致'
               FROM DUAL;
        COMMIT;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','总局出口退（免）税月报表 或 总局专项报表 未制表，无法比较勾稽关系！'
               FROM DUAL;
        COMMIT;
    END;
  END IF;
/*  
  IF V_BBDLDM IN ('B01','B03') THEN
    BEGIN
      SELECT NVL(T.BL_TK_XJ,0)
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='02';
      SELECT NVL(T.TMSE_YEAR,0)
        INTO LN_AMT_REFER
        FROM TJBB_DT_B03103 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC=SUBSTR(V_SWCODE, 4, 4)|| '0001';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,国库已办理退库额应与《浙江省办理出口退（免）税情况统计表》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT NVL(T.BL_TK_XJ,0)
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01100 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='03';
      SELECT NVL(T.TKE_YEAR,0)
        INTO LN_AMT_REFER
        FROM TJBB_DT_B03103 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC=SUBSTR(V_SWCODE, 4, 4)|| '0001';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（主表）,国库已办理调库额应与《浙江省办理出口退（免）税情况统计表》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT NVL(T.TK_XJ,0)
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01108 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='02';
      SELECT NVL(T.TMSE_MON,0)
        INTO LN_AMT_REFER
        FROM TJBB_DT_B03103 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC=SUBSTR(V_SWCODE, 4, 4)|| '0001';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（本月情况）,本月办理退库额应与《浙江省办理出口退（免）税情况统计表》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
      
      SELECT NVL(T.TK_XJ,0)
        INTO LN_AMT_TARGET
        FROM TJBB_DT_B01108 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC='03';
      SELECT NVL(T.TKE_MON,0)
        INTO LN_AMT_REFER
        FROM TJBB_DT_B03103 T
       WHERE T.SWJGDM=V_SWCODE AND T.SSNY=LC_THISMONTH AND T.BBLC=SUBSTR(V_SWCODE, 4, 4)|| '0001';
      IF ROUND(ABS(LN_AMT_TARGET - LN_AMT_REFER),0)>2 THEN
        INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
             SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B01100','1','2','出口退（免）税情况分析月报表（本月情况）,本月办理调库额应与《浙江省办理出口退（免）税情况统计表》对应栏一致'
               FROM DUAL;
        COMMIT;
      END IF;
    END;
  END IF;
*/  
  IF V_BBDLDM='B02' THEN
    BEGIN
      INSERT INTO TJBB_SB_JYXX(ID,SWJGDM,SSNY,BBDLDM,BBDM,MSG_TYPE,MSG_LEVEL,MSG)
           SELECT SEQ_TJBB_SB_JYXX.NEXTVAL,V_SWCODE,LC_THISMONTH,V_BBDLDM,'B02106','2','2','《外贸综合服务企业退税情况统计表》，申报受理的退税额应与审核退税额（审核通过+暂缓+不予+在途）一致'
             FROM DUAL
            WHERE EXISTS (SELECT 1
                            FROM TJBB_DT_B02106 
                           WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH AND ABS(TSE-SHTG_TSE-ZHBL_TSE-BYBL_TSE-SHZT_TSE)>1);
      COMMIT;
    END;
  END IF;

  RETURN;
END;
/
