CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03113_HZ_NEW
/*************************************************
 * 浙江省对美主要出口企业情况表（省、市局汇总）
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LC_THISMONTH     VARCHAR2(6);--当月
  LC_THISYEAR      VARCHAR2(6);--当年首月
  LC_LASTMONTH     VARCHAR2(6);--上年同期
  LC_LASTYEAR      VARCHAR2(6);--上年首月
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LD_SYSDATE       DATE;
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;

  LC_THISMONTH   :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LC_THISYEAR    :=TO_CHAR(LD_SYSDATE,'YYYY')||'01';
  LC_LASTMONTH   :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYYMM');
  LC_LASTYEAR    :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYY')||'01';

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03113 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、本年前50名当年数据
  BEGIN
    INSERT INTO TJBB_DT_B03113 
                (SSNY,BBLC,SWJGDM,CPCODE,QYHGDM,QYMC,JSMODE,JSMODEMC,PM,
                USA_CKE_YEAR,CKE_YEAR,USA_TMSE_YEAR,TMSE_YEAR,
                USA_CKE_YEAR_LAST,CKE_YEAR_LAST,USA_TMSE_YEAR_LAST,TMSE_YEAR_LAST,
                USA_CKE_TB,CKE_TB,USA_TMSE_TB,TMSE_TB,
                CKE_YEAR_ZB,CKE_YEAR_ZB_LAST,TMSE_YEAR_ZB,TMSE_YEAR_ZB_LAST)
    SELECT LC_THISMONTH,JSMODE||CASE WHEN PM<10 THEN '0' ELSE '' END||PM,V_SWCODE,CPCODE,QYHGDM,QYMC,JSMODE,JSMODEMC,PM,
           USA_CKE_YEAR,CKE_YEAR,USA_TMSE_YEAR,TMSE_YEAR,
           USA_CKE_YEAR_LAST,CKE_YEAR_LAST,USA_TMSE_YEAR_LAST,TMSE_YEAR_LAST,
           USA_CKE_TB,CKE_TB,USA_TMSE_TB,TMSE_TB,
           CKE_YEAR_ZB,CKE_YEAR_ZB_LAST,TMSE_YEAR_ZB,TMSE_YEAR_ZB_LAST
      FROM (SELECT CPCODE,QYHGDM,QYMC,JSMODE,JSMODEMC,
                   USA_CKE_YEAR,CKE_YEAR,USA_TMSE_YEAR,TMSE_YEAR,
                   USA_CKE_YEAR_LAST,CKE_YEAR_LAST,USA_TMSE_YEAR_LAST,TMSE_YEAR_LAST,
                   USA_CKE_TB,CKE_TB,USA_TMSE_TB,TMSE_TB,
                   CKE_YEAR_ZB,CKE_YEAR_ZB_LAST,TMSE_YEAR_ZB,TMSE_YEAR_ZB_LAST,
                   ROW_NUMBER() OVER (PARTITION BY JSMODE ORDER BY USA_CKE_YEAR DESC) AS PM
              FROM TJBB_DT_B03113 B 
             WHERE B.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))
               AND B.SSNY=LC_THISMONTH)
     WHERE PM<=50;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --2、汇总栏初始化
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03113 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03113' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
