CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03115_HZ_NEW
/*************************************************
 * 浙江省办理出口退税排名统计表（省、市局汇总）
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LC_THISMONTH     VARCHAR2(6);--当月
  LC_LASTMONTH     VARCHAR2(6);--上年同期

  LN_TMSE_HJ            NUMBER(16,4);--退（免）税额合计
  LN_TSE_HJ             NUMBER(16,4);--退税额合计
  LN_MDE_HJ             NUMBER(16,4);--免抵额合计
  LN_TMSE_HJ_LAST       NUMBER(16,4);--退（免）税额合计
  LN_TSE_HJ_LAST        NUMBER(16,4);--退税额合计
  LN_MDE_HJ_LAST        NUMBER(16,4);--免抵额合计
  LN_TMSE_OTHER         NUMBER(16,4);--退（免）税额合计
  LN_TSE_OTHER          NUMBER(16,4);--退税额合计
  LN_MDE_OTHER          NUMBER(16,4);--免抵额合计
  LN_TMSE_OTHER_LAST    NUMBER(16,4);--退（免）税额合计
  LN_TSE_OTHER_LAST     NUMBER(16,4);--退税额合计
  LN_MDE_OTHER_LAST     NUMBER(16,4);--免抵额合计

  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LD_SYSDATE       DATE;
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;

  LC_THISMONTH   :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LC_LASTMONTH   :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYYMM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03115 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、中间表数据计算
  BEGIN
    IF V_SWCODE='13300000000' THEN
      FOR CUR_PM IN (SELECT SWJGDM, JSMODE, DJXH, ROW_NUMBER() OVER (PARTITION BY JSMODE ORDER BY TMSE DESC) AS PM
                       FROM TJBB_DT_B03115_MID  
                      WHERE SSNY=LC_THISMONTH 
                        AND JSMODE IS NOT NULL)
      LOOP
        UPDATE TJBB_DT_B03115_MID T
           SET T.CKPM_3 = CUR_PM.PM
         WHERE T.SSNY=LC_THISMONTH AND T.JSMODE=CUR_PM.JSMODE AND T.SWJGDM=CUR_PM.SWJGDM AND T.DJXH=CUR_PM.DJXH;
        COMMIT;
      END LOOP;
    ELSE
      FOR CUR_PM IN (SELECT SWJGDM, JSMODE, DJXH, ROW_NUMBER() OVER (PARTITION BY JSMODE ORDER BY TMSE DESC) AS PM
                       FROM TJBB_DT_B03115_MID  
                      WHERE SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))
                        AND SSNY=LC_THISMONTH 
                        AND JSMODE IS NOT NULL)
      LOOP
        UPDATE TJBB_DT_B03115_MID T
           SET T.CKPM_2 = CUR_PM.PM
         WHERE T.SSNY=LC_THISMONTH AND T.JSMODE=CUR_PM.JSMODE AND T.SWJGDM=CUR_PM.SWJGDM AND T.DJXH=CUR_PM.DJXH;
        COMMIT;
      END LOOP;
    END IF;
  END;
  
  --2、查询并插入外贸（生产）各前10名
  BEGIN
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,JSMODEMC,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,TMSE_TB,XH)
    SELECT LC_THISMONTH, JSMODE||SUBSTR('00'||PM,-2), V_SWCODE,
           DJXH,SHXYNO,QYMC,JSMODE,JSMODEMC,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,TMSE_TB,PM
      FROM (SELECT DJXH, SHXYNO, QYMC, JSMODE, JSMODEMC, SWJG, TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,TMSE_TB,
                   ROW_NUMBER() OVER (PARTITION BY JSMODE ORDER BY TMSE DESC) AS PM
              FROM TJBB_DT_B03115 B 
             WHERE B.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))
               AND B.SSNY=LC_THISMONTH 
               AND B.JSMODE IS NOT NULL)
     WHERE PM<=20;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --3、计算并插入合计数、小计数与其他数
  BEGIN
    SELECT SUM(TMSE),SUM(TSE),SUM(MDE),SUM(TMSE_LAST),SUM(TSE_LAST),SUM(MDE_LAST)
      INTO LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ, LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='000';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '000', V_SWCODE,NULL,NULL,'合计',NULL,NULL,LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ,LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST,NULL
      FROM DUAL;
    COMMIT;

    SELECT SUM(TMSE),SUM(TSE),SUM(MDE),SUM(TMSE_LAST),SUM(TSE_LAST),SUM(MDE_LAST)
      INTO LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ, LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='100';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '100', V_SWCODE,NULL,NULL,'生产小计',NULL,NULL,LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ,LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST,NULL
      FROM DUAL;
    COMMIT;

    SELECT LN_TMSE_HJ - SUM(A.TMSE), LN_TSE_HJ - SUM(A.TSE), LN_MDE_HJ - SUM(A.MDE), 
           LN_TMSE_HJ_LAST - SUM(A.TMSE_LAST), LN_TSE_HJ_LAST - SUM(A.TSE_LAST), LN_MDE_HJ_LAST - SUM(A.MDE_LAST)
      INTO LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM=V_SWCODE AND A.SSNY=LC_THISMONTH AND A.BBLC>'100' AND A.BBLC<'200';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '199', V_SWCODE,NULL,NULL,'生产其他',NULL,NULL,LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST,NULL
      FROM DUAL;
    COMMIT;

    SELECT SUM(TMSE),SUM(TSE),SUM(MDE),SUM(TMSE_LAST),SUM(TSE_LAST),SUM(MDE_LAST)
      INTO LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ, LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='200';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '200', V_SWCODE,NULL,NULL,'外贸小计',NULL,NULL,LN_TMSE_HJ, LN_TSE_HJ, LN_MDE_HJ,LN_TMSE_HJ_LAST, LN_TSE_HJ_LAST, LN_MDE_HJ_LAST,NULL
      FROM DUAL;
    COMMIT;
    
    SELECT LN_TMSE_HJ - SUM(A.TMSE), LN_TSE_HJ - SUM(A.TSE), LN_MDE_HJ - SUM(A.MDE), 
           LN_TMSE_HJ_LAST - SUM(A.TMSE_LAST), LN_TSE_HJ_LAST - SUM(A.TSE_LAST), LN_MDE_HJ_LAST - SUM(A.MDE_LAST)
      INTO LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST
      FROM TJBB_DT_B03115 A
     WHERE A.SWJGDM=V_SWCODE AND A.SSNY=LC_THISMONTH AND A.BBLC>'200';
    INSERT INTO TJBB_DT_B03115 (SSNY,BBLC,SWJGDM,DJXH,SHXYNO,QYMC,JSMODE,SWJG,TMSE,TSE,MDE,TMSE_LAST,TSE_LAST,MDE_LAST,XH)
    SELECT LC_THISMONTH, '299', V_SWCODE,NULL,NULL,'外贸其他',NULL,NULL,LN_TMSE_OTHER, LN_TSE_OTHER, LN_MDE_OTHER, LN_TMSE_OTHER_LAST, LN_TSE_OTHER_LAST, LN_MDE_OTHER_LAST,NULL
      FROM DUAL;
    COMMIT;

    UPDATE TJBB_DT_B03115
       SET TMSE_TB = CASE WHEN NVL(TMSE_LAST,0)=0 THEN NULL ELSE ROUND(100 * TMSE / TMSE_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH
       AND BBLC IN ('000','100','199','200','299');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --4、汇总栏初始化
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03115 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03115' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
