CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B01103_CSH_NEW
/*************************************************
 * 未申报出口退（免）税情况统计月报表
 * 202202，针对同时申报出口货物劳务以及服务贸易的企业，调整lctjjc
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
  LC_PREVYEAR      VARCHAR2(4);
  LN_WSBHS_XJ      NUMBER(10);
  LN_WSBHS_WM      NUMBER(10);
  LN_WSBHS_WZF     NUMBER(10);
  LN_WSBHS_SC      NUMBER(10);
  LN_WSBHS_FWMY    NUMBER(10);
  LN_WSBWM_XJ      NUMBER(18,6);
  LN_WSBWM_PRE     NUMBER(18,6);
  LN_WSBWM_CUR     NUMBER(18,6);
  LN_WSBWZF_XJ     NUMBER(18,6);
  LN_WSBWZF_PRE    NUMBER(18,6);
  LN_WSBWZF_CUR    NUMBER(18,6);
  LN_WSBSC_XJ      NUMBER(18,6);
  LN_WSBSC_PRE     NUMBER(18,6);
  LN_WSBSC_CUR     NUMBER(18,6);
  LN_WSBFW_XJ      NUMBER(18,6);
  LN_WSBFW_PRE     NUMBER(18,6);
  LN_WSBFW_CUR     NUMBER(18,6);
  TOTAL_USD_AMT    NUMBER(18,6);
  TOTAL_TS_AMT     NUMBER(18,6);
  LN_TSE_PER_USD   NUMBER(18,6);
  LC_SWJGMC        VARCHAR2(100);
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LC_PREVYEAR    :=TO_CHAR(ADD_MONTHS(LD_THISYEAR,-1),'YYYY');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B01103 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、计算列
  BEGIN
    --税务机关名称
    SELECT SWJG_MC
      INTO LC_SWJGMC
      FROM DM_SWJG
     WHERE SWJG_DM=V_SWCODE;
    --户数
    SELECT COUNT(1),
           NVL(SUM(CASE WHEN A.BAJC_YEAR<'40' AND A.JSMODE='1' THEN 1 ELSE 0 END),0),
           NVL(SUM(CASE WHEN A.BAJC_YEAR<'40' AND A.JSMODE='2' THEN 1 ELSE 0 END),0),
           NVL(SUM(CASE WHEN A.BAJC_YEAR>='40' AND A.BAJC_YEAR<'70' THEN 1 ELSE 0 END),0),
           NVL(SUM(CASE WHEN A.BAJC_YEAR>='70' THEN 1 ELSE 0 END),0)
      INTO LN_WSBHS_XJ,LN_WSBHS_SC,LN_WSBHS_WM,LN_WSBHS_FWMY,LN_WSBHS_WZF
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX A
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.JSMODE IN ('1','2')
       AND EXISTS (SELECT 1 
                     FROM TL_TSSH.CKTS_WBSJ_BGD_WSB B
                    WHERE B.TSSWJG_DM=A.SWJGDM
                      AND B.DJXH=A.DJXH_JS);
    --生产企业
    SELECT NVL(ROUND(SUM(B.MYLAJ)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN B.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN 0 ELSE B.MYLAJ END)/10000,6),0)
      INTO LN_WSBSC_XJ,LN_WSBSC_PRE,LN_WSBSC_CUR
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX A
     INNER JOIN TL_TSSH.CKTS_WBSJ_BGD_WSB B ON B.TSSWJG_DM=A.SWJGDM AND B.DJXH=A.DJXH_JS
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.JSMODE='1'
       AND A.BAJC_YEAR<'40';
    --外贸企业
    SELECT NVL(ROUND(SUM(B.MYLAJ)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN B.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN 0 ELSE B.MYLAJ END)/10000,6),0)
      INTO LN_WSBWM_XJ,LN_WSBWM_PRE,LN_WSBWM_CUR
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX A
     INNER JOIN TL_TSSH.CKTS_WBSJ_BGD_WSB B ON B.TSSWJG_DM=A.SWJGDM AND B.DJXH=A.DJXH_JS
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.JSMODE='2'
       AND A.BAJC_YEAR<'40';
    --服务贸易企业
    SELECT NVL(ROUND(SUM(B.MYLAJ)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN B.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN 0 ELSE B.MYLAJ END)/10000,6),0)
      INTO LN_WSBFW_XJ,LN_WSBFW_PRE,LN_WSBFW_CUR
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX A
     INNER JOIN TL_TSSH.CKTS_WBSJ_BGD_WSB B ON B.TSSWJG_DM=A.SWJGDM AND B.DJXH=A.DJXH_JS
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.BAJC_YEAR>='40' AND A.BAJC_YEAR<'70';
    --外综服企业
    SELECT NVL(ROUND(SUM(B.MYLAJ)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN B.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN B.CKRQ_1<LD_THISYEAR THEN 0 ELSE B.MYLAJ END)/10000,6),0)
      INTO LN_WSBWZF_XJ,LN_WSBWZF_PRE,LN_WSBWZF_CUR
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX A
     INNER JOIN TL_TSSH.CKTS_WBSJ_BGD_WSB B ON B.TSSWJG_DM=A.SWJGDM AND B.DJXH=A.DJXH_JS
     WHERE A.SWJGDM=V_SWCODE
       AND A.ZX_FLAG='N'
       AND A.BAJC_YEAR>='70';
    --每美元退税额
    SELECT SUM(T.SB_XSEMY), SUM(NVL(T.SB_ZZSTSE,0)+NVL(T.SB_XFSTSE,0))
      INTO TOTAL_USD_AMT, TOTAL_TS_AMT
      FROM TL_TSSH.CKTS_LC_SHXX T
     WHERE T.TSSWJG_DM=V_SWCODE
       AND T.SBYWB_DM IN ('A0301001','A0305001','A0310001')
       AND TO_CHAR(T.QDSJ,'YYYY') = LC_PREVYEAR;
    LN_TSE_PER_USD := CASE WHEN TOTAL_USD_AMT=0 THEN 1 ELSE TOTAL_TS_AMT/TOTAL_USD_AMT END;
    
    INSERT INTO TJBB_DT_B01103(SSNY,BBLC,SWJGDM,SWJGMC, 
                HJ_QYHS,QYHS_WM,QYHS_WZF,QYHS_SC,QYHS_FWMY,
                CK_HJ,
                CK_WM_XJ,CK_WM_HIS,CK_WM_CUR,
                CK_WZF_XJ,CK_WZF_HIS,CK_WZF_CUR,
                CK_SC_XJ,CK_SC_HIS,CK_SC_CUR,
                CK_FWMY_XJ,CK_FWMY_HIS,CK_FWMY_CUR,
                TSE_PER_USD,
                CSTSE_HJ,
                CSTSE_WM_XJ,CSTSE_WM_HIS,CSTSE_WM_CUR,
                CSTSE_WZF_XJ,CSTSE_WZF_HIS,CSTSE_WZF_CUR,
                CSTSE_SC_XJ,CSTSE_SC_HIS,CSTSE_SC_CUR,
                CSTSE_FWMY_XJ,CSTSE_FWMY_HIS,CSTSE_FWMY_CUR)
         SELECT LC_THISMONTH, '01', V_SWCODE, LC_SWJGMC, 
                LN_WSBHS_XJ,LN_WSBHS_WM,LN_WSBHS_WZF,LN_WSBHS_SC,LN_WSBHS_FWMY,
                LN_WSBWM_XJ + LN_WSBWZF_XJ + LN_WSBSC_XJ + LN_WSBFW_XJ,
                LN_WSBWM_XJ,                   LN_WSBWM_PRE,                   LN_WSBWM_CUR,
                LN_WSBWZF_XJ,                  LN_WSBWZF_PRE,                  LN_WSBWZF_CUR,
                LN_WSBSC_XJ,                   LN_WSBSC_PRE,                   LN_WSBSC_CUR,
                LN_WSBFW_XJ,                   LN_WSBFW_PRE,                   LN_WSBFW_CUR,
                LN_TSE_PER_USD,
                LN_TSE_PER_USD * (LN_WSBWM_XJ + LN_WSBWZF_XJ + LN_WSBSC_XJ + LN_WSBFW_XJ),
                LN_TSE_PER_USD * LN_WSBWM_XJ,  LN_TSE_PER_USD * LN_WSBWM_PRE,  LN_TSE_PER_USD * LN_WSBWM_CUR,
                LN_TSE_PER_USD * LN_WSBWZF_XJ, LN_TSE_PER_USD * LN_WSBWZF_PRE, LN_TSE_PER_USD * LN_WSBWZF_CUR,
                LN_TSE_PER_USD * LN_WSBSC_XJ,  LN_TSE_PER_USD * LN_WSBSC_PRE,  LN_TSE_PER_USD * LN_WSBSC_CUR,
                LN_TSE_PER_USD * LN_WSBFW_XJ,  LN_TSE_PER_USD * LN_WSBFW_PRE,  LN_TSE_PER_USD * LN_WSBFW_CUR
           FROM DUAL;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --2、更新汇总列
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B01103 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B01103' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
