CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03106_CSH_NEW
/*************************************************
 * 浙江省出口商品主要贸易方式分布情况统计表
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LC_THISMONTH     VARCHAR2(6);--当月
  LC_THISYEAR      VARCHAR2(6);--当年1月
  LC_LASTMONTH     VARCHAR2(6);--上年同期
  LC_LASTYEAR      VARCHAR2(6);--上年1月
  
  LN_CKE_THIS      NUMBER(16,4);--本年出口额合计
  LN_TSE_THIS      NUMBER(16,4);--本年退税额合计
  LN_CKE_LAST      NUMBER(16,4);--上年出口额合计
  LN_TSE_LAST      NUMBER(16,4);--上年退税额合计
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LD_SYSDATE       DATE;
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;
  
  LC_THISMONTH   :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LC_THISYEAR    :=TO_CHAR(LD_SYSDATE,'YYYY')||'01';
  LC_LASTMONTH   :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYYMM');
  LC_LASTYEAR    :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYY')||'01';
  
  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03106 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、计算并插入本年明细
  BEGIN
    INSERT INTO TJBB_DT_B03106 (SSNY,BBLC,SWJGDM,MYFS_DM,MYFS_MC,CKE_YEAR,TSE_YEAR,CKE_YEAR_LAST,TSE_YEAR_LAST)
      WITH FL_TDCODE AS (SELECT XMFL, 
                                SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN USD_AMT ELSE 0 END)/10000 AS USD_AMT, 
                                SUM(CASE WHEN SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH THEN TS_AMT  ELSE 0 END)/10000 AS TS_AMT, 
                                SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN USD_AMT ELSE 0 END)/10000 AS USD_AMT_LAST, 
                                SUM(CASE WHEN SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH THEN TS_AMT  ELSE 0 END)/10000 AS TS_AMT_LAST
                           FROM TL_TSSH.TJBB_FHXX_TDCODE
                          WHERE SWCODE=V_SWCODE 
                            AND ((SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH) OR (SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH))
                          GROUP BY XMFL)
    SELECT LC_THISMONTH, '01', V_SWCODE, '', '合计', ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_TDCODE
     UNION ALL
    SELECT LC_THISMONTH, '02', V_SWCODE, '0110', '一般贸易', ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_TDCODE
     WHERE XMFL='0110'
     UNION ALL
    SELECT LC_THISMONTH, '03', V_SWCODE, '0615', '进料对口', ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_TDCODE
     WHERE XMFL='0615'
     UNION ALL
    SELECT LC_THISMONTH, '04', V_SWCODE, '1039', '市场采购', ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_TDCODE
     WHERE XMFL='1039'
     UNION ALL
    SELECT LC_THISMONTH, '05', V_SWCODE, '9610', '电子商务', ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_TDCODE
     WHERE XMFL='9610'
     UNION ALL
    SELECT LC_THISMONTH, '06', V_SWCODE, '9710', '跨境电商B2B直接出口', ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_TDCODE
     WHERE XMFL='9710'
     UNION ALL
    SELECT LC_THISMONTH, '07', V_SWCODE, '9810', '跨境电商出口海外仓', ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_TDCODE
     WHERE XMFL='9810'
     UNION ALL
    SELECT LC_THISMONTH, '08', V_SWCODE, '', '其他', ROUND(SUM(USD_AMT),0), ROUND(SUM(TS_AMT),0), ROUND(SUM(USD_AMT_LAST),0), ROUND(SUM(TS_AMT_LAST),0)
      FROM FL_TDCODE
     WHERE XMFL NOT IN ('0110','0615','1039','9610','9710','9810');
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --2、同比计算
  BEGIN
    UPDATE TJBB_DT_B03106
       SET CKE_YEAR_TB  = CASE WHEN NVL(CKE_YEAR_LAST,0)=0 THEN NULL ELSE ROUND(100 * CKE_YEAR / CKE_YEAR_LAST -100,1) END,
           TMSE_YEAR_TB = CASE WHEN NVL(TSE_YEAR_LAST,0)=0 THEN NULL ELSE ROUND(100 * TSE_YEAR / TSE_YEAR_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --3、占比计算
  BEGIN
    SELECT CKE_YEAR, TSE_YEAR, CKE_YEAR_LAST, TSE_YEAR_LAST
      INTO LN_CKE_THIS, LN_TSE_THIS, LN_CKE_LAST, LN_TSE_LAST
      FROM TJBB_DT_B03106
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH AND BBLC='01';
    UPDATE TJBB_DT_B03106 T
       SET CKE_YEAR_ZB  = CASE WHEN NVL(LN_CKE_THIS,0)=0 THEN NULL ELSE ROUND(100 * CKE_YEAR / LN_CKE_THIS,1) END,
           TMSE_YEAR_ZB = CASE WHEN NVL(LN_TSE_THIS,0)=0 THEN NULL ELSE ROUND(100 * TSE_YEAR / LN_TSE_THIS,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --4、汇总栏初始化
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03106 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03106' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
