CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03116_CSH_NEW
/*************************************************
 * 跨境电子商务零售出口退税情况统计表9810
 * 202504，根据省局关注点全新设计，分出口电子信息、申报（其中预退税）、办理（其中预退税）
 * 20250519，根据5月初报表运行情况创建表索引并优化语句
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
  LD_NEXTMONTH     DATE;
  LC_SQL           VARCHAR2(4000);
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LN_CK_HS         NUMBER(10);
  LN_CK_MY         NUMBER(18,6);
  LN_CK_RMB        NUMBER(18,6);
  LN_SB_HS         NUMBER(10);
  LN_SB_MY         NUMBER(18,6);
  LN_SB_JSJE       NUMBER(18,6);
  LN_SB_TMSE       NUMBER(18,6);
  LN_SB_HS_YT      NUMBER(10);
  LN_SB_MY_YT      NUMBER(18,6);
  LN_SB_JSJE_YT    NUMBER(18,6);
  LN_SB_TMSE_YT    NUMBER(18,6);
  LN_BL_HS         NUMBER(10);
  LN_BL_MY         NUMBER(18,6);
  LN_BL_JSJE       NUMBER(18,6);
  LN_BL_TMSE       NUMBER(18,6);
  LN_BL_HS_YT      NUMBER(10);
  LN_BL_MY_YT      NUMBER(18,6);
  LN_BL_JSJE_YT    NUMBER(18,6);
  LN_BL_TMSE_YT    NUMBER(18,6);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_SYSDATE,1),'MM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03116 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、当月外贸企业
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     INNER JOIN TL_TSSH.GLXT_BB_SHXT_DJXX DJ
        ON DJ.DJXH_JS=BGD.DJXH
       AND DJ.JSMODE<>'1'
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.JGFS_DM = '9810'
       AND BGD.CKRQ_1>=LD_SYSDATE AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT MTS.DJXH), NVL(ROUND(SUM(MTS.MYLAJ)/10000,6),0), NVL(ROUND(SUM(MTS.JSJE)/10000,6),0), NVL(ROUND(SUM(MTS.TSE)/10000,6),0),
           COUNT(DISTINCT CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.DJXH ELSE NULL END),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.JSJE ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.TSE ELSE 0 END)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
           LN_SB_HS_YT, LN_SB_MY_YT, LN_SB_JSJE_YT, LN_SB_TMSE_YT
      FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
     WHERE MTS.TSSWJG_DM=V_SWCODE
       AND MTS.TDCODE = '9810'
       AND MTS.SBRQ>=LD_SYSDATE AND MTS.SBRQ<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT MTS.DJXH), NVL(ROUND(SUM(MTS.MYLAJ)/10000,6),0), NVL(ROUND(SUM(MTS.JSJE)/10000,6),0), NVL(ROUND(SUM(MTS.TSE)/10000,6),0),
           COUNT(DISTINCT CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.DJXH ELSE NULL END),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.JSJE ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.TSE ELSE 0 END)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE,
           LN_BL_HS_YT, LN_BL_MY_YT, LN_BL_JSJE_YT, LN_BL_TMSE_YT
      FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
     WHERE MTS.TSSWJG_DM=V_SWCODE
       AND MTS.TDCODE = '9810'
       AND MTS.FSRQ>=LD_SYSDATE AND MTS.FSRQ<LD_NEXTMONTH
       AND NVL(MTS.BYBLBZ,'N')='N' AND NVL(MTS.BYTSBZ,'N')='N' AND MTS.SJLY='2';
    
    INSERT INTO TJBB_DT_B03116 (SSNY, BBLC, SWJGDM, CK_HS, CK_MYLAJ, CK_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE, SB_YTS_HS, SB_YTS_MYXSE, SB_YTS_JSJE, SB_YTS_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE, BL_YTS_HS, BL_YTS_MYXSE, BL_YTS_JSJE, BL_YTS_TMSE)
         SELECT LC_THISMONTH, '01', V_SWCODE, LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE, LN_SB_HS_YT, LN_SB_MY_YT, LN_SB_JSJE_YT, LN_SB_TMSE_YT,
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE, LN_BL_HS_YT, LN_BL_MY_YT, LN_BL_JSJE_YT, LN_BL_TMSE_YT
           FROM DUAL;
    COMMIT;
  END;

  --2、当月生产企业
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     INNER JOIN TL_TSSH.GLXT_BB_SHXT_DJXX DJ
        ON DJ.DJXH_JS=BGD.DJXH
       AND DJ.JSMODE='1'
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.JGFS_DM = '9810'
       AND BGD.CKRQ_1>=LD_SYSDATE AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT MDT.DJXH), NVL(ROUND(SUM(MDT.MYLAJ)/10000,6),0), NVL(ROUND(SUM(MDT.RMBLAJ)/10000,6),0), NVL(ROUND(SUM(MDT.MDTSE)/10000,6),0),
           COUNT(DISTINCT CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.DJXH ELSE NULL END),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.RMBLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.MDTSE ELSE 0 END)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
           LN_SB_HS_YT, LN_SB_MY_YT, LN_SB_JSJE_YT, LN_SB_TMSE_YT
      FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
     WHERE MDT.TSSWJG_DM=V_SWCODE
       AND MDT.TDCODE = '9810'
       AND MDT.SBRQ>=LD_SYSDATE AND MDT.SBRQ<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT MDT.DJXH), NVL(ROUND(SUM(MDT.MYLAJ)/10000,6),0), NVL(ROUND(SUM(MDT.RMBLAJ)/10000,6),0), NVL(ROUND(SUM(MDT.MDTSE)/10000,6),0),
           COUNT(DISTINCT CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.DJXH ELSE NULL END),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.RMBLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.MDTSE ELSE 0 END)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE,
           LN_BL_HS_YT, LN_BL_MY_YT, LN_BL_JSJE_YT, LN_BL_TMSE_YT
      FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
     WHERE MDT.TSSWJG_DM=V_SWCODE
       AND MDT.TDCODE = '9810'
       AND MDT.FSRQ>=LD_SYSDATE AND MDT.FSRQ<LD_NEXTMONTH
       AND NVL(MDT.BYBLBZ,'N')='N' AND NVL(MDT.BYTSBZ,'N')='N' AND MDT.SJLY='2';
    
    INSERT INTO TJBB_DT_B03116 (SSNY, BBLC, SWJGDM, CK_HS, CK_MYLAJ, CK_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE, SB_YTS_HS, SB_YTS_MYXSE, SB_YTS_JSJE, SB_YTS_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE, BL_YTS_HS, BL_YTS_MYXSE, BL_YTS_JSJE, BL_YTS_TMSE)
         SELECT LC_THISMONTH, '02', V_SWCODE, LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE, LN_SB_HS_YT, LN_SB_MY_YT, LN_SB_JSJE_YT, LN_SB_TMSE_YT, 
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE, LN_BL_HS_YT, LN_BL_MY_YT, LN_BL_JSJE_YT, LN_BL_TMSE_YT
           FROM DUAL;
    COMMIT;
  END;

  --3、当月小计
  
  --4、当年外贸企业
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     INNER JOIN TL_TSSH.GLXT_BB_SHXT_DJXX DJ
        ON DJ.DJXH_JS=BGD.DJXH
       AND DJ.JSMODE<>'1'
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.JGFS_DM = '9810'
       AND BGD.CKRQ_1>=LD_THISYEAR AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT MTS.DJXH), NVL(ROUND(SUM(MTS.MYLAJ)/10000,6),0), NVL(ROUND(SUM(MTS.JSJE)/10000,6),0), NVL(ROUND(SUM(MTS.TSE)/10000,6),0),
           COUNT(DISTINCT CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.DJXH ELSE NULL END),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.JSJE ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.TSE ELSE 0 END)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
           LN_SB_HS_YT, LN_SB_MY_YT, LN_SB_JSJE_YT, LN_SB_TMSE_YT
      FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
     WHERE MTS.TSSWJG_DM=V_SWCODE
       AND MTS.TDCODE = '9810'
       AND MTS.SBRQ>=LD_THISYEAR AND MTS.SBRQ<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT MTS.DJXH), NVL(ROUND(SUM(MTS.MYLAJ)/10000,6),0), NVL(ROUND(SUM(MTS.JSJE)/10000,6),0), NVL(ROUND(SUM(MTS.TSE)/10000,6),0),
           COUNT(DISTINCT CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.DJXH ELSE NULL END),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.JSJE ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MTS.CKTMSYWLXDMJH ,'^HWC-YT') THEN MTS.TSE ELSE 0 END)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE,
           LN_BL_HS_YT, LN_BL_MY_YT, LN_BL_JSJE_YT, LN_BL_TMSE_YT
      FROM TL_TSSH.CKTS_SB_MTS_CKMX MTS
     WHERE MTS.TSSWJG_DM=V_SWCODE
       AND MTS.TDCODE = '9810'
       AND MTS.FSRQ>=LD_THISYEAR AND MTS.FSRQ<LD_NEXTMONTH
       AND NVL(MTS.BYBLBZ,'N')='N' AND NVL(MTS.BYTSBZ,'N')='N' AND MTS.SJLY='2';
    
    INSERT INTO TJBB_DT_B03116 (SSNY, BBLC, SWJGDM, CK_HS, CK_MYLAJ, CK_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE, SB_YTS_HS, SB_YTS_MYXSE, SB_YTS_JSJE, SB_YTS_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE, BL_YTS_HS, BL_YTS_MYXSE, BL_YTS_JSJE, BL_YTS_TMSE)
         SELECT LC_THISMONTH, '04', V_SWCODE, LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE, LN_SB_HS_YT, LN_SB_MY_YT, LN_SB_JSJE_YT, LN_SB_TMSE_YT,
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE, LN_BL_HS_YT, LN_BL_MY_YT, LN_BL_JSJE_YT, LN_BL_TMSE_YT
           FROM DUAL;
    COMMIT;
  END;

  --5、当年生产企业
  BEGIN
    SELECT COUNT(DISTINCT BGD.DJXH), NVL(ROUND(SUM(BGD.MYLAJ)/10000,6),0), NVL(ROUND(SUM(BGD.RMBLAJ)/10000,6),0)
      INTO LN_CK_HS, LN_CK_MY, LN_CK_RMB
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD BGD
     INNER JOIN TL_TSSH.GLXT_BB_SHXT_DJXX DJ
        ON DJ.DJXH_JS=BGD.DJXH
       AND DJ.JSMODE='1'
     WHERE BGD.TSSWJG_DM_1=V_SWCODE
       AND BGD.JGFS_DM = '9810'
       AND BGD.CKRQ_1>=LD_THISYEAR AND BGD.CKRQ_1<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT MDT.DJXH), NVL(ROUND(SUM(MDT.MYLAJ)/10000,6),0), NVL(ROUND(SUM(MDT.RMBLAJ)/10000,6),0), NVL(ROUND(SUM(MDT.MDTSE)/10000,6),0),
           COUNT(DISTINCT CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.DJXH ELSE NULL END),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.RMBLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.MDTSE ELSE 0 END)/10000,6),0)
      INTO LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE,
           LN_SB_HS_YT, LN_SB_MY_YT, LN_SB_JSJE_YT, LN_SB_TMSE_YT
      FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
     WHERE MDT.TSSWJG_DM=V_SWCODE
       AND MDT.TDCODE = '9810'
       AND MDT.SBRQ>=LD_THISYEAR AND MDT.SBRQ<LD_NEXTMONTH;
    
    SELECT COUNT(DISTINCT MDT.DJXH), NVL(ROUND(SUM(MDT.MYLAJ)/10000,6),0), NVL(ROUND(SUM(MDT.RMBLAJ)/10000,6),0), NVL(ROUND(SUM(MDT.MDTSE)/10000,6),0),
           COUNT(DISTINCT CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.DJXH ELSE NULL END),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.MYLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.RMBLAJ ELSE 0 END)/10000,6),0),
           NVL(ROUND(SUM(CASE WHEN REGEXP_LIKE(MDT.CKTMSYWLXDMJH ,'^HWC-YT') THEN MDT.MDTSE ELSE 0 END)/10000,6),0)
      INTO LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE,
           LN_BL_HS_YT, LN_BL_MY_YT, LN_BL_JSJE_YT, LN_BL_TMSE_YT
      FROM TL_TSSH.CKTS_SB_MDT_CKMX MDT
     WHERE MDT.TSSWJG_DM=V_SWCODE
       AND MDT.TDCODE = '9810'
       AND MDT.FSRQ>=LD_THISYEAR AND MDT.FSRQ<LD_NEXTMONTH
       AND NVL(MDT.BYBLBZ,'N')='N' AND NVL(MDT.BYTSBZ,'N')='N' AND MDT.SJLY='2';
    
    INSERT INTO TJBB_DT_B03116 (SSNY, BBLC, SWJGDM, CK_HS, CK_MYLAJ, CK_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE, SB_YTS_HS, SB_YTS_MYXSE, SB_YTS_JSJE, SB_YTS_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE, BL_YTS_HS, BL_YTS_MYXSE, BL_YTS_JSJE, BL_YTS_TMSE)
         SELECT LC_THISMONTH, '05', V_SWCODE, LN_CK_HS, LN_CK_MY, LN_CK_RMB,
                LN_SB_HS, LN_SB_MY, LN_SB_JSJE, LN_SB_TMSE, LN_SB_HS_YT, LN_SB_MY_YT, LN_SB_JSJE_YT, LN_SB_TMSE_YT, 
                LN_BL_HS, LN_BL_MY, LN_BL_JSJE, LN_BL_TMSE, LN_BL_HS_YT, LN_BL_MY_YT, LN_BL_JSJE_YT, LN_BL_TMSE_YT
           FROM DUAL;
    COMMIT;
  END;
  
  --6、本年小计
  
  --10、小计行计算
  BEGIN
    FOR LSF_XX IN (SELECT TRIM(TO_CHAR(SUBSTR(T.FORMULA,2,INSTR(T.FORMULA,')')-2),'00')) AS BBLC,
                          '('||REPLACE(REPLACE(REPLACE(SUBSTR(T.FORMULA,INSTR(T.FORMULA,'=')+1),'(',''''),'+',','),')','''')||')' AS BBCS
                     FROM TJBB_REPORT_FORMULA T 
                    WHERE T.BBDM='B03116' 
                      AND T.TYPE=2
                    ORDER BY T.YXJ) 
    LOOP
      BEGIN
        LC_SQL := 'INSERT INTO TJBB_DT_B03116 (SSNY, BBLC, SWJGDM, CK_HS, CK_MYLAJ, CK_RMBLAJ,
                SB_HS, SB_MYXSE, SB_JSJE, SB_TMSE, SB_YTS_HS, SB_YTS_MYXSE, SB_YTS_JSJE, SB_YTS_TMSE,
                BL_HS, BL_MYXSE, BL_JSJE, BL_TMSE, BL_YTS_HS, BL_YTS_MYXSE, BL_YTS_JSJE, BL_YTS_TMSE)
                   SELECT '''||LC_THISMONTH||''', '''||LSF_XX.BBLC||''', '''||V_SWCODE||''', 
                          SUM(CK_HS),     SUM(CK_MYLAJ),     SUM(CK_RMBLAJ),
                          SUM(SB_HS),     SUM(SB_MYXSE),     SUM(SB_JSJE),     SUM(SB_TMSE),
                          SUM(SB_YTS_HS), SUM(SB_YTS_MYXSE), SUM(SB_YTS_JSJE), SUM(SB_YTS_TMSE),
                          SUM(BL_HS),     SUM(BL_MYXSE),     SUM(BL_JSJE),     SUM(BL_TMSE),
                          SUM(BL_YTS_HS), SUM(BL_YTS_MYXSE), SUM(BL_YTS_JSJE), SUM(BL_YTS_TMSE)
                     FROM TJBB_DT_B03116
                    WHERE SWJGDM='''||V_SWCODE||'''
                      AND SSNY='''||LC_THISMONTH||'''
                      AND TRIM(TO_CHAR(TO_NUMBER(BBLC))) IN '||LSF_XX.BBCS;
        
        EXECUTE IMMEDIATE LC_SQL;
        COMMIT;
      END;
    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --11、更新汇总列
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03116 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03116' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
