CREATE OR REPLACE PROCEDURE PRO_TJBB_CSH_ONETABLE
(
	LC_MONTH    IN  VARCHAR2
)
AS
  LN_ERROR         NUMBER;
  LC_MSG           VARCHAR2(2000);
  LC_SWJGDM        VARCHAR2(11);
BEGIN

  --区县局
  FOR LSF_SWJG IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND QYBZ='Y' AND YXWS=7 ORDER BY SWJG_DM) LOOP
    LC_SWJGDM := LSF_SWJG.SWJG_DM;

    BEGIN
      PRO_TJBB_DT_B03116_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03116_CSH_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03116_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;
  END LOOP;

  FOR LSF_SWJG IN (SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND QYBZ='Y' AND YXWS=5 ORDER BY SWJG_DM) LOOP
    LC_SWJGDM := LSF_SWJG.SWJG_DM;

    BEGIN
      PRO_TJBB_DT_B03116_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03116_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03116_HZ_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;

  END LOOP;

  LC_SWJGDM := '13300000000';

    BEGIN
      PRO_TJBB_DT_B03116_HZ_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B03116_HZ_NEW！'||LC_SWJGDM);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B03116_HZ_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
        COMMIT;
    END;

END;
/
