CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B02109_CSH_NEW
/*************************************************
 * 向外贸综合服务企业供货情况统计表
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE         DATE;
  LC_THISMONTH       VARCHAR2(6);
  LD_THISYEAR        DATE;
  LD_NEXTMONTH       DATE;

  LC_SQL_UPDATEHZ  VARCHAR2(4000);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_SYSDATE,1),'MM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02109 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、统计
  BEGIN
    INSERT INTO TJBB_DT_B02109 (SSNY,BBLC,SWJGDM,XH,NSRSBH,QYMC,JSJE_MON,JSJE_YEAR,SBTSE_MON,SBTSE_YEAR,SPHGDMS,QYHGDM)
    WITH WZFJHMX AS (SELECT A.DJXH, B.GHFNSRSBH_1, MIN(SUBSTR(B.CKSP_DM,1,4)) AS CMCODE4, 
                            NVL(ROUND(SUM(CASE WHEN A.QDSJ>=LD_SYSDATE THEN B.JSJE ELSE 0 END)/10000,6),0) AS JSJE_MON, 
                            NVL(ROUND(SUM(B.JSJE)/10000,6),0) AS JSJE_YEAR,
                            NVL(ROUND(SUM(CASE WHEN A.QDSJ>=LD_SYSDATE THEN B.TSE ELSE 0 END)/10000,6),0) AS SBTSE_MON, 
                            NVL(ROUND(SUM(B.TSE)/10000,6),0) AS SBTSE_YEAR
                       FROM TL_TSSH.CKTS_LC_SHXX A
                      INNER JOIN TL_TSSH.CKTS_SB_MTS_JHMX B ON B.LCSLID=A.LCSLID
                      WHERE A.TSSWJG_DM=V_SWCODE
                        AND A.LCTJJC = '71'
                        AND A.QDSJ<LD_NEXTMONTH
                        AND A.LCJSRQ>=LD_THISYEAR
                      GROUP BY A.DJXH,B.GHFNSRSBH_1)
    SELECT LC_THISMONTH, SUBSTR(V_SWCODE, 4, 4)|| SUBSTR('000000'||ROWNUM, LENGTH('000000'||ROWNUM)-5, 6), V_SWCODE, ROWNUM,
           WZFJHMX.GHFNSRSBH_1, D.NSRMC, WZFJHMX.JSJE_MON, WZFJHMX.JSJE_YEAR, WZFJHMX.SBTSE_MON, WZFJHMX.SBTSE_YEAR, WZFJHMX.CMCODE4, C.QYHGDM
      FROM WZFJHMX
     INNER JOIN TL_TSSH.GLXT_BB_SHXT_DJXX C ON C.DJXH_JS=WZFJHMX.DJXH
      LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX D ON D.NSRDJNO=WZFJHMX.GHFNSRSBH_1 OR D.SHXYNO=WZFJHMX.GHFNSRSBH_1;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --2、行内计算
  --3、汇总栏初始化
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B02109 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02109' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  RETURN;
END;
/
