CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03107_CSH_NEW
/*************************************************
 * 浙江省出口退（免）税分类管理情况统计表
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LC_THISMONTH     VARCHAR2(6);--当月
  LC_THISYEAR      VARCHAR2(6);--当年1月
  LC_LASTMONTH     VARCHAR2(6);--上年同期
  LC_LASTYEAR      VARCHAR2(6);--上年1月
  
  LN_TSE_HJ        NUMBER(16,4);--退税额合计
  TSE_1_LAST       NUMBER(16,4);
  TSE_2_LAST       NUMBER(16,4);
  TSE_3_LAST       NUMBER(16,4);
  TSE_4_LAST       NUMBER(16,4);
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LD_SYSDATE       DATE;
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;
  
  LC_THISMONTH   :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LC_THISYEAR    :=TO_CHAR(LD_SYSDATE,'YYYY')||'01';
  LC_LASTMONTH   :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYYMM');
  LC_LASTYEAR    :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYY')||'01';

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03107 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、计算并插入本年明细
  BEGIN
    INSERT INTO TJBB_DT_B03107 (SSNY,BBLC,SWJGDM,SBHS_1,SBHS_2,SBHS_3,SBHS_4,TSE_1_LJ,TSE_2_LJ,TSE_3_LJ,TSE_4_LJ)
    WITH THISYEAR AS (SELECT A.XMFL, A.TS_AMT_ALL, NVL(B.FLGLCD,'C') AS FLGLCD_B, NVL(C.KZXX,'C') AS FLGLCD_C, 
                             ROW_NUMBER() OVER (PARTITION BY A.SWCODE,A.XMFL,A.SSNY,A.SBYWBDM ORDER BY C.ST_DATE DESC) AS RN
                        FROM TL_TSSH.TJBB_FHXX_CPCODE A
                        LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX B ON A.XMFL=B.CPCODE
                        LEFT JOIN TL_BJTS.GS_DJ_CKTMSDAB_KZ C ON A.XMFL=C.CPCODE AND C.KZLX='FLGLCD' AND C.FLAG='1' AND A.SSNY||'01' BETWEEN TO_CHAR(C.ST_DATE,'YYYYMMDD') AND TO_CHAR(C.END_DATE,'YYYYMMDD')
                       WHERE A.SWCODE=V_SWCODE 
                         AND A.SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH)
    SELECT LC_THISMONTH, '01', V_SWCODE, 
           COUNT(DISTINCT CASE WHEN FLGLCD_B='A' THEN XMFL ELSE NULL END),
           COUNT(DISTINCT CASE WHEN FLGLCD_B='B' THEN XMFL ELSE NULL END),
           COUNT(DISTINCT CASE WHEN FLGLCD_B='C' THEN XMFL ELSE NULL END),
           COUNT(DISTINCT CASE WHEN FLGLCD_B='D' THEN XMFL ELSE NULL END),
           ROUND(SUM(CASE WHEN FLGLCD_C='A' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='B' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='C' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='D' THEN TS_AMT_ALL ELSE 0 END)/10000,0)
      FROM THISYEAR
     WHERE RN=1;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --2、更新地区名称
  BEGIN
    UPDATE TJBB_DT_B03107 T
       SET AREA=(SELECT S.SWJG_JC FROM DM_SWJG S WHERE S.SWJG_DM=T.SWJGDM)
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  --3、更新上年同期
  BEGIN
    WITH LASTYEAR AS (SELECT A.XMFL, A.TS_AMT_ALL, NVL(B.FLGLCD,'C') AS FLGLCD_B, NVL(C.KZXX,'C') AS FLGLCD_C, 
                             ROW_NUMBER() OVER (PARTITION BY A.SWCODE,A.XMFL,A.SSNY,A.SBYWBDM ORDER BY C.ST_DATE DESC) AS RN
                        FROM TL_TSSH.TJBB_FHXX_CPCODE A
                        LEFT JOIN TL_TSSH.GLXT_BB_SHXT_DJXX B ON A.XMFL=B.CPCODE
                        LEFT JOIN TL_BJTS.GS_DJ_CKTMSDAB_KZ C ON A.XMFL=C.CPCODE AND C.KZLX='FLGLCD' AND C.FLAG='1' AND A.SSNY||'01' BETWEEN TO_CHAR(C.ST_DATE,'YYYYMMDD') AND TO_CHAR(C.END_DATE,'YYYYMMDD')
                       WHERE A.SWCODE=V_SWCODE 
                         AND A.SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH)
    SELECT ROUND(SUM(CASE WHEN FLGLCD_C='A' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='B' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='C' THEN TS_AMT_ALL ELSE 0 END)/10000,0),
           ROUND(SUM(CASE WHEN FLGLCD_C='D' THEN TS_AMT_ALL ELSE 0 END)/10000,0)
      INTO TSE_1_LAST,TSE_2_LAST,TSE_3_LAST,TSE_4_LAST
      FROM LASTYEAR
     WHERE RN=1;
    UPDATE TJBB_DT_B03107 T
       SET (TSE_1_LJ_LAST,TSE_2_LJ_LAST,TSE_3_LJ_LAST,TSE_4_LJ_LAST) = (SELECT TSE_1_LAST,TSE_2_LAST,TSE_3_LAST,TSE_4_LAST FROM DUAL)
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  --4、同比计算
  BEGIN
    UPDATE TJBB_DT_B03107
       SET TSE_1_TB = CASE WHEN NVL(TSE_1_LJ_LAST,0)=0 THEN NULL ELSE ROUND(100 * TSE_1_LJ / TSE_1_LJ_LAST -100,1) END,
           TSE_2_TB = CASE WHEN NVL(TSE_2_LJ_LAST,0)=0 THEN NULL ELSE ROUND(100 * TSE_2_LJ / TSE_2_LJ_LAST -100,1) END,
           TSE_3_TB = CASE WHEN NVL(TSE_3_LJ_LAST,0)=0 THEN NULL ELSE ROUND(100 * TSE_3_LJ / TSE_3_LJ_LAST -100,1) END,
           TSE_4_TB = CASE WHEN NVL(TSE_4_LJ_LAST,0)=0 THEN NULL ELSE ROUND(100 * TSE_4_LJ / TSE_4_LJ_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --5、占比计算
  BEGIN
    SELECT TSE_1_LJ + TSE_2_LJ + TSE_3_LJ + TSE_4_LJ
      INTO LN_TSE_HJ
      FROM TJBB_DT_B03107
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    
    UPDATE TJBB_DT_B03107 T
       SET TSE_1_ZB = CASE WHEN NVL(LN_TSE_HJ,0)=0 THEN NULL ELSE ROUND(100 * TSE_1_LJ / LN_TSE_HJ,1) END,
           TSE_2_ZB = CASE WHEN NVL(LN_TSE_HJ,0)=0 THEN NULL ELSE ROUND(100 * TSE_2_LJ / LN_TSE_HJ,1) END,
           TSE_3_ZB = CASE WHEN NVL(LN_TSE_HJ,0)=0 THEN NULL ELSE ROUND(100 * TSE_3_LJ / LN_TSE_HJ,1) END,
           TSE_4_ZB = CASE WHEN NVL(LN_TSE_HJ,0)=0 THEN NULL ELSE ROUND(100 * TSE_4_LJ / LN_TSE_HJ,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --6、汇总栏初始化
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03107 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03107' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
