CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B03109_CSH_NEW
/*************************************************
 * 浙江省分出口海关分布情况统计表
 * 20210205，金额栏保留整数，比率保留小数点后1位
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY IN VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LC_THISMONTH     VARCHAR2(6);--当月
  LC_THISYEAR      VARCHAR2(6);--当年1月
  LC_LASTMONTH     VARCHAR2(6);--上年同期
  LC_LASTYEAR      VARCHAR2(6);--上年1月
  
  LN_CKE_HJ        NUMBER(16,4);--出口额合计
  LN_TSE_HJ        NUMBER(16,4);--退税额合计
  LN_CKE_LAST      NUMBER(16,4);--出口额合计
  LN_TSE_LAST      NUMBER(16,4);--退税额合计
  LN_CKE_OTHER     NUMBER(16,4);--出口额合计
  LN_TSE_OTHER     NUMBER(16,4);--退税额合计
  LN_CKE_OTHER_LAST     NUMBER(16,4);--出口额合计
  LN_TSE_OTHER_LAST     NUMBER(16,4);--退税额合计
  
  V_TEMP           NUMBER(10, 0) := 0;
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
  LD_SYSDATE       DATE;
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=SYSDATE;
  END IF;
  
  LC_THISMONTH   :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LC_THISYEAR    :=TO_CHAR(LD_SYSDATE,'YYYY')||'01';
  LC_LASTMONTH   :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYYMM');
  LC_LASTYEAR    :=TO_CHAR(ADD_MONTHS(LD_SYSDATE,-12),'YYYY')||'01';

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B03109_MID WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    DELETE FROM TJBB_DT_B03109 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --1、中间表数据计算
  BEGIN
    INSERT INTO TJBB_DT_B03109_MID (SWJGDM,SSNY,GBDM,CKE_LJ,TSE_LJ,CKPM)
    SELECT V_SWCODE, LC_THISMONTH, XMFL, ROUND(SUM(USD_AMT)/10000,0), ROUND(SUM(TS_AMT)/10000,0), ROW_NUMBER() OVER (ORDER BY SUM(USD_AMT) DESC)
      FROM TL_TSSH.TJBB_FHXX_HGCODE
     WHERE SWCODE=V_SWCODE AND SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH
     GROUP BY XMFL;
    COMMIT;
    
    SELECT COUNT(1)
      INTO V_TEMP
      FROM TJBB_DT_B03109_MID
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_LASTMONTH;
    IF V_TEMP = 0 THEN
      BEGIN
        INSERT INTO TJBB_DT_B03109_MID (SWJGDM,SSNY,GBDM,CKE_LJ,TSE_LJ,CKPM)
        SELECT V_SWCODE, LC_LASTMONTH, XMFL, ROUND(SUM(USD_AMT)/10000,0), ROUND(SUM(TS_AMT)/10000,0), ROW_NUMBER() OVER (ORDER BY SUM(USD_AMT) DESC)
          FROM TL_TSSH.TJBB_FHXX_HGCODE
         WHERE SWCODE=V_SWCODE AND SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH
         GROUP BY XMFL;
        COMMIT;
      END;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --2、计算并插入本年前20名明细及上年同期
  BEGIN
    INSERT INTO TJBB_DT_B03109 (SSNY,BBLC,SWJGDM,GBDM,HGMC,CKE_LJ,CKE_LJ_LAST)
    SELECT A.SSNY, CASE WHEN A.CKPM<9 THEN '0' ELSE '' END || (A.CKPM + 1), A.SWJGDM, A.GBDM, B.HGMC, A.CKE_LJ, C.CKE_LJ
      FROM TJBB_DT_B03109_MID A
     INNER JOIN DM_HGCODE B ON B.HGCODE=A.GBDM
      LEFT JOIN TJBB_DT_B03109_MID C ON C.SWJGDM=A.SWJGDM AND C.SSNY=LC_LASTMONTH AND C.GBDM=A.GBDM
     WHERE A.SWJGDM=V_SWCODE
       AND A.SSNY=LC_THISMONTH
       AND A.CKPM<=20;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --3、计算并插入合计数、其他数
  BEGIN
    SELECT ROUND(SUM(USD_AMT)/10000,0), ROUND(SUM(TS_AMT)/10000,0)
      INTO LN_CKE_HJ, LN_TSE_HJ
      FROM TL_TSSH.TJBB_FHXX_HGCODE
     WHERE SWCODE=V_SWCODE AND SSNY BETWEEN LC_THISYEAR AND LC_THISMONTH;

    SELECT ROUND(SUM(USD_AMT)/10000,0), ROUND(SUM(TS_AMT)/10000,0)
      INTO LN_CKE_LAST, LN_TSE_LAST
      FROM TL_TSSH.TJBB_FHXX_HGCODE
     WHERE SWCODE=V_SWCODE AND SSNY BETWEEN LC_LASTYEAR AND LC_LASTMONTH;

    SELECT LN_CKE_HJ - SUM(CKE_LJ), LN_CKE_LAST - SUM(CKE_LJ_LAST)
      INTO LN_CKE_OTHER, LN_CKE_OTHER_LAST
      FROM TJBB_DT_B03109
     WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    
    INSERT INTO TJBB_DT_B03109 (SSNY,BBLC,SWJGDM,GBDM,HGMC,CKE_LJ,CKE_LJ_LAST)
    SELECT LC_THISMONTH, '01', V_SWCODE, '', '合计', LN_CKE_HJ, LN_CKE_LAST
      FROM DUAL;
    COMMIT;
    
    INSERT INTO TJBB_DT_B03109 (SSNY,BBLC,SWJGDM,GBDM,HGMC,CKE_LJ,CKE_LJ_LAST)
    SELECT LC_THISMONTH, '22', V_SWCODE, '', '其他', LN_CKE_OTHER, LN_CKE_OTHER_LAST
      FROM DUAL;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  --4、同比计算
  BEGIN
    UPDATE TJBB_DT_B03109
       SET CKE_TB = CASE WHEN NVL(CKE_LJ_LAST,0)=0 THEN NULL ELSE ROUND(100 * CKE_LJ / CKE_LJ_LAST -100,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --5、占比计算
  BEGIN
    UPDATE TJBB_DT_B03109 T
       SET CKE_ZB = CASE WHEN NVL(LN_CKE_HJ,0)=0 THEN NULL ELSE ROUND(100 * CKE_LJ / LN_CKE_HJ,1) END
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;
  IF V_ERROR <> 0 THEN
    RETURN;
  END IF;

  --6、汇总栏初始化
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B03109 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B03109' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
