CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B07101_HZ_NEW
/*
 * 202210，新增
 * 列参考B01109，行参考B01100（将第39行提到11行，原11-38行依次下移一行）
 */
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY    IN  VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';

  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B07101 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;
  
  --1、计算非15行（按税局合计）
  BEGIN
    INSERT INTO TJBB_DT_B07101 (SWJGDM,SSNY,BBLC,
                RDHS,RDHS_HZ,SBHS,SBHS_HZ,
                SB_CKE_CUR,SB_CKE_CUR_HZ,SB_CKE_LAST,SB_CKE_LAST_HZ,
                SB_TMSE_CUR,SB_TMSE_CUR_HZ,SB_TMSE_LAST,SB_TMSE_LAST_HZ,
                SH_TMSE_CUR,SH_TMSE_CUR_HZ,SH_TMSE_LAST,SH_TMSE_LAST_HZ,
                SP_TMSE_CUR,SP_TMSE_CUR_HZ,SP_TMSE_LAST,SP_TMSE_LAST_HZ,
                TK_CUR,TK_CUR_HZ,TK_LAST,TK_LAST_HZ)
         SELECT V_SWCODE, LC_THISMONTH, BBLC,
                SUM(RDHS),SUM(RDHS_HZ),SUM(SBHS),SUM(SBHS_HZ),
                SUM(SB_CKE_CUR),SUM(SB_CKE_CUR_HZ),SUM(SB_CKE_LAST),SUM(SB_CKE_LAST_HZ),
                SUM(SB_TMSE_CUR),SUM(SB_TMSE_CUR_HZ),SUM(SB_TMSE_LAST),SUM(SB_TMSE_LAST_HZ),
                SUM(SH_TMSE_CUR),SUM(SH_TMSE_CUR_HZ),SUM(SH_TMSE_LAST),SUM(SH_TMSE_LAST_HZ),
                SUM(SP_TMSE_CUR),SUM(SP_TMSE_CUR_HZ),SUM(SP_TMSE_LAST),SUM(SP_TMSE_LAST_HZ),
                SUM(TK_CUR),SUM(TK_CUR_HZ),SUM(TK_LAST),SUM(TK_LAST_HZ)
           FROM TJBB_DT_B07101 T
          WHERE T.SWJGDM IN (SELECT SWJG_DM FROM TABLE(TL_ADMIN.FUNC_GET_XJ_SWJG(V_SWCODE)))
            AND T.SSNY = LC_THISMONTH
            AND T.BBLC <> '15'
          GROUP BY BBLC;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --2、计算15行
  BEGIN
    INSERT INTO TJBB_DT_B07101 (SWJGDM,SSNY,BBLC,
                RDHS,RDHS_HZ,SBHS,SBHS_HZ,
                SB_CKE_CUR,SB_CKE_CUR_HZ,SB_CKE_LAST,SB_CKE_LAST_HZ,
                SB_TMSE_CUR,SB_TMSE_CUR_HZ,SB_TMSE_LAST,SB_TMSE_LAST_HZ,
                SH_TMSE_CUR,SH_TMSE_CUR_HZ,SH_TMSE_LAST,SH_TMSE_LAST_HZ,
                SP_TMSE_CUR,SP_TMSE_CUR_HZ,SP_TMSE_LAST,SP_TMSE_LAST_HZ,
                TK_CUR,TK_CUR_HZ,TK_LAST,TK_LAST_HZ)
         SELECT V_SWCODE, LC_THISMONTH, '15', 
                NULL, NULL, NULL, NULL, 
                NULL, NULL, NULL, NULL, 
                CASE WHEN B.SB_TMSE_CUR=0 THEN 0 ELSE 100 * A.SB_TMSE_CUR/B.SB_TMSE_CUR END,
                CASE WHEN B.SB_TMSE_CUR_HZ=0 THEN 0 ELSE 100 * A.SB_TMSE_CUR_HZ/B.SB_TMSE_CUR_HZ END,
                CASE WHEN B.SB_TMSE_LAST=0 THEN 0 ELSE 100 * A.SB_TMSE_LAST/B.SB_TMSE_LAST END,
                CASE WHEN B.SB_TMSE_LAST_HZ=0 THEN 0 ELSE 100 * A.SB_TMSE_LAST_HZ/B.SB_TMSE_LAST_HZ END,
                CASE WHEN B.SH_TMSE_CUR=0 THEN 0 ELSE 100 * A.SH_TMSE_CUR/B.SH_TMSE_CUR END,
                CASE WHEN B.SH_TMSE_CUR_HZ=0 THEN 0 ELSE 100 * A.SH_TMSE_CUR_HZ/B.SH_TMSE_CUR_HZ END,
                CASE WHEN B.SH_TMSE_LAST=0 THEN 0 ELSE 100 * A.SH_TMSE_LAST/B.SH_TMSE_LAST END,
                CASE WHEN B.SH_TMSE_LAST_HZ=0 THEN 0 ELSE 100 * A.SH_TMSE_LAST_HZ/B.SH_TMSE_LAST_HZ END,
                CASE WHEN B.SP_TMSE_CUR=0 THEN 0 ELSE 100 * A.SP_TMSE_CUR/B.SP_TMSE_CUR END,
                CASE WHEN B.SP_TMSE_CUR_HZ=0 THEN 0 ELSE 100 * A.SP_TMSE_CUR_HZ/B.SP_TMSE_CUR_HZ END,
                CASE WHEN B.SP_TMSE_LAST=0 THEN 0 ELSE 100 * A.SP_TMSE_LAST/B.SP_TMSE_LAST END,
                CASE WHEN B.SP_TMSE_LAST_HZ=0 THEN 0 ELSE 100 * A.SP_TMSE_LAST_HZ/B.SP_TMSE_LAST_HZ END,
                CASE WHEN B.TK_CUR=0 THEN 0 ELSE 100 * A.TK_CUR/B.TK_CUR END,
                CASE WHEN B.TK_CUR_HZ=0 THEN 0 ELSE 100 * A.TK_CUR_HZ/B.TK_CUR_HZ END,
                CASE WHEN B.TK_LAST=0 THEN 0 ELSE 100 * A.TK_LAST/B.TK_LAST END,
                CASE WHEN B.TK_LAST_HZ=0 THEN 0 ELSE 100 * A.TK_LAST_HZ/B.TK_LAST_HZ END
      FROM TJBB_DT_B07101 A,
           TJBB_DT_B07101 B
     WHERE A.SWJGDM=V_SWCODE
       AND A.SSNY=LC_THISMONTH
       AND A.BBLC='13'
       AND B.SWJGDM=V_SWCODE
       AND B.SSNY=LC_THISMONTH
       AND B.BBLC='14';
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --3、更新占比、同比列
  BEGIN
    UPDATE TJBB_DT_B07101 T
       SET RD_SB_LV        = CASE WHEN T.RDHS=0            THEN 0 ELSE 100 * T.SBHS           /T.RDHS                 END,
           RD_SB_LV_HZ     = CASE WHEN T.RDHS_HZ=0         THEN 0 ELSE 100 * T.SBHS_HZ        /T.RDHS_HZ              END,
           SB_CKE_TBLV     = CASE WHEN T.SB_CKE_LAST=0     THEN 0 ELSE 100 * T.SB_CKE_CUR     /T.SB_CKE_LAST -100     END,
           SB_CKE_TBLV_HZ  = CASE WHEN T.SB_CKE_LAST_HZ=0  THEN 0 ELSE 100 * T.SB_CKE_CUR_HZ  /T.SB_CKE_LAST_HZ -100  END,
           SB_TMSE_TBLV    = CASE WHEN T.SB_TMSE_LAST=0    THEN 0 ELSE 100 * T.SB_TMSE_CUR    /T.SB_TMSE_LAST -100    END,
           SB_TMSE_TBLV_HZ = CASE WHEN T.SB_TMSE_LAST_HZ=0 THEN 0 ELSE 100 * T.SB_TMSE_CUR_HZ /T.SB_TMSE_LAST_HZ -100 END,
           SH_TMSE_TBLV    = CASE WHEN T.SH_TMSE_LAST=0    THEN 0 ELSE 100 * T.SH_TMSE_CUR    /T.SH_TMSE_LAST -100    END,
           SH_TMSE_TBLV_HZ = CASE WHEN T.SH_TMSE_LAST_HZ=0 THEN 0 ELSE 100 * T.SH_TMSE_CUR_HZ /T.SH_TMSE_LAST_HZ -100 END,
           SP_TMSE_TBLV    = CASE WHEN T.SP_TMSE_LAST=0    THEN 0 ELSE 100 * T.SP_TMSE_CUR    /T.SP_TMSE_LAST -100    END,
           SP_TMSE_TBLV_HZ = CASE WHEN T.SP_TMSE_LAST_HZ=0 THEN 0 ELSE 100 * T.SP_TMSE_CUR_HZ /T.SP_TMSE_LAST_HZ -100 END,
           TK_TBLV         = CASE WHEN T.TK_LAST=0         THEN 0 ELSE 100 * T.TK_CUR         /T.TK_LAST -100         END,
           TK_TBLV_HZ      = CASE WHEN T.TK_LAST_HZ=0      THEN 0 ELSE 100 * T.TK_CUR_HZ      /T.TK_LAST_HZ -100      END
     WHERE T.SWJGDM=V_SWCODE
       AND T.SSNY=LC_THISMONTH
       AND T.BBLC<>'15';
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  RETURN;
END;
/
