CREATE OR REPLACE PROCEDURE PRO_TJBB_B02_CSH
/*
 * 总局专项报表，区县局初始化
 * 需要指定区县级税务机关和报表所属期
 */
(
  LC_SWJGDM  IN  VARCHAR2,
  LC_MONTH    IN  VARCHAR2
)
AS
  LN_ERROR         NUMBER;
  LC_MSG           VARCHAR2(2000);
BEGIN
  --按报表顺序依次制表
  BEGIN
    PRO_TJBB_DT_B02101_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02101_CSH_NEW！'||LC_SWJGDM);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02101_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
      COMMIT;
  END;
  BEGIN
    PRO_TJBB_DT_B02102_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02102_CSH_NEW！'||LC_SWJGDM);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02102_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
      COMMIT;
  END;
  BEGIN
    PRO_TJBB_DT_B02103_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02103_CSH_NEW！'||LC_SWJGDM);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02103_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
      COMMIT;
  END;
  BEGIN
    PRO_TJBB_DT_B02104_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02104_CSH_NEW！'||LC_SWJGDM);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02104_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
      COMMIT;
  END;
  BEGIN
    PRO_TJBB_DT_B02105_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02105_CSH_NEW！'||LC_SWJGDM);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02105_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
      COMMIT;
  END;
  BEGIN
    PRO_TJBB_DT_B02106_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02106_CSH_NEW！'||LC_SWJGDM);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02106_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
      COMMIT;
  END;
  BEGIN
    PRO_TJBB_DT_B02107_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02107_CSH_NEW！'||LC_SWJGDM);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02107_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
      COMMIT;
  END;
  BEGIN
    PRO_TJBB_DT_B02108_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02108_CSH_NEW！'||LC_SWJGDM);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02108_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
      COMMIT;
  END;
  BEGIN
    PRO_TJBB_DT_B02109_CSH_NEW(LC_SWJGDM,LC_MONTH,LN_ERROR,LC_MSG);
    INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_TJBB_DT_B02109_CSH_NEW！'||LC_SWJGDM);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      INSERT INTO TL_TSSH.CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('执行PRO_TJBB_DT_B02109_CSH_NEW失败，税务机关：'||LC_SWJGDM, LC_MSG);
      COMMIT;
  END;

END;
/
