CREATE OR REPLACE PROCEDURE PRO_TJBB_CSH_ONESWJG
/*
 * 单一局，所有报表重置
 */
(
  LC_SWJGDM  IN  VARCHAR2,
	V_SSNY     IN  VARCHAR2
)
AS
  LC_MONTH         VARCHAR2(6);
BEGIN
  IF V_SSNY IS NOT NULL THEN
    LC_MONTH :=V_SSNY;
  ELSE
    LC_MONTH:= TO_CHAR(ADD_MONTHS(SYSDATE,-1),'YYYYMM');
  END IF;

  --按报表顺序依次制表
  PRO_TJBB_B01_CSH(LC_SWJGDM,LC_MONTH);
  PRO_TJBB_B02_CSH(LC_SWJGDM,LC_MONTH);
  PRO_TJBB_B04_CSH(LC_SWJGDM,LC_MONTH);
  PRO_TJBB_B05_CSH(LC_SWJGDM,LC_MONTH);
  PRO_TJBB_B06_CSH(LC_SWJGDM,LC_MONTH);

  IF SUBSTR(LC_SWJGDM,-6)='000000' THEN
    PRO_TJBB_B03_HZ(LC_SWJGDM,LC_MONTH);
    PRO_TJBB_B07_HZ(LC_SWJGDM,LC_MONTH);
  ELSE
    PRO_TJBB_B03_CSH(LC_SWJGDM,LC_MONTH);
    PRO_TJBB_B07_CSH(LC_SWJGDM,LC_MONTH);
  END IF;

END;
/
