CREATE OR REPLACE PROCEDURE PRO_TJBB_DT_B02105_CSH_NEW
/*************************************************
 * 特殊政策退（免）税季度统计表
 ************************************************/
(
  V_SWCODE  IN  VARCHAR2,
  V_SSNY    IN  VARCHAR2,
  V_ERROR   OUT NUMBER,
  V_MSG     OUT VARCHAR2
)
AS
  LD_SYSDATE       DATE;
  LC_THISMONTH     VARCHAR2(6);
  LD_THISYEAR      DATE;
  LD_NEXTMONTH     DATE;

  LN_SBHS          NUMBER(10);
  LN_SB_CKE_HIS    NUMBER(18,6);
  LN_SB_CKE_CUR    NUMBER(18,6);

  LN_SB_ZZS_HIS    NUMBER(18,6);
  LN_SB_ZZS_CUR    NUMBER(18,6);
  LN_SH_ZZS_HIS    NUMBER(18,6);
  LN_SH_ZZS_CUR    NUMBER(18,6);
  LN_BY_ZZS_HIS    NUMBER(18,6);
  LN_BY_ZZS_CUR    NUMBER(18,6);
  LN_ZT_ZZS_HIS    NUMBER(18,6);
  LN_ZT_ZZS_CUR    NUMBER(18,6);

  LN_SB_XFS_HIS    NUMBER(18,6);
  LN_SB_XFS_CUR    NUMBER(18,6);
  LN_SH_XFS_HIS    NUMBER(18,6);
  LN_SH_XFS_CUR    NUMBER(18,6);
  LN_BY_XFS_HIS    NUMBER(18,6);
  LN_BY_XFS_CUR    NUMBER(18,6);
  LN_ZT_XFS_HIS    NUMBER(18,6);
  LN_ZT_XFS_CUR    NUMBER(18,6);
  LC_SQL_INSERT    VARCHAR2(4000);
  LC_SQL_UPDATEHZ  VARCHAR2(4000);
BEGIN
  V_ERROR :=0;
  V_MSG   := ' ';
  
  IF V_SSNY IS NOT NULL THEN
    LD_SYSDATE:=TO_DATE(V_SSNY||'01','YYYYMMDD');
  ELSE
    LD_SYSDATE:=TRUNC(SYSDATE,'MM');
  END IF;
  LC_THISMONTH :=TO_CHAR(LD_SYSDATE,'YYYYMM');
  LD_THISYEAR  :=TRUNC(LD_SYSDATE,'YY');
  LD_NEXTMONTH :=TRUNC(ADD_MONTHS(LD_SYSDATE,1),'MM');

  --0、清除原有制表数据，准备重新制表
  BEGIN
    DELETE FROM TJBB_DT_B02105 WHERE SWJGDM=V_SWCODE AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  BEGIN
    --1.1 外轮供应、外航供应、远洋运输供应公司
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MTSBZ,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.TSE   * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS TSE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%WL%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '01', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
           FROM DUAL;
      COMMIT;
    END;
         
    --1.2 出境口岸免税店
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MTSBZ,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.TSE   * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS TSE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_MTS_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%MSD%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '02', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
           FROM DUAL;
      COMMIT;
    END;

    --1.4 中标机电产品
     BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END),0)/10000,6), --申报免抵退税额
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END),0)/10000,6), --申报
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END),0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR,
             LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MDTSNY,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END) 
                               END --根据是否复审用申报数或复审数计算退税部分
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_ZZSTSE=0 THEN 1 
                                    WHEN A.SNBL_ZZSTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE 
                               END AS TSE,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_MDSE/A.ZY_MDTSE END) 
                               END
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDSE=0 THEN 1 
                                    WHEN A.SNBL_MDSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDSE / A.ZY_MDSE 
                               END AS MDE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_MDT_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%ZB%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '04', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
           FROM DUAL
          UNION ALL
         SELECT LC_THISMONTH, '05', V_SWCODE, 0, 
                0, 0, LN_SB_XFS_HIS, LN_SB_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
           FROM DUAL;
      COMMIT;
    END;

    --1.6 外商投资企业采购国产设备
     BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 0, 0,
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='N' THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='N' THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.KPRQ AS CKRQ_1,B.BYTSBZ,C.LCSLID_FS,
                     B.TSE   * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS TSE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_GJ_SBMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH IN ('WZYFJG','GCSB')
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               INNER JOIN TL_TSSH.GLXT_BB_SHXT_DJXX D ON D.DJXH_JS=A.DJXH AND D.QYLX='2'
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '06', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
           FROM DUAL;
      COMMIT;
    END;

    --1.7 使（领）馆购买国产物品
    BEGIN
      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '07', V_SWCODE, 0, 
                0, 0, 0, 0, 
                0, 0, 0, 0, 0, 0, 
                0, 0, 0, 0, 0
           FROM DUAL;
      COMMIT;
    END;

    --1.9 对外承包工程
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END),0)/10000,6), --申报免抵退税额
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END),0)/10000,6), --申报
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END),0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR,
             LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MDTSNY,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END) 
                               END --根据是否复审用申报数或复审数计算退税部分
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_ZZSTSE=0 THEN 1 
                                    WHEN A.SNBL_ZZSTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE 
                               END AS TSE,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_MDSE/A.ZY_MDTSE END) 
                               END
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDSE=0 THEN 1 
                                    WHEN A.SNBL_MDSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDSE / A.ZY_MDSE 
                               END AS MDE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_MDT_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%DWCB%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '09', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
           FROM DUAL
          UNION ALL
         SELECT LC_THISMONTH, '10', V_SWCODE, 0, 
                0, 0, LN_SB_XFS_HIS, LN_SB_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
           FROM DUAL;
      COMMIT;
    END;

    --1.12 对外修理修配
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END),0)/10000,6), --申报免抵退税额
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END),0)/10000,6), --申报
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END),0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR,
             LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MDTSNY,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END) 
                               END --根据是否复审用申报数或复审数计算退税部分
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_ZZSTSE=0 THEN 1 
                                    WHEN A.SNBL_ZZSTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE 
                               END AS TSE,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_MDSE/A.ZY_MDTSE END) 
                               END
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDSE=0 THEN 1 
                                    WHEN A.SNBL_MDSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDSE / A.ZY_MDSE 
                               END AS MDE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_MDT_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%XLXP%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '12', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
           FROM DUAL
          UNION ALL
         SELECT LC_THISMONTH, '13', V_SWCODE, 0, 
                0, 0, LN_SB_XFS_HIS, LN_SB_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
           FROM DUAL;
      COMMIT;
    END;

    --1.15 境外投资
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MYLAJ ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.MDE ELSE 0 END),0)/10000,6), --申报免抵退税额
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.MDE ELSE 0 END),0)/10000,6), --申报
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.MDE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.MDTSNY IS NOT NULL THEN T.MDE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.MDE ELSE 0 END),0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR,
             LN_SB_XFS_HIS, LN_SB_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.CKRQ_1,B.MDTSNY,B.BYTSBZ,C.LCSLID_FS,
                     B.MYLAJ * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS MYLAJ,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 1 ELSE A.SB_ZZSTSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 1 ELSE A.ZY_ZZSTSE/A.ZY_MDTSE END) 
                               END --根据是否复审用申报数或复审数计算退税部分
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_ZZSTSE=0 THEN 1 
                                    WHEN A.SNBL_ZZSTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_ZZSTSE / A.ZY_ZZSTSE 
                               END AS TSE,
                     B.MDTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN (CASE WHEN A.SB_MDTSE=0 THEN 0 ELSE A.SB_MDSE/A.SB_MDTSE END)
                                                             ELSE (CASE WHEN A.ZY_MDTSE=0 THEN 0 ELSE A.ZY_MDSE/A.ZY_MDTSE END) 
                               END
                             * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDSE=0 THEN 1 
                                    WHEN A.SNBL_MDSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDSE / A.ZY_MDSE 
                               END AS MDE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_MDT_CKMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N' AND B.CKTMSYWLXDMJH LIKE '%JWTZ%'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '15', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
           FROM DUAL
          UNION ALL
         SELECT LC_THISMONTH, '16', V_SWCODE, 0, 
                0, 0, LN_SB_XFS_HIS, LN_SB_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_BY_XFS_HIS, LN_BY_XFS_CUR, LN_ZT_XFS_HIS, LN_ZT_XFS_CUR, 
                LN_SH_XFS_HIS, LN_SH_XFS_CUR, LN_SH_XFS_HIS + LN_SH_XFS_CUR, LN_SH_XFS_HIS, LN_SH_XFS_CUR
           FROM DUAL;
      COMMIT;
    END;

    --1.18 其他
    BEGIN
      --申报户数、申报出口额
      SELECT COUNT(DISTINCT T.DJXH), 0, 0,
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6), 
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR THEN T.TSE ELSE 0 END),0)/10000,6),
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NULL THEN T.TSE ELSE 0 END),0)/10000,6), --在途
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='N' THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='N' THEN T.TSE ELSE 0 END),0)/10000,6), --准予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1< LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6), --不予
             ROUND(NVL(SUM(CASE WHEN T.CKRQ_1>=LD_THISYEAR AND TRIM(T.LCSLID_FS) IS NOT NULL AND T.BYTSBZ='Y' THEN T.TSE ELSE 0 END),0)/10000,6) --不予
        INTO LN_SBHS, LN_SB_CKE_HIS, LN_SB_CKE_CUR, 
             LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR
        FROM (SELECT B.DJXH,B.LCSLID,B.SBXH,B.KPRQ AS CKRQ_1,B.BYTSBZ,C.LCSLID_FS,
                     B.TSE   * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                    WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                    ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                               END AS TSE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_GJ_SBMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               INNER JOIN TL_TSSH.GLXT_BB_SHXT_DJXX D ON D.DJXH_JS=A.DJXH
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR
                 AND ((B.CKTMSYWLXDMJH IN ('SDQ',' NZYFJG')) OR (B.CKTMSYWLXDMJH='GCSB' AND D.QYLX<>'2'))
               UNION ALL
              SELECT B.DJXH,B.LCSLID,B.SBXH,B.KPRQ AS CKRQ_1,B.BYTSBZ,C.LCSLID_FS,
                     B.XFSTSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                     WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                     ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                                END AS TSE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_FZC_SBMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               INNER JOIN TL_TSSH.GLXT_BB_SHXT_DJXX D ON D.DJXH_JS=A.DJXH
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR
               UNION ALL
              SELECT B.DJXH,B.LCSLID,B.SBXH,B.KPRQ AS CKRQ_1,B.BYTSBZ,C.LCSLID_FS,
                     B.TSE * CASE WHEN TRIM(C.LCSLID_FS) IS NULL THEN 1  
                                    WHEN A.SNBL_MDTSE=0 THEN 1
                                     WHEN A.SNBL_MDTSE>0 AND B.BYTSBZ='Y' THEN 0
                                     ELSE 1 - A.SNBL_MDTSE / A.ZY_MDTSE 
                                END AS TSE
                FROM TL_TSSH.CKTS_LC_SHXX A
               INNER JOIN TL_TSSH.CKTS_SB_YS_SBMX B ON B.LCSLID=A.LCSLID AND B.CHBZ='N'
                LEFT JOIN (SELECT DISTINCT LCSLID_FS FROM TL_TSSH.CKTS_LC_YWHZXX S) C ON C.LCSLID_FS=A.LCSLID_FS
               INNER JOIN TL_TSSH.GLXT_BB_SHXT_DJXX D ON D.DJXH_JS=A.DJXH
               WHERE A.TSSWJG_DM=V_SWCODE
                 AND A.QDSJ<LD_NEXTMONTH
                 AND A.LCJSRQ>=LD_THISYEAR
                 ) T;

      INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, 
                SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, 
                SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, 
                SPTK_TKE_HIS,   SPTK_TKE_YEAR, YSGK_TKE, GKBL_TKE_HIS,   GKBL_TKE_YEAR)
         SELECT LC_THISMONTH, '18', V_SWCODE, LN_SBHS, 
                LN_SB_CKE_HIS, LN_SB_CKE_CUR, LN_SB_ZZS_HIS, LN_SB_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_BY_ZZS_HIS, LN_BY_ZZS_CUR, LN_ZT_ZZS_HIS, LN_ZT_ZZS_CUR, 
                LN_SH_ZZS_HIS, LN_SH_ZZS_CUR, LN_SH_ZZS_HIS + LN_SH_ZZS_CUR, LN_SH_ZZS_HIS, LN_SH_ZZS_CUR
           FROM DUAL
          UNION ALL
         SELECT LC_THISMONTH, '19', V_SWCODE, 0, 
                0, 0, 0, 0, 
                0, 0, 0, 0, 0, 0, 
                0, 0, 0, 0, 0
           FROM DUAL;
      COMMIT;
    END;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --10、计算行
  LC_SQL_INSERT:= 
      'INSERT INTO TJBB_DT_B02105 (SSNY, BBLC, SWJGDM, SBHS, ' ||
              'SBLJ_TSCKE_HIS, SBLJ_TSCKE_YEAR, ' ||
              'SBLJ_TMSE_HIS,  SBLJ_TMSE_YEAR, ' ||
              'SHLJ_TMSE_HIS,  SHLJ_TMSE_YEAR, ' ||
              'SHBY_TMSE_HIS,  SHBY_TMSE_YEAR, ' ||
              'SHZT_TMSE_HIS,  SHZT_TMSE_YEAR, ' ||
              'SPTK_TKE_HIS,   SPTK_TKE_YEAR, ' ||
              'YSGK_TKE, ' ||
              'GKBL_TKE_HIS,   GKBL_TKE_YEAR) ' ||
      'SELECT :1, :2 AS BBLC, :3 AS SWJGDM, SUM(SBHS), ' ||
              'SUM(SBLJ_TSCKE_HIS), SUM(SBLJ_TSCKE_YEAR), ' ||
              'SUM(SBLJ_TMSE_HIS),  SUM(SBLJ_TMSE_YEAR), ' ||
              'SUM(SHLJ_TMSE_HIS),  SUM(SHLJ_TMSE_YEAR), ' ||
              'SUM(SHBY_TMSE_HIS),  SUM(SHBY_TMSE_YEAR), ' ||
              'SUM(SHZT_TMSE_HIS),  SUM(SHZT_TMSE_YEAR), ' ||
              'SUM(SPTK_TKE_HIS),   SUM(SPTK_TKE_YEAR), ' ||
              'SUM(YSGK_TKE), ' ||
              'SUM(GKBL_TKE_HIS),   SUM(GKBL_TKE_YEAR) ' ||
        'FROM TJBB_DT_B02105 ' ||
       'WHERE SWJGDM=:4 ' ||
         'AND SSNY=:5 ' ||
         'AND TRIM(TO_CHAR(TO_NUMBER(BBLC))) IN ';

  BEGIN
    FOR LSF_XX IN (SELECT TRIM(TO_CHAR(SUBSTR(T.FORMULA,2,INSTR(T.FORMULA,')')-2),'00')) AS BBLC,
                          '('||REPLACE(REPLACE(REPLACE(SUBSTR(T.FORMULA,INSTR(T.FORMULA,'=')+1),'(',''''),'+',','),')','''')||')' AS BBCS
                     FROM TJBB_REPORT_FORMULA T
                    WHERE T.BBDM='B02105'
                      AND T.TYPE=2
                    ORDER BY T.YXJ)
    LOOP
      BEGIN
        EXECUTE IMMEDIATE LC_SQL_INSERT || LSF_XX.BBCS
          USING LC_THISMONTH, LSF_XX.BBLC, V_SWCODE, V_SWCODE, LC_THISMONTH;
        COMMIT;
      END;
    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
  END;

  --10、更新小计列
  BEGIN
    UPDATE TJBB_DT_B02105
       SET SB_TSCKE_XJ  = SBLJ_TSCKE_HIS + SBLJ_TSCKE_YEAR,
           SB_TMSE_XJ   = SBLJ_TMSE_HIS  + SBLJ_TMSE_YEAR,
           SH_TMSE_XJ   = SHLJ_TMSE_HIS  + SHLJ_TMSE_YEAR,
           SHBY_TMSE_XJ = SHBY_TMSE_HIS  + SHBY_TMSE_YEAR,
           SHZT_TMSE_XJ = SHZT_TMSE_HIS  + SHZT_TMSE_YEAR,
           SPTK_TKE_XJ  = SPTK_TKE_HIS   + SPTK_TKE_YEAR,
           GKBL_TKE_XJ  = GKBL_TKE_HIS   + GKBL_TKE_YEAR,
           ZT_TKE       = YSGK_TKE - GKBL_TKE_HIS - GKBL_TKE_YEAR
     WHERE SWJGDM=V_SWCODE
       AND SSNY=LC_THISMONTH;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  --11、更新汇总列
  BEGIN
    LC_SQL_UPDATEHZ := 'UPDATE TJBB_DT_B02105 SET ';

    FOR LSF_XX IN (SELECT FNAME FROM TJBB_HEADER_COLS WHERE BBDM='B02105' AND FTYPE='NUMBER' ORDER BY SHOWORDER)
    LOOP
      LC_SQL_UPDATEHZ := LC_SQL_UPDATEHZ || LSF_XX.FNAME || '_HZ=' || LSF_XX.FNAME || ', ';
    END LOOP;

    LC_SQL_UPDATEHZ := SUBSTR(LC_SQL_UPDATEHZ, 1, LENGTH(LC_SQL_UPDATEHZ)-2) ||
                       ' WHERE SWJGDM=''' || V_SWCODE || ''' AND SSNY=''' || LC_THISMONTH || '''';

    EXECUTE IMMEDIATE LC_SQL_UPDATEHZ;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := SQLCODE;
      V_MSG   := SQLERRM;
      RETURN;
  END;

  RETURN;
END;
/
