CREATE OR REPLACE FUNCTION F_GZR_BETWEEN(IN_RQ_Z DATE,IN_RQ_Q DATE)
RETURN  NUMBER
IS
  GZR_DAYS NUMBER;
BEGIN
  WITH V_RQ AS
  (SELECT IN_RQ_Q AS RQ_Q,
          IN_RQ_Z AS RQ_Z
     FROM DUAL)
  SELECT R.RQ_Z
         - R.RQ_Q
         - COALESCE(SUM(J1.JJRZZRQ - J1.JJRQSRQ + 1), 0)
         - COALESCE(J2.JJRZZRQ - R.RQ_Q + 1, 0)
         - COALESCE(R.RQ_Z - J3.JJRQSRQ + 1, 0)
         INTO GZR_DAYS
  FROM V_RQ R
  LEFT JOIN HX_CS_ZDY.CS_GY_JJR J1 ON J1.JJRQSRQ >= R.RQ_Q AND J1.JJRZZRQ <= R.RQ_Z
  LEFT JOIN HX_CS_ZDY.CS_GY_JJR J2 ON J2.JJRQSRQ <= R.RQ_Q AND J2.JJRZZRQ >= R.RQ_Q
  LEFT JOIN HX_CS_ZDY.CS_GY_JJR J3 ON J3.JJRQSRQ <= R.RQ_Z AND J3.JJRZZRQ >= R.RQ_Z
  GROUP BY R.RQ_Q,R.RQ_Z,J2.JJRZZRQ,J3.JJRQSRQ
  ;

RETURN GZR_DAYS;
END ;
/
