CREATE OR REPLACE PROCEDURE PRO_DEAL_CKTS_HD_JJYQ
/*
 * 即将逾期函调复函数据提取
 * 20250422，根据杭州市局王薇逾期回函内控指标的建议，调整即将逾期的条件
 * 20260817，根据绍兴市局陈弯弯当天到期未提醒的问题，调整截止日大于等于当前日期的条件
 */
AS
BEGIN
  -- 函调回函
  EXECUTE IMMEDIATE 'TRUNCATE TABLE CKTS_HD_JJYQ';
  COMMIT;

  INSERT INTO CKTS_HD_JJYQ(FHXXBUUID,GHFZGSWJG_DM,GHFZGSWJGMC,GHFDJXH1,GHQYNSRSBH_1,GHFQYMC_1,FAHDSWJGMC,WSBH,FPFS,JSHJ,QFRQ,FUHJZRQ,YQRQ_1,YQFHYY,YQCS)
       SELECT FHXXBUUID,GHFZGSWJG_DM,GHFZGSWJGMC,GHFDJXH1,GHQYNSRSBH_1,GHFQYMC_1,FAHDSWJGMC,WSBH,FPFS,JSHJ,QFRQ,FUHJZRQ,YQRQ_1,YQFHYY,YQCS
         FROM (SELECT F1.FHXXBUUID,F1.GHFZGSWJG_DM,F1.GHFZGSWJGMC,F1.GHFDJXH1,F1.GHQYNSRSBH_1,F1.GHFQYMC_1,F1.FAHDSWJGMC,
                      F1.WSBH,F1.FPFS,F1.JSHJ,F1.QFRQ,F1.FUHJZRQ,H1.QFRQ AS QFRQ_H,H1.YQRQ_1,H1.YQFHYY,
                      CASE WHEN H1.YQRQ_1 IS NULL THEN 0 ELSE ROW_NUMBER() OVER(PARTITION BY F1.FHXXBUUID ORDER BY H1.QFRQ) END AS YQCS,
                      NVL(H1.QFRQ,F1.QFRQ) AS RQQ,NVL(H1.YQRQ_1,F1.FUHJZRQ) AS RQZ,
                      ROW_NUMBER() OVER(PARTITION BY F1.FHXXBUUID ORDER BY H1.YQRQ_1 DESC, H1.FUHXXBUUID) AS RN
                 FROM HX_ZH.ZH_CKTS_FHXXB F1
                 LEFT JOIN HX_ZH.ZH_CKTS_FUHXXB H1 ON H1.FHXXBUUID = F1.FHXXBUUID
                                                   AND NVL(H1.ZFBZ_1,'N') = 'N'
                                                   AND NVL(H1.FHLX_DM,'3') = '3'
                                                   AND H1.FHBH IS NOT NULL
                WHERE F1.ZFBZ_1 = 'N'
                  AND F1.GHFZGSWJG_DM LIKE '133%' AND F1.GHFZGSWJG_DM NOT LIKE '13302%') F
        WHERE RN=1
          AND F.RQZ>=TRUNC(SYSDATE) AND COMPUTE_BLDATE(F.RQZ,SYSDATE)<=3 --未到期且到期日小于3个工作日，不包括已到期数据
          AND NOT EXISTS (SELECT 1
                            FROM HX_ZH.ZH_CKTS_FUHXXB H
                           WHERE H.FHXXBUUID = F.FHXXBUUID
                             AND H.FHBH IS NOT NULL
                             AND H.ZFBZ_1 = 'N'
                             AND H.QFRQ>F.RQQ
                             AND H.QFRQ<F.RQZ);
  COMMIT;

  RETURN;
END;
/
