CREATE OR REPLACE PROCEDURE PRO_DEAL_FXGL_FZPCKQY
/*
 * 纺织品出口企业风险指标提取过程
 */
(
  P_FXYEAR  IN VARCHAR2 --分析年度
)
AS
  LC_FXYEAR  CHAR(4);
  LD_FXRQQ   DATE; --分析期起
  LD_FXRQZ   DATE; --分析期止
  LD_SSQQ    DATE; --财务报表所属期起

  LN_CK_ZL_CD   NUMBER(16,4);
  LN_CK_CD_ZL   NUMBER(16,4);
  LN_CK_ZL_SL   NUMBER(16,4);
  LN_CK_SL_ZL   NUMBER(16,4);
  LN_CK_ZL_ALL  NUMBER(16,4);
  LN_CK_RMB     NUMBER(18,2);

  LN_QBXSSR     NUMBER(18,2);
  LN_CH_QCYE    NUMBER(18,2);
  LN_CH_QMYE    NUMBER(18,2);

BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE FXGL_DATA_FZPCKQY';
  COMMIT;

  -- 按年分析，因涉及财务报表，分析期止不能大于上一季度末
  IF (TRIM(P_FXYEAR) IS NULL) OR (LENGTH(TRIM(P_FXYEAR))!=4) OR
    (TRIM(P_FXYEAR)<'2019') OR (TRIM(P_FXYEAR)>TO_CHAR(ADD_MONTHS(SYSDATE,-4),'YYYY')) THEN
    LC_FXYEAR := TO_CHAR(ADD_MONTHS(SYSDATE,-4),'YYYY');
  ELSE
    LC_FXYEAR := TRIM(P_FXYEAR);
  END IF;
  LD_FXRQQ := TO_DATE(LC_FXYEAR||'-01-01','YYYY-MM-DD');
  LD_FXRQZ := TO_DATE(LC_FXYEAR||'-12-31','YYYY-MM-DD');
  IF LD_FXRQZ > TRUNC(SYSDATE,'Q') THEN
    LD_FXRQZ := TRUNC(SYSDATE,'Q') - 1;
  END IF;
  LD_SSQQ := TRUNC(LD_FXRQZ,'Q');

  -- 插入分析期内有纺织品出口的企业名单及出口统计数据
  INSERT INTO FXGL_DATA_FZPCKQY(DJXH,CK_RMB,CK_MY,CK_ZL_CD,CK_CD_ZL,CK_ZL_SL,CK_SL_ZL,CK_ZL_ALL,CK_FZP)
  SELECT BGD.DJXH,SUM(BGD.RMBLAJ),SUM(BGD.MYLAJ),
         SUM(CASE
             WHEN BGD.DYJLDW_DM = '09' AND BGD.DEJLDW_DM='04' THEN
               BGD.CKSL
             WHEN BGD.DEJLDW_DM = '09' AND BGD.DYJLDW_DM='04' THEN
               BGD.DECKSL
             ELSE
               0
             END) AS CK_ZL_CD,
         SUM(CASE
             WHEN BGD.DYJLDW_DM = '09' AND BGD.DEJLDW_DM='04' THEN
               BGD.DECKSL
             WHEN BGD.DEJLDW_DM = '09' AND BGD.DYJLDW_DM='04' THEN
               BGD.CKSL
             ELSE
               0
             END)  AS CK_CD_ZL,
         SUM(CASE
             WHEN BGD.DYJLDW_DM = '09' AND BGD.DEJLDW_DM='01' THEN
               BGD.CKSL
             WHEN BGD.DEJLDW_DM = '09' AND BGD.DYJLDW_DM='01' THEN
               BGD.DECKSL
             ELSE
               0
             END)  AS CK_ZL_SL,
         SUM(CASE
             WHEN BGD.DYJLDW_DM = '09' AND BGD.DEJLDW_DM='01' THEN
               BGD.DECKSL
             WHEN BGD.DEJLDW_DM = '09' AND BGD.DYJLDW_DM='01' THEN
               BGD.CKSL
             ELSE
               0
             END)  AS CK_SL_ZL,
         SUM(CASE
             WHEN BGD.DYJLDW_DM = '09'  THEN
               BGD.CKSL
             WHEN BGD.DEJLDW_DM = '09'  THEN
               BGD.DECKSL
             ELSE
               0
             END)  AS CK_ZL_ALL,
         SUM(CASE
             WHEN BGD.JGFS_DM IN (SELECT JGFS_DM FROM HX_DM_ZDY.DM_CKTS_HGJGFS WHERE JGFSTSLX_DM = '1') THEN
               BGD.RMBLAJ
             ELSE
               0
             END) AS CK_FZP
    FROM HX_CKTS.CKTS_WBSJ_HG_BGD201 BGD
   WHERE BGD.CKRQ_1 >= LD_FXRQQ
     AND BGD.CKRQ_1 <= LD_FXRQZ
     AND SUBSTR(BGD.CKSP_DM, 1, 2) BETWEEN '50' AND '63'
   GROUP BY BGD.DJXH;
  COMMIT;

  FOR CUR_CKQY IN (SELECT DJXH FROM FXGL_DATA_FZPCKQY) LOOP
    -- 更新纺织品出口企业全部销售额信息
    WITH SBB AS (
    SELECT DISTINCT SB.SBUUID
      FROM HX_SB.SB_SBXX SB
     WHERE SB.DJXH=CUR_CKQY.DJXH
       AND SB.SKSSQQ >= LD_FXRQQ
       AND SB.SKSSQZ <= LD_FXRQZ
       AND SB.ZSXM_DM = '10101'
       AND SB.YZPZZL_DM = 'BDA0610606'
       AND SB.GZLX_DM_1 IN ('1', '5')
       AND SB.ZFBZ_1 = 'N'
    )
    SELECT SUM(ZZS.ASYSLJSXSE + ZZS.AJYBFJSXSE + ZZS.MDTBFCKXSE + ZZS.MSXSE)
      INTO LN_QBXSSR
      FROM SBB
     INNER JOIN HX_SB.SB_ZZS_YBNSR ZZS
        ON ZZS.SBUUID = SBB.SBUUID
     WHERE ZZS.EWBLXH IN (1, 3);
    UPDATE FXGL_DATA_FZPCKQY T
       SET T.QBXSSR = LN_QBXSSR,
           T.FZP_CKBL = CASE WHEN T.CK_FZP>=LN_QBXSSR THEN 1 ELSE T.CK_FZP/LN_QBXSSR END
     WHERE T.DJXH=CUR_CKQY.DJXH;
    COMMIT;

    --  更新财务报表存货信息
    WITH CWBB AS (
    SELECT A.ZLBSCJUUID
      FROM HX_SB.SB_ZLBSCJB A
     WHERE A.DJXH = CUR_CKQY.DJXH
       AND A.SSQQ >= LD_SSQQ
       AND A.SSQZ = LD_FXRQZ
       AND A.ZFBZ_1 IS NULL)
    SELECT SUM(CH_QCYE), SUM(CH_QMYE)
      INTO LN_CH_QCYE, LN_CH_QMYE
      FROM (SELECT B.NCYE_ZC AS CH_QCYE, B.QMYE_ZC AS CH_QMYE
              FROM CWBB
             INNER JOIN HX_SB.SB_CWBB_QYKJZZYBQY_ZCFZB B
                ON B.ZLBSCJUUID=CWBB.ZLBSCJUUID
             WHERE B.EWBHXH = 9
             UNION ALL
            SELECT B.NCS_ZC AS CH_QCYE, B.QMS_ZC AS CH_QMYE
              FROM CWBB
             INNER JOIN HX_SB.SB_CWBB_QYKJZZ_ZCFZB B
                ON B.ZLBSCJUUID=CWBB.ZLBSCJUUID
             WHERE B.EWBHXH = 10
             UNION ALL
            SELECT B.NCYE_ZC AS CH_QCYE, B.QMYE_ZC AS CH_QMYE
              FROM CWBB
             INNER JOIN HX_SB.SB_CWBB_XQYKJZZ_ZCFZB B
                ON B.ZLBSCJUUID=CWBB.ZLBSCJUUID
             WHERE B.EWBHXH = 9
             UNION ALL
            SELECT B.SNNMYE_ZC AS CH_QCYE, B.QMYE_ZC AS CH_QMYE
              FROM CWBB
             INNER JOIN HX_SB.SB_CWBB_QYKJZZYBQY_ZCFZBZX B
                ON B.ZLBSCJUUID=CWBB.ZLBSCJUUID
             WHERE B.EWBHXH = 9
           ) T;
    UPDATE FXGL_DATA_FZPCKQY T
       SET T.ZC_CH_QCYE = LN_CH_QCYE,
           T.ZC_CH_QMYE = LN_CH_QMYE,
           T.ZC_CH_ZYE = LN_CH_QMYE - LN_CH_QCYE
     WHERE T.DJXH=CUR_CKQY.DJXH;
    COMMIT;

  END LOOP;

  -- 删除暂不需要分析数据
  DELETE FROM FXGL_DATA_FZPCKQY T WHERE T.CK_FZP<10000000;
  COMMIT;
  DELETE FROM FXGL_DATA_FZPCKQY T WHERE T.CK_FZP<0.3*T.QBXSSR;
  COMMIT;

  -- 更新每米公斤数、每件公斤数、每公斤单价
  SELECT SUM(S.CK_ZL_CD), SUM(S.CK_CD_ZL), SUM(S.CK_ZL_SL),SUM(S.CK_SL_ZL),SUM(S.CK_ZL_ALL),SUM(S.CK_RMB)
    INTO LN_CK_ZL_CD, LN_CK_CD_ZL, LN_CK_ZL_SL, LN_CK_SL_ZL, LN_CK_ZL_ALL, LN_CK_RMB
    FROM FXGL_DATA_FZPCKQY S;
  UPDATE FXGL_DATA_FZPCKQY T
     SET T.CK_GJ_M = CASE WHEN T.CK_CD_ZL = 0 THEN NULL ELSE T.CK_ZL_CD / T.CK_CD_ZL END,
         T.CK_GJ_M_PJ = CASE WHEN LN_CK_CD_ZL = 0 THEN NULL ELSE LN_CK_ZL_CD / LN_CK_CD_ZL END,
         T.CK_GJ_J = CASE WHEN T.CK_SL_ZL = 0 THEN NULL ELSE T.CK_ZL_SL / T.CK_SL_ZL END,
         T.CK_GJ_J_PJ = CASE WHEN LN_CK_SL_ZL = 0 THEN NULL ELSE LN_CK_ZL_SL / LN_CK_SL_ZL END,
         T.CK_DJ_GJ = CASE WHEN T.CK_ZL_ALL = 0 THEN NULL ELSE T.CK_RMB / T.CK_ZL_ALL END,
         T.CK_DJ_GJ_PJ = CASE WHEN LN_CK_ZL_ALL = 0 THEN NULL ELSE LN_CK_RMB / LN_CK_ZL_ALL END;
  COMMIT;

  -- 更新纺织品出口企业税务登记信息
  UPDATE FXGL_DATA_FZPCKQY T
     SET T.NSRSBH = (
  SELECT NVL(S.SHXYDM,S.NSRSBH)
    FROM HX_DJ.DJ_NSRXX S
   WHERE S.DJXH=T.DJXH);
  COMMIT;

END;
/
