CREATE OR REPLACE PROCEDURE PRO_DEAL_CKTS_CKWSB_STOP
/*
 * 出口未申报报关单提取
 * 停止使用
 */
AS
BEGIN

  EXECUTE IMMEDIATE 'TRUNCATE TABLE CKTS_WBSJ_CKWSB';
  COMMIT;
  
  FOR CUR_NSRXX IN (SELECT T.TSSWJG_DM_1,T.DJXH,T.HGQY_DM
                      FROM HX_CKTS.CKTS_BA_BAXX_JGB T
                     WHERE NVL(T.BACHBZ,'N')='N' AND T.CKHWTMSJSFF_DM<'3'
                     ORDER BY T.TSSWJG_DM_1) LOOP
    INSERT INTO CKTS_WBSJ_CKWSB(TSSWJG_DM_1,DJXH,RKRQ,CKRQ_1,CKBGDH,JGFS_DM,CKSP_DM,HGSPMC,RMBLAJ,MYLAJ,HGQY_DM,BAH,SJLY)
         SELECT S.TSSWJG_DM_1,S.DJXH,S.RKRQ,S.CKRQ_1,S.CKBGDH,S.JGFS_DM,S.CKSP_DM,S.HGSPMC,S.RMBLAJ,S.MYLAJ,S.HGQY_DM,S.BAH,'BGD201'
           FROM HX_CKTS.CKTS_WBSJ_HG_BGD201 S 
          INNER JOIN HX_DM_ZDY.DM_CKTS_HGJGFS JG ON JG.JGFS_DM=S.JGFS_DM AND JG.JGFSTSLX_DM='1'
          WHERE S.TSSWJG_DM_1=CUR_NSRXX.TSSWJG_DM_1 -- 金三分区表
            AND S.DJXH=CUR_NSRXX.DJXH -- 单户抽取
            AND S.CKRQ_1<TRUNC(SYSDATE,'YY') -- 不包括本年业务，金三有索引
            AND S.TSSBSL+S.DLSBSL=0 AND S.CKSL-S.TYSL>0; --未申报退税、代理证明，同时未全部退运
    COMMIT;
    INSERT INTO CKTS_WBSJ_CKWSB(TSSWJG_DM_1,DJXH,RKRQ,CKRQ_1,CKBGDH,JGFS_DM,CKSP_DM,HGSPMC,RMBLAJ,MYLAJ,HGQY_DM,BAH,SJLY)
         SELECT S.TSSWJG_DM_1,S.DJXH,S.RKRQ,S.CKRQ_1,S.DLCKHWZMHM,S.JGFS_DM,S.CKSP_DM,S.HGSPMC,S.RMBLAJ,S.MYLAJ,S.WTFHGQYDM,S.BAH,'DLCKZM'
           FROM HX_CKTS.CKTS_WBSJ_ZJ_DLCKHWZM S 
          INNER JOIN HX_DM_ZDY.DM_CKTS_HGJGFS JG ON JG.JGFS_DM=S.JGFS_DM AND JG.JGFSTSLX_DM='1'
          WHERE S.DJXH=CUR_NSRXX.DJXH -- 单户抽取
            AND S.CKRQ_1<TRUNC(SYSDATE,'YY') -- 不包括本年业务，金三有索引
            AND S.TSSBSL=0 AND S.CKSL-S.TYSL>0; --未申报退税，同时未全部退运
    COMMIT;
  END LOOP;
  
  --删除禁止出口商品或不退税商品、免税商品
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_TY_CKSPTSLWK 
                   WHERE CKSP_DM = CKTS_WBSJ_CKWSB.CKSP_DM
                     AND CKTS_WBSJ_CKWSB.CKRQ_1 BETWEEN YXQQ AND YXQZ
                     AND CKSPTSSPLX_DM IN ('1','2'));
  COMMIT;
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_TY_CKSPTSLWK 
                   WHERE CKSP_DM = SUBSTR(CKTS_WBSJ_CKWSB.CKSP_DM,1,8)
                     AND CKTS_WBSJ_CKWSB.CKRQ_1 BETWEEN YXQQ AND YXQZ
                     AND CKSPTSSPLX_DM IN ('1','2'));
  COMMIT;
  
  --删除生产企业免抵退已申报数据
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_MDT_TSSB_JGB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_MDT_TSSB_GCB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  
  --删除外贸免退税已申报数据
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_MTS_TSSB_JGB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_MTS_TSSB_GCB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;

  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_MTS_TSSB_LB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  
  --删除外综服代办退税已申报数据
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_DB_TSSB_JGB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_DB_TSSB_GCB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  
  --删除非自产退消费税已申报数据
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_FZC_SBMX_JGB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_FZC_SBMX_GCB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  
  --删除已使用旧设备已申报数据
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_YS_SBMX_JGB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_SB_YS_SBMX_GCB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  
  --删除代理出口证明已申报数据
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_ZM_DLCK_JGMXB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  DELETE CKTS_WBSJ_CKWSB
   WHERE EXISTS ( SELECT 1
                    FROM HX_CKTS.CKTS_ZM_DLCK_GCMXB
                   WHERE DJXH = CKTS_WBSJ_CKWSB.DJXH
                     AND CKBGDH = CKTS_WBSJ_CKWSB.CKBGDH);
  COMMIT;
  
END;
/
