CREATE OR REPLACE PROCEDURE PRO_DEAL_CKTS_KZ_SLQY
(
  V_SJCLSJD IN  DATE
)
AS
BEGIN
  -- 四类企业法定代表人信息
  EXECUTE IMMEDIATE 'TRUNCATE TABLE CKTS_KZ_SLQY';
  COMMIT;

  INSERT INTO CKTS_KZ_SLQY(UUID,TSSWJG_DM_1,DJXH,LCSLID,YXQQ,YXQZ,LRRQ,NSRSBH,SHXYDM,NSRMC,FDDBRXM,FDDBRSFZJLX_DM,FDDBRSFZJHM,BACHBZ,BACHRQ)
       SELECT S.UUID,S.TSSWJG_DM_1,S.DJXH,S.LCSLID,TRUNC(S.YXQQ),TRUNC(S.YXQZ),TRUNC(S.LRRQ),
              T.NSRSBH,T.SHXYDM,T.NSRMC,T.FDDBRXM,T.FDDBRSFZJLX_DM,T.FDDBRSFZJHM,
              R.BACHBZ,R.BACHRQ
         FROM HX_CKTS.CKTS_BA_KZ_JGB S
        INNER JOIN HX_DJ.DJ_NSRXX T ON T.DJXH=S.DJXH
        INNER JOIN HX_CKTS.CKTS_BA_BAXX_JGB R ON R.DJXH=S.DJXH
        WHERE S.CKTMSBAKZLX_DM='FLGLCD' AND S.YXBZ='Y' AND S.KZNR='D'
          AND S.YXQZ>=V_SJCLSJD
          AND R.BACHBZ='N'
          AND R.BACHRQ IS NULL
        UNION ALL
       SELECT S.UUID,S.TSSWJG_DM_1,S.DJXH,S.LCSLID,TRUNC(S.YXQQ),TRUNC(S.YXQZ),TRUNC(S.LRRQ),
              T.NSRSBH,T.SHXYDM,T.NSRMC,T.FDDBRXM,T.FDDBRSFZJLX_DM,T.FDDBRSFZJHM,
              R.BACHBZ,R.BACHRQ
         FROM HX_CKTS.CKTS_BA_KZ_JGB S
        INNER JOIN HX_DJ.DJ_NSRXX T ON T.DJXH=S.DJXH
        INNER JOIN HX_CKTS.CKTS_BA_BAXX_JGB R ON R.DJXH=S.DJXH
        WHERE S.CKTMSBAKZLX_DM='FLGLCD' AND S.YXBZ='Y' AND S.KZNR='D'
          AND S.YXQZ>=V_SJCLSJD
          AND R.BACHBZ='Y'
          AND R.BACHRQ>V_SJCLSJD;
  COMMIT;

  RETURN;
END;
/
