CREATE OR REPLACE PROCEDURE PRO_DEAL_CKTS_LC_STZC
AS
BEGIN
  -- 出口退税审核流程（增量） 发放时间为系统日期提前7天，防止数据遗漏
  MERGE INTO CKTS_LC_STZC A
       USING (SELECT T.UUID,T.TSSWJG_DM_1,T.LCSWSX_DM,T.LCSLID,T.CKQYGLLB_DM,T.DJXH,T.SSQ,T.FFRQ,
                     SUM(S.MYLAJ) AS MYLAJ,SUM(S.RMBLAJ) AS RMBLAJ,SUM(S.MDTSE) AS MDTSE
                FROM HX_CKTS.CKTS_TY_YWBLXX T
               INNER JOIN HX_CKTS.CKTS_SB_MDT_TSSB_JGB S
                  ON S.TSSWJG_DM_1=T.TSSWJG_DM_1
                 AND S.DJXH=T.DJXH
                 AND S.SSQ=T.SSQ
                 AND REGEXP_LIKE(S.CKTMSYWLXDMJH,'STZC-01')
                 AND S.MDTSNY IS NOT NULL
                 AND S.MDTSE>0
               WHERE T.LCSWSX_DM='LCSXA081038001'
                 AND T.LCSLID=T.ZLCLCSLID
                 AND NVL(T.HTBZ_1,'N')='N'
                 AND T.FFRQ>=SYSDATE-7
               GROUP BY T.UUID,T.TSSWJG_DM_1,T.LCSWSX_DM,T.LCSLID,T.CKQYGLLB_DM,T.DJXH,T.SSQ,T.FFRQ
             ) B
          ON (A.UUID=B.UUID)
        WHEN MATCHED THEN
          UPDATE SET A.TSSWJG_DM_1=B.TSSWJG_DM_1,A.LCSWSX_DM=B.LCSWSX_DM,A.LCSLID=B.LCSLID,
                     A.CKQYGLLB_DM=B.CKQYGLLB_DM,A.DJXH=B.DJXH,A.SSQ=B.SSQ,A.FFRQ=B.FFRQ,
                     A.MYLAJ=B.MYLAJ,A.RMBLAJ=B.RMBLAJ,A.MDTSE=B.MDTSE
        WHEN NOT MATCHED THEN
          INSERT (UUID,TSSWJG_DM_1,LCSWSX_DM,LCSLID,CKQYGLLB_DM,DJXH,SSQ,FFRQ,MYLAJ,RMBLAJ,MDTSE,LCZT)
          VALUES (B.UUID,B.TSSWJG_DM_1,B.LCSWSX_DM,B.LCSLID,B.CKQYGLLB_DM,B.DJXH,B.SSQ,B.FFRQ,B.MYLAJ,B.RMBLAJ,B.MDTSE,'00');
  COMMIT;

  FOR CUR_LC IN (SELECT UUID,DJXH,FFRQ FROM CKTS_LC_STZC WHERE LCZT='00') LOOP
    UPDATE CKTS_LC_STZC T
       SET (T.ZGSWSKFJ_DM,T.NSRSBH,T.NSRMC,T.DJRQ)=
           (SELECT ZGSWSKFJ_DM,NSRSBH,NSRMC,DJRQ FROM HX_DJ.DJ_NSRXX WHERE DJXH=CUR_LC.DJXH)
     WHERE T.UUID=CUR_LC.UUID;
    COMMIT;

    UPDATE CKTS_LC_STZC T
       SET T.PJJB=(SELECT XY.PJJB FROM FXNK_JC2B_NSXYPJ XY WHERE XY.DJXH=CUR_LC.DJXH)
     WHERE T.UUID=CUR_LC.UUID;
    COMMIT;
  
    UPDATE CKTS_LC_STZC T
       SET T.SNDXSE=(SELECT SUM(ASYSLJSXSE+AJYBFJSXSE+MDTBFCKXSE+MSXSE)
                       FROM HX_SB.SB_ZZS_YBNSR
                      WHERE SBUUID IN (SELECT DISTINCT SBUUID
                                         FROM HX_SB.SB_SBXX
                                        WHERE DJXH=CUR_LC.DJXH
                                         AND SKSSQQ>=ADD_MONTHS(TRUNC(CUR_LC.FFRQ,'YY'),-12)
                                         AND SKSSQZ<TRUNC(CUR_LC.FFRQ,'YY')
                                         AND ZSXM_DM='10101' 
                                         AND YZPZZL_DM='BDA0610606'
                                         AND GZLX_DM_1 IN ('1','5')
                                         AND ZFBZ_1='N' )
                       AND EWBLXH IN (1, 3))
     WHERE T.UUID=CUR_LC.UUID;
    COMMIT;
      
    UPDATE CKTS_LC_STZC T
       SET T.LCZT=CASE WHEN ADD_MONTHS(T.DJRQ,24)>T.FFRQ OR T.PJJB<>'A' OR T.SNDXSE<500000000 THEN '11' ELSE '10' END
     WHERE T.UUID=CUR_LC.UUID AND T.DJRQ IS NOT NULL AND T.PJJB IS NOT NULL AND T.SNDXSE IS NOT NULL;
    COMMIT;
  END LOOP;

  RETURN;
END;
/
