CREATE OR REPLACE PROCEDURE PRO_DEAL_FXGL_STZCANDGJSB
/*
 * 生产企业出口外购货物风险模型、购进设备开1%3%普票风险模型
 * 数据初始化过程，确定生产企业范围
 */
AS
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE FXGL_DATA_STZC';
  COMMIT;

  -- 插入分析期内有视同自产出口的生产企业出口统计数据
  INSERT INTO FXGL_DATA_STZC(DJXH,SBTS_CKE,SBTS_WGCKE)
  SELECT SB.DJXH,SUM(SB.RMBLAJ),
         SUM(CASE WHEN REGEXP_LIKE(SB.CKTMSYWLXDMJH,'STZC') AND NOT REGEXP_LIKE(SB.CKTMSYWLXDMJH,'STZC-05') THEN SB.RMBLAJ ELSE 0 END)
    FROM HX_CKTS.CKTS_SB_MDT_TSSB_JGB SB
   WHERE SB.CKRQ_1 >= DATE'2024-01-01' AND SB.CKRQ_1 < DATE'2026-01-01' -- 出口日期范围
     AND SB.MDTSNY IS NOT NULL -- 已准予退税
   GROUP BY SB.DJXH;
  COMMIT;

  UPDATE FXGL_DATA_STZC T
     SET (NSRSBH,NSRMC,ZGSWJ_DM,ZGSWJ_MC,HY_DM,HY_MC,NSRZT_DM) =
         (SELECT NVL(S.SHXYDM,S.NSRSBH),S.NSRMC,S.ZGSWJ_DM,SW.SWJGMC,S.HY_DM,HY.HYMC,S.NSRZT_DM
            FROM HX_DJ.DJ_NSRXX S
           INNER JOIN HX_DM_ZDY.DM_GY_SWJG SW ON SW.SWJG_DM=S.ZGSWJ_DM
           INNER JOIN HX_DM_QG.DM_GY_HY HY ON HY.HY_DM=S.HY_DM
           WHERE S.DJXH=T.DJXH);
  COMMIT;

  UPDATE FXGL_DATA_STZC T
     SET (T.BARQ,T.BACHBZ,T.CKHWTMSJSFF_DM) =
         (SELECT S.BARQ,S.BACHBZ,S.CKHWTMSJSFF_DM
            FROM HX_CKTS.CKTS_BA_BAXX_JGB S
           WHERE S.DJXH=T.DJXH);
  COMMIT;

END;
/
