CREATE OR REPLACE PROCEDURE PRO_DEAL_CKTS_HD_XFHHSB
/*
 * 先发函后申报发票数据提取
 */
(
  V_SJCLSJD IN  DATE
)
AS
  LC_SSQ         VARCHAR(60);
  LC_SBPC        VARCHAR(75);
  LC_SBXH        VARCHAR(50);
  LD_LRRQ        DATE;
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE CKTS_HD_XFHHSB';
  COMMIT;

  -- 插入函调发票清单及签发日期
  INSERT INTO CKTS_HD_XFHHSB(HDFPQDUUID,ZZSZYFPDMHM,JE,SE,KTSE_1,FHXXBUUID,GHFDJXH,QFRQ)
       SELECT FP.HDFPQDUUID,FP.ZZSZYFPDMHM,FP.JE,FP.SE,FP.KTSE_1,FH.FHXXBUUID,FH.GHFDJXH,FH.QFRQ
         FROM HX_ZH.ZH_CKTS_FHXXB FH --函调发函
        INNER JOIN HX_ZH.ZH_CKTS_HDFPQD FP ON FH.FHXXBUUID=FP.FHXXBUUID --函调发票清单
        WHERE FH.FAHDSWJG_DM LIKE '133%' AND FH.FAHDSWJG_DM NOT LIKE '13302%' --发函地税局：浙江非宁波
          AND NVL(FH.ZFBZ_1,'N')='N' --发函未作废
          AND FH.DZBZDSZL_DM='BDA1320284' --非上游核实函, 上游核实函为BDA1320288
          AND FH.QFRQ>=V_SJCLSJD --签发日期起始
          AND NVL(FP.ZFBZ_1,'N')='N' --清单未作废
          --AND NVL(FP.SFYTS,'N')='N' --未退税发票
          ;
  COMMIT;

  -- 删除生产企业（可能对原材料发函）
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_BA_BAXX_JGB JGB WHERE JGB.DJXH=T.GHFDJXH AND JGB.CKHWTMSJSFF_DM='1');
  COMMIT;
  -- 删除先购进申报
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_SB_GJ_SBMX_GCB GCB WHERE GCB.DJXH=T.GHFDJXH AND GCB.JHPZH=T.ZZSZYFPDMHM AND GCB.LRRQ<T.QFRQ+1);
  COMMIT;
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_SB_GJ_SBMX_JGB JGB WHERE JGB.DJXH=T.GHFDJXH AND JGB.JHPZH=T.ZZSZYFPDMHM AND JGB.LRRQ<T.QFRQ+1);
  COMMIT;
  -- 删除先代办退税申报
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_SB_DB_TSSB_GCB GCB WHERE GCB.DJXH=T.GHFDJXH AND GCB.DBTSWSPZHM=T.ZZSZYFPDMHM AND GCB.LRRQ<T.QFRQ+1);
  COMMIT;
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_SB_DB_TSSB_JGB JGB WHERE JGB.DJXH=T.GHFDJXH AND JGB.DBTSWSPZHM=T.ZZSZYFPDMHM AND JGB.LRRQ<T.QFRQ+1);
  COMMIT;
  -- 删除先服务贸易免退税申报
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_SB_MTS_YSFWCK_GCB GCB WHERE GCB.DJXH=T.GHFDJXH AND GCB.JHPZH=T.ZZSZYFPDMHM AND GCB.LRRQ<T.QFRQ+1);
  COMMIT;
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_SB_MTS_YSFWCK_JGB JGB WHERE JGB.DJXH=T.GHFDJXH AND JGB.JHPZH=T.ZZSZYFPDMHM AND JGB.LRRQ<T.QFRQ+1);
  COMMIT;
  -- 删除先免退税申报
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_SB_MTS_TSJH_GCB GCB WHERE GCB.DJXH=T.GHFDJXH AND GCB.JHPZH=T.ZZSZYFPDMHM AND GCB.LRRQ<T.QFRQ+1);
  COMMIT;
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_SB_MTS_TSJH_JGB JGB WHERE JGB.DJXH=T.GHFDJXH AND JGB.JHPZH=T.ZZSZYFPDMHM AND JGB.LRRQ<T.QFRQ+1);
  COMMIT;
  DELETE FROM CKTS_HD_XFHHSB T WHERE EXISTS (
         SELECT 1 FROM HX_CKTS.CKTS_SB_MTS_TSJH_LB JGB WHERE JGB.DJXH=T.GHFDJXH AND JGB.JHPZH=T.ZZSZYFPDMHM AND JGB.LRRQ<T.QFRQ+1);
  COMMIT;

  FOR CUR_LC IN (SELECT HDFPQDUUID,ZZSZYFPDMHM,GHFDJXH FROM CKTS_HD_XFHHSB) LOOP
    BEGIN
      SELECT SSQ,SBPC,SBXH,LRRQ
        INTO LC_SSQ,LC_SBPC,LC_SBXH,LD_LRRQ
        FROM (SELECT SSQ,SBPC,SBXH,LRRQ
                FROM (SELECT GCB.SSQ,GCB.SBPC,GCB.SBXH,GCB.LRRQ
                        FROM HX_CKTS.CKTS_SB_MTS_TSJH_GCB GCB
                       WHERE GCB.DJXH=CUR_LC.GHFDJXH AND GCB.JHPZH=CUR_LC.ZZSZYFPDMHM
                       UNION ALL
                      SELECT JGB.SSQ,JGB.SBPC,JGB.SBXH,JGB.LRRQ
                        FROM HX_CKTS.CKTS_SB_MTS_TSJH_JGB JGB
                       WHERE JGB.DJXH=CUR_LC.GHFDJXH AND JGB.JHPZH=CUR_LC.ZZSZYFPDMHM
                       UNION ALL
                      SELECT GCB.SSQ,NULL AS SBPC,GCB.SBXH,GCB.LRRQ
                        FROM HX_CKTS.CKTS_SB_GJ_SBMX_GCB GCB
                       WHERE GCB.DJXH=CUR_LC.GHFDJXH AND GCB.JHPZH=CUR_LC.ZZSZYFPDMHM
                       UNION ALL
                      SELECT JGB.SSQ,NULL AS SBPC,JGB.SBXH,JGB.LRRQ
                        FROM HX_CKTS.CKTS_SB_GJ_SBMX_JGB JGB
                       WHERE JGB.DJXH=CUR_LC.GHFDJXH AND JGB.JHPZH=CUR_LC.ZZSZYFPDMHM
                       UNION ALL
                      SELECT GCB.SSQ,GCB.SBPC,GCB.SBXH,GCB.LRRQ
                        FROM HX_CKTS.CKTS_SB_DB_TSSB_GCB GCB
                       WHERE GCB.DJXH=CUR_LC.GHFDJXH AND GCB.DBTSWSPZHM=CUR_LC.ZZSZYFPDMHM
                       UNION ALL
                      SELECT JGB.SSQ,JGB.SBPC,JGB.SBXH,JGB.LRRQ
                        FROM HX_CKTS.CKTS_SB_DB_TSSB_JGB JGB
                       WHERE JGB.DJXH=CUR_LC.GHFDJXH AND JGB.DBTSWSPZHM=CUR_LC.ZZSZYFPDMHM
                     ) T
               ORDER BY LRRQ) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
        LC_SSQ := NULL;
        LC_SBPC := NULL;
        LC_SBXH := NULL;
        LD_LRRQ := NULL;
    END;

    UPDATE CKTS_HD_XFHHSB S
       SET S.SSQ=LC_SSQ, S.SBPC=LC_SBPC, S.SBXH=LC_SBXH, S.LRRQ=LD_LRRQ
     WHERE S.HDFPQDUUID=CUR_LC.HDFPQDUUID;
    COMMIT;
  END LOOP;

  RETURN;
END;
/
