CREATE OR REPLACE PROCEDURE PRO_DEAL_CKTS_LC_SDHC_STOP
/*
 * 新管理办法出台以后，容缺办理已经取消
 * 停止使用
 */
AS
  LD_SDHCQDSJ    DATE;
  LC_HCBH        VARCHAR(32);
  LD_SDHCWCSJ    DATE;
  LD_RQSEBJSJ    DATE;
  LC_ZLCLCSLID   VARCHAR(32);
  LC_ZFBZ_1      VARCHAR(2);
BEGIN
  -- 实地核查流程（增量）启动时间为系统日期提前7天，防止数据遗漏
  MERGE INTO CKTS_LC_SDHC A
       USING (SELECT T1.UUID,T1.TSSWJG_DM_1,T1.DJXH,S1.NSRSBH,S1.NSRMC,T1.LCSLID,T1.ZLCLCSLID,T1.HCYYSM,
                     T1.SDHCRQTZBH,T1.RQDCPGRY,T1.RQQRRY,T1.RQQRSJ,T1.JCRQSJ,T1.QXRQSJ,T1.RQDDXESJ,T1.LRRQ
                FROM HX_CKTS.CKTS_SDHC_JHSDHCTZ_JGB T1
               INNER JOIN HX_DJ.DJ_NSRXX S1 ON S1.DJXH=T1.DJXH
               WHERE T1.LRRQ>=SYSDATE-7 AND T1.RQBLSDHCBZ='Y' AND REGEXP_LIKE(T1.HCYYSM,'01|17|18')
               UNION ALL
              SELECT T2.UUID,T2.TSSWJG_DM_1,T2.DJXH,S2.NSRSBH,S2.NSRMC,T2.LCSLID,T2.ZLCLCSLID,T2.HCYYSM,
                     T2.SDHCRQTZBH,T2.RQDCPGRY,T2.RQQRRY,T2.RQQRSJ,T2.JCRQSJ,T2.QXRQSJ,T2.RQDDXESJ,T2.LRRQ
                FROM HX_CKTS.CKTS_SDHC_JHSDHCTZ_GCB T2
               INNER JOIN HX_DJ.DJ_NSRXX S2 ON S2.DJXH=T2.DJXH
               WHERE T2.LRRQ>=SYSDATE-7 AND T2.RQBLSDHCBZ='Y' AND REGEXP_LIKE(T2.HCYYSM,'01|17|18')) B
          ON (A.UUID=B.UUID)
        WHEN MATCHED THEN
          UPDATE SET A.TSSWJG_DM_1=B.TSSWJG_DM_1,A.DJXH=B.DJXH,A.NSRSBH=B.NSRSBH,A.NSRMC=B.NSRMC,
                     A.LCSLID=B.LCSLID,A.ZLCLCSLID=B.ZLCLCSLID,A.HCYYSM=B.HCYYSM,A.SDHCRQTZBH=B.SDHCRQTZBH,
                     A.RQDCPGRY=B.RQDCPGRY,A.RQQRRY=B.RQQRRY,A.RQQRSJ=B.RQQRSJ,A.JCRQSJ=B.JCRQSJ,A.QXRQSJ=B.QXRQSJ,
                     A.RQDDXESJ=B.RQDDXESJ,A.LRRQ=B.LRRQ
        WHEN NOT MATCHED THEN
          INSERT (UUID,TSSWJG_DM_1,DJXH,NSRSBH,NSRMC,LCSLID,ZLCLCSLID,HCYYSM,SDHCRQTZBH,RQDCPGRY,RQQRRY,RQQRSJ,JCRQSJ,QXRQSJ,RQDDXESJ,LRRQ,LCZT)
          VALUES (B.UUID,B.TSSWJG_DM_1,B.DJXH,B.NSRSBH,B.NSRMC,B.LCSLID,B.ZLCLCSLID,B.HCYYSM,B.SDHCRQTZBH,B.RQDCPGRY,B.RQQRRY,B.RQQRSJ,B.JCRQSJ,B.QXRQSJ,B.RQDDXESJ,B.LRRQ,'00');
  COMMIT;

  FOR CUR_LC IN (SELECT UUID,DJXH,NVL(ZLCLCSLID,LCSLID) AS ZLCLCSLID,LRRQ,RQQRSJ FROM CKTS_LC_SDHC WHERE LCZT<'10') LOOP
    -- SDHCQDSJ
    BEGIN
      SELECT MIN(T.RWFQSJ)
        INTO LD_SDHCQDSJ
        FROM (SELECT T1.*
                FROM HX_CKTS.CKTS_SDHC_JHSDHCTZ_JGB JGB
               INNER JOIN ZJ_MH.MH_LSRWXX T1 ON T1.LCSLID=JGB.LCSLID
               WHERE JGB.DJXH=CUR_LC.DJXH AND JGB.LRRQ>=CUR_LC.LRRQ AND REGEXP_LIKE(JGB.HCYYSM,'01|17|18')
               UNION ALL
              SELECT T2.*
                FROM HX_CKTS.CKTS_SDHC_JHSDHCTZ_GCB GCB
               INNER JOIN ZJ_MH.MH_RWXX T2 ON T2.LCSLID=GCB.LCSLID
               WHERE GCB.DJXH=CUR_LC.DJXH AND GCB.LRRQ>=CUR_LC.LRRQ AND REGEXP_LIKE(GCB.HCYYSM,'01|17|18')
             ) T
       WHERE T.RWSTATUS<>'06' AND T.RWZT LIKE '实地核查-实地核查实施%';
    EXCEPTION
      WHEN OTHERS THEN
        LD_SDHCQDSJ := NULL;
    END;
    -- HCBH, SDHCWCSJ
    BEGIN
      SELECT HCBH, SDHCWCSJ
        INTO LC_HCBH, LD_SDHCWCSJ
        FROM (SELECT HCBH, SDHCWCSJ
                FROM (SELECT T.HCBH, NVL(T.DCPGCLRQ,T.LRRQ) AS SDHCWCSJ
                        FROM HX_CKTS.CKTS_SDHC_SDHCBG_JGB T
                       WHERE T.DJXH=CUR_LC.DJXH AND T.LRRQ>=CUR_LC.LRRQ AND REGEXP_LIKE(T.HCYYSM,'01|17|18')
                       UNION ALL
                      SELECT T.HCBH, NVL(T.DCPGCLRQ,T.LRRQ) AS SDHCWCSJ
                        FROM HX_CKTS.CKTS_SDHC_SDHCBG_GCB T
                       WHERE T.DJXH=CUR_LC.DJXH AND T.LRRQ>=CUR_LC.LRRQ AND REGEXP_LIKE(T.HCYYSM,'01|17|18')
                     ) TT
               ORDER BY SDHCWCSJ) TTT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
        LC_HCBH := NULL;
        LD_SDHCWCSJ := NULL;
    END;
    -- ZLCLCSLID, ZFBZ_1
    BEGIN
      SELECT LCSLID, ZFBZ_1
        INTO LC_ZLCLCSLID, LC_ZFBZ_1
        FROM (SELECT T.LCSLID,T.QDSJ, NVL(T.ZFBZ_1,'N') AS ZFBZ_1
                FROM HX_CKTS.CKTS_TY_YWBLXX T
               WHERE T.DJXH=CUR_LC.DJXH
                 AND T.LCSWSX_DM IN ('LCSXA081038001','LCSXA081039001','LCSXA081042006','LCSXA081042001','LCSXA081042002','LCSXA081040001')
                 AND T.LCSLID = T.ZLCLCSLID
                 AND T.QDSJ <= (SELECT QDSJ FROM HX_CKTS.CKTS_TY_YWBLXX WHERE DJXH=CUR_LC.DJXH AND LCSLID=CUR_LC.ZLCLCSLID)
               ORDER BY T.QDSJ DESC) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
        LC_ZLCLCSLID := CUR_LC.ZLCLCSLID;
        LC_ZFBZ_1 := 'Y';
    END;
    --LD_RQSEBJSJ
    BEGIN
      SELECT MIN(CASE WHEN NVL(YW.FSZZSTSE,0)+NVL(YW.FSXFSTSE,0)-NVL(SE.BYHZZZSTSE,0)-NVL(SE.BYHZXFSTSE,0)>0 THEN TH.KPRQ
                      ELSE SE.SEHZRQ END)
        INTO LD_RQSEBJSJ
        FROM HX_CKTS.CKTS_TY_YWHZB YW
        LEFT JOIN HX_CKTS.CKTS_TY_SEHZB SE ON SE.YWHZBUUID=YW.YWHZBUUID
        LEFT JOIN HX_ZS.ZS_YDTXX ZS ON ZS.YDTLYUUID=SE.ZZSSSSRTHSBH AND ZS.TZLX_DM IN ('1','4')
        LEFT JOIN HX_ZS.ZS_SRTHS TH ON TH.YDTUUID=ZS.YDTUUID
       WHERE YW.DJXH=CUR_LC.DJXH AND YW.YWHZSJ>CUR_LC.RQQRSJ AND (YW.FSZZSTSE+YW.FSXFSTSE+YW.FSMDSE)>0;
    EXCEPTION
      WHEN OTHERS THEN
        LD_RQSEBJSJ := NULL;
    END;

    UPDATE CKTS_LC_SDHC S
       SET S.SDHCQDSJ=LD_SDHCQDSJ, S.HCBH=LC_HCBH, S.SDHCWCSJ=LD_SDHCWCSJ, S.RQSEBJSJ=LD_RQSEBJSJ,
           S.ZLCLCSLID=LC_ZLCLCSLID, S.ZFBZ_1=LC_ZFBZ_1,
           S.SDHCQDZQ=COMPUTE_BLDATE(NVL(S.SDHCQDSJ,SYSDATE),NVL(S.RQSEBJSJ,SYSDATE)),
           S.SDHCWCZQ=COMPUTE_BLDATE(NVL(S.SDHCWCSJ,SYSDATE),GREATEST(S.RQDDXESJ,NVL(S.RQSEBJSJ,SYSDATE)))
     WHERE S.UUID=CUR_LC.UUID;
    COMMIT;

    UPDATE CKTS_LC_SDHC S
       SET LCZT=CASE WHEN S.ZFBZ_1='Y'
                     THEN '20'
                     WHEN NVL(S.QXRQSJ,SYSDATE+1)<SYSDATE
                     THEN '20'
                     WHEN S.SDHCWCSJ IS NOT NULL
                     THEN (CASE WHEN S.RQDDXESJ IS NULL AND S.SDHCQDZQ>=20
                                THEN '12'
                                WHEN S.RQDDXESJ IS NOT NULL AND S.SDHCWCZQ>=20
                                THEN '12'
                                ELSE '10'
                           END)
                     ELSE (CASE WHEN S.RQDDXESJ IS NULL AND S.SDHCQDZQ>=20
                                THEN '02'
                                WHEN S.RQDDXESJ IS NOT NULL AND S.SDHCWCZQ>=20
                                THEN '02'
                                WHEN S.RQDDXESJ IS NULL AND S.SDHCQDZQ>=15
                                THEN '01'
                                WHEN S.RQDDXESJ IS NOT NULL AND S.SDHCWCZQ>=15
                                THEN '01'
                                ELSE '00'
                           END)
                END
     WHERE UUID=CUR_LC.UUID;
    COMMIT;
  END LOOP;

  RETURN;
END;
/
