CREATE OR REPLACE PROCEDURE PRO_DEAL_TSGZ_FQYCKJSBTJ
/*
 * 态势感知_分企业出口及申报统计
 */
AS
  LN_RMBLAJ_ALL   NUMBER(18,2);
  LN_RMBLAJ_TSL   NUMBER(18,2);
  LN_RMBLAJ_TSSB  NUMBER(18,2);
  LN_MSXSE_YB     NUMBER(18,2);
  LN_MSXSE_XGM    NUMBER(18,2);
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE TSGZ_DATA_FQYCKJSBTJ';
  COMMIT;
  
  FOR CUR_CKQY IN (SELECT A.TSSWJG_DM_1,A.DJXH,B.NSRMC,NVL(B.SHXYDM,B.NSRSBH) AS NSRSBH
                     FROM HX_CKTS.CKTS_BA_BAXX_JGB A
                    INNER JOIN HX_DJ.DJ_NSRXX B ON B.DJXH=A.DJXH
                    WHERE NVL(A.BACHBZ,'N')='N' AND A.BACHRQ IS NULL --未备案撤回
                      AND B.NSRZT_DM NOT IN ('05','07','08') --纳税人状态正常
                      AND EXISTS (
                          SELECT 1 FROM HX_CKTS.CKTS_WBSJ_HG_BGD201 C WHERE C.DJXH=A.DJXH AND C.CKRQ_1>=DATE'2026-01-01'
                           UNION ALL
                          SELECT 1 FROM HX_CKTS.CKTS_WBSJ_ZJ_DLCKHWZM D WHERE D.DJXH=A.DJXH AND D.CKRQ_1>=DATE'2026-01-01')
                    ORDER BY A.TSSWJG_DM_1,A.DJXH)
  LOOP
    -- 出口及退税申报情况
    WITH
    MX AS (
    SELECT T.CKBGDH,T.MYLAJ,T.RMBLAJ,T.TSSBMYLAJ,JG.JGFSTSLX_DM,WK.TSL,
           1 AS RN
      FROM HX_CKTS.CKTS_WBSJ_HG_BGD201 T
     INNER JOIN HX_DM_ZDY.DM_CKTS_HGJGFS JG
        ON JG.JGFS_DM=T.JGFS_DM
     INNER JOIN HX_CKTS.CKTS_TY_CKSPTSLWK WK
        ON (WK.CKSP_DM=T.CKSP_DM OR WK.CKSP_DM=SUBSTR(T.CKSP_DM,1,8))
       AND T.CKRQ_1 BETWEEN WK.YXQQ AND WK.YXQZ
     WHERE T.DJXH=CUR_CKQY.DJXH
       AND T.CKRQ_1>=DATE'2026-01-01'
       AND T.DLSBMYLAJ=0
     UNION ALL
    SELECT T.DLCKHWZMHM AS CKBGDH,T.MYLAJ,T.RMBLAJ,T.TSSBMYLAJ,JG.JGFSTSLX_DM,WK.TSL,
           ROW_NUMBER() OVER (PARTITION BY T.DLCKHWZMHM ORDER BY T.RKRQ DESC) AS RN
      FROM HX_CKTS.CKTS_WBSJ_ZJ_DLCKHWZM T
     INNER JOIN HX_DM_ZDY.DM_CKTS_HGJGFS JG
        ON JG.JGFS_DM=T.JGFS_DM
     INNER JOIN HX_CKTS.CKTS_TY_CKSPTSLWK WK
        ON REGEXP_LIKE(T.CKSP_DM,WK.CKSP_DM)
       AND T.CKRQ_1 BETWEEN WK.YXQQ AND WK.YXQZ
     WHERE T.DJXH=CUR_CKQY.DJXH
       AND T.CKRQ_1>=DATE'2026-01-01'
    )
    SELECT NVL(SUM(RMBLAJ),0),
           NVL(SUM(CASE WHEN JGFSTSLX_DM>'0' AND TSL>0 THEN RMBLAJ ELSE 0 END),0),
           NVL(SUM(CASE WHEN TSSBMYLAJ>0 THEN RMBLAJ ELSE 0 END),0)
      INTO LN_RMBLAJ_ALL, LN_RMBLAJ_TSL, LN_RMBLAJ_TSSB
      FROM MX
     WHERE RN=1;

    -- 对出口数大于0的企业统计增值税免税申报
    IF LN_RMBLAJ_ALL>0 THEN
      -- 一般纳税人报表
      SELECT NVL(SUM(MSXSE),0)
        INTO LN_MSXSE_YB
        FROM HX_SB.SB_ZZS_YBNSR
       WHERE SBUUID IN (SELECT DISTINCT SBUUID
                          FROM HX_SB.SB_SBXX
                         WHERE DJXH=CUR_CKQY.DJXH
                           AND SKSSQQ>=DATE'2026-01-01' AND SKSSQZ<SYSDATE
                           AND ZSXM_DM='10101' 
                           AND YZPZZL_DM='BDA0610606'
                           AND GZLX_DM_1 IN ('1','5')
                           AND ZFBZ_1='N' )
         AND EWBLXH IN (1, 3);
      -- 小规模报表
      SELECT NVL(SUM(CKMSXSE),0)
        INTO LN_MSXSE_XGM
        FROM HX_SB.SB_ZZS_XGM
       WHERE SBUUID IN (SELECT DISTINCT SBUUID
                          FROM HX_SB.SB_SBXX
                         WHERE DJXH=CUR_CKQY.DJXH
                           AND SKSSQQ>=DATE'2026-01-01' AND SKSSQZ<SYSDATE
                           AND ZSXM_DM='10101' 
                           AND YZPZZL_DM='BDA0610611'
                           AND GZLX_DM_1 IN ('1','5')
                           AND ZFBZ_1='N' )
         AND EWBLXH IN (1, 2);
      LN_MSXSE_YB := LN_MSXSE_YB + LN_MSXSE_XGM;

      INSERT INTO TSGZ_DATA_FQYCKJSBTJ(TSSWJG_DM_1,DJXH,NSRMC,NSRSBH,RMBLAJ_ALL,RMBLAJ_TSL,RMBLAJ_TSSB,ZZSMSXSE,SBL_TSSB,SBL_ZZS)
      SELECT CUR_CKQY.TSSWJG_DM_1,CUR_CKQY.DJXH,CUR_CKQY.NSRMC,CUR_CKQY.NSRSBH,
             ROUND(LN_RMBLAJ_ALL/10000,4),ROUND(LN_RMBLAJ_TSL/10000,4),
             ROUND(LN_RMBLAJ_TSSB/10000,4),ROUND(LN_MSXSE_YB/10000,4),
             CASE WHEN LN_RMBLAJ_TSL<=0 THEN NULL
                  WHEN LN_RMBLAJ_TSSB<=0 THEN 0
                  WHEN LN_RMBLAJ_TSSB>=LN_RMBLAJ_TSL THEN 100
                  ELSE ROUND(100 * LN_RMBLAJ_TSSB / LN_RMBLAJ_TSL,2)
             END,
             CASE WHEN LN_RMBLAJ_TSL<=0 THEN NULL
                  WHEN LN_MSXSE_YB<=0 THEN 0
                  WHEN LN_MSXSE_YB>=LN_RMBLAJ_TSL THEN 100
                  ELSE ROUND(100 * LN_MSXSE_YB / LN_RMBLAJ_TSL,2)
             END
        FROM DUAL;
      COMMIT;
    END IF;
  END LOOP;

END;
/
