CREATE OR REPLACE PROCEDURE PRO_DEAL_CKTS_CQWSB_ONE
/*
 * 单户长期未申报报关单提取
 * 有需要时人工调用
 */
(
  P_SHXYDM  IN VARCHAR2 --单户税号
)
AS
  V_CKSPTSSPLX_DM  CHAR(1);
  V_ZSSL           NUMBER(18,2);
  V_TSL            NUMBER(18,2);
BEGIN
  IF P_SHXYDM IS NULL THEN
    RETURN;
  END IF;
  
  FOR CUR_NSRXX IN (SELECT T.TSSWJG_DM_1,T.DJXH,T.CKHWTMSJSFF_DM,T.HGQY_DM,NVL(S.SHXYDM,S.NSRSBH) AS NSRSBH,S.NSRMC
                      FROM HX_CKTS.CKTS_BA_BAXX_JGB T
                     INNER JOIN HX_DJ.DJ_NSRXX S ON S.DJXH=T.DJXH
                     WHERE S.NSRSBH=P_SHXYDM OR S.SHXYDM=P_SHXYDM) LOOP
    BEGIN
      MERGE INTO RCGL_CQWSB_DATA A
           USING (SELECT UUID,DJXH,CKBGDH,CKRQ_1,CKSP_DM,GFHHGSPMC,BGD.JGFS_DM,HGCJFS_DM,MYLAJ,RMBLAJ,
                         DYJLDW_DM,CKSL,GREATEST(CKSL-TSSBSL-TYSL-DLSBSL,0) AS WSBSL,
                         JG.JGFSTSLX_DM,JG.CKYZSBZ,JG.MSJGBZ
                    FROM HX_CKTS.CKTS_WBSJ_HG_BGD201 BGD
                   INNER JOIN CKTS_DM_HGJGFS JG
                      ON JG.JGFS_DM=BGD.JGFS_DM
                     AND (JG.MSJGBZ='Y' OR JG.JGFSTSLX_DM<>'0')
                   WHERE BGD.DJXH=CUR_NSRXX.DJXH -- 单户抽取
                     AND BGD.CKSL-BGD.TYSL>0
                     AND BGD.TSSBSL=0
                     AND BGD.DLSBSL=0) B
              ON (A.DJXH=B.DJXH AND A.CKBGDH=B.CKBGDH)
            WHEN NOT MATCHED THEN
              INSERT (UUID,SWJGDM,DJXH,NSRSBH,NSRMC,TSJSFFDM,CKBGDH,CKRQ_1,CKSP_DM,GFHHGSPMC,JGFS_DM,HGCJFS_DM,
                     MYLAJ,RMBLAJ,DYJLDW_DM,CKSL,WSBSL,SJLY,CJRQ,JGFSTSLX_DM,CKYZSBZ,MSJGBZ)
              VALUES (B.UUID,CUR_NSRXX.TSSWJG_DM_1,CUR_NSRXX.DJXH,CUR_NSRXX.NSRSBH,CUR_NSRXX.NSRMC,CUR_NSRXX.CKHWTMSJSFF_DM,
                     B.CKBGDH,B.CKRQ_1,B.CKSP_DM,B.GFHHGSPMC,B.JGFS_DM,B.HGCJFS_DM,
                     B.MYLAJ,B.RMBLAJ,B.DYJLDW_DM,B.CKSL,B.WSBSL,'BGD201',SYSDATE,B.JGFSTSLX_DM,B.CKYZSBZ,B.MSJGBZ);
      COMMIT;
      MERGE INTO RCGL_CQWSB_DATA A
           USING (SELECT UUID,DJXH,DLCKHWZMHM AS CKBGDH,CKRQ_1,CKSP_DM,GFHHGSPMC,BGD.JGFS_DM,HGCJFS_DM,MYLAJ,RMBLAJ,
                         DYJLDW_DM,CKSL,GREATEST(CKSL-TSSBSL-TYSL,0) AS WSBSL,
                         JG.JGFSTSLX_DM,JG.CKYZSBZ,JG.MSJGBZ
                    FROM HX_CKTS.CKTS_WBSJ_ZJ_DLCKHWZM BGD
                   INNER JOIN CKTS_DM_HGJGFS JG
                      ON JG.JGFS_DM=BGD.JGFS_DM
                     AND (JG.MSJGBZ='Y' OR JG.JGFSTSLX_DM<>'0')
                   WHERE BGD.DJXH=CUR_NSRXX.DJXH -- 单户抽取
                     AND BGD.CKSL-BGD.TYSL>0
                     AND BGD.TSSBSL=0) B
              ON (A.DJXH=B.DJXH AND A.CKBGDH=B.CKBGDH)
            WHEN NOT MATCHED THEN
              INSERT (UUID,SWJGDM,DJXH,NSRSBH,NSRMC,TSJSFFDM,CKBGDH,CKRQ_1,CKSP_DM,GFHHGSPMC,JGFS_DM,HGCJFS_DM,
                     MYLAJ,RMBLAJ,DYJLDW_DM,CKSL,WSBSL,SJLY,CJRQ,JGFSTSLX_DM,CKYZSBZ,MSJGBZ)
              VALUES (B.UUID,CUR_NSRXX.TSSWJG_DM_1,CUR_NSRXX.DJXH,CUR_NSRXX.NSRSBH,CUR_NSRXX.NSRMC,CUR_NSRXX.CKHWTMSJSFF_DM,
                     B.CKBGDH,B.CKRQ_1,B.CKSP_DM,B.GFHHGSPMC,B.JGFS_DM,B.HGCJFS_DM,
                     B.MYLAJ,B.RMBLAJ,B.DYJLDW_DM,B.CKSL,B.WSBSL,'DLCKHWZM',SYSDATE,B.JGFSTSLX_DM,B.CKYZSBZ,B.MSJGBZ);
      COMMIT;
      MERGE INTO RCGL_CQWSB_DATA A
           USING (SELECT UUID,DJXH,CKBGDH,CKRQ_1,CKSP_DM,GFHHGSPMC,BGD.JGFS_DM,HGCJFS_DM,MYLAJ,RMBLAJ,
                         DYJLDW_DM,CKSL,CKSL AS WSBSL,
                         JG.JGFSTSLX_DM,JG.CKYZSBZ,JG.MSJGBZ
                    FROM HX_CKTS.CKTS_WBSJ_HG_WQFBGD201 BGD
                   INNER JOIN CKTS_DM_HGJGFS JG
                      ON JG.JGFS_DM=BGD.JGFS_DM
                     AND (JG.MSJGBZ='Y' OR JG.JGFSTSLX_DM<>'0')
                   WHERE NVL(BGD.DJXH,0)=CUR_NSRXX.DJXH -- 单户抽取
                     ) B
              ON (A.DJXH=B.DJXH AND A.CKBGDH=B.CKBGDH)
            WHEN NOT MATCHED THEN
              INSERT (UUID,SWJGDM,DJXH,NSRSBH,NSRMC,TSJSFFDM,CKBGDH,CKRQ_1,CKSP_DM,GFHHGSPMC,JGFS_DM,HGCJFS_DM,
                     MYLAJ,RMBLAJ,DYJLDW_DM,CKSL,WSBSL,SJLY,CJRQ,JGFSTSLX_DM,CKYZSBZ,MSJGBZ)
              VALUES (B.UUID,CUR_NSRXX.TSSWJG_DM_1,CUR_NSRXX.DJXH,CUR_NSRXX.NSRSBH,CUR_NSRXX.NSRMC,CUR_NSRXX.CKHWTMSJSFF_DM,
                     B.CKBGDH,B.CKRQ_1,B.CKSP_DM,B.GFHHGSPMC,B.JGFS_DM,B.HGCJFS_DM,
                     B.MYLAJ,B.RMBLAJ,B.DYJLDW_DM,B.CKSL,B.WSBSL,'WQFBGD',SYSDATE,B.JGFSTSLX_DM,B.CKYZSBZ,B.MSJGBZ);
      COMMIT;
    END;
    
    FOR CUR_WSB IN (SELECT T.DJXH,T.CKBGDH,T.CKRQ_1,T.CKSP_DM
                      FROM RCGL_CQWSB_DATA T
                     WHERE T.DJXH=CUR_NSRXX.DJXH
                       AND T.ZMTBZ IS NULL) LOOP
      BEGIN
        SELECT CKSPTSSPLX_DM, ZSSL, TSL
          INTO V_CKSPTSSPLX_DM, V_ZSSL, V_TSL
          FROM (SELECT CKSPTSSPLX_DM,TO_NUMBER(CASE WHEN LENGTH(ZSSLJH)>=2 THEN SUBSTR(ZSSLJH,1,2) ELSE ZSSLJH END) AS ZSSL,TSL
                  FROM (SELECT NVL(A.CKSPTSSPLX_DM,'0') AS CKSPTSSPLX_DM,A.ZSSLJH,A.TSL
                          FROM HX_CKTS.CKTS_TY_CKSPTSLWK A
                         WHERE A.CKSP_DM LIKE CUR_WSB.CKSP_DM||'%' AND (CUR_WSB.CKRQ_1 BETWEEN A.YXQQ AND A.YXQZ) AND A.JBSPBZ='Y'
                         UNION ALL
                        SELECT NVL(B.CKSPTSSPLX_DM,'0') AS CKSPTSSPLX_DM,B.ZSSLJH,B.TSL
                          FROM HX_CKTS.CKTS_TY_CKSPTSLWK B
                         WHERE B.CKSP_DM = SUBSTR(CUR_WSB.CKSP_DM,1,8) AND (CUR_WSB.CKRQ_1 BETWEEN B.YXQQ AND B.YXQZ) AND B.JBSPBZ='Y'
                        ) S
                 ORDER BY TSL DESC) R
         WHERE ROWNUM=1;
      EXCEPTION
        WHEN OTHERS THEN
          --找不到对应的基本商品
          V_CKSPTSSPLX_DM:=NULL;
          V_ZSSL:=NULL;
          V_TSL:=NULL;
      END;
      
      IF V_ZSSL IS NULL THEN
        BEGIN
          SELECT ZSSL, TSL
            INTO V_ZSSL, V_TSL
            FROM (SELECT TO_NUMBER(CASE WHEN LENGTH(ZSSLJH)>=2 THEN SUBSTR(ZSSLJH,1,2) ELSE ZSSLJH END) AS ZSSL,TSL
                    FROM HX_CKTS.CKTS_TY_CKSPTSLWK
                   WHERE CKSP_DM = SUBSTR(CUR_WSB.CKSP_DM,1,6)||'%' AND (CUR_WSB.CKRQ_1 BETWEEN YXQQ AND YXQZ) AND JBSPBZ='Y'
                   ORDER BY TSL DESC) R
           WHERE ROWNUM=1;
        EXCEPTION
          WHEN OTHERS THEN
            --找不到对应的基本商品
            V_ZSSL:=NULL;
            V_TSL:=NULL;
        END;
      END IF;
    
    UPDATE RCGL_CQWSB_DATA S
       SET S.ZMTBZ=CASE WHEN V_CKSPTSSPLX_DM='1' AND S.CKYZSBZ='Y' THEN '1' --文库征税商品+监管方式应征税：征税
                        WHEN V_CKSPTSSPLX_DM='1' AND S.CKYZSBZ='N' THEN '2' --文库征税商品+监管方式不征税：免税
                        WHEN V_CKSPTSSPLX_DM='2' THEN '2'  --文库免税商品：免税
                        WHEN S.JGFSTSLX_DM='0' THEN '3' --监管方式不退税
                        WHEN S.TSJSFFDM IN ('3','9') THEN '9' --退税计算方式不退税
                        WHEN V_CKSPTSSPLX_DM IS NULL THEN 'W' --因文库代码调整，未知
                        ELSE '0' END,
           S.ZSSL=V_ZSSL,
           S.TSL=V_TSL
     WHERE S.DJXH=CUR_WSB.DJXH AND S.CKBGDH=CUR_WSB.CKBGDH;
    COMMIT;
    END LOOP;
  END LOOP;
END;
/
