CREATE OR REPLACE PROCEDURE PRO_DEAL_CKTS_CKYZS_STOP
/*
 * 出口应征税商品数据提取
 * 停止使用
 */
AS
  LC_RKRQ   VARCHAR(8);
BEGIN
  SELECT TO_CHAR(TRUNC(MAX(T.RKRQ))-1,'YYYYMMDD')
    INTO LC_RKRQ
    FROM CKTS_WBSJ_CKYZS T;
  FOR CUR_SWJG IN (SELECT DJXH FROM HX_CKTS.CKTS_BA_BAXX_JGB ORDER BY TSSWJG_DM_1,DJXH) LOOP
    MERGE INTO CKTS_WBSJ_CKYZS A
         USING (SELECT T.TSSWJG_DM_1,T.DJXH,T.RKRQ,T.CKRQ_1,T.CKBGDH,T.JGFS_DM,T.CKSP_DM,T.HGSPMC,T.RMBLAJ,T.MYLAJ,SW.SWJGJC,NVL(QY.SHXYDM,QY.NSRSBH) AS NSRSBH,QY.NSRMC
                  FROM HX_CKTS.CKTS_WBSJ_HG_BGD201 T
                 INNER JOIN CKTS_DM_HGJGFS JG
                    ON JG.JGFS_DM=T.JGFS_DM AND JG.CKYZSBZ='Y'
                   AND (JG.JGFS_DM<>'1039' OR (JG.JGFS_DM='1039' AND T.CKRQ_1>=DATE'2024-03-20'))
                 INNER JOIN HX_CKTS.CKTS_TY_CKSPTSLWK WK
                    ON T.CKSP_DM LIKE WK.CKSP_DM||'%'
                   AND (T.CKRQ_1 BETWEEN WK.YXQQ AND WK.YXQZ)
                   AND WK.CKSPTSSPLX_DM='1'
                 INNER JOIN HX_DM_ZDY.DM_GY_SWJG SW
                    ON SW.SWJG_DM=T.TSSWJG_DM_1
                 INNER JOIN HX_DJ.DJ_NSRXX QY
                    ON QY.DJXH=T.DJXH
                 WHERE T.DJXH=CUR_SWJG.DJXH
                   AND TO_CHAR(T.RKRQ,'YYYYMMDD')>=LC_RKRQ
                   AND T.DLSBSL=0) B
            ON (A.DJXH=B.DJXH AND A.CKBGDH=B.CKBGDH)
          WHEN NOT MATCHED THEN
            INSERT (TSSWJG_DM_1,DJXH,RKRQ,CKRQ_1,CKBGDH,JGFS_DM,CKSP_DM,HGSPMC,RMBLAJ,MYLAJ,SJLY,TSSWJG_MC,NSRSBH,NSRMC)
            VALUES (B.TSSWJG_DM_1,B.DJXH,B.RKRQ,B.CKRQ_1,B.CKBGDH,B.JGFS_DM,B.CKSP_DM,B.HGSPMC,B.RMBLAJ,B.MYLAJ,'BGD201',B.SWJGJC,B.NSRSBH,B.NSRMC);
    COMMIT;
  END LOOP;
  
  MERGE INTO CKTS_WBSJ_CKYZS A
       USING (SELECT T.TSSWJG_DM_1,T.DJXH,T.RKRQ,T.CKRQ_1,T.DLCKHWZMHM,T.JGFS_DM,T.CKSP_DM,T.HGSPMC,T.RMBLAJ,T.MYLAJ,SW.SWJGJC,NVL(QY.SHXYDM,QY.NSRSBH) AS NSRSBH,QY.NSRMC
                FROM HX_CKTS.CKTS_WBSJ_ZJ_DLCKHWZM T
                 INNER JOIN CKTS_DM_HGJGFS JG
                    ON JG.JGFS_DM=T.JGFS_DM AND JG.CKYZSBZ='Y'
                   AND (JG.JGFS_DM<>'1039' OR (JG.JGFS_DM='1039' AND T.CKRQ_1>=DATE'2024-03-20'))
               INNER JOIN HX_CKTS.CKTS_TY_CKSPTSLWK WK
                  ON T.CKSP_DM LIKE WK.CKSP_DM||'%'
                 AND (T.CKRQ_1 BETWEEN WK.YXQQ AND WK.YXQZ)
                 AND WK.CKSPTSSPLX_DM='1'
               INNER JOIN HX_DM_ZDY.DM_GY_SWJG SW
                  ON SW.SWJG_DM=T.TSSWJG_DM_1
               INNER JOIN HX_DJ.DJ_NSRXX QY
                  ON QY.DJXH=T.DJXH
               WHERE TO_CHAR(T.RKRQ,'YYYYMMDD')>=LC_RKRQ) B
          ON (A.DJXH=B.DJXH AND A.CKBGDH=B.DLCKHWZMHM)
        WHEN NOT MATCHED THEN
          INSERT (TSSWJG_DM_1,DJXH,RKRQ,CKRQ_1,CKBGDH,JGFS_DM,CKSP_DM,HGSPMC,RMBLAJ,MYLAJ,SJLY,TSSWJG_MC,NSRSBH,NSRMC)
          VALUES (B.TSSWJG_DM_1,B.DJXH,B.RKRQ,B.CKRQ_1,B.DLCKHWZMHM,B.JGFS_DM,B.CKSP_DM,B.HGSPMC,B.RMBLAJ,B.MYLAJ,'DLCKZM',B.SWJGJC,B.NSRSBH,B.NSRMC);
  COMMIT;

  MERGE INTO CKTS_WBSJ_CKYZS A
       USING (SELECT T.TSSWJG_DM_1,T.DJXH,T.XGRQ,T.CKRQ_1,T.CKBGDH,T.JGFS_DM,T.CKSP_DM,T.HGSPMC,T.RMBLAJ,T.MYLAJ,SW.SWJGJC,NVL(QY.SHXYDM,QY.NSRSBH) AS NSRSBH,QY.NSRMC
                FROM HX_CKTS.CKTS_WBSJ_HG_WQFBGD201 T
                 INNER JOIN CKTS_DM_HGJGFS JG
                    ON JG.JGFS_DM=T.JGFS_DM AND JG.CKYZSBZ='Y'
                   AND (JG.JGFS_DM<>'1039' OR (JG.JGFS_DM='1039' AND T.CKRQ_1>=DATE'2024-03-20'))
               INNER JOIN HX_CKTS.CKTS_TY_CKSPTSLWK WK
                  ON T.CKSP_DM LIKE WK.CKSP_DM||'%'
                 AND (T.CKRQ_1 BETWEEN WK.YXQQ AND WK.YXQZ)
                 AND WK.CKSPTSSPLX_DM='1'
               INNER JOIN HX_DM_ZDY.DM_GY_SWJG SW
                  ON SW.SWJG_DM=T.TSSWJG_DM_1
               INNER JOIN HX_DJ.DJ_NSRXX QY
                  ON QY.DJXH=T.DJXH
               WHERE TO_CHAR(T.XGRQ,'YYYYMMDD')>=LC_RKRQ
                 AND T.DJXH IS NOT NULL) B
          ON (A.DJXH=B.DJXH AND A.CKBGDH=B.CKBGDH)
        WHEN NOT MATCHED THEN
          INSERT (TSSWJG_DM_1,DJXH,RKRQ,CKRQ_1,CKBGDH,JGFS_DM,CKSP_DM,HGSPMC,RMBLAJ,MYLAJ,SJLY,TSSWJG_MC,NSRSBH,NSRMC)
          VALUES (B.TSSWJG_DM_1,B.DJXH,B.XGRQ,B.CKRQ_1,B.CKBGDH,B.JGFS_DM,B.CKSP_DM,B.HGSPMC,B.RMBLAJ,B.MYLAJ,'WQFBGD1',B.SWJGJC,B.NSRSBH,B.NSRMC);
  COMMIT;

  MERGE INTO CKTS_WBSJ_CKYZS A
       USING (SELECT QY.ZGSWJ_DM,QY.DJXH,T.XGRQ,T.CKRQ_1,T.CKBGDH,T.JGFS_DM,T.CKSP_DM,T.HGSPMC,T.RMBLAJ,T.MYLAJ,SW.SWJGJC,NVL(QY.SHXYDM,QY.NSRSBH) AS NSRSBH,QY.NSRMC
                FROM HX_CKTS.CKTS_WBSJ_HG_WQFBGD201 T
                 INNER JOIN CKTS_DM_HGJGFS JG
                    ON JG.JGFS_DM=T.JGFS_DM AND JG.CKYZSBZ='Y'
                   AND (JG.JGFS_DM<>'1039' OR (JG.JGFS_DM='1039' AND T.CKRQ_1>=DATE'2024-03-20'))
               INNER JOIN HX_CKTS.CKTS_TY_CKSPTSLWK WK
                  ON T.CKSP_DM LIKE WK.CKSP_DM||'%'
                 AND (T.CKRQ_1 BETWEEN WK.YXQQ AND WK.YXQZ)
                 AND WK.CKSPTSSPLX_DM='1'
               INNER JOIN HX_DM_ZDY.DM_GY_SWJG SW
                  ON SW.SWJG_DM=T.TSSWJG_DM_1
               INNER JOIN HX_DJ.DJ_NSRXX QY
                  ON QY.NSRMC=T.JYDWMC
               WHERE TO_CHAR(T.XGRQ,'YYYYMMDD')>=LC_RKRQ
                 AND T.DJXH IS NULL) B
          ON (A.DJXH=B.DJXH AND A.CKBGDH=B.CKBGDH)
        WHEN NOT MATCHED THEN
          INSERT (TSSWJG_DM_1,DJXH,RKRQ,CKRQ_1,CKBGDH,JGFS_DM,CKSP_DM,HGSPMC,RMBLAJ,MYLAJ,SJLY,TSSWJG_MC,NSRSBH,NSRMC)
          VALUES (B.ZGSWJ_DM,B.DJXH,B.XGRQ,B.CKRQ_1,B.CKBGDH,B.JGFS_DM,B.CKSP_DM,B.HGSPMC,B.RMBLAJ,B.MYLAJ,'WQFBGD2',B.SWJGJC,B.NSRSBH,B.NSRMC);
  COMMIT;

  MERGE INTO CKTS_WBSJ_CKYZS A
       USING (SELECT T.TSSWJG_DM_1,T.DJXH,T.LRRQ,T.CKRQ_1,T.CKBGDH,T.JGFS_DM,T.CKSP_DM,S.HGSPMC,S.RMBLAJ,T.MYLAJ,SW.SWJGJC,NVL(QY.SHXYDM,QY.NSRSBH) AS NSRSBH,QY.NSRMC
                FROM HX_CKTS.CKTS_QT_BSYTMS_CKMX_JGB T
                LEFT JOIN HX_CKTS.CKTS_WBSJ_HG_BGD201 S
                  ON S.DJXH=T.DJXH
                 AND S.CKBGDH=T.CKBGDH
               INNER JOIN HX_DM_ZDY.DM_GY_SWJG SW
                  ON SW.SWJG_DM=T.TSSWJG_DM_1
               INNER JOIN HX_DJ.DJ_NSRXX QY
                  ON QY.DJXH=T.DJXH
               WHERE TO_CHAR(T.LRRQ,'YYYYMMDD')>=LC_RKRQ
                 AND T.CKBGDH IS NOT NULL
                 AND T.ZMSJY_DM='1') B
          ON (A.DJXH=B.DJXH AND A.CKBGDH=B.CKBGDH)
        WHEN NOT MATCHED THEN
          INSERT (TSSWJG_DM_1,DJXH,RKRQ,CKRQ_1,CKBGDH,JGFS_DM,CKSP_DM,HGSPMC,RMBLAJ,MYLAJ,SJLY,TSSWJG_MC,NSRSBH,NSRMC)
          VALUES (B.TSSWJG_DM_1,B.DJXH,B.LRRQ,B.CKRQ_1,B.CKBGDH,B.JGFS_DM,B.CKSP_DM,B.HGSPMC,B.RMBLAJ,B.MYLAJ,'BSYTMS',B.SWJGJC,B.NSRSBH,B.NSRMC);
  COMMIT;
END;
/
