CREATE OR REPLACE PROCEDURE TMP_PRO_DEAL_20260413
AS
  LN_TSE  NUMBER(18,6);
BEGIN
  DELETE FROM TMP_20260413_TSHKSZX_1;
  COMMIT;
  
  INSERT INTO TMP_20260413_TSHKSZX_1(TSSWJG_DM_1,SWJGJC,DJXH,NSRSBH,NSRMC,BARQ,BACHRQ,BACHBZ,NSRZT_DM,NSRZTMC,YXQQ_FZC,YXQQ_FZCZX,YXQQ_ZX,SEHZRQ_MIN,SEHZRQ_MAX,SEHZ_TSE)
  WITH
  CKQY AS (
  SELECT T.TSSWJG_DM_1,T.DJXH,NVL(S.SHXYDM,S.NSRSBH) AS NSRSBH,S.NSRMC,TRUNC(T.BARQ) AS BARQ,TRUNC(T.BACHRQ) AS BACHRQ,T.BACHBZ,S.NSRZT_DM,
         CASE WHEN S.NSRZT_DM IN ('05','07','08') THEN
           (SELECT MIN(A.YXQQ) FROM HX_DJ.DJ_NSRZTBGXXB A --非正常日期，剔除无效数据，剔除备案前发生数据
            WHERE A.DJXH=T.DJXH AND A.NSRZT_DM='05' AND A.YXQZ>A.YXQQ
            AND NOT EXISTS (SELECT 1 FROM HX_DJ.DJ_NSRZTBGXXB B WHERE B.DJXH=A.DJXH AND B.NSRZT_DM='03' AND B.YXQZ>A.YXQQ))
           ELSE NULL END AS YXQQ_FZC,
         CASE WHEN S.NSRZT_DM IN ('05','07','08') THEN
           (SELECT MIN(A.YXQQ) FROM HX_DJ.DJ_NSRZTBGXXB A --非正常注销日期，剔除无效数据，剔除备案前发生数据
            WHERE A.DJXH=T.DJXH AND A.NSRZT_DM='08' AND A.YXQZ>A.YXQQ
            AND NOT EXISTS (SELECT 1 FROM HX_DJ.DJ_NSRZTBGXXB B WHERE B.DJXH=A.DJXH AND B.NSRZT_DM='03' AND B.YXQZ>A.YXQQ))
           ELSE NULL END AS YXQQ_FZCZX,
         CASE WHEN S.NSRZT_DM IN ('05','07','08') THEN
           (SELECT MIN(A.YXQQ) FROM HX_DJ.DJ_NSRZTBGXXB A --注销日期，剔除无效数据，剔除备案前发生数据
            WHERE A.DJXH=T.DJXH AND A.NSRZT_DM='07' AND A.YXQZ>A.YXQQ
            AND NOT EXISTS (SELECT 1 FROM HX_DJ.DJ_NSRZTBGXXB B WHERE B.DJXH=A.DJXH AND B.NSRZT_DM='03' AND B.YXQZ>A.YXQQ))
           ELSE NULL END AS YXQQ_ZX
    FROM HX_CKTS.CKTS_BA_BAXX_JGB T
   INNER JOIN HX_DJ.DJ_NSRXX S ON S.DJXH=T.DJXH
   WHERE T.BACHBZ='Y' OR S.NSRZT_DM IN ('05','07','08') -- 所有已备案撤回或状态为非正常、非正常注销、注销的出口企业
  ),
  TS AS (
  SELECT T.DJXH, TRUNC(MIN(T.SEHZRQ)) AS SEHZRQ_MIN, TRUNC(MAX(T.SEHZRQ)) AS SEHZRQ_MAX, SUM(T.SEHZZZSTSE+T.SEHZXFSTSE) AS SEHZ_TSE
    FROM CKQY
   INNER JOIN HX_CKTS.CKTS_TY_SEHZB T ON T.DJXH=CKQY.DJXH
   WHERE T.SEHZZZSTSE+T.SEHZXFSTSE>0
   GROUP BY T.DJXH --按企业汇总最早退税日期、最迟退税日期、以及核准退税额
  HAVING SUM(T.SEHZZZSTSE+T.SEHZXFSTSE)>=1000000 --退税额已超过100W
  )
  SELECT CKQY.TSSWJG_DM_1,JG.SWJGJC,CKQY.DJXH,CKQY.NSRSBH,CKQY.NSRMC,CKQY.BARQ,CKQY.BACHRQ,CKQY.BACHBZ,CKQY.NSRZT_DM,ZT.NSRZTMC,
         CKQY.YXQQ_FZC,CKQY.YXQQ_FZCZX,CKQY.YXQQ_ZX,TS.SEHZRQ_MIN,TS.SEHZRQ_MAX,TS.SEHZ_TSE
    FROM CKQY
   INNER JOIN TS ON TS.DJXH=CKQY.DJXH
   INNER JOIN HX_DM_ZDY.DM_GY_SWJG JG ON JG.SWJG_DM=CKQY.TSSWJG_DM_1
   INNER JOIN HX_DM_QG.DM_GY_NSRZT ZT ON ZT.NSRZT_DM=CKQY.NSRZT_DM
  ;
  COMMIT;

  FOR CUR_DJXH IN (SELECT T.DJXH FROM TMP_20260413_TSHKSZX_1 T)
  LOOP
    BEGIN
      LN_TSE :=0;
      FOR CUR_HZ IN (SELECT S.SEHZZZSTSE+S.SEHZXFSTSE AS HZTSE,TRUNC(S.SEHZRQ) AS SEHZRQ FROM HX_CKTS.CKTS_TY_SEHZB S WHERE S.DJXH=CUR_DJXH.DJXH ORDER BY S.SEHZRQ)
      LOOP
        BEGIN
          LN_TSE := LN_TSE + CUR_HZ.HZTSE;
          IF LN_TSE >=1000000 THEN
            UPDATE TMP_20260413_TSHKSZX_1 TT
               SET TT.SEHZRQ_100W=CUR_HZ.SEHZRQ
             WHERE TT.DJXH=CUR_DJXH.DJXH;
            COMMIT;
            EXIT;
          END IF;
        END;
      END LOOP;
    END;
  END LOOP;
END;
/
