CREATE OR REPLACE PROCEDURE TMP_PRO_TEST_YJWM
/*
 * 预警处理效率测试
 */
AS
BEGIN
  FOR CUR_LC IN (SELECT TSSWJG_DM_1,DJXH,SSQ,SBPC,LCSWSX_DM,LCSLID
                   FROM HX_CKTS.CKTS_TY_YWBLXX T
                  WHERE T.LCSWSX_DM='LCSXA081039001'
                    AND T.QDSJ>TRUNC(SYSDATE,'MM')
                    AND T.ZLCLCSLID=T.LCSLID
                    AND EXISTS (SELECT 1
                                  FROM HX_CKTS.CKTS_SB_MTS_TSSB_GCB S1
                                 WHERE S1.LCSLID=T.LCSLID)
                    AND NOT EXISTS (SELECT 1
                                      FROM CKTS_YJRZ_LCSLID S2
                                     WHERE S2.LCSLID=T.LCSLID AND S2.ZBCODE='10501'))
  LOOP
    --新增出口商品（外贸）
    INSERT INTO CKTS_YJRZ_LCSLID(TSSWJG_DM_1,DJXH,SSQ,SBPC,LCSWSX_DM,LCSLID,ZBCODE)
         VALUES (CUR_LC.TSSWJG_DM_1,CUR_LC.DJXH,CUR_LC.SSQ,CUR_LC.SBPC,CUR_LC.LCSWSX_DM,CUR_LC.LCSLID,'10101');
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.YJ_COUNT=(SELECT COUNT(1) FROM (
/*********************************************************************************************************************************/
           WITH
           GLMX AS (
           SELECT A1.DJXH,A1.LCSLID,A1.CKSP_DM,A1.GLH,A1.CKRQ_1,A1.MYLAJ,
                  (SELECT SUM(A2.TSE) FROM HX_CKTS.CKTS_SB_MTS_TSJH_GCB A2 WHERE A2.DJXH=A1.DJXH AND A2.GLH=A1.GLH) AS TSE
             FROM HX_CKTS.CKTS_SB_MTS_TSSB_GCB A1
            WHERE A1.LCSLID = CUR_LC.LCSLID --#{LCSLID}
           ),
           FZTJ AS (
           SELECT A.DJXH,A.LCSLID,
                  SUBSTR(A.CKSP_DM,1,8) AS YJ_OBJECT,
                  MIN(A.GLH) AS YJ_RECORD,
                  COUNT(1) AS YJ_COUNT,
                  SUM(A.MYLAJ) AS YJ_AMT,
                  SUM(A.TSE) AS YJ_TAX,
                  MIN(A.CKRQ_1) AS CKRQ0
             FROM GLMX A
            GROUP BY A.DJXH,A.LCSLID,SUBSTR(A.CKSP_DM,1,8)
           HAVING SUM(A.TSE) > 1 --#{PVAL1}
           )
           SELECT T.LCSLID,T.YJ_OBJECT,T.YJ_RECORD,T.YJ_COUNT,T.YJ_AMT,T.YJ_TAX,
                  (SELECT B.SBHGSPMC FROM HX_CKTS.CKTS_SB_MTS_TSSB_GCB B WHERE B.LCSLID=T.LCSLID AND B.GLH=T.YJ_RECORD) AS CMNAME
             FROM FZTJ T
            WHERE NOT EXISTS (SELECT 1
                                FROM HX_CKTS.CKTS_SB_MTS_TSSB_JGB S
                               WHERE S.DJXH = T.DJXH
                                 AND SUBSTR(S.CKSP_DM,1,8) = T.YJ_OBJECT
                                 AND S.CKRQ_1 >=ADD_MONTHS(TRUNC(T.CKRQ0,'YY'),-24))
/**/
                      ))
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10101';
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.END_TIME=SYSDATE
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10101';
    COMMIT;
    
    --新增供货商（外贸）
    INSERT INTO CKTS_YJRZ_LCSLID(TSSWJG_DM_1,DJXH,SSQ,SBPC,LCSWSX_DM,LCSLID,ZBCODE)
         VALUES (CUR_LC.TSSWJG_DM_1,CUR_LC.DJXH,CUR_LC.SSQ,CUR_LC.SBPC,CUR_LC.LCSWSX_DM,CUR_LC.LCSLID,'10201');
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.YJ_COUNT=(SELECT COUNT(1) FROM (
/*********************************************************************************************************************************/
           WITH
           FZTJ AS (
           SELECT A.DJXH,
                  A.LCSLID,
                  A.GHFNSRSBH_1 AS YJ_OBJECT,
                  MIN(A.GLH) AS YJ_RECORD,
                  COUNT(1) AS YJ_COUNT,
                  SUM(A.JSJE) AS YJ_AMT,
                  SUM(A.TSE) AS YJ_TAX,
                  MIN(A.KPRQ) AS KPRQ0
             FROM HX_CKTS.CKTS_SB_MTS_TSJH_GCB A
            WHERE A.LCSLID = CUR_LC.LCSLID --#{LCSLID}
            GROUP BY A.DJXH,A.LCSLID,A.GHFNSRSBH_1
           HAVING SUM(A.TSE) > 1 --#{PVAL1}
           )
           SELECT T.LCSLID,T.YJ_OBJECT,T.YJ_RECORD,T.YJ_COUNT,T.YJ_AMT,T.YJ_TAX,
                  (SELECT B.SBHGSPMC FROM HX_CKTS.CKTS_SB_MTS_TSSB_GCB B WHERE B.LCSLID=T.LCSLID AND B.GLH=T.YJ_RECORD) AS CMNAME
             FROM FZTJ T
            WHERE NOT EXISTS (SELECT 1
                                FROM HX_CKTS.CKTS_SB_MTS_TSJH_JGB S
                               WHERE S.DJXH = T.DJXH
                                 AND S.GHFNSRSBH_1 = T.YJ_OBJECT
                                 AND S.KPRQ >=ADD_MONTHS(TRUNC(T.KPRQ0,'YY'),-24))
/**/
                      ))
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10201';
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.END_TIME=SYSDATE
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10201';
    COMMIT;
    
    --首次申报出口退税
    INSERT INTO CKTS_YJRZ_LCSLID(TSSWJG_DM_1,DJXH,SSQ,SBPC,LCSWSX_DM,LCSLID,ZBCODE)
         VALUES (CUR_LC.TSSWJG_DM_1,CUR_LC.DJXH,CUR_LC.SSQ,CUR_LC.SBPC,CUR_LC.LCSWSX_DM,CUR_LC.LCSLID,'10301');
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.YJ_COUNT=(
/*********************************************************************************************************************************/
           WITH
           SCSBQK AS (
           SELECT B.DJXH, B.LCSWSX_DM, NVL(B.SDHCWCBZ,'0') AS SDHCWCBZ, B.QYZTLX, TRUNC(B.QYZTBGSJ) AS QYZTBGSJ
             FROM (SELECT T.DJXH, T.LCSWSX_DM, T.LCSLID, T.QDSJ, A.SDHCWCBZ, A.QYZTLX, A.QYZTBGSJ, A.LRRQ
                     FROM HX_CKTS.CKTS_TY_YWBLXX T
                    INNER JOIN HX_CKTS.CKTS_TY_SCSBQK A ON A.DJXH=T.DJXH
                    WHERE T.LCSLID=CUR_LC.LCSLID --#{LCSLID}
                    ORDER BY A.LRRQ DESC) B
            WHERE ROWNUM=1),
           SDHCBG AS (
           SELECT D.DJXH, D.HCYYSM, D.HCJGSM
             FROM (SELECT C.DJXH, C.HCYYSM, C.HCJGSM, C.LRRQ
                     FROM SCSBQK
                    INNER JOIN HX_CKTS.CKTS_SDHC_SDHCBG_JGB C ON C.DJXH=SCSBQK.DJXH
                    WHERE SCSBQK.SDHCWCBZ<>'2'
                      AND C.HCYYSM LIKE DECODE(SCSBQK.QYZTLX,'1','%01%','2',DECODE(SCSBQK.LCSWSX_DM,'LCSXA081038001','%17%','%18%'),'3','%12%')
                      AND C.LRRQ >=SCSBQK.QYZTBGSJ
                    ORDER BY C.LRRQ DESC) D
            WHERE ROWNUM=1)
           SELECT COUNT(1)
             FROM DUAL
            WHERE NOT EXISTS (SELECT 1 FROM SCSBQK WHERE SCSBQK.SDHCWCBZ='2'
                              UNION
                              SELECT 1 FROM SDHCBG WHERE REGEXP_LIKE(SDHCBG.HCJGSM,'01|02|03|04'))
/**/
           )
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10301';
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.END_TIME=SYSDATE
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10301';
    COMMIT;
    
    --货源地不一致
    INSERT INTO CKTS_YJRZ_LCSLID(TSSWJG_DM_1,DJXH,SSQ,SBPC,LCSWSX_DM,LCSLID,ZBCODE)
         VALUES (CUR_LC.TSSWJG_DM_1,CUR_LC.DJXH,CUR_LC.SSQ,CUR_LC.SBPC,CUR_LC.LCSWSX_DM,CUR_LC.LCSLID,'10401');
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.YJ_COUNT=(SELECT COUNT(1) FROM (
/*********************************************************************************************************************************/
           WITH
           GLMX AS (
           SELECT A.LCSLID,SUBSTR(A.CKBGDH,1,18) AS YJ_OBJECT,A.GLH AS YJ_RECORD,A.MYLAJ,
                  C.HZDWDQ_DM,D.HZDWDQ_MC,D.XZQH_DM,B.SBXH,B.JSJE,B.TSE,B.GHFNSRSBH_1,
                  CASE WHEN DJ.ZGSWJ_DM IS NOT NULL AND SUBSTR(DJ.ZGSWJ_DM,2,LENGTH(D.XZQH_DM))=D.XZQH_DM THEN 0
                       WHEN LENGTH(B.GHFNSRSBH_1)=18 AND SUBSTR(B.GHFNSRSBH_1,5,2)='00' AND SUBSTR(B.GHFNSRSBH_1,3,2)=SUBSTR(D.XZQH_DM,1,2) THEN 0
                       WHEN LENGTH(B.GHFNSRSBH_1)=18 AND SUBSTR(B.GHFNSRSBH_1,5,2)<>'00' AND SUBSTR(B.GHFNSRSBH_1,3,LENGTH(D.XZQH_DM))=D.XZQH_DM THEN 0
                       WHEN LENGTH(B.GHFNSRSBH_1)>=15 AND LENGTH(B.GHFNSRSBH_1)<>18 AND SUBSTR(B.GHFNSRSBH_1,1,LENGTH(D.XZQH_DM))=D.XZQH_DM THEN 0
                       ELSE 1 END AS HYDYZ
             FROM HX_CKTS.CKTS_SB_MTS_TSSB_GCB A
            INNER JOIN HX_CKTS.CKTS_WBSJ_HG_BGD201 C ON C.DJXH=A.DJXH AND C.CKBGDH=A.CKBGDH
            INNER JOIN FXGL_DM_HZDWDQ D ON D.HZDWDQ_DM=C.HZDWDQ_DM
            INNER JOIN HX_CKTS.CKTS_SB_MTS_TSJH_GCB B ON A.DJXH=B.DJXH AND A.GLH=B.GLH
             LEFT JOIN HX_DJ.DJ_NSRXX DJ ON COALESCE(DJ.SHXYDM,DJ.NSRSBH)=B.GHFNSRSBH_1 AND DJ.KZZTDJLX_DM='1110'
            WHERE A.LCSLID=CUR_LC.LCSLID --#{LCSLID}
              AND A.CKBGDH IS NOT NULL
            UNION ALL
           SELECT A.LCSLID,SUBSTR(A.DLZMH,1,18) AS YJ_OBJECT,A.GLH AS YJ_RECORD,A.MYLAJ,
                  C.JNHYD_DM AS HZDWDQ_DM,D.HZDWDQ_MC,D.XZQH_DM,B.SBXH,B.JSJE,B.TSE,B.GHFNSRSBH_1,
                  CASE WHEN DJ.ZGSWJ_DM IS NOT NULL AND SUBSTR(DJ.ZGSWJ_DM,2,LENGTH(D.XZQH_DM))=D.XZQH_DM THEN 0
                       WHEN LENGTH(B.GHFNSRSBH_1)=18 AND SUBSTR(B.GHFNSRSBH_1,5,2)='00' AND SUBSTR(B.GHFNSRSBH_1,3,2)=SUBSTR(D.XZQH_DM,1,2) THEN 0
                       WHEN LENGTH(B.GHFNSRSBH_1)=18 AND SUBSTR(B.GHFNSRSBH_1,5,2)<>'00' AND SUBSTR(B.GHFNSRSBH_1,3,LENGTH(D.XZQH_DM))=D.XZQH_DM THEN 0
                       WHEN LENGTH(B.GHFNSRSBH_1)>=15 AND LENGTH(B.GHFNSRSBH_1)<>18 AND SUBSTR(B.GHFNSRSBH_1,1,LENGTH(D.XZQH_DM))=D.XZQH_DM THEN 0
                       ELSE 1 END AS HYDYZ
             FROM HX_CKTS.CKTS_SB_MTS_TSSB_GCB A
            INNER JOIN HX_CKTS.CKTS_WBSJ_ZJ_DLCKHWZM C ON C.DJXH=A.DJXH AND C.TSSWJG_DM_1=A.TSSWJG_DM_1 AND C.DLCKHWZMHM=A.DLZMH
            INNER JOIN FXGL_DM_HZDWDQ D ON D.HZDWDQ_DM=C.JNHYD_DM
            INNER JOIN HX_CKTS.CKTS_SB_MTS_TSJH_GCB B ON A.DJXH=B.DJXH AND A.GLH=B.GLH
             LEFT JOIN HX_DJ.DJ_NSRXX DJ ON COALESCE(DJ.SHXYDM,DJ.NSRSBH)=B.GHFNSRSBH_1 AND DJ.KZZTDJLX_DM='1110'
            WHERE A.LCSLID=CUR_LC.LCSLID --#{LCSLID}
              AND A.CKBGDH IS NULL
           ),
           BYZMX AS (
           SELECT LCSLID,YJ_OBJECT,YJ_RECORD,MYLAJ,HZDWDQ_DM,HZDWDQ_MC,XZQH_DM,SBXH,JSJE,TSE,GHFNSRSBH_1,
                  ROW_NUMBER() OVER (PARTITION BY YJ_RECORD ORDER BY JSJE DESC) AS JSMYBZ,
                  ROW_NUMBER() OVER (PARTITION BY YJ_OBJECT ORDER BY JSJE DESC) AS XSYJBZ
             FROM GLMX T
            WHERE HYDYZ=1
              AND NOT EXISTS (SELECT 1 FROM GLMX S WHERE S.YJ_OBJECT=T.YJ_OBJECT AND S.HYDYZ=0)
           ),
           BYZTJ AS (
           SELECT YJ_OBJECT,COUNT(1) AS YJ_COUNT,SUM(CASE WHEN JSMYBZ=1 THEN MYLAJ ELSE 0 END) AS YJ_USD,SUM(JSJE) AS YJ_AMT,SUM(TSE) AS YJ_TAX
             FROM BYZMX
            GROUP BY YJ_OBJECT
            HAVING SUM(TSE)>1 --#{PVAL1}
           )
           SELECT BYZMX.LCSLID,BYZMX.YJ_OBJECT,BYZMX.YJ_RECORD,BYZTJ.YJ_COUNT,BYZTJ.YJ_USD,BYZTJ.YJ_AMT,BYZTJ.YJ_TAX,
                  BYZMX.HZDWDQ_DM,BYZMX.HZDWDQ_MC,BYZMX.XZQH_DM,BYZMX.GHFNSRSBH_1
             FROM BYZMX
            INNER JOIN BYZTJ ON BYZTJ.YJ_OBJECT=BYZMX.YJ_OBJECT
            WHERE BYZMX.XSYJBZ=1
/**/
                      ))
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10401';
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.END_TIME=SYSDATE
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10401';
    COMMIT;
    
    --商品名称不一致
    INSERT INTO CKTS_YJRZ_LCSLID(TSSWJG_DM_1,DJXH,SSQ,SBPC,LCSWSX_DM,LCSLID,ZBCODE)
         VALUES (CUR_LC.TSSWJG_DM_1,CUR_LC.DJXH,CUR_LC.SSQ,CUR_LC.SBPC,CUR_LC.LCSWSX_DM,CUR_LC.LCSLID,'10501');
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.YJ_COUNT=(SELECT COUNT(1) FROM (
/*********************************************************************************************************************************/
           WITH
           GLMX AS (
           SELECT A.LCSLID,A.CKSP_DM AS YJ_OBJECT,A.GLH AS YJ_RECORD,A.MYLAJ,B.SBXH,B.JSJE,B.TSE,
                  C.GFHHGSPMC,D.GFHHWHYSLWMC,
                  CASE WHEN C.GFHHGSPMC=D.GFHHWHYSLWMC THEN 0 ELSE 1 END AS SPMCYZ
             FROM HX_CKTS.CKTS_SB_MTS_TSSB_GCB A
            INNER JOIN HX_CKTS.CKTS_SB_MTS_TSJH_GCB B ON A.DJXH=B.DJXH AND A.GLH=B.GLH
            INNER JOIN HX_CKTS.CKTS_WBSJ_HG_BGD201 C ON C.DJXH=A.DJXH AND C.CKBGDH=A.CKBGDH
            INNER JOIN HX_CKTS.CKTS_WBSJ_FP_ZZSFPHWXX D ON D.DJXH=A.DJXH AND D.JHPZH=B.JHPZH
            WHERE A.LCSLID=CUR_LC.LCSLID --#{LCSLID}
              AND A.CKBGDH IS NOT NULL
            UNION ALL
           SELECT A.LCSLID,A.CKSP_DM AS YJ_OBJECT,A.GLH AS YJ_RECORD,A.MYLAJ,B.SBXH,B.JSJE,B.TSE,
                  C.GFHHGSPMC,D.GFHHWHYSLWMC,
                  CASE WHEN C.GFHHGSPMC=D.GFHHWHYSLWMC THEN 0 ELSE 1 END AS SPMCYZ
             FROM HX_CKTS.CKTS_SB_MTS_TSSB_GCB A
            INNER JOIN HX_CKTS.CKTS_SB_MTS_TSJH_GCB B ON A.DJXH=B.DJXH AND A.GLH=B.GLH
            INNER JOIN HX_CKTS.CKTS_WBSJ_ZJ_DLCKHWZM C ON C.DJXH=A.DJXH AND C.TSSWJG_DM_1=A.TSSWJG_DM_1 AND C.DLCKHWZMHM=A.DLZMH
            INNER JOIN HX_CKTS.CKTS_WBSJ_FP_ZZSFPHWXX D ON D.DJXH=A.DJXH AND D.JHPZH=B.JHPZH
            WHERE A.LCSLID=CUR_LC.LCSLID --#{LCSLID}
              AND A.CKBGDH IS NULL
           ),
           BYZMX AS (
           SELECT LCSLID,YJ_OBJECT,YJ_RECORD,MYLAJ,SBXH,JSJE,TSE,GFHHGSPMC,GFHHWHYSLWMC,
                  ROW_NUMBER() OVER (PARTITION BY YJ_RECORD ORDER BY JSJE DESC) AS JSMYBZ,
                  ROW_NUMBER() OVER (PARTITION BY SBXH ORDER BY JSJE DESC) AS JSSEBZ
             FROM GLMX T
            WHERE SPMCYZ=1
              AND NOT EXISTS (SELECT 1 FROM GLMX S WHERE S.YJ_RECORD=T.YJ_RECORD AND S.SPMCYZ=0)
           ),
           BYZTJ AS (
           SELECT YJ_RECORD,1 AS YJ_COUNT,
                  SUM(CASE WHEN JSMYBZ=1 THEN MYLAJ ELSE 0 END) AS YJ_USD,
                  SUM(CASE WHEN JSSEBZ=1 THEN JSJE ELSE 0 END) AS YJ_AMT,
                  SUM(CASE WHEN JSSEBZ=1 THEN TSE ELSE 0 END) AS YJ_TAX
             FROM BYZMX
            GROUP BY YJ_RECORD
            HAVING SUM(TSE)>1 --#{PVAL1}
           )
           SELECT BYZMX.LCSLID,BYZMX.YJ_OBJECT,BYZMX.YJ_RECORD,BYZTJ.YJ_COUNT,BYZTJ.YJ_USD,BYZTJ.YJ_AMT,BYZTJ.YJ_TAX,
                  BYZMX.SBXH,BYZMX.GFHHGSPMC,BYZMX.GFHHWHYSLWMC
             FROM BYZMX
            INNER JOIN BYZTJ ON BYZTJ.YJ_RECORD=BYZMX.YJ_RECORD
            WHERE BYZMX.JSMYBZ=1
/**/
                      ))
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10501';
    COMMIT;
    UPDATE CKTS_YJRZ_LCSLID S
       SET S.END_TIME=SYSDATE
     WHERE S.LCSLID=CUR_LC.LCSLID AND S.ZBCODE='10501';
    COMMIT;
  END LOOP;

END;
/
