CREATE OR REPLACE PROCEDURE TMP_PRO_DEAL_20260313
AS
  LN_MSXSE_Y  NUMBER(18,6);
  LN_MSXSE_X  NUMBER(18,6);
BEGIN
  INSERT INTO TMP_20260313_1039_1(DJXH,CKYEAR,FS,BS,RMBLAJ,MYLAJ,SJLY)
  select T.DJXH,TO_CHAR(T.CKRQ_1,'YYYY'),COUNT(DISTINCT SUBSTR(T.CKBGDH,1,18)),COUNT(1),SUM(T.RMBLAJ),SUM(T.MYLAJ),'BGD201'
    from HX_CKTS.CKTS_WBSJ_HG_BGD201 t
   WHERE T.JGFS_DM='1039' AND T.CKRQ_1>=DATE'2023-01-01'
   GROUP BY T.DJXH,TO_CHAR(T.CKRQ_1,'YYYY')
   UNION ALL
  select T.DJXH,TO_CHAR(T.CKRQ_1,'YYYY'),COUNT(DISTINCT SUBSTR(T.CKBGDH,1,18)),COUNT(1),SUM(T.RMBLAJ),SUM(T.MYLAJ),'WQFBGD201'
    from HX_CKTS.CKTS_WBSJ_HG_WQFBGD201 t
   WHERE T.DJXH IS NOT NULL AND T.JGFS_DM='1039' AND T.CKRQ_1>=DATE'2023-01-01'
   GROUP BY T.DJXH,TO_CHAR(T.CKRQ_1,'YYYY');
  COMMIT;
  INSERT INTO TMP_20260313_1039_2(DJXH,CKYEAR,FS,BS,RMBLAJ,MYLAJ,SJLY)
  SELECT DJXH,CKYEAR,SUM(FS),SUM(BS),SUM(RMBLAJ),SUM(MYLAJ),LISTAGG(SJLY,';') within group(order by DJXH,CKYEAR) as glgx_jh
    FROM TMP_20260313_1039_1 T
   GROUP BY DJXH,CKYEAR;
  COMMIT;

  FOR CUR_LC IN (SELECT T.DJXH,T.CKYEAR FROM TMP_20260313_1039_2 T)
  LOOP
    BEGIN
      LN_MSXSE_Y :=NULL;
      LN_MSXSE_X :=NULL;
      SELECT SUM(MSXSE)
        INTO LN_MSXSE_Y
        FROM HX_SB.SB_ZZS_YBNSR
       WHERE SBUUID IN (SELECT DISTINCT SBUUID
                          FROM HX_SB.SB_SBXX
                         WHERE DJXH=CUR_LC.DJXH
                           AND SKSSQQ>=TO_DATE(CUR_LC.CKYEAR||'0101','YYYYMMDD')
                           AND SKSSQZ<ADD_MONTHS(TO_DATE(CUR_LC.CKYEAR||'0101','YYYYMMDD'),12)
                           AND ZSXM_DM='10101' 
                           AND YZPZZL_DM ='BDA0610606'
                           AND GZLX_DM_1 IN ('1','5')
                           AND ZFBZ_1='N' )
         AND EWBLXH=1;
      SELECT SUM(MSXSE)
        INTO LN_MSXSE_X
        FROM HX_SB.SB_ZZS_XGM
       WHERE SBUUID IN (SELECT DISTINCT SBUUID
                          FROM HX_SB.SB_SBXX
                         WHERE DJXH=CUR_LC.DJXH
                           AND SKSSQQ>=TO_DATE(CUR_LC.CKYEAR||'0101','YYYYMMDD')
                           AND SKSSQZ<ADD_MONTHS(TO_DATE(CUR_LC.CKYEAR||'0101','YYYYMMDD'),12)
                           AND ZSXM_DM='10101' 
                           AND YZPZZL_DM ='BDA0610611'
                           AND GZLX_DM_1 IN ('1','5')
                           AND ZFBZ_1='N' )
         AND EWBLXH=1;
      UPDATE TMP_20260313_1039_2 S
         SET S.MSXSE_YBNSR=LN_MSXSE_Y,
             S.MSXSE_XGMNSR=LN_MSXSE_X
       WHERE S.DJXH=CUR_LC.DJXH
         AND S.CKYEAR=CUR_LC.CKYEAR;
      COMMIT;
    END;
  END LOOP;
END;
/
