CREATE OR REPLACE PROCEDURE TMP_PRO_DEAL_20260519
AS
  LN_JSJKZZ  NUMBER(18,2);
  LN_JSCKZZ  NUMBER(18,2);
  LN_JSJKZZ_0654  NUMBER(18,2);
  LN_JSCKZZ_0654  NUMBER(18,2);
  LN_JSJKZZ_0654_ZS  NUMBER(18,2);
  LN_JSCKZZ_0654_ZS  NUMBER(18,2);
  LN_JSCKZZ_BGD201_0654  NUMBER(18,2);
  LN_JSCKZZ_BGD201_0654_ZS  NUMBER(18,2);
BEGIN
/*
  INSERT INTO TMP_20260519_JLSJGJZ_1(DJXH,BAH,HXQSRQ,HXJZRQ)
  SELECT DISTINCT T.DJXH,T.BAH,DATE'1900-01-01' AS HXQSRQ, DATE'2026-12-31' AS HXJZRQ
    FROM HX_CKTS.CKTS_WBSJ_HG_DZSCHXXX T
   WHERE TRUNC(T.JARQ,'yy')=DATE'2025-01-01'
   UNION ALL
  SELECT DISTINCT T.DJXH,T.BAH,T.HXQSRQ, T.HXJZRQ
    FROM HX_CKTS.CKTS_WBSJ_HG_DZZCHXXX T
   WHERE TRUNC(T.HXJZRQ,'yy')=DATE'2025-01-01';
  COMMIT;
  SELECT T.*,T.ROWID FROM TMP_20260519_JLSJGJZ_1 T WHERE T.DJXH IS NULL;
  SELECT T.*,T.ROWID,S.*,ROW_NUMBER() OVER (PARTITION BY T.DJXH,T.BAH ORDER BY S.LRRQ DESC) AS PM
    FROM TMP_20260519_JLSJGJZ_1 T
   INNER JOIN HX_CKTS.CKTS_SB_JLJG_MDTHX_JGB S
      ON S.DJXH=T.DJXH AND S.JLJGSZCH=T.BAH
   WHERE REGEXP_LIKE(T.BAH,'^B|^C')
     AND T.JSJKZZ_MDTHX IS NULL;
  SELECT T.*,T.ROWID,S.*,ROW_NUMBER() OVER (PARTITION BY T.DJXH,T.BAH ORDER BY S.LRRQ DESC) AS PM
    FROM TMP_20260519_JLSJGJZ_1 T
   INNER JOIN HX_CKTS.CKTS_SB_JLJG_MDTHX_JGB S
      ON S.DJXH=T.DJXH AND S.JLJGSZCH=T.BAH AND S.HXQSRQ=T.HXQSRQ AND S.HXJZRQ=T.HXJZRQ
   WHERE REGEXP_LIKE(T.BAH,'^E|^H')
     AND T.JSJKZZ_MDTHX IS NULL;
*/
  FOR CUR_SZC IN (SELECT DJXH,BAH,HXQSRQ,HXJZRQ FROM TMP_20260519_JLSJGJZ_1 WHERE BAH LIKE 'C%' AND JSJKZZ_HXGBD IS NULL)
  LOOP
    BEGIN
      SELECT SUM(CASE WHEN S.JS_FLAG_1=1 THEN T.RMBLAJ WHEN S.JS_FLAG_1=3 THEN T.RMBLAJ WHEN S.JS_FLAG_1=4 THEN (-1) * T.RMBLAJ ELSE 0 END),
             SUM(CASE WHEN S.JS_FLAG_1=2 THEN T.RMBLAJ WHEN S.JS_FLAG_1=5 THEN T.RMBLAJ WHEN S.JS_FLAG_1=6 THEN (-1) * T.RMBLAJ ELSE 0 END),
             SUM(CASE WHEN T.JGFS_DM='0654' AND T.JCKBZ_DM='I' THEN T.RMBLAJ ELSE 0 END),
             SUM(CASE WHEN T.JGFS_DM='0654' AND T.JCKBZ_DM='E' THEN T.RMBLAJ ELSE 0 END),
             SUM(CASE WHEN T.JGFS_DM='0654' AND T.JCKBZ_DM='I' AND NVL(NVL(A.CKSPTSSPLX_DM,B.CKSPTSSPLX_DM),'0')='1' THEN T.RMBLAJ ELSE 0 END),
             SUM(CASE WHEN T.JGFS_DM='0654' AND T.JCKBZ_DM='E'  AND NVL(NVL(A.CKSPTSSPLX_DM,B.CKSPTSSPLX_DM),'0')='1'THEN T.RMBLAJ ELSE 0 END)
        INTO LN_JSJKZZ, LN_JSCKZZ, LN_JSJKZZ_0654, LN_JSCKZZ_0654, LN_JSJKZZ_0654_ZS, LN_JSCKZZ_0654_ZS
        FROM HX_CKTS.CKTS_WBSJ_HG_HXBGD T
       INNER JOIN TMP_TDCODE_JLJG S ON S.CODE=T.JGFS_DM AND S.JCKBZ=T.JCKBZ_DM
        LEFT JOIN HX_CKTS.CKTS_TY_CKSPTSLWK A ON A.CKSP_DM=T.CKSP_DM AND T.CKRQ_1>=A.YXQQ AND T.CKRQ_1<=A.YXQZ
        LEFT JOIN HX_CKTS.CKTS_TY_CKSPTSLWK B ON B.CKSP_DM=SUBSTR(T.CKSP_DM,1,8) AND T.CKRQ_1>=B.YXQQ AND T.CKRQ_1<=B.YXQZ
       WHERE T.DJXH=CUR_SZC.DJXH
         AND T.BAH=CUR_SZC.BAH
         AND (REGEXP_LIKE(CUR_SZC.BAH,'^B|^C') OR 
              (REGEXP_LIKE(CUR_SZC.BAH,'^E|^H') AND T.CKRQ_1>=CUR_SZC.HXQSRQ AND T.CKRQ_1<=CUR_SZC.HXJZRQ));
    EXCEPTION
      WHEN OTHERS THEN
        LN_JSJKZZ := 0;
        LN_JSCKZZ := 0;
        LN_JSJKZZ_0654 :=0;
        LN_JSCKZZ_0654 :=0;
        LN_JSJKZZ_0654_ZS :=0;
        LN_JSCKZZ_0654_ZS :=0;
    END;
    BEGIN
      SELECT SUM(T.RMBLAJ),
             SUM(CASE WHEN NVL(NVL(A.CKSPTSSPLX_DM,B.CKSPTSSPLX_DM),'0')='1' THEN T.RMBLAJ ELSE 0 END)
        INTO LN_JSCKZZ_BGD201_0654, LN_JSCKZZ_BGD201_0654_ZS
        FROM HX_CKTS.CKTS_WBSJ_HG_BGD201 T
        LEFT JOIN HX_CKTS.CKTS_TY_CKSPTSLWK A ON A.CKSP_DM=T.CKSP_DM AND T.CKRQ_1>=A.YXQQ AND T.CKRQ_1<=A.YXQZ
        LEFT JOIN HX_CKTS.CKTS_TY_CKSPTSLWK B ON B.CKSP_DM=SUBSTR(T.CKSP_DM,1,8) AND T.CKRQ_1>=B.YXQQ AND T.CKRQ_1<=B.YXQZ
       WHERE T.DJXH=CUR_SZC.DJXH
         AND T.BAH=CUR_SZC.BAH
         AND T.JGFS_DM='0654'
         AND (REGEXP_LIKE(CUR_SZC.BAH,'^B|^C') OR 
              (REGEXP_LIKE(CUR_SZC.BAH,'^E|^H') AND T.CKRQ_1>=CUR_SZC.HXQSRQ AND T.CKRQ_1<=CUR_SZC.HXJZRQ));
    EXCEPTION
      WHEN OTHERS THEN
        LN_JSCKZZ_BGD201_0654 := 0;
        LN_JSCKZZ_BGD201_0654_ZS := 0;
    END;
    UPDATE TMP_20260519_JLSJGJZ_1 S
       SET S.JSJKZZ_HXGBD = LN_JSJKZZ,
           S.JSCKZZ_HXBGD = LN_JSCKZZ,
           S.JSJKZZ_HXGBD_0654 = LN_JSJKZZ_0654,
           S.JSCKZZ_HXBGD_0654 = LN_JSCKZZ_0654,
           S.JSJKZZ_HXGBD_0654_ZS = LN_JSJKZZ_0654_ZS,
           S.JSCKZZ_HXBGD_0654_ZS = LN_JSCKZZ_0654_ZS,
           S.JSCKZZ_BGD201_0654 = LN_JSCKZZ_BGD201_0654,
           S.JSCKZZ_BGD201_0654_ZS = LN_JSCKZZ_BGD201_0654_ZS
     WHERE S.DJXH = CUR_SZC.DJXH
       AND S.BAH = CUR_SZC.BAH
       AND S.HXQSRQ = CUR_SZC.HXQSRQ
       AND S.HXJZRQ = CUR_SZC.HXJZRQ;
    COMMIT;
  END LOOP;
/*
  SELECT S.ZGSWJ_DM,NVL(S.SHXYDM,S.NSRSBH),S.NSRMC,T.*
    FROM TMP_20260519_JLSJGJZ_1 T
   INNER JOIN HX_DJ.DJ_NSRXX S ON S.DJXH=T.DJXH
   WHERE T.JSJKZZ_HXGBD IS NOT NULL
   ORDER BY S.ZGSWJ_DM,T.BAH;
*/
END;
/
