<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<parent>
		<artifactId>tl-cloud-parent</artifactId>
		<groupId>com.tl</groupId>
		<version>3.0.0-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.tl</groupId>
	<artifactId>tl-bjts-sw</artifactId>
	<version>1.2.0</version>
	<packaging>jar</packaging>

	<profiles>
		<profile>
			<id>dev</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<profileActive>dev</profileActive>
				<cloud>80.64.64.21</cloud>
				<port>8848</port>
				<namespace>dc156618-612b-41ff-a96c-60fb95ed81e1</namespace>
				<discoverynamespace>dc156618-612b-41ff-a96c-60fb95ed81e1</discoverynamespace>
			</properties>
		</profile>
		<profile>
			<id>pro</id>
			<properties>
				<profileActive>pro</profileActive>
				<cloud>80.12.136.131</cloud>
				<port>8848</port>
				<namespace>5dc8adcf-6798-4cdf-8d85-952b17e5abd2</namespace>
				<discoverynamespace>5dc8adcf-6798-4cdf-8d85-952b17e5abd2</discoverynamespace>
			</properties>
		</profile>
		<profile>
			<id>nbpro</id>
			<properties>
				<profileActive>pro</profileActive>
				<cloud>80.27.64.53</cloud>
				<port>80</port>
				<namespace>03e257ec-2889-4bc4-ba5d-e1d8be5db831</namespace>
				<discoverynamespace>03e257ec-2889-4bc4-ba5d-e1d8be5db831</discoverynamespace>
			</properties>
		</profile>
		<profile>
			<id>test</id>
			<properties>
				<profileActive>test</profileActive>
				<cloud>80.64.64.21</cloud>
				<port>8848</port>
				<namespace>dc156618-612b-41ff-a96c-60fb95ed81e1</namespace>
				<discoverynamespace>dc156618-612b-41ff-a96c-60fb95ed81e1</discoverynamespace>
			</properties>
		</profile>
			<!--  浙江预生产环境  -->
		<profile>
			<id>pre</id>
			<properties>
				<profileActive>pre</profileActive>
				<cloud>80.12.136.175</cloud>
				<port>8848</port>
				<namespace>0bb52634-f6d5-437b-acd4-a2e9615bea5d</namespace>
				<discoverynamespace>0bb52634-f6d5-437b-acd4-a2e9615bea5d</discoverynamespace>
			</properties>
		</profile>
	</profiles>

	<dependencies>
		<dependency>
			<groupId>com.tl</groupId>
			<artifactId>tl-common</artifactId>
		</dependency>
		<dependency>
			<groupId>com.tl</groupId>
			<artifactId>tl-redis-shiro</artifactId>
		</dependency>
		<dependency>
			<groupId>com.tl</groupId>
			<artifactId>tl-common-ext</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-amqp</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-jexl</artifactId>
			<version>2.1.1</version>
		</dependency>

		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bootstrap</artifactId>
		</dependency>


		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</dependency>

		<dependency>
			<groupId>org.mybatis.spring.boot</groupId>
			<artifactId>mybatis-spring-boot-starter</artifactId>
		</dependency>
		<!--数据源-->
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>druid</artifactId>
			<version>1.0.29</version>
		</dependency>
		<!--数据库 驱动-->
		<dependency>
			<groupId>oracle</groupId>
			<artifactId>ojdbc14</artifactId>
			<version>10.2.0.4.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.8</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
		</dependency>

		<!--pagehelper-->
		<dependency>
			<groupId>com.github.pagehelper</groupId>
			<artifactId>pagehelper-spring-boot-starter</artifactId>
		</dependency>

		<!--通用mapper-->
		<dependency>
			<groupId>tk.mybatis</groupId>
			<artifactId>mapper-spring-boot-starter</artifactId>
			<version>2.0.1</version>
		</dependency>


		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.0.0</version>
		</dependency>


		<dependency>
			<groupId>net.sourceforge.jexcelapi</groupId>
			<artifactId>jxl</artifactId>
			<version>2.6.12</version>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
		</dependency>
		<dependency>
			<groupId>com.tl</groupId>
			<artifactId>tl-bjts-swgl-general</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>

		<!-- 阿里云oss -->
		<dependency>
			<groupId>com.aliyun.oss</groupId>
			<artifactId>aliyun-sdk-oss</artifactId>
			<version>3.5.0</version>
		</dependency>

		<!--  华为云obs  -->
		<dependency>
			<groupId>com.huaweicloud</groupId>
			<artifactId>esdk-obs-java-bundle</artifactId>
			<version>[3.21.8,)</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.mybatis.generator</groupId>
				<artifactId>mybatis-generator-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<excludes>
					<exclude>application.properties</exclude>
					<exclude>bootstrap.properties</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>application.properties</include>
					<include>bootstrap.properties</include>
				</includes>
			</resource>

			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<excludes>
					<exclude>**/**/*.json</exclude>
					<exclude>**/**/*.xls</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<includes>
					<include>**/**/*.json</include>
					<include>**/**/*.xls</include>
				</includes>
			</resource>
		</resources>

	</build>
</project>
