DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W30206$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W30206
/*
 * 企业本年度出口额相较于上一年度变动情况（首次申报不晚于上月的前一年年初）
 * ZB_VAL：本年出口额大于等于100W，超过上年全年1.5倍返回1，否则返回0
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_JQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    --参数1
  DECLARE VAL2         DECIMAL(18,2);    --参数2
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W30206_CKE_JE';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W30206_CKE_HB';

    SELECT S.CK_CKEUSD
      INTO V_THIS_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;
    SELECT S.CK_CKEUSD
      INTO V_LAST_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_JQID;

    SET V_PARAMS = '[d]报告期出口额=' || V_THIS_DATA || '|基期出口额=' || V_LAST_DATA;
    IF V_LAST_DATA<=0 THEN
      SET V_ZB_VAL = NULL;
    ELSEIF V_THIS_DATA>=VAL1 AND V_THIS_DATA>=VAL2 * V_LAST_DATA THEN
      SET V_ZB_VAL =1;
    ELSE
      SET V_ZB_VAL =0;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30206' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W30206',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30206';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
