DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DEAL_HWCYTS$$

CREATE PROCEDURE PRO_DEAL_HWCYTS()
/*
 * 处理海外仓预退税数据
 */
routine_body: BEGIN
  DECLARE V_BEGINDATE      DATETIME;
  DECLARE LC_SBYY          VARCHAR(2000);

  SET V_BEGINDATE = ORA_DATE_ADD(DATE(CURRENT_TIMESTAMP), -(3));

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('RCGL_SDQY_9810数据处理开始...');
  COMMIT;

  -- 免抵退税
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET LC_SBYY =BJTS_SQLERRM_003;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('CKTS_SB_MDT_CKMX-->RCGL_SDQY_9810失败！', LC_SBYY);
      COMMIT;

  END;
INSERT INTO RCGL_SDQY_9810 (ID,DJXH,NSRSBH,NSRMC,SWJGDM,QYBJ,CJR,CRTIME)
SELECT B.DJXH,B.DJXH,B.NSRSBH,B.NSRMC,B.TSSWJG_DM,'Y','SYSTEM',CURRENT_TIMESTAMP
FROM (
SELECT DISTINCT S.DJXH,IFNULL(T.SHXYNO, T.NSRDJNO) AS NSRSBH,T.NSRMC,S.TSSWJG_DM
                  FROM CKTS_SB_MDT_CKMX S
                 INNER JOIN GLXT_BB_SHXT_DJXX T ON T.DJXH_JS=S.DJXH
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND REGEXP_LIKE(S.CKTMSYWLXDMJH,'HWC-YT')
) AS B
WHERE NOT EXISTS (
  SELECT 1 FROM RCGL_SDQY_9810 AS A WHERE A.DJXH=B.DJXH
);
    COMMIT;
  END;

  -- 免退税
  BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
      SET LC_SBYY =BJTS_SQLERRM_002;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('CKTS_SB_MTS_CKMX-->RCGL_SDQY_9810失败！', LC_SBYY);
      COMMIT;

  END;
INSERT INTO RCGL_SDQY_9810 (ID,DJXH,NSRSBH,NSRMC,SWJGDM,QYBJ,CJR,CRTIME)
SELECT B.DJXH,B.DJXH,B.NSRSBH,B.NSRMC,B.TSSWJG_DM,'Y','SYSTEM',CURRENT_TIMESTAMP
FROM (
SELECT DISTINCT S.DJXH,IFNULL(T.SHXYNO, T.NSRDJNO) AS NSRSBH,T.NSRMC,S.TSSWJG_DM
                  FROM CKTS_SB_MTS_CKMX S
                 INNER JOIN GLXT_BB_SHXT_DJXX T ON T.DJXH_JS=S.DJXH
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND REGEXP_LIKE(S.CKTMSYWLXDMJH,'HWC-YT')
) AS B
WHERE NOT EXISTS (
  SELECT 1 FROM RCGL_SDQY_9810 AS A WHERE A.DJXH=B.DJXH
);
    COMMIT;
  END;

  -- 代办退税
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET LC_SBYY =BJTS_SQLERRM_001;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('CKTS_SB_WZF_CKMX-->RCGL_SDQY_9810失败！', LC_SBYY);
      COMMIT;

  END;
INSERT INTO RCGL_SDQY_9810 (ID,DJXH,NSRSBH,NSRMC,SWJGDM,QYBJ,CJR,CRTIME)
SELECT B.DJXH,B.DJXH,B.NSRSBH,B.NSRMC,B.TSSWJG_DM,'Y','SYSTEM',CURRENT_TIMESTAMP
FROM (
SELECT DISTINCT S.DJXH,IFNULL(T.SHXYNO, T.NSRDJNO) AS NSRSBH,T.NSRMC,S.TSSWJG_DM
                  FROM CKTS_SB_WZF_CKMX S
                 INNER JOIN GLXT_BB_SHXT_DJXX T ON T.DJXH_JS=S.DJXH
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND REGEXP_LIKE(S.CKTMSYWLXDMJH,'HWC-YT')
) AS B
WHERE NOT EXISTS (
  SELECT 1 FROM RCGL_SDQY_9810 AS A WHERE A.DJXH=B.DJXH
);
    COMMIT;
  END;

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('RCGL_SDQY_9810数据处理结束。');
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
