DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S10201$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S10201
/*
 * 平均固定资产销售额，取统计期往前一年的数据
 * ZB_VAL：销售额/固定资产总额
 */
(
  IN P_BGQID DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
    SELECT (S.ZC_GDZC_QC + S.ZC_GDZC_QM)/2, S.ZZS_XSE_QB,
           '[d]增值税全部销售额=' || S.ZZS_XSE_QB || '|期初固定资产=' || S.ZC_GDZC_QC || '|期末固定资产=' || S.ZC_GDZC_QM
      INTO V_THIS_DATA, V_LAST_DATA, V_PARAMS
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;
    IF V_THIS_DATA>1 AND V_LAST_DATA>0 THEN
      SET V_ZB_VAL = V_LAST_DATA/V_THIS_DATA;
    ELSE
      SET V_ZB_VAL = NULL;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10201' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10201',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10201';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
