DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W20101$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W20101
/*
 * 跨大类商品退税额
 * ZB_VAL：跨大类商品退税额>XX AND 跨大类商品退税额/报告期_退税额>YY%，返回1
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_JQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    --参数1
  DECLARE VAL2         DECIMAL(18,2);    --参数2
  DECLARE V_PARAMS     VARCHAR(4000);
  DECLARE V_PARAM2     VARCHAR(4000);

  BEGIN
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W20101_KDLSP_TSE';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W20101_KDLSP_ZB';

    SELECT T.TS_TSE_SB+T.TS_MDE_SB
      INTO V_THIS_DATA
      FROM JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    SET V_ROWS = 0;
    SET V_PARAM2 = '';
    SET V_LAST_DATA =0;
    FOR CUR_SPDM IN (SELECT T.SP_DL, DM.CKSP_MC, SUM(T.SBTMSE) AS SBTMSE
                       FROM JKGL_DATA_TJ_ZBU_TSSP T
                       LEFT JOIN JCFX_DM_CKSPTREE DM ON DM.CKSP_DM=T.SP_DL AND DM.CKSP_JC='2'
                      WHERE T.BGQID=P_BGQID
                        AND NOT EXISTS (SELECT 1
                                          FROM JKGL_DATA_TJ_ZBU_TSSP S
                                         WHERE S.BGQID=P_JQID
                                           AND S.SP_DL=T.SP_DL)
                      GROUP BY T.SP_DL, DM.CKSP_MC)
    LOOP
      SET V_ROWS = V_ROWS +1;
      SET V_LAST_DATA = V_LAST_DATA + CUR_SPDM.SBTMSE;
      IF V_ROWS<=20 THEN
        SET V_PARAM2 = V_PARAM2 || '|跨大类商品代码=' || CUR_SPDM.SP_DL || '（' || CUR_SPDM.CKSP_MC ||'），申报退免税额=' || CUR_SPDM.SBTMSE;
      END IF;
    END LOOP;
    IF V_ROWS>20 THEN
      SET V_PARAM2 = V_PARAM2 || '|...';
    END IF;

    SET V_PARAMS = '[d]报告期申报退(免)税额=' || V_THIS_DATA || '|其中跨大类商品申报退(免)税额=' || V_LAST_DATA;
    IF V_THIS_DATA>0 AND V_LAST_DATA>0 THEN
      IF V_LAST_DATA>=VAL2 AND V_LAST_DATA>=V_THIS_DATA * VAL1 THEN
        SET V_ZB_VAL = 1;
      ELSE
        SET V_ZB_VAL = 0;
      END IF;
      SET V_PARAMS = V_PARAMS || '|占比=' || ROUND(100 * V_LAST_DATA / V_THIS_DATA,2) || '%';
    ELSE
      SET V_ZB_VAL = 0;
    END IF;
    SET V_PARAMS = V_PARAMS || V_PARAM2;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20101' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W20101',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20101';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
