DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S20103$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S20103
/*
 * 跨大类商品退税额
 * ZB_VAL：跨大类商品退税额>XX AND 跨大类商品退税额/报告期_退税额>YY%，返回1
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_JQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    -- 参数1
  DECLARE VAL2         DECIMAL(18,2);    -- 参数2
  DECLARE V_PARAMS     VARCHAR(4000);
  DECLARE V_PARAM2     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S20103_TMSE_ZB';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S20103_TMSE_JE';

    SELECT T.TS_TSE_SB+T.TS_MDE_SB
      INTO V_THIS_DATA
      FROM JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    SET V_ROWS = 0;
    SET V_PARAM2 = '';
    SET V_LAST_DATA =0;
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_SPDM_SP_DL_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_CKSP_MC_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_SBTMSE_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.SP_DL, DM.CKSP_MC, SUM(T.SBTMSE) AS SBTMSE
                       FROM JKGL_DATA_TJ_ZBU_TSSP T
                       LEFT JOIN JCFX_DM_CKSPTREE DM ON DM.CKSP_DM=T.SP_DL AND DM.CKSP_JC='2'
                      WHERE T.BGQID=P_BGQID
                        AND NOT EXISTS (SELECT 1
                                          FROM JKGL_DATA_TJ_ZBU_TSSP S
                                         WHERE S.BGQID=P_JQID
                                           AND S.SP_DL=T.SP_DL)
                      GROUP BY T.SP_DL, DM.CKSP_MC;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_SPDM_SP_DL_001, BJTS_CUR_SPDM_CKSP_MC_001, BJTS_CUR_SPDM_SBTMSE_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET V_ROWS = V_ROWS +1;
      SET V_LAST_DATA = V_LAST_DATA + BJTS_CUR_SPDM_SBTMSE_001;
      IF V_ROWS<=20 THEN
        SET V_PARAM2 = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(V_PARAM2, '|跨大类商品='), BJTS_CUR_SPDM_SP_DL_001), '（'), BJTS_CUR_SPDM_CKSP_MC_001), '），申报退（免）税额='), BJTS_CUR_SPDM_SBTMSE_001);
      END IF;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
    IF V_ROWS>20 THEN
      SET V_PARAM2 = ORA_CONCAT(V_PARAM2, '|...');
    END IF;

    SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]报告期申报退（免）税额=', V_THIS_DATA), '|其中跨大类商品申报退（免）税额='), V_LAST_DATA);
    IF V_THIS_DATA>0 AND V_LAST_DATA>0 THEN
      IF V_LAST_DATA>=VAL2 AND V_LAST_DATA>=V_THIS_DATA * VAL1 THEN
        SET V_ZB_VAL = 1;
      ELSE
        SET V_ZB_VAL = 0;
      END IF;
      SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(V_PARAMS, '|占比='), ROUND(100 * V_LAST_DATA / V_THIS_DATA,2)), '%');
    ELSE
      SET V_ZB_VAL = NULL;
    END IF;
    SET V_PARAMS = ORA_CONCAT(V_PARAMS, V_PARAM2);
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S20103' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S20103',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S20103';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
