DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W20201$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W20201
/*
 * (报关单每单的每美元利润<本企业每美元利润中位数*下限%
 * or 报关单每单的每美元利润>本企业每美元利润中位数*上限%）的出口额合计/报告期_出口额>80%
 * ZB_VAL：
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10),
  IN P_BGQ_Q DATETIME,
  IN P_BGQ_Z DATETIME
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_MEDIAN     DECIMAL(18,3);
  DECLARE V_MAX        DECIMAL(18,3);
  DECLARE V_MIN        DECIMAL(18,3);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT SUM(CKEUSD), MEDIAN(MMYLR), MAX(MMYLR), MIN(MMYLR)
      INTO V_THIS_DATA, V_MEDIAN, V_MAX, V_MIN
      FROM (SELECT SUBSTR(T.CKBGDH,1,18) AS CKBGDH, SUM(T.MYLAJ) AS CKEUSD, SUM(T.RMBLAJ) AS CKERMB, SUM(T.JSJE) AS JHJE,
                   CASE WHEN SUM(T.MYLAJ)<=0 THEN 0 ELSE ROUND((SUM(T.RMBLAJ) - SUM(T.JSJE)) / SUM(T.MYLAJ),2) END AS MMYLR
              FROM JCFX_DATA_TSSBMX T
             WHERE T.DJXH=P_DJXH
               AND T.SBRQ>=P_BGQ_Q AND T.SBRQ<P_BGQ_Z+1
             GROUP BY SUBSTR(T.CKBGDH,1,18)) TT;

    SET V_PARAMS = '[d]报告期出口额=' || V_THIS_DATA || '|本企业每美元利润中位数=' || V_MEDIAN ||
                '|本企业每美元利润最大值=' || V_MAX || '|本企业每美元利润最小值=' || V_MIN;
    SET V_MAX = (V_MAX + V_MEDIAN) /2;
    SET V_MIN = (V_MIN + V_MEDIAN) /2;
    SET V_PARAMS = V_PARAMS || '|按大于上限=' || V_MAX || '|或小于下限=' || V_MIN;

    SELECT SUM(CKEUSD)
      INTO V_LAST_DATA
      FROM (SELECT SUBSTR(T.CKBGDH,1,18) AS CKBGDH, SUM(T.MYLAJ) AS CKEUSD, SUM(T.RMBLAJ) AS CKERMB, SUM(T.JSJE) AS JHJE,
                   CASE WHEN SUM(T.MYLAJ)<=0 THEN 0 ELSE ROUND((SUM(T.RMBLAJ) - SUM(T.JSJE)) / SUM(T.MYLAJ),2) END AS MMYLR
              FROM JCFX_DATA_TSSBMX T
             WHERE T.DJXH=P_DJXH
               AND T.SBRQ>=P_BGQ_Q AND T.SBRQ<P_BGQ_Z+1
             GROUP BY SUBSTR(T.CKBGDH,1,18)) TT
     WHERE MMYLR>V_MAX OR MMYLR<V_MIN;
    SET V_PARAMS = V_PARAMS || '|与中位数偏离较大的出口额=' || V_LAST_DATA;

    IF V_THIS_DATA<=0 OR V_LAST_DATA<0 THEN
      SET V_ZB_VAL = NULL;
    ELSE
      SET V_ZB_VAL =ROUND(100 * V_LAST_DATA / V_THIS_DATA, 2);
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20201' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W20201',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20201';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
