DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DEAL_JCFX_NSR_BLV$$

CREATE PROCEDURE PRO_DEAL_JCFX_NSR_BLV
routine_body: BEGIN
  DECLARE LN_CKBGDFS       BIGINT;
  DECLARE LN_CKMYLAJ       DECIMAL(18,2);
  DECLARE LN_SBMYLAJ       DECIMAL(18,2);
  DECLARE LN_SBTMSE         DECIMAL(18,2);
  DECLARE LN_SBMDE         DECIMAL(18,2);
  DECLARE LC_CKGM          VARCHAR(1);
  DECLARE LN_MDBLV         DECIMAL(10,6);
  DECLARE LC_MDBLV         VARCHAR(1);

  FOR CUR_NSR IN (SELECT T.DJXH_JS FROM GLXT_BB_SHXT_DJXX T)
  LOOP
    SELECT COUNT(DISTINCT SUBSTR(S.CKBGDH,1,18)), IFNULL(SUM(S.MYLAJ), 0)
      INTO LN_CKBGDFS, LN_CKMYLAJ
      FROM CKTS_WBSJ_HG_BGD S
     WHERE S.DJXH=CUR_NSR.DJXH_JS
       AND S.CKRQ_1>=DATE_ADD(TRUNCATE(CURRENT_TIMESTAMP, 'YY'), INTERVAL -12 MONTH)
       AND S.CKRQ_1< TRUNCATE(CURRENT_TIMESTAMP, 'YY');
    
    SELECT IFNULL(SUM(S.USD_AMT), 0), IFNULL(SUM(S.SB_TS_AMT), 0)+ IFNULL(SUM(S.SB_MD_AMT), 0), IFNULL(SUM(S.SB_MD_AMT), 0)
      INTO LN_SBMYLAJ, LN_SBTMSE, LN_SBMDE
      FROM GLXT_BB_SHXT_LCXX S 
     WHERE S.DJXH=CUR_NSR.DJXH_JS 
       AND IFNULL(S.SL_DATE, S.SB_DATE)>=DATE_ADD(TRUNCATE(CURRENT_TIMESTAMP, 'YY'), INTERVAL -12 MONTH)
       AND IFNULL(S.SL_DATE, S.SB_DATE)< TRUNCATE(CURRENT_TIMESTAMP, 'YY');
     
    SET LC_CKGM = CASE WHEN LN_SBMYLAJ>=100000000 THEN 'A' 
                    WHEN LN_SBMYLAJ>=50000000 THEN 'B' 
                    WHEN LN_SBMYLAJ>=10000000 THEN 'C' 
                    WHEN LN_SBMYLAJ>=1000000 THEN 'D' 
                    ELSE 'E' END;
    
    IF LN_SBMDE<=0 THEN
      SET LN_MDBLV = 0;
    ELSEIF LN_SBTMSE<0 THEN
      SET LN_MDBLV = 100;
    ELSE
      SET LN_MDBLV = 100 * LN_SBMDE / LN_SBTMSE;
    END IF;
    SET LC_MDBLV = CASE WHEN LN_MDBLV>=40 THEN 'A' 
                     WHEN LN_MDBLV>=30 THEN 'B' 
                     WHEN LN_MDBLV>=20 THEN 'C' 
                     WHEN LN_MDBLV>=10 THEN 'D' 
                     ELSE 'E' END;
    
    UPDATE GLXT_BB_SHXT_DJXX A
       SET A.CK_BGDFS = LN_CKBGDFS,
           A.CK_MYLAJ = LN_CKMYLAJ,
           A.CKGM     = LN_SBMYLAJ,
           A.SB_TMSE  = LN_SBTMSE,
           A.SB_MDE   = LN_SBMDE,
           A.MDBLV    = LN_MDBLV,
           A.CKGM_DM  = LC_CKGM,
           A.MDBLV_DM = LC_MDBLV
     WHERE A.DJXH_JS=CUR_NSR.DJXH_JS;
    COMMIT;
  END LOOP;

  LEAVE routine_body;
END$$

DELIMITER ;
