DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W10102$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W10102
/*
 * 布尔，报告期内是否变更法人代表
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10),
  IN P_BGQ_Q DATETIME,
  IN P_BGQ_Z DATETIME
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = 0;

  END;
SELECT ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]变更日期=', DATE_FORMAT(LRRQ, '%Y%m%d')), '|变更前内容='), BGQNR), '|变更后内容='), BGHNR)
      INTO V_PARAMS
      FROM (SELECT *
              FROM CKTS_DJ_BGDJMX T
             WHERE T.DJXH=P_DJXH AND T.LRRQ>=P_BGQ_Q AND T.LRRQ<ORA_DATE_ADD(P_BGQ_Z, 1)
               AND T.BGQNR<>T.BGHNR
             ORDER BY T.LRRQ DESC)
     WHERE 1=1
LIMIT 1;
     IF V_PARAMS IS NOT NULL THEN
       SET V_ZB_VAL =1;
     ELSE
       SET V_ZB_VAL =0;
     END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10102' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W10102',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10102';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
