DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S10104$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S10104
/*
 * 出口企业出口企业法定代表人年龄是否异常
 * ZB_VAL：法定代表人年龄小于19周岁；企业经营期未满三年且法人代表年龄大于65周岁，返回1
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10),
  IN P_BGQ_Z DATETIME,
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_ZJLX       VARCHAR(50);
  DECLARE V_ZJHM       VARCHAR(50);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    --参数1
  DECLARE VAL2         DECIMAL(18,2);    --参数2
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S10104_AGE_LOWER';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S10104_AGE_UPPER';

    SELECT FRDB_ZJLX, FRDB_ZJHM
      INTO V_ZJLX, V_ZJHM
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.DJXH_JS=P_DJXH;

    IF V_ZJLX='201' AND LENGTH(V_ZJHM)=15 THEN
      SET V_THIS_DATA = EXTRACT(YEAR FROM P_BGQ_Z) - CAST('19'||SUBSTR(V_ZJHM,7,2) AS DECIMAL(65,30));
    ELSEIF V_ZJLX='201' AND LENGTH(V_ZJHM)=18 THEN
      SET V_THIS_DATA = EXTRACT(YEAR FROM P_BGQ_Z) - CAST(SUBSTR(V_ZJHM,7,4) AS DECIMAL(65,30));
    ELSE
      SET V_THIS_DATA = 0;
    END IF;

    SELECT FLOOR(TIMESTAMPDIFF(MONTH, MAX(IFNULL(S.LRRQ, T.SWDJ_DATE)), P_BGQ_Z))
      INTO V_LAST_DATA
      FROM GLXT_BB_SHXT_DJXX T
      LEFT JOIN CKTS_DJ_BGDJMX S ON S.DJXH=T.DJXH_JS AND S.LRRQ<=P_BGQ_Z
     WHERE T.DJXH_JS=P_DJXH;

    IF V_THIS_DATA<=0 THEN
      SET V_ZB_VAL = NULL;
    ELSEIF V_THIS_DATA<VAL1 THEN
      SET V_ZB_VAL = 1;
    ELSEIF V_THIS_DATA>VAL2 AND V_LAST_DATA<36 THEN
      SET V_ZB_VAL = 1;
    ELSE
      SET V_ZB_VAL = 0;
    END IF;

    SET V_PARAMS = '[d]法定代表人证件号码=' || V_ZJHM || '|经营期限=' || V_LAST_DATA || '个月';
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10104' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10104',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10104';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
