DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W10403$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W10403
/*
 * 法人兼营多家企业
 * ZB_VAL：企业法人兼营的企业户数，目前未计算股东兼营情况
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_ZJHM       VARCHAR(50);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT T.FRDB_ZJHM,
           '[d]企业法人证件号码=' || T.FRDB_ZJHM || '，法人兼营企业列表：'
      INTO V_ZJHM, V_PARAMS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.DJXH_JS=P_DJXH
       AND ROWNUM=1;

    SET V_ZB_VAL = 0;
    FOR CUR_SPDM IN (SELECT DISTINCT T.NSRSBH, T.NSRMC
                       FROM CKTS_DJ_NSRXX T
                      WHERE T.FDDBRSFZJHM = V_ZJHM
                        AND T.NSRZT_DM NOT IN ('07','13')
                        AND LENGTH(T.NSRSBH)=18
                        AND SUBSTR(T.NSRSBH,1,1)<>'L'
                        AND T.NSRMC NOT LIKE '%车购税%')
    LOOP
      SET V_ZB_VAL = V_ZB_VAL +1;
      IF V_ZB_VAL<=20 THEN
        SET V_PARAMS = V_PARAMS || '|税号=' || CUR_SPDM.NSRSBH || '，名称=' || CUR_SPDM.NSRMC;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      SET V_PARAMS = V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10403' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W10403',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10403';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
