DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S30602$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S30602
/*
 * 出口同一国别（地区）货代（申报单位）数量超5个。
 * ZB_VAL：存在大于5个货代（申报单位）的出口国别数量
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE VAL1         DECIMAL(18,2);    -- 参数1
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30602_GB_SBDW_SL';

    SET V_ZB_VAL = 0;
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_SPDM_GB_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_CKGB_MC_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_SBDWSL_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.GB_DM,DM.CKGB_MC,T.SBDWSL
                       FROM JKGL_DATA_TJ_ZBU_CKGB T
                       LEFT JOIN JCFX_DM_CKGB DM ON DM.CKGB_DM=T.GB_DM
                      WHERE T.BGQID=P_BGQID
                        AND T.SBDWSL>VAL1
                        AND T.GB_DM<>'142';
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_SPDM_GB_DM_001, BJTS_CUR_SPDM_CKGB_MC_001, BJTS_CUR_SPDM_SBDWSL_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET V_ZB_VAL = V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]国别代码=', BJTS_CUR_SPDM_GB_DM_001), '（'), BJTS_CUR_SPDM_CKGB_MC_001), '），申报单位数量='), BJTS_CUR_SPDM_SBDWSL_001);
      ELSEIF V_ZB_VAL<=20 THEN
        SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(V_PARAMS, '|国别代码='), BJTS_CUR_SPDM_GB_DM_001), '（'), BJTS_CUR_SPDM_CKGB_MC_001), '），申报单位数量='), BJTS_CUR_SPDM_SBDWSL_001);
      END IF;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
    IF V_ZB_VAL>20 THEN
      SET V_PARAMS = ORA_CONCAT(V_PARAMS, '|...');
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30602' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30602',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30602';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
