DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W40201$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W40201
/*
 * ZB_VAL：
 * 进项发票开具日期滞后于货物出口日期超过90天的，金额超过XX1或占比超过XX2%或票数超过XX3票，返回2
 * 否则，进项发票开具日期滞后于货物出口日期超过60天的，金额超过YY1或占比超过YY2%或票数超过YY3票，返回1
 * 否则，返回0
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_TOTAL_AMT  DECIMAL(18,2);
  DECLARE V_THIS_DAT1  DECIMAL(18,2);
  DECLARE V_LAST_DAT1  DECIMAL(18,2);
  DECLARE V_THIS_DAT2  DECIMAL(18,2);
  DECLARE V_LAST_DAT2  DECIMAL(18,2);
  DECLARE VAL11        DECIMAL(18,2);    --参数1
  DECLARE VAL12        DECIMAL(18,2);    --参数2
  DECLARE VAL13        DECIMAL(18,2);    --参数3
  DECLARE VAL21        DECIMAL(18,2);    --参数1
  DECLARE VAL22        DECIMAL(18,2);    --参数2
  DECLARE VAL23        DECIMAL(18,2);    --参数3
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL11
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40201_CQKP1_FS';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL12
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40201_CQKP1_JE';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL13
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40201_CQKP1_ZB';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL21
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40201_CQKP2_FS';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL22
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40201_CQKP2_JE';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL23
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40201_CQKP2_ZB';

    SELECT T.TS_JHFP_JE, T.TS_JHFP_JE_CQ1, T.TS_JHFP_FS_CQ1, T.TS_JHFP_JE_CQ2, T.TS_JHFP_FS_CQ2 
      INTO V_TOTAL_AMT, V_THIS_DAT1, V_LAST_DAT1, V_THIS_DAT2, V_LAST_DAT2
      FROM JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    SET V_PARAMS = '[d]报告期退税发票金额=' || V_TOTAL_AMT
             || '|滞后60天及以上开票金额=' || V_THIS_DAT1 || '，开票份数=' || V_LAST_DAT1
             || '|滞后90天及以上开票金额=' || V_THIS_DAT2 || '，开票份数=' || V_LAST_DAT2;
    IF V_TOTAL_AMT <= 0 THEN
      SET V_ZB_VAL = 0;
    ELSEIF V_LAST_DAT2>VAL21 OR V_THIS_DAT2>=VAL22 OR V_THIS_DAT2>=VAL23*V_TOTAL_AMT THEN
      SET V_ZB_VAL =2;
    ELSEIF V_LAST_DAT1>VAL11 OR V_THIS_DAT1>=VAL12 OR V_THIS_DAT1>=VAL13*V_TOTAL_AMT THEN
      SET V_ZB_VAL =1;
    ELSE
      SET V_ZB_VAL =0;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40201' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W40201',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40201';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
