DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W50302$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W50302
/*
 * 应收账款占营业收入比重
 * ZB_VAL：100% * 期末应收 / 营业收入
 */
(
  IN P_BGQID DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT T.LR_YYSR, T.ZC_YSZK_QM,
           ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]营业收入=', T.LR_YYSR), '|期末应收='), T.ZC_YSZK_QM)
      INTO V_LAST_DATA, V_THIS_DATA, V_PARAMS
      FROM JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    SET V_ZB_VAL = ROUND(100 * V_THIS_DATA / V_LAST_DATA, 2);
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50302' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W50302',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50302';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
