DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S30203$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S30203
/*
 * 出口额超1WUSD且商品_平均出口单价环比>150% 的商品数量
 * ZB_VAL：商品出口额超1WUSD且平均出口单价环比>150% 的商品个数
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_JQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE VAL1         DECIMAL(18,2);    -- 参数1
  DECLARE VAL2         DECIMAL(18,2);    -- 参数1
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30203_SP_DJ_HB';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30203_SP_CKE_JE';

    SET V_ZB_VAL = 0;
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_SPDM_SP8_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_CKSP_MC_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_CKEUSD_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_CKDJ_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_JQDJ_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.SP8_DM, DM.CKSP_MC,T.CKEUSD,T.CKDJ,S.CKDJ AS JQDJ
                       FROM JKGL_DATA_TJ_ZBU_CKSP T
                      INNER JOIN JKGL_DATA_TJ_ZBU_CKSP S ON S.BGQID=P_JQID AND S.SP8_DM=T.SP8_DM
                       LEFT JOIN JCFX_DM_CKSPTREE DM ON DM.CKSP_DM=T.SP8_DM AND DM.CKSP_JC='4'
                      WHERE T.BGQID=P_BGQID
                        AND T.CKEUSD>=VAL2
                        AND T.CKDJ>=VAL1 * S.CKDJ;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_SPDM_SP8_DM_001, BJTS_CUR_SPDM_CKSP_MC_001, BJTS_CUR_SPDM_CKEUSD_001, BJTS_CUR_SPDM_CKDJ_001, BJTS_CUR_SPDM_JQDJ_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET V_ZB_VAL = V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]商品代码=', BJTS_CUR_SPDM_SP8_DM_001), '（'), BJTS_CUR_SPDM_CKSP_MC_001), '），报告期出口额='), BJTS_CUR_SPDM_CKEUSD_001), '，出口单价='), BJTS_CUR_SPDM_CKDJ_001), '，基期单价='), BJTS_CUR_SPDM_JQDJ_001);
      ELSEIF V_ZB_VAL<=20 THEN
        SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(V_PARAMS, '|商品代码='), BJTS_CUR_SPDM_SP8_DM_001), '（'), BJTS_CUR_SPDM_CKSP_MC_001), '），报告期出口额='), BJTS_CUR_SPDM_CKEUSD_001), '，出口单价='), BJTS_CUR_SPDM_CKDJ_001), '，基期单价='), BJTS_CUR_SPDM_JQDJ_001);
      END IF;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
    IF V_ZB_VAL>20 THEN
      SET V_PARAMS = ORA_CONCAT(V_PARAMS, '|...');
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30203' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30203',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30203';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
