DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W40105$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W40105
/*
 * 外贸企业使用非正常户或注销户供货纳税人开具的增值税专用发票申报出口退税，
 * 外贸企业连续12个月内使用3户以上,且占该期间全部供货纳税人户数10%以上的。
 * ZB_VAL：是1，否0
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    -- 参数1
  DECLARE VAL2         DECIMAL(18,2);    -- 参数2
  DECLARE V_PARAMS     VARCHAR(4000);
  DECLARE V_PARAM2     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40105_FZCQYGH_SL';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40105_FZCQYGH_SL_ZB';

    SELECT T.TS_GHS_NUM
      INTO V_THIS_DATA
      FROM JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    IF V_THIS_DATA < 1 THEN
      SET V_ZB_VAL = NULL;
    ELSE
      SET V_LAST_DATA = 0;
      SET V_PARAM2 = '';
      BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_SPDM_GHFSH_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_QYMC_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_TSE_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.GHFSH, S.QYMC, SUM(T.TSE) AS TSE
                         FROM JKGL_DATA_TJ_ZBU_TSGH T
                        INNER JOIN JKGL_GY_GHQYXX S ON S.QYSBH=T.GHFSH
                        WHERE T.BGQID=P_BGQID AND IFNULL(S.NSRZT_DM, '03')='05'
                        GROUP BY T.GHFSH, S.QYMC
                        ORDER BY SUM(T.TSE) DESC;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_SPDM_GHFSH_001, BJTS_CUR_SPDM_QYMC_001, BJTS_CUR_SPDM_TSE_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
        SET V_LAST_DATA = V_LAST_DATA +1;
        IF V_LAST_DATA<=20 THEN
          SET V_PARAM2 = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(V_PARAM2, '|非正常企业税号='), BJTS_CUR_SPDM_GHFSH_001), '（'), BJTS_CUR_SPDM_QYMC_001), '），退税额='), BJTS_CUR_SPDM_TSE_001);
        ELSE
          SET V_PARAM2 = ORA_CONCAT(V_PARAM2, '|...');
        END IF;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

      SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]报告期供货企业户数=', V_THIS_DATA), '|供货企业非正常户数='), V_LAST_DATA), V_PARAM2);
      IF V_LAST_DATA>=VAL1 OR V_LAST_DATA>=VAL2*V_THIS_DATA THEN
        SET V_ZB_VAL =1;
      ELSE
        SET V_ZB_VAL =0;
      END IF;
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40105' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W40105',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40105';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
