DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S20101$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S20101
/*
 * 应退税额占比，取统计期往前一年的数据
 * ZB_VAL：出口销售额占全部销售额比例90%以下但应退税额占免抵退税额比例达90%以上，返回1
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_THIS_AMT   DECIMAL(18,2);
  DECLARE V_LAST_AMT   DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    --参数1
  DECLARE VAL2         DECIMAL(18,2);    --参数2
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S20101_YTMDZB';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S20101_CKXSZB';

    SELECT S.ZZS_XSE_QB, S.ZZS_XSE_MDT + S.ZZS_XSE_MS, S.TS_MDE_SB + S.TS_TSE_SB, S.TS_TSE_SB
      INTO V_THIS_DATA, V_LAST_DATA, V_THIS_AMT, V_LAST_AMT
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;

    SET V_PARAMS = '[d]报告期销售额=' || V_THIS_DATA || '|报告期出口销售额=' || V_LAST_DATA ||
                '|报告期申报退（免）税额=' || V_THIS_AMT || '|报告期申报退税额=' || V_LAST_AMT;
    IF V_THIS_DATA>0 AND V_LAST_DATA>0 AND V_THIS_AMT>0 AND V_LAST_AMT>0 THEN
      IF V_LAST_DATA<=V_THIS_DATA * VAL2 AND V_LAST_AMT>=V_THIS_AMT * VAL1 THEN
        SET V_ZB_VAL = 1;
      ELSE
        SET V_ZB_VAL = 0;
      END IF;
      SET V_PARAMS = V_PARAMS || '|出口销售额占比=' || ROUND(100 * V_LAST_DATA / V_THIS_DATA,2) ||
                  '%|退税额占比=' || ROUND(100 * V_LAST_AMT / V_THIS_AMT,2) || '%';
    ELSE
      SET V_ZB_VAL = NULL;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S20101' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S20101',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S20101';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
