DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DEAL_JCFX_DATA_TSSBMX$$

CREATE PROCEDURE PRO_DEAL_JCFX_DATA_TSSBMX()
routine_body: BEGIN
  DECLARE V_BEGINDATE      DATETIME;
  DECLARE V_RMBLAJ         DECIMAL(18,2);
  DECLARE V_GHFNSRSBH      VARCHAR(30);
  DECLARE V_HYDXZQH_DM     VARCHAR(10);
  DECLARE LN_ROWS          BIGINT;
  DECLARE LC_SBYY          VARCHAR(2000);

  SET @BJTS_DYNAMIC_SQL_001 = 'ALTER TABLE JCFX_DATA_TSSBMX ENABLE ROW MOVEMENT';
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;

  SELECT ORA_DATE_ADD(DATE(MAX(T.SJGXSJ)), -(1))
    INTO V_BEGINDATE
    FROM JCFX_DATA_TSSBMX T;

  SELECT COUNT(1)
    INTO LN_ROWS
    FROM CKTS_SB_MDT_CKMX S
   WHERE S.SJTB_SJ>=V_BEGINDATE
     AND IFNULL(S.BYBLBZ, 'N')='N';

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('CKTS_SB_MDT_CKMX-->JCFX_DATA_TSSBMX开始运行，记录总数：', LN_ROWS));
  COMMIT;

  -- 免抵退税
  BEGIN
  DECLARE BJTS_SQLCODE_008 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_008 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_008 = MYSQL_ERRNO, BJTS_SQLERRM_008 = MESSAGE_TEXT;
      SET LC_SBYY =BJTS_SQLERRM_008;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('CKTS_SB_MDT_CKMX-->JCFX_DATA_TSSBMX失败！', LC_SBYY);
      COMMIT;

  END;
UPDATE JCFX_DATA_TSSBMX AS A
JOIN (
SELECT S.UUID,S.TSSWJG_DM,S.DJXH,IFNULL(TRIM(S.DLCKHWZMHM), S.CKBGDH) AS CKBGDH,DATE_FORMAT(S.SBRQ, '%Y%m') AS NY,S.SBRQ,S.CKRQ_1,S.CKSP_DM,
                       S.HGCODE,S.GBCODE,S.TDCODE,S.HZDWDQDM,'1' AS SBYWLX,S.LCSLID_SB,
                       S.CKSL,S.MYLAJ,S.RMBLAJ,S.TSL,S.MDTSE
                  FROM CKTS_SB_MDT_CKMX S
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND IFNULL(S.BYBLBZ, 'N')='N'
                   AND IFNULL(TRIM(S.DLCKHWZMHM), S.CKBGDH) IS NOT NULL
) AS B
ON A.UUID=B.UUID
SET TSSWJG_DM = B.TSSWJG_DM, DJXH = B.DJXH, CKBGDH = B.CKBGDH, NY = B.NY, SBRQ = B.SBRQ, CKRQ = B.CKRQ_1, CKSP_DM = B.CKSP_DM, HGGQKA_DM = B.HGCODE, MYGDQSZ_DM = B.GBCODE, JGFS_DM = B.TDCODE, HZDWDQ_DM = B.HZDWDQDM, SJGXSJ = CURRENT_TIMESTAMP, SBYWLX = B.SBYWLX, LCSLID = B.LCSLID_SB, MYLAJ = B.MYLAJ, RMBLAJ = B.RMBLAJ, JSJE = B.RMBLAJ, TSL = B.TSL, TMSE = B.MDTSE, CKSL = B.CKSL;
INSERT INTO JCFX_DATA_TSSBMX (UUID,TSSWJG_DM,DJXH,CKBGDH,NY,SBRQ,CKRQ,CKSP_DM,HGGQKA_DM,MYGDQSZ_DM,JGFS_DM,HZDWDQ_DM,SJGXSJ,SBYWLX,LCSLID,MYLAJ,RMBLAJ,JSJE,TSL,TMSE,CKSL)
SELECT B.UUID,B.TSSWJG_DM,B.DJXH,B.CKBGDH,B.NY,B.SBRQ,B.CKRQ_1,B.CKSP_DM,B.HGCODE,B.GBCODE,B.TDCODE,B.HZDWDQDM,CURRENT_TIMESTAMP,B.SBYWLX,B.LCSLID_SB,B.MYLAJ,B.RMBLAJ,B.RMBLAJ,B.TSL,B.MDTSE,B.CKSL
FROM (
SELECT S.UUID,S.TSSWJG_DM,S.DJXH,IFNULL(TRIM(S.DLCKHWZMHM), S.CKBGDH) AS CKBGDH,DATE_FORMAT(S.SBRQ, '%Y%m') AS NY,S.SBRQ,S.CKRQ_1,S.CKSP_DM,
                       S.HGCODE,S.GBCODE,S.TDCODE,S.HZDWDQDM,'1' AS SBYWLX,S.LCSLID_SB,
                       S.CKSL,S.MYLAJ,S.RMBLAJ,S.TSL,S.MDTSE
                  FROM CKTS_SB_MDT_CKMX S
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND IFNULL(S.BYBLBZ, 'N')='N'
                   AND IFNULL(TRIM(S.DLCKHWZMHM), S.CKBGDH) IS NOT NULL
) AS B
WHERE NOT EXISTS (
  SELECT 1 FROM JCFX_DATA_TSSBMX AS A WHERE A.UUID=B.UUID
);
    COMMIT;
    -- 不需要补充GHFNSRSBH,HYDXZQH_DM
  END;

  SELECT COUNT(1)
    INTO LN_ROWS
    FROM CKTS_SB_MTS_CKMX S
   WHERE S.SJTB_SJ>=V_BEGINDATE
     AND IFNULL(S.BYBLBZ, 'N')='N';

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('CKTS_SB_MTS_CKMX-->JCFX_DATA_TSSBMX开始运行，记录总数：', LN_ROWS));
  COMMIT;

  -- 免退税
  BEGIN
  DECLARE BJTS_SQLCODE_007 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_007 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_007 = MYSQL_ERRNO, BJTS_SQLERRM_007 = MESSAGE_TEXT;
      SET LC_SBYY =BJTS_SQLERRM_007;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('CKTS_SB_MTS_CKMX-->JCFX_DATA_TSSBMX失败！', LC_SBYY);
      COMMIT;

  END;
UPDATE JCFX_DATA_TSSBMX AS A
JOIN (
SELECT S.UUID,S.TSSWJG_DM,S.DJXH,IFNULL(TRIM(S.DLCKHWZMHM), S.CKBGDH) AS CKBGDH,DATE_FORMAT(S.SBRQ, '%Y%m') AS NY,S.SBRQ,S.CKRQ_1,S.CKSP_DM,
                       S.HGCODE,S.GBCODE,S.TDCODE,S.HZDWDQDM,'2' AS SBYWLX,S.LCSLID_SB,
                       S.CKSL,S.MYLAJ,S.GLH,S.JSJE,S.TSL,S.TSE
                  FROM CKTS_SB_MTS_CKMX S
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND IFNULL(S.BYBLBZ, 'N')='N'
) AS B
ON A.UUID=B.UUID
SET TSSWJG_DM = B.TSSWJG_DM, DJXH = B.DJXH, CKBGDH = B.CKBGDH, NY = B.NY, SBRQ = B.SBRQ, CKRQ = B.CKRQ_1, CKSP_DM = B.CKSP_DM, HGGQKA_DM = B.HGCODE, MYGDQSZ_DM = B.GBCODE, JGFS_DM = B.TDCODE, HZDWDQ_DM = B.HZDWDQDM, SJGXSJ = CURRENT_TIMESTAMP, SBYWLX = B.SBYWLX, LCSLID = B.LCSLID_SB, MYLAJ = B.MYLAJ, GLH = B.GLH, JSJE = B.JSJE, TSL = B.TSL, TMSE = B.TSE, CKSL = B.CKSL;
INSERT INTO JCFX_DATA_TSSBMX (UUID,TSSWJG_DM,DJXH,CKBGDH,NY,SBRQ,CKRQ,CKSP_DM,HGGQKA_DM,MYGDQSZ_DM,JGFS_DM,HZDWDQ_DM,SJGXSJ,SBYWLX,LCSLID,MYLAJ,GLH,JSJE,TSL,TMSE,CKSL)
SELECT B.UUID,B.TSSWJG_DM,B.DJXH,B.CKBGDH,B.NY,B.SBRQ,B.CKRQ_1,B.CKSP_DM,B.HGCODE,B.GBCODE,B.TDCODE,B.HZDWDQDM,CURRENT_TIMESTAMP,B.SBYWLX,B.LCSLID_SB,B.MYLAJ,B.GLH,B.JSJE,B.TSL,B.TSE,B.CKSL
FROM (
SELECT S.UUID,S.TSSWJG_DM,S.DJXH,IFNULL(TRIM(S.DLCKHWZMHM), S.CKBGDH) AS CKBGDH,DATE_FORMAT(S.SBRQ, '%Y%m') AS NY,S.SBRQ,S.CKRQ_1,S.CKSP_DM,
                       S.HGCODE,S.GBCODE,S.TDCODE,S.HZDWDQDM,'2' AS SBYWLX,S.LCSLID_SB,
                       S.CKSL,S.MYLAJ,S.GLH,S.JSJE,S.TSL,S.TSE
                  FROM CKTS_SB_MTS_CKMX S
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND IFNULL(S.BYBLBZ, 'N')='N'
) AS B
WHERE NOT EXISTS (
  SELECT 1 FROM JCFX_DATA_TSSBMX AS A WHERE A.UUID=B.UUID
);
    COMMIT;
  END;

  BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';
    -- 补充RMBLAJ,GHFNSRSBH,HYDXZQH_DM

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
      SET LC_SBYY =BJTS_SQLERRM_004;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('JCFX_DATA_TSSBMX补充RMBLAJ,GHFNSRSBH,HYDXZQH_DM失败！', LC_SBYY);
      COMMIT;

  END;
BEGIN
  DECLARE BJTS_CURSOR_DONE_006 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_TSSB_UUID_006 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_DJXH_006 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_CKBGDH_006 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_CKSP_DM_006 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_GLH_006 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_MYLAJ_006 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_CKNY_006 LONGTEXT;
  DECLARE BJTS_CURSOR_006 CURSOR FOR
SELECT T.UUID,T.DJXH,T.CKBGDH,T.CKSP_DM,GLH,MYLAJ,DATE_FORMAT(T.CKRQ, '%Y%m') AS CKNY FROM JCFX_DATA_TSSBMX T WHERE T.SJGXSJ>=DATE(CURRENT_TIMESTAMP) AND T.SBYWLX='2';
  OPEN BJTS_CURSOR_006;
  BJTS_CURSOR_LOOP_006: LOOP
    SET BJTS_CURSOR_DONE_006 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_006 = TRUE;
      FETCH BJTS_CURSOR_006 INTO BJTS_CUR_TSSB_UUID_006, BJTS_CUR_TSSB_DJXH_006, BJTS_CUR_TSSB_CKBGDH_006, BJTS_CUR_TSSB_CKSP_DM_006, BJTS_CUR_TSSB_GLH_006, BJTS_CUR_TSSB_MYLAJ_006, BJTS_CUR_TSSB_CKNY_006;
    END;
    IF BJTS_CURSOR_DONE_006 THEN
      LEAVE BJTS_CURSOR_LOOP_006;
    END IF;
      BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';
        -- 防止部分申报

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
          SET V_RMBLAJ = NULL;

  END;
SELECT BJTS_CUR_TSSB_MYLAJ_006 * S.RMBLAJ / S.MYLAJ
          INTO V_RMBLAJ
          FROM CKTS_WBSJ_HG_BGD S
         WHERE S.DJXH=BJTS_CUR_TSSB_DJXH_006 AND S.CKBGDH=BJTS_CUR_TSSB_CKBGDH_006;
      END;

      IF V_RMBLAJ IS NULL THEN
        SELECT BJTS_CUR_TSSB_MYLAJ_006 * S.HL_RMB / 100
          INTO V_RMBLAJ
          FROM GS_HBZL_HLV S
         WHERE S.CODE='USD' AND S.HL_YM=BJTS_CUR_TSSB_CKNY_006 AND 1=1
LIMIT 1;
      END IF;

      BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';
        -- 主要供货商

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
          SET V_GHFNSRSBH =NULL;
          SET V_HYDXZQH_DM =NULL;

  END;
SELECT GHFNSRSBH_1, CASE WHEN SUBSTR(GHFNSRSBH_1,1,2)='91' THEN SUBSTR(GHFNSRSBH_1,3,4) ELSE SUBSTR(GHFNSRSBH_1,1,4) END
          INTO V_GHFNSRSBH, V_HYDXZQH_DM
          FROM (SELECT S.GHFNSRSBH_1, SUM(S.TSE) AS TSE
                  FROM CKTS_SB_MTS_JHMX S
                 WHERE S.DJXH=BJTS_CUR_TSSB_DJXH_006 AND S.GLH=BJTS_CUR_TSSB_GLH_006 AND S.CKSP_DM=BJTS_CUR_TSSB_CKSP_DM_006
                 GROUP BY S.GHFNSRSBH_1
                 ORDER BY SUM(S.TSE) DESC) TT
         WHERE 1=1
LIMIT 1;
      END;

      UPDATE JCFX_DATA_TSSBMX AS S
         SET RMBLAJ = V_RMBLAJ,
    GHFNSRSBH = V_GHFNSRSBH,
    HYDXZQH_DM = V_HYDXZQH_DM
       WHERE S.UUID=BJTS_CUR_TSSB_UUID_006;
      COMMIT;

  END LOOP BJTS_CURSOR_LOOP_006;
  CLOSE BJTS_CURSOR_006;
END;
  END;

  SELECT COUNT(1)
    INTO LN_ROWS
    FROM CKTS_SB_WZF_CKMX S
   WHERE S.SJTB_SJ>=V_BEGINDATE
     AND IFNULL(S.BYBLBZ, 'N')='N';

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('CKTS_SB_WZF_CKMX-->JCFX_DATA_TSSBMX开始运行，记录总数：', LN_ROWS));
  COMMIT;

  -- 代办退税
  BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
      SET LC_SBYY =BJTS_SQLERRM_003;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('CKTS_SB_WZF_CKMX-->JCFX_DATA_TSSBMX失败！', LC_SBYY);
      COMMIT;

  END;
UPDATE JCFX_DATA_TSSBMX AS A
JOIN (
SELECT S.UUID,S.TSSWJG_DM,S.DJXH,S.CKBGDH,DATE_FORMAT(S.SBRQ, '%Y%m') AS NY,S.SBRQ,S.CKRQ_1,S.CKSP_DM,
                       S.HGCODE,S.GBCODE,S.TDCODE,S.HZDWDQDM,'3' AS SBYWLX,S.LCSLID_SB,
                       S.CKSL,S.MYLAJ,S.JSJE,S.TSL,S.TSE,S.WTDBTSSCQYNSRSBH,
                       CASE WHEN SUBSTR(S.WTDBTSSCQYNSRSBH,1,2)='91' THEN SUBSTR(S.WTDBTSSCQYNSRSBH,3,4) ELSE SUBSTR(S.WTDBTSSCQYNSRSBH,1,4) END AS HYDXZQH_DM
                  FROM CKTS_SB_WZF_CKMX S
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND IFNULL(S.BYBLBZ, 'N')='N'
) AS B
ON A.UUID=B.UUID
SET TSSWJG_DM = B.TSSWJG_DM, DJXH = B.DJXH, CKBGDH = B.CKBGDH, NY = B.NY, SBRQ = B.SBRQ, CKRQ = B.CKRQ_1, CKSP_DM = B.CKSP_DM, HGGQKA_DM = B.HGCODE, MYGDQSZ_DM = B.GBCODE, JGFS_DM = B.TDCODE, HZDWDQ_DM = B.HZDWDQDM, SJGXSJ = CURRENT_TIMESTAMP, SBYWLX = B.SBYWLX, LCSLID = B.LCSLID_SB, MYLAJ = B.MYLAJ, JSJE = B.JSJE, TSL = B.TSL, TMSE = B.TSE, CKSL = B.CKSL, GHFNSRSBH = B.WTDBTSSCQYNSRSBH, HYDXZQH_DM = B.HYDXZQH_DM;
INSERT INTO JCFX_DATA_TSSBMX (UUID,TSSWJG_DM,DJXH,CKBGDH,NY,SBRQ,CKRQ,CKSP_DM,HGGQKA_DM,MYGDQSZ_DM,JGFS_DM,HZDWDQ_DM,SJGXSJ,SBYWLX,LCSLID,MYLAJ,JSJE,TSL,TMSE,CKSL,GHFNSRSBH,HYDXZQH_DM)
SELECT B.UUID,B.TSSWJG_DM,B.DJXH,B.CKBGDH,B.NY,B.SBRQ,B.CKRQ_1,B.CKSP_DM,B.HGCODE,B.GBCODE,B.TDCODE,B.HZDWDQDM,CURRENT_TIMESTAMP,B.SBYWLX,B.LCSLID_SB,B.MYLAJ,B.JSJE,B.TSL,B.TSE,B.CKSL,B.WTDBTSSCQYNSRSBH,B.HYDXZQH_DM
FROM (
SELECT S.UUID,S.TSSWJG_DM,S.DJXH,S.CKBGDH,DATE_FORMAT(S.SBRQ, '%Y%m') AS NY,S.SBRQ,S.CKRQ_1,S.CKSP_DM,
                       S.HGCODE,S.GBCODE,S.TDCODE,S.HZDWDQDM,'3' AS SBYWLX,S.LCSLID_SB,
                       S.CKSL,S.MYLAJ,S.JSJE,S.TSL,S.TSE,S.WTDBTSSCQYNSRSBH,
                       CASE WHEN SUBSTR(S.WTDBTSSCQYNSRSBH,1,2)='91' THEN SUBSTR(S.WTDBTSSCQYNSRSBH,3,4) ELSE SUBSTR(S.WTDBTSSCQYNSRSBH,1,4) END AS HYDXZQH_DM
                  FROM CKTS_SB_WZF_CKMX S
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND IFNULL(S.BYBLBZ, 'N')='N'
) AS B
WHERE NOT EXISTS (
  SELECT 1 FROM JCFX_DATA_TSSBMX AS A WHERE A.UUID=B.UUID
);
    COMMIT;
  END;

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';
    -- 补充RMBLAJ

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET LC_SBYY =BJTS_SQLERRM_001;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('JCFX_DATA_TSSBMX补充RMBLAJ失败！', LC_SBYY);
      COMMIT;

  END;
BEGIN
  DECLARE BJTS_CURSOR_DONE_005 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_TSSB_UUID_005 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_DJXH_005 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_CKBGDH_005 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_MYLAJ_005 LONGTEXT;
  DECLARE BJTS_CUR_TSSB_NY_005 LONGTEXT;
  DECLARE BJTS_CURSOR_005 CURSOR FOR
SELECT T.UUID,T.DJXH,T.CKBGDH,MYLAJ,T.NY FROM JCFX_DATA_TSSBMX T WHERE T.SJGXSJ>=DATE(CURRENT_TIMESTAMP) AND T.SBYWLX='3';
  OPEN BJTS_CURSOR_005;
  BJTS_CURSOR_LOOP_005: LOOP
    SET BJTS_CURSOR_DONE_005 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_005 = TRUE;
      FETCH BJTS_CURSOR_005 INTO BJTS_CUR_TSSB_UUID_005, BJTS_CUR_TSSB_DJXH_005, BJTS_CUR_TSSB_CKBGDH_005, BJTS_CUR_TSSB_MYLAJ_005, BJTS_CUR_TSSB_NY_005;
    END;
    IF BJTS_CURSOR_DONE_005 THEN
      LEAVE BJTS_CURSOR_LOOP_005;
    END IF;
      BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
          SET V_RMBLAJ = NULL;

  END;
SELECT S.RMBLAJ * BJTS_CUR_TSSB_MYLAJ_005 / S.MYLAJ  -- 防止部分申报
          INTO V_RMBLAJ
          FROM CKTS_WBSJ_HG_BGD S
         WHERE S.DJXH=BJTS_CUR_TSSB_DJXH_005 AND S.CKBGDH=BJTS_CUR_TSSB_CKBGDH_005;
      END;

      IF V_RMBLAJ IS NULL THEN
        SELECT BJTS_CUR_TSSB_MYLAJ_005 * S.HL_RMB / 100
          INTO V_RMBLAJ
          FROM GS_HBZL_HLV S
         WHERE S.CODE='USD' AND S.HL_YM=BJTS_CUR_TSSB_NY_005 AND 1=1
LIMIT 1;
      END IF;

      UPDATE JCFX_DATA_TSSBMX AS S
         SET RMBLAJ = V_RMBLAJ
       WHERE S.UUID=BJTS_CUR_TSSB_UUID_005;
      COMMIT;

  END LOOP BJTS_CURSOR_LOOP_005;
  CLOSE BJTS_CURSOR_005;
END;
  END;

  SET @BJTS_DYNAMIC_SQL_002 = 'ALTER TABLE JCFX_DATA_TSSBMX DISABLE ROW MOVEMENT';
PREPARE BJTS_DYNAMIC_STMT_002 FROM @BJTS_DYNAMIC_SQL_002;
EXECUTE BJTS_DYNAMIC_STMT_002;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_002;

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('JCFX_DATA_TSSBMX 开始运行，清除作废流程和不予办理数据...');
  COMMIT;

  BEGIN
    -- 根据明细变更情况，删除不予办理数据
    BEGIN
  DECLARE BJTS_CURSOR_DONE_004 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_BYBL_UUID_004 LONGTEXT;
  DECLARE BJTS_CURSOR_004 CURSOR FOR
SELECT T.UUID FROM CKTS_SB_MDT_CKMX T WHERE T.XGRQ>=V_BEGINDATE AND T.BYBLBZ='Y';
  OPEN BJTS_CURSOR_004;
  BJTS_CURSOR_LOOP_004: LOOP
    SET BJTS_CURSOR_DONE_004 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_004 = TRUE;
      FETCH BJTS_CURSOR_004 INTO BJTS_CUR_BYBL_UUID_004;
    END;
    IF BJTS_CURSOR_DONE_004 THEN
      LEAVE BJTS_CURSOR_LOOP_004;
    END IF;
      DELETE FROM JCFX_DATA_TSSBMX AS S WHERE S.UUID=BJTS_CUR_BYBL_UUID_004;

  END LOOP BJTS_CURSOR_LOOP_004;
  CLOSE BJTS_CURSOR_004;
END;
    COMMIT;

    BEGIN
  DECLARE BJTS_CURSOR_DONE_003 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_BYBL_UUID_003 LONGTEXT;
  DECLARE BJTS_CURSOR_003 CURSOR FOR
SELECT T.UUID FROM CKTS_SB_MTS_CKMX T WHERE T.XGRQ>=V_BEGINDATE AND T.BYBLBZ='Y';
  OPEN BJTS_CURSOR_003;
  BJTS_CURSOR_LOOP_003: LOOP
    SET BJTS_CURSOR_DONE_003 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_003 = TRUE;
      FETCH BJTS_CURSOR_003 INTO BJTS_CUR_BYBL_UUID_003;
    END;
    IF BJTS_CURSOR_DONE_003 THEN
      LEAVE BJTS_CURSOR_LOOP_003;
    END IF;
      DELETE FROM JCFX_DATA_TSSBMX AS S WHERE S.UUID=BJTS_CUR_BYBL_UUID_003;

  END LOOP BJTS_CURSOR_LOOP_003;
  CLOSE BJTS_CURSOR_003;
END;
    COMMIT;

    BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_BYBL_UUID_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT T.UUID FROM CKTS_SB_WZF_CKMX T WHERE T.XGRQ>=V_BEGINDATE AND T.BYBLBZ='Y';
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_CUR_BYBL_UUID_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
      DELETE FROM JCFX_DATA_TSSBMX AS S WHERE S.UUID=BJTS_CUR_BYBL_UUID_002;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;
    COMMIT;

    -- 根据流程信息作废情况，删除作废数据
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_ZFLC_LCSLID_SB_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.LCSLID_SB FROM CKTS_LC_SBXX T WHERE T.ZFRQ>=V_BEGINDATE;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_ZFLC_LCSLID_SB_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      DELETE FROM JCFX_DATA_TSSBMX AS S WHERE S.LCSLID=BJTS_CUR_ZFLC_LCSLID_SB_001;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
    COMMIT;

    DELETE FROM JCFX_DATA_TSSBMX AS T
     WHERE T.SJGXSJ>=DATE_ADD(DATE(CURRENT_TIMESTAMP), INTERVAL -1 MONTH) AND T.SBYWLX='1'
       AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MDT_CKMX S WHERE S.UUID=T.UUID);
    COMMIT;

    DELETE FROM JCFX_DATA_TSSBMX AS T
     WHERE T.SJGXSJ>=DATE_ADD(DATE(CURRENT_TIMESTAMP), INTERVAL -1 MONTH) AND T.SBYWLX='2'
       AND NOT EXISTS (SELECT 1 FROM CKTS_SB_MTS_CKMX S WHERE S.UUID=T.UUID);
    COMMIT;

    DELETE FROM JCFX_DATA_TSSBMX AS T
     WHERE T.SJGXSJ>=DATE_ADD(DATE(CURRENT_TIMESTAMP), INTERVAL -1 MONTH) AND T.SBYWLX='3'
       AND NOT EXISTS (SELECT 1 FROM CKTS_SB_WZF_CKMX S WHERE S.UUID=T.UUID);
    COMMIT;

  END;

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('JCFX_DATA_TSSBMX 处理结束！');
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
