DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S10102$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S10102
/*
 * 出口企业法定代表人是否为企业实际控制人
 * ZB_VAL：出口企业填报JKGL_ZLCJ_JGB，以填报结果为准，一致为0，不一致为1
 *         出口企业未填报JKGL_ZLCJ_JGB，查看股东占股比例，小于10%为1，否则为0
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,6);
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
    SELECT CASE WHEN T.FDDBR_XM=T.SJJYR_XM THEN 0 ELSE 1 END,
           '[d]法定代表人=' || T.FDDBR_XM || '|实际控制人=' || T.SJJYR_XM
      INTO V_ZB_VAL, V_PARAMS
      FROM JKGL_ZLCJ_JGB T
     WHERE T.DJXH=P_DJXH;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SELECT IFNULL(T.FDDBR_CGBL, 0),
           '[d]法定代表人=' || T.FDDBRMC || '|持股比例=' || IFNULL(T.FDDBR_CGBL, 0) || '%'
      INTO V_THIS_DATA, V_PARAMS
      FROM GS_DJ_CKTMSDAB T
     WHERE T.CPCODE=CAST(P_DJXH AS CHAR);
    IF V_THIS_DATA<10 THEN
      SET V_ZB_VAL = 1;
    ELSE
      SET V_ZB_VAL = 0;
    END IF;
  END IF;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10102' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10102',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10102';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
