DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W50101$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W50101
/*
 * 毛利率与同行业相比偏离较大的商品数量
 * ZB_VAL：毛利率与同行业平均值相比差异超过50%的
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_QSPJID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE VAL1         DECIMAL(18,2);    --参数1
  DECLARE VAL2         DECIMAL(18,2);    --参数2
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W50101_MMYLR_BL_LOWER';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W50101_MMYLR_BL_UPPER';

    SET V_ZB_VAL = 0;
    FOR CUR_SPDM IN (SELECT T.SP8_DM,T.MMYLR,S.MMYLR AS PJMMYLR
                       FROM JKGL_DATA_TJ_ZBU_TSSP T
                      INNER JOIN JKGL_QSPJ_CKSP S ON S.BGQID=P_QSPJID AND S.SP8_DM=T.SP8_DM
                      WHERE T.BGQID=P_BGQID
                        AND (T.MMYLR<=VAL1*S.MMYLR OR T.MMYLR>=VAL2*S.MMYLR))
    LOOP
      SET V_ZB_VAL = V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        SET V_PARAMS = '[d]商品代码=' || CUR_SPDM.SP8_DM || '，毛利率=' || CUR_SPDM.MMYLR || '，行业平均值=' || CUR_SPDM.PJMMYLR;
      ELSEIF V_ZB_VAL<=20 THEN
        SET V_PARAMS = V_PARAMS || '|商品代码=' || CUR_SPDM.SP8_DM || '，毛利率=' || CUR_SPDM.MMYLR || '，行业平均值=' || CUR_SPDM.PJMMYLR;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      SET V_PARAMS = V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50101' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W50101',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50101';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
