DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S30205$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S30205
/*
 * 根据报告期和基期分商品（8位HS编码）出口汇总指标元，
 * 商品出口额阈值>（参数1：阈值） 且 出口销售额同比>（参数2：150%）的敏感商品数量。
 * 报告期新增敏感出口商品只要出口额>（参数1阈值）即计入。
 * ZB_VAL：敏感商品出口数量
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_JQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE VAL1         DECIMAL(18,2);    -- 参数1
  DECLARE VAL2         DECIMAL(18,2);    -- 参数1
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30205_MGSP_CKE_HB';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30205_MGSP_CKE_JE';

    SET V_ZB_VAL = 0;
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_SPDM_SP8_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_CKSP_MC_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_CKEUSD_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_JQCKE_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.SP8_DM,DM.CKSP_MC,T.CKEUSD,IFNULL(JQ.CKEUSD, 0) AS JQCKE
                       FROM JKGL_DATA_TJ_ZBU_CKSP T
                      INNER JOIN JKGL_GY_MGSP_SWJG MG ON MG.MGSP_DM=T.SP8_DM AND MG.QYBZ='Y'
                       LEFT JOIN JKGL_DATA_TJ_ZBU_CKSP JQ ON JQ.BGQID=P_JQID AND JQ.SP8_DM=T.SP8_DM
                       LEFT JOIN JCFX_DM_CKSPTREE DM ON DM.CKSP_DM=T.SP8_DM AND DM.CKSP_JC='4'
                      WHERE T.BGQID=P_BGQID
                        AND T.CKEUSD>=VAL2
                        AND T.CKEUSD>=VAL1 * IFNULL(JQ.CKEUSD, 0);
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_SPDM_SP8_DM_001, BJTS_CUR_SPDM_CKSP_MC_001, BJTS_CUR_SPDM_CKEUSD_001, BJTS_CUR_SPDM_JQCKE_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET V_ZB_VAL = V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]敏感商品代码=', BJTS_CUR_SPDM_SP8_DM_001), '（'), BJTS_CUR_SPDM_CKSP_MC_001), '），报告期出口额='), BJTS_CUR_SPDM_CKEUSD_001), '，基期出口额='), BJTS_CUR_SPDM_JQCKE_001);
      ELSEIF V_ZB_VAL<=20 THEN
        SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(V_PARAMS, '|敏感商品代码='), BJTS_CUR_SPDM_SP8_DM_001), '（'), BJTS_CUR_SPDM_CKSP_MC_001), '），报告期出口额='), BJTS_CUR_SPDM_CKEUSD_001), '，基期出口额='), BJTS_CUR_SPDM_JQCKE_001);
      END IF;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
    IF V_ZB_VAL>20 THEN
      SET V_PARAMS = ORA_CONCAT(V_PARAMS, '|...');
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30205' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30205',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30205';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
