DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S10204$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S10204
/*
 * 销售额与电费支出合理关系，取统计期往前一年的数据
 * ZB_VAL：报告期内电费支出小于等于5万元且外销收入减委托加工费用大于700W以上，返回1
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    -- 参数1
  DECLARE VAL2         DECIMAL(18,2);    -- 参数2
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S10204_CKXSEJWTJG';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S10204_DFZC';

    SELECT S.ZZS_XSE_MDT + S.ZZS_XSE_MS - S.DZ_WTJG, S.DZ_DFJE_ZC - S.DZ_DFJE_SR
      INTO V_THIS_DATA, V_LAST_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;

    SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]报告期出口销售额(扣除委托加工费)=', V_THIS_DATA), '|报告期电费支出='), V_LAST_DATA);
    IF V_THIS_DATA>0 AND V_LAST_DATA>=0 THEN
      IF V_THIS_DATA>=VAL1 AND V_LAST_DATA<=VAL2 THEN
        SET V_ZB_VAL = 1;
      ELSE
        SET V_ZB_VAL = 0;
      END IF;
    ELSE
      SET V_ZB_VAL = NULL;
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10204' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10204',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10204';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
