DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W30203$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W30203
/*
 * 首笔出口未满一年企业,出口额超1000万美元。
 * ZB_VAL：前1-13月出口额大于等于1000W返回1，否则返回0
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10),
  IN P_BGQ_Z DATETIME,
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_SCCKYF     DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    --参数1
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
    SELECT TIMESTAMPDIFF(MONTH, IFNULL(A.SCCKRQ, CURRENT_TIMESTAMP), P_BGQ_Z),'[d]企业首笔出口日期：'||DATE_FORMAT(A.SCCKRQ, '%Y%m%d')
      INTO V_SCCKYF, V_PARAMS
      FROM GS_DJ_CKTMSDAB A
     WHERE A.CPCODE=CAST(P_DJXH AS CHAR)
       AND ROWNUM=1;
    IF V_SCCKYF>=12 THEN
      SET V_ZB_VAL = NULL;
    ELSE
      SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
        INTO VAL1
        FROM JKGL_PZ_ZB_CS T
        LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
       WHERE T.CSBM='ZC_W30203_CKWMYN_YNNCKE';

      SELECT S.CK_CKEUSD_LASTYEAR
        INTO V_THIS_DATA
        FROM JKGL_DATA_TJ_ZBU S
       WHERE S.BGQID=P_BGQID;

      SET V_PARAMS = V_PARAMS || '|最近12个月出口销售额=' || V_THIS_DATA;
      IF V_THIS_DATA>=VAL1 THEN
        SET V_ZB_VAL =1;
      ELSE
        SET V_ZB_VAL =0;
      END IF;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30203' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W30203',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30203';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
