DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_FXGL_ATFX_CKFP$$

CREATE PROCEDURE PRO_FXGL_ATFX_CKFP
/*
 * 风险管理——案头分析——出口电子信息补充发票号码、境外收货人信息
 */
(
  IN P_DJXH VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_CKFP        VARCHAR(30);
  DECLARE LN_FGF         BIGINT;
  DECLARE LC_WSMC        VARCHAR(300);

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_CK_DJXH_001 LONGTEXT;
  DECLARE BJTS_CUR_CK_CKBGDH_001 LONGTEXT;
  DECLARE BJTS_CUR_CK_DLCKHWZMHM_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT CK.DJXH,CK.CKBGDH,CK.DLCKHWZMHM
                   FROM ATFX_CK_YS_CKDZXX CK
                  WHERE CK.DJXH=P_DJXH
                    AND CK.CYTSSBJL IS NOT NULL AND CK.CKFPHM IS NULL;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_CK_DJXH_001, BJTS_CUR_CK_CKBGDH_001, BJTS_CUR_CK_DLCKHWZMHM_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
        SET LC_CKFP = NULL;

  END;
IF BJTS_CUR_CK_DLCKHWZMHM_001 IS NULL THEN
        SELECT CKFPH
          INTO LC_CKFP
          FROM (SELECT MTS.CKFPH
                  FROM ATFX_TS_YS_CKMXSBB MTS
                 WHERE MTS.DJXH=BJTS_CUR_CK_DJXH_001
                   AND MTS.CKBGDH=BJTS_CUR_CK_CKBGDH_001
                 UNION ALL
                SELECT MDT.CKFPH
                  FROM ATFX_TS_YS_MDTSSBB MDT
                 WHERE MDT.DJXH=BJTS_CUR_CK_DJXH_001
                   AND MDT.CKBGDH=BJTS_CUR_CK_CKBGDH_001)
         WHERE 1=1
LIMIT 1;
      ELSE
        SELECT CKFPH
          INTO LC_CKFP
          FROM (SELECT MTS.CKFPH
                  FROM ATFX_TS_YS_CKMXSBB MTS
                 WHERE MTS.DJXH=BJTS_CUR_CK_DJXH_001
                   AND MTS.DLZMH=BJTS_CUR_CK_DLCKHWZMHM_001
                 UNION ALL
                SELECT MDT.CKFPH
                  FROM ATFX_TS_YS_MDTSSBB MDT
                 WHERE MDT.DJXH=BJTS_CUR_CK_DJXH_001
                   AND MDT.DLCKHWZMHM=BJTS_CUR_CK_DLCKHWZMHM_001)
         WHERE 1=1
LIMIT 1;
      END IF;
    END;

    IF LC_CKFP IS NOT NULL THEN
      SET LN_FGF = INSTR(LC_CKFP,',');
      IF LN_FGF>0 THEN
        SET LC_CKFP = SUBSTR(LC_CKFP,1,LN_FGF-1);
      END IF;
      SET LN_FGF = INSTR(LC_CKFP,'-');
      IF LN_FGF>0 THEN
        SET LC_CKFP = SUBSTR(LC_CKFP,1,LN_FGF-1);
      END IF;
      BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
          SET LC_WSMC = NULL;

  END;
IF LENGTH(LC_CKFP) IN (18,20) THEN
          SELECT FP.GMFMC
            INTO LC_WSMC
            FROM ATFX_FP_YS_XSFPXX FP
           WHERE FP.DJXH=BJTS_CUR_CK_DJXH_001
             AND FP.FPHM=LC_CKFP
             AND 1=1
LIMIT 1;
        ELSE
          SELECT FP.GMFMC
            INTO LC_WSMC
            FROM ATFX_FP_YS_XSFPXX FP
           WHERE FP.DJXH=BJTS_CUR_CK_DJXH_001
             AND FP.FPHM LIKE ORA_CONCAT('%', LC_CKFP)
             AND 1=1
LIMIT 1;
        END IF;
      END;

      UPDATE ATFX_CK_YS_CKDZXX AS T
         SET CKFPHM = LC_CKFP,
    JWSHR = LC_WSMC
       WHERE T.DJXH = BJTS_CUR_CK_DJXH_001
         AND T.CKBGDH = BJTS_CUR_CK_CKBGDH_001;
      COMMIT;
    END IF;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  LEAVE routine_body;
END$$

DELIMITER ;
