DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W30107$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W30107
/*
 * 出口到同一国别（地区）出口口岸数量是否过多
 * ZB_VAL：统计(国别_口岸数量>5)的国别个数
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE VAL1         DECIMAL(18,2);    --参数1
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W30107_GB_KA_SL';

    SET V_ZB_VAL = 0;
    FOR CUR_SPDM IN (SELECT T.GB_DM,DM.CKGB_MC,T.KASL
                       FROM JKGL_DATA_TJ_ZBU_CKGB T
                       LEFT JOIN JCFX_DM_CKGB DM ON DM.CKGB_DM=T.GB_DM
                      WHERE T.BGQID=P_BGQID
                        AND T.KASL>VAL1
                        AND T.GB_DM<>'142')
    LOOP
      SET V_ZB_VAL = V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        SET V_PARAMS = '[d]国别代码=' || CUR_SPDM.GB_DM || '（' || CUR_SPDM.CKGB_MC ||'），口岸数量=' || CUR_SPDM.KASL;
      ELSEIF V_ZB_VAL<=20 THEN
        SET V_PARAMS = V_PARAMS || '|国别代码=' || CUR_SPDM.GB_DM || '（' || CUR_SPDM.CKGB_MC ||'），口岸数量=' || CUR_SPDM.KASL;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      SET V_PARAMS = V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30107' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W30107',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30107';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
