DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W20202$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W20202
/*
 * 超期申报报关单多、金额占比高
 * ZB_VAL：超期申报报关单数量>XX and 超期申报出口额/报告期出口额>YY%
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_CQSB_NUM   DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    -- 参数1
  DECLARE VAL2         DECIMAL(18,2);    -- 参数2
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W20202_CQSB_BGD_NUM';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W20202_CQSB_CKE_ZB';

    SELECT T.TS_CKEUSD, T.TS_CKEUSD_CQ, T.TS_BGDSL_CQ
      INTO V_THIS_DATA, V_LAST_DATA, V_CQSB_NUM
      FROM JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]报告期出口额=', V_THIS_DATA), '|超期申报出口额='), V_LAST_DATA), '|超期申报报关单数量='), V_CQSB_NUM);
    IF V_THIS_DATA<=0 THEN
      SET V_ZB_VAL = NULL;
    ELSEIF V_CQSB_NUM>=VAL1 AND V_LAST_DATA>=VAL2 * V_THIS_DATA THEN
      SET V_ZB_VAL =1;
    ELSE
      SET V_ZB_VAL =0;
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20202' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W20202',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20202';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
