DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_JKM_MAIN$$

CREATE PROCEDURE PRO_JKGL_JKM_MAIN(
  IN P_DJXH VARCHAR(4000),
  IN P_SWJG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE V_COUNT BIGINT;
  DECLARE V_DJXH VARCHAR(20);
  DECLARE CUR_QY(A_DJXH DECIMAL(38,10), A_SWJG VARCHAR(4000)) CURSOR FOR
      SELECT DJ.CPCODE, (CASE DJ.JSMODE WHEN '1' THEN '1' ELSE '2' END) AS TSJSFS, DJ.SWJGDM
        FROM JKGL_DATA_QYJKM_JGB T 
       INNER JOIN GLXT_BB_SHXT_DJXX DJ ON DJ.CPCODE=T.DJXH
       WHERE (A_DJXH IS NULL OR T.DJXH=A_DJXH) 
         AND (A_SWJG IS NULL OR DJ.SWJGDM=A_SWJG)
         AND EXISTS (SELECT 1 
                       FROM JKGL_DATA_ZB_JGB Z 
                      WHERE T.DJXH=Z.DJXH AND Z.ZB_ID IN ('W10101','S10101'));

  SET V_COUNT =0;
  DBMS_OUTPUT.PUT_LINE('【健康码】刷新开始，时间:'||DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m%d %H:%i:%s'));

  --开始循环
  BEGIN
    FOR CUR IN CUR_QY(P_DJXH, P_SWJG)
    LOOP
      SET V_COUNT =V_COUNT+1;
      SET V_DJXH = CUR.CPCODE;

      --对指标进行异常判定和赋分
      PRO_JKGL_JKM_ZB_YCFF(V_DJXH,CUR.TSJSFS,CUR.SWJGDM);

      --对指标进行异常判定和赋分
      PRO_JKGL_JKM_COMPUTE(V_DJXH,CUR.TSJSFS,CUR.SWJGDM);


    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('【健康码】刷新异常:'||SQLCODE||SQLERRM);
      DBMS_OUTPUT.PUT_LINE('【异常企业】-'||V_COUNT||'-'||V_DJXH);
      LEAVE routine_body;
  END;

  DBMS_OUTPUT.PUT_LINE('【健康码】刷新结束，时间:'||DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m%d %H:%i:%s'));
  DBMS_OUTPUT.PUT_LINE('【健康码】刷新户数='||V_COUNT);

  LEAVE routine_body;
END$$

DELIMITER ;
