DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DEAL_JCFX_DATA_QYYHZ_INIT$$

CREATE PROCEDURE PRO_DEAL_JCFX_DATA_QYYHZ_INIT()
/*
 * 每月月初，取JCFX_NSR_BADJ_TOHZ表中记录并初始化JCFX_DATA_QYYHZ
 */
routine_body: BEGIN
  DECLARE LD_ENDMONTH          DATETIME;             -- 上上月，汇总截止月份，老企业汇总起始月份
  DECLARE LD_DEALMONTH         DATETIME;             -- 按月汇总的控制时间（月初）
  DECLARE LD_NEXTMONTH         DATETIME;             -- 按月汇总的控制时间（下月初）
  DECLARE LC_NY                VARCHAR(6);      -- 开票月份，财务报表、纳税申报表所属期止月份，免抵退申报所属期或免退税申报月份
  DECLARE LD_NEWMONTH          DATETIME;             -- 新增商品、供应商的控制时间（月初）
  DECLARE LC_NEWNY             VARCHAR(6);      -- 新增商品、供应商的控制时间（月份）
  -- JCFX_DATA_QYYHZ.ck
  DECLARE LN_CK_SB_XSEMY        DECIMAL(18,2);     -- 出口_销售美元
  DECLARE LN_CK_SB_XSERMB       DECIMAL(18,2);     -- 出口_销售人民币
  DECLARE LN_CK_SB_JSJE         DECIMAL(18,2);     -- 出口_计税金额
  DECLARE LN_CK_SB_JHCB         DECIMAL(18,2);     -- 出口_进货成本
  DECLARE LN_CK_SB_TSE          DECIMAL(18,2);     -- 出口_申报退税
  DECLARE LN_CK_SB_MDE          DECIMAL(18,2);     -- 出口_申报免抵
  DECLARE LN_CK_HZ_TSE          DECIMAL(18,2);     -- 出口_核准退税
  DECLARE LN_CK_HZ_MDE          DECIMAL(18,2);     -- 出口_核准免抵
  DECLARE LN_CK_BL_TSE          DECIMAL(18,2);     -- 出口_办理退税
  DECLARE LN_CK_BL_MDE          DECIMAL(18,2);     -- 出口_办理免抵
  DECLARE LN_CK_XZSP_CKE        DECIMAL(18,2);     -- 出口_新增商品出口额
  DECLARE LN_CK_XZGHS_JSJE      DECIMAL(18,2);     -- 出口_新增供应商计税金额
  DECLARE LN_CK_TSSP_CKE        DECIMAL(18,2);     -- 出口_特殊商品出口额
  DECLARE LN_CK_MGSP_CKE        DECIMAL(18,2);     -- 出口_敏感商品出口额
  DECLARE LN_CK_MGKA_CKE        DECIMAL(18,2);     -- 出口_敏感口岸出口额
  DECLARE LN_CNT                INTEGER;          -- 统计数

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_NSR_DJXH_001 LONGTEXT;
  DECLARE BJTS_CUR_NSR_NSRSBH_001 LONGTEXT;
  DECLARE BJTS_CUR_NSR_SHXYDM_001 LONGTEXT;
  DECLARE BJTS_CUR_NSR_SWJGDM_001 LONGTEXT;
  DECLARE BJTS_CUR_NSR_JLXZSJ_001 LONGTEXT;
  DECLARE BJTS_CUR_NSR_BACHSJ_001 LONGTEXT;
  DECLARE BJTS_CUR_NSR_JCFXSJ_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT DJXH,NSRSBH,IFNULL(SHXYDM, NSRSBH) AS SHXYDM,SWJGDM,JLXZSJ,BACHSJ,JCFXSJ FROM JCFX_NSR_BADJ_TOHZ;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_NSR_DJXH_001, BJTS_CUR_NSR_NSRSBH_001, BJTS_CUR_NSR_SHXYDM_001, BJTS_CUR_NSR_SWJGDM_001, BJTS_CUR_NSR_JLXZSJ_001, BJTS_CUR_NSR_BACHSJ_001, BJTS_CUR_NSR_JCFXSJ_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    IF BJTS_CUR_NSR_JCFXSJ_001 IS NULL THEN -- 根据上一次监测分析时间是否为空判定是否新增企业
      SET LD_DEALMONTH =DATE_ADD(MAKEDATE(YEAR(BJTS_CUR_NSR_JLXZSJ_001), 1), INTERVAL -24 MONTH); -- 新增企业汇总起始月份，上上年
    ELSE
      BEGIN
  DECLARE BJTS_SQLCODE_007 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_007 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_007 = MYSQL_ERRNO, BJTS_SQLERRM_007 = MESSAGE_TEXT;
          SET LD_DEALMONTH = NULL;

  END;
SELECT STR_TO_DATE(ORA_CONCAT(MAX(S.NY), '01'), '%Y%m%d')
          INTO LD_DEALMONTH
          FROM JCFX_DATA_QYYHZ S
          WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001;
      END;
      IF LD_DEALMONTH IS NULL THEN
        SET LD_DEALMONTH =DATE_ADD(CAST(DATE_FORMAT(BJTS_CUR_NSR_JCFXSJ_001, '%Y-%m-01') AS DATETIME), INTERVAL -2 MONTH); -- 老企业汇总起始月份，上上月
      END IF;
    END IF;
    -- 终止月份，上上月、备案撤回月份（未撤回按系统日期比较）较小者
    SET LD_ENDMONTH =LEAST(DATE_ADD(CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-01') AS DATETIME), INTERVAL -2 MONTH),CAST(DATE_FORMAT(IFNULL(BJTS_CUR_NSR_BACHSJ_001, CURRENT_TIMESTAMP), '%Y-%m-01') AS DATETIME));

    -- DEBUG
    BJTS_LOOP_001: LOOP
      IF LD_DEALMONTH > LD_ENDMONTH THEN LEAVE BJTS_LOOP_001; END IF;
      -- 日期赋值
      SET LD_NEXTMONTH =DATE_ADD(LD_DEALMONTH, INTERVAL 1 MONTH);
      SET LC_NY =DATE_FORMAT(LD_DEALMONTH, '%Y%m');
      SET LD_NEWMONTH =DATE_ADD(LD_DEALMONTH, INTERVAL -6 MONTH);
      SET LC_NEWNY =DATE_FORMAT(LD_NEWMONTH, '%Y%m');

      -- JCFX_DATA_QYYHZ
      BEGIN
        SELECT COUNT(*) INTO LN_CNT FROM JCFX_DATA_QYYHZ T WHERE T.DJXH=BJTS_CUR_NSR_DJXH_001 AND T.NY=LC_NY;
        IF LN_CNT = 0 THEN
          INSERT INTO JCFX_DATA_QYYHZ(DJXH,NY,NSRSBH,SHXYDM)
          VALUES(BJTS_CUR_NSR_DJXH_001,LC_NY,BJTS_CUR_NSR_NSRSBH_001,BJTS_CUR_NSR_SHXYDM_001);
          COMMIT;
        END IF;

        SELECT COUNT(*) INTO LN_CNT FROM JCFX_DATA_QYYHZ T WHERE T.DJXH=BJTS_CUR_NSR_DJXH_001 AND T.NY=LC_NY AND IFNULL(T.BJTS_ZT, 'N') <> 'Y';
        -- 本地BJTS抽取
        IF LN_CNT > 0 THEN
          -- LN_CK_SB_XSEMY,LN_CK_SB_XSERMB,LN_CK_SB_JSJE,LN_CK_SB_JHCB
          BEGIN
  DECLARE BJTS_SQLCODE_006 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_006 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_006 = MYSQL_ERRNO, BJTS_SQLERRM_006 = MESSAGE_TEXT;
              SET LN_CK_SB_XSEMY =0;
              SET LN_CK_SB_XSERMB =0;
              SET LN_CK_SB_JSJE =0;
              SET LN_CK_SB_JHCB =0;

  END;
SELECT IFNULL(SUM(XSEMY), 0),IFNULL(SUM(XSERMB), 0),IFNULL(SUM(JSJE), 0),IFNULL(SUM(JHCB), 0)
              INTO LN_CK_SB_XSEMY, LN_CK_SB_XSERMB, LN_CK_SB_JSJE, LN_CK_SB_JHCB
              FROM (SELECT SUM(T.MYLAJ) AS XSEMY, SUM(T.RMBLAJ) AS XSERMB, SUM(T.RMBLAJ) AS JSJE, 0 AS JHCB
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MDT_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0305001' AND S.SSQ=LC_NY AND S.ZFBZ IS NULL
                     UNION ALL
                    SELECT SUM(T.YSFWYYEMY) AS XSEMY, SUM(T.YSFWYYERMB) AS XSERMB, SUM(T.YSFWYYERMB) AS JSJE, 0 AS JHCB
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MDT_YFSJ T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0305001' AND S.SSQ=LC_NY AND S.ZFBZ IS NULL
                     UNION ALL
                    SELECT SUM(T.YSFWYYEMY) AS XSEMY, SUM(T.YSFWYYERMB) AS XSERMB, SUM(T.YSFWYYERMB) AS JSJE, 0 AS JHCB
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MDT_GJYS T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0305001' AND S.SSQ=LC_NY AND S.ZFBZ IS NULL
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY, SUM(T.MYLAJ * R.RMBLAJ / R.MYLAJ) AS XSERMB, 0 AS JSJE, 0 AS JHCB
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MTS_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     INNER JOIN CKTS_WBSJ_HG_BGD R ON R.DJXH=BJTS_CUR_NSR_DJXH_001 AND R.CKBGDH=T.CKBGDH
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0301001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                     UNION ALL
                    SELECT 0 AS XSEMY, 0 AS XSERMB, SUM(T.JSJE) AS JSJE, SUM(T.JSJE * (100+T.ZSSL-T.TSL) / 100) AS JHCB
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MTS_JHMX T ON T.LCSLID_SB=S.LCSLID_SB AND T.SZ='V'
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0301001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                     UNION ALL
                    SELECT SUM(T.SKJEMY) AS XSEMY, SUM(T.BQQRYSFWYYSRRMBJE) AS XSERMB, SUM(T.JSJE) AS JSJE, SUM(T.JSJE * (100+T.ZSSL-T.TSL) / 100) AS JHCB
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MTS_YSFW T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0301001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY, SUM(T.MYLAJ * R.RMBLAJ / R.MYLAJ) AS XSERMB, SUM(T.JSJE) AS JSJE, SUM(T.JSJE * (100+T.ZSSL-T.TSL) / 100) AS JHCB
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_WZF_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     INNER JOIN CKTS_WBSJ_HG_BGD R ON R.DJXH=BJTS_CUR_NSR_DJXH_001 AND R.CKBGDH=T.CKBGDH
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0310001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                     UNION ALL
                    SELECT SUM(R.MYLAJ) AS XSEMY, SUM(R.RMBLAJ) AS XSERMB, SUM(T.SBZYJZ) AS JSJE, SUM(T.SBZYJZ * (100+T.ZSSL-T.TSL) / 100) AS JHCB
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_YS_SBMX T ON T.LCSLID=S.LCSLID_SB
                     INNER JOIN CKTS_WBSJ_HG_BGD R ON R.DJXH=BJTS_CUR_NSR_DJXH_001 AND R.CKBGDH=T.CKBGDH
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0303001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                     UNION ALL
                    SELECT 0 AS XSEMY, 0 AS XSERMB, SUM(T.JSJE) AS JSJE, SUM(T.JSJE) AS JHCB
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_GJ_SBMX T ON T.LCSLID=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0304001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL) TT;
          END;

          -- LN_CK_SB_TSE,LN_CK_SB_MDE
          SELECT IFNULL(SUM(S.SB_ZZSTSE+S.SB_XFSTSE), 0),IFNULL(SUM(S.SB_MDSE), 0)
            INTO LN_CK_SB_TSE,LN_CK_SB_MDE
            FROM CKTS_LC_SBXX S
           WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001
             AND ((S.SBYWB_DM='A0305001' AND S.SSQ=LC_NY) OR ( S.SBYWB_DM<>'A0305001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH))
             AND S.ZFBZ IS NULL;

          -- LN_CK_HZ_TSE,LN_CK_HZ_MDE
          SELECT IFNULL(SUM(S.SEHZ_ZZSTSE+S.SEHZ_XFSTSE), 0),IFNULL(SUM(S.SEHZ_MDSE), 0)
            INTO LN_CK_HZ_TSE,LN_CK_HZ_MDE
            FROM CKTS_LC_SEHZXX S
           WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SEHZRQ>=LD_DEALMONTH AND S.SEHZRQ<LD_NEXTMONTH;

          -- LN_CK_BL_TSE
          SELECT IFNULL(SUM(S.SE), 0)
            INTO LN_CK_BL_TSE
            FROM CKTS_ZS_SRTHS S
           WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.THRQ_1>=LD_DEALMONTH AND S.THRQ_1<LD_NEXTMONTH AND S.TTSJLX_DM='01' AND S.TZLX_DM IN ('1','4');

          -- LN_CK_BL_MDE
          SELECT IFNULL(SUM(S.JE), 0)
            INTO LN_CK_BL_MDE
            FROM CKTS_ZS_TKGZ S
           WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.GKGZRQ>=LD_DEALMONTH AND S.GKGZRQ<LD_NEXTMONTH AND S.TZSLY='3' AND S.TZLX_DM='1' AND S.GZBZ='Y';

          -- LN_CK_XZSP_CKE             --出口_新增商品出口额
          BEGIN
  DECLARE BJTS_SQLCODE_005 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_005 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_005 = MYSQL_ERRNO, BJTS_SQLERRM_005 = MESSAGE_TEXT;
              SET LN_CK_XZSP_CKE =0;

  END;
SELECT IFNULL(SUM(XSEMY), 0)
              INTO LN_CK_XZSP_CKE
              FROM (SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MDT_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0305001' AND S.SSQ=LC_NY AND S.ZFBZ IS NULL
                       AND NOT EXISTS (SELECT 1
                                         FROM CKTS_LC_SBXX S1
                                        INNER JOIN CKTS_SB_MDT_CKMX T1 ON T1.LCSLID_SB=S1.LCSLID_SB
                                        WHERE S1.DJXH=BJTS_CUR_NSR_DJXH_001 AND S1.SBYWB_DM='A0305001' AND S1.SSQ>=LC_NEWNY AND S1.SSQ<LC_NY AND S1.ZFBZ IS NULL
                                          AND T1.CKSP_DM LIKE ORA_CONCAT(SUBSTR(T.CKSP_DM,1,4), '%'))
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MTS_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0301001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                       AND NOT EXISTS (SELECT 1
                                         FROM CKTS_LC_SBXX S1
                                        INNER JOIN CKTS_SB_MTS_CKMX T1 ON T1.LCSLID_SB=S1.LCSLID_SB
                                        WHERE S1.DJXH=BJTS_CUR_NSR_DJXH_001 AND S1.SBYWB_DM='A0301001' AND S1.SBRQ>=LD_NEWMONTH AND S1.SBRQ<LD_DEALMONTH AND S1.ZFBZ IS NULL
                                          AND T1.CKSP_DM LIKE ORA_CONCAT(SUBSTR(T.CKSP_DM,1,4), '%'))
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_WZF_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0310001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                       AND NOT EXISTS (SELECT 1
                                         FROM CKTS_LC_SBXX S1
                                        INNER JOIN CKTS_SB_WZF_CKMX T1 ON T1.LCSLID_SB=S1.LCSLID_SB
                                        WHERE S1.DJXH=BJTS_CUR_NSR_DJXH_001 AND S1.SBYWB_DM='A0310001' AND S1.SBRQ>=LD_NEWMONTH AND S1.SBRQ<LD_DEALMONTH AND S1.ZFBZ IS NULL
                                          AND T1.CKSP_DM LIKE ORA_CONCAT(SUBSTR(T.CKSP_DM,1,4), '%')
                                          AND T1.WTDBTSSCQYNSRSBH=T.WTDBTSSCQYNSRSBH) ) TT;
          END;

          -- LN_CK_XZGHS_JSJE           --出口_新增供应商计税金额
          BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
              SET LN_CK_XZGHS_JSJE =0;

  END;
SELECT IFNULL(SUM(JSJE), 0)
              INTO LN_CK_XZGHS_JSJE
              FROM (SELECT SUM(T.JSJE) AS JSJE
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MTS_JHMX T ON T.LCSLID_SB=S.LCSLID_SB AND T.SZ='V'
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0301001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                       AND NOT EXISTS (SELECT 1
                                         FROM CKTS_LC_SBXX S1
                                        INNER JOIN CKTS_SB_MTS_JHMX T1 ON T1.LCSLID_SB=S1.LCSLID_SB
                                        WHERE S1.DJXH=BJTS_CUR_NSR_DJXH_001 AND S1.SBYWB_DM='A0301001' AND S1.SBRQ>=LD_NEWMONTH AND S1.SBRQ<LD_DEALMONTH AND S1.ZFBZ IS NULL
                                          AND T1.GHFNSRSBH_1=T.GHFNSRSBH_1) ) TT;
          END;

          -- LN_CK_TSSP_CKE             --出口_特殊商品出口额
          BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
              SET LN_CK_TSSP_CKE =0;

  END;
SELECT IFNULL(SUM(XSEMY), 0)
              INTO LN_CK_TSSP_CKE
              FROM (SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MDT_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0305001' AND S.SSQ=LC_NY AND S.ZFBZ IS NULL
                       AND T.CKSP_DM IN (SELECT R.CKSP_DM FROM JCFX_CS_TSSP R WHERE R.SWJGDM=BJTS_CUR_NSR_SWJGDM_001)
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MTS_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0301001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                       AND T.CKSP_DM IN (SELECT R.CKSP_DM FROM JCFX_CS_TSSP R WHERE R.SWJGDM=BJTS_CUR_NSR_SWJGDM_001)
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_WZF_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0310001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                       AND T.CKSP_DM IN (SELECT R.CKSP_DM FROM JCFX_CS_TSSP R WHERE R.SWJGDM=BJTS_CUR_NSR_SWJGDM_001) ) TT;
          END;

          -- LN_CK_MGSP_CKE             --出口_敏感商品出口额
          BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
              SET LN_CK_MGSP_CKE =0;

  END;
SELECT IFNULL(SUM(XSEMY), 0)
              INTO LN_CK_MGSP_CKE
              FROM (SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MDT_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0305001' AND S.SSQ=LC_NY AND S.ZFBZ IS NULL
                       AND T.CKSP_DM IN (SELECT R.CKSP_DM FROM JCFX_CS_MGSP R WHERE R.SWJGDM=BJTS_CUR_NSR_SWJGDM_001)
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MTS_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0301001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                       AND T.CKSP_DM IN (SELECT R.CKSP_DM FROM JCFX_CS_MGSP R WHERE R.SWJGDM=BJTS_CUR_NSR_SWJGDM_001)
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_WZF_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0310001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                       AND T.CKSP_DM IN (SELECT R.CKSP_DM FROM JCFX_CS_MGSP R WHERE R.SWJGDM=BJTS_CUR_NSR_SWJGDM_001) ) TT;
          END;

          -- LN_CK_MGKA_CKE             --出口_敏感口岸出口额
          BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
              SET LN_CK_MGSP_CKE =0;

  END;
SELECT IFNULL(SUM(XSEMY), 0)
              INTO LN_CK_MGSP_CKE
              FROM (SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MDT_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0305001' AND S.SSQ=LC_NY AND S.ZFBZ IS NULL
                       AND T.HGCODE IN (SELECT R.HGGQKA_DM FROM JCFX_CS_MGKA R WHERE R.SWJGDM=BJTS_CUR_NSR_SWJGDM_001)
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_MTS_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0301001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                       AND T.HGCODE IN (SELECT R.HGGQKA_DM FROM JCFX_CS_MGKA R WHERE R.SWJGDM=BJTS_CUR_NSR_SWJGDM_001)
                     UNION ALL
                    SELECT SUM(T.MYLAJ) AS XSEMY
                      FROM CKTS_LC_SBXX S
                     INNER JOIN CKTS_SB_WZF_CKMX T ON T.LCSLID_SB=S.LCSLID_SB
                     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.SBYWB_DM='A0310001' AND S.SBRQ>=LD_DEALMONTH AND S.SBRQ<LD_NEXTMONTH AND S.ZFBZ IS NULL
                       AND T.HGCODE IN (SELECT R.HGGQKA_DM FROM JCFX_CS_MGKA R WHERE R.SWJGDM=BJTS_CUR_NSR_SWJGDM_001) ) TT;
          END;

          UPDATE JCFX_DATA_QYYHZ AS A
             SET CK_SB_XSEMY=LN_CK_SB_XSEMY,
    CK_SB_XSERMB=LN_CK_SB_XSERMB,
    CK_SB_JSJE=LN_CK_SB_JSJE,
    CK_SB_JHCB=LN_CK_SB_JHCB,
    CK_SB_TSE=LN_CK_SB_TSE,
    CK_SB_MDE=LN_CK_SB_MDE,
    CK_HZ_TSE=LN_CK_HZ_TSE,
    CK_HZ_MDE=LN_CK_HZ_MDE,
    CK_BL_TSE=LN_CK_BL_TSE,
    CK_BL_MDE=LN_CK_BL_MDE,
    CK_XZSP_CKE=LN_CK_XZSP_CKE,
    CK_XZGHS_JSJE=LN_CK_XZGHS_JSJE,
    CK_TSSP_CKE=LN_CK_TSSP_CKE,
    CK_MGSP_CKE=LN_CK_MGSP_CKE,
    CK_MGKA_CKE=LN_CK_MGKA_CKE,
    BJTS_ZT='Y',
    BJTS_SJ=CURRENT_TIMESTAMP,
    SJGXSJ=CURRENT_TIMESTAMP
          WHERE DJXH=BJTS_CUR_NSR_DJXH_001 AND NY=LC_NY;
          COMMIT;

        END IF;
      END;

      SET LD_DEALMONTH =LD_NEXTMONTH;
    END LOOP BJTS_LOOP_001;

    UPDATE JCFX_NSR_BADJ_TOHZ SET JCFXSJ = CURRENT_TIMESTAMP WHERE DJXH=BJTS_CUR_NSR_DJXH_001;
    COMMIT;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  DO '检测分析初始化完成';
  LEAVE routine_body;
END$$

DELIMITER ;
