DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S10101$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S10101
/*
 * 企业经营稳定性
 * ZB_VAL：最后一次变更法人代表时间（未变更按税务登记时间）至报告期止月数
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10),
  IN P_BGQ_Z DATETIME
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT ROUND(TIMESTAMPDIFF(MONTH, MAX(CAST(DATE_FORMAT(IFNULL(S.LRRQ, T.SWDJ_DATE), '%Y-%m-01') AS DATETIME)), P_BGQ_Z)),
           '[d]报告期截止日期=' || DATE_FORMAT(P_BGQ_Z, '%Y%m%d') || 
           '|税务登记日期=' || DATE_FORMAT(MAX(T.SWDJ_DATE), '%Y%m%d') ||
           '|最近变更法人代表日期=' || DATE_FORMAT(MAX(S.LRRQ), '%Y%m%d')
      INTO V_ZB_VAL, V_PARAMS
      FROM GLXT_BB_SHXT_DJXX T
      LEFT JOIN CKTS_DJ_BGDJMX S ON S.DJXH=T.DJXH_JS AND S.BGQNR<>S.BGHNR AND S.LRRQ<=P_BGQ_Z
     WHERE T.DJXH_JS=P_DJXH;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10101' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10101',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10101';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
