DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S30101$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S30101
/*
 * 出口额变动率异常
 * ZB_VAL：（报告期出口销售额-基期出口销售额）÷基期出口销售额×100%
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_JQID DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT S.CK_CKEUSD
      INTO V_THIS_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;
    SELECT S.CK_CKEUSD
      INTO V_LAST_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_JQID;

    SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]报告期出口美元销售额=', V_THIS_DATA), '|基期出口美元销售额='), V_LAST_DATA);
    IF V_THIS_DATA>0 AND V_LAST_DATA>0 THEN
      SET V_ZB_VAL =ROUND(100 * (V_THIS_DATA - V_THIS_DATA) / V_LAST_DATA,2);
    ELSE
      SET V_ZB_VAL = NULL;
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30101' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30101',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30101';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
