DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W30104$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W30104
/*
 * 企业出口货物拼箱占比
 * ZB_VAL：100 * 拼箱18位报关单数量 / 全部18位报关单数量，报告期出口报关单数量小于10，输出0
 */
(
  IN P_BGQID DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT T.CK_BGDSL, T.CK_PXBGDSL
      INTO V_THIS_DATA, V_LAST_DATA
      FROM JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    SET V_PARAMS = '[d]报告期出口报关单数量=' || V_THIS_DATA || '|其中拼箱报关单数量=' || V_LAST_DATA;
    IF V_THIS_DATA<=1 OR V_LAST_DATA<0 THEN
      SET V_ZB_VAL = NULL;
    ELSE
      SET V_ZB_VAL =LEAST(100, ROUND(100 * V_LAST_DATA / V_THIS_DATA, 2));
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30104' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W30104',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30104';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
