DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_ZBU_QSPJ$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_ZBU_QSPJ
/*
 * 全省平均数据刷新口径
 */
(
  IN P_ZBYEAR VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE V_SQL_SELECT      VARCHAR(1000);
  DECLARE V_QSPJZ           DECIMAL(18,2); --  全省平均值
  DECLARE V_ROWS            BIGINT;  -- 待更新表中是否存在目标记录

  BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_BGQ_BGQID_002 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_QYLX_002 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_BGQ_Q_002 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_BGQ_Z_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT T.BGQID, T.QYLX, T.BGQ_Q, T.BGQ_Z
                    FROM JKGL_DATA_BGQ_QSPJ T
                   WHERE P_ZBYEAR IS NULL
                      OR DATE_FORMAT(T.BGQ_Q, '%Y')=P_ZBYEAR;
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_CUR_BGQ_BGQID_002, BJTS_CUR_BGQ_QYLX_002, BJTS_CUR_BGQ_BGQ_Q_002, BJTS_CUR_BGQ_BGQ_Z_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
    -- 锁定正在处理的报告期
    UPDATE JKGL_DATA_BGQ_QSPJ AS T
       SET TQBZ=REPLACE(UUID(), '-', ''),
    TQSJ=CURRENT_TIMESTAMP,
    SXZT='1'
     WHERE T.BGQID=BJTS_CUR_BGQ_BGQID_002;
    COMMIT;

    -- 确定 JKGL_QSPJ_JGB.BGQID 存在
    SELECT LEAST(COUNT(1), 1)
      INTO V_ROWS
      FROM JKGL_QSPJ_JGB T
     WHERE T.BGQID=BJTS_CUR_BGQ_BGQID_002 AND 1=1;
    IF V_ROWS=0 THEN
      BEGIN
        INSERT INTO JKGL_QSPJ_JGB(ID,BGQID) VALUES (BJTS_CUR_BGQ_BGQID_002,BJTS_CUR_BGQ_BGQID_002);
        COMMIT;
      END;
    END IF;

    -- 更新全省平均数
    -- 毛利润
    SELECT ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('SELECT C.CW_MLL AS OBJ FROM GLXT_BB_SHXT_DJXX A', ' INNER JOIN JKGL_DATA_BGQ B ON B.DJXH=A.DJXH_JS'), ' INNER JOIN JKGL_DATA_TJ_ZBU_KZ C ON C.BGQID=B.BGQID'), (CASE BJTS_CUR_BGQ_QYLX_002 WHEN '1' THEN ' WHERE A.JSMODE=''1''' ELSE ' WHERE A.JSMODE=''2''' END)), ' AND B.BGQ_Q='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Q_002, '%Y-%m-%d')), ''''), ' AND B.BGQ_Z='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Z_002, '%Y-%m-%d')), ''''), ' AND C.CW_MLL IS NOT NULL')
      INTO V_SQL_SELECT
;

    CALL F_MY_STDAVG_TMPTB(V_SQL_SELECT, V_QSPJZ);

    UPDATE JKGL_QSPJ_JGB
       SET MLL = V_QSPJZ
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_002;
    COMMIT;

    -- 还原税负率
    SELECT ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('SELECT C.CW_HYSFL AS OBJ FROM GLXT_BB_SHXT_DJXX A', ' INNER JOIN JKGL_DATA_BGQ B ON B.DJXH=A.DJXH_JS'), ' INNER JOIN JKGL_DATA_TJ_ZBU_KZ C ON C.BGQID=B.BGQID'), (CASE BJTS_CUR_BGQ_QYLX_002 WHEN '1' THEN ' WHERE A.JSMODE=''1''' ELSE ' WHERE A.JSMODE=''2''' END)), ' AND B.BGQ_Q='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Q_002, '%Y-%m-%d')), ''''), ' AND B.BGQ_Z='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Z_002, '%Y-%m-%d')), ''''), ' AND C.CW_HYSFL IS NOT NULL')
      INTO V_SQL_SELECT
;

    CALL F_MY_STDAVG_TMPTB(V_SQL_SELECT, V_QSPJZ);

    UPDATE JKGL_QSPJ_JGB
       SET HYSFL = V_QSPJZ
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_002;
    COMMIT;

    -- 费用收入比
    SELECT ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('SELECT ROUND(100 * C.LR_XSFY / C.LR_YYSR, 2) AS OBJ FROM GLXT_BB_SHXT_DJXX A', ' INNER JOIN JKGL_DATA_BGQ B ON B.DJXH=A.DJXH_JS'), ' INNER JOIN JKGL_DATA_TJ_ZBU C ON C.BGQID=B.BGQID'), (CASE BJTS_CUR_BGQ_QYLX_002 WHEN '1' THEN ' WHERE A.JSMODE=''1''' ELSE ' WHERE A.JSMODE=''2''' END)), ' AND B.BGQ_Q='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Q_002, '%Y-%m-%d')), ''''), ' AND B.BGQ_Z='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Z_002, '%Y-%m-%d')), ''''), ' AND C.LR_YYSR>1')
      INTO V_SQL_SELECT
;

    CALL F_MY_STDAVG_TMPTB(V_SQL_SELECT, V_QSPJZ);

    UPDATE JKGL_QSPJ_JGB
       SET FYSRB = V_QSPJZ
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_002;
    COMMIT;

    -- 单位固定资产销售额
    SELECT ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('SELECT ROUND(2*C.ZZS_XSE_QB/(C.ZC_GDZC_QC+C.ZC_GDZC_QM),2) AS OBJ', '  FROM GLXT_BB_SHXT_DJXX A'), ' INNER JOIN JKGL_DATA_BGQ B ON B.DJXH=A.DJXH_JS'), ' INNER JOIN JKGL_DATA_TJ_ZBU C ON C.BGQID=B.BGQID'), (CASE BJTS_CUR_BGQ_QYLX_002 WHEN '1' THEN ' WHERE A.JSMODE=''1''' ELSE ' WHERE A.JSMODE=''2''' END)), ' AND B.BGQ_Q='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Q_002, '%Y-%m-%d')), ''''), ' AND B.BGQ_Z='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Z_002, '%Y-%m-%d')), ''''), ' AND C.ZC_GDZC_QC + C.ZC_GDZC_QM<>0')
      INTO V_SQL_SELECT
;

    CALL F_MY_STDAVG_TMPTB(V_SQL_SELECT, V_QSPJZ);

    UPDATE JKGL_QSPJ_JGB
       SET DWGDZCXSE = V_QSPJZ
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_002;
    COMMIT;

    -- 单位经营面积销售额
    SELECT ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('SELECT ROUND(C.ZZS_XSE_QB / D.YJBGCS_MJ, 2) AS OBJ', '  FROM GLXT_BB_SHXT_DJXX A'), ' INNER JOIN JKGL_DATA_BGQ B ON B.DJXH=A.DJXH_JS'), ' INNER JOIN JKGL_DATA_TJ_ZBU C ON C.BGQID=B.BGQID'), ' INNER JOIN JKGL_ZLCJ_JGB D ON D.DJXH=A.DJXH_JS'), (CASE BJTS_CUR_BGQ_QYLX_002 WHEN '1' THEN ' WHERE A.JSMODE=''1''' ELSE ' WHERE A.JSMODE=''2''' END)), ' AND B.BGQ_Q='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Q_002, '%Y-%m-%d')), ''''), ' AND B.BGQ_Z='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Z_002, '%Y-%m-%d')), ''''), ' AND D.YJBGCS_MJ<>0')
      INTO V_SQL_SELECT
;

    CALL F_MY_STDAVG_TMPTB(V_SQL_SELECT, V_QSPJZ);

    UPDATE JKGL_QSPJ_JGB
       SET DWJYMJXSE = V_QSPJZ
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_002;
    COMMIT;

    -- 确定 JKGL_QSPJ_CKSP.BGQID 不存在
    DELETE FROM JKGL_QSPJ_CKSP AS T WHERE T.BGQID=BJTS_CUR_BGQ_BGQID_002;
    COMMIT;

    -- ID  N NUMBER(20)  N     序号
    -- BGQID N NUMBER(20)  Y     报告期ID 关联主表PK_JKGL_DATA_BGQ
    -- SP8_DM N VARCHAR2(8) Y     商品代码（8）
    -- CKEUSD  N NUMBER(18,2)  Y     出口额USD
    -- CKERMB N NUMBER(18,2)  Y     出口额
    -- CKSL  N NUMBER(18,2)  Y     出口数量
    -- QYHS  N INTEGER Y     企业户数
    INSERT INTO JKGL_QSPJ_CKSP (ID,BGQID,SP8_DM,CKEUSD,CKERMB,CKSL,QYHS)
         SELECT SEQ_NEXTVAL('SEQ_JKGL_QSPJ_CKSP'),BJTS_CUR_BGQ_BGQID_002,SP8_DM,CKEUSD,CKERMB,CKSL,QYHS
           FROM (SELECT C.SP8_DM,SUM(C.CKSL) AS CKSL,SUM(C.CKEUSD) AS CKEUSD,SUM(C.CKERMB) AS CKERMB,
                        COUNT(DISTINCT A.DJXH_JS) AS QYHS
                   FROM GLXT_BB_SHXT_DJXX A
                  INNER JOIN JKGL_DATA_BGQ B ON B.DJXH=A.DJXH_JS
                  INNER JOIN JKGL_DATA_TJ_ZBU_CKSP C ON C.BGQID=B.BGQID
                  WHERE (CASE A.JSMODE WHEN '1' THEN '1' ELSE '2' END)=BJTS_CUR_BGQ_QYLX_002
                    AND B.BGQ_Q=BJTS_CUR_BGQ_BGQ_Q_002
                    AND B.BGQ_Z=BJTS_CUR_BGQ_BGQ_Z_002
                  GROUP BY C.SP8_DM) TT;
    COMMIT;

    -- CKDJ  N NUMBER(18,2)  Y     出口单价
    -- MMYLR N NUMBER(18,2)  Y     每美元利润
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_CKSP_ID_001 LONGTEXT;
  DECLARE BJTS_CUR_CKSP_SP8_DM_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT ID,SP8_DM FROM JKGL_QSPJ_CKSP WHERE BGQID=BJTS_CUR_BGQ_BGQID_002 ORDER BY ID;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_CKSP_ID_001, BJTS_CUR_CKSP_SP8_DM_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SELECT ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('SELECT C.CKDJ AS OBJ FROM GLXT_BB_SHXT_DJXX A', ' INNER JOIN JKGL_DATA_BGQ B ON B.DJXH=A.DJXH_JS'), ' INNER JOIN JKGL_DATA_TJ_ZBU_CKSP C ON C.BGQID=B.BGQID'), (CASE BJTS_CUR_BGQ_QYLX_002 WHEN '1' THEN ' WHERE A.JSMODE=''1''' ELSE ' WHERE A.JSMODE=''2''' END)), ' AND B.BGQ_Q='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Q_002, '%Y-%m-%d')), ''''), ' AND B.BGQ_Z='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Z_002, '%Y-%m-%d')), ''''), ' AND C.SP8_DM='''), BJTS_CUR_CKSP_SP8_DM_001), ''''), ' AND C.CKDJ IS NOT NULL')
        INTO V_SQL_SELECT
;

      CALL F_MY_STDAVG_TMPTB(V_SQL_SELECT, V_QSPJZ);

      UPDATE JKGL_QSPJ_CKSP
         SET CKDJ = V_QSPJZ
       WHERE ID=BJTS_CUR_CKSP_ID_001;
      COMMIT;

      IF BJTS_CUR_BGQ_QYLX_002 = '2' THEN
        SELECT ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('SELECT C.MMYLR AS OBJ FROM GLXT_BB_SHXT_DJXX A', ' INNER JOIN JKGL_DATA_BGQ B ON B.DJXH=A.DJXH_JS'), ' INNER JOIN JKGL_DATA_TJ_ZBU_TSSP C ON C.BGQID=B.BGQID'), ' WHERE A.JSMODE=''2'''), ' AND B.BGQ_Q='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Q_002, '%Y-%m-%d')), ''''), ' AND B.BGQ_Z='''), DATE_FORMAT(BJTS_CUR_BGQ_BGQ_Z_002, '%Y-%m-%d')), ''''), ' AND C.SP8_DM='''), BJTS_CUR_CKSP_SP8_DM_001), ''''), ' AND C.MMYLR IS NOT NULL')
          INTO V_SQL_SELECT
;

        CALL F_MY_STDAVG_TMPTB(V_SQL_SELECT, V_QSPJZ);

        UPDATE JKGL_QSPJ_CKSP
           SET MMYLR = V_QSPJZ
         WHERE ID=BJTS_CUR_CKSP_ID_001;
        COMMIT;
      END IF;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

    -- 解锁处理完成的报告期
    UPDATE JKGL_DATA_BGQ_QSPJ AS T
       SET TQBZ=NULL,
    WCSJ=CURRENT_TIMESTAMP,
    SXZT='2'
     WHERE T.BGQID=BJTS_CUR_BGQ_BGQID_002;
    COMMIT;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;

  LEAVE routine_body;
END$$

DELIMITER ;
