DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S30201$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S30201
/*
 * 商品出口额超1WUSD且环比>150% 的商品数量
 *（判定是否属于同一类商品以8位HS编码是否相同为准。）
 * ZB_VAL：商品出口额超1WUSD且环比>150% 的商品数量
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_JQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE VAL1         DECIMAL(18,2);    --参数1
  DECLARE VAL2         DECIMAL(18,2);    --参数1
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30201_SP_CKE_HB';
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30201_SP_CKE_JE';

    SET V_ZB_VAL = 0;
    FOR CUR_SPDM IN (SELECT T.SP8_DM,DM.CKSP_MC,T.CKEUSD,IFNULL(S.CKEUSD, 0) AS JQCKE
                       FROM JKGL_DATA_TJ_ZBU_CKSP T
                       LEFT JOIN JKGL_DATA_TJ_ZBU_CKSP S ON S.BGQID=P_JQID AND S.SP8_DM=T.SP8_DM
                       LEFT JOIN JCFX_DM_CKSPTREE DM ON DM.CKSP_DM=T.SP8_DM AND DM.CKSP_JC='4'
                      WHERE T.BGQID=P_BGQID
                        AND T.CKEUSD>=VAL2
                        AND T.CKEUSD>=VAL1 * IFNULL(S.CKEUSD, 0))
    LOOP
      SET V_ZB_VAL = V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        SET V_PARAMS = '[d]商品代码=' || CUR_SPDM.SP8_DM || '（' || CUR_SPDM.CKSP_MC ||'），报告期出口额=' || CUR_SPDM.CKEUSD || '，基期出口额=' || CUR_SPDM.JQCKE;
      ELSEIF V_ZB_VAL<=20 THEN
        SET V_PARAMS = V_PARAMS || '|商品代码=' || CUR_SPDM.SP8_DM || '（' || CUR_SPDM.CKSP_MC ||'），报告期出口额=' || CUR_SPDM.CKEUSD || '，基期出口额=' || CUR_SPDM.JQCKE;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      SET V_PARAMS = V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30201' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30201',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30201';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
