DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DEAL_JCFX_DATA_BGDMX$$

CREATE PROCEDURE PRO_DEAL_JCFX_DATA_BGDMX()
routine_body: BEGIN
  DECLARE V_BEGINDATE      DATETIME;
  DECLARE V_TSSWJG_DM      VARCHAR(11);
  DECLARE V_CKSPTSSPLX_DM  CHAR(1);
  DECLARE V_TSL            DECIMAL(18,2);
  DECLARE V_JGFSTSLX_DM    CHAR(1);
  DECLARE V_HYDXZQH_DM     CHAR(4);
  DECLARE LN_ROWS          BIGINT;
  DECLARE LN_REC           BIGINT;
  DECLARE LN_UNIT          BIGINT;

  SELECT DATE(MAX(T.SJGXSJ))
    INTO V_BEGINDATE
    FROM JCFX_DATA_BGDMX T;

  SELECT COUNT(1)
    INTO LN_ROWS
    FROM CKTS_WBSJ_HG_BGD T
   WHERE T.SJTB_SJ>=V_BEGINDATE;

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES (ORA_CONCAT('PRO_DEAL_JCFX_DATA_BGDMX 开始运行，记录总数：', LN_ROWS));
  COMMIT;

  -- 增量用数据更新时间
  SET LN_REC =0;
  SET LN_UNIT =0;
  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_BGD_UUID_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_TSSWJG_DM_1_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_DJXH_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_CKBGDH_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_CKNY_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_CKRQ_1_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_CKSP_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_HGGQKA_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_MYGDQSZ_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_JGFS_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_HZDWDQ_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_CKSL_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_MYLAJ_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_RMBLAJ_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_TSSBSL_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_DLSBSL_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_TYSL_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_MYLAJ_YSB_001 LONGTEXT;
  DECLARE BJTS_CUR_BGD_SJTB_SJ_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.UUID,T.TSSWJG_DM_1,T.DJXH,T.CKBGDH,T.CKNY,T.CKRQ_1,T.CKSP_DM,
                         T.HGGQKA_DM,T.MYGDQSZ_DM,T.JGFS_DM,T.HZDWDQ_DM,
                         T.CKSL,T.MYLAJ,T.RMBLAJ,T.TSSBSL,T.DLSBSL,T.TYSL,
                         CASE WHEN T.TSSBSL+T.DLSBSL+T.TYSL>T.CKSL+1 THEN T.CKSL / (T.TSSBSL+T.DLSBSL+T.TYSL) ELSE 1 END
                           * (T.TSSBMYLAJ + T.DLSBMYLAJ + T.TYMYLAJ) AS MYLAJ_YSB,
                         T.SJTB_SJ
                    FROM CKTS_WBSJ_HG_BGD T
                   WHERE T.SJTB_SJ>=V_BEGINDATE;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_BGD_UUID_001, BJTS_CUR_BGD_TSSWJG_DM_1_001, BJTS_CUR_BGD_DJXH_001, BJTS_CUR_BGD_CKBGDH_001, BJTS_CUR_BGD_CKNY_001, BJTS_CUR_BGD_CKRQ_1_001, BJTS_CUR_BGD_CKSP_DM_001, BJTS_CUR_BGD_HGGQKA_DM_001, BJTS_CUR_BGD_MYGDQSZ_DM_001, BJTS_CUR_BGD_JGFS_DM_001, BJTS_CUR_BGD_HZDWDQ_DM_001, BJTS_CUR_BGD_CKSL_001, BJTS_CUR_BGD_MYLAJ_001, BJTS_CUR_BGD_RMBLAJ_001, BJTS_CUR_BGD_TSSBSL_001, BJTS_CUR_BGD_DLSBSL_001, BJTS_CUR_BGD_TYSL_001, BJTS_CUR_BGD_MYLAJ_YSB_001, BJTS_CUR_BGD_SJTB_SJ_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    BEGIN
  DECLARE BJTS_SQLCODE_004 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_004 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_004 = MYSQL_ERRNO, BJTS_SQLERRM_004 = MESSAGE_TEXT;
        -- 找不到对应的基本商品
        INSERT INTO JCFX_DATA_BGDMX(UUID,TSSWJG_DM,DJXH,CKBGDH,NY,CKRQ,CKSP_DM,HGGQKA_DM,MYGDQSZ_DM,JGFS_DM,HZDWDQ_DM,MYLAJ,RMBLAJ,MYLAJ_YSB,SJGXSJ)
             VALUES (BJTS_CUR_BGD_UUID_001,BJTS_CUR_BGD_TSSWJG_DM_1_001,BJTS_CUR_BGD_DJXH_001,BJTS_CUR_BGD_CKBGDH_001,BJTS_CUR_BGD_CKNY_001,BJTS_CUR_BGD_CKRQ_1_001,BJTS_CUR_BGD_CKSP_DM_001,BJTS_CUR_BGD_HGGQKA_DM_001,BJTS_CUR_BGD_MYGDQSZ_DM_001,BJTS_CUR_BGD_JGFS_DM_001,BJTS_CUR_BGD_HZDWDQ_DM_001,BJTS_CUR_BGD_MYLAJ_001,BJTS_CUR_BGD_RMBLAJ_001,BJTS_CUR_BGD_MYLAJ_YSB_001,BJTS_CUR_BGD_SJTB_SJ_001);
        COMMIT;

  END;
SELECT A.TSSWJG_DM
        INTO V_TSSWJG_DM
        FROM JCFX_DATA_BGDMX A
       WHERE A.DJXH=BJTS_CUR_BGD_DJXH_001 AND A.CKBGDH=BJTS_CUR_BGD_CKBGDH_001;

      IF V_TSSWJG_DM=BJTS_CUR_BGD_TSSWJG_DM_1_001 THEN
        UPDATE JCFX_DATA_BGDMX AS A
           SET UUID=BJTS_CUR_BGD_UUID_001,
    NY=BJTS_CUR_BGD_CKNY_001,
    CKRQ=BJTS_CUR_BGD_CKRQ_1_001,
    CKSP_DM=BJTS_CUR_BGD_CKSP_DM_001,
    HGGQKA_DM=BJTS_CUR_BGD_HGGQKA_DM_001,
    MYGDQSZ_DM=BJTS_CUR_BGD_MYGDQSZ_DM_001,
    JGFS_DM=BJTS_CUR_BGD_JGFS_DM_001,
    HZDWDQ_DM=BJTS_CUR_BGD_HZDWDQ_DM_001,
    MYLAJ=BJTS_CUR_BGD_MYLAJ_001,
    RMBLAJ=BJTS_CUR_BGD_RMBLAJ_001,
    MYLAJ_YSB=BJTS_CUR_BGD_MYLAJ_YSB_001,
    SJGXSJ=BJTS_CUR_BGD_SJTB_SJ_001
         WHERE A.DJXH=BJTS_CUR_BGD_DJXH_001 AND A.CKBGDH=BJTS_CUR_BGD_CKBGDH_001;
        COMMIT;
      ELSE
        DELETE FROM JCFX_DATA_BGDMX AS A WHERE A.DJXH=BJTS_CUR_BGD_DJXH_001 AND A.CKBGDH=BJTS_CUR_BGD_CKBGDH_001;
        COMMIT;
        INSERT INTO JCFX_DATA_BGDMX(UUID,TSSWJG_DM,DJXH,CKBGDH,NY,CKRQ,CKSP_DM,HGGQKA_DM,MYGDQSZ_DM,JGFS_DM,HZDWDQ_DM,MYLAJ,RMBLAJ,MYLAJ_YSB,SJGXSJ)
             VALUES (BJTS_CUR_BGD_UUID_001,BJTS_CUR_BGD_TSSWJG_DM_1_001,BJTS_CUR_BGD_DJXH_001,BJTS_CUR_BGD_CKBGDH_001,BJTS_CUR_BGD_CKNY_001,BJTS_CUR_BGD_CKRQ_1_001,BJTS_CUR_BGD_CKSP_DM_001,BJTS_CUR_BGD_HGGQKA_DM_001,BJTS_CUR_BGD_MYGDQSZ_DM_001,BJTS_CUR_BGD_JGFS_DM_001,BJTS_CUR_BGD_HZDWDQ_DM_001,BJTS_CUR_BGD_MYLAJ_001,BJTS_CUR_BGD_RMBLAJ_001,BJTS_CUR_BGD_MYLAJ_YSB_001,BJTS_CUR_BGD_SJTB_SJ_001);
        COMMIT;
      END IF;
    END;

    BEGIN
  DECLARE BJTS_SQLCODE_003 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_003 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_003 = MYSQL_ERRNO, BJTS_SQLERRM_003 = MESSAGE_TEXT;
        -- 找不到对应的基本商品
        SET V_HYDXZQH_DM ='0000';

  END;
SELECT S.XZQH_DM
        INTO V_HYDXZQH_DM
        FROM DM_HGHYD S
       WHERE S.HGHYD_DM=BJTS_CUR_BGD_HZDWDQ_DM_001
         AND 1=1
LIMIT 1;
    END;

    BEGIN
  DECLARE BJTS_SQLCODE_002 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_002 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_002 = MYSQL_ERRNO, BJTS_SQLERRM_002 = MESSAGE_TEXT;
        -- 找不到对应的基本商品
        SET V_CKSPTSSPLX_DM ='0';
        SET V_TSL =0;

  END;
SELECT CKSPTSSPLX_DM,TSL
        INTO V_CKSPTSSPLX_DM, V_TSL
        FROM (SELECT CKSPTSSPLX_DM,TSL
                FROM (SELECT IFNULL(A.CKSPTSSPLX_DM, '0') AS CKSPTSSPLX_DM,A.TSL
                        FROM CKTS_DM_TSLVWK A
                       WHERE A.CKSP_DM LIKE ORA_CONCAT(BJTS_CUR_BGD_CKSP_DM_001, '%') AND (BJTS_CUR_BGD_CKRQ_1_001 BETWEEN A.YXQQ AND A.YXQZ) AND A.JBSPBZ='Y'
                       UNION ALL
                      SELECT IFNULL(B.CKSPTSSPLX_DM, '0') AS CKSPTSSPLX_DM,B.TSL
                        FROM CKTS_DM_TSLVWK B
                       WHERE B.CKSP_DM = SUBSTR(BJTS_CUR_BGD_CKSP_DM_001,1,8) AND (BJTS_CUR_BGD_CKRQ_1_001 BETWEEN B.YXQQ AND B.YXQZ) AND B.JBSPBZ='Y'
                      ) S
               ORDER BY TSL DESC) R
       WHERE 1=1
LIMIT 1;
    END;

    BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
        SET V_JGFSTSLX_DM ='1';

  END;
SELECT JGFSTSLX_DM
        INTO V_JGFSTSLX_DM
        FROM CKTS_DM_HGJGFS A
       WHERE A.JGFS_DM=BJTS_CUR_BGD_JGFS_DM_001;
    END;

    IF V_CKSPTSSPLX_DM='1' THEN
      UPDATE JCFX_DATA_BGDMX AS T
         SET MYLAJ_ZS=T.MYLAJ,
    HYDXZQH_DM=V_HYDXZQH_DM
       WHERE T.DJXH=BJTS_CUR_BGD_DJXH_001 AND T.CKBGDH=BJTS_CUR_BGD_CKBGDH_001;
    ELSEIF V_CKSPTSSPLX_DM='2' THEN
      UPDATE JCFX_DATA_BGDMX AS T
         SET MYLAJ_MS=T.MYLAJ,
    HYDXZQH_DM=V_HYDXZQH_DM
       WHERE T.DJXH=BJTS_CUR_BGD_DJXH_001 AND T.CKBGDH=BJTS_CUR_BGD_CKBGDH_001;
    ELSEIF V_JGFSTSLX_DM='0' THEN
      UPDATE JCFX_DATA_BGDMX AS T
         SET MYLAJ_BTS=T.MYLAJ,
    HYDXZQH_DM=V_HYDXZQH_DM
       WHERE T.DJXH=BJTS_CUR_BGD_DJXH_001 AND T.CKBGDH=BJTS_CUR_BGD_CKBGDH_001;
    ELSE
      UPDATE JCFX_DATA_BGDMX AS T
         SET MYLAJ_KTS=T.MYLAJ,
    TSL=V_TSL,
    YGTMSE=ROUND(T.RMBLAJ * V_TSL / 100,2),
    HYDXZQH_DM=V_HYDXZQH_DM
       WHERE T.DJXH=BJTS_CUR_BGD_DJXH_001 AND T.CKBGDH=BJTS_CUR_BGD_CKBGDH_001;
    END IF;
    COMMIT;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_DEAL_JCFX_DATA_BGDMX 处理结束！');
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
