DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DEAL_HWCYTS$$

CREATE PROCEDURE PRO_DEAL_HWCYTS
/*
 * 处理海外仓预退税数据
 */
routine_body: BEGIN
  DECLARE V_BEGINDATE      DATETIME;
  DECLARE LC_SBYY          VARCHAR(2000);

  SET V_BEGINDATE = TRUNCATE(CURRENT_TIMESTAMP, 0)-3;

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('RCGL_SDQY_9810数据处理开始...');
  COMMIT;
  
  --免抵退税
  BEGIN
    MERGE INTO RCGL_SDQY_9810 A
         USING (SELECT DISTINCT S.DJXH,IFNULL(T.SHXYNO, T.NSRDJNO) AS NSRSBH,T.NSRMC,S.TSSWJG_DM
                  FROM CKTS_SB_MDT_CKMX S
                 INNER JOIN GLXT_BB_SHXT_DJXX T ON T.DJXH_JS=S.DJXH
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND REGEXP_LIKE(S.CKTMSYWLXDMJH,'HWC-YT')) B
            ON (A.DJXH=B.DJXH)
          WHEN NOT MATCHED THEN
            INSERT (ID,DJXH,NSRSBH,NSRMC,SWJGDM,QYBJ,CJR,CRTIME)
            VALUES (B.DJXH,B.DJXH,B.NSRSBH,B.NSRMC,B.TSSWJG_DM,'Y','SYSTEM',CURRENT_TIMESTAMP);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET LC_SBYY =SQLERRM;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('CKTS_SB_MDT_CKMX-->RCGL_SDQY_9810失败！', LC_SBYY);
      COMMIT;
  END;

  --免退税
  BEGIN
    MERGE INTO RCGL_SDQY_9810 A
         USING (SELECT DISTINCT S.DJXH,IFNULL(T.SHXYNO, T.NSRDJNO) AS NSRSBH,T.NSRMC,S.TSSWJG_DM
                  FROM CKTS_SB_MTS_CKMX S
                 INNER JOIN GLXT_BB_SHXT_DJXX T ON T.DJXH_JS=S.DJXH
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND REGEXP_LIKE(S.CKTMSYWLXDMJH,'HWC-YT')) B
            ON (A.DJXH=B.DJXH)
          WHEN NOT MATCHED THEN
            INSERT (ID,DJXH,NSRSBH,NSRMC,SWJGDM,QYBJ,CJR,CRTIME)
            VALUES (B.DJXH,B.DJXH,B.NSRSBH,B.NSRMC,B.TSSWJG_DM,'Y','SYSTEM',CURRENT_TIMESTAMP);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET LC_SBYY =SQLERRM;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('CKTS_SB_MTS_CKMX-->RCGL_SDQY_9810失败！', LC_SBYY);
      COMMIT;
  END;
  
  --代办退税
  BEGIN
    MERGE INTO RCGL_SDQY_9810 A
         USING (SELECT DISTINCT S.DJXH,IFNULL(T.SHXYNO, T.NSRDJNO) AS NSRSBH,T.NSRMC,S.TSSWJG_DM
                  FROM CKTS_SB_WZF_CKMX S
                 INNER JOIN GLXT_BB_SHXT_DJXX T ON T.DJXH_JS=S.DJXH
                 WHERE S.SJTB_SJ>=V_BEGINDATE
                   AND REGEXP_LIKE(S.CKTMSYWLXDMJH,'HWC-YT')) B
            ON (A.DJXH=B.DJXH)
          WHEN NOT MATCHED THEN
            INSERT (ID,DJXH,NSRSBH,NSRMC,SWJGDM,QYBJ,CJR,CRTIME)
            VALUES (B.DJXH,B.DJXH,B.NSRSBH,B.NSRMC,B.TSSWJG_DM,'Y','SYSTEM',CURRENT_TIMESTAMP);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      SET LC_SBYY =SQLERRM;
      INSERT INTO CKTS_LOG_DEALDATA(CZJL,SBYY) VALUES ('CKTS_SB_WZF_CKMX-->RCGL_SDQY_9810失败！', LC_SBYY);
      COMMIT;
  END;
  
  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('RCGL_SDQY_9810数据处理结束。');
  COMMIT;
  
  LEAVE routine_body;
END$$

DELIMITER ;
