DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W20203$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W20203
/*
 * 综合换汇成本异常=进项发票总金额/出口额人民币
 * ZB_VAL：TL_TSSH.JKGL_DATA_TJ_ZBU.TS_HHCB
 */
(
  IN P_BGQID DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT T.TS_HHCB, ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]申报退税总计税金额=', T.TS_JSJE), '|申报退税报关单人民币销售额='), T.TS_CKERMB)
      INTO V_ZB_VAL, V_PARAMS
      FROM JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID
       AND T.TS_HHCB>0;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20203' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W20203',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20203';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
