DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DXTX_JJYQ$$

CREATE PROCEDURE PRO_DXTX_JJYQ()
/*
 * 20260515，根据杭州市局王薇意见，每年4月申报期增加卷烟免税核销的提醒
 */
routine_body: BEGIN
  DECLARE LL_JJR        BIGINT;
  DECLARE LL_TSSB       BIGINT;
  DECLARE LL_FUH        BIGINT;
  DECLARE LL_FUHCL      BIGINT;
  DECLARE LL_SDHC       BIGINT;
  DECLARE LL_FXCK       BIGINT;
  DECLARE LL_NKSQTX     BIGINT;
  DECLARE LL_NKSHJD     BIGINT;
  DECLARE LL_MSZMHX     BIGINT;
  DECLARE LC_SWJGDM     VARCHAR(11);
  DECLARE LC_MSG        VARCHAR(200);

  SELECT COUNT(1)
    INTO LL_JJR
    FROM PUB_JJR T
   WHERE T.JJR_DATE=DATE(CURRENT_TIMESTAMP);

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_USER_ID_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_JOB_TYPE_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_PHONE_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_SWJG_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_SWJG_MC_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_USERNAME_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_JJYQ_TSSB_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_JJYQ_FUH_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_JJYQ_FUHCL_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_JJYQ_SDHC_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_FXCK_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_NKSQTX_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_NKSHJD_001 LONGTEXT;
  DECLARE BJTS_CUR_USER_JJRTXBZ_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.ID,T.JOB_TYPE,T.PHONE,T.SWJG_DM,T.SWJG_MC,T.USERNAME,
                          T.JJYQ_TSSB,T.JJYQ_FUH,T.JJYQ_FUHCL,T.JJYQ_SDHC,T.FXCK,T.NKSQTX,T.NKSHJD,T.JJRTXBZ
                    FROM MSG_PUSH_USER T
                   WHERE T.QYBZ='Y';
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_USER_ID_001, BJTS_CUR_USER_JOB_TYPE_001, BJTS_CUR_USER_PHONE_001, BJTS_CUR_USER_SWJG_DM_001, BJTS_CUR_USER_SWJG_MC_001, BJTS_CUR_USER_USERNAME_001, BJTS_CUR_USER_JJYQ_TSSB_001, BJTS_CUR_USER_JJYQ_FUH_001, BJTS_CUR_USER_JJYQ_FUHCL_001, BJTS_CUR_USER_JJYQ_SDHC_001, BJTS_CUR_USER_FXCK_001, BJTS_CUR_USER_NKSQTX_001, BJTS_CUR_USER_NKSHJD_001, BJTS_CUR_USER_JJRTXBZ_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    IF BJTS_CUR_USER_JJRTXBZ_001='N' AND LL_JJR>0 THEN
      ITERATE BJTS_CURSOR_LOOP_001;
    END IF;
    IF BJTS_CUR_USER_JOB_TYPE_001 IN ('1','2') THEN -- 区县局
      BEGIN
        IF BJTS_CUR_USER_JJYQ_TSSB_001='Y' THEN
          BEGIN
            SELECT COUNT(1)
              INTO LL_TSSB
              FROM MSG_PUSH_DATA S
             WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='退税办理' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
            IF LL_TSSB>0 THEN
              INSERT INTO MSG_PUSH_PLAN(ID,USERID,CONTENT,SEND_TYPE,SEND_TARG,CRTIME,PLAN_FLAG,QYBZ,PLAN_TAG,SWJG_DM,USERNAME)
                   SELECT SEQ_NEXTVAL('SEQ_MSG_PUSH_PLAN'),BJTS_CUR_USER_ID_001,
                          ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('温馨提醒：[', BJTS_CUR_USER_SWJG_MC_001), ']，有'), LL_TSSB), '笔出口退(免)税业务即将超期，请及时办理。谢谢！'),
                          '0',BJTS_CUR_USER_PHONE_001,CURRENT_TIMESTAMP,'0','Y',ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-%d'), '-01'),
                          BJTS_CUR_USER_SWJG_DM_001,BJTS_CUR_USER_USERNAME_001
;
              COMMIT;
            END IF;
          END;
        END IF;

        IF BJTS_CUR_USER_JJYQ_FUH_001='Y' THEN
          BEGIN
            SELECT COUNT(1)
              INTO LL_FUH
              FROM MSG_PUSH_DATA S
             WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='函调复函' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
            IF LL_FUH>0 THEN
              INSERT INTO MSG_PUSH_PLAN(ID,USERID,CONTENT,SEND_TYPE,SEND_TARG,CRTIME,PLAN_FLAG,QYBZ,PLAN_TAG,SWJG_DM,USERNAME)
                   SELECT SEQ_NEXTVAL('SEQ_MSG_PUSH_PLAN'),BJTS_CUR_USER_ID_001,
                          ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('温馨提醒：[', BJTS_CUR_USER_SWJG_MC_001), ']，'), S.YWBZ), '的函调业务即将超期，请及时办理。谢谢！'),
                          '0',BJTS_CUR_USER_PHONE_001,CURRENT_TIMESTAMP,'0','Y',ORA_CONCAT(ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-%d'), '-02-'), S.BIZKEY),BJTS_CUR_USER_SWJG_DM_001,BJTS_CUR_USER_USERNAME_001
                     FROM MSG_PUSH_DATA S
                    WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='函调复函' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
              COMMIT;
            END IF;
          END;
        END IF;

        IF BJTS_CUR_USER_JJYQ_FUHCL_001='Y' THEN
          BEGIN
            SELECT COUNT(1)
              INTO LL_FUHCL
              FROM MSG_PUSH_DATA S
             WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='函调处理' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
            IF LL_FUHCL>0 THEN
              INSERT INTO MSG_PUSH_PLAN(ID,USERID,CONTENT,SEND_TYPE,SEND_TARG,CRTIME,PLAN_FLAG,QYBZ,PLAN_TAG,SWJG_DM,USERNAME)
                   SELECT SEQ_NEXTVAL('SEQ_MSG_PUSH_PLAN'),BJTS_CUR_USER_ID_001,
                          ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('温馨提醒：[', BJTS_CUR_USER_SWJG_MC_001), ']，'), S.YWBZ), '已于'), DATE_FORMAT(QDSJ, '%Y-%m-%d')), '回函，请及时办理。谢谢！'),
                          '0',BJTS_CUR_USER_PHONE_001,CURRENT_TIMESTAMP,'0','Y',ORA_CONCAT(ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-%d'), '-05-'), S.BIZKEY),BJTS_CUR_USER_SWJG_DM_001,BJTS_CUR_USER_USERNAME_001
                     FROM MSG_PUSH_DATA S
                    WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='函调处理' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
              COMMIT;
            END IF;
          END;
        END IF;

        IF BJTS_CUR_USER_JJYQ_SDHC_001='Y' THEN
          BEGIN
            SELECT COUNT(1)
              INTO LL_SDHC
              FROM MSG_PUSH_DATA S
             WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='容缺办理' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
            IF LL_SDHC>0 THEN
              INSERT INTO MSG_PUSH_PLAN(ID,USERID,CONTENT,SEND_TYPE,SEND_TARG,CRTIME,PLAN_FLAG,QYBZ,PLAN_TAG,SWJG_DM,USERNAME)
                   SELECT SEQ_NEXTVAL('SEQ_MSG_PUSH_PLAN'),BJTS_CUR_USER_ID_001,
                          ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('温馨提醒：[', BJTS_CUR_USER_SWJG_MC_001), ']，税号['), S.NSRSBH), ']的容缺办理退税业务，实地核查即将超期，请及时办理。谢谢！'),
                          '0',BJTS_CUR_USER_PHONE_001,CURRENT_TIMESTAMP,'0','Y',ORA_CONCAT(ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-%d'), '-03-'), S.BIZKEY),BJTS_CUR_USER_SWJG_DM_001,BJTS_CUR_USER_USERNAME_001
                     FROM MSG_PUSH_DATA S
                    WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='容缺办理' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
              COMMIT;
            END IF;
          END;
        END IF;

        IF BJTS_CUR_USER_FXCK_001='Y' THEN
          BEGIN
            SELECT COUNT(1)
              INTO LL_FXCK
              FROM MSG_PUSH_DATA S
             WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='风险出口电子信息' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
            IF LL_FXCK>0 THEN
              INSERT INTO MSG_PUSH_PLAN(ID,USERID,CONTENT,SEND_TYPE,SEND_TARG,CRTIME,PLAN_FLAG,QYBZ,PLAN_TAG,SWJG_DM,USERNAME)
                   SELECT SEQ_NEXTVAL('SEQ_MSG_PUSH_PLAN'),BJTS_CUR_USER_ID_001,
                          ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('温馨提醒：[', BJTS_CUR_USER_SWJG_MC_001), ']，您部门扫描到['), LL_FXCK), ']笔风险出口电子信息，请加强监管。详情请到便捷退税管理系统的短信关联业务查询！'),
                          '0',BJTS_CUR_USER_PHONE_001,CURRENT_TIMESTAMP,'0','Y',ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-%d'), '-04'),BJTS_CUR_USER_SWJG_DM_001,BJTS_CUR_USER_USERNAME_001
;
              COMMIT;
            END IF;
          END;
        END IF;

        IF BJTS_CUR_USER_NKSQTX_001='Y' THEN
          BEGIN
            SELECT COUNT(1)
              INTO LL_NKSQTX
              FROM MSG_PUSH_DATA S
             WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='内控提醒' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
            IF LL_NKSQTX>0 THEN
              INSERT INTO MSG_PUSH_PLAN(ID,USERID,CONTENT,SEND_TYPE,SEND_TARG,CRTIME,PLAN_FLAG,QYBZ,PLAN_TAG,SWJG_DM,USERNAME)
                   SELECT SEQ_NEXTVAL('SEQ_MSG_PUSH_PLAN'),BJTS_CUR_USER_ID_001,
                          ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('温馨提醒：[', BJTS_CUR_USER_SWJG_MC_001), ']，您部门扫描到['), LL_FXCK), ']笔内控风险事前提醒业务，请及时处理。详情请到便捷退税管理系统的内控管理——内控风险处理——事前提醒信息管理查询！'),
                          '0',BJTS_CUR_USER_PHONE_001,CURRENT_TIMESTAMP,'0','Y',ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-%d'), '-04'),BJTS_CUR_USER_SWJG_DM_001,BJTS_CUR_USER_USERNAME_001
;
              COMMIT;
            END IF;
          END;
        END IF;

        IF BJTS_CUR_USER_NKSHJD_001='Y' THEN
          BEGIN
            SELECT COUNT(1)
              INTO LL_NKSHJD
              FROM MSG_PUSH_DATA S
             WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='内控监督' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
            IF LL_NKSHJD>0 THEN
              INSERT INTO MSG_PUSH_PLAN(ID,USERID,CONTENT,SEND_TYPE,SEND_TARG,CRTIME,PLAN_FLAG,QYBZ,PLAN_TAG,SWJG_DM,USERNAME)
                   SELECT SEQ_NEXTVAL('SEQ_MSG_PUSH_PLAN'),BJTS_CUR_USER_ID_001,
                          ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('温馨提醒：[', BJTS_CUR_USER_SWJG_MC_001), ']，您部门扫描到['), LL_FXCK), ']笔内控风险事后监督业务，请及时处理。详情请到便捷退税管理系统的内控管理——内控风险处理——事后风险信息管理查询！'),
                          '0',BJTS_CUR_USER_PHONE_001,CURRENT_TIMESTAMP,'0','Y',ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-%d'), '-04'),BJTS_CUR_USER_SWJG_DM_001,BJTS_CUR_USER_USERNAME_001
;
              COMMIT;
            END IF;
          END;
        END IF;

        IF BJTS_CUR_USER_JJYQ_TSSB_001='Y' THEN
          BEGIN
            SELECT COUNT(1)
              INTO LL_MSZMHX
              FROM MSG_PUSH_DATA S
             WHERE S.SWJG_DM=BJTS_CUR_USER_SWJG_DM_001 AND S.BIZTYPE='免税核销' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP);
            IF LL_MSZMHX>0 THEN
              INSERT INTO MSG_PUSH_PLAN(ID,USERID,CONTENT,SEND_TYPE,SEND_TARG,CRTIME,PLAN_FLAG,QYBZ,PLAN_TAG,SWJG_DM,USERNAME)
                   SELECT SEQ_NEXTVAL('SEQ_MSG_PUSH_PLAN'),BJTS_CUR_USER_ID_001,
                          ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('温馨提醒：[', BJTS_CUR_USER_SWJG_MC_001), ']，您部门扫描到['), LL_FXCK), ']笔企业（出口卷烟/来料加工证明）未免税核销的提醒，请提醒企业及时核销。详情请到便捷退税管理系统的内控管理——内控风险处理——事后风险信息管理查询！'),
                          '0',BJTS_CUR_USER_PHONE_001,CURRENT_TIMESTAMP,'0','Y',ORA_CONCAT(DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-%d'), '-04'),BJTS_CUR_USER_SWJG_DM_001,BJTS_CUR_USER_USERNAME_001
;
              COMMIT;
            END IF;
          END;
        END IF;

      END;
    ELSE
      BEGIN
        IF BJTS_CUR_USER_JOB_TYPE_001 = '3' THEN
          SET LC_SWJGDM =ORA_CONCAT(SUBSTR(BJTS_CUR_USER_SWJG_DM_001, 1, 5), '%');
        ELSE
          SET LC_SWJGDM =ORA_CONCAT(SUBSTR(BJTS_CUR_USER_SWJG_DM_001, 1, 3), '%');
        END IF;
        SELECT COUNT(1)
          INTO LL_TSSB
          FROM MSG_PUSH_DATA S
         WHERE S.SWJG_DM LIKE LC_SWJGDM AND S.BIZTYPE='退税办理' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP)
           AND BJTS_CUR_USER_JJYQ_TSSB_001='Y';
        SELECT COUNT(1)
          INTO LL_FUH
          FROM MSG_PUSH_DATA S
         WHERE S.SWJG_DM LIKE LC_SWJGDM AND S.BIZTYPE='函调复函' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP)
           AND BJTS_CUR_USER_JJYQ_FUH_001='Y';
        SELECT COUNT(1)
          INTO LL_FUHCL
          FROM MSG_PUSH_DATA S
         WHERE S.SWJG_DM LIKE LC_SWJGDM AND S.BIZTYPE='函调处理' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP)
           AND BJTS_CUR_USER_JJYQ_FUHCL_001='Y';
        SELECT COUNT(1)
          INTO LL_SDHC
          FROM MSG_PUSH_DATA S
         WHERE S.SWJG_DM LIKE LC_SWJGDM AND S.BIZTYPE='容缺办理' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP)
           AND BJTS_CUR_USER_JJYQ_SDHC_001='Y';
        SELECT COUNT(1)
          INTO LL_MSZMHX
          FROM MSG_PUSH_DATA S
         WHERE S.SWJG_DM LIKE LC_SWJGDM AND S.BIZTYPE='免税核销' AND S.SJTBSJ>=DATE(CURRENT_TIMESTAMP)
           AND BJTS_CUR_USER_JJYQ_TSSB_001='Y';
        IF (LL_TSSB + LL_FUH + LL_FUHCL + LL_SDHC + LL_MSZMHX) >0 THEN
          SET LC_MSG = ORA_CONCAT(ORA_CONCAT('温馨提醒：[', BJTS_CUR_USER_SWJG_MC_001), ']，下属各局共有');
          IF LL_TSSB > 0 THEN
            SET LC_MSG = ORA_CONCAT(ORA_CONCAT(LC_MSG, LL_TSSB), '笔出口退(免)税业务，');
          END IF;
          IF LL_FUH > 0 THEN
            SET LC_MSG = ORA_CONCAT(ORA_CONCAT(LC_MSG, LL_FUH), '笔函调复函业务，');
          END IF;
          IF LL_FUHCL > 0 THEN
            SET LC_MSG = ORA_CONCAT(ORA_CONCAT(LC_MSG, LL_FUHCL), '笔复函处理业务，');
          END IF;
          IF LL_SDHC > 0 THEN
            SET LC_MSG = ORA_CONCAT(ORA_CONCAT(LC_MSG, LL_SDHC), '笔容缺办理的实地核查业务，');
          END IF;
          IF LL_MSZMHX > 0 THEN
            SET LC_MSG = ORA_CONCAT(ORA_CONCAT(LC_MSG, LL_MSZMHX), '笔企业免税核销提醒，');
          END IF;
          SET LC_MSG = ORA_CONCAT(LC_MSG, '即将超期，请督促办理。谢谢！');
          INSERT INTO MSG_PUSH_PLAN(ID,USERID,CONTENT,SEND_TYPE,SEND_TARG,CRTIME,PLAN_FLAG,QYBZ,PLAN_TAG,SWJG_DM,USERNAME)
               SELECT SEQ_NEXTVAL('SEQ_MSG_PUSH_PLAN'),BJTS_CUR_USER_ID_001,LC_MSG,'0',BJTS_CUR_USER_PHONE_001,
                      CURRENT_TIMESTAMP,'0','Y',DATE_FORMAT(CURRENT_TIMESTAMP, '%Y-%m-%d'),BJTS_CUR_USER_SWJG_DM_001,BJTS_CUR_USER_USERNAME_001
;
          COMMIT;
        END IF;
      END;
    END IF;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  LEAVE routine_body;
END$$

DELIMITER ;
