DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S10108$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S10108
/*
 * 布尔，报告期内是否变更法人代表
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10),
  IN P_BGQ_Q DATETIME,
  IN P_BGQ_Z DATETIME
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT '[d]变更日期=' || DATE_FORMAT(LRRQ, '%Y%m%d') || '|变更前内容=' || BGQNR || '|变更后内容=' || BGHNR
      INTO V_PARAMS
      FROM (SELECT *
              FROM CKTS_DJ_BGDJMX T
             WHERE T.DJXH=P_DJXH AND T.LRRQ>=P_BGQ_Q AND T.LRRQ<P_BGQ_Z+1
               AND T.BGQNR<>T.BGHNR
             ORDER BY T.LRRQ DESC)
     WHERE ROWNUM=1;
     IF V_PARAMS IS NOT NULL THEN
       SET V_ZB_VAL =1;
     ELSE
       SET V_ZB_VAL =0;
     END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = 0;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10108' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10108',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10108';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
