DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W10302$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W10302
/*
 * 出口企业法定代表人是否来自骗税高风险地区
 * ZB_VAL：否0，是1，非身份证的返回0
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_ZJLX       VARCHAR(50);
  DECLARE V_ZJHM       VARCHAR(50);
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
    SELECT FRDB_ZJLX, FRDB_ZJHM, '[d]法定代表人证件号码=' || FRDB_ZJHM
      INTO V_ZJLX, V_ZJHM, V_PARAMS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.DJXH_JS=P_DJXH;

    IF V_ZJLX='201' AND LENGTH(V_ZJHM) IN (15,18) THEN
      SELECT LEAST(COUNT(1),1)
        INTO V_ZB_VAL
        FROM JKGL_GY_FXDQ_SWJG S
       WHERE (S.XZQH_DM=SUBSTR(V_ZJHM,1,6) OR S.XZQH_DM=SUBSTR(V_ZJHM,1,4))
         AND S.QYBZ='Y';
    ELSE
      SET V_ZB_VAL = NULL;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10302' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W10302',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10302';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
