DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W10401$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W10401
/*
 * 企业四员是否来自敏感地区
 * ZB_VAL：存在来自敏感地区的成员，返回1
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_FRDBRZJHM  VARCHAR(100);
  DECLARE V_CWFZRZJHM  VARCHAR(100);
  DECLARE V_BSYZJHM    VARCHAR(100);
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT FRDB_ZJHM, ORA_CONCAT('[d]法定代表人证件号码=', FRDB_ZJHM)
      INTO V_FRDBRZJHM, V_PARAMS
      FROM GLXT_BB_SHXT_DJXX T
     WHERE T.DJXH_JS=P_DJXH;

    SELECT T1.CWFZRSFZJHM
      INTO V_CWFZRZJHM
      FROM GS_DJ_CKTMSDAB T1
     WHERE T1.CPCODE=CAST(P_DJXH AS CHAR);
    SELECT COUNT(1)
      INTO V_ROWS
      FROM JKGL_GY_FXDQ_SWJG S1
     WHERE (S1.XZQH_DM=SUBSTR(V_CWFZRZJHM,1,6) OR S1.XZQH_DM=SUBSTR(V_CWFZRZJHM,1,4))
       AND S1.QYBZ='Y'
       AND LENGTH(V_CWFZRZJHM) IN (15,18);
    SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(V_PARAMS, '|财务负责人证件号码='), V_CWFZRZJHM);
    IF V_ROWS>0 THEN
      SET V_PARAMS = ORA_CONCAT(V_PARAMS, '，是');
    ELSE
      SET V_PARAMS = ORA_CONCAT(V_PARAMS, '，否');
    END IF;

    SELECT T1.BSRSFZJHM
      INTO V_BSYZJHM
      FROM GS_DJ_CKTMSDAB T1
     WHERE T1.CPCODE=CAST(P_DJXH AS CHAR);
    SELECT COUNT(1)
      INTO V_ZB_VAL
      FROM JKGL_GY_FXDQ_SWJG S1
     WHERE (S1.XZQH_DM=SUBSTR(V_BSYZJHM,1,6) OR S1.XZQH_DM=SUBSTR(V_BSYZJHM,1,4))
       AND S1.QYBZ='Y'
       AND LENGTH(V_BSYZJHM) IN (15,18);
    SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(V_PARAMS, '|办税员证件号码='), V_BSYZJHM);
    IF V_ZB_VAL>0 THEN
      SET V_PARAMS = ORA_CONCAT(V_PARAMS, '，是');
    ELSE
      SET V_PARAMS = ORA_CONCAT(V_PARAMS, '，否');
    END IF;

    IF (V_ZB_VAL>0 AND V_FRDBRZJHM<>V_BSYZJHM) OR (V_ROWS>0 AND V_FRDBRZJHM<>V_CWFZRZJHM) THEN
      SET V_ZB_VAL = 1;
    ELSE
      SET V_ZB_VAL =0;
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10401' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W10401',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10401';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
