DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_FXGL_COMPUTE_MAIN$$

CREATE PROCEDURE PRO_FXGL_COMPUTE_MAIN()
/*
 * 态势感知平台——风险管理——日常监管指标
 * 自动扫描主程序
 */
routine_body: BEGIN

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_LSF_SWJG_SWJG_DM_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT SWJG_DM FROM DM_SWJG WHERE TSJG_BZ='1' AND QYBZ='Y' AND YXWS=7 ORDER BY SWJG_DM;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_LSF_SWJG_SWJG_DM_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    CALL PRO_FXGL_COMPUTE_C01001(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);
    CALL PRO_FXGL_COMPUTE_C02001(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);
    CALL PRO_FXGL_COMPUTE_C02002(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);
    CALL PRO_FXGL_COMPUTE_C02003(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);
    CALL PRO_FXGL_COMPUTE_C02004(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);
    CALL PRO_FXGL_COMPUTE_C02005(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);
    CALL PRO_FXGL_COMPUTE_C03001(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);
    CALL PRO_FXGL_COMPUTE_C04001(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);
    CALL PRO_FXGL_COMPUTE_C05001(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);
    CALL PRO_FXGL_COMPUTE_C06001(BJTS_LSF_SWJG_SWJG_DM_001,NULL,NULL);

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

   CALL PRO_FXGL_COMPUTE_C07001('13310000000',NULL,NULL);
   CALL PRO_FXGL_COMPUTE_C07001('13307000000',NULL,NULL);

END$$

DELIMITER ;
