DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DEAL_JCFX_NSR_BADJ$$

CREATE PROCEDURE PRO_DEAL_JCFX_NSR_BADJ()
routine_body: BEGIN
  DECLARE LD_DEALDATA      DATETIME;          -- 用于基础数据处理的提前量

  BEGIN
    UPDATE JCFX_NSR_BADJ AS A
JOIN (
SELECT T.DJXH_JS,T.NSRDJNO,T.SHXYNO,T.NSRMC,T.QYHGDM,T.QYLX,T.FLGLCD,T.DJZCLX_JS,T.HYDM,T.NSRZT_JS,T.NSRLX_JS,T.SQ_DATE,IFNULL(T.ZX_FLAG, 'N') AS ZX_FLAG,T.ZX_DATE,T.SWJGDM,T.ZGSWSKFJ_DM,T.JDXZ_DM
                  FROM GLXT_BB_SHXT_DJXX T
) AS B
ON A.DJXH=B.DJXH_JS
SET NSRSBH = B.NSRDJNO, SHXYDM = B.SHXYNO, NSRMC = B.NSRMC, QYHGDM = B.QYHGDM, CKQYLX = B.QYLX, FLGLCD = B.FLGLCD, DJZCLX = B.DJZCLX_JS, HY = B.HYDM, NSRZT = B.NSRZT_JS, NSRLB = B.NSRLX_JS, SQ_DATE = B.SQ_DATE, BACHBZ = B.ZX_FLAG, BACHSJ = B.ZX_DATE, SWJGDM = B.SWJGDM, KSSWJG_DM = B.ZGSWSKFJ_DM, JDXZ_DM = B.JDXZ_DM;
INSERT INTO JCFX_NSR_BADJ (DJXH,NSRSBH,SHXYDM,NSRMC,QYHGDM,CKQYLX,FLGLCD,DJZCLX,HY,NSRZT,NSRLB,SQ_DATE,BACHBZ,BACHSJ,SWJGDM,KSSWJG_DM,JDXZ_DM)
SELECT B.DJXH_JS,B.NSRDJNO,B.SHXYNO,B.NSRMC,B.QYHGDM,B.QYLX,B.FLGLCD,B.DJZCLX_JS,B.HYDM,B.NSRZT_JS,B.NSRLX_JS,B.SQ_DATE,B.ZX_FLAG,B.ZX_DATE,B.SWJGDM,B.ZGSWSKFJ_DM,B.JDXZ_DM
FROM (
SELECT T.DJXH_JS,T.NSRDJNO,T.SHXYNO,T.NSRMC,T.QYHGDM,T.QYLX,T.FLGLCD,T.DJZCLX_JS,T.HYDM,T.NSRZT_JS,T.NSRLX_JS,T.SQ_DATE,IFNULL(T.ZX_FLAG, 'N') AS ZX_FLAG,T.ZX_DATE,T.SWJGDM,T.ZGSWSKFJ_DM,T.JDXZ_DM
                  FROM GLXT_BB_SHXT_DJXX T
) AS B
WHERE NOT EXISTS (
  SELECT 1 FROM JCFX_NSR_BADJ AS A WHERE A.DJXH=B.DJXH_JS
);
    COMMIT;

    -- QYFZ,NSRDZDAH
  END;

  SELECT ORA_DATE_ADD(MAX(JLXZSJ), -(7)) INTO LD_DEALDATA FROM JCFX_NSR_BADJ_TOHZ;

  BEGIN
    -- 后续增量数据1：新备案出口企业
    INSERT INTO JCFX_NSR_BADJ_TOHZ(DJXH,NSRSBH,SHXYDM,JLXZSJ,BACHSJ,SWJGDM)
         SELECT T.DJXH_JS,T.NSRDJNO,T.SHXYNO,DATE(LEAST(CURRENT_TIMESTAMP,T.SQ_DATE)),T.ZX_DATE,T.SWJGDM
           FROM GLXT_BB_SHXT_DJXX T
          WHERE T.SQ_DATE>=LD_DEALDATA
            AND NOT EXISTS (SELECT 1 FROM JCFX_NSR_BADJ_TOHZ S WHERE S.DJXH=T.DJXH_JS);
    COMMIT;

    -- 后续增量数据2：老备案企业，2019年1月1日以来首次申报出口退免税
    INSERT INTO JCFX_NSR_BADJ_TOHZ(DJXH,NSRSBH,SHXYDM,JLXZSJ,BACHSJ,SWJGDM)
         SELECT T.DJXH_JS,T.NSRDJNO,T.SHXYNO,DATE(CURRENT_TIMESTAMP),T.ZX_DATE,T.SWJGDM
           FROM GLXT_BB_SHXT_DJXX T
          WHERE EXISTS (SELECT 1 FROM CKTS_LC_SBXX S WHERE S.DJXH=T.DJXH_JS AND S.SBRQ>=LD_DEALDATA)
            AND NOT EXISTS (SELECT 1 FROM JCFX_NSR_BADJ_TOHZ S WHERE S.DJXH=T.DJXH_JS);
    COMMIT;

  -- 后续注销企业
    UPDATE JCFX_NSR_BADJ_TOHZ AS T
       SET BACHSJ=(SELECT S.ZX_DATE FROM GLXT_BB_SHXT_DJXX S WHERE S.DJXH_JS=T.DJXH)
     WHERE EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX S WHERE S.DJXH_JS=T.DJXH AND S.ZX_DATE>=LD_DEALDATA);
    COMMIT;
  END;

  LEAVE routine_body;
END$$

DELIMITER ;
