DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S10105$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S10105
/*
 * 财务负责人是否兼职
 * ZB_VAL：财务负责人兼职的企业合计户数
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_ZJHM       VARCHAR(50);
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT T.CWFZRSFZJHM,
           ORA_CONCAT('[d]财务负责人证件号码=', T.CWFZRSFZJHM)
      INTO V_ZJHM, V_PARAMS
      FROM GS_DJ_CKTMSDAB T
     WHERE T.CPCODE=CAST(P_DJXH AS CHAR)
       AND 1=1
LIMIT 1;

    SET V_ZB_VAL = 0;
    BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_SPDM_NSRSBH_001 LONGTEXT;
  DECLARE BJTS_CUR_SPDM_NSRMC_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT DISTINCT T.NSRSBH, T.NSRMC
                       FROM GS_DJ_CKTMSDAB T
                      WHERE T.CWFZRSFZJHM = V_ZJHM
                         OR T.FRZJHM = V_ZJHM;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_SPDM_NSRSBH_001, BJTS_CUR_SPDM_NSRMC_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
      SET V_ZB_VAL = V_ZB_VAL +1;
      IF V_ZB_VAL<=20 THEN
        SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(V_PARAMS, '|财务负责人所在单位税号='), BJTS_CUR_SPDM_NSRSBH_001), '，名称='), BJTS_CUR_SPDM_NSRMC_001);
      END IF;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
    IF V_ZB_VAL>20 THEN
      SET V_PARAMS = ORA_CONCAT(V_PARAMS, '|...');
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10105' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10105',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10105';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
