DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W30502$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W30502
/*
 * 同一口岸货代（申报单位）数量超5个。
 * ZB_VAL：存在大于5个货代（申报单位）的口岸数量
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE VAL1         DECIMAL(18,2);    --参数1
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W30502_GB_KA_SL';

    SET V_ZB_VAL = 0;
    FOR CUR_SPDM IN (SELECT T.KA_DM,DM.CKKA_MC,T.SBDWSL
                       FROM JKGL_DATA_TJ_ZBU_CKKA T
                       LEFT JOIN JCFX_DM_CKKA DM ON DM.CKKA_DM=T.KA_DM
                      WHERE T.BGQID=P_BGQID
                        AND T.SBDWSL>VAL1)
    LOOP
      SET V_ZB_VAL = V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        SET V_PARAMS = '[d]口岸代码=' || CUR_SPDM.KA_DM || '（' || CUR_SPDM.CKKA_MC ||'），申报单位数量=' || CUR_SPDM.SBDWSL;
      ELSEIF V_ZB_VAL<=20 THEN
        SET V_PARAMS = V_PARAMS || '|口岸代码=' || CUR_SPDM.KA_DM || '（' || CUR_SPDM.CKKA_MC ||'），申报单位数量=' || CUR_SPDM.SBDWSL;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      SET V_PARAMS = V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30502' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W30502',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30502';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
