DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DEAL_JCFX_NSR_BLV$$

CREATE PROCEDURE PRO_DEAL_JCFX_NSR_BLV()
routine_body: BEGIN
  DECLARE LN_CKBGDFS       BIGINT;
  DECLARE LN_CKMYLAJ       DECIMAL(18,2);
  DECLARE LN_SBMYLAJ       DECIMAL(18,2);
  DECLARE LN_SBTMSE         DECIMAL(18,2);
  DECLARE LN_SBMDE         DECIMAL(18,2);
  DECLARE LC_CKGM          VARCHAR(1);
  DECLARE LN_MDBLV         DECIMAL(10,6);
  DECLARE LC_MDBLV         VARCHAR(1);

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_NSR_DJXH_JS_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.DJXH_JS FROM GLXT_BB_SHXT_DJXX T;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_NSR_DJXH_JS_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    SELECT COUNT(DISTINCT SUBSTR(S.CKBGDH,1,18)), IFNULL(SUM(S.MYLAJ), 0)
      INTO LN_CKBGDFS, LN_CKMYLAJ
      FROM CKTS_WBSJ_HG_BGD S
     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_JS_001
       AND S.CKRQ_1>=DATE_ADD(MAKEDATE(YEAR(CURRENT_TIMESTAMP), 1), INTERVAL -12 MONTH)
       AND S.CKRQ_1< MAKEDATE(YEAR(CURRENT_TIMESTAMP), 1);

    SELECT IFNULL(SUM(S.USD_AMT), 0), IFNULL(SUM(S.SB_TS_AMT), 0)+ IFNULL(SUM(S.SB_MD_AMT), 0), IFNULL(SUM(S.SB_MD_AMT), 0)
      INTO LN_SBMYLAJ, LN_SBTMSE, LN_SBMDE
      FROM GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_JS_001
       AND IFNULL(S.SL_DATE, S.SB_DATE)>=DATE_ADD(MAKEDATE(YEAR(CURRENT_TIMESTAMP), 1), INTERVAL -12 MONTH)
       AND IFNULL(S.SL_DATE, S.SB_DATE)< MAKEDATE(YEAR(CURRENT_TIMESTAMP), 1);

    SET LC_CKGM = CASE WHEN LN_SBMYLAJ>=100000000 THEN 'A'
                    WHEN LN_SBMYLAJ>=50000000 THEN 'B'
                    WHEN LN_SBMYLAJ>=10000000 THEN 'C'
                    WHEN LN_SBMYLAJ>=1000000 THEN 'D'
                    ELSE 'E' END;

    IF LN_SBMDE<=0 THEN
      SET LN_MDBLV = 0;
    ELSEIF LN_SBTMSE<0 THEN
      SET LN_MDBLV = 100;
    ELSE
      SET LN_MDBLV = 100 * LN_SBMDE / LN_SBTMSE;
    END IF;
    SET LC_MDBLV = CASE WHEN LN_MDBLV>=40 THEN 'A'
                     WHEN LN_MDBLV>=30 THEN 'B'
                     WHEN LN_MDBLV>=20 THEN 'C'
                     WHEN LN_MDBLV>=10 THEN 'D'
                     ELSE 'E' END;

    UPDATE GLXT_BB_SHXT_DJXX AS A
       SET CK_BGDFS = LN_CKBGDFS,
    CK_MYLAJ = LN_CKMYLAJ,
    CKGM     = LN_SBMYLAJ,
    SB_TMSE  = LN_SBTMSE,
    SB_MDE   = LN_SBMDE,
    MDBLV    = LN_MDBLV,
    CKGM_DM  = LC_CKGM,
    MDBLV_DM = LC_MDBLV
     WHERE A.DJXH_JS=BJTS_CUR_NSR_DJXH_JS_001;
    COMMIT;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  LEAVE routine_body;
END$$

DELIMITER ;
