DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S50101$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S50101
/*
 * (增值税_免抵销售+增值税_免税销售)/增值税_全部销售
 */
(
  IN P_BGQID DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DAT2  DECIMAL(18,2);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT S.ZZS_XSE_QB, S.ZZS_XSE_MDT, S.ZZS_XSE_MS
      INTO V_THIS_DATA, V_LAST_DATA, V_LAST_DAT2
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;

    SET V_PARAMS = '[d]报告期增值税全部销售=' || V_THIS_DATA || '|报告期免抵销售=' || V_LAST_DATA || '|报告期免税销售=' || V_LAST_DAT2;
    SET V_LAST_DATA = V_LAST_DATA + V_LAST_DAT2;
    IF V_THIS_DATA <=1 THEN
      SET V_ZB_VAL = NULL;
    ELSE
      SET V_ZB_VAL = ROUND(100 * V_LAST_DATA / V_THIS_DATA, 2);
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S50101' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S50101',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S50101';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
