DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_DEAL_JCFX_NSR_BADJ_BLV$$

CREATE PROCEDURE PRO_DEAL_JCFX_NSR_BADJ_BLV
(
  IN V_YEAR VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LN_QBXSE         DECIMAL(18,2);
  DECLARE LN_CKXSE         DECIMAL(18,2);
  DECLARE LN_CKGM          DECIMAL(18,2);
  DECLARE LN_SBMDE         DECIMAL(18,2);
  DECLARE LN_SBMDTSE       DECIMAL(18,2);
  DECLARE LN_SBSF          DECIMAL(18,2);
  DECLARE LN_CKBLV         DECIMAL(10,6);
  DECLARE LN_MDBLV         DECIMAL(10,6);
  DECLARE LN_SFBLV         DECIMAL(10,6);
  DECLARE LC_CKBLV         VARCHAR(1);
  DECLARE LC_CKGM          VARCHAR(1);
  DECLARE LC_MDBLV         VARCHAR(1);
  DECLARE LC_SFBLV         VARCHAR(1);

  IF V_YEAR IS NULL THEN
    LEAVE routine_body;
  END IF;

  -- 根据审核信息设置LCTJJC
  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_NSR_DJXH_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.DJXH
                    FROM JCFX_NSR_BADJ T;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_NSR_DJXH_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    SELECT IFNULL(SUM(S.ZZS_QBXSSR), 0), IFNULL(SUM(S.CK_SB_XSERMB), 0), IFNULL(SUM(S.CK_SB_XSEMY), 0), IFNULL(SUM(S.CK_SB_MDE), 0), IFNULL(SUM(S.CK_SB_TSE+S.CK_SB_MDE), 0), IFNULL(SUM(S.ZZS_YNSE+S.CK_SB_MDE), 0)
      INTO LN_QBXSE, LN_CKXSE, LN_CKGM, LN_SBMDE, LN_SBMDTSE, LN_SBSF
      FROM JCFX_DATA_QYYHZ S
     WHERE S.DJXH=BJTS_CUR_NSR_DJXH_001 AND S.NY LIKE ORA_CONCAT(V_YEAR, '%');

    IF LN_QBXSE<=0 THEN
      IF LN_CKXSE<=0 THEN
        SET LN_CKBLV = 0;
      ELSE
        SET LN_CKBLV = 100;
      END IF;
    ELSE
      -- LN_QBXSE>0
      IF LN_CKXSE> LN_QBXSE THEN
        SET LN_CKBLV = 100;
      ELSEIF LN_CKXSE<0 THEN
        SET LN_CKBLV = 0;
      ELSE
        SET LN_CKBLV = 100 * LN_CKXSE / LN_QBXSE;
      END IF;
    END IF;

    IF LN_SBMDTSE<=0 OR LN_SBMDE<=0 THEN
      SET LN_MDBLV = 0;
    ELSEIF LN_SBMDE>LN_SBMDTSE THEN
      SET LN_MDBLV = 100;
    ELSE
      SET LN_MDBLV = 100 * LN_SBMDE / LN_SBMDTSE;
    END IF;

    IF LN_QBXSE<=0 OR LN_SBSF<=0 THEN
      SET LN_SFBLV = 0;
    ELSEIF LN_SBSF>LN_QBXSE THEN
      SET LN_SFBLV = 100;
    ELSE
      SET LN_SFBLV = 100 * LN_SBSF / LN_QBXSE;
    END IF;


    SET LC_CKBLV = CASE WHEN LN_CKBLV>=80 THEN 'A' WHEN LN_CKBLV>=60 THEN 'B' WHEN LN_CKBLV>=40 THEN 'C' WHEN LN_CKBLV>=20 THEN 'D' ELSE 'E' END;
    SET LC_CKGM = CASE WHEN LN_CKGM>=100000000 THEN 'A' WHEN LN_CKGM>=50000000 THEN 'B' WHEN LN_CKGM>=10000000 THEN 'C' WHEN LN_CKGM>=1000000 THEN 'D' ELSE 'E' END;
    SET LC_MDBLV = CASE WHEN LN_MDBLV>=40 THEN 'A' WHEN LN_MDBLV>=30 THEN 'B' WHEN LN_MDBLV>=20 THEN 'C' WHEN LN_MDBLV>=10 THEN 'D' ELSE 'E' END;
    SET LC_SFBLV = CASE WHEN LN_SFBLV>=20 THEN 'A' WHEN LN_SFBLV>=15 THEN 'B' WHEN LN_SFBLV>=10 THEN 'C' WHEN LN_SFBLV>=5 THEN 'D' ELSE 'E' END;

    UPDATE JCFX_NSR_BADJ AS A
       SET CKBLV=LN_CKBLV,
    CKBLV_DM=LC_CKBLV,
    CKGM=LN_CKGM,
    CKGM_DM=LC_CKGM,
    MDBLV=LN_MDBLV,
    MDBLV_DM=LC_MDBLV,
    SFLV=LN_SFBLV,
    SFLV_DM=LC_SFBLV
     WHERE A.DJXH=BJTS_CUR_NSR_DJXH_001;
    COMMIT;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  LEAVE routine_body;
END$$

DELIMITER ;
