DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_JKM_MAIN$$

CREATE PROCEDURE PRO_JKGL_JKM_MAIN(
  IN P_DJXH VARCHAR(4000),
  IN P_SWJG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE V_COUNT BIGINT;
  DECLARE V_DJXH VARCHAR(20);


  SET V_COUNT =0;
  DO ORA_CONCAT('【健康码】刷新开始，时间:', DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m%d %H:%i:%s'));

  -- 开始循环
  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      DO ORA_CONCAT(ORA_CONCAT('【健康码】刷新异常:', BJTS_SQLCODE_001), BJTS_SQLERRM_001);
      DO ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('【异常企业】-', V_COUNT), '-'), V_DJXH);
      LEAVE routine_body;

  END;
BEGIN
  DECLARE BJTS_NAMED_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_CPCODE_001 LONGTEXT;
  DECLARE BJTS_CUR_TSJSFS_001 LONGTEXT;
  DECLARE BJTS_CUR_SWJGDM_001 LONGTEXT;
  DECLARE BJTS_NAMED_CURSOR_001 CURSOR FOR
SELECT DJ.CPCODE, (CASE DJ.JSMODE WHEN '1' THEN '1' ELSE '2' END) AS TSJSFS, DJ.SWJGDM
        FROM JKGL_DATA_QYJKM_JGB T
       INNER JOIN GLXT_BB_SHXT_DJXX DJ ON DJ.CPCODE=T.DJXH
       WHERE ((P_DJXH) IS NULL OR T.DJXH=(P_DJXH))
         AND ((P_SWJG) IS NULL OR DJ.SWJGDM=(P_SWJG))
         AND EXISTS (SELECT 1
                       FROM JKGL_DATA_ZB_JGB Z
                      WHERE T.DJXH=Z.DJXH AND Z.ZB_ID IN ('W10101','S10101'));
  OPEN BJTS_NAMED_CURSOR_001;
  BJTS_NAMED_CURSOR_LOOP_001: LOOP
    SET BJTS_NAMED_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_NAMED_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_NAMED_CURSOR_001 INTO BJTS_CUR_CPCODE_001, BJTS_CUR_TSJSFS_001, BJTS_CUR_SWJGDM_001;
    END;
    IF BJTS_NAMED_CURSOR_DONE_001 THEN
      LEAVE BJTS_NAMED_CURSOR_LOOP_001;
    END IF;
      SET V_COUNT =V_COUNT+1;
      SET V_DJXH = BJTS_CUR_CPCODE_001;

      -- 对指标进行异常判定和赋分
      CALL PRO_JKGL_JKM_ZB_YCFF(V_DJXH,BJTS_CUR_TSJSFS_001,BJTS_CUR_SWJGDM_001);

      -- 对指标进行异常判定和赋分
      CALL PRO_JKGL_JKM_COMPUTE(V_DJXH,BJTS_CUR_TSJSFS_001,BJTS_CUR_SWJGDM_001);



  END LOOP BJTS_NAMED_CURSOR_LOOP_001;
  CLOSE BJTS_NAMED_CURSOR_001;
END;
  END;

  DO ORA_CONCAT('【健康码】刷新结束，时间:', DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m%d %H:%i:%s'));
  DO ORA_CONCAT('【健康码】刷新户数=', V_COUNT);

  LEAVE routine_body;
END$$

DELIMITER ;
