DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S30104$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S30104
/*
 * 首笔出口未满一年企业,出口额达100万美元且环比增幅超50%。
 * ZB_VAL：出口额大于等于100W，返回报告期增幅，否则坏点
 */
(
  IN P_BGQID DECIMAL(38,10),
  IN P_JDBGQID DECIMAL(38,10),
  IN P_JDJQID DECIMAL(38,10),
  IN P_DJXH DECIMAL(38,10),
  IN P_BGQ_Z DATETIME,
  IN P_SWJGDM VARCHAR
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_SCCKYF     DECIMAL(18,2);
  DECLARE VAL1         DECIMAL(18,2);    -- 参数1
  DECLARE VAL2         DECIMAL(18,2);    -- 参数2
  DECLARE V_PARAMS     VARCHAR(1000);

  BEGIN
  DECLARE BJTS_SQLCODE_001 INT DEFAULT 0;
  DECLARE BJTS_SQLERRM_001 TEXT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 BJTS_SQLCODE_001 = MYSQL_ERRNO, BJTS_SQLERRM_001 = MESSAGE_TEXT;
      SET V_ZB_VAL = NULL;

  END;
SELECT TIMESTAMPDIFF(MONTH, IFNULL(A.SCCKRQ, CURRENT_TIMESTAMP), P_BGQ_Z)
      INTO V_SCCKYF
      FROM GS_DJ_CKTMSDAB A
     WHERE A.CPCODE=CAST(P_DJXH AS CHAR)
       AND 1=1
LIMIT 1;
    IF V_SCCKYF>=12 THEN
      SET V_ZB_VAL = NULL;
    ELSE
      SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
        INTO VAL1
        FROM JKGL_PZ_ZB_CS T
        LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
       WHERE T.CSBM='ZC_S30104_CKWMYN_CKE_HB';
      SELECT IFNULL(S.VAL_DEF, T.VAL_DEF) / (CASE T.CSTYPE WHEN '百分比' THEN 100 ELSE 1 END)
        INTO VAL2
        FROM JKGL_PZ_ZB_CS T
        LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
       WHERE T.CSBM='ZC_S30104_CKWMYN_CKE_JE';

      SELECT S.CK_CKEUSD
        INTO V_THIS_DATA
        FROM JKGL_DATA_TJ_ZBU S
       WHERE S.BGQID=P_JDBGQID;
      SELECT S.CK_CKEUSD
        INTO V_LAST_DATA
        FROM JKGL_DATA_TJ_ZBU S
       WHERE S.BGQID=P_JDJQID;

      SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT('[d]季度报告期出口销售额=', V_THIS_DATA), '|季度基期出口销售额='), V_LAST_DATA);
      IF V_LAST_DATA>0 THEN
        IF V_THIS_DATA>=VAL2 AND V_THIS_DATA>=V_LAST_DATA * VAL1 THEN
          SET V_ZB_VAL = 1;
        ELSE
          SET V_ZB_VAL = 0;
        END IF;
        SET V_PARAMS = ORA_CONCAT(ORA_CONCAT(ORA_CONCAT(V_PARAMS, '|季度环比='), ROUND(100 * V_THIS_DATA / V_LAST_DATA,2)), '%');
      ELSE
        SET V_ZB_VAL = NULL;
      END IF;
    END IF;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT LEAST(COUNT(1), 1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30104' AND 1=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30104',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB AS T
       SET ZB_VAL=V_ZB_VAL,
    BADPOINT=V_BADPOINT,
    PARAMS=V_PARAMS,
    UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30104';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
