DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_S50201$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_S50201
/*
 * (资产_期末存货-资产_期末存货[基期])/资产_期末存货[基期]
 */
(
  IN P_BGQID DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT S.ZC_CH_QC, S.ZC_CH_QM
      INTO V_THIS_DATA, V_LAST_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;

    SET V_PARAMS = '[d]期初存货=' || V_THIS_DATA || '|期末存货=' || V_LAST_DATA;
    IF V_THIS_DATA <=1 THEN
      SET V_ZB_VAL = NULL;
    ELSE
      SET V_ZB_VAL = ROUND(100 * (V_LAST_DATA - V_THIS_DATA) / V_THIS_DATA, 2);
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S50201' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S50201',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S50201';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
