DELIMITER $$

DROP PROCEDURE IF EXISTS PRO_JKGL_COMPUTE_W50301$$

CREATE PROCEDURE PRO_JKGL_COMPUTE_W50301
/*
 * 应收账款周转率
 * ZB_VAL：100% * 营业收入 / [(期初应收+期末应收）/2]
 */
(
  IN P_BGQID DECIMAL(38,10)
)
routine_body: BEGIN
  DECLARE V_ZB_VAL     DECIMAL(18,2);
  DECLARE V_ROWS       BIGINT;
  DECLARE V_BADPOINT   CHAR(1);
  DECLARE V_THIS_DATA  DECIMAL(18,2);
  DECLARE V_LAST_DATA  DECIMAL(18,2);
  DECLARE V_PARAMS     VARCHAR(4000);

  BEGIN
    SELECT T.LR_YYSR, (T.ZC_YSZK_QC + T.ZC_YSZK_QM) / 2,
           '[d]营业收入=' ||T.LR_YYSR || '|期初应收=' || T.ZC_YSZK_QC || '|期末应收=' || T.ZC_YSZK_QM
      INTO V_THIS_DATA, V_LAST_DATA, V_PARAMS
      FROM JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    SET V_ZB_VAL = ROUND(100 * V_THIS_DATA / V_LAST_DATA, 2);
  EXCEPTION
    WHEN OTHERS THEN
      SET V_ZB_VAL = NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SET V_BADPOINT = 'Y';
  ELSE
    SET V_BADPOINT = 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50301' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W50301',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=CURRENT_TIMESTAMP
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50301';
  END IF;
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
