DELIMITER $$

DROP PROCEDURE IF EXISTS TEMP_PRO_DEAL_LCTJJC$$

CREATE PROCEDURE TEMP_PRO_DEAL_LCTJJC()
routine_body: BEGIN

  -- 免抵退业务审核信息1
  BEGIN
  DECLARE BJTS_CURSOR_DONE_004 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_SHXX_UUID_004 LONGTEXT;
  DECLARE BJTS_CUR_SHXX_LCSLID_FS_004 LONGTEXT;
  DECLARE BJTS_CURSOR_004 CURSOR FOR
SELECT T.UUID,T.LCSLID_FS
                     FROM CKTS_LC_SHXX T
                    WHERE T.LCTJJC IN ('23','22','21','20','10','00')
                      AND EXISTS (
                          SELECT 1
                            FROM CKTS_LC_YWHZXX S
                           WHERE S.LCSLID_FS=T.LCSLID_FS AND S.CKTMSHWYSFWLX_DM='2')
                      AND NOT EXISTS (
                          SELECT 1
                            FROM CKTS_LC_SHXX R
                           WHERE R.LCSLID_FS=T.LCSLID_FS AND R.LCTJJC IN ('63','62','61','53','52','51','50','43','42','41','40'));
  OPEN BJTS_CURSOR_004;
  BJTS_CURSOR_LOOP_004: LOOP
    SET BJTS_CURSOR_DONE_004 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_004 = TRUE;
      FETCH BJTS_CURSOR_004 INTO BJTS_CUR_SHXX_UUID_004, BJTS_CUR_SHXX_LCSLID_FS_004;
    END;
    IF BJTS_CURSOR_DONE_004 THEN
      LEAVE BJTS_CURSOR_LOOP_004;
    END IF;
    BEGIN
      -- LCTJJC
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='00'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004;
      COMMIT;
      -- 35号公告代办退税
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='72'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'72' AND T.SBYWB_DM='A0310001';
      COMMIT;
      -- 17号公告代办退税
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='71'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'71' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MTS_CKMX A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.CKTMSYWLXDMJH LIKE 'WMZHFW%');
      COMMIT;
      -- 综服企业自营业务
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='70'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'70' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND A.BAJC_YEAR LIKE '7%');
      COMMIT;
      -- 国际运输业务
      -- 外商投资企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='63'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'63' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_GJYS A WHERE A.LCSLID_SB=T.LCSLID_SB)
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND SUBSTR(A.DJZCLX_JS,0,1) IN ('2','3'));
      COMMIT;
      -- 委托出口企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='62'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'62' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_GJYS A WHERE A.LCSLID_SB=T.LCSLID_SB)
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND LENGTH(A.QYHGDM)=10 AND A.QYHGDM LIKE '9%');
      COMMIT;
      -- 内资生产企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='61'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'61' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_GJYS A WHERE A.LCSLID_SB=T.LCSLID_SB);
      COMMIT;
      -- 研发设计业务
      -- 外商投资企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='53'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'53' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.YSFW_DM IN ('9902000000','9903000000'))
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND SUBSTR(A.DJZCLX_JS,0,1) IN ('2','3'));
      COMMIT;
      -- 委托出口企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='52'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'52' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.YSFW_DM IN ('9902000000','9903000000'))
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND LENGTH(A.QYHGDM)=10 AND A.QYHGDM LIKE '9%');
      COMMIT;
      -- 内资生产企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='51'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'51' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.YSFW_DM IN ('9902000000','9903000000'));
      COMMIT;
      -- 其他服务贸易
      -- 外商投资企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='43'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'43' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB)
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND SUBSTR(A.DJZCLX_JS,0,1) IN ('2','3'));
      COMMIT;
      -- 委托出口企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='42'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'42' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB)
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND LENGTH(A.QYHGDM)=10 AND A.QYHGDM LIKE '9%');
      COMMIT;
      -- 内资生产企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='41'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'41' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB);
      COMMIT;
      -- 外贸服务贸易
      -- 研发设计业务
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='50'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'50' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MTS_YSFW A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.YSFW_DM IN ('9902000000','9903000000'));
      COMMIT;
      -- 其他服务贸易
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='40'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'40' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MTS_YSFW A WHERE A.LCSLID_SB=T.LCSLID_SB);
      COMMIT;
      -- 周边业务
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='30'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'30' AND T.SBYWB_DM IN ('A0302001','A0303001','A0304001');
      COMMIT;
      -- 外商投资企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='23'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'23' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND SUBSTR(A.DJZCLX_JS,0,1) IN ('2','3'));
      COMMIT;
      -- 委托出口企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='22'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'22' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND LENGTH(A.QYHGDM)=10 AND A.QYHGDM LIKE '9%');
      COMMIT;
      -- 内资生产企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='21'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'21' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' ';
      COMMIT;
      -- 外贸企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='10'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_004 AND T.LCTJJC<'10' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' ';
      COMMIT;

      BEGIN
  DECLARE BJTS_CURSOR_DONE_003 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_HZXX_YWHZBUUID_003 LONGTEXT;
  DECLARE BJTS_CUR_HZXX_CKTMSHWYSFWLX_DM_003 LONGTEXT;
  DECLARE BJTS_CUR_HZXX_LCTJJC_003 LONGTEXT;
  DECLARE BJTS_CURSOR_003 CURSOR FOR
SELECT T.YWHZBUUID,T.CKTMSHWYSFWLX_DM,MAX(S.LCTJJC) AS LCTJJC
                         FROM CKTS_LC_YWHZXX T
                        INNER JOIN CKTS_LC_SHXX S ON S.LCSLID_FS=T.LCSLID_FS
                        WHERE T.LCSLID_FS=BJTS_CUR_SHXX_LCSLID_FS_004
                        GROUP BY T.YWHZBUUID,T.CKTMSHWYSFWLX_DM;
  OPEN BJTS_CURSOR_003;
  BJTS_CURSOR_LOOP_003: LOOP
    SET BJTS_CURSOR_DONE_003 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_003 = TRUE;
      FETCH BJTS_CURSOR_003 INTO BJTS_CUR_HZXX_YWHZBUUID_003, BJTS_CUR_HZXX_CKTMSHWYSFWLX_DM_003, BJTS_CUR_HZXX_LCTJJC_003;
    END;
    IF BJTS_CURSOR_DONE_003 THEN
      LEAVE BJTS_CURSOR_LOOP_003;
    END IF;
        UPDATE CKTS_LC_YWHZXX AS A
           SET LCTJJC=(CASE WHEN (BJTS_CUR_HZXX_LCTJJC_003 IN ('72','71','70','30','23','22','21','10')) OR (BJTS_CUR_HZXX_CKTMSHWYSFWLX_DM_003='2') THEN BJTS_CUR_HZXX_LCTJJC_003
                              ELSE (CASE WHEN BJTS_CUR_HZXX_LCTJJC_003 IN ('63','53','43') THEN '23'
                                         WHEN BJTS_CUR_HZXX_LCTJJC_003 IN ('62','52','42') THEN '22'
                                         WHEN BJTS_CUR_HZXX_LCTJJC_003 IN ('61','51','41') THEN '21'
                                         WHEN BJTS_CUR_HZXX_LCTJJC_003 IN ('50','40') THEN '10'
                                         ELSE '00'
                                   END)
                        END)
         WHERE A.YWHZBUUID=BJTS_CUR_HZXX_YWHZBUUID_003;
        COMMIT;
        UPDATE CKTS_LC_SEHZXX AS B
           SET LCTJJC =(SELECT A.LCTJJC FROM CKTS_LC_YWHZXX A WHERE A.YWHZBUUID=B.YWHZBUUID AND 1=1
LIMIT 1)
         WHERE B.YWHZBUUID=BJTS_CUR_HZXX_YWHZBUUID_003;
        COMMIT;

  END LOOP BJTS_CURSOR_LOOP_003;
  CLOSE BJTS_CURSOR_003;
END;
    END;

  END LOOP BJTS_CURSOR_LOOP_004;
  CLOSE BJTS_CURSOR_004;
END;

  -- 免抵退业务审核信息1
  BEGIN
  DECLARE BJTS_CURSOR_DONE_002 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_SHXX_UUID_002 LONGTEXT;
  DECLARE BJTS_CUR_SHXX_LCSLID_FS_002 LONGTEXT;
  DECLARE BJTS_CURSOR_002 CURSOR FOR
SELECT T.UUID,T.LCSLID_FS
                     FROM CKTS_LC_SHXX T
                    WHERE T.LCTJJC IN ('23','22','21','20','10','00')
                      AND T.DJXH IN (
                          SELECT A.DJXH
                            FROM CKTS_LC_SHXX A
                           WHERE A.LCTJJC IN ('21','22','23') AND A.LCJSRQ>=CAST('2026-01-01' AS DATE)
                            GROUP BY A.DJXH HAVING COUNT(DISTINCT A.LCTJJC)>1);
  OPEN BJTS_CURSOR_002;
  BJTS_CURSOR_LOOP_002: LOOP
    SET BJTS_CURSOR_DONE_002 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_002 = TRUE;
      FETCH BJTS_CURSOR_002 INTO BJTS_CUR_SHXX_UUID_002, BJTS_CUR_SHXX_LCSLID_FS_002;
    END;
    IF BJTS_CURSOR_DONE_002 THEN
      LEAVE BJTS_CURSOR_LOOP_002;
    END IF;
    BEGIN
      -- LCTJJC
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='00'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002;
      COMMIT;
      -- 35号公告代办退税
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='72'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'72' AND T.SBYWB_DM='A0310001';
      COMMIT;
      -- 17号公告代办退税
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='71'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'71' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MTS_CKMX A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.CKTMSYWLXDMJH LIKE 'WMZHFW%');
      COMMIT;
      -- 综服企业自营业务
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='70'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'70' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND A.BAJC_YEAR LIKE '7%');
      COMMIT;
      -- 国际运输业务
      -- 外商投资企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='63'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'63' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_GJYS A WHERE A.LCSLID_SB=T.LCSLID_SB)
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND SUBSTR(A.DJZCLX_JS,0,1) IN ('2','3'));
      COMMIT;
      -- 委托出口企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='62'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'62' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_GJYS A WHERE A.LCSLID_SB=T.LCSLID_SB)
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND LENGTH(A.QYHGDM)=10 AND A.QYHGDM LIKE '9%');
      COMMIT;
      -- 内资生产企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='61'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'61' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_GJYS A WHERE A.LCSLID_SB=T.LCSLID_SB);
      COMMIT;
      -- 研发设计业务
      -- 外商投资企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='53'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'53' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.YSFW_DM IN ('9902000000','9903000000'))
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND SUBSTR(A.DJZCLX_JS,0,1) IN ('2','3'));
      COMMIT;
      -- 委托出口企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='52'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'52' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.YSFW_DM IN ('9902000000','9903000000'))
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND LENGTH(A.QYHGDM)=10 AND A.QYHGDM LIKE '9%');
      COMMIT;
      -- 内资生产企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='51'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'51' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.YSFW_DM IN ('9902000000','9903000000'));
      COMMIT;
      -- 其他服务贸易
      -- 外商投资企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='43'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'43' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB)
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND SUBSTR(A.DJZCLX_JS,0,1) IN ('2','3'));
      COMMIT;
      -- 委托出口企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='42'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'42' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB)
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND LENGTH(A.QYHGDM)=10 AND A.QYHGDM LIKE '9%');
      COMMIT;
      -- 内资生产企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='41'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'41' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MDT_YFSJ A WHERE A.LCSLID_SB=T.LCSLID_SB);
      COMMIT;
      -- 外贸服务贸易
      -- 研发设计业务
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='50'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'50' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MTS_YSFW A WHERE A.LCSLID_SB=T.LCSLID_SB AND A.YSFW_DM IN ('9902000000','9903000000'));
      COMMIT;
      -- 其他服务贸易
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='40'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'40' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM CKTS_SB_MTS_YSFW A WHERE A.LCSLID_SB=T.LCSLID_SB);
      COMMIT;
      -- 周边业务
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='30'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'30' AND T.SBYWB_DM IN ('A0302001','A0303001','A0304001');
      COMMIT;
      -- 外商投资企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='23'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'23' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND SUBSTR(A.DJZCLX_JS,0,1) IN ('2','3'));
      COMMIT;
      -- 委托出口企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='22'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'22' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' '
         AND EXISTS (SELECT 1 FROM GLXT_BB_SHXT_DJXX A WHERE A.DJXH_JS=T.DJXH AND LENGTH(A.QYHGDM)=10 AND A.QYHGDM LIKE '9%');
      COMMIT;
      -- 内资生产企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='21'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'21' AND T.SBYWB_DM='A0305001' AND T.LCSLID_SB<>' ';
      COMMIT;
      -- 外贸企业
      UPDATE CKTS_LC_SHXX AS T
         SET LCTJJC='10'
       WHERE T.UUID=BJTS_CUR_SHXX_UUID_002 AND T.LCTJJC<'10' AND T.SBYWB_DM='A0301001' AND T.LCSLID_SB<>' ';
      COMMIT;

      BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_HZXX_YWHZBUUID_001 LONGTEXT;
  DECLARE BJTS_CUR_HZXX_CKTMSHWYSFWLX_DM_001 LONGTEXT;
  DECLARE BJTS_CUR_HZXX_LCTJJC_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.YWHZBUUID,T.CKTMSHWYSFWLX_DM,MAX(S.LCTJJC) AS LCTJJC
                         FROM CKTS_LC_YWHZXX T
                        INNER JOIN CKTS_LC_SHXX S ON S.LCSLID_FS=T.LCSLID_FS
                        WHERE T.LCSLID_FS=BJTS_CUR_SHXX_LCSLID_FS_002
                        GROUP BY T.YWHZBUUID,T.CKTMSHWYSFWLX_DM;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_HZXX_YWHZBUUID_001, BJTS_CUR_HZXX_CKTMSHWYSFWLX_DM_001, BJTS_CUR_HZXX_LCTJJC_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
        UPDATE CKTS_LC_YWHZXX AS A
           SET LCTJJC=(CASE WHEN (BJTS_CUR_HZXX_LCTJJC_001 IN ('72','71','70','30','23','22','21','10')) OR (BJTS_CUR_HZXX_CKTMSHWYSFWLX_DM_001='2') THEN BJTS_CUR_HZXX_LCTJJC_001
                              ELSE (CASE WHEN BJTS_CUR_HZXX_LCTJJC_001 IN ('63','53','43') THEN '23'
                                         WHEN BJTS_CUR_HZXX_LCTJJC_001 IN ('62','52','42') THEN '22'
                                         WHEN BJTS_CUR_HZXX_LCTJJC_001 IN ('61','51','41') THEN '21'
                                         WHEN BJTS_CUR_HZXX_LCTJJC_001 IN ('50','40') THEN '10'
                                         ELSE '00'
                                   END)
                        END)
         WHERE A.YWHZBUUID=BJTS_CUR_HZXX_YWHZBUUID_001;
        COMMIT;
        UPDATE CKTS_LC_SEHZXX AS B
           SET LCTJJC =(SELECT A.LCTJJC FROM CKTS_LC_YWHZXX A WHERE A.YWHZBUUID=B.YWHZBUUID AND 1=1
LIMIT 1)
         WHERE B.YWHZBUUID=BJTS_CUR_HZXX_YWHZBUUID_001;
        COMMIT;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;
    END;

  END LOOP BJTS_CURSOR_LOOP_002;
  CLOSE BJTS_CURSOR_002;
END;
  LEAVE routine_body;
END$$

DELIMITER ;
