DELIMITER $$

DROP PROCEDURE IF EXISTS TEMP_PRO_JKGL_COMPUTE_ZBANDJKM$$

CREATE PROCEDURE TEMP_PRO_JKGL_COMPUTE_ZBANDJKM()
routine_body: BEGIN

  INSERT INTO JKGL_LOG_DEALDATA(CZJL) VALUES ('TEMP_PRO_JKGL_COMPUTE_ZBANDJKM开始处理！');
  COMMIT;
/*
  INSERT INTO JKGL_DATA_QYJKM_LSB(ID,DJXH,JKM_LEVEL,SCORE_10,SCORE_20,SCORE_30,SCORE_40,SCORE_50,SCORE_60,SCORE_ZH,
              UPTIME,TSJSFS_DM,NOTE,RGFM_LEVEL,RGFMSJ,FMYXQ,CZYDM,CZYMC,RGBZMS)
       SELECT SEQ_JKGL_DATA_QYJKM_LSB.NEXTVAL,DJXH,JKM_LEVEL,SCORE_10,SCORE_20,SCORE_30,SCORE_40,SCORE_50,SCORE_60,SCORE_ZH,
              T.UPTIME,T.TSJSFS_DM,'2024',T.RGFM_LEVEL,T.RGFMSJ,T.FMYXQ,T.CZYDM,T.CZYMC,T.RGBZMS
         FROM JKGL_DATA_QYJKM_JGB T;
  COMMIT;
  INSERT INTO JKGL_LOG_DEALDATA(CZJL) VALUES ('INSERT INTO JKGL_DATA_QYJKM_LSB 2024 结束！');
  COMMIT;
*/
  SET @BJTS_DYNAMIC_SQL_001 = 'TRUNCATE TABLE JKGL_DATA_ZB_JGB';
PREPARE BJTS_DYNAMIC_STMT_001 FROM @BJTS_DYNAMIC_SQL_001;
EXECUTE BJTS_DYNAMIC_STMT_001;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_001;
  COMMIT;
  INSERT INTO JKGL_DATA_ZB_JGB(DJXH,ZB_ID,ZB_VAL,BADPOINT,SCORE,JS_STATUS,FF_STATUS,UPTIME,PARAMS)
       SELECT B.DJXH,Z.ZB_ID,Z.ZB_VAL,Z.BADPOINT, 0,'1','0',CURRENT_TIMESTAMP, Z.PARAMS
                FROM GLXT_BB_SHXT_DJXX D, JKGL_DATA_BGQ B, JKGL_DATA_TJ_ZB Z
               WHERE B.BGQID=Z.BGQID AND D.DJXH_JS=B.DJXH
                 AND B.BGQ_Q=CAST('2025-01-01' AS DATE) AND B.BGQ_Z=CAST('2025-12-31' AS DATE);
  INSERT INTO JKGL_LOG_DEALDATA(CZJL) VALUES ('MERGE INTO TL_TSSH.JKGL_DATA_ZB_JGB 2025结束！');
  COMMIT;

  SET @BJTS_DYNAMIC_SQL_002 = 'TRUNCATE TABLE JKGL_DATA_QYJKM_JGB';
PREPARE BJTS_DYNAMIC_STMT_002 FROM @BJTS_DYNAMIC_SQL_002;
EXECUTE BJTS_DYNAMIC_STMT_002;
DEALLOCATE PREPARE BJTS_DYNAMIC_STMT_002;
  COMMIT;
  INSERT INTO JKGL_DATA_QYJKM_JGB(DJXH,TSJSFS_DM,CRTIME)
       SELECT T.DJXH_JS,T.JSMODE,CURRENT_TIMESTAMP
         FROM GLXT_BB_SHXT_DJXX T
        WHERE EXISTS (SELECT 1
                        FROM JKGL_DATA_ZB_JGB Z
                       WHERE T.DJXH_JS=Z.DJXH AND Z.FF_STATUS='0' AND Z.ZB_ID IN ('W10101','S10101'))
          AND NOT EXISTS (SELECT 1
                            FROM JKGL_DATA_QYJKM_JGB U
                           WHERE U.DJXH=T.DJXH_JS);
  INSERT INTO JKGL_LOG_DEALDATA(CZJL) VALUES ('MERGE INTO TL_TSSH.JKGL_DATA_QYJKM_JGB 2025 结束！');
  COMMIT;

  CALL PRO_JKGL_JKM_MAIN(NULL,NULL);
  INSERT INTO JKGL_LOG_DEALDATA(CZJL) VALUES ('PRO_JKGL_JKM_MAIN 2025 结束！');
  COMMIT;

  LEAVE routine_body;
END$$

DELIMITER ;
