DELIMITER $$

DROP PROCEDURE IF EXISTS TEMP_PRO_DEAL_MTS_HIS$$

CREATE PROCEDURE TEMP_PRO_DEAL_MTS_HIS()
routine_body: BEGIN

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_SHXX_UUID_001 LONGTEXT;
  DECLARE BJTS_CUR_SHXX_LCSLID_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.UUID,T.LCSLID FROM CKTS_LC_SHXX T WHERE T.SBYWB_DM='A0301001' /*AND T.LCJSRQ>=DATE'2023-01-01'*/ AND T.LCJSRQ<CAST('2025-01-01' AS DATE) AND T.SJTB_BZ<>'H';
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_SHXX_UUID_001, BJTS_CUR_SHXX_LCSLID_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    INSERT INTO CKTS_SB_MTS_CKMX_HIS
    SELECT * FROM CKTS_SB_MTS_CKMX S WHERE S.LCSLID=BJTS_CUR_SHXX_LCSLID_001;
    INSERT INTO CKTS_SB_MTS_JHMX_HIS
    SELECT * FROM CKTS_SB_MTS_JHMX S WHERE S.LCSLID=BJTS_CUR_SHXX_LCSLID_001;
    COMMIT;
    DELETE FROM CKTS_SB_MTS_CKMX AS S WHERE S.LCSLID=BJTS_CUR_SHXX_LCSLID_001;
    DELETE FROM CKTS_SB_MTS_JHMX AS S WHERE S.LCSLID=BJTS_CUR_SHXX_LCSLID_001;
    UPDATE CKTS_LC_SHXX AS S
       SET SJTB_BZ='H'
     WHERE S.UUID=BJTS_CUR_SHXX_UUID_001;
    COMMIT;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  LEAVE routine_body;
END$$

DELIMITER ;
