DELIMITER $$

DROP PROCEDURE IF EXISTS TEMP_PRO_DEAL_AFTER_ETL$$

CREATE PROCEDURE TEMP_PRO_DEAL_AFTER_ETL
(
  OUT V_ERROR DECIMAL(38,10),
  OUT V_MSG VARCHAR(4000)
)
routine_body: BEGIN
  DECLARE LC_SBYY          VARCHAR(2000);
  DECLARE LD_DEALDATA      DATETIME;          --用于基础数据处理的提前量
  DECLARE LN_LOG           BIGINT;
  DECLARE LC_BBNY          VARCHAR(6);   --本期制表年月
  DECLARE LD_BBNY_KSNF     DATETIME;          --本期制表年月年初
  DECLARE LD_BBNY_KSRQ     DATETIME;          --本期制表年月开始日期，一般为制表年月的月初
  DECLARE LD_BBNY_JZRQ     DATETIME;          --本期制表年月结束日期，一般为制表年月的下一个月初
  DECLARE LC_DJZCLX        VARCHAR(6);   --本期制表年月
  DECLARE GLH_JSJE         DECIMAL(18,2);
  DECLARE GLH_TSL          DECIMAL(18,2);
  DECLARE GLH_TMSE         DECIMAL(18,2);
  DECLARE LN_ALLCK         DECIMAL(18,2);
  DECLARE LN_SNCK          DECIMAL(18,2);
  DECLARE LN_MYLAJ         DECIMAL(18,2);
  DECLARE LN_RMBLAJ        DECIMAL(18,2);
  DECLARE LN_MDTSE         DECIMAL(18,2);
  DECLARE LN_ZH_MDTSE      DECIMAL(18,2);
  DECLARE LN_BYTS_MDTSE    DECIMAL(18,2);
  DECLARE LN_BYBL_MDTSE    DECIMAL(18,2);
  DECLARE LN_ZZS           DECIMAL(18,2);
  DECLARE LN_XFS           DECIMAL(18,2);
  DECLARE LN_MDSE          DECIMAL(18,2);
  DECLARE SN_ZZS           DECIMAL(18,2);
  DECLARE SN_XFS           DECIMAL(18,2);
  DECLARE SN_MDSE          DECIMAL(18,2);
  DECLARE SY_ZZS           DECIMAL(18,2);
  DECLARE SY_XFS           DECIMAL(18,2);
  DECLARE SY_MDSE          DECIMAL(18,2);
  DECLARE ALL_SB_MDTSE     DECIMAL(18,2);
  DECLARE LD_LASTRQ        DATETIME;
  DECLARE V_ZLC_FS         DECIMAL(18,2);
  DECLARE V_ZLC_TS_AMT     DECIMAL(18,2);
  DECLARE V_ZLC_MD_AMT     DECIMAL(18,2);
  DECLARE V_ZLC_ZK_AMT     DECIMAL(18,2);
  DECLARE V_FF_DATE        DATETIME;
  DECLARE V_SL_DATE        DATETIME;
  DECLARE V_FH_DATE        DATETIME;
  DECLARE V_FH_USER        VARCHAR(20);
  DECLARE V_YWHZ_DATE      DATETIME;
  DECLARE V_YWHZ_USER      VARCHAR(20);
  DECLARE V_SEHZ_DATE      DATETIME;
  DECLARE V_SEHZ_USER      VARCHAR(20);
  DECLARE V_TSKP_DATE      DATETIME;
  DECLARE V_TSTK_DATE      DATETIME;
  DECLARE LN_I             BIGINT;
  DECLARE LN_J             BIGINT;
  DECLARE V_ZFBZ           CHAR(1);
  DECLARE V_ZFR_DM         VARCHAR(100);
  DECLARE V_ZFRQ           DATETIME;
  DECLARE V_CKSPTSSPLX_DM  CHAR(1);
  DECLARE V_TSL            DECIMAL(18,2);
  DECLARE V_JGFSTSLX_DM    CHAR(1);
  DECLARE V_HYDXZQH_DM     CHAR(4);

  SET V_ERROR =0;
  SET V_MSG = ' ';

  SET LD_DEALDATA =TRUNCATE(CURRENT_TIMESTAMP, 0) - 3;
  SET LN_LOG =2;

    --ZBBLBZ：需要根据CKTS_LC_SHYDDCL重新设置
    --20260730从CKTS_LC_SHYDDCL设置暂不办理，从CKTS_LC_JCZBBL解除暂不办理
    SET LN_I =0;
    FOR CUR_MTS IN (SELECT DISTINCT T.DJXH, T.GLH, T.LCSLID
                      FROM (SELECT * FROM CKTS_LC_SHYDDCL WHERE SBYWB_DM='A0301001'
                             UNION ALL
                            SELECT * FROM CKTS_LC_SHYDDCL_SHXT WHERE SBYWB_DM='A0301001') T)
    LOOP
      BEGIN
        UPDATE CKTS_SB_MTS_JHMX R
           SET R.SJTB_SJ=CURRENT_TIMESTAMP, R.ZBBLBZ='Y'
         WHERE R.DJXH=CUR_MTS.DJXH AND R.GLH=CUR_MTS.GLH AND R.LCSLID=CUR_MTS.LCSLID AND R.ZBBLBZ='N';
        UPDATE CKTS_SB_MTS_CKMX R
           SET R.SJTB_SJ=CURRENT_TIMESTAMP, R.ZBBLBZ='Y'
         WHERE R.DJXH=CUR_MTS.DJXH AND R.GLH=CUR_MTS.GLH AND R.LCSLID=CUR_MTS.LCSLID AND R.ZBBLBZ='N';
        COMMIT;
        SET LN_I =LN_I+1;
      END;
    END LOOP;

    SET LN_I =0;
    FOR CUR_MTS IN (SELECT DISTINCT T.DJXH, T.GLH, T.LCSLID
                      FROM CKTS_LC_JCZBBL T
                     WHERE T.SBYWB_DM='A0301001')
    LOOP
      BEGIN
        UPDATE CKTS_SB_MTS_JHMX R
           SET R.SJTB_SJ=CURRENT_TIMESTAMP, R.ZBBLBZ='N'
         WHERE R.DJXH=CUR_MTS.DJXH AND R.GLH=CUR_MTS.GLH AND R.LCSLID=CUR_MTS.LCSLID AND R.ZBBLBZ='Y';
        UPDATE CKTS_SB_MTS_CKMX R
           SET R.SJTB_SJ=CURRENT_TIMESTAMP, R.ZBBLBZ='N'
         WHERE R.DJXH=CUR_MTS.DJXH AND R.GLH=CUR_MTS.GLH AND R.LCSLID=CUR_MTS.LCSLID AND R.ZBBLBZ='Y';
        COMMIT;
        SET LN_I =LN_I+1;
      END;
    END LOOP;

  LEAVE routine_body;
END$$

DELIMITER ;
