DELIMITER $$

DROP PROCEDURE IF EXISTS TEMP_JKGL_COMPUTE_ZBU_JD$$

CREATE PROCEDURE TEMP_JKGL_COMPUTE_ZBU_JD()
/*
 * 季度指标元刷新算法
 * 202309，增加判断是否新开业的出口企业
 * 202309，增加代理出口统计
 * 20250919，调整拼箱与整柜报关单的计算口径
 */
routine_body: BEGIN
  DECLARE V_CK_PXBGDSL      BIGINT; --  出口_拼箱报关单数量
  DECLARE V_CK_ZXBGDSL      DECIMAL(18,2); --  出口_整箱报关单数量
  DECLARE V_CK_PJDBHGZ      DECIMAL(18,2); --  出口_平均单笔货柜值
  DECLARE V_BGQ_Q           DATETIME;

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_BGQ_BGQID_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_DJXH_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_BGQ_Q_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_BGQ_Z_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_SQ_DATE_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.BGQID, T.DJXH, T.BGQ_Q, ORA_DATE_ADD(T.BGQ_Z, 1) AS BGQ_Z, S.SQ_DATE
                    FROM JKGL_DATA_BGQ T
                   INNER JOIN GLXT_BB_SHXT_DJXX S ON S.DJXH_JS=T.DJXH
                   WHERE T.ZQLX='季' AND MAKEDATE(YEAR(T.BGQ_Q), 1)>=CAST('2020-01-01' AS DATE);
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_BGQ_BGQID_001, BJTS_CUR_BGQ_DJXH_001, BJTS_CUR_BGQ_BGQ_Q_001, BJTS_CUR_BGQ_BGQ_Z_001, BJTS_CUR_BGQ_SQ_DATE_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    -- 判断是否新开业的出口企业
    IF BJTS_CUR_BGQ_SQ_DATE_001>=BJTS_CUR_BGQ_BGQ_Q_001 AND BJTS_CUR_BGQ_SQ_DATE_001<BJTS_CUR_BGQ_BGQ_Z_001 THEN
      -- 当年新办的出口企业，首次报告期统计范围从当年年初开始，防止先出口后备案，并与年度报告期分类统计一致
      SET V_BGQ_Q = MAKEDATE(YEAR(BJTS_CUR_BGQ_BGQ_Q_001), 1);
    ELSE
      SET V_BGQ_Q = BJTS_CUR_BGQ_BGQ_Q_001;
    END IF;

    --  V_CK_
    BEGIN
      --  V_CK_PXBGDSL  NUMBER(10)  出口_拼箱报关单数量
      SELECT COUNT(DISTINCT T.BGDHGBH)
        INTO V_CK_PXBGDSL
        FROM CKTS_WBSJ_HG_BGD204 T
       WHERE T.DJXH=BJTS_CUR_BGQ_DJXH_001
         AND T.CKRQ_1>=V_BGQ_Q AND T.CKRQ_1<BJTS_CUR_BGQ_BGQ_Z_001
         AND T.JZXH<>'无'
         AND (T.BJMMJBZ LIKE '%拼箱%' OR
             EXISTS (SELECT 1
                       FROM CKTS_WBSJ_HG_BGD204 S
                      WHERE S.JZXH=T.JZXH AND S.CKRQ_1=T.CKRQ_1 AND S.DJXH<>T.DJXH));

      --  V_CK_ZXBGDSL  NUMBER(18,2)  出口_整箱报关单数量
      --  V_CK_PJDBHGZ  NUMBER(18,2)  出口_平均单笔货柜值
      WITH JZXHXX AS (SELECT T2.BGDHGBH, COUNT(DISTINCT T2.JZXH) AS JZXSL
                        FROM CKTS_WBSJ_HG_BGD204 T2
                       WHERE T2.DJXH=BJTS_CUR_BGQ_DJXH_001
                         AND T2.CKRQ_1>=V_BGQ_Q AND T2.CKRQ_1<BJTS_CUR_BGQ_BGQ_Z_001
                         AND T2.JZXH<>'无'
                         AND T2.BJMMJBZ NOT LIKE '%拼箱%'
                         AND NOT EXISTS (SELECT 1
                                           FROM CKTS_WBSJ_HG_BGD204 T3
                                          WHERE T3.JZXH=T2.JZXH AND T3.CKRQ_1=T2.CKRQ_1 AND T3.DJXH<>T2.DJXH)
                       GROUP BY T2.BGDHGBH),
           CKBGXX AS (SELECT SUBSTR(T.CKBGDH,1,18) AS BGDHGBH, SUM(T.MYLAJ) AS TOTALMY
                        FROM CKTS_WBSJ_HG_BGD T
                       WHERE T.DJXH=BJTS_CUR_BGQ_DJXH_001
                         AND T.CKRQ_1>=V_BGQ_Q AND T.CKRQ_1<BJTS_CUR_BGQ_BGQ_Z_001
                         AND T.JGFS_DM<>'1039'
                       GROUP BY SUBSTR(T.CKBGDH,1,18))
      SELECT COUNT(DISTINCT JZXHXX.BGDHGBH),
             IFNULL((CASE WHEN SUM(JZXHXX.JZXSL)=0 THEN 0 ELSE SUM(CKBGXX.TOTALMY)/SUM(JZXHXX.JZXSL) END), 0)
        INTO V_CK_ZXBGDSL, V_CK_PJDBHGZ
        FROM JZXHXX
       INNER JOIN CKBGXX ON JZXHXX.BGDHGBH=CKBGXX.BGDHGBH;

      UPDATE JKGL_DATA_TJ_ZBU
         SET CK_PXBGDSL=V_CK_PXBGDSL,
    CK_ZXBGDSL=V_CK_ZXBGDSL,
    CK_PJDBHGZ=V_CK_PJDBHGZ
       WHERE BGQID=BJTS_CUR_BGQ_BGQID_001;
      COMMIT;
    END;

  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  LEAVE routine_body;
END$$

DELIMITER ;
