DELIMITER $$

DROP PROCEDURE IF EXISTS TEMP_JKGL_COMPUTE_ZBU_ND$$

CREATE PROCEDURE TEMP_JKGL_COMPUTE_ZBU_ND()
/*
 * 年度指标元刷新算法
 * 202309，增加代理出口统计
 * 20260714，根据龙泉税局反馈，修正年度报表财务期初数据取数口径
 */
routine_body: BEGIN
  DECLARE V_ZC_YSZK_QC      DECIMAL(18,2); --  资产_应收账款_期初
  DECLARE V_ZC_YFZK_QC      DECIMAL(18,2); --  资产_应付账款_期初
  DECLARE V_ZC_GDZC_QC      DECIMAL(18,2); --  资产_固定资产_期初
  DECLARE V_ZC_CH_QC        DECIMAL(18,2); --  资产_存货_期初
  DECLARE V_ZC_ZCZE_QC      DECIMAL(18,2); --  资产_资产总额_期初
  DECLARE V_ZC_FZZE_QC      DECIMAL(18,2); --  资产_负债总额_期初
  DECLARE V_ZC_SYZQY_QC     DECIMAL(18,2); --  资产_所有者权益_期初
  DECLARE V_ZC_SSGDQY_QC    DECIMAL(18,2); --  资产_少数股东权益_期初
  DECLARE V_ZC_LDZC_QC      DECIMAL(18,2); --  资产_流动资产_期初
  DECLARE V_ZC_YUSZK_QC     DECIMAL(18,2); --  资产_预收账款_期初
  DECLARE V_ZC_YUFZK_QC     DECIMAL(18,2); --  资产_预付账款_期初
  DECLARE V_ZC_LDFZZE_QC    DECIMAL(18,2); --  资产_流动负债总额_期初

  BEGIN
  DECLARE BJTS_CURSOR_DONE_001 BOOLEAN DEFAULT FALSE;
  DECLARE BJTS_CUR_BGQ_BGQID_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_ZQLX_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_DJXH_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_BGQ_Q_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_BGQ_Z_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_YF_Q_001 LONGTEXT;
  DECLARE BJTS_CUR_BGQ_YF_Z_001 LONGTEXT;
  DECLARE BJTS_CURSOR_001 CURSOR FOR
SELECT T.BGQID, T.ZQLX, T.DJXH,
                         T.BGQ_Q, T.BGQ_Z, DATE_FORMAT(T.BGQ_Q, '%Y%m') AS YF_Q, DATE_FORMAT(T.BGQ_Z, '%Y%m') AS YF_Z
                    FROM JKGL_DATA_BGQ T
                   WHERE T.ZQLX='年' AND T.SXZT='0' AND T.TQBZ IS NULL;
  OPEN BJTS_CURSOR_001;
  BJTS_CURSOR_LOOP_001: LOOP
    SET BJTS_CURSOR_DONE_001 = FALSE;
    BEGIN
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET BJTS_CURSOR_DONE_001 = TRUE;
      FETCH BJTS_CURSOR_001 INTO BJTS_CUR_BGQ_BGQID_001, BJTS_CUR_BGQ_ZQLX_001, BJTS_CUR_BGQ_DJXH_001, BJTS_CUR_BGQ_BGQ_Q_001, BJTS_CUR_BGQ_BGQ_Z_001, BJTS_CUR_BGQ_YF_Q_001, BJTS_CUR_BGQ_YF_Z_001;
    END;
    IF BJTS_CURSOR_DONE_001 THEN
      LEAVE BJTS_CURSOR_LOOP_001;
    END IF;
    -- 锁定正在处理的报告期
    UPDATE JKGL_DATA_BGQ AS T
       SET TQBZ=REPLACE(UUID(), '-', ''),
    TQSJ=CURRENT_TIMESTAMP,
    SXZT='1'
     WHERE T.BGQID=BJTS_CUR_BGQ_BGQID_001;
    COMMIT;

    SELECT ZC_YSZK_QC, ZC_YFZK_QC, ZC_GDZC_QC, ZC_CH_QC, ZC_ZCZE_QC, ZC_FZZE_QC,
           ZC_SYZQY_QC, ZC_SSGDQY_QC, ZC_LDZC_QC, ZC_YUSZK_QC, ZC_YUFZK_QC, ZC_LDFZZE_QC
      INTO V_ZC_YSZK_QC, V_ZC_YFZK_QC, V_ZC_GDZC_QC, V_ZC_CH_QC, V_ZC_ZCZE_QC, V_ZC_FZZE_QC,
           V_ZC_SYZQY_QC, V_ZC_SSGDQY_QC, V_ZC_LDZC_QC, V_ZC_YUSZK_QC, V_ZC_YUFZK_QC, V_ZC_LDFZZE_QC
      FROM (SELECT T2.*, T1.BGQ_Z
              FROM JKGL_DATA_BGQ T1
             INNER JOIN JKGL_DATA_TJ_ZBU T2 ON T2.BGQID=T1.BGQID
             WHERE T1.DJXH=BJTS_CUR_BGQ_DJXH_001 AND T1.BGQ_Q>=BJTS_CUR_BGQ_BGQ_Q_001 AND T1.BGQ_Z<=BJTS_CUR_BGQ_BGQ_Z_001
               AND T1.ZQLX='季'
             ORDER BY T1.BGQ_Z ASC)
     WHERE 1=1
LIMIT 1;

    UPDATE JKGL_DATA_TJ_ZBU
       SET ZC_YSZK_QC=V_ZC_YSZK_QC,
    ZC_YFZK_QC=V_ZC_YFZK_QC,
    ZC_GDZC_QC=V_ZC_GDZC_QC,
    ZC_CH_QC=V_ZC_CH_QC,
    ZC_ZCZE_QC=V_ZC_ZCZE_QC,
    ZC_FZZE_QC=V_ZC_FZZE_QC,
    ZC_SYZQY_QC=V_ZC_SYZQY_QC,
    ZC_SSGDQY_QC=V_ZC_SSGDQY_QC,
    ZC_LDZC_QC=V_ZC_LDZC_QC,
    ZC_YUSZK_QC=V_ZC_YUSZK_QC,
    ZC_YUFZK_QC=V_ZC_YUFZK_QC,
    ZC_LDFZZE_QC=V_ZC_LDFZZE_QC
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_001;
    COMMIT;

    UPDATE JKGL_DATA_TJ_ZBU_KZ AS T
       SET CW_HYSFL = (SELECT -- 行业税负率=100%*（0.13*（增值税全部销售额+期末存货-期初存货）-进项税额+进项税额转出）/增值税全部销售额
           CASE WHEN (ZZS_XSE_QB IS NOT NULL) AND (ZZS_XSE_QB<>0)
                THEN LEAST(GREATEST(ROUND(100*(0.13*(ZZS_XSE_QB+ZC_CH_QM-ZC_CH_QC)-ZZS_JXSE+ZZS_JXSEZC)/ZZS_XSE_QB,2),-100),100)
                ELSE NULL
           END
FROM JKGL_DATA_TJ_ZBU
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_001),
    CW_ZZCBCL = (SELECT -- 总资产报酬率=100%*息税前利润/资产平均总额=200%*（净利润+所得税+利息支出）/（年初资产总额+年末资产总额）
           CASE WHEN (ZC_ZCZE_QC IS NOT NULL) AND (ZC_ZCZE_QM IS NOT NULL) AND (ZC_ZCZE_QC+ZC_ZCZE_QM<>0)
                THEN LEAST(GREATEST(ROUND(200*(LR_JLR+LR_SDS+LR_LXZC)/(ZC_ZCZE_QC+ZC_ZCZE_QM),2),-100),1000)
                ELSE NULL
           END
FROM JKGL_DATA_TJ_ZBU
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_001),
    CW_ZZCZZL = (SELECT -- 总资产增长率=100%*（年末资产总额-年初资产总额）/年初资产总额
           CASE WHEN (ZC_ZCZE_QC IS NOT NULL) AND (ZC_ZCZE_QC<>0)
                THEN LEAST(GREATEST(ROUND(100*(ZC_ZCZE_QM-ZC_ZCZE_QC)/ZC_ZCZE_QC,2),-100),1000)
                ELSE NULL
           END
FROM JKGL_DATA_TJ_ZBU
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_001),
    CW_CHZZL = (SELECT -- 存货周转率=营业成本/平均存货=2*营业成本/(期末存货+期初存货)
           CASE WHEN (ZC_CH_QC IS NOT NULL) AND (ZC_CH_QM IS NOT NULL) AND (ZC_CH_QC+ZC_CH_QM<>0)
                THEN LEAST(GREATEST(ROUND(2*LR_YYCB/(ZC_CH_QC+ZC_CH_QM),2),0),360)
                ELSE NULL
           END
FROM JKGL_DATA_TJ_ZBU
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_001),
    CW_YSZKZZL = (SELECT -- 应收账款周转率=2*当期销售净收入/（期初应收账款+期末应收账款
           CASE WHEN (ZC_YSZK_QC IS NOT NULL) AND (ZC_YSZK_QM IS NOT NULL) AND (ZC_YSZK_QC+ZC_YSZK_QM<>0)
                THEN LEAST(GREATEST(ROUND(200*LR_YYSR/(ZC_YSZK_QC+ZC_YSZK_QM),2),0),360)
                ELSE NULL
           END
FROM JKGL_DATA_TJ_ZBU
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_001)
     WHERE BGQID=BJTS_CUR_BGQ_BGQID_001;
    COMMIT;

    -- 解锁处理完成的报告期
    UPDATE JKGL_DATA_BGQ AS T
       SET TQBZ=NULL,
    WCSJ=CURRENT_TIMESTAMP,
    SXZT='2'
     WHERE T.BGQID=BJTS_CUR_BGQ_BGQID_001;
    COMMIT;


  END LOOP BJTS_CURSOR_LOOP_001;
  CLOSE BJTS_CURSOR_001;
END;

  LEAVE routine_body;
END$$

DELIMITER ;
