CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W50304
/*
 * 应付账款占营业成本比重
 * ZB_VAL：100% * 期末应付 / 营业成本
 */
(
  P_BGQID   IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT T.LR_YYCB, T.ZC_YFZK_QM,
           '[d]营业成本=' ||T.LR_YYCB || '|期末应付=' || T.ZC_YFZK_QM
      INTO V_THIS_DATA, V_LAST_DATA, V_PARAMS
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    V_ZB_VAL := ROUND(100 * V_LAST_DATA / V_THIS_DATA, 2);
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50304' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W50304',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50304';
  END IF;
  COMMIT;

  RETURN;
END;
/
