CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S30202
/*
 * 新增商品出口占比
 * ZB_VAL：报告期新增商品出口额÷报告期出口销售额×100%
 */
(
  P_BGQID   IN NUMBER,
  P_JQID    IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_PARAMS     VARCHAR(4000);
  V_PARAMS1    VARCHAR(4000);
BEGIN
  BEGIN
    SELECT S.CK_CKEUSD
      INTO V_THIS_DATA
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;
    V_PARAMS := '[d]报告期出口额=' || V_THIS_DATA;

    V_ZB_VAL := 0;
    V_LAST_DATA :=0;
    V_PARAMS1 := '';
    FOR CUR_SPDM IN (SELECT T.SP8_DM, DM.CKSP_MC, T.CKEUSD
                       FROM TL_TSSH.JKGL_DATA_TJ_ZBU_CKSP T
                       LEFT JOIN TL_TSSH.JCFX_DM_CKSPTREE DM ON DM.CKSP_DM=T.SP8_DM AND DM.CKSP_JC='4'
                      WHERE T.BGQID=P_BGQID
                        AND NOT EXISTS (SELECT 1
                                          FROM TL_TSSH.JKGL_DATA_TJ_ZBU_CKSP S
                                         WHERE S.BGQID=P_JQID
                                           AND S.SP8_DM=T.SP8_DM))
    LOOP
      V_ZB_VAL := V_ZB_VAL +1;
      V_LAST_DATA := V_LAST_DATA + CUR_SPDM.CKEUSD;
      IF V_ZB_VAL<=20 THEN
        V_PARAMS1 := V_PARAMS1 || '|新增出口商品=' || CUR_SPDM.SP8_DM || '（' || CUR_SPDM.CKSP_MC ||'），出口额' || CUR_SPDM.CKEUSD;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      V_PARAMS1 := V_PARAMS1 || '|...';
    END IF;

    V_PARAMS := V_PARAMS || '|报告期新增商品出口总额=' || V_LAST_DATA || V_PARAMS1;
    IF V_THIS_DATA>1 THEN
      V_ZB_VAL:=ROUND(100 * V_LAST_DATA / V_THIS_DATA,2);
    ELSE
      V_ZB_VAL := NULL;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30202' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30202',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30202';
  END IF;
  COMMIT;

  RETURN;
END;
/
