CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W10202
/*
 * 注册地址与生产经营地址不一致
 * ZB_VAL：一致0，不一致1
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT CASE WHEN T.ADDRESS_ZC=T.ADDRESS_JY THEN 0 ELSE 1 END,
           '[d]企业注册地址=' || T.ADDRESS_ZC || '|企业经营地址=' || T.ADDRESS_JY
      INTO V_ZB_VAL, V_PARAMS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.DJXH_JS=P_DJXH;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10202' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W10202',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10202';
  END IF;
  COMMIT;

  RETURN;
END;
/
