CREATE OR REPLACE PROCEDURE PRO_DEAL_JCFX_NSR_BADJ_BLV
(
  V_YEAR IN VARCHAR2
)
AS
  LN_QBXSE         NUMBER(18,2);
  LN_CKXSE         NUMBER(18,2);
  LN_CKGM          NUMBER(18,2);
  LN_SBMDE         NUMBER(18,2);
  LN_SBMDTSE       NUMBER(18,2);
  LN_SBSF          NUMBER(18,2);
  LN_CKBLV         NUMBER(10,6);
  LN_MDBLV         NUMBER(10,6);
  LN_SFBLV         NUMBER(10,6);
  LC_CKBLV         VARCHAR(1);
  LC_CKGM          VARCHAR(1);
  LC_MDBLV         VARCHAR(1);
  LC_SFBLV         VARCHAR(1);
BEGIN
  IF V_YEAR IS NULL THEN 
    RETURN;
  END IF;
  
  --根据审核信息设置LCTJJC
  FOR CUR_NSR IN (SELECT T.DJXH
                    FROM TL_TSSH.JCFX_NSR_BADJ T)
  LOOP
    SELECT NVL(SUM(S.ZZS_QBXSSR),0), NVL(SUM(S.CK_SB_XSERMB),0), NVL(SUM(S.CK_SB_XSEMY),0), NVL(SUM(S.CK_SB_MDE),0), NVL(SUM(S.CK_SB_TSE+S.CK_SB_MDE),0), NVL(SUM(S.ZZS_YNSE+S.CK_SB_MDE),0)
      INTO LN_QBXSE, LN_CKXSE, LN_CKGM, LN_SBMDE, LN_SBMDTSE, LN_SBSF
      FROM TL_TSSH.JCFX_DATA_QYYHZ S 
     WHERE S.DJXH=CUR_NSR.DJXH AND S.NY LIKE V_YEAR || '%';
    
    IF LN_QBXSE<=0 THEN
      IF LN_CKXSE<=0 THEN
        LN_CKBLV := 0;
      ELSE
        LN_CKBLV := 100;
      END IF;
    ELSE 
      -- LN_QBXSE>0
      IF LN_CKXSE> LN_QBXSE THEN
        LN_CKBLV := 100;
      ELSIF LN_CKXSE<0 THEN
        LN_CKBLV := 0;
      ELSE
        LN_CKBLV := 100 * LN_CKXSE / LN_QBXSE;
      END IF;
    END IF;
    
    IF LN_SBMDTSE<=0 OR LN_SBMDE<=0 THEN
      LN_MDBLV := 0;
    ELSIF LN_SBMDE>LN_SBMDTSE THEN
      LN_MDBLV := 100;
    ELSE
      LN_MDBLV := 100 * LN_SBMDE / LN_SBMDTSE;
    END IF;
    
    IF LN_QBXSE<=0 OR LN_SBSF<=0 THEN
      LN_SFBLV := 0;
    ELSIF LN_SBSF>LN_QBXSE THEN
      LN_SFBLV := 100;
    ELSE
      LN_SFBLV := 100 * LN_SBSF / LN_QBXSE;
    END IF;
      
      
    LC_CKBLV := CASE WHEN LN_CKBLV>=80 THEN 'A' WHEN LN_CKBLV>=60 THEN 'B' WHEN LN_CKBLV>=40 THEN 'C' WHEN LN_CKBLV>=20 THEN 'D' ELSE 'E' END;
    LC_CKGM := CASE WHEN LN_CKGM>=100000000 THEN 'A' WHEN LN_CKGM>=50000000 THEN 'B' WHEN LN_CKGM>=10000000 THEN 'C' WHEN LN_CKGM>=1000000 THEN 'D' ELSE 'E' END;
    LC_MDBLV := CASE WHEN LN_MDBLV>=40 THEN 'A' WHEN LN_MDBLV>=30 THEN 'B' WHEN LN_MDBLV>=20 THEN 'C' WHEN LN_MDBLV>=10 THEN 'D' ELSE 'E' END;
    LC_SFBLV := CASE WHEN LN_SFBLV>=20 THEN 'A' WHEN LN_SFBLV>=15 THEN 'B' WHEN LN_SFBLV>=10 THEN 'C' WHEN LN_SFBLV>=5 THEN 'D' ELSE 'E' END;
    
    UPDATE TL_TSSH.JCFX_NSR_BADJ A
       SET A.CKBLV=LN_CKBLV, A.CKBLV_DM=LC_CKBLV, A.CKGM=LN_CKGM, A.CKGM_DM=LC_CKGM, A.MDBLV=LN_MDBLV, A.MDBLV_DM=LC_MDBLV, A.SFLV=LN_SFBLV, A.SFLV_DM=LC_SFBLV
     WHERE A.DJXH=CUR_NSR.DJXH;
    COMMIT;
  END LOOP;

  RETURN;
END;
/
