CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W30103
/*
 * 企业出口大单(>=10WUSD)占比
 * ZB_VAL：LEAST(100, ROUND(100 * V_LAST_DATA / V_THIS_DATA, 2))
 */
(
  P_BGQID   IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT T.CK_CKEUSD, T.CK_CKEUSD_DE
      INTO V_THIS_DATA, V_LAST_DATA
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    V_PARAMS := '[d]报告期美元出口销售额=' || V_THIS_DATA || '|其中大单美元出口销售额=' || V_LAST_DATA;
    IF V_THIS_DATA<=1 OR V_LAST_DATA<0 THEN
      V_ZB_VAL := NULL;
    ELSE
      V_ZB_VAL:=LEAST(100, ROUND(100 * V_LAST_DATA / V_THIS_DATA, 2));
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30103' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W30103',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30103';
  END IF;
  COMMIT;

  RETURN;
END;
/
