CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W50102
/*
 * 出口企业总体毛利率与同行业平均值相比偏离是否较大
 * ZB_VAL：总体毛利率
 */
(
  P_BGQID   IN NUMBER,
  P_QSPJID   IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT T.CW_MLL
      INTO V_ZB_VAL
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU_KZ T
     WHERE T.BGQID=P_BGQID;
    SELECT '[d]全省平均毛利率：' || T.MLL
      INTO V_PARAMS
      FROM JKGL_QSPJ_JGB T
     WHERE T.BGQID=P_QSPJID;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50102' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W50102',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50102';
  END IF;
  COMMIT;

  RETURN;
END;
/
