CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S30101
/*
 * 出口额变动率异常
 * ZB_VAL：（报告期出口销售额-基期出口销售额）÷基期出口销售额×100%
 */
(
  P_BGQID   IN NUMBER,
  P_JQID    IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_PARAMS     VARCHAR(1000);
BEGIN
  BEGIN
    SELECT S.CK_CKEUSD
      INTO V_THIS_DATA
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;
    SELECT S.CK_CKEUSD
      INTO V_LAST_DATA
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_JQID;

    V_PARAMS := '[d]报告期出口美元销售额=' || V_THIS_DATA || '|基期出口美元销售额=' || V_LAST_DATA;
    IF V_THIS_DATA>0 AND V_LAST_DATA>0 THEN
      V_ZB_VAL:=ROUND(100 * (V_THIS_DATA - V_THIS_DATA) / V_LAST_DATA,2);
    ELSE
      V_ZB_VAL := NULL;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30101' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30101',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30101';
  END IF;
  COMMIT;

  RETURN;
END;
/
