CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W20202
/*
 * 超期申报报关单多、金额占比高
 * ZB_VAL：超期申报报关单数量>XX and 超期申报出口额/报告期出口额>YY%
 */
(
  P_BGQID   IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_CQSB_NUM   NUMBER(18,2);
  VAL1         NUMBER(18,2);    --参数1
  VAL2         NUMBER(18,2);    --参数2
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W20202_CQSB_BGD_NUM';
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W20202_CQSB_CKE_ZB';

    SELECT T.TS_CKEUSD, T.TS_CKEUSD_CQ, T.TS_BGDSL_CQ
      INTO V_THIS_DATA, V_LAST_DATA, V_CQSB_NUM
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    V_PARAMS := '[d]报告期出口额=' || V_THIS_DATA || '|超期申报出口额=' || V_LAST_DATA || '|超期申报报关单数量=' || V_CQSB_NUM;
    IF V_THIS_DATA<=0 THEN
      V_ZB_VAL := NULL;
    ELSIF V_CQSB_NUM>=VAL1 AND V_LAST_DATA>=VAL2 * V_THIS_DATA THEN
      V_ZB_VAL:=1;
    ELSE
      V_ZB_VAL:=0;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20202' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W20202',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20202';
  END IF;
  COMMIT;

  RETURN;
END;
/
