CREATE OR REPLACE PROCEDURE PRO_FXGL_SZYJ_XBLQY
/*
 * 风险管理——事中预警——新办类企业
 */
(
  P_SWJGDM  IN  VARCHAR2, --非空，通审核助手获取当前流程的退税机关代码并传入
  P_DJXH    IN  VARCHAR2, --非空，通审核助手获取当前流程的企业登记序号并传入
  P_OUTMSG  OUT VARCHAR2
)
AS
  LN_MONTHS_ZDCK   NUMBER(18,2);
  LN_MONTHS_SCSB   NUMBER(18,2);
  LD_PRE_MAXRQ     DATE;
  LD_NOW_MINRQ     DATE;
  LD_BG_TSJWRQ     DATE;
BEGIN
  --预警参数：新办类企业首次申报以后有效期
  SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
    INTO LN_MONTHS_SCSB
    FROM FXGL_PZ_ZB_CS T
    LEFT JOIN FXGL_PZ_ZB_CS_SWJG S
      ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
   WHERE T.CSBM='C01001_MONTHS_SCSB';
  --预警参数：中断出口后复出口的企业中断期
  SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
    INTO LN_MONTHS_ZDCK
    FROM FXGL_PZ_ZB_CS T
    LEFT JOIN FXGL_PZ_ZB_CS_SWJG S
      ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
   WHERE T.CSBM='C01001_MONTHS_ZDCK';
  -- LN_MONTHS_SCSB个月前最后一次申报时间
  SELECT TRUNC(MAX(T.QDSJ))
    INTO LD_PRE_MAXRQ
    FROM CKTS_LC_SBXX T
   WHERE T.DJXH = P_DJXH
     AND NVL(T.ZFBZ, 'N') = 'N'
     AND T.QDSJ <= ADD_MONTHS(SYSDATE, (-1) * LN_MONTHS_SCSB);
  -- LN_MONTHS_SCSB个月内最早一次申报时间
  SELECT TRUNC(MIN(T.QDSJ))
    INTO LD_NOW_MINRQ
    FROM CKTS_LC_SBXX T
   WHERE T.DJXH = P_DJXH
     AND NVL(T.ZFBZ, 'N') = 'N'
     AND T.QDSJ > ADD_MONTHS(SYSDATE, (-1) * LN_MONTHS_SCSB);
  -- 外贸企业LN_MONTHS_SCSB个月内最后一次迁移
  SELECT TRUNC(MAX(T.LRRQ))
    INTO LD_BG_TSJWRQ
    FROM CKTS_BA_BABGQK_JGB T
   INNER JOIN GLXT_BB_SHXT_DJXX S
      ON S.DJXH_JS=T.DJXH
     AND S.JSMODE='2'
   WHERE T.DJXH = P_DJXH
     AND BABGZD_DM='TSSWJG_DM_1'
     AND T.LRRQ > ADD_MONTHS(SYSDATE, (-1) * LN_MONTHS_SCSB);
  IF LD_PRE_MAXRQ IS NULL THEN
    P_OUTMSG := '01-新办类企业，出口企业首次申报不足'||LN_MONTHS_SCSB||'个月，请加强审核！';
    RETURN;
  END IF;
  IF NVL(LD_NOW_MINRQ,SYSDATE) >= ADD_MONTHS(LD_PRE_MAXRQ, LN_MONTHS_ZDCK) THEN
    P_OUTMSG := '02-新办类企业，出口企业中断申报'||LN_MONTHS_ZDCK||'个月后复出口申报不足'||LN_MONTHS_SCSB||'个月，请加强审核！';
    RETURN;
  END IF;
  IF LD_BG_TSJWRQ IS NOT NULL THEN
    P_OUTMSG := '03-新办类企业，外贸企业于'||TO_CHAR(LD_BG_TSJWRQ,'YYYY-MM-DD')||'迁移后首次申报不足'||LN_MONTHS_SCSB||'个月，请加强审核！';
    RETURN;
  END IF;
  P_OUTMSG := '00';
  
  RETURN;
END;
/
