CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S20102
/*
 * 退税额增长，取统计期往前一季的数据与上一季的比较
 * ZB_VAL：退税额大于50万元且环比大于150%，返回1
 */
(
  P_BGQID   IN NUMBER,
  P_JQID    IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  VAL1         NUMBER(18,2);    --参数1
  VAL2         NUMBER(18,2);    --参数2
  V_PARAMS     VARCHAR(1000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S20102_TMSE_HB';
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S20102_TMSE';

    SELECT S.TS_MDE_SB + S.TS_TSE_SB
      INTO V_THIS_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;

    SELECT S.TS_MDE_SB + S.TS_TSE_SB
      INTO V_LAST_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_JQID;

    V_PARAMS := '[d]报告期申报退（免）税额=' || V_THIS_DATA || '|基期申报退（免）税额=' || V_LAST_DATA;
    IF V_THIS_DATA>0 AND V_LAST_DATA>0 THEN
      IF V_THIS_DATA>=VAL2 AND V_THIS_DATA>=V_LAST_DATA * VAL1 THEN
        V_ZB_VAL := 1;
      ELSE
        V_ZB_VAL := 0;
      END IF;
      V_PARAMS := V_PARAMS || '|环比=' || ROUND(100 * V_THIS_DATA / V_LAST_DATA,2) || '%';
    ELSE
      V_ZB_VAL := NULL;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S20102' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S20102',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S20102';
  END IF;
  COMMIT;

  RETURN;
END;
/
