CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S10104
/*
 * 出口企业出口企业法定代表人年龄是否异常
 * ZB_VAL：法定代表人年龄小于19周岁；企业经营期未满三年且法人代表年龄大于65周岁，返回1
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER,
  P_BGQ_Z   IN DATE,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_ZJLX       VARCHAR2(50);
  V_ZJHM       VARCHAR2(50);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  VAL1         NUMBER(18,2);    --参数1
  VAL2         NUMBER(18,2);    --参数2
  V_PARAMS     VARCHAR(1000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S10104_AGE_LOWER';
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S10104_AGE_UPPER';

    SELECT FRDB_ZJLX, FRDB_ZJHM
      INTO V_ZJLX, V_ZJHM
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.DJXH_JS=P_DJXH;

    IF V_ZJLX='201' AND LENGTH(V_ZJHM)=15 THEN
      V_THIS_DATA := EXTRACT(YEAR FROM P_BGQ_Z) - TO_NUMBER('19'||SUBSTR(V_ZJHM,7,2));
    ELSIF V_ZJLX='201' AND LENGTH(V_ZJHM)=18 THEN
      V_THIS_DATA := EXTRACT(YEAR FROM P_BGQ_Z) - TO_NUMBER(SUBSTR(V_ZJHM,7,4));
    ELSE
      V_THIS_DATA := 0;
    END IF;

    SELECT FLOOR(MONTHS_BETWEEN(P_BGQ_Z,MAX(NVL(S.LRRQ,T.SWDJ_DATE))))
      INTO V_LAST_DATA
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
      LEFT JOIN TL_TSSH.CKTS_DJ_BGDJMX S ON S.DJXH=T.DJXH_JS AND S.LRRQ<=P_BGQ_Z
     WHERE T.DJXH_JS=P_DJXH;

    IF V_THIS_DATA<=0 THEN
      V_ZB_VAL := NULL;
    ELSIF V_THIS_DATA<VAL1 THEN
      V_ZB_VAL := 1;
    ELSIF V_THIS_DATA>VAL2 AND V_LAST_DATA<36 THEN
      V_ZB_VAL := 1;
    ELSE
      V_ZB_VAL := 0;
    END IF;

    V_PARAMS := '[d]法定代表人证件号码=' || V_ZJHM || '|经营期限=' || V_LAST_DATA || '个月';
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10104' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10104',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10104';
  END IF;
  COMMIT;

  RETURN;
END;
/
