CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W30108
/*
 * 敏感口岸数量
 * ZB_VAL：敏感口岸数量
 */
(
  P_BGQID   IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    V_ZB_VAL := 0;
    FOR CUR_SPDM IN (SELECT T.KA_DM,DM.CKKA_MC,T.CKEUSD
                       FROM TL_TSSH.JKGL_DATA_TJ_ZBU_CKKA T
                       LEFT JOIN TL_TSSH.JCFX_DM_CKKA DM ON DM.CKKA_DM=T.KA_DM
                      WHERE T.BGQID=P_BGQID
                        AND T.MGBZ='1')
    LOOP
      V_ZB_VAL := V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        V_PARAMS := '[d]口岸代码=' || CUR_SPDM.KA_DM || '（' || CUR_SPDM.CKKA_MC ||'），出口额=' || CUR_SPDM.CKEUSD;
      ELSIF V_ZB_VAL<=20 THEN
        V_PARAMS := V_PARAMS || '|口岸代码=' || CUR_SPDM.KA_DM || '（' || CUR_SPDM.CKKA_MC ||'），出口额=' || CUR_SPDM.CKEUSD;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      V_PARAMS := V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30108' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W30108',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30108';
  END IF;
  COMMIT;

  RETURN;
END;
/
