CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W20203
/*
 * 综合换汇成本异常=进项发票总金额/出口额人民币
 * ZB_VAL：TL_TSSH.JKGL_DATA_TJ_ZBU.TS_HHCB
 */
(
  P_BGQID   IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT T.TS_HHCB, '[d]申报退税总计税金额=' || T.TS_JSJE || '|申报退税报关单人民币销售额=' || T.TS_CKERMB
      INTO V_ZB_VAL, V_PARAMS
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID
       AND T.TS_HHCB>0;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20203' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W20203',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20203';
  END IF;
  COMMIT;

  RETURN;
END;
/
