CREATE OR REPLACE PROCEDURE PRO_FXGL_DATA_STZCANDGJSB
/*
 * 生产企业出口外购货物风险模型、购进设备开1%3%普票风险模型
 */
AS
BEGIN
  -- 1、先运行zj_bjts用户下的PRO_DEAL_FXGL_STZCANDGJSB存储过程，获取FXGL_DATA_STZC企业信息
  -- 2、提取sbtscke>100000的数据到本地，目前有29961户
  -- 3、调用ETL抽取进销项发票数据到FXGL_DATA_STZC_FPXX表中
  -- 数据抽取逻辑如下
/*
  INSERT INTO FXGL_DATA_STZC_FPXX
         (FPHM,XH,KPRQ,XSFNSRSBH,XHFDJXH,GMFNSRSBH,GMFDJXH,SPHFWSSFLHBBM,XMMC,FPSPDJ,FPSPSL,JE,SL_1,SE,BZ)
  SELECT HW.FPHM,HW.XH,HW.KPRQ,
         FP.XSFNSRSBH,FP.XHFDJXH,
         FP.GMFNSRSBH,FP.GMFDJXH,
         HW.SPHFWSSFLHBBM,HW.XMMC,
         HW.FPSPDJ,HW.FPSPSL,HW.JE,HW.SL_1,HW.SE,
         FP.BZ
    FROM DZFP_KPYW_FPJCXXB FP
   INNER JOIN DZFP_KPYW_FPMXXXB HW
      ON HW.FPHM=FP.FPHM
   WHERE FP.KPRQ >= DATE'2024-01-01' AND FP.KPRQ < DATE'2026-01-01'
     --AND FP.FPZT_DM<>'2'
     AND NOT REGEXP_LIKE(HW.XMMC, '原价合计|折扣额合计'
     AND (FP.XSFNSRSBH IN (SELECT NSRSBH FROM FXGL_DATA_STZC) OR
         FP.GMFNSRSBH IN (SELECT NSRSBH FROM FXGL_DATA_STZC));
  COMMIT;
*/
  -- 4、调用ETL抽取采购设备的进项发票（包括数电、专票、普票）数据到FXGL_DATA_STZC_FPXX_GJ表中
  -- 数据抽取逻辑如下
/*
  INSERT INTO FXGL_DATA_STZC_FPXX_GJ
         (FPHM,XH,KPRQ,XSFNSRSBH,XHFDJXH,GMFNSRSBH,GMFDJXH,SPHFWSSFLHBBM,XMMC,FPSPDJ,FPSPSL,JE,SL_1,SE,BZ,FPLB)
  SELECT HW.FPHM,HW.XH,HW.KPRQ,
         FP.XSFNSRSBH,FP.XHFDJXH,
         FP.GMFNSRSBH,FP.GMFDJXH,
         HW.SPHFWSSFLHBBM,HW.XMMC,
         HW.FPSPDJ,HW.FPSPSL,HW.JE,HW.SL_1,HW.SE,
         FP.BZ,FPLB -- 底帐库根据专票、普票的对应表设置，数电票需要根据发票的某个字段区分，分别设置为“专票、普票”
    FROM DZFP_KPYW_FPJCXXB FP
   INNER JOIN DZFP_KPYW_FPMXXXB HW
      ON HW.FPHM=FP.FPHM
   WHERE FP.GMFNSRSBH IN (SELECT NSRSBH FROM FXGL_DATA_STZC)
     --AND FP.FPZT_DM<>'2'
     AND FP.SPHFWSSFLHBBM LIKE '109%' -- 购进设备
     AND (CASE WHEN NVL(HW.FPSPDJ,'0')='0' OR UPPER(HW.FPSPDJ)='NULL' THEN HW.JE ELSE TO_NUMBER(HW.FPSPDJ) END)>5000; -- 单价5000以上
  COMMIT;
*/

  EXECUTE IMMEDIATE 'TRUNCATE TABLE FXGL_DATA_STZC_CKMX';
  COMMIT;

  -- 出口发票按商品编码、名称分组
  INSERT INTO FXGL_DATA_STZC_CKMX(DJXH,SPHFWSSFLHBBM,XMMC,JE)
  SELECT FP.XHFDJXH,FP.SPHFWSSFLHBBM,FP.XMMC,SUM(FP.JE)
    FROM FXGL_DATA_STZC_FPXX FP
   WHERE FP.XHFDJXH IS NOT NULL
     AND FP.SE = 0 --出口业务，全省除绍兴，其他大部分开免税，因此用税额判断
     AND REGEXP_LIKE(FP.BZ,'出口业务')
   GROUP BY FP.XHFDJXH,FP.SPHFWSSFLHBBM,FP.XMMC;
  COMMIT;

  EXECUTE IMMEDIATE 'TRUNCATE TABLE FXGL_DATA_STZC_JXMX';
  COMMIT;

  -- 进货发票按商品编码、名称分组
  INSERT INTO FXGL_DATA_STZC_CKMX(DJXH,SPHFWSSFLHBBM,XMMC,JE)
  SELECT FP.GMFDJXH,FP.SPHFWSSFLHBBM,FP.XMMC,SUM(FP.JE)
    FROM FXGL_DATA_STZC_FPXX FP
   WHERE FP.GMFDJXH IS NOT NULL
   GROUP BY FP.GMFDJXH,FP.SPHFWSSFLHBBM,FP.XMMC;
  COMMIT;

  EXECUTE IMMEDIATE 'TRUNCATE TABLE FXGL_DATA_STZC_YSWG_BM';
  COMMIT;

  -- 按商品编码分组疑似外购比较
  INSERT INTO FXGL_DATA_STZC_YSWG_BM(DJXH,SPHFWSSFLHBBM,CKJE,JHJE,YSWG_BFB,YSWG_CKJE)
  SELECT A.DJXH,A.SPHFWSSFLHBBM,A.CKJE,B.JHJE,
         CASE 
           WHEN A.CKJE>0 AND A.CKJE<B.JHJE THEN 100
           WHEN A.CKJE>0 AND A.CKJE>=B.JHJE THEN ROUND(B.JHJE*100/A.CKJE,2)
           ELSE 0
         END AS YSWG_BFB,
         CASE 
           WHEN A.CKJE>0 AND A.CKJE<B.JHJE THEN A.CKJE
           WHEN A.CKJE>0 AND A.CKJE>=B.JHJE THEN B.JHJE
           ELSE 0
         END AS YSWG_CKJE
    FROM (SELECT DJXH,SPHFWSSFLHBBM,SUM(JE) AS CKJE FROM FXGL_DATA_STZC_CKMX GROUP BY DJXH,SPHFWSSFLHBBM) A
   INNER JOIN (SELECT DJXH,SPHFWSSFLHBBM,SUM(JE) AS JHJE FROM FXGL_DATA_STZC_JXMX GROUP BY DJXH,SPHFWSSFLHBBM) B
      ON A.DJXH=B.DJXH AND A.SPHFWSSFLHBBM=B.SPHFWSSFLHBBM;
  COMMIT;

  EXECUTE IMMEDIATE 'TRUNCATE TABLE FXGL_DATA_STZC_YSWG_MC';
  COMMIT;

  -- 按商品编码、名称分组疑似外购比较
  INSERT INTO FXGL_DATA_STZC_YSWG_MC(DJXH,SPHFWSSFLHBBM,XMMC,CKJE,JHJE,YSWG_BFB,YSWG_CKJE)
  SELECT A.DJXH,A.SPHFWSSFLHBBM,A.XMMC,A.CKJE,B.JHJE,
         CASE 
           WHEN A.CKJE>0 AND A.CKJE<B.JHJE THEN 100
           WHEN A.CKJE>0 AND A.CKJE>=B.JHJE THEN ROUND(B.JHJE*100/A.CKJE,2)
           ELSE 0
         END AS YSWG_BFB,
         CASE 
           WHEN A.CKJE>0 AND A.CKJE<B.JHJE THEN A.CKJE
           WHEN A.CKJE>0 AND A.CKJE>=B.JHJE THEN B.JHJE
           ELSE 0
         END AS YSWG_CKJE
    FROM (SELECT DJXH,SPHFWSSFLHBBM,XMMC,SUM(JE) AS CKJE FROM FXGL_DATA_STZC_CKMX GROUP BY DJXH,SPHFWSSFLHBBM,XMMC) A
   INNER JOIN (SELECT DJXH,SPHFWSSFLHBBM,XMMC,SUM(JE) AS JHJE FROM FXGL_DATA_STZC_JXMX GROUP BY DJXH,SPHFWSSFLHBBM,XMMC) B
      ON A.DJXH=B.DJXH AND A.SPHFWSSFLHBBM=B.SPHFWSSFLHBBM AND A.XMMC=B.XMMC;
  COMMIT;

  UPDATE FXGL_DATA_STZC T
     SET T.FP_CKE=(
         SELECT SUM(FP.JE)
           FROM FXGL_DATA_STZC_FPXX FP
          WHERE FP.XHFDJXH=T.DJXH
            AND FP.SE = 0 --出口业务，全省除绍兴，其他大部分开免税，因此用税额判断
            AND REGEXP_LIKE(FP.BZ,'出口业务')),
         T.FP_GJE=(
         SELECT SUM(FP.JE)
           FROM FXGL_DATA_STZC_FPXX FP
          WHERE FP.GMFDJXH=T.DJXH),
         T.YSWG_CKJE_BM=(
         SELECT SUM(YSWG_CKJE)
           FROM FXGL_DATA_STZC_YSWG_BM BM
          WHERE BM.DJXH=T.DJXH),
         T.YSWG_CKJE_MC=(
         SELECT SUM(YSWG_CKJE)
           FROM FXGL_DATA_STZC_YSWG_MC MC
          WHERE MC.DJXH=T.DJXH)
   WHERE T.ETL_BZ='1';
  COMMIT;

  UPDATE FXGL_DATA_STZC T
     SET T.YSWG_CKZB_BM = ROUND(100* T.YSWG_CKJE_BM/T.FP_CKE,2),
         T.YSWG_CKZB_MC = ROUND(100* T.YSWG_CKJE_MC/T.FP_CKE,2)
   WHERE T.ETL_BZ='1'
     AND T.FP_CKE>0;
  COMMIT;

  UPDATE FXGL_DATA_STZC T
     SET (GJSB_MINKPRQ,GJSB_ZJE,GJSB_XGM_PP,GJSB_XGM_ZP)=(
         SELECT MIN(FP.KPRQ),SUM(FP.JE),
                SUM(CASE WHEN FP.SL_1<=0.03 AND FP.FPLB='普票' THEN FP.JE ELSE 0 END),
                SUM(CASE WHEN FP.SL_1<=0.03 AND FP.FPLB='专票' THEN FP.JE ELSE 0 END)
           FROM FXGL_DATA_STZC_FPXX_GJ FP
          WHERE FP.GMFDJXH=T.DJXH)
   WHERE T.ETL_BZ='1';
  COMMIT;

  UPDATE FXGL_DATA_STZC T
     SET T.GJSB_ZB_PP = ROUND(100* T.GJSB_XGM_PP/T.GJSB_ZJE,2)
   WHERE T.ETL_BZ='1'
     AND T.GJSB_ZJE>0;
  COMMIT;

  UPDATE FXGL_DATA_STZC T
     SET T.ETL_BZ='2'
   WHERE T.ETL_BZ='1';
  COMMIT;

  EXECUTE IMMEDIATE 'TRUNCATE TABLE FXGL_DATA_STZC_FPXX';
  COMMIT;

  EXECUTE IMMEDIATE 'TRUNCATE TABLE FXGL_DATA_STZC_FPXX_GJ';
  COMMIT;

  --输出生产企业出口外购货物风险模型企业清单
/*
  SELECT A.DJXH,
         A.NSRSBH  纳税人识别号,
         A.NSRMC  纳税人名称,
         A.ZGSWJ_DM  主管税务机关编码,
         A.ZGSWJ_MC  主管税务机关名称,
         A.HY_DM  行业代码,
         A.HY_MC  行业名称,
         TO_CHAR(A.BARQ,'yyyy-mm-dd')  退税备案日期,
         A.FP_CKE  出口发票总金额,
         A.FP_GJE  购进发票总金额,
         A.SBTS_CKE  申报退税出口额,
         A.SBTS_WGCKE  申报退税外购出口额,
         A.YSWG_CKJE_BM  疑似外购出口金额_编码,
         A.YSWG_CKZB_BM  疑似外购出口占比_编码,
         A.YSWG_CKJE_MC  疑似外购出口金额_品名,
         A.YSWG_CKZB_MC  疑似外购出口占比_品名
    FROM FXGL_DATA_STZC A
   WHERE A.FP_CKE>0
     AND A.YSWG_CKZB_BM>30
     AND A.YSWG_CKJE_MC>100000;
*/
  --输出生产企业购进设备开1%3%普票风险模型企业清单
/*
  SELECT A.DJXH,
         A.NSRSBH  纳税人识别号,
         A.NSRMC  纳税人名称,
         A.ZGSWJ_DM  主管税务机关编码,
         A.ZGSWJ_MC  主管税务机关名称,
         A.HY_DM  行业代码,
         A.HY_MC  行业名称,
         TO_CHAR(A.BARQ,'yyyy-mm-dd')  退税备案日期,
         TO_CHAR(A.GJSB_MINKPRQ,'yyyy-mm-dd')  购进设备统计期起,
         A.GJSB_ZJE  购进设备总金额,
         A.GJSB_XGM_PP  其中开具小规模普票金额,
         A.GJSB_XGM_ZP  其中开具小规模专票金额,
         A.GJSB_ZB_PP  开具小规模普票占比
    FROM FXGL_DATA_STZC A
   WHERE A.GJSB_ZJE>0
     AND A.GJSB_XGM_PP>100000;
*/
END;
/
