CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S10101
/*
 * 企业经营稳定性
 * ZB_VAL：最后一次变更法人代表时间（未变更按税务登记时间）至报告期止月数
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER,
  P_BGQ_Z   IN DATE
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT ROUND(MONTHS_BETWEEN(P_BGQ_Z,MAX(TRUNC(NVL(S.LRRQ,T.SWDJ_DATE),'MM')))),
           '[d]报告期截止日期=' || TO_CHAR(P_BGQ_Z,'YYYYMMDD') || 
           '|税务登记日期=' || TO_CHAR(MAX(T.SWDJ_DATE),'YYYYMMDD') ||
           '|最近变更法人代表日期=' || TO_CHAR(MAX(S.LRRQ),'YYYYMMDD')
      INTO V_ZB_VAL, V_PARAMS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
      LEFT JOIN TL_TSSH.CKTS_DJ_BGDJMX S ON S.DJXH=T.DJXH_JS AND S.BGQNR<>S.BGHNR AND S.LRRQ<=P_BGQ_Z
     WHERE T.DJXH_JS=P_DJXH;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10101' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10101',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10101';
  END IF;
  COMMIT;

  RETURN;
END;
/
