CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W10401
/*
 * 企业四员是否来自敏感地区
 * ZB_VAL：存在来自敏感地区的成员，返回1
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_FRDBRZJHM  VARCHAR(100);
  V_CWFZRZJHM  VARCHAR(100);
  V_BSYZJHM    VARCHAR(100);
  V_PARAMS     VARCHAR(1000);
BEGIN
  BEGIN
    SELECT FRDB_ZJHM, '[d]法定代表人证件号码=' || FRDB_ZJHM
      INTO V_FRDBRZJHM, V_PARAMS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
     WHERE T.DJXH_JS=P_DJXH;

    SELECT T1.CWFZRSFZJHM
      INTO V_CWFZRZJHM
      FROM TL_BJTS.GS_DJ_CKTMSDAB T1
     WHERE T1.CPCODE=TO_CHAR(P_DJXH);
    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_GY_FXDQ_SWJG S1
     WHERE (S1.XZQH_DM=SUBSTR(V_CWFZRZJHM,1,6) OR S1.XZQH_DM=SUBSTR(V_CWFZRZJHM,1,4))
       AND S1.QYBZ='Y'
       AND LENGTH(V_CWFZRZJHM) IN (15,18);
    V_PARAMS := V_PARAMS || '|财务负责人证件号码=' || V_CWFZRZJHM;
    IF V_ROWS>0 THEN
      V_PARAMS := V_PARAMS || '，是';
    ELSE
      V_PARAMS := V_PARAMS || '，否';
    END IF;

    SELECT T1.BSRSFZJHM
      INTO V_BSYZJHM
      FROM TL_BJTS.GS_DJ_CKTMSDAB T1
     WHERE T1.CPCODE=TO_CHAR(P_DJXH);
    SELECT COUNT(1)
      INTO V_ZB_VAL
      FROM TL_TSSH.JKGL_GY_FXDQ_SWJG S1
     WHERE (S1.XZQH_DM=SUBSTR(V_BSYZJHM,1,6) OR S1.XZQH_DM=SUBSTR(V_BSYZJHM,1,4))
       AND S1.QYBZ='Y'
       AND LENGTH(V_BSYZJHM) IN (15,18);
    V_PARAMS := V_PARAMS || '|办税员证件号码=' || V_BSYZJHM;
    IF V_ZB_VAL>0 THEN
      V_PARAMS := V_PARAMS || '，是';
    ELSE
      V_PARAMS := V_PARAMS || '，否';
    END IF;

    IF (V_ZB_VAL>0 AND V_FRDBRZJHM<>V_BSYZJHM) OR (V_ROWS>0 AND V_FRDBRZJHM<>V_CWFZRZJHM) THEN
      V_ZB_VAL := 1;
    ELSE
      V_ZB_VAL :=0;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10401' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W10401',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10401';
  END IF;
  COMMIT;

  RETURN;
END;
/
