CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S50301
/*
 * 出口企业还原税负率
 * ZB_VAL：还原税负率
 */
(
  P_BGQID   IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT S.CW_HYSFL,
           '[d]增值税全部销售额=' ||T.ZZS_XSE_QB || '|期末存货=' || T.ZC_CH_QM || '|期初存货=' || T.ZC_CH_QC ||
           '|增值税进项税额=' || T.ZZS_JXSE || '|增值税进项税额转出=' || T.ZZS_JXSEZC
      INTO V_ZB_VAL, V_PARAMS
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     INNER JOIN TL_TSSH.JKGL_DATA_TJ_ZBU_KZ S ON S.BGQID=T.BGQID
     WHERE T.BGQID=P_BGQID;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S50301' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S50301',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S50301';
  END IF;
  COMMIT;

  RETURN;
END;
/
