CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W40101
/*
 * 供货企业是否来自预警地区
 * ZB_VAL：供货企业汇总_供货金额>{参数1：50万} 且
 *         供货企业行政区划属于所属税务机关设置的风险地区的个数/报告期_供货企业数量>{参数2：50%}
 */
(
  P_BGQID   IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_TOTAL_NUM  NUMBER(18,2);
  V_TOTAL_JE   NUMBER(18,2);
  VAL1         NUMBER(18,2);    --参数1
  VAL2         NUMBER(18,2);    --参数2
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40101_FXGHQY_JE';
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40101_FXGHQY_SL_ZB';

    SELECT T.TS_GHS_NUM, T.TS_JSJE
      INTO V_TOTAL_NUM, V_TOTAL_JE
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    IF V_TOTAL_NUM<1 OR V_TOTAL_JE<=0 THEN
      V_ZB_VAL := NULL;
    ELSE
      SELECT COUNT(1), NVL(SUM(T.JHJE),0)
        INTO V_THIS_DATA, V_LAST_DATA
        FROM TL_TSSH.JKGL_DATA_TJ_ZBU_TSGH T
       WHERE T.BGQID=P_BGQID
         AND EXISTS (SELECT 1
                       FROM TL_TSSH.JKGL_GY_FXDQ_SWJG S
                      WHERE S.XZQH_DM= CASE WHEN LENGTH(T.GHFSH)=15
                                            THEN SUBSTR(T.GHFSH,1,LENGTH(S.XZQH_DM))
                                            ELSE SUBSTR(T.GHFSH,3,LENGTH(S.XZQH_DM)) END
                        AND S.QYBZ='Y');

      V_PARAMS := '[d]报告期供货企业总数=' || V_TOTAL_NUM || '|总计税金额=' || V_TOTAL_JE
               || '|风险地区供货企业数' || V_THIS_DATA || '|风险地区供货计税金额' || V_LAST_DATA;
      IF V_LAST_DATA>=VAL1 AND V_THIS_DATA >= VAL2*V_TOTAL_NUM THEN
        V_ZB_VAL:=1;
      ELSE
        V_ZB_VAL:=0;
      END IF;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40101' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W40101',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40101';
  END IF;
  COMMIT;

  RETURN;
END;
/
