CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S30301
/*
 * 口岸出口额环比=报告期该口岸出口销售额÷基期该口岸出口销售额×100%
 * ZB_VAL：出口额环比超150%的口岸个数
 */
(
  P_BGQID   IN NUMBER,
  P_JQID    IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  VAL1         NUMBER(18,2);    --参数1
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30301_KA_CKE_HB';

    V_ZB_VAL := 0;
    FOR CUR_SPDM IN (SELECT T.KA_DM,DM.CKKA_MC,T.CKEUSD,NVL(S.CKEUSD,0) AS JQCKE
                       FROM TL_TSSH.JKGL_DATA_TJ_ZBU_CKKA T
                       LEFT JOIN TL_TSSH.JKGL_DATA_TJ_ZBU_CKKA S ON S.BGQID=P_JQID AND S.KA_DM=T.KA_DM
                       LEFT JOIN TL_TSSH.JCFX_DM_CKKA DM ON DM.CKKA_DM=T.KA_DM
                      WHERE T.BGQID=P_BGQID
                        AND T.CKEUSD>=VAL1 * NVL(S.CKEUSD,0))
    LOOP
      V_ZB_VAL := V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        V_PARAMS := '[d]口岸代码=' || CUR_SPDM.KA_DM || '（' || CUR_SPDM.CKKA_MC ||'），报告期出口额=' || CUR_SPDM.CKEUSD || '，基期出口额=' || CUR_SPDM.JQCKE;
      ELSIF V_ZB_VAL<=20 THEN
        V_PARAMS := V_PARAMS || '|口岸代码=' || CUR_SPDM.KA_DM || '（' || CUR_SPDM.CKKA_MC ||'），报告期出口额=' || CUR_SPDM.CKEUSD || '，基期出口额=' || CUR_SPDM.JQCKE;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      V_PARAMS := V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30301' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30301',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30301';
  END IF;
  COMMIT;

  RETURN;
END;
/
