CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W40104
/*
 * 供货企业汇总_非正常标志的退税额合计>100万元 or
 * 供货企业汇总_非正常标志的退税额合计/报告期_退免税额>15%
 * ZB_VAL：是1，否0
 */
(
  P_BGQID   IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  VAL1         NUMBER(18,2);    --参数1
  VAL2         NUMBER(18,2);    --参数2
  V_PARAMS     VARCHAR(4000);
  V_PARAM2     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40104_FZCQYGH_TSE';
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40104_FZCQYGH_TSE_ZB';

    SELECT T.TS_TSE_SB
      INTO V_THIS_DATA
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    IF V_THIS_DATA <= 0 THEN
      V_ZB_VAL := NULL;
    ELSE
      V_ZB_VAL := 0;
      V_LAST_DATA :=0;
      V_PARAM2 := '';
      FOR CUR_SPDM IN (SELECT T.GHFSH, S.QYMC, SUM(T.TSE) AS TSE
                         FROM TL_TSSH.JKGL_DATA_TJ_ZBU_TSGH T
                        INNER JOIN TL_TSSH.JKGL_GY_GHQYXX S ON S.QYSBH=T.GHFSH
                        WHERE T.BGQID=P_BGQID AND NVL(S.NSRZT_DM,'03')='05'
                        GROUP BY T.GHFSH, S.QYMC
                        ORDER BY SUM(T.TSE) DESC)
      LOOP
        V_ZB_VAL := V_ZB_VAL +1;
        V_LAST_DATA := V_LAST_DATA + CUR_SPDM.TSE;
        IF V_ZB_VAL<=20 THEN
          V_PARAM2 := V_PARAM2 || '|非正常企业税号=' || CUR_SPDM.GHFSH || '（' || CUR_SPDM.QYMC || '），退税额=' || CUR_SPDM.TSE;
        ELSE
          V_PARAM2 := V_PARAM2 || '|...';
        END IF;
      END LOOP;
      
      V_PARAMS := '[d]报告期退免税额=' || V_THIS_DATA || '|非正常企业供货的退税额合计=' || V_LAST_DATA || V_PARAM2;
      IF V_LAST_DATA>=VAL1 OR V_LAST_DATA>=VAL2*V_THIS_DATA THEN
        V_ZB_VAL:=1;
      ELSE
        V_ZB_VAL:=0;
      END IF;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40104' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W40104',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40104';
  END IF;
  COMMIT;

  RETURN;
END;
/
