CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S10107
/*
 * 出口企业分类管理等级
 * ZB_VAL：A-1,B-2,C-3,D-4，无类别返回5
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER,
  P_BGQ_Z   IN DATE
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_PARAMS     VARCHAR(1000);
BEGIN
  BEGIN
    SELECT DECODE(B.KZXX,'A',1,'B',2,'C',3,'D',4,5),
           '[d]出口企业分类管理等级=' || B.KZXX
      INTO V_ZB_VAL, V_PARAMS
      FROM TL_BJTS.GS_DJ_CKTMSDAB A
     INNER JOIN TL_BJTS.GS_DJ_CKTMSDAB_KZ B ON A.NSRDZDAH=B.NSRDZDAH AND B.KZLX='FLGLCD' AND (P_BGQ_Z BETWEEN B.ST_DATE AND B.END_DATE)
     WHERE A.CPCODE=TO_CHAR(P_DJXH)
       AND ROWNUM=1;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10107' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10107',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10107';
  END IF;
  COMMIT;

  RETURN;
END;
/
