CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S30102
/*
 * 企业出口大单(>=10WUSD)占比
 * ZB_VAL：出口_大额报关单出口额USD / 出口_出口额USD > 80%，输出1
 */
(
  P_BGQID   IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  VAL1         NUMBER(18,2);    --参数1
  V_PARAMS     VARCHAR(1000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30102_DEBGD_CKE_ZB';

    SELECT S.CK_CKEUSD, S.CK_CKEUSD_DE
      INTO V_THIS_DATA, V_LAST_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;

    V_PARAMS := '[d]报告期出口美元销售额=' || V_THIS_DATA || '|10万美元以上大单出口额=' || V_LAST_DATA;
    IF V_THIS_DATA>0 THEN
      IF V_LAST_DATA >= V_THIS_DATA * VAL1 THEN
        V_ZB_VAL := 1;
      ELSE
        V_ZB_VAL := 0;
      END IF;
      V_PARAMS := V_PARAMS || '|占比=' || ROUND(100 * V_LAST_DATA / V_THIS_DATA,2) || '%';
    ELSE
      V_ZB_VAL := NULL;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30102' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30102',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30102';
  END IF;
  COMMIT;

  RETURN;
END;
/
