CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S10105
/*
 * 财务负责人是否兼职
 * ZB_VAL：财务负责人兼职的企业合计户数
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_ZJHM       VARCHAR2(50);
  V_BADPOINT   CHAR(1);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT T.CWFZRSFZJHM,
           '[d]财务负责人证件号码=' || T.CWFZRSFZJHM
      INTO V_ZJHM, V_PARAMS
      FROM TL_BJTS.GS_DJ_CKTMSDAB T
     WHERE T.CPCODE=TO_CHAR(P_DJXH)
       AND ROWNUM=1;

    V_ZB_VAL := 0;
    FOR CUR_SPDM IN (SELECT DISTINCT T.NSRSBH, T.NSRMC
                       FROM TL_BJTS.GS_DJ_CKTMSDAB T
                      WHERE T.CWFZRSFZJHM = V_ZJHM
                         OR T.FRZJHM = V_ZJHM)
    LOOP
      V_ZB_VAL := V_ZB_VAL +1;
      IF V_ZB_VAL<=20 THEN
        V_PARAMS := V_PARAMS || '|财务负责人所在单位税号=' || CUR_SPDM.NSRSBH || '，名称=' || CUR_SPDM.NSRMC;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      V_PARAMS := V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10105' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10105',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10105';
  END IF;
  COMMIT;

  RETURN;
END;
/
