CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S10108
/*
 * 布尔，报告期内是否变更法人代表
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER,
  P_BGQ_Q   IN DATE,
  P_BGQ_Z   IN DATE
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT '[d]变更日期=' || TO_CHAR(LRRQ,'YYYYMMDD') || '|变更前内容=' || BGQNR || '|变更后内容=' || BGHNR
      INTO V_PARAMS
      FROM (SELECT *
              FROM TL_TSSH.CKTS_DJ_BGDJMX T
             WHERE T.DJXH=P_DJXH AND T.LRRQ>=P_BGQ_Q AND T.LRRQ<P_BGQ_Z+1
               AND T.BGQNR<>T.BGHNR
             ORDER BY T.LRRQ DESC)
     WHERE ROWNUM=1;
     IF V_PARAMS IS NOT NULL THEN
       V_ZB_VAL:=1;
     ELSE
       V_ZB_VAL:=0;
     END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := 0;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10108' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10108',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10108';
  END IF;
  COMMIT;

  RETURN;
END;
/
