CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S10102
/*
 * 出口企业法定代表人是否为企业实际控制人
 * ZB_VAL：出口企业填报JKGL_ZLCJ_JGB，以填报结果为准，一致为0，不一致为1
 *         出口企业未填报JKGL_ZLCJ_JGB，查看股东占股比例，小于10%为1，否则为0
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,6);
  V_PARAMS     VARCHAR(1000);
BEGIN
  BEGIN
    SELECT CASE WHEN T.FDDBR_XM=T.SJJYR_XM THEN 0 ELSE 1 END,
           '[d]法定代表人=' || T.FDDBR_XM || '|实际控制人=' || T.SJJYR_XM
      INTO V_ZB_VAL, V_PARAMS
      FROM TL_TSSH.JKGL_ZLCJ_JGB T
     WHERE T.DJXH=P_DJXH;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    SELECT NVL(T.FDDBR_CGBL,0),
           '[d]法定代表人=' || T.FDDBRMC || '|持股比例=' || NVL(T.FDDBR_CGBL,0) || '%'
      INTO V_THIS_DATA, V_PARAMS
      FROM TL_BJTS.GS_DJ_CKTMSDAB T
     WHERE T.CPCODE=TO_CHAR(P_DJXH);
    IF V_THIS_DATA<10 THEN
      V_ZB_VAL := 1;
    ELSE
      V_ZB_VAL := 0;
    END IF;
  END IF;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10102' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10102',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10102';
  END IF;
  COMMIT;

  RETURN;
END;
/
