CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S30204
/*
 * 商品单价差异率=（商品_出口单价-全省商品平均出口单价）/全省商品平均出口单价
 * ZB_VAL：商品出口额超1WUSD且出口单价与全省平均差异超50%的商品个数
 */
(
  P_BGQID   IN NUMBER,
  P_QSPJID  IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  VAL1         NUMBER(18,2);    --参数1
  VAL2         NUMBER(18,2);    --参数2
  VAL3         NUMBER(18,2);    --参数3
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30204_SP_DJ_BL_LOWER';
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30204_SP_DJ_BL_UPPER';
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL3
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S30204_SP_CKE_JE';

    V_ZB_VAL := 0;
    FOR CUR_SPDM IN (SELECT T.SP8_DM, DM.CKSP_MC,T.CKEUSD,T.CKDJ,S.CKDJ AS PJDJ
                       FROM TL_TSSH.JKGL_DATA_TJ_ZBU_CKSP T
                      INNER JOIN TL_TSSH.JKGL_QSPJ_CKSP S ON S.BGQID=P_QSPJID AND S.SP8_DM=T.SP8_DM
                       LEFT JOIN TL_TSSH.JCFX_DM_CKSPTREE DM ON DM.CKSP_DM=T.SP8_DM AND DM.CKSP_JC='4'
                      WHERE T.BGQID=P_BGQID
                        AND T.CKEUSD>=VAL3
                        AND (T.CKDJ>=VAL2 * S.CKDJ OR T.CKDJ<=VAL1 * S.CKDJ))
    LOOP
      V_ZB_VAL := V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        V_PARAMS := '[d]商品代码=' || CUR_SPDM.SP8_DM || '（' || CUR_SPDM.CKSP_MC ||'），报告期出口额=' || CUR_SPDM.CKEUSD || '，出口单价=' || CUR_SPDM.CKDJ || '，全省平均单价=' || CUR_SPDM.PJDJ;
      ELSIF V_ZB_VAL<=20 THEN
        V_PARAMS := V_PARAMS || '|商品代码=' || CUR_SPDM.SP8_DM || '（' || CUR_SPDM.CKSP_MC ||'），报告期出口额=' || CUR_SPDM.CKEUSD || '，出口单价=' || CUR_SPDM.CKDJ || '，全省平均单价=' || CUR_SPDM.PJDJ;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      V_PARAMS := V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30204' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S30204',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S30204';
  END IF;
  COMMIT;

  RETURN;
END;
/
