CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W20201
/*
 * (报关单每单的每美元利润<本企业每美元利润中位数*下限%
 * or 报关单每单的每美元利润>本企业每美元利润中位数*上限%）的出口额合计/报告期_出口额>80%
 * ZB_VAL：
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER,
  P_BGQ_Q   IN DATE,
  P_BGQ_Z   IN DATE
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_MEDIAN     NUMBER(18,3);
  V_MAX        NUMBER(18,3);
  V_MIN        NUMBER(18,3);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT SUM(CKEUSD), MEDIAN(MMYLR), MAX(MMYLR), MIN(MMYLR)
      INTO V_THIS_DATA, V_MEDIAN, V_MAX, V_MIN
      FROM (SELECT SUBSTR(T.CKBGDH,1,18) AS CKBGDH, SUM(T.MYLAJ) AS CKEUSD, SUM(T.RMBLAJ) AS CKERMB, SUM(T.JSJE) AS JHJE,
                   CASE WHEN SUM(T.MYLAJ)<=0 THEN 0 ELSE ROUND((SUM(T.RMBLAJ) - SUM(T.JSJE)) / SUM(T.MYLAJ),2) END AS MMYLR
              FROM TL_TSSH.JCFX_DATA_TSSBMX T
             WHERE T.DJXH=P_DJXH
               AND T.SBRQ>=P_BGQ_Q AND T.SBRQ<P_BGQ_Z+1
             GROUP BY SUBSTR(T.CKBGDH,1,18)) TT;

    V_PARAMS := '[d]报告期出口额=' || V_THIS_DATA || '|本企业每美元利润中位数=' || V_MEDIAN ||
                '|本企业每美元利润最大值=' || V_MAX || '|本企业每美元利润最小值=' || V_MIN;
    V_MAX := (V_MAX + V_MEDIAN) /2;
    V_MIN := (V_MIN + V_MEDIAN) /2;
    V_PARAMS := V_PARAMS || '|按大于上限=' || V_MAX || '|或小于下限=' || V_MIN;

    SELECT SUM(CKEUSD)
      INTO V_LAST_DATA
      FROM (SELECT SUBSTR(T.CKBGDH,1,18) AS CKBGDH, SUM(T.MYLAJ) AS CKEUSD, SUM(T.RMBLAJ) AS CKERMB, SUM(T.JSJE) AS JHJE,
                   CASE WHEN SUM(T.MYLAJ)<=0 THEN 0 ELSE ROUND((SUM(T.RMBLAJ) - SUM(T.JSJE)) / SUM(T.MYLAJ),2) END AS MMYLR
              FROM TL_TSSH.JCFX_DATA_TSSBMX T
             WHERE T.DJXH=P_DJXH
               AND T.SBRQ>=P_BGQ_Q AND T.SBRQ<P_BGQ_Z+1
             GROUP BY SUBSTR(T.CKBGDH,1,18)) TT
     WHERE MMYLR>V_MAX OR MMYLR<V_MIN;
    V_PARAMS := V_PARAMS || '|与中位数偏离较大的出口额=' || V_LAST_DATA;

    IF V_THIS_DATA<=0 OR V_LAST_DATA<0 THEN
      V_ZB_VAL := NULL;
    ELSE
      V_ZB_VAL:=ROUND(100 * V_LAST_DATA / V_THIS_DATA, 2);
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20201' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W20201',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W20201';
  END IF;
  COMMIT;

  RETURN;
END;
/
