CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S10204
/*
 * 销售额与电费支出合理关系，取统计期往前一年的数据
 * ZB_VAL：报告期内电费支出小于等于5万元且外销收入减委托加工费用大于700W以上，返回1
 */
(
  P_BGQID   IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  VAL1         NUMBER(18,2);    --参数1
  VAL2         NUMBER(18,2);    --参数2
  V_PARAMS     VARCHAR(1000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S10204_CKXSEJWTJG';
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_S10204_DFZC';

    SELECT S.ZZS_XSE_MDT + S.ZZS_XSE_MS - S.DZ_WTJG, S.DZ_DFJE_ZC - S.DZ_DFJE_SR
      INTO V_THIS_DATA, V_LAST_DATA
      FROM JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;

    V_PARAMS := '[d]报告期出口销售额(扣除委托加工费)=' || V_THIS_DATA || '|报告期电费支出=' || V_LAST_DATA;
    IF V_THIS_DATA>0 AND V_LAST_DATA>=0 THEN
      IF V_THIS_DATA>=VAL1 AND V_LAST_DATA<=VAL2 THEN
        V_ZB_VAL := 1;
      ELSE
        V_ZB_VAL := 0;
      END IF;
    ELSE
      V_ZB_VAL := NULL;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10204' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S10204',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S10204';
  END IF;
  COMMIT;

  RETURN;
END;
/
