CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W50501
/*
 * 企业销售费用与企业营业收入的比值是否异常
 * ZB_VAL：企业销售费用与企业营业收入的比值
 */
(
  P_BGQID   IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT T.LR_YYSR, T.LR_XSFY,
           '[d]营业收入=' ||T.LR_YYSR || '|销售费用=' || T.LR_XSFY
      INTO V_THIS_DATA, V_LAST_DATA, V_PARAMS
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    V_ZB_VAL := ROUND(100 * V_LAST_DATA / V_THIS_DATA, 2);
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50501' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W50501',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W50501';
  END IF;
  COMMIT;

  RETURN;
END;
/
