CREATE OR REPLACE PROCEDURE PRO_JKGL_JKM_MAIN(
  P_DJXH  IN VARCHAR2,
  P_SWJG  IN VARCHAR2
) AS
  V_COUNT NUMBER(10);
  V_DJXH VARCHAR2(20);
  CURSOR CUR_QY(A_DJXH NUMBER, A_SWJG VARCHAR2) IS
      SELECT DJ.CPCODE, DECODE(DJ.JSMODE,'1','1','2') AS TSJSFS, DJ.SWJGDM
        FROM JKGL_DATA_QYJKM_JGB T 
       INNER JOIN GLXT_BB_SHXT_DJXX DJ ON DJ.CPCODE=T.DJXH
       WHERE (A_DJXH IS NULL OR T.DJXH=A_DJXH) 
         AND (A_SWJG IS NULL OR DJ.SWJGDM=A_SWJG)
         AND EXISTS (SELECT 1 
                       FROM JKGL_DATA_ZB_JGB Z 
                      WHERE T.DJXH=Z.DJXH AND Z.ZB_ID IN ('W10101','S10101'));
BEGIN
  V_COUNT:=0;
  DBMS_OUTPUT.PUT_LINE('【健康码】刷新开始，时间:'||TO_CHAR(SYSDATE,'yyyymmdd hh24:mi:ss'));

  --开始循环
  BEGIN
    FOR CUR IN CUR_QY(P_DJXH, P_SWJG)
    LOOP
      V_COUNT :=V_COUNT+1;
      V_DJXH := CUR.CPCODE;

      --对指标进行异常判定和赋分
      TL_TSSH.PRO_JKGL_JKM_ZB_YCFF(V_DJXH,CUR.TSJSFS,CUR.SWJGDM);

      --对指标进行异常判定和赋分
      TL_TSSH.PRO_JKGL_JKM_COMPUTE(V_DJXH,CUR.TSJSFS,CUR.SWJGDM);


    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('【健康码】刷新异常:'||SQLCODE||SQLERRM);
      DBMS_OUTPUT.PUT_LINE('【异常企业】-'||V_COUNT||'-'||V_DJXH);
      RETURN;
  END;

  DBMS_OUTPUT.PUT_LINE('【健康码】刷新结束，时间:'||TO_CHAR(SYSDATE,'yyyymmdd hh24:mi:ss'));
  DBMS_OUTPUT.PUT_LINE('【健康码】刷新户数='||V_COUNT);

  RETURN;
END PRO_JKGL_JKM_MAIN;
/
