CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W30201
/*
 * 出口额过高且同比增长较快（首次申报不晚于上月的前一年年初）
 * ZB_VAL：出口额USD>100万美元,年度报告期增幅>50%
 */
(
  P_BGQID   IN NUMBER,
  P_JQID    IN NUMBER,
  P_DJXH    IN NUMBER,
  P_BGQ_Z   IN DATE,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_SCCKYF     NUMBER(18,2);
  VAL1         NUMBER(18,2);    --参数1
  VAL2         NUMBER(18,2);    --参数2
  V_PARAMS     VARCHAR(1000);
BEGIN
  BEGIN
    SELECT MONTHS_BETWEEN(P_BGQ_Z,NVL(A.SCCKRQ,SYSDATE)),'[d]企业首笔出口日期：'||TO_CHAR(A.SCCKRQ,'YYYYMMDD')
      INTO V_SCCKYF, V_PARAMS
      FROM TL_BJTS.GS_DJ_CKTMSDAB A
     WHERE A.CPCODE=TO_CHAR(P_DJXH)
       AND ROWNUM=1;
    IF V_SCCKYF<12 THEN
      V_ZB_VAL := NULL;
    ELSE
      SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
        INTO VAL1
        FROM JKGL_PZ_ZB_CS T
        LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
       WHERE T.CSBM='ZC_W30201_CKMYN_CKE_JE';
      SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
        INTO VAL2
        FROM JKGL_PZ_ZB_CS T
        LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
       WHERE T.CSBM='ZC_W30201_CKMYN_CKE_HB';

      SELECT S.CK_CKEUSD
        INTO V_THIS_DATA
        FROM TL_TSSH.JKGL_DATA_TJ_ZBU S
       WHERE S.BGQID=P_BGQID;
      SELECT S.CK_CKEUSD
        INTO V_LAST_DATA
        FROM TL_TSSH.JKGL_DATA_TJ_ZBU S
       WHERE S.BGQID=P_JQID;

      V_PARAMS := V_PARAMS || '|报告期出口销售额=' || V_THIS_DATA || '|基期出口销售额=' || V_LAST_DATA;
      IF V_THIS_DATA>0 AND V_LAST_DATA>0 THEN
        IF V_THIS_DATA>=VAL2 AND V_THIS_DATA>=V_LAST_DATA * VAL1 THEN
          V_ZB_VAL := 1;
        ELSE
          V_ZB_VAL := 0;
        END IF;
        V_PARAMS := V_PARAMS || '|环比=' || ROUND(100 * V_THIS_DATA / V_LAST_DATA,2) || '%';
      ELSE
        V_ZB_VAL := 0;
      END IF;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30201' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W30201',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30201';
  END IF;
  COMMIT;

  RETURN;
END;
/
