CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W40301
/*
 * 上游供货企业涉及贵金属
 * ZB_VAL：报告期进货单位涉及贵金属企业数量
 */
(
  P_BGQID   IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
BEGIN
  BEGIN
    SELECT COUNT(1)
      INTO V_ZB_VAL
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU_DZSPJX T
     WHERE T.BGQID=P_BGQID
       AND T.SPSM LIKE '1080311%';

  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40301' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT)
           VALUES(P_BGQID,'W40301',V_ZB_VAL,V_BADPOINT);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40301';
  END IF;
  COMMIT;

  RETURN;
END;
/
