CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W10201
/*
 * 是否存在多个企业共用一个经营地址的情况
 * ZB_VAL：出口企业经营地址登记企业数量
 */
(
  P_BGQID   IN NUMBER,
  P_DJXH    IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_ADDRESS    VARCHAR(1000);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT S.ADDRESS_JY,
           '[d]企业经营地址=' || S.ADDRESS_JY || '，该地址登记企业：'
      INTO V_ADDRESS, V_PARAMS
      FROM TL_TSSH.GLXT_BB_SHXT_DJXX S
     WHERE S.DJXH_JS=P_DJXH
       AND ROWNUM=1;

    V_ZB_VAL := 0;
    FOR CUR_SPDM IN (SELECT T.NSRDJNO, T.NSRMC
                       FROM TL_TSSH.GLXT_BB_SHXT_DJXX T
                      WHERE T.ADDRESS_JY = V_ADDRESS)
    LOOP
      V_ZB_VAL := V_ZB_VAL +1;
      IF V_ZB_VAL<=20 THEN
        V_PARAMS := V_PARAMS || '|税号=' || CUR_SPDM.NSRDJNO || '，名称=' ||  CUR_SPDM.NSRMC ;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      V_PARAMS := V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10201' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W10201',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W10201';
  END IF;
  COMMIT;

  RETURN;
END;
/
