CREATE OR REPLACE PROCEDURE PRO_FXGL_COMPUTE_MAIN
/*
 * 态势感知平台——风险管理——日常监管指标
 * 自动扫描主程序
 */
AS
BEGIN
  FOR LSF_SWJG IN (SELECT SWJG_DM FROM TL_ADMIN.DM_SWJG WHERE TSJG_BZ='1' AND QYBZ='Y' AND YXWS=7 ORDER BY SWJG_DM) LOOP
    PRO_FXGL_COMPUTE_C01001(LSF_SWJG.SWJG_DM,NULL,NULL);
    PRO_FXGL_COMPUTE_C02001(LSF_SWJG.SWJG_DM,NULL,NULL);
    PRO_FXGL_COMPUTE_C02002(LSF_SWJG.SWJG_DM,NULL,NULL);
    PRO_FXGL_COMPUTE_C02003(LSF_SWJG.SWJG_DM,NULL,NULL);
    PRO_FXGL_COMPUTE_C02004(LSF_SWJG.SWJG_DM,NULL,NULL);
    PRO_FXGL_COMPUTE_C02005(LSF_SWJG.SWJG_DM,NULL,NULL);
    PRO_FXGL_COMPUTE_C03001(LSF_SWJG.SWJG_DM,NULL,NULL);
    PRO_FXGL_COMPUTE_C04001(LSF_SWJG.SWJG_DM,NULL,NULL);
    PRO_FXGL_COMPUTE_C05001(LSF_SWJG.SWJG_DM,NULL,NULL);
    PRO_FXGL_COMPUTE_C06001(LSF_SWJG.SWJG_DM,NULL,NULL);
  END LOOP;

   PRO_FXGL_COMPUTE_C07001('13310000000',NULL,NULL);
   PRO_FXGL_COMPUTE_C07001('13307000000',NULL,NULL);

END;
/
