CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W40103
/*
 * 报告期内供应商大于等于20个且增幅达50%以上。
 * ZB_VAL：是1，否0
 */
(
  P_BGQID   IN NUMBER,
  P_JQID    IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  VAL1         NUMBER(18,2);    --参数1
  VAL2         NUMBER(18,2);    --参数2
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40103_GHQY_SL';
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL2
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W40103_GHQY_SL_HB';

    SELECT T.TS_GHS_NUM
      INTO V_THIS_DATA
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_BGQID;

    SELECT T.TS_GHS_NUM
      INTO V_LAST_DATA
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU T
     WHERE T.BGQID=P_JQID;

    V_PARAMS := '[d]报告期供应商数量=' || V_THIS_DATA || '|基期供应商数量=' || V_LAST_DATA;
    IF V_THIS_DATA <= 0 AND V_LAST_DATA<=0 THEN
      V_ZB_VAL := NULL;
    ELSIF V_THIS_DATA>=VAL1 AND V_THIS_DATA>=VAL2*V_LAST_DATA THEN
      V_ZB_VAL:=1;
    ELSE
      V_ZB_VAL:=0;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40103' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W40103',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W40103';
  END IF;
  COMMIT;

  RETURN;
END;
/
