CREATE OR REPLACE PROCEDURE PRO_DEAL_JCFX_DATA_BGDMX
AS
  V_BEGINDATE      DATE;
  V_TSSWJG_DM      VARCHAR2(11);
  V_CKSPTSSPLX_DM  CHAR(1);
  V_TSL            NUMBER(18,2);
  V_JGFSTSLX_DM    CHAR(1);
  V_HYDXZQH_DM     CHAR(4);
  LN_ROWS          NUMBER(10);
  LN_REC           NUMBER(10);
  LN_UNIT          NUMBER(10);
BEGIN
  SELECT TRUNC(MAX(T.SJGXSJ))
    INTO V_BEGINDATE
    FROM JCFX_DATA_BGDMX T;
  
  SELECT COUNT(1)
    INTO LN_ROWS
    FROM CKTS_WBSJ_HG_BGD T
   WHERE T.SJTB_SJ>=V_BEGINDATE;

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_DEAL_JCFX_DATA_BGDMX 开始运行，记录总数：' || LN_ROWS);
  COMMIT;
  
  --增量用数据更新时间
  LN_REC :=0;
  LN_UNIT:=0;
  FOR CUR_BGD IN (SELECT T.UUID,T.TSSWJG_DM_1,T.DJXH,T.CKBGDH,T.CKNY,T.CKRQ_1,T.CKSP_DM,
                         T.HGGQKA_DM,T.MYGDQSZ_DM,T.JGFS_DM,T.HZDWDQ_DM,
                         T.CKSL,T.MYLAJ,T.RMBLAJ,T.TSSBSL,T.DLSBSL,T.TYSL,
                         CASE WHEN T.TSSBSL+T.DLSBSL+T.TYSL>T.CKSL+1 THEN T.CKSL / (T.TSSBSL+T.DLSBSL+T.TYSL) ELSE 1 END 
                           * (T.TSSBMYLAJ + T.DLSBMYLAJ + T.TYMYLAJ) AS MYLAJ_YSB,
                         T.SJTB_SJ
                    FROM CKTS_WBSJ_HG_BGD T
                   WHERE T.SJTB_SJ>=V_BEGINDATE)
  LOOP
    BEGIN
      SELECT A.TSSWJG_DM
        INTO V_TSSWJG_DM
        FROM JCFX_DATA_BGDMX A
       WHERE A.DJXH=CUR_BGD.DJXH AND A.CKBGDH=CUR_BGD.CKBGDH;
      
      IF V_TSSWJG_DM=CUR_BGD.TSSWJG_DM_1 THEN
        UPDATE JCFX_DATA_BGDMX A
           SET A.UUID=CUR_BGD.UUID, A.NY=CUR_BGD.CKNY, A.CKRQ=CUR_BGD.CKRQ_1, A.CKSP_DM=CUR_BGD.CKSP_DM, 
               A.HGGQKA_DM=CUR_BGD.HGGQKA_DM, A.MYGDQSZ_DM=CUR_BGD.MYGDQSZ_DM, A.JGFS_DM=CUR_BGD.JGFS_DM, A.HZDWDQ_DM=CUR_BGD.HZDWDQ_DM,
               A.MYLAJ=CUR_BGD.MYLAJ, A.RMBLAJ=CUR_BGD.RMBLAJ, A.MYLAJ_YSB=CUR_BGD.MYLAJ_YSB, A.SJGXSJ=CUR_BGD.SJTB_SJ
         WHERE A.DJXH=CUR_BGD.DJXH AND A.CKBGDH=CUR_BGD.CKBGDH;
        COMMIT;
      ELSE
        DELETE FROM JCFX_DATA_BGDMX A WHERE A.DJXH=CUR_BGD.DJXH AND A.CKBGDH=CUR_BGD.CKBGDH;
        COMMIT;
        INSERT INTO JCFX_DATA_BGDMX(UUID,TSSWJG_DM,DJXH,CKBGDH,NY,CKRQ,CKSP_DM,HGGQKA_DM,MYGDQSZ_DM,JGFS_DM,HZDWDQ_DM,MYLAJ,RMBLAJ,MYLAJ_YSB,SJGXSJ)
             VALUES (CUR_BGD.UUID,CUR_BGD.TSSWJG_DM_1,CUR_BGD.DJXH,CUR_BGD.CKBGDH,CUR_BGD.CKNY,CUR_BGD.CKRQ_1,CUR_BGD.CKSP_DM,CUR_BGD.HGGQKA_DM,CUR_BGD.MYGDQSZ_DM,CUR_BGD.JGFS_DM,CUR_BGD.HZDWDQ_DM,CUR_BGD.MYLAJ,CUR_BGD.RMBLAJ,CUR_BGD.MYLAJ_YSB,CUR_BGD.SJTB_SJ);
        COMMIT;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        --找不到对应的基本商品
        INSERT INTO JCFX_DATA_BGDMX(UUID,TSSWJG_DM,DJXH,CKBGDH,NY,CKRQ,CKSP_DM,HGGQKA_DM,MYGDQSZ_DM,JGFS_DM,HZDWDQ_DM,MYLAJ,RMBLAJ,MYLAJ_YSB,SJGXSJ)
             VALUES (CUR_BGD.UUID,CUR_BGD.TSSWJG_DM_1,CUR_BGD.DJXH,CUR_BGD.CKBGDH,CUR_BGD.CKNY,CUR_BGD.CKRQ_1,CUR_BGD.CKSP_DM,CUR_BGD.HGGQKA_DM,CUR_BGD.MYGDQSZ_DM,CUR_BGD.JGFS_DM,CUR_BGD.HZDWDQ_DM,CUR_BGD.MYLAJ,CUR_BGD.RMBLAJ,CUR_BGD.MYLAJ_YSB,CUR_BGD.SJTB_SJ);
        COMMIT;
    END;

    BEGIN
      SELECT S.XZQH_DM
        INTO V_HYDXZQH_DM
        FROM TL_BJTS.DM_HGHYD S 
       WHERE S.HGHYD_DM=CUR_BGD.HZDWDQ_DM
         AND ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
        --找不到对应的基本商品
        V_HYDXZQH_DM :='0000';
    END;

    BEGIN
      SELECT CKSPTSSPLX_DM,TSL
        INTO V_CKSPTSSPLX_DM, V_TSL
        FROM (SELECT CKSPTSSPLX_DM,TSL
                FROM (SELECT NVL(A.CKSPTSSPLX_DM,'0') AS CKSPTSSPLX_DM,A.TSL
                        FROM TL_BJTS.CKTS_DM_TSLVWK A
                       WHERE A.CKSP_DM LIKE CUR_BGD.CKSP_DM||'%' AND (CUR_BGD.CKRQ_1 BETWEEN A.YXQQ AND A.YXQZ) AND A.JBSPBZ='Y'
                       UNION ALL
                      SELECT NVL(B.CKSPTSSPLX_DM,'0') AS CKSPTSSPLX_DM,B.TSL
                        FROM TL_BJTS.CKTS_DM_TSLVWK B
                       WHERE B.CKSP_DM = SUBSTR(CUR_BGD.CKSP_DM,1,8) AND (CUR_BGD.CKRQ_1 BETWEEN B.YXQQ AND B.YXQZ) AND B.JBSPBZ='Y'
                      ) S
               ORDER BY TSL DESC) R
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
        --找不到对应的基本商品
        V_CKSPTSSPLX_DM :='0';
        V_TSL :=0;
    END;
      
    BEGIN
      SELECT JGFSTSLX_DM
        INTO V_JGFSTSLX_DM
        FROM TL_BJTS.CKTS_DM_HGJGFS A
       WHERE A.JGFS_DM=CUR_BGD.JGFS_DM;
    EXCEPTION
      WHEN OTHERS THEN
        V_JGFSTSLX_DM :='1';
    END;
      
    IF V_CKSPTSSPLX_DM='1' THEN
      UPDATE JCFX_DATA_BGDMX T
         SET T.MYLAJ_ZS=T.MYLAJ, T.HYDXZQH_DM=V_HYDXZQH_DM
       WHERE T.DJXH=CUR_BGD.DJXH AND T.CKBGDH=CUR_BGD.CKBGDH;
    ELSIF V_CKSPTSSPLX_DM='2' THEN
      UPDATE JCFX_DATA_BGDMX T
         SET T.MYLAJ_MS=T.MYLAJ, T.HYDXZQH_DM=V_HYDXZQH_DM
       WHERE T.DJXH=CUR_BGD.DJXH AND T.CKBGDH=CUR_BGD.CKBGDH;
    ELSIF V_JGFSTSLX_DM='0' THEN
      UPDATE JCFX_DATA_BGDMX T
         SET T.MYLAJ_BTS=T.MYLAJ, T.HYDXZQH_DM=V_HYDXZQH_DM
       WHERE T.DJXH=CUR_BGD.DJXH AND T.CKBGDH=CUR_BGD.CKBGDH;
    ELSE
      UPDATE JCFX_DATA_BGDMX T
         SET T.MYLAJ_KTS=T.MYLAJ, T.TSL=V_TSL, T.YGTMSE=ROUND(T.RMBLAJ * V_TSL / 100,2), T.HYDXZQH_DM=V_HYDXZQH_DM
       WHERE T.DJXH=CUR_BGD.DJXH AND T.CKBGDH=CUR_BGD.CKBGDH;
    END IF;
    COMMIT;
  END LOOP;

  INSERT INTO CKTS_LOG_DEALDATA(CZJL) VALUES ('PRO_DEAL_JCFX_DATA_BGDMX 处理结束！');
  COMMIT;

  RETURN;
END;
/
