CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_S40203
/*
 * (底账_农产品进项税额-底账_农产品进项税额[基期])/底账_农产品进项税额[基期])
 */
(
  P_BGQID   IN NUMBER,
  P_JQID    IN NUMBER
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  V_THIS_DATA  NUMBER(18,2);
  V_LAST_DATA  NUMBER(18,2);
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT S.DZ_JXSE_NCP
      INTO V_THIS_DATA
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_BGQID;

    SELECT S.DZ_JXSE_NCP
      INTO V_LAST_DATA
      FROM TL_TSSH.JKGL_DATA_TJ_ZBU S
     WHERE S.BGQID=P_JQID;

    V_PARAMS := '[d]报告期农产品进项税额=' || V_THIS_DATA || '，基期农产品进项税额=' || V_LAST_DATA;
    IF V_LAST_DATA <=1 THEN
      V_ZB_VAL := NULL;
    ELSE
      V_ZB_VAL:= ROUND(100 * (V_THIS_DATA - V_LAST_DATA) / V_LAST_DATA, 2);
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='S40203' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'S40203',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='S40203';
  END IF;
  COMMIT;

  RETURN;
END;
/
