CREATE OR REPLACE PROCEDURE PRO_JKGL_COMPUTE_W30110
/*
 * 同一国别的运输方式偏多
 * ZB_VAL：(国别_运输方式数量>2 and 国别代码 not in ('142'))的国别数量
 */
(
  P_BGQID   IN NUMBER,
  P_SWJGDM  IN VARCHAR
)
AS
  V_ZB_VAL     NUMBER(18,2);
  V_ROWS       NUMBER(10);
  V_BADPOINT   CHAR(1);
  VAL1         NUMBER(18,2);    --参数1
  V_PARAMS     VARCHAR(4000);
BEGIN
  BEGIN
    SELECT NVL(S.VAL_DEF,T.VAL_DEF) / DECODE(T.CSTYPE,'百分比',100, 1)
      INTO VAL1
      FROM JKGL_PZ_ZB_CS T
      LEFT JOIN JKGL_PZ_ZB_CS_SWJG S ON S.CSBM=T.CSBM AND S.SWJG_DM=P_SWJGDM AND S.YXBZ='Y'
     WHERE T.CSBM='ZC_W30110_GB_YSFS_SL';

    V_ZB_VAL := 0;
    FOR CUR_SPDM IN (SELECT T.GB_DM,DM.CKGB_MC,T.YSFSSL
                       FROM TL_TSSH.JKGL_DATA_TJ_ZBU_CKGB T
                       LEFT JOIN TL_TSSH.JCFX_DM_CKGB DM ON DM.CKGB_DM=T.GB_DM
                      WHERE T.BGQID=P_BGQID
                        AND T.YSFSSL>VAL1
                        AND T.GB_DM<>'142')
    LOOP
      V_ZB_VAL := V_ZB_VAL +1;
      IF V_ZB_VAL=1 THEN
        V_PARAMS := '[d]国别代码=' || CUR_SPDM.GB_DM || '（' || CUR_SPDM.CKGB_MC ||'），运输方式数量=' || CUR_SPDM.YSFSSL;
      ELSIF V_ZB_VAL<=20 THEN
        V_PARAMS := V_PARAMS || '|国别代码=' || CUR_SPDM.GB_DM || '（' || CUR_SPDM.CKGB_MC ||'），运输方式数量=' || CUR_SPDM.YSFSSL;
      END IF;
    END LOOP;
    IF V_ZB_VAL>20 THEN
      V_PARAMS := V_PARAMS || '|...';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      V_ZB_VAL := NULL;
  END;

  IF V_ZB_VAL IS NULL THEN
    V_BADPOINT := 'Y';
  ELSE
    V_BADPOINT := 'N';
  END IF;

  SELECT COUNT(1)
    INTO V_ROWS
    FROM JKGL_DATA_TJ_ZB T
   WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30110' AND ROWNUM=1;
  IF V_ROWS=0 THEN
    INSERT INTO JKGL_DATA_TJ_ZB(BGQID,ZB_ID,ZB_VAL,BADPOINT,PARAMS)
           VALUES(P_BGQID,'W30110',V_ZB_VAL,V_BADPOINT,V_PARAMS);
  ELSE
    UPDATE JKGL_DATA_TJ_ZB T
       SET T.ZB_VAL=V_ZB_VAL, T.BADPOINT=V_BADPOINT, T.PARAMS=V_PARAMS, T.UPTIME=SYSDATE
     WHERE T.BGQID=P_BGQID AND T.ZB_ID='W30110';
  END IF;
  COMMIT;

  RETURN;
END;
/
