CREATE OR REPLACE PROCEDURE PRO_DEAL_JCFX_NSR_BLV
AS
  LN_CKBGDFS       NUMBER(10);
  LN_CKMYLAJ       NUMBER(18,2);
  LN_SBMYLAJ       NUMBER(18,2);
  LN_SBTMSE         NUMBER(18,2);
  LN_SBMDE         NUMBER(18,2);
  LC_CKGM          VARCHAR(1);
  LN_MDBLV         NUMBER(10,6);
  LC_MDBLV         VARCHAR(1);
BEGIN
  FOR CUR_NSR IN (SELECT T.DJXH_JS FROM TL_TSSH.GLXT_BB_SHXT_DJXX T)
  LOOP
    SELECT COUNT(DISTINCT SUBSTR(S.CKBGDH,1,18)), NVL(SUM(S.MYLAJ),0)
      INTO LN_CKBGDFS, LN_CKMYLAJ
      FROM TL_TSSH.CKTS_WBSJ_HG_BGD S
     WHERE S.DJXH=CUR_NSR.DJXH_JS
       AND S.CKRQ_1>=ADD_MONTHS(TRUNC(SYSDATE, 'YY'),-12)
       AND S.CKRQ_1< TRUNC(SYSDATE, 'YY');
    
    SELECT NVL(SUM(S.USD_AMT),0), NVL(SUM(S.SB_TS_AMT),0)+ NVL(SUM(S.SB_MD_AMT),0), NVL(SUM(S.SB_MD_AMT),0)
      INTO LN_SBMYLAJ, LN_SBTMSE, LN_SBMDE
      FROM TL_TSSH.GLXT_BB_SHXT_LCXX S 
     WHERE S.DJXH=CUR_NSR.DJXH_JS 
       AND NVL(S.SL_DATE,S.SB_DATE)>=ADD_MONTHS(TRUNC(SYSDATE, 'YY'),-12)
       AND NVL(S.SL_DATE,S.SB_DATE)< TRUNC(SYSDATE, 'YY');
     
    LC_CKGM := CASE WHEN LN_SBMYLAJ>=100000000 THEN 'A' 
                    WHEN LN_SBMYLAJ>=50000000 THEN 'B' 
                    WHEN LN_SBMYLAJ>=10000000 THEN 'C' 
                    WHEN LN_SBMYLAJ>=1000000 THEN 'D' 
                    ELSE 'E' END;
    
    IF LN_SBMDE<=0 THEN
      LN_MDBLV := 0;
    ELSIF LN_SBTMSE<0 THEN
      LN_MDBLV := 100;
    ELSE
      LN_MDBLV := 100 * LN_SBMDE / LN_SBTMSE;
    END IF;
    LC_MDBLV := CASE WHEN LN_MDBLV>=40 THEN 'A' 
                     WHEN LN_MDBLV>=30 THEN 'B' 
                     WHEN LN_MDBLV>=20 THEN 'C' 
                     WHEN LN_MDBLV>=10 THEN 'D' 
                     ELSE 'E' END;
    
    UPDATE TL_TSSH.GLXT_BB_SHXT_DJXX A
       SET A.CK_BGDFS = LN_CKBGDFS,
           A.CK_MYLAJ = LN_CKMYLAJ,
           A.CKGM     = LN_SBMYLAJ,
           A.SB_TMSE  = LN_SBTMSE,
           A.SB_MDE   = LN_SBMDE,
           A.MDBLV    = LN_MDBLV,
           A.CKGM_DM  = LC_CKGM,
           A.MDBLV_DM = LC_MDBLV
     WHERE A.DJXH_JS=CUR_NSR.DJXH_JS;
    COMMIT;
  END LOOP;

  RETURN;
END;
/
