CREATE OR REPLACE PROCEDURE TEMP_PRO_DEAL_MTS_HIS
AS
BEGIN
  FOR CUR_SHXX IN (SELECT T.UUID,T.LCSLID FROM CKTS_LC_SHXX T WHERE T.SBYWB_DM='A0301001' /*AND T.LCJSRQ>=DATE'2023-01-01'*/ AND T.LCJSRQ<DATE'2025-01-01' AND T.SJTB_BZ<>'H')
  LOOP
    INSERT INTO CKTS_SB_MTS_CKMX_HIS
    SELECT * FROM CKTS_SB_MTS_CKMX S WHERE S.LCSLID=CUR_SHXX.LCSLID;
    INSERT INTO CKTS_SB_MTS_JHMX_HIS
    SELECT * FROM CKTS_SB_MTS_JHMX S WHERE S.LCSLID=CUR_SHXX.LCSLID;
    COMMIT;
    DELETE FROM CKTS_SB_MTS_CKMX S WHERE S.LCSLID=CUR_SHXX.LCSLID;
    DELETE FROM CKTS_SB_MTS_JHMX S WHERE S.LCSLID=CUR_SHXX.LCSLID;
    UPDATE CKTS_LC_SHXX S
       SET S.SJTB_BZ='H'
     WHERE S.UUID=CUR_SHXX.UUID;
    COMMIT;
  END LOOP;

  RETURN;
END;
/
