CREATE OR REPLACE PROCEDURE TEMP_PRO_DEAL_SBLCSLID
AS
  LS_LCSLID      VARCHAR2(32);
BEGIN

  FOR CUR_SHXX IN (
    SELECT T.DJXH,T.SSQ FROM TL_TSSH.CKTS_LC_SHXX T 
     WHERE T.SBYWB_DM='A0305001' AND T.ZFBZ IS NULL
     GROUP BY T.DJXH,T.SSQ
    HAVING COUNT(DISTINCT T.LCSLID_SB)>1
  )
  LOOP
    BEGIN
      SELECT NVL(LCSLID_SB,' ')
        INTO LS_LCSLID
        FROM (SELECT A.LCSLID_SB
                FROM CKTS_LC_SBXX A
               WHERE A.SBYWB_DM='A0305001'
                 AND A.DJXH=CUR_SHXX.DJXH AND A.SSQ=CUR_SHXX.SSQ
                 AND A.ZFBZ IS NULL
               ORDER BY NVL(A.HTBZ_1,'N')) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
      LS_LCSLID:=' ';
    END;
    UPDATE TL_TSSH.CKTS_LC_SHXX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.SBYWB_DM='A0305001'
       AND S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ
       AND S.ZFBZ IS NULL;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MDT_CKMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MDT_GJYS S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MDT_YFSJ S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ;
    COMMIT;
    DELETE FROM TL_TSSH.GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SB_YM=CUR_SHXX.SSQ
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SBXX A WHERE A.UUID=S.UUID AND NVL(A.ZFBZ,'N')='N');
    COMMIT;
  END LOOP;

  FOR CUR_SHXX IN (
    SELECT T.DJXH,T.SSQ FROM TL_TSSH.CKTS_LC_SHXX T 
     WHERE T.SBYWB_DM='A0305001' AND T.ZFBZ IS NULL
       AND NOT EXISTS (SELECT 1 FROM TL_TSSH.CKTS_LC_SBXX S WHERE S.LCSLID_SB=T.LCSLID_SB AND S.ZFBZ IS NULL)
  )
  LOOP
    BEGIN
      SELECT NVL(LCSLID_SB,' ')
        INTO LS_LCSLID
        FROM (SELECT A.LCSLID_SB
                FROM CKTS_LC_SBXX A
               WHERE A.SBYWB_DM='A0305001'
                 AND A.DJXH=CUR_SHXX.DJXH AND A.SSQ=CUR_SHXX.SSQ
                 AND A.ZFBZ IS NULL
               ORDER BY NVL(A.HTBZ_1,'N')) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
      LS_LCSLID:=' ';
    END;
    UPDATE TL_TSSH.CKTS_LC_SHXX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.SBYWB_DM='A0305001'
       AND S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ
       AND S.ZFBZ IS NULL;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MDT_CKMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MDT_GJYS S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MDT_YFSJ S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ;
    COMMIT;
    DELETE FROM TL_TSSH.GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SB_YM=CUR_SHXX.SSQ
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SBXX A WHERE A.UUID=S.UUID AND NVL(A.ZFBZ,'N')='N');
    COMMIT;
  END LOOP;

  FOR CUR_SHXX IN (
    SELECT T.DJXH,T.SSQ FROM TL_TSSH.CKTS_LC_SBXX T 
     WHERE T.SBYWB_DM='A0305001' AND T.ZFBZ IS NULL
       AND T.QDSJ>=TRUNC(SYSDATE,'YY')
       AND NOT EXISTS (SELECT 1 FROM TL_TSSH.CKTS_LC_SHXX S WHERE S.LCSLID_SB=T.LCSLID_SB AND S.ZFBZ IS NULL)
  )
  LOOP
    BEGIN
      SELECT NVL(LCSLID_SB,' ')
        INTO LS_LCSLID
        FROM (SELECT A.LCSLID_SB
                FROM CKTS_LC_SBXX A
               WHERE A.SBYWB_DM='A0305001'
                 AND A.DJXH=CUR_SHXX.DJXH AND A.SSQ=CUR_SHXX.SSQ
                 AND A.ZFBZ IS NULL
               ORDER BY NVL(A.HTBZ_1,'N')) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
      LS_LCSLID:=' ';
    END;
    UPDATE TL_TSSH.CKTS_LC_SHXX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.SBYWB_DM='A0305001'
       AND S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ
       AND S.ZFBZ IS NULL;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MDT_CKMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MDT_GJYS S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MDT_YFSJ S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ;
    COMMIT;
    DELETE FROM TL_TSSH.GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SB_YM=CUR_SHXX.SSQ
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SBXX A WHERE A.UUID=S.UUID AND NVL(A.ZFBZ,'N')='N');
    COMMIT;
  END LOOP;

  FOR CUR_SHXX IN (
    SELECT T.DJXH,T.SSQ,T.SBPC FROM TL_TSSH.CKTS_LC_SHXX T 
     WHERE T.SBYWB_DM='A0301001' AND T.ZFBZ IS NULL
     GROUP BY T.DJXH,T.SSQ,T.SBPC
    HAVING COUNT(DISTINCT T.LCSLID_SB)>1
  )
  LOOP
    BEGIN
      SELECT NVL(LCSLID_SB,' ')
        INTO LS_LCSLID
        FROM (SELECT A.LCSLID_SB
                FROM CKTS_LC_SBXX A
               WHERE A.SBYWB_DM='A0301001'
                 AND A.DJXH=CUR_SHXX.DJXH AND A.SSQ=CUR_SHXX.SSQ AND A.SBPC=CUR_SHXX.SBPC
                 AND A.ZFBZ IS NULL
               ORDER BY NVL(A.HTBZ_1,'N')) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
      LS_LCSLID:=' ';
    END;
    UPDATE TL_TSSH.CKTS_LC_SHXX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.SBYWB_DM='A0301001'
       AND S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC
       AND S.ZFBZ IS NULL;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MTS_CKMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MTS_JHMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MTS_YSFW S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    DELETE FROM TL_TSSH.GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SB_YM=CUR_SHXX.SSQ AND S.SB_PC=CUR_SHXX.SBPC
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SBXX A WHERE A.UUID=S.UUID AND NVL(A.ZFBZ,'N')='N');
    COMMIT;
  END LOOP;
  FOR CUR_SHXX IN (
    SELECT T.DJXH,T.SSQ,T.SBPC FROM TL_TSSH.CKTS_LC_SHXX T 
     WHERE T.SBYWB_DM='A0301001' AND T.ZFBZ IS NULL
       AND NOT EXISTS (SELECT 1 FROM TL_TSSH.CKTS_LC_SBXX S WHERE S.LCSLID_SB=T.LCSLID_SB AND S.ZFBZ IS NULL)
  )
  LOOP
    BEGIN
      SELECT NVL(LCSLID_SB,' ')
        INTO LS_LCSLID
        FROM (SELECT A.LCSLID_SB
                FROM CKTS_LC_SBXX A
               WHERE A.SBYWB_DM='A0301001'
                 AND A.DJXH=CUR_SHXX.DJXH AND A.SSQ=CUR_SHXX.SSQ AND A.SBPC=CUR_SHXX.SBPC
                 AND A.ZFBZ IS NULL
               ORDER BY NVL(A.HTBZ_1,'N')) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
      LS_LCSLID:=' ';
    END;
    UPDATE TL_TSSH.CKTS_LC_SHXX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.SBYWB_DM='A0301001'
       AND S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC
       AND S.ZFBZ IS NULL;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MTS_CKMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MTS_JHMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MTS_YSFW S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    DELETE FROM TL_TSSH.GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SB_YM=CUR_SHXX.SSQ AND S.SB_PC=CUR_SHXX.SBPC
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SBXX A WHERE A.UUID=S.UUID AND NVL(A.ZFBZ,'N')='N');
    COMMIT;
  END LOOP;
  FOR CUR_SHXX IN (
    SELECT T.DJXH,T.SSQ,T.SBPC FROM TL_TSSH.CKTS_LC_SBXX T 
     WHERE T.SBYWB_DM='A0301001' AND T.ZFBZ IS NULL
       AND T.QDSJ>=TRUNC(SYSDATE,'YY')
       AND NOT EXISTS (SELECT 1 FROM TL_TSSH.CKTS_LC_SHXX S WHERE S.LCSLID_SB=T.LCSLID_SB AND S.ZFBZ IS NULL)
  )
  LOOP
    BEGIN
      SELECT NVL(LCSLID_SB,' ')
        INTO LS_LCSLID
        FROM (SELECT A.LCSLID_SB
                FROM CKTS_LC_SBXX A
               WHERE A.SBYWB_DM='A0301001'
                 AND A.DJXH=CUR_SHXX.DJXH AND A.SSQ=CUR_SHXX.SSQ AND A.SBPC=CUR_SHXX.SBPC
                 AND A.ZFBZ IS NULL
               ORDER BY NVL(A.HTBZ_1,'N')) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
      LS_LCSLID:=' ';
    END;
    UPDATE TL_TSSH.CKTS_LC_SHXX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.SBYWB_DM='A0301001'
       AND S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC
       AND S.ZFBZ IS NULL;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MTS_CKMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MTS_JHMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_MTS_YSFW S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    DELETE FROM TL_TSSH.GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SB_YM=CUR_SHXX.SSQ AND S.SB_PC=CUR_SHXX.SBPC
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SBXX A WHERE A.UUID=S.UUID AND NVL(A.ZFBZ,'N')='N');
    COMMIT;
  END LOOP;

  FOR CUR_SHXX IN (
    SELECT T.DJXH,T.SSQ,T.SBPC FROM TL_TSSH.CKTS_LC_SHXX T 
     WHERE T.SBYWB_DM='A0310001' AND T.ZFBZ IS NULL
     GROUP BY T.DJXH,T.SSQ,T.SBPC
    HAVING COUNT(DISTINCT T.LCSLID_SB)>1
  )
  LOOP
    BEGIN
      SELECT NVL(LCSLID_SB,' ')
        INTO LS_LCSLID
        FROM (SELECT A.LCSLID_SB
                FROM CKTS_LC_SBXX A
               WHERE A.SBYWB_DM='A0310001'
                 AND A.DJXH=CUR_SHXX.DJXH AND A.SSQ=CUR_SHXX.SSQ AND A.SBPC=CUR_SHXX.SBPC
                 AND A.ZFBZ IS NULL
               ORDER BY NVL(A.HTBZ_1,'N')) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
      LS_LCSLID:=' ';
    END;
    UPDATE TL_TSSH.CKTS_LC_SHXX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.SBYWB_DM='A0310001'
       AND S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC
       AND S.ZFBZ IS NULL;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_WZF_CKMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    DELETE FROM TL_TSSH.GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SB_YM=CUR_SHXX.SSQ AND S.SB_PC=CUR_SHXX.SBPC
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SBXX A WHERE A.UUID=S.UUID AND NVL(A.ZFBZ,'N')='N');
    COMMIT;
  END LOOP;
  FOR CUR_SHXX IN (
    SELECT T.DJXH,T.SSQ,T.SBPC FROM TL_TSSH.CKTS_LC_SHXX T 
     WHERE T.SBYWB_DM='A0310001' AND T.ZFBZ IS NULL
       AND NOT EXISTS (SELECT 1 FROM TL_TSSH.CKTS_LC_SBXX S WHERE S.LCSLID_SB=T.LCSLID_SB AND S.ZFBZ IS NULL)
  )
  LOOP
    BEGIN
      SELECT NVL(LCSLID_SB,' ')
        INTO LS_LCSLID
        FROM (SELECT A.LCSLID_SB
                FROM CKTS_LC_SBXX A
               WHERE A.SBYWB_DM='A0310001'
                 AND A.DJXH=CUR_SHXX.DJXH AND A.SSQ=CUR_SHXX.SSQ AND A.SBPC=CUR_SHXX.SBPC
                 AND A.ZFBZ IS NULL
               ORDER BY NVL(A.HTBZ_1,'N')) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
      LS_LCSLID:=' ';
    END;
    UPDATE TL_TSSH.CKTS_LC_SHXX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.SBYWB_DM='A0310001'
       AND S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC
       AND S.ZFBZ IS NULL;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_WZF_CKMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    DELETE FROM TL_TSSH.GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SB_YM=CUR_SHXX.SSQ AND S.SB_PC=CUR_SHXX.SBPC
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SBXX A WHERE A.UUID=S.UUID AND NVL(A.ZFBZ,'N')='N');
    COMMIT;
  END LOOP;
  FOR CUR_SHXX IN (
    SELECT T.DJXH,T.SSQ,T.SBPC FROM TL_TSSH.CKTS_LC_SBXX T 
     WHERE T.SBYWB_DM='A0310001' AND T.ZFBZ IS NULL
       AND T.QDSJ>=TRUNC(SYSDATE,'YY')
       AND NOT EXISTS (SELECT 1 FROM TL_TSSH.CKTS_LC_SHXX S WHERE S.LCSLID_SB=T.LCSLID_SB AND S.ZFBZ IS NULL)
  )
  LOOP
    BEGIN
      SELECT NVL(LCSLID_SB,' ')
        INTO LS_LCSLID
        FROM (SELECT A.LCSLID_SB
                FROM CKTS_LC_SBXX A
               WHERE A.SBYWB_DM='A0310001'
                 AND A.DJXH=CUR_SHXX.DJXH AND A.SSQ=CUR_SHXX.SSQ AND A.SBPC=CUR_SHXX.SBPC
                 AND A.ZFBZ IS NULL
               ORDER BY NVL(A.HTBZ_1,'N')) TT
       WHERE ROWNUM=1;
    EXCEPTION
      WHEN OTHERS THEN
      LS_LCSLID:=' ';
    END;
    UPDATE TL_TSSH.CKTS_LC_SHXX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.SBYWB_DM='A0310001'
       AND S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC
       AND S.ZFBZ IS NULL;
    COMMIT;
    UPDATE TL_TSSH.CKTS_SB_WZF_CKMX S
       SET S.LCSLID_SB=LS_LCSLID
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SSQ=CUR_SHXX.SSQ AND S.SBPC=CUR_SHXX.SBPC;
    COMMIT;
    DELETE FROM TL_TSSH.GLXT_BB_SHXT_LCXX S
     WHERE S.DJXH=CUR_SHXX.DJXH AND S.SB_YM=CUR_SHXX.SSQ AND S.SB_PC=CUR_SHXX.SBPC
       AND NOT EXISTS (SELECT 1 FROM CKTS_LC_SBXX A WHERE A.UUID=S.UUID AND NVL(A.ZFBZ,'N')='N');
    COMMIT;
  END LOOP;

  RETURN;
END;
/
