CREATE OR REPLACE PROCEDURE TEMP_PRO_JKGL_AFTER_ETL
/*
 * 检查并修复ETL发生错误时，部分数据未抽取标记已打的问题
 */
AS
  V_ROWS            NUMBER(10);  -- 待更新表中是否存在目标记录
BEGIN
  -- ZZS_ZT
  BEGIN
    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.ZZS_ZT='Y' AND S.ZZS_XSE_QB IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.ZZS_ZT='N'
       WHERE T.SXZT='3' AND T.ZZS_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.ZZS_XSE_QB IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.ZZS_ZT='Y' AND S.ZZS_MDTBDDKJXSE IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.ZZS_ZT='N'
       WHERE T.SXZT='3' AND T.ZZS_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.ZZS_MDTBDDKJXSE IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.ZZS_ZT='Y' AND S.ZC_GDZC_QC IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.ZZS_ZT='N'
       WHERE T.SXZT='3' AND T.ZZS_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.ZC_GDZC_QC IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.ZZS_ZT='Y' AND S.ZC_GDZC_QM IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.ZZS_ZT='N'
       WHERE T.SXZT='3' AND T.ZZS_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.ZC_GDZC_QM IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.ZZS_ZT='Y' AND S.LR_YYSR IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.ZZS_ZT='N'
       WHERE T.SXZT='3' AND T.ZZS_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.LR_YYSR IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.ZZS_ZT='Y' AND S.TS_JHFP_FS_DG IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.ZZS_ZT='N'
       WHERE T.SXZT='3' AND T.ZZS_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.TS_JHFP_FS_DG IS NULL);
      COMMIT;
    END IF;
  END;
  -- DZDZ_ZT
  BEGIN
    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZDZ_ZT='Y' AND S.DZ_JXFS_ZY IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZDZ_ZT='N'
       WHERE T.SXZT='3' AND T.DZDZ_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_JXFS_ZY IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZDZ_ZT='Y' AND S.DZ_JXFS_PT IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZDZ_ZT='N'
       WHERE T.SXZT='3' AND T.DZDZ_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_JXFS_PT IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZDZ_ZT='Y' AND S.DZ_JXFS_DGKJ IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZDZ_ZT='N'
       WHERE T.SXZT='3' AND T.DZDZ_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_JXFS_DGKJ IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZDZ_ZT='Y' AND S.DZ_JXSE_JKS IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZDZ_ZT='N'
       WHERE T.SXZT='3' AND T.DZDZ_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_JXSE_JKS IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZDZ_ZT='Y' AND S.DZ_JXJE_SN IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZDZ_ZT='N'
       WHERE T.SXZT='3' AND T.DZDZ_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_JXJE_SN IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZDZ_ZT='Y' AND S.DZ_JXJE_SW IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZDZ_ZT='N'
       WHERE T.SXZT='3' AND T.DZDZ_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_JXJE_SW IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZDZ_ZT='Y' AND S.DZ_XXFS_ZY IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZDZ_ZT='N'
       WHERE T.SXZT='3' AND T.DZDZ_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_XXFS_ZY IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZDZ_ZT='Y' AND S.DZ_XXFS_PT IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZDZ_ZT='N'
       WHERE T.SXZT='3' AND T.DZDZ_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_XXFS_PT IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZDZ_ZT='Y' AND S.DZ_XXFS_CK IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZDZ_ZT='N'
       WHERE T.SXZT='3' AND T.DZDZ_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_XXFS_CK IS NULL);
      COMMIT;
    END IF;
  END;
  -- DZSP_ZT
  BEGIN
    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZSP_ZT='Y' AND S.DZ_DFJE_SR IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZSP_ZT='N'
       WHERE T.SXZT='3' AND T.DZSP_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_DFJE_SR IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZSP_ZT='Y' AND S.DZ_DFJE_ZC IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZSP_ZT='N'
       WHERE T.SXZT='3' AND T.DZSP_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_DFJE_ZC IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZSP_ZT='Y' AND S.DZ_WTJG IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZSP_ZT='N'
       WHERE T.SXZT='3' AND T.DZSP_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_WTJG IS NULL);
      COMMIT;
    END IF;

    SELECT COUNT(1)
      INTO V_ROWS
      FROM TL_TSSH.JKGL_DATA_BGQ T
     INNER JOIN JKGL_DATA_TJ_ZBU S ON S.BGQID=T.BGQID
     WHERE T.SXZT='3' AND T.DZSP_ZT='Y' AND S.DZ_YFJE IS NULL;
    IF V_ROWS>0 THEN
      UPDATE JKGL_DATA_BGQ T
         SET T.DZSP_ZT='N'
       WHERE T.SXZT='3' AND T.DZSP_ZT='Y'
         AND EXISTS (SELECT 1 FROM JKGL_DATA_TJ_ZBU S WHERE S.BGQID=T.BGQID AND S.DZ_YFJE IS NULL);
      COMMIT;
    END IF;
  END;

  RETURN;
END;
/
